### ISSUE TITLE
Youtube albums and concerts scrobbling

### ISSUE THREAD

**Issue by ghost** [web-scrobbler/web-scrobbler#122]
On youtube it's common practice to upload whole album, or a live convert. It's very useful feature. But it can't be scrobbled by every song.

Often such videos have track list in description. Often it's easy to parse:
(Here are examples)

```
04. Track title - 08:15
...
16 - Track title (23:42)
...
or without track number
03:14 Track Title
```

Will be great tool if scrobbler will parse this list and scrobbles song if it's time for it.
(is it possible to get current position of video on youtube - I don't really know)

**Comment by galeksandrp** [comment]
*Easy to parse*, hah. #755

**Comment by jaccarmac** [comment]
I wonder if it would be worth generalizing this feature request and #1834. That is, decouple the idea of YouTube videos from "tracks", and introduce a way to delay or batch-edit "tracks" more-or-less independently of the status of video playback?

**Comment by killd0zr** [comment]
So, are there any chances to start working on this fix in nearest time?

**Comment by alexesprit** [comment]
This issue was opened 6 years ago, and it's still opened. So, I doubt it will be resolved in near future. A lot of work should be done to get this feature worked properly.

**Comment by killd0zr** [comment]
> This issue was opened 6 years ago, and it's still opened. So, I doubt it will be resolved in near future. A lot of work should be done to get this feature worked properly.

Maybe we could collect some funds and hire a freelancer to get this work done?

**Comment by killd0zr** [comment]
How much would it cost?

**Comment by inverse** [comment]
Cost is relative. Best bet is to wait for someone who is passionate enough about the problem and is able to solve it.

Like Alexey said it's not an easy change thoiugh.

**Comment by lacivert** [comment]
BTW, even though someone implements this feature, there is no guarantee that Youtube would change the way about the album info. This may go in vain.

**Comment by killd0zr** [comment]
> Cost is relative. Best bet is to wait for someone who is passionate enough about the problem and is able to solve it.
> 
> Like Alexey said it's not an easy change thoiugh.

Waiting can last for many years :(

**Comment by inverse** [comment]
> BTW, even though someone implements this feature, there is no guarantee that Youtube would change the way about the album info. This may go in vain.

It will be like any "scraper" volatile to change.

**Comment by killd0zr** [comment]
> BTW, even though someone implements this feature, there is no guarantee that Youtube would change the way about the album info. This may go in vain.

But we are not talking about Youtube's album info, right? It is about text tracklist in description, and it is written by user, nothing is going to change in this format, often it is like [02:34] Artist - Track name

**Comment by eronisko** [comment]
A good start might be to collect different video descriptions, so that we have an idea of what formats there are out there. YouTube has an [API](https://developers.google.com/youtube/v3/docs/videos) so we might even be able to do this programatically.

**Comment by killd0zr** [comment]
00:00 Artist - Track name 1
02:38 Artist - Track name 2

[00:00] Artist - Track name 1
[02:38] Artist - Track name 2

01 00:00 Artist - Track name 1
02 02:38 Artist - Track name 2

01. 00:00 Artist - Track name 1
02. 02:38 Artist - Track name 2

00:00 Artist - Track name 1
https://soundcloud.com/link1
02:38 Artist - Track name 2
https://soundcloud.com/link2

**Comment by killd0zr** [comment]
These are different types I've seen

**Comment by buremba** [comment]
Unless Youtube implements a feature that lets people write the tracks in a set, it would not be an easy task for sure. I'm also not sure if it worth...

**Comment by lc-guy** [comment]
> 
> 
> Unless Youtube implements a feature that lets people write the tracks in a set, it would not be an easy task for sure. I'm also not sure if it worth...

This is actually a thing now -- eg. https://www.youtube.com/watch?v=83wiw5C9z-k

**Comment by alexesprit** [comment]
@lc-guy that looks interesting. How does it work, by the way?

**Comment by buremba** [comment]
@alexesprit I believe that Youtube has an internal database (similar to Shazam but it probably works on videos too) that lets them check if there's any copyright infringement issue when a user uploads a new video. It looks like that used that feature to add copyright information to the video page.

**Comment by alexesprit** [comment]
Seems like it just parses a video description and extracts tracks from it.

![image](https://user-images.githubusercontent.com/1119267/79009109-77348500-7b67-11ea-946c-c031a318d7da.png)

**Comment by buremba** [comment]
@alexesprit are you using an extension for the player? :/ I don't see these indicators in the player, I assumed that @lc-guy was inferring the `Music in this video` part as seen in this picture:

![image](https://user-images.githubusercontent.com/82745/79013370-45282080-7b71-11ea-9d91-28cc36de9a01.png)

**Comment by jaccarmac** [comment]
@buremba I see the new UI without extensions, it's possible that it's a new feature that Google is A/B testing.

**Comment by buremba** [comment]
That looks really cool. 👌Hope Youtube won't try to compete with Soundcloud though. 😬

**Comment by stephanebruckert** [comment]
I don't that's new! The tracklist was added in the video description by the uploader, and the "Music in this video" don't have timestamps which make it difficult to scrobble

**Comment by alexesprit** [comment]
@buremba no, I don't use extensions for YouTube. The "Music in this video" category isn't usable w/o timestamps. Seems like @jaccarmac is right about A/B testing.

**Comment by alexesprit** [comment]
I'm closing this one, since the basic support for chapters was added.
