### ISSUE TITLE
Use YouTube video thumbnail as track art

### ISSUE THREAD

**Issue by ali-essam** [web-scrobbler/web-scrobbler#1221]
I noticed YouTube connector doesn't try to parse track art in anyway and leaves it to song metadata (which is not available sometimes). I was thinking it might be a nice idea to use YouTube thumbnail as a fallback strategy, but the logic of `song.getTrackArt` seems to do the opposite (which is fine in most cases).

So the 2 points I want to discuss are:
- Is using YouTube thumbnail a good idea?
- If so, should it be fallback? and how should it be implemented to allow such strategy?

```
Connector.getTrackArt = function () {
	var id = $('meta[itemprop="videoId"]').attr('content');
	return 'https://img.youtube.com/vi/' + id + '/mqdefault.jpg'
}
```

![youtube thumb art](https://cloud.githubusercontent.com/assets/5252681/21769492/ab38342e-d687-11e6-846c-d2cc0ee7464d.png)

**Comment by alexesprit** [comment]
> Is using YouTube thumbnail a good idea?

Sounds pretty good, but thumbnails should be squared somehow (but I'm not sure if it's possible w/o external services).

> If so, should it be fallback? and how should it be implemented to allow such strategy?

 Yes, the thumbnail as fallback is better than as a primary source. Can't say anything about implementation right now, that's not easy question.

**Comment by ali-essam** [comment]
> Sounds pretty good, but thumbnails should be squared somehow (but I'm not sure if it's possible w/o external services).

I couldn't find an easy way that doesn't depend on external service, but I found this cool free image resizing service [rsz.io](https://rsz.io), combined with YouTube API you get this.

```javascript
Connector.getTrackArt = function () {
	var id = $('meta[itemprop="videoId"]').attr('content');
	return 'http://img.youtube.com.rsz.io/vi/'+ id + '/mqdefault.jpg?height=100&width=100&anchor=center&mode=crop'
}
```

![youtube thumb square](https://cloud.githubusercontent.com/assets/5252681/21775999/0f43f214-d6a1-11e6-84d3-7895a6a08331.png)

**Comment by alexesprit** [comment]
That's awesome!

I don't think that dependency of external services such as this one is a bad way, because it doesn't require authentication, and it is pretty easy to use.

**Comment by ali-essam** [comment]
As for how it might be implemented, I have two ideas in mind:

1. Add another boolean property to `Connector` that would indicate whether the parsed track art should be prioritized or not, and since song has access to connector object it can take the decision.
2. Change `getTrackArt` signature so that in addition to the url it returns a boolean to indicate so (with backward compatibility for other connectors). This way connectors can decide per request. Though you would still have to add some property as [1] for default selector.

I'm not really familiar with the core code, but [1] seems straightforward though might be a bit hackish, and I'm not really sure about how easy/hard is [2].

Let me know if you have any other ideas in mind too.

**Comment by bgbrandongomez** [comment]
I do not know how possible it is to manipulate images just with Javascript, but, the PWA known as https://smaller-pictures.appspot.com/ seems to be able to recompress the images without an external service.

**Comment by alexesprit** [comment]
An example of implementation is https://github.com/alexesprit/web-scrobbler/tree/trackart-priority.

**Comment by inverse** [comment]
@alexesprit What does the priority mean?

**Comment by alexesprit** [comment]
@inverse it's a property that allows to force the use of trackarts from external sources (Last.fm, coverart archive etc) even if a parsed trackart is defined. In current implementaion parsed trackarts are always preferrable.

**Comment by alexesprit** [comment]
Updated the branch; renamed `trackArtPriority` to `trackArtProvider` property which can takes two values: 'core' and 'corrector'. Not sure if the code looks easier to understand.

**Comment by inverse** [comment]
Having priority was a bit confusing - I think the new naming makes sense if it's clearly documented. What does `corrector` mean though? 

Is the idea to simply the flow for common patterns of extracting the track art?

**Comment by alexesprit** [comment]
> What does corrector mean though?

Oops, that was a typo. 'connector', of course.

**Comment by alexesprit** [comment]
I also noticed rsz.io sometimes down. That's bad. :(

**Comment by alexesprit** [comment]
I realized it is not a good itea to use external services to crop images. About 40% of scrobbles are from YouTube. I'm not sure if services won't down because of lot of requests.

Adding a library to crop images is total overkill for such a small feature.
