### ISSUE TITLE
Scrobbling of embedded audio/video

### ISSUE THREAD

**Issue by marsjaninzmarsa** [web-scrobbler/web-scrobbler#1357]
Got into https://daily.bandcamp.com/2017/07/07/guerilla-toss-gt-ultra-review/

### Expected Behavior
Bandcamp scrobbling working

### Current Behavior
Bandcamp player not detected

### Context
Scrobbling from embedded players not supported https://github.com/david-sabata/web-scrobbler/issues/993#issuecomment-238107197 and not planned https://github.com/david-sabata/web-scrobbler/issues/106#issuecomment-59698831. Due to limitations of WebExtensions, iframes cannot be targeted for Content Script injection without targeting parent frame, means without targeting every frame (cause every could have possible embed). And "parsing the content of every site" sounds like overkill.

### Possible Solution
Declare [catch all](https://stackoverflow.com/a/19288288) with Content Script looking for applicable connectors against `location.href` for and unloading itself right after.
If above would cause too much performance overhead, we can provide default `pageAction` handler, manually triggering script injection. Both ofc optable.

**Comment by inverse** [comment]
We will need to update the BC connector to handle these pages

**Comment by marsjaninzmarsa** [comment]
Bandcamp ofc was only an example - ofc maybe developing BC specific workaround (embeds, but with same origin) would be easiest than generic embeds support, but it's needed, it's recurring (since 2012), and it's doable, I think. I've started code digging, but before thinking about PRs and stuff I need your (plural _you_) opinion - am I right? I'm WebExt newbie, currently finishing up first own extension (ok, forked, abandoned one, but rewrited in 90%), so I may be wrong. Counting on your experience, cheers and many successful scrobbles, Kuba. 🎵🎵🎵

**Comment by alexesprit** [comment]
I suggest to rewrite the BC connector in a following way:
```js
'use strict';

setupConnector();

function setupConnector() {
    if (isEmbedPlayer()) {
        setupEmbedPlayer();
    } else {
        setupDefaultPlayer();
    }
}

function setupEmbedPlayer() {
    // bindings for embed player
}

function setupDefaultPlayer() {
    // current code of BC connector
}
```

**Comment by alexesprit** [comment]
Example of implementation: https://github.com/alexesprit/web-scrobbler/tree/bc-embed
I don't listen to music on Bandcamp, so I'm not sure I didn't broke anything else. I checked some random pages on Bandcamp, had no regressions.
