### ISSUE TITLE
Notify of native scrobbling

### ISSUE THREAD

**Issue by alexesprit** [web-scrobbler/web-scrobbler#1375]
Some websites have own implementation of Last.fm scrobbling. The extension should notify of such feature. Optionally, it should provide a simple way to disable connectors to prevent double scrobbling.

I suggest to show a notification with informational message when an user visits the website first time. Users can disable connectors for the website by clicking on the notification.

Extracted from #630.

**Comment by marsjaninzmarsa** [comment]
Maybe (optable) throttling first scrobble to check, if there are scrobbling active on sidechannel? Some services (Spofify...) menages scrobbling per device, and not all devices are enabled for scrobbling at all...

**Comment by jaccarmac** [comment]
This seems like something which could be checked using the Last.fm API in addition to a white-(or black?)-list of sites.
