### ISSUE TITLE
No longer scrobbling from Amazon Alexa website on Chrome

### ISSUE THREAD

**Issue by chrisuab** [web-scrobbler/web-scrobbler#1381]
On Google Chrome, the Last.fm scrobbler icon turns red on the Amazon Alexa website (http://alexa.amazon.com/spa/index.html#music/services) but it doesn't see any of the songs playing from their playlists like it used to.

**Comment by chrisuab** [comment]
Nevermind.  It will scrobble if you maximize the song playing (showing the cover art).  I thought it used to scrobble when it was minimized but maybe not.

**Comment by chrisuab** [comment]
It will scrobble the first song, but won't scrobble any of the subsequent songs unless I refresh.

**Comment by werewegian** [comment]
I'm getting this for the last few days. It will only scrobble a few songs an hour. It announces the song is playing and last.fm shows it as playing but when it moves on to the next track, the scrobble is not saved.

My Alexa player's page is

http://alexa.amazon.co.uk/spa/index.html#player

**Comment by Furchin** [comment]
I had the same issue, but refreshing (and logging in to last.fm and granting permissions) fixed the issues.
