### ISSUE TITLE
proper dependency management

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#1390]
Should we manage our dependencies properly via npm?

The main drawbacks I can see are:

1. Increase the barrier to contribution
2. make it slower to share builds, unless we setup some CI process to create builds (might be nice to have)

**Comment by inverse** [comment]
Could we leverage travis to create builds?

**Comment by alexesprit** [comment]
Propably. Travis CI allows to deploy packages: https://docs.travis-ci.com/user/deployment

**Comment by inverse** [comment]
Could work, but I guess we'd need somewhere to drop builds. 

What's your stance on npm for proper dependency management?

**Comment by alexesprit** [comment]
> What's your stance on npm for proper dependency management?

I have no strong opinion. If it won't make development harder, I'm not against these changes.

I suppose to get this worked we should use webpack, right? AFAIK there's no native way to use npm modules in ES5/ES6. Anyway, firstly, we should configure Travis to build packages; otherwise testing builds from master will become much harder for users.

**Comment by inverse** [comment]
It will increase the barrier to entry that's for sure. considering we only use npm for the linting/testing pipeline which is done automatically by travis and not mandatory for new connectors.

As for your question - I am not sure. I don't use that much JS in my day to day working these days :(

**Comment by alexesprit** [comment]
Just started playing with webpack. Have no idea what to do with content scripts & connectors. They use jQuery too, but now jQuery is installed via npm.

The only solution I see is use webpack in content scripts too, but I have no idea how to combine content modules and connectors.

Yes, we can still use a copy of jQuery in `vendor` directory, but I don't like this way.

**Comment by OwnageIsMagic** [comment]
git submodules?

**Comment by inverse** [comment]
What are you trying to achieve? One module per page, e.g. one for options etc? I've got limited webpack experience and only really used it with `symfony/encore`

**Comment by alexesprit** [comment]
I get jQuery worked for background scripts using `require` function. But I want to use jQuery from npm in content scripts too using the same way. The problem is everything wrapped by webpack is not accessible in global namespace (`window` object). So, the connectors won't access `Connector` object they extend.

**Comment by alexesprit** [comment]
> git submodules?

Well, it's not a solution, because we still have two package sources (the one is npm, and the second source is git repositories). @inverse suggests npm as a single package source.

**Comment by alexesprit** [comment]
I was playing with `webpack` again, and noticed slower perfomance of popup windows.

Alternative solution is to copy dependencies from `node_modules` directory.

> Could we leverage travis to create builds?

GitHub Actions allow to upload artifacts per each workflow run.

**Comment by inverse** [comment]
Where does GH publish the artifact for builds on a branch for example? I guess you could plug anything in.

**Comment by alexesprit** [comment]
@inverse https://github.com/actions/upload-artifact

> In the top right corner of a workflow run, once the run is over, if you used this action, there will be a Artifacts dropdown which you can download items from. Here's a screenshot of what it looks like
> ![Artifacts Screenshot](https://user-images.githubusercontent.com/3685876/62906968-1b4aff80-bd3f-11e9-8815-9058eb05692a.png)

The disadvantage of the alternative way I suggested is dependencies are missing for tests.

**Comment by alexesprit** [comment]
Probably, the best solution so far: https://github.com/alexesprit/web-scrobbler/commits/feature/npm

> A script copies dependencies to `vendor` directory after running `npm install`; a new workflow uploads the build extension as an artifact.

**Comment by alexesprit** [comment]
The proper solution: https://github.com/web-scrobbler/web-scrobbler/tree/feature/v3

Uses `webpack` to build the extension. This made possible by removing jQuery dependency.

> I was playing with webpack again, and noticed slower perfomance of popup windows.

UI was rewritten using Vue.js; I see no performance regression.

**Comment by inverse** [comment]
Awesome - I wonder what in particular was happening with webpack that caused it :/
