### ISSUE TITLE
Support for Listenbrainz scroblling

### ISSUE THREAD

**Issue by naught101** [web-scrobbler/web-scrobbler#1394]
It would be great if Web Scrobbler supported scrobbling to [ListenBrainz](https://listenbrainz.org/). Listenbrainz is an open source listen tracker, that allows full access to its' data, and is supported by the Metabrainz foundation.

Listenbrainz is still in Beta, but it has a complete and well documented API.

**Comment by Freso** [comment]
ListenBrainz API: https://listenbrainz.readthedocs.io/

**Comment by marsjaninzmarsa** [comment]
Not sure if worth implementing separate auth flow for their API token, should we [wait for OAuth](https://tickets.metabrainz.org/projects/LB/issues/LB-216)?

**Comment by inverse** [comment]
How does one get the token with the current setup? The documentation mentions setting the Auth header with the token but doesn't really explain how to get this? or is it a case of grabbing it from your user profile?

**Comment by naught101** [comment]
Yep, log in, and go to https://listenbrainz.org/user/info, and it's listed there. It's possible to replace it at any time, too.

**Comment by inverse** [comment]
I guess that could be something to start with until OAuth is implemented.

**Comment by felipemarinho97** [comment]
Hey, any news about the support? I really want to send my music to ListenBrainz and also can help in the development if it's necessary

**Comment by inverse** [comment]
Support coming in #1679
