### ISSUE TITLE
Support PocketCasts web ui?

### ISSUE THREAD

**Issue by ThomasGHenry** [web-scrobbler/web-scrobbler#1419]
Would be nice to scrobble from https://play.pocketcasts.com/web/

### Expected behavior
podcast episodes would scrobble to last.fm as a music track would

### Current behavior
I don't see this happening, assuming by design. 

### Environment
* Browser name and version: Chrome 60.0.3112.113 (Official Build) (64-bit) on MacOS Sierra 10.12.6 (16G29)

**Comment by xyauhideto** [comment]
The player shows only the titles of the podcast and the episode but not the author name. Would you expect the podcast title to be considered as the artist?

**Comment by MarkG76** [comment]
@xyauhideto perhaps the interface has since been updated, but I can see the show title when i play an episode. See screenshot  https://www.dropbox.com/s/xygvjd77qpfapct/Screenshot%20from%202018-08-18%2019-03-33.png?dl=0 

Would be great if this can be supported so I could sync podcasts to last.fm and then to gyrosco.pe 

thank you!

**Comment by goodevilgenius** [comment]
@xyauhideto Generally when scrobbling podcasts, the podcast title is used as the artist name.

E.g., you can see on [my last.fm](https://www.last.fm/user/dan000), the vast majority of those recent artists (Up First, 5 Things, Throughline) are podcasts.

**Comment by goodevilgenius** [comment]
By they way, the URL for the web player is now https://play.pocketcasts.com/podcasts, rather than https://play.pocketcasts.com/web

**Comment by ThomasGHenry** [comment]
I've moved on to castbox myself. I haven't checked whether it's supported. If it's not, feel free to throw that in there while you're at it. 😊

**Comment by inverse** [comment]
@goodevilgenius feel free to contribute - everything helps!

@ThomasGHenry if you want castbox supported please create a new ticket )

**Comment by ThomasGHenry** [comment]
Fair enough! Figured I'd try : )

**Comment by goodevilgenius** [comment]
https://github.com/web-scrobbler/web-scrobbler/pull/2351
