### ISSUE TITLE
Authenticating the scrobbler with libre.fm  

### ISSUE THREAD

**Issue by MartinL0815** [web-scrobbler/web-scrobbler#1421]
### summary

If I try to authenticate the scrobbler for libre.fm, than the displayed information would make me denying access.
The displayed information for the scrobbler is worthless and guarantees no trust:

>![Screenshot of authenticating scrobbler for libre.fm](https://user-images.githubusercontent.com/525700/31220434-b7d18c78-a9c0-11e7-811c-f5a7007f112d.png)

### Expected behavior

I would have expected the scrobbler to identify itself correctly and to have a more informative API key name.

### Environment

* Last.FM Scrobbler 2.0.1
* Google Chrome 61.0.3163.100 (Official Build) (32-bit) on Windows 7 SP2 Pro 64 bit

**Comment by alexesprit** [comment]
The extension uses default Libre.fm API key. Do you know how to obtain proper Libre.fm API key? Because I don't.

**Comment by mattl** [comment]
Any 32 character key is accepted, use something that's vaguely identifying to your project if you can.

**Comment by alexesprit** [comment]
> Any 32 character key is accepted, use something that's vaguely identifying to your project if you can.

Ok, but Libre.fm won't know if this key is assigned to the extension, right?

**Comment by mattl** [comment]
Correct. To know the client you should let us (ie. me and @robmyers) know the three letter code for your client.

**Comment by alexesprit** [comment]
@mattl thanks for information. What is the three letter code you mentioned in your comment?

Btw, 32 char codes for API key and API secret from #1422 can be used.

**Comment by inverse** [comment]
@mattl is there no way to register applications directly on libre?

**Comment by alexesprit** [comment]
Ok, I read [this article](http://git.gnu.io/foocorp/librefm/wikis/Clients) and figured out what is the client code. I suggest to use `wsc` for this project.

**Comment by alexesprit** [comment]
@mattl @robmyers we have added API key and API secret (#1422), and I suggest to use `wsc` code for the extension if it's available, of course. Is anything we can do to resolve this issue?

**Comment by alexesprit** [comment]
Since Libre.fm devs don't respond, I close this issue.
