### ISSUE TITLE
Auto like on lastfm if a person likes a track on scrobbleable service

### ISSUE THREAD

**Issue by bykidi** [web-scrobbler/web-scrobbler#1424]
### Expected behavior
If you like a track, for example, on youtube - it should also like that track on lastfm

### Current behavior
Nothing happens.

**Comment by inverse** [comment]
This sounds like a feature which could post a `v2.toggleLove` event

**Comment by CennoxX** [comment]
Is this open for contributing?

**Comment by bykidi** [comment]
wow... i noticed this suggestion in the notification list and i was like 'oh, that's actually a good idea!'

until i noticed that it is mine

Xd

**Comment by inverse** [comment]
Def something that could be added. Need to hook into the "like" action on the particular page.

**Comment by alexesprit** [comment]
> Is this open for contributing?

Sure. But it requires a lot of work to support this feature on all websites have rating system.
