### ISSUE TITLE
Saved corrections wrong cache match

### ISSUE THREAD

**Issue by OwnageIsMagic** [web-scrobbler/web-scrobbler#1456]
`ElisaDay – The Letter` somehow matched `Infant Annihilator – Decapitation Fornication`, but I can't reproduce this.
_sorry for trashy tracks_

**Comment by alexesprit** [comment]
What does it mean?

**Comment by OwnageIsMagic** [comment]
Sometimes when I listen to new song ext autocorrects it to the one that I manually corrected in the past

**Comment by alexesprit** [comment]
Is this happening on a particular website?

**Comment by OwnageIsMagic** [comment]
vk.com

**Comment by OwnageIsMagic** [comment]
Also it sometimes just stops working
![1gif](https://user-images.githubusercontent.com/10534634/32039342-5fdf765c-ba36-11e7-825e-54af4c0293fb.gif)
As you can see it was scrobling and then something happend
![image](https://user-images.githubusercontent.com/10534634/32039391-95a9a032-ba36-11e7-9b82-53bf3435899c.png)
on this track
![image](https://user-images.githubusercontent.com/10534634/32039455-da70a92c-ba36-11e7-8c31-aa573f4f35e5.png)

**Comment by alexesprit** [comment]
Can't figure out what did you mean by "stops working".

**Comment by alexesprit** [comment]
[How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

**Comment by OwnageIsMagic** [comment]
look at last fm log and playlist. this 2 pics were captured on the same time
 gif shows that skipping to next song doesn't activate ext

**Comment by alexesprit** [comment]
@OwnageIsMagic could you install the extension from the zipball I made in https://github.com/david-sabata/web-scrobbler/issues/1455#issuecomment-339585038 and reproduce the moment when the extension "stops working" again? I've added a workaround that enforces page action visibility, so we can sure the extension works (or it doesn't work).

**Comment by OwnageIsMagic** [comment]
Oh, I just remembered one common thing within wrong corrections
It screws up this way only if manual correction was of unrecognized track(question mark in notification)
ps I can't test right now 
will do when return home

**Comment by OwnageIsMagic** [comment]
log of prev version
content scr
![image](https://user-images.githubusercontent.com/10534634/32076725-9df47334-baa9-11e7-897d-ce50bcae3db3.png)
back https://pastebin.com/qQ6wnXyW

**Comment by OwnageIsMagic** [comment]
вроде поймал что-то
![image](https://user-images.githubusercontent.com/10534634/32081322-5693977c-babd-11e7-889d-56509ffbaa16.png)

**Comment by alexesprit** [comment]
Is this log related to the issue when the extension stops working? If so, it should be extracted into another issue.

I noticed a line in debug log above:
```
Tab 803: Remove controller for VK connector
```
This should happen only when an user closes a tab. Did you close the tab?

**Comment by OwnageIsMagic** [comment]
Yeah, I probably closed another one tab.
Looks there are no log entries regarding this issue.

**Comment by OwnageIsMagic** [comment]
finally find out semi-stable way to reproduce ext breakage
You should modify current playlist (press `Play next` or rearrange tracks) after currently playing track already scrobled.
Worked for me 2 times in a row

**Comment by OwnageIsMagic** [comment]
![image](https://user-images.githubusercontent.com/10534634/34444168-3e665af2-ecdd-11e7-8e0d-d417d9438393.png)
No idea how to reproduce
If I click prev - next track it still matches wrong correction even after page refresh

**Comment by OwnageIsMagic** [comment]
btw why you use crypto function like MD5 for hash generation?

**Comment by alexesprit** [comment]
> btw why you use crypto function like MD5 for hash generation?

Some tracks have no an unique ID (it depends on a website and connector implementation; e.g. VK provides their own IDs), and they can't be saved in to the local cache. In the case of empty unique ID the extension makes it by itself.

> there is a lot of lightweight hashing algorithms

Yes, but MD5 library is already used in this project, so we have less dependencies. And I don't think calculating an internal unique ID slows down the extension.

> And why not just plaintext?

There's no certain reason to not use plain text (I guess you meant the string which is used to make MD5 hash) as ID. Well, I want to have unique IDs as short as possible. IDs like "Artist+Track+Album" looks bad when track has too long artist name or track title. But, technically, plain text can be used.

**Comment by OwnageIsMagic** [comment]
> less dependencies

5 lines vs 185 [md5](https://github.com/web-scrobbler/web-scrobbler/blob/master/vendor/md5.js) :)
```js
function hashFnv32a(str, seed = 0x811c9dc5 ) {
    for (var i = 0, var l = str.length; i < l; i++) {
        hval ^= str.charCodeAt(i);
        hval += (hval << 1) + (hval << 4) + (hval << 7) + (hval << 8) + (hval << 24);
    }
    // Convert to 8 digit hex string
    return ("0000000" + (hval >>> 0).toString(16)).substr(-8);
}
```

**Comment by alexesprit** [comment]
These 185 lines are used in another place too. And `hashFnv32a` function is supposed to be used in a `song` module only. I'm not sure this comparison is corrected.

I'm not against other ways to calculate the unique ID. The reason I would keep MD5 function to calulate the ID is local caches users already have. If we'll use different calculation algorithm, these local caches will become useless.

**Comment by OwnageIsMagic** [comment]
I understand problem about changing it
just wonder why people using crypto functions where they aren't needed
