### ISSUE TITLE
Scrobble now

### ISSUE THREAD

**Issue by OwnageIsMagic** [web-scrobbler/web-scrobbler#1471]
Add scrobble now button

**Comment by alexesprit** [comment]
Why?

**Comment by OwnageIsMagic** [comment]
I have 2 use cases 
When ext disables (#1455) I can submit skipped tracks without relistening them

**Comment by alexesprit** [comment]
> When ext disables (#1455) I can submit skipped tracks without relistening them :)

Well, I'm not sure if it's possible to implement in near future.

> Also if I heard song on the street I can find it in the internet and scrobble instantly

If you want to add a track to your playback w/o actuall listening of a track, you can use [OpenWebScrobbler](https://ows.elamperti.com).

**Comment by inverse** [comment]
@alexesprit is this ticket even valid anymore? 

I think OpenWebScrobber covers the 2nd point and the other point was solved shortly after you posted this.

**Comment by alexesprit** [comment]
@inverse you're right, OpenWebScrobber fully covers the second point. The first one was resolved.
