### ISSUE TITLE
Connector Request: Napster

### ISSUE THREAD

**Issue by forenta** [web-scrobbler/web-scrobbler#1492]
After searching around I can't find any scrobbler that supports the Napster streaming service, formerly known as 'Rhapsody'. The Chrome-extensions 'scroblr' already has the support - as I'm back on Firefox, I'd love to keep on scrobbling.

Here's the [source ](https://github.com/cgravolet/scroblr/blob/82cee1013b3ec545a56bacf3b388879ae34ded7e/src/js/plugins/rhapsody.js)they use - maybe it'll help you to figure out how to implement. Although it's still called 'Rhapsody' there, it is working with Napster right now.

**Comment by forenta** [comment]
If someone would like to code the connector, but is not able to do so because she or he does not have an account for Napster - feel free to send me a message. The access is possible from everywhere (credit card-related), so I would lend my account for two days.

**Comment by inverse** [comment]
Doesn't work in Germany :(

**Comment by forenta** [comment]
Sure it does, I'm just sitting in no man's land of NRW.

**Comment by inverse** [comment]
I was on the US page and it threw an error.  Should be able to make a connector based on that other one you provided.
