### ISSUE TITLE
Scrobble approvals

### ISSUE THREAD

**Issue by ampersham** [web-scrobbler/web-scrobbler#1496]
My problem is that the extension will scrobble things which are not music, such as videos viewed on YouTube.

For instance, have you heard of KIDS EAT GERMAN SNACKS | Kids Vs. Food<https://www.youtube.com/watch?v=esRoxoE2_4U>? Great music, apparently has 38 scrobbles, probably from this addon!

Would be really nice if things like this weren't scrobbled. If I could approve and disapprove scrobbles in general, or on YouTube specifically that would be greatly appreciated. I'd suggest maybe having an index of positively verified real music, maybe derived from musicbrainz or discogs of actual artist/song matches that get auto-approved for scrobbling, while inferred scrobbles can have approval turned on.

I've used the extension for years on different browser (Chrome, Opera, now Firefox (yay!)) and have always dealt with this. Lectures and documentaries, whatever, showing up in my scrobbles... Let me know what you think.

**Comment by alexesprit** [comment]
This is possible to implement if MusicBrainz or Discogs have API which can help to recognize is a video title has valid track info.

**Comment by inverse** [comment]
They should have something for that. What about the "Scrobble videos from "Music" category" feature in the options? Does that help limit the scope of what's being scrobbled?

**Comment by OwnageIsMagic** [comment]
Maybe turn it on by default?

**Comment by inverse** [comment]
Perhaps having on on boarding with new users on the extension might be good. Even just a simple info window explaing how to access the options as it's quite well explained there.

**Comment by chinatsu-chan** [comment]
I do i fact have the only scrobble from music option enabled, an had the entertainment one checked too. As the video in question is categorized as entertainment it was scrobbled.

MusicBrainz does in fact have an API.

**Comment by alexesprit** [comment]
I think this idea could be implemented as a pipeline state (or as a part of `metadata` state); as an option "Validate track info via MusicBrainz" in the options page. Plus, current option called "Force song recognition" can be reverted and renamed to "Validate track info via Last.fm"; that should be more clear for users. These two options turned off mean the extension will scrobble a now playing track "as is".

And I definetely think this feature should be optional, because it'll slow down track processing.

Haven't used MusicBrainz API before, will try to look into that later.

**Comment by alexesprit** [comment]
https://github.com/web-scrobbler/web-scrobbler/tree/feature/validate Some experiments

Personally, I don't like the result; some known tracks are not recognized now.

**Comment by inverse** [comment]
Is this ticket even valid anymore?

**Comment by yayuyokitano** [comment]
This is effectively solved through the setting to only scrobble edited tracks, since that forces you to approve metadata for every track before scrobbling.
