### ISSUE TITLE
right click menu not showing

### ISSUE THREAD

**Issue by OwnageIsMagic** [web-scrobbler/web-scrobbler#1502]
![image](https://user-images.githubusercontent.com/10534634/32999530-dad5ccea-cdb3-11e7-8c8c-eb3016195a33.png)

**Comment by alexesprit** [comment]
How to reproduce?

**Comment by bykidi** [comment]
switch to tab with unsupported site, click on button, done.
fde 58.0b4 32bit

**Comment by OwnageIsMagic** [comment]
Happens time to time
This screenshot from vk.com

**Comment by alexesprit** [comment]
I'm aware of this bug, but I can't catch the one. Probably, will revert some changes.
