### ISSUE TITLE
Use tab audible API to detect the playing state?

### ISSUE THREAD

**Issue by xyauhideto** [web-scrobbler/web-scrobbler#1516]
For sites using a flash player, the current connector is usually unable to detect the playing state (e.g.#1515). For this purpose, is it possible to introduce the [tab audible API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) (support by Chrome and Firefox since v45)?

### Expected behavior

Correctly detect the playing state of sites using a flash player.

### Current behavior

Assume the `isPlaying` state is always true.

### Possible solution

Introduce the [tab audible API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) (support by Chrome and Firefox since v45).

**Comment by jaccarmac** [comment]
Chrome's warning about the imminent removal of Flash on the dev channel, but perhaps this could still be useful for certain connectors?

**Comment by alexesprit** [comment]
I think it could be possible to use as a default way to detect playing state.

Unfortunately, it doesn't always trigger on Opera (their issue).
