### ISSUE TITLE
Focus@Will not working

### ISSUE THREAD

**Issue by rodrigoplant** [web-scrobbler/web-scrobbler#1521]
Hey there!

Is anybody else having problem with the extension at the Focus@Will site?
It get stucked with "Play some music to get started" (obviously I'm actually playing it).

Thanks in advance.

**Comment by alexesprit** [comment]
I have no Focus@Will account, so I'm not able to fix it. I know they provide 2 week trial, but it's expired for me. You could share yours, so I can try to fix it.

**Comment by rodrigoplant** [comment]
Sure. I'll e-mail you.

**Comment by alexesprit** [comment]
Looks like it works fine again. Could you install the extension from the master branch and tell if scrobbling works or not?

**Comment by rodrigoplant** [comment]
It works! Will you update it on the Chrome Store?

**Comment by alexesprit** [comment]
Yes, of course.

**Comment by rodrigoplant** [comment]
Focus@Will changed its UI and the plugin is not scrobbling correctly. Can you kindly check that again? Thanks!
