### ISSUE TITLE
Extension does not recognize Google Play Music every time

### ISSUE THREAD

**Issue by Kxze** [web-scrobbler/web-scrobbler#1534]
### Expected behavior
The app scrobbles correctly from Google Play Music.

### Current behavior
It doesn't always detect that Google Play Music is a supported website (grey icon), or that music is playing (red icon). I have to refresh the page a couple of times before it works correctly.

### Steps to reproduce (for bugs)
1. Open Google Play Music
2. Play a track

### Logs
https://gist.github.com/Kxze/ee6e0c85f00df6fd2a0f4521ee8c22af

### Steps for resolving the issue
- [x] Reauthenticate on Last.fm
- [x] Try to use unpacked extension from latest master
- [x] Check other issues for duplicates

### Environment
* Version used: 2.2.4
* Browser name and version: Firefox 57.0.2 (64-bit)
* OS: Windows 10 64 Bit

**Comment by davidgm2** [comment]
I'm experiencing the same issue with the same browser & system specs you've listed. Refreshing the page is never guaranteed to fix the problem

**Comment by alexesprit** [comment]
Ref #1502.
