### ISSUE TITLE
Firefox extension doesn't connect to Last.fm

### ISSUE THREAD

**Issue by TechSmurfy** [web-scrobbler/web-scrobbler#1538]
I'd expect a popup notification or something to ask for access to my last.fm account but no. I don't see any request whatsoever so no scrobbling works.

I've uninstalled and re-installed, enabled and disabled. I thought it had to do with the libre.fm account, so I created one, but again, nothing.

Furthermore, all soundcloud tracks I tried are "not recognized", and all youtube tracks I tried I'm getting the "is it already playing?" notification.

### Environment
* Version used: 2.2.4
* Browser name and version: Firefox 50.1

**Comment by alexesprit** [comment]
The extension works only on Firefox 53 and newer, because older versions don't support sync storage.

**Comment by TechSmurfy** [comment]
Oh, good to know, I'll update soon.
A "browser versions supported" notification would be useful though ;)

**Comment by alexesprit** [comment]
> A "browser versions supported" notification would be useful though ;)

I'll update a required Firefox version in manifest.
