### ISSUE TITLE
Firefox 57 can't connect to libre.fm

### ISSUE THREAD

**Issue by rootion** [web-scrobbler/web-scrobbler#1542]
### Current behavior
When trying to connect accounts on a freshly installed Firefox browser, libre.fm won't connect.
Last.fm will open a new tab. Libre.fm will display an error pop-up instead without showing sign-in form. 

Error message:
```
Authentication error. Unable to sign in to libre.fm. Please try again later.
```

### Steps to reproduce (for bugs)
1. In firefox: Addons manager > Preferences
2. In web scrobbler, under libre.fm, click Sign in
3. Error message without sign-in form.

### Environment
* Version used: 2.2.4

* Browser name and version: 
Firefox 57.0.1 64-bit
Same issue on Firefox Nightly 59.0a1 64-bit
No other extensions enabled.

* OS: Ubuntu 16.04

**Comment by alexesprit** [comment]
I'm not sure if this issue is related to this project. Libre.fm website doesn't work.

**Comment by alexesprit** [comment]
It sign in to Libre.fm fine for me.
