### ISSUE TITLE
Youtube japanese songs scrobbling

### ISSUE THREAD

**Issue by Defunktt1** [web-scrobbler/web-scrobbler#1544]
Found a problem with scrobbling Japanese artists on YT. Often they write name of the track in 「」brackets. For example 大森靖子「君に届くな」. Plugin can't correctly detect artist's name – song's name.

Video for example: https://www.youtube.com/watch?v=_3nAi0wEYjw

**Comment by alexesprit** [comment]
Fixed in b57698339a33d26ef72f32e059a1bcb13bf3f0f6.
