### ISSUE TITLE
Export edited tracks doesn't work (FF)

### ISSUE THREAD

**Issue by OwnageIsMagic** [web-scrobbler/web-scrobbler#1546]
https://github.com/web-scrobbler/web-scrobbler/blob/master/options/options.js#L404 returns Url of options page

**Comment by alexesprit** [comment]
@OwnageIsMagic fixed for me on FF57. Btw, it worked for me before, but stopped working suddenly. Could you test these changes and tell it's fixed?

**Comment by OwnageIsMagic** [comment]
No,
![image](https://user-images.githubusercontent.com/10534634/34454226-ef82e8ba-ed77-11e7-9e66-12083fd13b76.png)

![image](https://user-images.githubusercontent.com/10534634/34454220-d693829c-ed77-11e7-8680-5c0d5bfccfb8.png)

**Comment by alexesprit** [comment]
What's your Firefox version?

I believe you test the extension from the master branch, because I didn't publish a patch update to AMO and CWS.

**Comment by OwnageIsMagic** [comment]
https://github.com/web-scrobbler/web-scrobbler/commit/51087f4da3b046dc7f01424bc2cad143bd179f3b won't fix this anyway
![image](https://user-images.githubusercontent.com/10534634/34454323-12f9d176-ed7a-11e7-960b-73f25e966957.png)
![image](https://user-images.githubusercontent.com/10534634/34454322-079be5ee-ed7a-11e7-8fe5-1c390cf73251.png)

**Comment by alexesprit** [comment]
Can't reproduce on Firefox 58 with 51087f4da3b046dc7f01424bc2cad143bd179f3b applied.

**Comment by alexesprit** [comment]
Could you install [this][1] extension, install some userstyle, and export it via this extension? They made a workaround for Firefox to save data to a file, which can be important.

[1]: https://addons.mozilla.org/en-US/firefox/addon/styl-us/

**Comment by OwnageIsMagic** [comment]
OK
![image](https://user-images.githubusercontent.com/10534634/34454617-f45aa80c-ed7f-11e7-8e24-bd697e5d60ca.png)

**Comment by alexesprit** [comment]
Ok, thanks. Will steal their code soon.

**Comment by OwnageIsMagic** [comment]
Oh sorry
 51087f4 actually fixes it

**Comment by alexesprit** [comment]
Glad to head the issue is fixed. Publishing a new version right now.
