### ISSUE TITLE
How to import local cache?

### ISSUE THREAD

**Issue by alexesprit** [web-scrobbler/web-scrobbler#1548]
1. Extend current local cache by imported one. 
E.g. we have "AAA — BBB" track saved in cache, and we import cache with "111 — 222" and "@@@ — %%%" track. After import local cache will contain all three tracks.

2. Use imported local cache instead of current one.
The same situation, but the result is different. The imported cache will replace the current one. Only two last tracks will be in the cache after import.

Currently the extension behaves in a way descriped in the second point, but I realized this could unexpected. I vote for the first option.

**Comment by OwnageIsMagic** [comment]
let user choose `confirm('Replace?') ? oldFn() : newFn()`

**Comment by alexesprit** [comment]
Yes, this is a best solution to satisfy all users. But is there a *real* purpose to have two ways to import data?

**Comment by OwnageIsMagic** [comment]
Since there is already clear storage button
Just merging is ok

**Comment by inverse** [comment]
1 offers the most flexibility and if we make it clear that it's an append operation then it should be fine!
