### ISSUE TITLE
Custom filters

### ISSUE THREAD

**Issue by OwnageIsMagic** [web-scrobbler/web-scrobbler#1552]
Add user created fillters

**Comment by alexesprit** [comment]
What do you mean by filters?

**Comment by OwnageIsMagic** [comment]
Metadata filters
https://www.youtube.com/watch?v=MBvAvW6KQDk&list=PLRO4b8EqD8g5ptqAPiMnrnslZPIK70V44&index=7
have all songs ending wih  `- Solo Guitar`

**Comment by alexesprit** [comment]
But this feature is related to Youtube connector only, right? Because other connectors (excepts several ones) use other filters.

**Comment by OwnageIsMagic** [comment]
The best approach is to be able to configure used filters dynamically

**Comment by OwnageIsMagic** [comment]
Something with checkboxes where I can enable each filter individually or disable all post processing

**Comment by alexesprit** [comment]
Do you suggest to apply these user-defined *rules* (because a filter is an object) to every connector?

Now we have the default trim filter used everywhere, plus, some connectors extend this filter by other custom filters. Your suggestion is to add another filter which uses custom rules defined by a user. Am I correct?

**Comment by OwnageIsMagic** [comment]
![image](https://user-images.githubusercontent.com/10534634/34652850-c3ebf042-f3f4-11e7-9ec8-b99099c0f08d.png)
Something like this 
user defines custom function that accepts metadata, mutates it and returns it

**Comment by OwnageIsMagic** [comment]
Solve this type of problems:
> Implement translit filter (for bandcamp) and enable it only on for current album

And make it Promise based to allow async operations :)

**Comment by OwnageIsMagic** [comment]
btw there are tons of filters that I would like to apply and they are already implemented for others controllers but it requires plugin rebuild to enable them
for example
![image](https://user-images.githubusercontent.com/10534634/35478429-57b56eb2-03ee-11e8-909c-0840d11cf87b.png)

**Comment by inverse** [comment]
So is this really a two part feature.

- Add support for custom user defined filters
- A rule engine to decide when to apply. e.g. 
  - Current album
  - Connector
  - Page?

**Comment by OwnageIsMagic** [comment]
Yes and no
With custom filter I can copypaste all needed filters to all-in-one
But design like this looks more user friendly
![image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgeNQlfrOwoJBjbnOVjxPs5ITzLgYvjQoyT77frUnkGolTb_pqJg) 
Dropdown with connectors
On the left all filters, on the right applied

**Comment by brodie-g** [comment]
If I'm understanding this feature correctly, it might help with an issue I'm having.

Scrobbling from SiriusXM web app, there's a lot of tracks that are appended by the year in brackets:

Diamonds - The Stroll (57)
Petula Clark - I Know A Place (65)


Is there anything that exists now, or would the filter feature be able to strip out text? In this case, a regex to find and remove numbers in parentheses at the end of the track title before submitting to last.fm.

**Comment by sorashi** [comment]
I would like something similar to this to be implemented, because there are YouTube song titles ending with `| Some Genre` and they fail to be recognized correctly. I would like the option to make custom regex filters.

**Comment by RAM237** [comment]
Agree, guys, would be really helpful and time-saving in some specific cases.

**Comment by kimonoki** [comment]
Yes would nice to have something like pano scrobbler
