### ISSUE TITLE
Scrobbler seems to have issues with some albums on Google Music (namely one)

### ISSUE THREAD

**Issue by Moondownr** [web-scrobbler/web-scrobbler#1554]
I use the plugin chiefly on Google Music webplayer and it works generally well, but there is a weird issue with the album Polygondwanaland by King Gizzard & the Lizard Wizard
(https://play.google.com/music/listen#/album/Bz6cqubixadrz6vu347u66f3fee)

It only scrobbles the 1st, sometimes 2nd track, and then fails to recognize each next one. I have tried it multiple times over a month, and it happens each time. Moreover, after submitting song info manually, they appear on "Now listening" on my last.fm profile, but then often fail to scrobble (sometimes they do scrobble, it seems random). Generally, the performance with this album is very erratic and unpredictable.

* Version used: last.fm scrobbler 2.3.5
* Browser name and version: Firefox 57.0.4 64 bit on Ubuntu Gnome 16.04

**Comment by alexesprit** [comment]
The extension does not recognize these tracks, that's expected. After submitting track info via the info popup these tracks are recognized correctly. That's how the extension behaves for me.

You can force scrobbling of unknown by Last.fm tracks by turning on the "Force track recognition".
