### ISSUE TITLE
Scrobbler doesn't scrobble track without album at radiotunes.com

### ISSUE THREAD

**Issue by drymar** [web-scrobbler/web-scrobbler#1555]
Hello David!

I've want to report issue with scrobble tracks without album. When I listen music at radiotunes.com and scrobble doesn't find album for track, it's not scrobble(adds to my library). Can we fix it's by accessing scrobble tracks to library with empty album value.

Thanks for supporting!
Dima

**Comment by alexesprit** [comment]
Is it only on Radiotunes?

**Comment by dimapower** [comment]
@alexesprit no, as i know also at rockradio.com
