### ISSUE TITLE
Mixcloud not scrobbling

### ISSUE THREAD

**Issue by heyarne** [web-scrobbler/web-scrobbler#1557]
I'm on Firefox 58.0b16 (Developer Edition) and the extension doesn't detect anything on Mixcloud. [here is the track I realized it with](https://www.mixcloud.com/BeatTheFuture/btf-89-w-maja-milich-melanie-charles-jus-fly-anakin-matt-martians-exile-swarvy-pink-siifu/). Log output:

```
Web Scrobbler: Setting up observer
starter.js:31:3
Web Scrobbler: Player element (.player-wrapper) was not found in the page.
starter.js:44:4
Web Scrobbler: found .player-wrapper using second MutationObserver.
starter.js:49:6
perf_trace {"name": "e2e", "parent": "PageEvents.BIGPIPE_ONLOAD"}
QQi_J7YMTZL.js:186:2813
```

**Comment by Romchyk** [comment]
Same story with Google Chrome 63.0.3239.132 (Developer) (64-bit)

**Comment by alexesprit** [comment]
Works fine for me on the track you linked above.

**Comment by heyarne** [comment]
What exactly does it scrobble? Does mixcloud work differently in different countries due to different laws maybe? I remember them having problems with their tracklists (writing this in Germany).

Maybe a screenshot helps?

![screen shot 2018-01-21 at 17 31 40-min](https://user-images.githubusercontent.com/525780/35196364-535efcce-fed1-11e7-99cc-93eaf157fd9c.png)

**Comment by inverse** [comment]
![image](https://user-images.githubusercontent.com/713525/35243267-8769a5c8-ffbc-11e7-94c6-7b9001c341d3.png)

... it's working for me. Also in DE.

**Comment by heyarne** [comment]
I tested it on some other sets and have yet to find one where it scrobbles. Most of the time the message about the second MutationObserver isn't shown, I didn't see it since I made the post above and haven't changed my setup. Can I provide any additional info?

**Comment by apmechev** [comment]
Can't scrobble here either

Chrome 64.0.3282.186 (Official Build) (64-bit) (Linux)

Song URL: https://www.mixcloud.com/ChemicalgrooveRadio/charlotte-de-witte-bbc-radio-1s-essential-mix-2018-02-10/

**Comment by Romchyk** [comment]
Tested. Same story as your.
http://prntscr.com/inmu8q
Same story with Google Chrome  64.0.3282.186 (Developer) (64-bit)

**Comment by MalikTH** [comment]
@alexesprit Oh, that makes sense. Thanks for the correction.

**Comment by heyarne** [comment]
Only slightly related, but what exactly is the reason for artist titles showing up for some users while for others there are none? This can be observed in my example afaik. Is there any browser extension that fixes this maybe?
