### ISSUE TITLE
Support Resonate.is

### ISSUE THREAD

**Issue by lindner** [web-scrobbler/web-scrobbler#1558]
### Expected behavior

Support scrobbling for the Resonate streaming service.

Sample URLs
   https://beta.resonate.is/  (Unified player)
   https://resonate.is/album/138/ugress-it_came_from_beyond_eternal_september/

I will happily fund a Resonate account for any developer that wants to take this on.

**Comment by inverse** [comment]
Ill take this one - looks like I can get some free credit :) No need to fund.

**Comment by inverse** [comment]
p.s. you should have listed your affiliate link :)

**Comment by lindner** [comment]
I'm happy to pay a bounty!  Also the newest interface is at
beta3.resonate.is

**Comment by inverse** [comment]
Updated PR to support beta3 player.

**Comment by peteratomic** [comment]
@inverse you're in Berlin! We should meet up. Msg us on the resonate.is contact page and it will reach me. :-)

**Comment by inverse** [comment]
Will be in the next release!

**Comment by lindner** [comment]
Thanks!

**Comment by inverse** [comment]
@lindner It's deployed ;)

**Comment by lindner** [comment]
\o/  posted about this.

http://www.1500wordmtu.com/2018/scrobbling-for-resonatecoop-is-now-available-thanks

**Comment by inverse** [comment]
:D nice
