### ISSUE TITLE
Options UI Spelling mistakes

### ISSUE THREAD

**Issue by SensehacK** [web-scrobbler/web-scrobbler#1562]
In Options menu UI : 

### Expected behavior
>> General
                  >>> Notify if track is not recongized _"recognized"_ 

>> Edited tracks
                 >>>  This extention stores edited tracks.  _"extension"_

I tried to search for this words on the project >> Src >> options. I couldn't find the text maybe, the text is being parsed real time using JSON/rest apis.
So raising the issue. Do let me know how can I fix it & submit , as that would be my first contribution on Github :)

### Environment

* Version used: Version 63.0.3239.132 (Official Build) (64-bit)
* Browser name and version: Google Chrome 
* OS : Windows 10 (64-bit)

**Comment by alexesprit** [comment]
> Notify if track is not recongized "recognized"

This typo was fixed in #1550.

> This extention stores edited tracks. "extension"

And this one wasn't. You can find the string in `src/_locales/en/messages.json`.

**Comment by alexesprit** [comment]
I'm closing this one since you've fixed all typos mentioned here.
