### ISSUE TITLE
Listen.moe updated the design. due to this, the Scrobbler isn't working anymore

### ISSUE THREAD

**Issue by calvinc64** [web-scrobbler/web-scrobbler#1563]
Because Listen.moe updated the whole design on the Website, the Scrobbler is sadly not working anymore.

### Current behavior

Not Scrobbling.

### Possible solution

Update the Webhook (I have no Idea how)

### Steps to reproduce (for bugs)

1. Go to https://listen.moe/ 
2. Click Play
3. NO Scrobble.

### Environment

* Version used: 2.3.5
* Browser name and version: (Chrome) 63.0.3239.132 (64bit Windows 10)

**Comment by alexesprit** [comment]
Fixed in #1571.
