### ISSUE TITLE
Small problem with a new connector for site muzo.fm

### ISSUE THREAD

**Issue by akleski** [web-scrobbler/web-scrobbler#1572]
Hi

I've added new connector for Muzo.FM radio station. It's in my forked repo.
 
It seems to be working kind of okay. However, I've noticed it doesn't recognize the transition between the songs. 
What I mean is, I checked that on last.fm in 'Recent Tracks' list the currently playing songs keep changing band & artist, but the playback is counted as a one long continuous scrobble. Instead, I'd like it to be counted separately.  
Right now to properly split the "Now scrobbling" the player must be stopped manually, and re-started (and sometimes the page has to be refreshed) - this is of course not optimal solution :P 

Can someone please advise how to fix it?

This is probably because the selected #player in Connector.isPlaying always hasClass('playing'). The only thing that changes when a new songs kicks-in is the value of text of the two selected elements:
.player__label--band 
.player__label--title

I'm not very familiar with NodeJS, so I might be wrong and for sure at the moment I'm clueless on how to deal with this. I tried googling for something related to string value change of an element, but to no avail. I'd appreciate any help - thanks in advance!

Regards,
Adam

**Comment by inverse** [comment]
First up awesome getting going with your implementation!

Usually with these sorts of transitions the duration of the track is exposed so this can be factored in to help with the transition AFAIK @alexesprit can you confirm?

As for this situation looking at their DOM I am not sure how else to detect? Since the DOM doesn't actually change in this instance if a track is repeated. Does this happen often on the radio station?

**Comment by OwnageIsMagic** [comment]
@akleski `Node.js` is server side JavaScript runtime

**Comment by akleski** [comment]
@OwnageIsMagic  thanks for clarifying 

@inverse, can you shed more light on the exposed duration of the track? I've no idea how this could be achieved.

> As for this situation looking at their DOM I am not sure how else to detect? Since the DOM doesn't actually change in this instance if a track is repeated. Does this happen often on the radio station?

Yes, this radio is unfortunately doing just that sometimes. 

Still I found a new clue, namely when two (or more) songs aren't played one after another (i.e.: radio host does some talking before playing next song), then this element:
`<div class="player__labels">`
gets one extra class inside:
`<div class="player__labels player__labels--off">`

which clears the .player__label--band & .player__label--title elements. 

I already tried the following code change:
`Connector.isPlaying = () => !$('.player__labels').hasClass('player__labels--off');`

for reference, previously it was:
`// Connector.isPlaying = () => $('#player').hasClass('playing');`

I think it's slightly better now. 

But maybe it could be solved differently? Perhaps with getter 'n setters and comparing the track after a fixed period of time, or some event.. I really don't know yet.  

Any ideas?

/cheers~!

**Comment by inverse** [comment]
I don't think that change to isPlaying would work? The way it was before seems more logical to me. But I could be mistaken?

The thing is there needs to be some change in the DOM for the state change to be triggered. However like I mentioned it uses the duration to trigger this for same tracks AFAIK.

There is an HTML5 audio player on that page, but since it's a stream you won't be able to tag on to that. 

I'm not sure of how best to handle such cases :(

**Comment by akleski** [comment]
Actually after the change the scrobbling works better  :)

The only drawback is that for Chrome the radio-player has to be either:

- opened alone in a separate browser window, 

- or be on the browser's active tab 

If not, then the "Automatic tab discarding" feature (enabled by default) discards the background tab state. This means page content isn't auto-refreshed and the element 'player__labels' does not change.
 This functionality is described in more detail here: [https://productforums.google.com/forum/#!topic/chrome/70x0I7JFgmM](url)

That being said, yet another approach has to be devised to make web-scrobbler fully compatible with MuzoFM.

**Comment by akleski** [comment]
After some thought, I added three conditions for .isPlaying():

`Connector.isPlaying = () => ($('#player').hasClass('playing') && !$('.player__labels').hasClass('player__labels--off') && !$('#player').hasClass('muted'));`

Reason is 'player__labels' element is changing even when player is stopped/paused or muted.

I was also thinking of adding information (notification) for users about the chrome feature that is impacting the scrobbling from MuzoFM. Can this be implemented as part of the new connector?
(I assume you cant switch off this feature via extension/javaScript, right?)

**Comment by alexesprit** [comment]
> I was also thinking of adding information (notification) for users about the chrome feature that is impacting the scrobbling from MuzoFM.

What does it mean? Could you clarify?
