### ISSUE TITLE
Disable album guessing

### ISSUE THREAD

**Issue by nagrizolich** [web-scrobbler/web-scrobbler#1575]
I would like to request an option to disable album auto-completion. On YouTube it often guesses some compilation for single tracks and I don't want that. Scrobbling without the album field IS possible for example by Open Web Scrobbler and then album which Last.fm suggests doesn't appear in my library. However, when using this addon it does.

**Comment by alexesprit** [comment]
Ok, but I'd keep this option turned on by default.
