### ISSUE TITLE
"Ignored by service"?

### ISSUE THREAD

**Issue by fishstik** [web-scrobbler/web-scrobbler#1579]
I noticed a scrobble on SoundCloud not going through, and it looks like it's being ignored deliberately (either by the connector or Last.fm) because of unusual characters. The original track data from sc is Artist: **onitram.** Title: **1.four.sokro?????**. This was unknown to Last.fm so I edited it to Artist: **onitram** Title **1.four.sokro?????** (just removing the dot after the artist name). I then got the green "Now Playing" icon. Then when it came time to scrobble, the red 'ignore' icon popped up.

### Expected behavior
Scrobble titles no matter how weird they are.

### Current behavior
Scrobble is ignored with red X icon and "Ignored <artist> --- <title>" tooltip. Clicking icon doesn't do anything.

### Possible solution
I thought the "Looking up <track>" part of the scrobbling sequence was checking against the Last.fm database. But if there was a recent change to do something beyond this check, it might be rejecting the scrobble. Or maybe it's a problem on Last.fm's side.

### Steps to reproduce (for bugs)
1. Play track at https://soundcloud.com/onitram52/1foursokro
2. Click on [?] and click Submit (with or without edits)
3. Wait until halfway point of playback
4. See red [X]

### Environment
* Version used: 2.3.5
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)

Screenshot:
![image](https://user-images.githubusercontent.com/4278123/36448307-3187dfd0-1655-11e8-8817-c3ae69b4b455.png)

**Comment by inverse** [comment]
First up - thanks for such a detailed explanation! 

I'm not seeing what you described however It's not showing up on my last.fm.

**Comment by alexesprit** [comment]
Why do you think it's the issue? The extension just shows Last.fm response and this is expected behaviour (for this track, of course).

I just tried to scrobble it using [OpenWebScrobbler](https://ows.elamperti.com/), but with no success.
