### ISSUE TITLE
Show the scrobbler icon on every tab

### ISSUE THREAD

**Issue by CennoxX** [web-scrobbler/web-scrobbler#1581]
It's unlikely for a user, to hear (and scrobble) more than one song at the time. So an option would be great, to show the scrobbler status on every tab. This would also provide an easier way to get the song name, album, see if the song was recognised, etc. without notifications and changing the tab.
Currently the scrobbler icon is grayed out on every page except of the page which is playing the music.

**Comment by alexesprit** [comment]
Ok, just a simple example:
1. Open a website A and play something, then pause a track.
2. Open a website B in a new tab and play something, then pause a track.
3. Switch to the tab with the website A opened and resume the track.

What track info should the extension show on step 2? On step 3?

**Comment by CennoxX** [comment]
Always the last one with an interaction (play, pause).

**Comment by alexesprit** [comment]
3a. Switch to the tab with the website A opened and do nothing.

Should we update the popup content, i.e. force to show A instead of B?

**Comment by CennoxX** [comment]
Always show the last track with an interaction, so when no interaction with the tab on website A happens, keep the popup content of B.

**Comment by RAM237** [comment]
+1, wanted to raise the same proposal.

It was very handy in **scroblr** (which I used to use before moving to **web-scrobbler**), that you can view/modify current track info no matter on which tab you are.  
Always switching back to the tab where your music is playing - is very annoying and distracting from your parallel activities (I used to scrobble from work most of the time, so looking for desired tab, switching to it, doing required actions, then looking for previous tab and switching to it takes too much time and significantly slows down my productivity).  
I REALLY want to be able to do the action from ANY tab.

As an idea of dealing with website A & website B example above - how about showing both tracks in extension? Just sort them for the most recent interaction to be on top.

**Comment by alexesprit** [comment]
> As an idea of dealing with website A & website B example above - how about showing both tracks in extension? Just sort them for the most recent interaction to be on top.

I think displaying the last active track is better and easier to implement.

**Comment by alexesprit** [comment]
Also, if this feature will be implemented, we should display a website name in the info popup (like it's displayed in a now playing notification).

**Comment by alexesprit** [comment]
What should we do with browser action context menu? If we keep it as is, it will be confused for users, as the browser action is global, but the context menu is limited to a current website in an active tab.
![image](https://user-images.githubusercontent.com/1119267/68992825-f0160600-0881-11ea-9dde-745a99dd4147.png)

**Comment by CennoxX** [comment]
Ya, probably it would be consistent to make the context menu global too. Maybe with two entries, one with "Disable Whatever connector (currently playing)", one with "Disable Plex connector (current page)" (if both tabs have different music services, otherwise one would be enough), if that is not too cluttered. I think the reaction to the current tab ("Disable connector until tab is closed") should only appear on the currently opened tab, maybe with slightly changed wording (including the name of the connector), to prevent confusion with the playing tab.

**Comment by alexesprit** [comment]
Preview: https://github.com/web-scrobbler/web-scrobbler/tree/feature/single-browser-action

**Comment by alexesprit** [comment]
> Also, if this feature will be implemented, we should display a website name in the info popup (like it's displayed in a now playing notification).



![image](https://user-images.githubusercontent.com/1119267/76704064-7f73de80-66e7-11ea-8f42-f940b3e7a331.png)

What's your thoughts on this? Suggestions are welcome.

The only issue I've not resolved is displaying a long connector labels:
<details>
  <summary>Image (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/76704605-2c9c2600-66eb-11ea-9f2d-a09f1859ea01.png)
</details>

/cc @anuragbhd

**Comment by RAM237** [comment]
Probably will just have to trim it, ending with "...", where it reached the display limit?

**Comment by alexesprit** [comment]
> Probably will just have to trim it, ending with "...", where it reached the display limit?

You're right, but I don't know how to do it :)

**Comment by anuragbhd** [comment]
Interesting discussion. I agree in principle that this feature should be implemented for convenience. I'd be one of the beneficiaries :)

@alexesprit That's a good design you have there.

@RAM237 +1 to your ellipses suggestion.

**Comment by anuragbhd** [comment]
> > Probably will just have to trim it, ending with "...", where it reached the display limit?
> 
> You're right, but I don't know how to do it :)

Perhaps something like this:

```javascript
if (connectorLabel.length > 25) {
  connectorLabel = connectorLabel.slice(0, 25) + '...';
}
.
.
.
$('#connectorLabel').text(connectorLabel);
```

**Comment by alexesprit** [comment]
@anuragbhd I would resolve this with HTML/CSS functionality. This workaround is acceptable for now, though.

**Comment by anuragbhd** [comment]
> @anuragbhd I would resolve this with HTML/CSS functionality. This workaround is acceptable for now, though.

Indeed. CSS's `text-overflow` property is a better fit here. We only need to ensure full text is visible on hover (by setting element's `title` attribute).

**Comment by RAM237** [comment]
Can't wait for it to be released!   :+1:
Want to try it and donate for it!

**Comment by alexesprit** [comment]
Found a way to ellipsize the connector label. :)

![image](https://user-images.githubusercontent.com/1119267/89436483-fbca9500-d74e-11ea-9d42-0b03f308e491.png)
