### ISSUE TITLE
filter out %C2%A0

### ISSUE THREAD

**Issue by OwnageIsMagic** [web-scrobbler/web-scrobbler#1582]
Replace non-breaking space with common space
https://www.last.fm/music/Within%C2%A0Temptation/_/Whole%C2%A0World+is+Watching

**Comment by alexesprit** [comment]
Did you see tracks with NBSP in its name on other websites or they are on VK only?

Could you link an example of such track?

**Comment by OwnageIsMagic** [comment]
https://www.youtube.com/watch?v=VRNPkJ0ELPc

**Comment by OwnageIsMagic** [comment]
btw Add id to cache listing
`for (let k in data) data[k].artist.includes('Tempt') ? console.log(k, data[k]) : 0` is not easy way to look up it
