### ISSUE TITLE
Hi, is there any chance to be added a beatsense connector in the future? Thanks.

### ISSUE THREAD

**Issue by Seryc** [web-scrobbler/web-scrobbler#1583]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
I'm closing this in favor of #2039, as it has better description.
