### ISSUE TITLE
TuneIn Radio not working

### ISSUE THREAD

**Issue by patrickl97** [web-scrobbler/web-scrobbler#1584]
### Expected behavior
last.fm-Scrobbler should support TuneIn Radio-

### Current behavior
I think the guys at TuneIn changed something. At the moment it's not possible to scrobble something from their page.  

### Possible solution
Maybe you have to edit something inside the code to support the new TuneIn page... 

### Context
I'm an internet radio fan and i have no chance to scrobble the songs from my favorite station to last.fm. I would be very happy if this could be possible through the Chrome extension.

### Environment
* Version used: v2.3.5
* Browser name and version: Chrome 64.0.3282.167

**Comment by alexesprit** [comment]
I believe I fixed it in #1556.
