### ISSUE TITLE
lastfm

### ISSUE THREAD

**Issue by farinhabenta** [web-scrobbler/web-scrobbler#1585]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [x] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
What's the problem? The title and description shows nothing.
