### ISSUE TITLE
vk.com does not scrobbling 

### ISSUE THREAD

**Issue by BeardedWhale** [web-scrobbler/web-scrobbler#1586]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
Can't reproduce on latest Opera.

**Comment by dklebedev** [comment]
Works for me. And never had an issue. Using Yandex Browser.

**Comment by bykidi** [comment]
working just fine on FDE 60.0b6
