### ISSUE TITLE
Amazon india prime music not scrobbling

### ISSUE THREAD

**Issue by ladu** [web-scrobbler/web-scrobbler#1587]
Amazon India prime music is live now (from 1st March, 2018). 
https://music.amazon.in/home 

### Expected behavior
The extension should detect and scobble.

### Current behavior
It just shows that this site is supported. But do not detect any music playing.

### Environment

* Version used: v2.3.5
* Browser name and version: Chrome v64.0.3282.186

**Comment by jagnyx** [comment]
Confirming.

**Tested Environment:** 

- Extension version: v2.3.5
- Browser: Firefox.
- Version: 58.0.2 64bit.
- OS: Windows 10 Pro 64bit.
