### ISSUE TITLE
Track not recognized sometimes appears

### ISSUE THREAD

**Issue by OwnageIsMagic** [web-scrobbler/web-scrobbler#1592]
![image](https://user-images.githubusercontent.com/10534634/37106094-f2555b64-2241-11e8-8af8-c52003fdeb1c.png)
![image](https://user-images.githubusercontent.com/10534634/37106256-64cb4f0a-2242-11e8-96da-44af85f0223b.png)
and sometimes just doubles
![default](https://user-images.githubusercontent.com/10534634/37183049-44375be0-2345-11e8-88af-d56180b0cba3.png)

**Comment by alexesprit** [comment]
Is it still an issue? I can't reproduce it by myself.
