### ISSUE TITLE
EDIT: In chrome, a freshly opened tab of a youtube video is scrobbled, even if the song isn't actually played

### ISSUE THREAD

**Issue by lucccien** [web-scrobbler/web-scrobbler#1595]
*EDITED for precision: 
In some situations, launching a youtube link into a new tab leads to a scrobble, even though the video was never played

### Expected behavior
In the past, it would only scrobble vids once you played them halfway through.
Is there a way to return this setting as a feature?

### Current behavior
I'm playing a song in youtube in Chrome. I right-click a related video and open that video into a new tab. Even though chrome will not play that video until I actually click on the tab, the song gets scrobbled anyway.

### Possible solution
Unable to provide a solution per se, but this is somewhat new behavior, so hopefully the old code/method still exists in earlier versions. Not sure of how long ago this started happening, but maybe it's been at least a few months.

### Steps to reproduce (for bugs)
EDITED for precision
1. open a tab in Google chrome
2. find a youtube music vid and start playing it.
3. right-click a related music vid into a new tab
4. observe that the song gets scrobbled, even if you never actually click on (change focus to) that new tab you opened.

### Context
I end up scrobbling nearly any youtube vid I watch, (and in some cases even close) after a few seconds,, which is obviously not desired.  [EDIT: I cannot consistently reproduce closing a tab and having the closed video still getting scrobbled, or having an immediately paused-at-the-beginning video getting scrobbled, so I have removed that part for now.] 

### Environment
* Version used: 2.4.3
* Chrome 64.0.3282.186 x64
* Windows 7 Home Premium SP 1 x64

**Comment by alexesprit** [comment]
Don't know how to fix this issue, but the workaround I added should help.
