### ISSUE TITLE
As a user I would like to scrobble from last.fm website

### ISSUE THREAD

**Issue by dklebedev** [web-scrobbler/web-scrobbler#1601]
I sometimes listen to my recommendations and my mix on last.fm and would like those to be scrobbled. It seems that last.fm website is unsupported. The extension icon is gray.

### Environment

* Version used: 2.4.3
* Browser name and version: Yandex 18.1.1.839

**Comment by OwnageIsMagic** [comment]
last.fm scrobbles on their own site by themselves

**Comment by dklebedev** [comment]
@OwnageIsMagic did not notice. Thanks!

**Comment by OwnageIsMagic** [comment]
Close this issue please
