### ISSUE TITLE
Not scrobbling certain musics on YouTube

### ISSUE THREAD

**Issue by germanoochner** [web-scrobbler/web-scrobbler#1604]
Hello everyone, I'm having issues of scrobbling some musics that are not in the category of "Music" on youtube, just some indie stuff that are released on "Art & Education" for example... 

Example: https://www.youtube.com/watch?v=CwDBNYZpbos

* Browser name and version: Mozilla Firefox Quantum 59.0.2 (64-bit)

Thank you.

**Comment by OwnageIsMagic** [comment]
As intended 
search issues

**Comment by alexesprit** [comment]
The extension scrobbles this video fine, if the options below are both turned off.
![image](https://user-images.githubusercontent.com/1119267/38469095-fef531c6-3b57-11e8-8485-5757414908e3.png)
