### ISSUE TITLE
Spotify playlist titles scrobbled as album titles on the Amazon Alexa page.

### ISSUE THREAD

**Issue by OttoWerse** [web-scrobbler/web-scrobbler#1611]
### Expected behavior

When scrobbling, the album title should either be the correct one, or left empty, if it is not displayed anywhere on the page.

### Current behavior

When playing a playlist from Spotify via Alexa and using the Alexa web interface to scrobble, the title of the playlist is used as the album title. This probably happens due to them appearing in the same text field of the web page. Obviously the extension can't do anything about the poor design choices on Amazons part, but there might be a way to at least fix the impact of this on Last.fm.

### Possible solution

I don't know if there is an easy fix for this, as there isn't really any obvious way to distinguish playlist titles from album titles if they are just put into the same text field carelessly. The only viable option I could think of, is an option to turn off including album titles from certain web pages or altogether. Unless, of course, there is some underlying code in the web page that would allow to distinguish them, that I don't know.

### Steps to reproduce (for bugs)

1. Tell Alexa to play a Spotify playlist
2. Open the Alexa web itnerface (https://alexa.amazon.de/spa/index.html#player)
3. Look at the album title field in the scrobbler GUI

### Context

It's not that bad, as the information about artists and songs is still coherent, but it really botches up your statistics about albums. Since I've gotten my echo and started using this extension, my average albums per week has been going up by over 50% (currently at ~1000) which was the reason I noticed this bug.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used: v2.4.3
* Browser name and version: Chrome Version 65.0.3325.181 (64 bit)

**Comment by thedrinkeno** [comment]
https://github.com/web-scrobbler/web-scrobbler/issues/1400

seems to be the same issue here
