### ISSUE TITLE
Can't create account, service error

### ISSUE THREAD

**Issue by ghost** [web-scrobbler/web-scrobbler#1613]
Howdy.
I can't create an account, playing music gets a "Service error" notification when I click on the WebScrobbler button.

### Expected behavior
Well, I was hoping to use this addon 😄 

### Current behavior
Clicking "Accounts" open up a small while space, nothing more. I'm supposed to be able to connect my accounts through there, right?

### Steps to reproduce (for bugs)
Not applicable. Here are some logs though: https://gist.github.com/NadavRuskin/635e2e4f3f2c94c29e51bcadf18ab735

I also have the following error in the console when loading the extension's webpage:
`downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1): status=2152857618 source: moz-extension://c0bccb74-11e2-49ad-ad4e-d50b06bae5db/vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0`

### Environment

* Version used: Latest from master (hash 28101b2), Latest on the Firefox extension page: 2.4.3
* Browser name and version: Firefox 56.0b9 (64-bit)

**Comment by alexesprit** [comment]
Is it still an issue? Could you use newer Firefox version?
