### ISSUE TITLE
Cannot scrobble from SiriusXM since they have updated their layout

### ISSUE THREAD

**Issue by jblattnerNYC** [web-scrobbler/web-scrobbler#1616]
The new SiriusXM website at https://player.siriusxm.com has updated their player and the Web Scrobbler doesn't work

**Comment by weirdoslam** [comment]
yeah i second this! should p easy to do since the metadata for songs are as visible as ever

**Comment by jblattnerNYC** [comment]
I should point out that is issue is associated with the Desktop version of the SiriusXM player/website. The smartphone application for SiriusXM is able to scrobble with another third-party Android scrobbler

**Comment by OwnageIsMagic** [comment]
@jblattnerNYC this is not related

**Comment by brodie-g** [comment]
+1 . I might try taking a look at making these changes if I get a second. Haven't contributed to this project yet, but this should be a fairly simple change.

**Comment by brodie-g** [comment]
Made a new PR at https://github.com/web-scrobbler/web-scrobbler/pull/1630. Working ok for me locally with that build.

**Comment by jblattnerNYC** [comment]
Is the issue related to the visibility of metadata within the new desktop player? The website is still not scrobbling. I only brought up the smartphone app to point out that scrobbling is still available with the older format (but not via Desktop or http://player.siriusxm.com/)

**Comment by brodie-g** [comment]
@jblattnerNYC , once my PR gets accepted and merged I think it should start working again.

**Comment by brodie-g** [comment]
Merged now. Not sure when the next release will be made, but in the meantime if you wanted to load from source you could follow these instructions https://github.com/web-scrobbler/web-scrobbler/wiki/Install-an-unpacked-extension
@jblattnerNYC
