### ISSUE TITLE
add http://music.businesscasual.biz

### ISSUE THREAD

**Issue by mattleistner** [web-scrobbler/web-scrobbler#1617]
hi,

could you add http://music.businesscasual.biz to the list of websites to scrobble, please?

**Comment by jawshoeah** [comment]
This appears to be a bandcamp like player?

**Comment by mattleistner** [comment]
Yep it is a subsite of bandcamp

W dniu sob., 19.05.2018 o 15:30 jawshoeah <notifications@github.com>
napisał(a):

**Comment by OwnageIsMagic** [comment]
https://github.com/web-scrobbler/web-scrobbler/wiki/Custom-URL-patterns

**Comment by inverse** [comment]
Closing as can be solved with Custom-URL-pattern feature
