### ISSUE TITLE
Save title corrections and prioritise their use

### ISSUE THREAD

**Issue by Xalaxis** [web-scrobbler/web-scrobbler#1619]
Often users will need to override the default detection or provide a detection for where one is not automatically available.  This happens particularly often on YouTube, where the video title may not be intentionally formatted in an easily parseable format.

If the user provides a correction for a title, we should store this correction on a per-URL basis (at least for YouTube where the URL changes for every song) and re-use this over attempting to guess the song title again.

### Expected behaviour
Revisiting the same YouTube video should recognise a previously applied title 'correction'

### Current behavior
Revisiting the same YouTube video will run another automatic detection attempt and ignore any previous 'corrections' over the current 'live' information.

### Possible solution
Save any correction applied to some form of local storage and check this location first for keys matching current URL or other selector at match-time.

### Context
I listen to a lot of Japanese music with unusual characters in the title.  This upsets the match algorithm, yet I have to manually apply the same correction every time I listen to the same song - Even if it's one I've heard many times before.  This is non-ideal.

**Comment by OwnageIsMagic** [comment]
Already implemented 
Post links to videos

**Comment by Xalaxis** [comment]
I can't seem to reproduce this now 🙁
