### ISSUE TITLE
Web Scrobbler no longer scrobbles from plug.dj

### ISSUE THREAD

**Issue by fluteds** [web-scrobbler/web-scrobbler#1620]
### Expected behavior
Web Scrobbler should scrobble and log all songs that are currently playing in plug.dj to last.fm.

### Current behavior
Web Scrobbler recognises the site with "Play some music to get started" but no longer detects and scrobbles songs currently playing probably due to the completely new user interface design on site.

### Suggestion
Most likely fix, update source from cdn.plug.dj to **cdn-prog.plug.dj** 

### Environment
* Version used: 2.5.0
* Browser name and version: Google Chrome Version: 65.0.3325.209 (Official Build) (64-bit)

**Comment by andrzej1pokrywka** [comment]
I can confirm it. The problem also occurs on Firefox. Recent interface update of plug.dj must have caused the issue.

**Comment by jawshoeah** [comment]
I can confirm the issue exists on Firefox, Chrome, and my Chromebook.
