### ISSUE TITLE
Last.fm announcement regarding Spotify integration

### ISSUE THREAD

**Issue by Potherca** [web-scrobbler/web-scrobbler#1621]
I received [an email from Last.fm regarding Spotify integration](https://us11.campaign-archive.com/?u=5c4ec1cbbbb30151caef0782f&id=6198846e7a) that might be of impact for this plugin:

> ## We’re updating the way you scrobble from Spotify to Last.fm
>
> Hey \<\<Username>>,
>
> We've recently added the ability to scrobble from any Spotify device by connecting your accounts from within your Last.fm settings. Soon this will be the _**only**_ way that you can scrobble from Spotify to Last.fm, make sure you connect your accounts now. 

I'm assuming this is not entirely new to you but it felt prudent to mention this here.

<img src="https://user-images.githubusercontent.com/195757/39895067-37d9569c-54a9-11e8-83cb-84a9b383daa5.png" width=100%>

**Comment by Pendrokar** [comment]
I haven't checked. But does this cause duplicate scrobbles? Also I have removed Spotify from Web Scrobblers checklist. Though that also means that I don't scrobble to the open source Libre.fm.

**Comment by Potherca** [comment]
I connected Spotify to my Last.fm account yesterday. 

I havent seen any weird behaviour yet.

If I disable the web-scrobbler plugin, songs played on the Spotify web-app _do_ get added to last.fm.

**Comment by Potherca** [comment]
I'm beginning to see double entries: https://www.last.fm/user/potherca

No indication if this is related (yet).

**Comment by Pendrokar** [comment]
That kinda is a failure on last.fm's part. Since they can retrieve the length of a track and therefore should be able to tell if you are really repeating the track. Sure I switch a lot without listening to a song fully. But that has never led to duplicates.
