### ISSUE TITLE
Stop working with Soma FM

### ISSUE THREAD

**Issue by Ileca** [web-scrobbler/web-scrobbler#1623]
Hello.
I didn't notice when it stopped scrobbling the songs exactly (red add-on icon) but they recently updated their online player's layout so I guess it might come from that.

**Comment by inverse** [comment]
Will be fixed in the next release - feel free to run unpacked if you wanna test now: https://github.com/web-scrobbler/web-scrobbler#install-from-source-code

**Comment by Ileca** [comment]
Thanks.
