### ISSUE TITLE
Youtube Channel Playlist Bug

### ISSUE THREAD

**Issue by felixhj** [web-scrobbler/web-scrobbler#1624]
Not recognising youtube music playing when on channel playlists

### Expected behavior
Music should be recognised when a youtube video is playing

### Current behavior
No music is registered by the extension

### Steps to reproduce (for bugs)
1.) go to a channel (e.g. https://www.youtube.com/channel/UCWJ0h-sGerHCxjAo2vRtkbg)
2.) click "play all" next to uploads
3.) youtube playlist playing but no music registered

### Environment
Mac OSX 10.11.6
Chrome 66.0.3359.139
Web Scrobbler 2.5.0

**Comment by OwnageIsMagic** [comment]
Scrobbling from yt enabled only if video in music category by default 
You can change it in options

**Comment by alexesprit** [comment]
Closed as not reproduceable.
