### ISSUE TITLE
Stopped working on iheartradio

### ISSUE THREAD

**Issue by Jonahrf** [web-scrobbler/web-scrobbler#1625]
It just stopped working. I think the connector code needs to be updated

**Comment by inverse** [comment]
I'm unable to listen to music on the site. in the console everything looks broken.

**Comment by James-W2** [comment]
I'm using Chrome to play iHeart Radio.  Their website appears to be working "normally," as it was prior to installing the scrobbler extension.  The Last.fm scrobbler icon is in extension position and is red, when hovering over icon gives message "This site is supported for scrobbling."  I even added my "custom" URL to iHeart in options, which made no difference.  I was using same browser and extension earlier this evening to play Pandora, and songs were scrobbling normally.
