### ISSUE TITLE
Won't log in to Last.fm

### ISSUE THREAD

**Issue by akilou** [web-scrobbler/web-scrobbler#1627]
Just installed the extension for the first time. First step was to connect it to Last.fm. This notification popped up: 
![image](https://user-images.githubusercontent.com/4934676/40060524-d77e0b06-5824-11e8-9ad9-43ca3db90dd7.png)

clicking on it brought me to this page in a new tab: http://status.last.fm/

Extension still says it's not connected to my last.fm account.
![image](https://user-images.githubusercontent.com/4934676/40060596-fe806906-5824-11e8-9f2d-eba6b6c865c8.png)

Not sure what to do next.

**Comment by inverse** [comment]
@akilou still an issue? could be last.fm had issues which is why they redirect there.
