### ISSUE TITLE
Wont scrobble google play

### ISSUE THREAD

**Issue by DevinBooker** [web-scrobbler/web-scrobbler#1629]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by kegbuna** [comment]
I am seeing this on music.google.com as well

**Comment by qwandor** [comment]
It's stopped working for me too.

**Comment by wcomartin** [comment]
Does not work for me either, has this been confirmed? is it being worked on?

**Comment by wcomartin** [comment]
do you take pull requests?

**Comment by HEdingfield** [comment]
Had this problem in Windows, then updated to Chrome 69.0.3497.100 and it seems to be resolved.

**Comment by ianlewis** [comment]
I'm having this issue as well.
I'm on ChromeOS 69.0.3497.95 (Official Build) (64-bit)

Will try again when I get .100

**Comment by inverse** [comment]
Interesting - it's working here :/

**Comment by ianlewis** [comment]
Odd. It seems to be working again now though I'm still on the same chrome version. Maybe the issue was on Google play's side

**Comment by HEdingfield** [comment]
On the contrary, I'm now having this problem again in Windows with Web Scrobbler 2.6.0 and Chrome 69.0.3497.100.

**Comment by ianlewis** [comment]
It's not working for me again on Chrome 69.0.3497.120 (Official Build) (64-bit)

**Comment by HEdingfield** [comment]
Yeah, I'm definitely having this issue on Linux still, no matter which version of Chrome I use.

**Comment by ianlewis** [comment]
Opened a new issue #1793
