### ISSUE TITLE
Won't scrobble on youtube

### ISSUE THREAD

**Issue by sarthakmm** [web-scrobbler/web-scrobbler#1631]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by sarthakmm** [comment]
Also, I have already reauthenticated it using last.fm

**Comment by magnus919** [comment]
I can reproduce this.

Watching [this](https://www.youtube.com/watch?v=rILKm-DC06A&index=3&list=LLU14WGNxM4sYdg_yXUZg6VQ&t=0s), I can confirm that the plugin can't detect music playing and thus won't scrobble.

**Comment by magnus919** [comment]
Try reproducing with the link I included above. [This other track](https://www.youtube.com/watch?v=An4uDegHB8s) works fine. Some content works, some doesn't.

**Comment by magnus919** [comment]
[Here](https://www.youtube.com/watch?v=WNDtb9ecWEs) is another example of a non-working track.

**Comment by sarthakmm** [comment]
I figured how to fix the problem that I had. For me, the button would turn yellow and say reauthenticate otherwise post on GitHub. I realised it was because in some tracks they are not recognised so it lets you edit and correct it. I had tried editing and accidentally only filled in the track name and not the artist as well. So I had to go into options of the plugin and delete the incorrectly filled information which made it go back to normal.

**Comment by sarthakmm** [comment]
Magnus919 the first song you commented saying isn't detected is because the video was uploaded under the category of **entertainment**. So if you have clicked scrobble music category in options it will not detect this video To fix it either you can select on the entertainment category as well or dis-select the music category option.

**Comment by inverse** [comment]
Closed as non-issue
