### ISSUE TITLE
the scrobbler works not correct

### ISSUE THREAD

**Issue by Tscharbo** [web-scrobbler/web-scrobbler#1637]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by Tscharbo** [comment]
The scrobbler scrobbels not all songs that i listen at deezer and bandcamp! they show me that i listen to the song, but they scrobbel not the song! This problem is since the last 3 days.
I listen at bandcamp a completly album with 10 tracks, but the scrobbler scrobbels only 7 songs! the same is at deezer...i scrobbel a playlist with 25 tracks and the scrobbler scrobbels only 19 tracks!
i check all songs in the extensionbar before i listen the songs! I don't know why the scrobbler not scrobbel all songs!

**Comment by OwnageIsMagic** [comment]
please provide album url
