### ISSUE TITLE
Gaana not scrobbling from certain plays

### ISSUE THREAD

**Issue by llamabanana** [web-scrobbler/web-scrobbler#1638]
The scrobbler no longer detects the current song that's being played on gaana.com UNLESS it's being played from a playlist or the song is played after playing from a favorited playlist first. 

### Expected behavior

I played a song by searching an artist and the song played fine, however it wasn't detected by the scrobbler. After fooling around with it, when I played a song from my favorites list instead of from the artist's page, it worked. It was the same song so I don't think it was a case of the song itself being weird. After doing this, when I played a song from the artist's page it was working again. So it somehow needs to be started by playing a song from my favorites list to detect that songs are being played?

### Steps to reproduce (for bugs)

Try to play a song from an artist's page:  https://gaana.com/artist/arijit-singh
            instead of detecting and scrobbling, it said nothing was being played
once I played something from my saved songs: https://gaana.com/myfavoritetracks
            the scrobbler started detecting all subsequent tracks

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
I don't have an account. Anyone able to reproduce issue?

**Comment by alexesprit** [comment]
Are you on Firefox?

**Comment by alexesprit** [comment]
Ok, I close this as inactive, and, probably, duplicate of #1450.
