### ISSUE TITLE
Scrobble Percentage Changed?

### ISSUE THREAD

**Issue by jeswontuka** [web-scrobbler/web-scrobbler#1639]
The scrobbler has always registered a scrobble at the 50% mark of a song, but recently it has started scrobbling at the 75% mark. I can't find any reason this happened or any options to change it back so I was just wondering if anyone knows how to fix this.

**Comment by alexesprit** [comment]
It's because of buggy repeat detection.

I'd get rid of this feature, and return the old way of repeat detection which works much better, but it doesn't support websites w/o track duration info.

**Comment by alexesprit** [comment]
It didn't changed. The extension should scrobble tracks approx. at 50% of their duratio (probably, more on high latency connections).
