### ISSUE TITLE
Chrome: dubtrack.fm not working for all soundcloud songs

### ISSUE THREAD

**Issue by Karpfador** [web-scrobbler/web-scrobbler#1646]
The extension will recognize youtube songs just fine, just not for all songs on soundcloud.
I noticed it with these for example:
https://soundcloud.com/bju/merianplatz
https://soundcloud.com/alone1official/x-anfield-you
Opening the exact same song on soundcloud does work on the other hand.

### Expected behavior
It should find soundcloud songs

### Current behavior
It does not scrobble all soundcloud songs on dubtrack.
I think this happens when a song only has a title without artist displayed on dubtrack. At least thats what the two songs I mentioned had in common

### Steps to reproduce (for bugs)
1. enter any room on dubtrack.fm
2. wait for a soundcloud song to play

### Environment
* Version used: 2.5
* Browser name and version: Chrome Version 67.0.3396.62

**Comment by inverse** [comment]
I'm unable to reproduce this issue :( both tracks work just fine for me.

**Comment by Karpfador** [comment]
I can reproduce it. Can you join a room on the site right now where I put them into queue?

**Comment by inverse** [comment]
Do any tracks from soundcloud get scrobbled? From what I've seen with limited testing is that it only takes the soundcloud track name, missing out the artist. which is why we cannot figure out the artist and don't scrobble.

**Comment by keerah** [comment]
At the moment dubtrack does not get scrobbled at all

**Comment by alexesprit** [comment]
Are any rooms are playing tracks from Soundcloud? Can't find the one to reproduce the issue.

> At the moment dubtrack does not get scrobbled at all

I have just opened dubtrack.fm and it works fine:
![image](https://user-images.githubusercontent.com/1119267/57181061-d853d300-6e97-11e9-8faa-8e049d67011f.png)

**Comment by alexesprit** [comment]
> I think this happens when a song only has a title without artist displayed on dubtrack. At least thats what the two songs I mentioned had in common

You're totally right, dubtrack doesn't show an artist name when a track from SoundCloud is playing. Unfortunately, we can't fix it, because dubtrack uses embedded SoundCloud player. I think it should be changed on dubtrack.fm side.
