### ISSUE TITLE
"|" not escaped correctly 

### ISSUE THREAD

**Issue by kimonoki** [web-scrobbler/web-scrobbler#1647]
In the youtube video the title with "I" is not scrobbled correctly 
For example in the audiotree's sessions the video title is 

> artist name - song name | Audiotree

 the detected song title is  

>song name |tree

can be reproduced with a video like [this](https://www.youtube.com/watch?v=cI2PIcKEldI)

**Comment by inverse** [comment]
We use the `-` char as the separator for artist - title which is why this happens.
