### ISSUE TITLE
Allow to fliter out keywords from scrobbling (SiriuxXM)

### ISSUE THREAD

**Issue by Mrjmbjmb** [web-scrobbler/web-scrobbler#1648]
I use the extension mainly for scrobbling SiriuxXM web player to last.fm.

On stations where there is a live DJ hosting the show and in between some songs the web player briefly displays content in rhe artist/track metadata thats is not related to an actual song such as:

SiriuxXMU Sessions - @TheRealYLT
fb.com/siriusxmu — @juliacunningham
SiriusXMU - #DL15

And this is just to name a few examples, each station has a bunch of those Artists/Track metadata that are not related to songs. The main problem is that some of these non-song metadata are wrongly recognized by last.fm as a song and scrobble to my account.

I think this problem would be easy to fix by having some sort of exclusion list where you can specify parameters that, if met, would not scrobble the current track. By example, I could say that when the artist is detected as 'SiriusXMU' the track would not be scrobbled.

Does this feature already exist or is it something you plan to addin the near future?

**Comment by alexesprit** [comment]
I suppressed scrobbling if artist contains "SiriuxXMU" (case insensitive) string.

There's no feature to add excludes manually. If you have more examples that should not be scrobbled, feel free to post them here. I'll add them in the connector code directly.
