### ISSUE TITLE
Doesn't scrobble from fip.fr

### ISSUE THREAD

**Issue by thegreekdude** [web-scrobbler/web-scrobbler#1650]
Even though "FIP" is included in the list under the options tab, and I have the box ticked, the extension doesn't scrobble any music from the fip online player fip.fr/player

If I click on the extension icon while I am on fip.fr I get this message: "This website is not supported
Web Scrobbler does not support scrobbling from this website." 

I haven't had a problem with scrobbling from any other site I've tried.

**Comment by inverse** [comment]
I created a PR to fix this which you can test by running unpacked (see readme).

**Comment by thegreekdude** [comment]
Thank you, did that but no change. Still "This website is not supported"

**Comment by arkhi** [comment]
I’d be interested to have this fixed as well. What kind of information can be provided to help resolve this issue?

**Comment by alexesprit** [comment]
It's fixed in 2ad41854356f3e80cb2f4c76980b8d6951c565ec.

You can add `*://fip.fr/*` as a custom URL pattern to fix it for yourself.

**Comment by arkhi** [comment]
Sweet!

Thanks for the quick heads up.

**Comment by arkhi** [comment]
`*://fip.fr/*` will not work if a user uses www.fip.fr, which I believe is the default URL when the player is linked, Adding `*://www.fip.fr/*` as well makes sure all corners are covered.

I can make a PR if you like.

**Comment by alexesprit** [comment]
You're totally right.

But I've found out I updated default pattern to `www.fip.fr` in another commit (1bcb70ba59200b2196b5b5b3874b85a302ffdc84).
