### ISSUE TITLE
Double scrobbles

### ISSUE THREAD

**Issue by jeffreeh** [web-scrobbler/web-scrobbler#1659]
Every time I pause a YouTube video, which I often do, and resume it later - it now counts as 2 scrobbles - even when ''listening'' to a few seconds of the song

**Comment by lacivert** [comment]
I have the same issue

**Comment by inverse** [comment]
Is this a common bug? anyone else experiencing this? Notice example patterns

**Comment by lacivert** [comment]
I think if I pause the youtube video for a long time, it sends once a scrobble data and then later when I continue, it sends scrobble again.

**Comment by lacivert** [comment]
Sometimes I open youtube video on new tab via middle click or 'ctrl' so tab creates but not opens. In this scenerio youtube video does not start to play but scrobbler starts to count. some time later I open the tab so video starts, and I suppose scrobbler count it again?

**Comment by marsjaninzmarsa** [comment]
> youtube video does not start to play but scrobbler starts to count

AFAIR this shoudn't possibly happen, scrobbler looks for playing status though...

**Comment by alexesprit** [comment]
YouTube connector doesn't recognize if a video is paused, that leads to this issue. This happens because of tricky mechanism of repeat detection.
