### ISSUE TITLE
AlbumArtist support

### ISSUE THREAD

**Issue by haeckle** [web-scrobbler/web-scrobbler#1662]
### Expected behavior
Scrobbling an album from e.g. bandcamp with different artists (like [this](https://feinestier.bandcamp.com/album/feines-tier-zoo-vol-1)) should lead to one album in last.fm (like [this](https://www.last.fm/de/music/Various+Artists/Feines+Tier+Zoo,+Vol.+1))

### Current behavior
Every artist of the album get an own album with the albumtitle but only their own songs in it (like [this](https://www.last.fm/de/music/The+Cheapers/Feines+Tier+Zoo+Vol.1))

### Possible solution
Also submit the albumartist

### Steps to reproduce (for bugs)
Scrobble the above mentioned album (or any other with various artists) with we-scrobbler.

**Comment by Maddieman** [comment]
I'd like to see this too.

**Comment by inverse** [comment]
@haeckle @Maddieman - just to clarify in the example URL listed.

artist would be - "Various Artists"
albumArtist would be - the actual artist

?

**Comment by haeckle** [comment]
albumArtist should be "Various Artists" and artist the actual artist oft the song, in this case "The Cheapers"

Thanks for your effort!

**Comment by alexesprit** [comment]
Closed via #2010.
