### ISSUE TITLE
Pandora no longer scrobbles

### ISSUE THREAD

**Issue by amar0q** [web-scrobbler/web-scrobbler#1663]
### Expected behavior

Pandora scrobbles a song

### Current behavior

The red last.fm logo says "Scrobbling is supported for this site!" but no scrobbling occurs.

### Steps to reproduce (for bugs)

1. Use pandora on Chrome
2.
3.

### Context

I was trying to listen to pandora and it didn't scrobble my music.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used: 2.5.0
* Browser name and version: Chrome 67.0.3396.99

**Comment by IRainman** [comment]
Same problem :(

**Comment by paladzin** [comment]
Same

**Comment by orionmerlin** [comment]
Happening to me as well.

**Comment by mwguthrie** [comment]
ditto
