### ISSUE TITLE
Pandora.com not scrobbling for Last.fm

### ISSUE THREAD

**Issue by James-W2** [web-scrobbler/web-scrobbler#1667]
### Expected behavior
When open Pandora in Chrome, the Last.fm icon is red.  Scrolling over it shows "this site is supported for scrobbling." When start a song, it should indicate being scrobbled or if info is missing.

### Current behavior
When start playing a song, nothing changes and piece is not scrobbled.  When click on icon, says to play some music.  When I click on Already Playing, states in part: The connector code for this specific website needs to be updated. You can navigate to the list of issues and see if this website is already reported.

### Steps to reproduce (for bugs)

As described above, even when closed Last.fm and Pandora and reopened both in Chrome, no change in behavior.  

See attached files for logs.

### Steps for resolving the issue
Closed tabs and browser and restarted, with no changes noted.

### Environment

* Version used: Using Windows 7 Pro.
* Browser name and version:  Chrome Version 67.0.3396.99 (Official Build) (64-bit) 

[Chrome Pandora Extention.docx](https://github.com/web-scrobbler/web-scrobbler/files/2157844/Chrome.Pandora.Extention.docx)
[Logs of content scripts.docx](https://github.com/web-scrobbler/web-scrobbler/files/2157845/Logs.of.content.scripts.docx)

**Comment by alexesprit** [comment]
It's known issue and it's already fixed.

**Comment by James-W2** [comment]
Please see my comment under Commit (98f23ac).
