### ISSUE TITLE
WS shows 'This site is unsupported' on every supported website

### ISSUE THREAD

**Issue by Arutemu64** [web-scrobbler/web-scrobbler#1668]
### Expected behavior
I should be able to see status of currently scrobbling track and be able to edit information when clicking the WS icon.

### Current behavior
Instead, I see 'This site is unsupported', however scrobbling itself works okay, I'm just not able to see and edit current track information.

### Possible solution
I don't know...

### Steps to reproduce (for bugs)
I'm using Firefox 62.0 Beta (currently running Beta 4, same thing happened on previous beta build too)

Here is a list of errors I see in debug log of WS while listening to music from GPM:
1. 'Unchecked lastError value: DataCloneError: The object could not be cloned. controller.js:446
notifySongIsUpdated
moz-extension://b5f7a1e5-bcfb-4a85-ab8b-51e373237235/core/background/controller.js:446:4'
2. 'Content Security Policy: Параметры страницы заблокировали загрузку ресурса data:font/woff;base64,d09GRgABAAAAAIw4AB... («font-src»).' (preferences of page prevents resource from being loaded)
3. 'Promise resolved while context is inactive apply.js:54 requestStyles moz-extension://889fd0ef-494e-464f-8131-83c39711d191/content/apply.js:54:7'

Then it logs my current song just fine!

### Context
This problem appeared kinda week ago.

### Steps for resolving the issue

I tried to remove the extension, wipe extension folder and stuff. That not helped.

- [X] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master (seems like recent commits are only connectors bug fixes, but since I don't have a problem with exact connector I don't think I need to try unpacked extension)

- [X] Check other issues for duplicates

### Environment

* Version used: 2.5.0
* Browser name and version: Firefox 62.0b4 (64-bit)

**Comment by alexesprit** [comment]
Is it only on Firefox beta? I tested the extension on Firefox Nightly (63), everything works fine.

**Comment by OwnageIsMagic** [comment]
![image](https://user-images.githubusercontent.com/10534634/43286789-bab24c86-912b-11e8-96f8-b96a8323c5b6.png)

FF 62.0b10 (64-bit)

**Comment by Arutemu64** [comment]
Seem to work again on FF 63 Beta and FF 64 Nightly

**Comment by myfonj** [comment]
Yup, for me it started to work again about a week or two ago, in Nightly 63 at that time and continues to work. So glad…

**Comment by inverse** [comment]
Is this an issue still?
