### ISSUE TITLE
Review for German translation needed

### ISSUE THREAD

**Issue by grandchild** [web-scrobbler/web-scrobbler#1673]
I translated everything [into German on Transifex](https://www.transifex.com/web-scrobbler/web-scrobbler/translate/#de/messagesjson/118669401), would be nice if someone else who speaks it could look it over and review it.

Sorry if Transifex notifies you guys separately and this issue is one notification too much.

### Expected behavior

Translation reviewed and ready to use.

### Current behavior

All strings are translated but 99% are unreviewed.

**Comment by alexesprit** [comment]
@inverse could you review the translation?

**Comment by inverse** [comment]
My German isn't 100% but can get my wife to check.

**Comment by grandchild** [comment]
Ask her if the word "Konnektor" is too weird a translation for "connector" -- I didn't use "Verbinder" in order to signify the "technicalness" of the thing, but maybe it's too techy.

**Comment by inverse** [comment]
She said it sounds weird "Verbindung" would be more suitable. 

That aside the rest seems reasonable. 

Also - people can contribute to fix :)

**Comment by grandchild** [comment]
OK, I changed everything to "Verbinder" ("Verbindung" is too much like "connection" as a state and not as an object for me, and these connectors feel more like objects imo).
I also reworded a few other ones. Should be better now..

**Comment by alexesprit** [comment]
@grandchild @inverse I suppose everything in the German translation is ok now, right? Can I copy the translation from Transifex to the repository? I don't know German, so I can't verify translated strings.

**Comment by inverse** [comment]
I think it should be good to go ;) people can suggest improvements if they see fit :)

**Comment by grandchild** [comment]
I went through some of them and changed them in insignificant places. It should be good to go as a start.
