### ISSUE TITLE
Deezer beta version isn´t working

### ISSUE THREAD

**Issue by fmpallini** [web-scrobbler/web-scrobbler#1678]
New Deezer style available at Deezer Labs tab at configuration page doesn't scrobble. Reverting to old style works.

**Comment by fmpallini** [comment]
The beta version uses a bottom div as player and not the sidebar anymore. I've tried to adjust the connector but don´t have enough js knowledge.

**Comment by inverse** [comment]
Interesting - Looks like we will have to support both players. I dont have a deezer account to test unfortunately :(

**Comment by wujekbogdan** [comment]
@inverse, @fmpallini 

> The beta version uses a bottom div as player and not the sidebar anymore. I've tried to adjust the connector but don´t have enough js knowledge.

Why don't you read the data from `window.document.title`?

**Comment by CTimmerman** [comment]
I clicked the blue notification bar for the new version, noticed Web Scrobbler didn't pick up me playing https://www.deezer.com/nl/album/48200562 and used this to get artist - track:

`$(".track-link:nth-child(1)").text() + " - " + $(".track-link:nth-child(2)").text()`

Which returns "Stand & Deliver - Airbourne".

**Comment by alexesprit** [comment]
I think it is resolved after #1735.
