### ISSUE TITLE
mixbla.st does not work?

### ISSUE THREAD

**Issue by akiramar** [web-scrobbler/web-scrobbler#1683]
### Expected behavior
Open the mixbla.st web page

### Current behavior
When opening the mixbla.st page on a web browser there is an error:
This site can’t be reached
mixbla.st’s server IP address could not be found.
Try:

Checking the connection
Checking the proxy, firewall and DNS configuration
Running Windows Network Diagnostics
ERR_NAME_NOT_RESOLVED

### Steps to reproduce (for bugs)
Open the page http://mixbla.st/ on any browser

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
I guess this site is dead
