### ISSUE TITLE
Track not recognized on Amazon Music India

### ISSUE THREAD

**Issue by dufferzafar** [web-scrobbler/web-scrobbler#1687]
### Expected behavior
The extension should correctly detect track information & scrobble it automatically.

### Current behavior
"The Track is not recognized" notification is showed every single time.

I then have to click the web-scrobbler icon in the toolbar, and click "Submit" manually every time.

Track information extractions seems to be working fine, as the info is already filled, and I just click submit. If the info was correctly identified, then why is the "Track Not Recognized" notification shown?

### Environment

* Version used: v2.6.0
* Browser name and version: Firefox 61.0.1

**Comment by inverse** [comment]
So everything is filled... could be that the artist doesn't exist on last.fm? got a link?

**Comment by alexesprit** [comment]
Logs, please.
