### ISSUE TITLE
Support YouTube TV browser interface (youtube.com/tv)

### ISSUE THREAD

**Issue by KatyLB** [web-scrobbler/web-scrobbler#1690]
Scrobbling does not currently work from the YouTube TV web browser interface (available at https://www.youtube.com/tv). This web interface is the only official way to remotely control YouTube, so it's ideal for playing music videos on a computer from a phone. It would good to be able to scrobble it and as it uses predictable artist and title patterns, it shouldn't work too differently to YouTube.

### Expected behavior
Tracks would be scrobbled the same way as they are from YouTube, but via the YouTube TV browser interface at youtube.com/tv instead.

### Current behavior
Scrobbling does not currently seem to be supported at youtube.com/tv.

### Possible solution
Implement scrobbling from youtube.com/tv, which should be possible as the video titles are displayed in much the same way as the main YouTube site.

### Steps to reproduce (for bugs)
Any video can be played at youtube.com/tv to verify the Web Scrobbler does not recognise it.

### Context
youtube.com/tv is the only way to play music remotely from a phone on desktop, and is very useful for watching music videos. Being able to scrobble them would be very useful.

**Comment by KatyLB** [comment]
![image](https://user-images.githubusercontent.com/37089178/44437160-a2441c80-a5b0-11e8-9f91-e3b2eb3e790e.png)
For reference, here is a screenshot of the interface. All of the information from regular YouTube is there and should be possible to parse in the same way.

**Comment by jaccarmac** [comment]
As noted at the bottom of that thread, I discovered that the alternative interfaces to YouTube seem not to use the same event infrastructure the existing connector depends on. That's where my work on #1231 stalled out, as I'm not familiar enough with the connector to rewrite it, which is what appears to be necessary to getting these corner cases to work uniformly.

**Comment by swimtrunks** [comment]
I think it would safe to close this since youtube tv has migrated to tv.youtube.com and only streams tv.
