### ISSUE TITLE
Can't get YouTube scrobbling working?

### ISSUE THREAD

**Issue by XPMai** [web-scrobbler/web-scrobbler#1691]
### Expected behavior
Scrobble YouTube music videos to Last.FM

### Current behavior
Icon says "This site is supported for scrobbling" but nothing happens?

### Steps to reproduce (for bugs)

```
chrome.storage.local = {"Core":{"appVersion":"1.52.1"},"LastFM":{"sessionID":null,"token":null}}
core/background/services/lastfm.js:52 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
getAuthUrl @ core/background/services/lastfm.js:52
core/background/services/lastfm.js:56 getToken response: <?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <token>djOGx9yE-iEU57Xq8eK5pfVPQPuMDltw</token>
</lfm>

core/background/notifications.js:163 Notification onClicked: aae1f339-f927-46a4-a11d-18abcb981375
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting connectors/v2/youtube.js
inject.js:107 	injecting core/content/starter.js
controller.js:320 Tab 932: created controller for connector: {"label":"YouTube","matches":["*://www.youtube.com/watch*","*://www.youtube.com/user/*"],"js":["connectors/v2/youtube.js"],"version":2}
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting connectors/v2/youtube.js
inject.js:107 	injecting core/content/starter.js
controller.js:320 Tab 932: created controller for connector: {"label":"YouTube","matches":["*://www.youtube.com/watch*","*://www.youtube.com/user/*"],"js":["connectors/v2/youtube.js"],"version":2}
3inject.js:120 -- subsequent ajax navigation, the scripts are already injected
main.js:97 Missing controller for tab 932 (should only happen for legacy connector)
getControllerByTabId @ main.js:97
_generated_background_page.html:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'onStateChanged' of undefined
    at chrome-extension://pncfaijgefbolbapchmpkfkjpgjelclh/core/background/main.js:145:10
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting connectors/v2/youtube.js
inject.js:107 	injecting core/content/starter.js
controller.js:320 Tab 932: created controller for connector: {"label":"YouTube","matches":["*://www.youtube.com/watch*","*://www.youtube.com/user/*"],"js":["connectors/v2/youtube.js"],"version":2}
core/background/notifications.js:163 Notification onClicked: caaaa785-9462-47eb-a539-a2606e7a1075
inject.js:79 -- loaded for the first time, injecting the scripts
inject.js:107 	injecting vendor/jquery-2.1.0.min.js
inject.js:107 	injecting vendor/underscore-min.js
inject.js:107 	injecting core/content/reactor.js
inject.js:107 	injecting core/content/connector.js
inject.js:107 	injecting connectors/v2/youtube.js
inject.js:107 	injecting core/content/starter.js
controller.js:320 Tab 932: created controller for connector: {"label":"YouTube","matches":["*://www.youtube.com/watch*","*://www.youtube.com/user/*"],"js":["connectors/v2/youtube.js"],"version":2}
```
1.
2.
3.

### Steps for resolving the issue

- [x] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by musictilldeath** [comment]
I have the same problem, nothing helps

**Comment by rohitps** [comment]
Same here

**Comment by dreamingbleu** [comment]
Same problem here, i'm using this extension at Opera.

**Comment by alexesprit** [comment]
> chrome.storage.local = {"Core":{"appVersion":"1.52.1"},"LastFM":{"sessionID":null,"token":null}}

These logs are from version 1.52.1 which is not supported.

v2.6.0 works fine with Youtube.

**Comment by dreamingbleu** [comment]
I have this problem, when i try to scrobble a youtube video it says "This site is supported for scrobbling" but it doesn't scrobble!
This problem is happening with the v2.6.0 at Opera but at Chrome it works fine.

**Comment by WCBROW01** [comment]
I'm having this issue, but only on the new site.

**Comment by XPMai** [comment]
>These logs are from version 1.52.1 which is not supported.
>
>v2.6.0 works fine with Youtube.

Ohh. How can I get the latest version of this plugin? It's newly installed

@XenHat yeah, I tried finkering the settings but it didn't work

**Comment by inverse** [comment]
Could you provide a sample URL?

**Comment by James-W2** [comment]
I'm using Chrome.  After reinstalling the scrobbler extension I got YouTube to scrobble again. It works for the most part with YouTube, but I'm finding certain music videos will not scrobble while others will.  Example of one **not scrobbling** is: https://www.youtube.com/watch?v=Y2GT8Iu6fro.  I'm wondering if the problem videos are ones that are part of a "mix" or "playlist?"  I tried the tricks that @XenHat suggested, but without any changes.

**Comment by XPMai** [comment]
https://www.youtube.com/watch?v=BVn1XdSSz7w ?

It never worked for me :/

**Comment by XPMai** [comment]
> After updating to 2.9.0 in Chrome I'm able to scrobble YouTube well. Even scrobbled above video you were having problems with. See also Issue #1788.

sorry, how to update? Doesn't it auto-update?

**Comment by James-W2** [comment]
Chrome itself auto-updates, but not individual extensions apparently.  There's no extension update feature I could find in Chrome, so I had to delete my old extension version and go to the Chrome store and reinstall the most recent version. Maybe someone else has a better way of updating this extension??
