### ISSUE TITLE
SiriusXM webplayer scrobbling

### ISSUE THREAD

**Issue by jonlandry** [web-scrobbler/web-scrobbler#1696]
### Expected behavior
Would like to be able to scrobble from https://player.siriusxm.com/

### Current behavior
Currently not available

### Possible solution
Add SiriusXM web player scrobbling support

### Context
Sorry if this has been asked or requested before- I did try to find a previous request to no avail before posting.

**Comment by inverse** [comment]
We already support this site. I'm guessing it's broken.

**Comment by jonlandry** [comment]
This is now working correctly for me.
