### ISSUE TITLE
Clyp.it Support

### ISSUE THREAD

**Issue by Spekular** [web-scrobbler/web-scrobbler#1697]
It'd be nice if scrobbling worked on Clyp.it.

For context, I compared the global alexa ranks of some less popular sites that are already supported. In other words, I picked sites where Clyp would compare favorably. 😅

##### Global Alexa Rank (Lower is Better)

- Anghami: 12,215
- Clyp.it:  26,898
- Soma.fm: 56,171
- Freegalmusic: 96,909
- Listen.moe: 366,585

**Comment by inverse** [comment]
@Spekular How would we handle supporting extracting meta data?

e.g. https://clyp.it/zu41oxts

What would be the artist and what would be the title in this case?

**Comment by Spekular** [comment]
I get the feeling there's something to this question that I'm missing, but:

Artist: LØST PHO3NIX
Title: "Thoughts of You" feat. Heather Winn (V3)

The title here isn't exactly ideal I guess, if that's what you're pointing out? I feel like the same issue applies to many Soundcloud and Youtube uploads though, and it's just something you have to live with on sites like that.

**Comment by inverse** [comment]
That makes sense - I guess we can work with this and apply similar filters like what we do with YT and SC.

Thanks for getting back!
