### ISSUE TITLE
Soundcloud not scrobbling unlisted tracks

### ISSUE THREAD

**Issue by cameronjonesweb** [web-scrobbler/web-scrobbler#1699]
Looking at the [code](https://github.com/web-scrobbler/web-scrobbler/blob/ed86e78afa4dbf2965da3760a6178158941b3347/src/connectors/soundcloud.js#L51), this might be intentional?
Unlisted, won't work:
https://soundcloud.com/user-812554612/10-beartooth-infection/s-GXQi4
Public, works:
https://soundcloud.com/solid-state-records/demon-hunter-the-heart-of-a-graveyard

**Comment by inverse** [comment]
I believe this was intention. Sounds like it'll make more sense to be a user configurable option of the connector.

**Comment by alexesprit** [comment]
I updated the way the extension gets track info from SC in 96c569035af0698dbf1e270d1769bafc1f5bfcdd. That means it does not recognize anymore if a track is unlisted or not. So, for now the issue is resolved.

We will probably move the previous way back, so I'll keep the issue opened for a while.
