### ISSUE TITLE
last.fm authentication issues

### ISSUE THREAD

**Issue by Madbrad200** [web-scrobbler/web-scrobbler#1700]
Can't login to last.fm

### Current behavior
Whenever you attempt to "sign in" to last.fm it results in an authentication error.

### Steps to reproduce (for bugs)

Right click extension symbol in the top bar > options > accounts > under "Last fm" click sign in

**Comment by inverse** [comment]
Still an issue? What error message is displayed?

**Comment by Madbrad200** [comment]
Hey @inverse yeah it's still an issue, same error as above: Authentication Error: "Unable to sign in to Last.fm. Please try later"

I'm using Cent Browser, could be that? It is chromium though so I don't see why

**Comment by alexesprit** [comment]
Logs?
