### ISSUE TITLE
Somafm not scrobbling

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#1707]
Scrobbling not working on https://somafm.com/

### Expected behavior
Extension should scrobble current music

### Steps to reproduce (for bugs)
Go to https://somafm.com/ and play a radio, like http://somafm.com/player/#/now-playing/dronezone

1.
2.
3.

### Environment
* Version used: Web Scrobbler 2.5.0
* Browser name and version: 63.0b4 (64-bit) Mac OS

**Comment by myfonj** [comment]
Works for me in Nightly 64.0a1 with Web Scrobbler 2.6.0.  Could you update?

**Comment by inverse** [comment]
It's working for me too :(

**Comment by pedrojvaz** [comment]
I confirm that, after the update, it started working

![somafm_player__groove_salad](https://user-images.githubusercontent.com/4522620/45511119-6578d900-b79c-11e8-867d-647811aaafaa.png)

**Comment by inverse** [comment]
p.s. awesome choice of radio ;)

**Comment by pedrojvaz** [comment]
Soma stopped working again on FF. Shall I create a new issue or update this one?

**Comment by inverse** [comment]
A new issue would be better :+1:
