### ISSUE TITLE
Deezer beta player not scrobbling

### ISSUE THREAD

**Issue by wujekbogdan** [web-scrobbler/web-scrobbler#1708]
I have enabled the beta version of Deezer player and updated Google Chrome. 

### Expected behavior
web scrobbler is scrobbling

### Current behavior
web scrobbler is not scrobbling :)

### Possible solution
I'm not aware of any solution.

### Steps to reproduce (for bugs)
It happens always. 

### Context
I'm not sure when it started, it might be related to Chrome v69 update but also with Deezer beta player change.

**EDIT:**
I've disabled the beta player and now scrobbling works, so it's definitely the beta player's fault. 

### Environment

Chrome 69.0.3497.81, macOS 10.13.6

**Comment by fmpallini** [comment]
Duplicated. I´ve reported it in the past. #1678

**Comment by inverse** [comment]
Closed as dupe
