### ISSUE TITLE
NRK Radio not scrobbling anymore

### ISSUE THREAD

**Issue by hbhc** [web-scrobbler/web-scrobbler#1716]
Hello all,

https://radio.nrk.no/ stopped scrobbling a while ago. I have no idea how to fix this. Can anyone help?

Thanks.

**Comment by KatyLB** [comment]
Also isn't working for me.

**Comment by alexesprit** [comment]
They changed website layout, and the extension should be changed too.

**Comment by hbhc** [comment]
They have changed the player once again. Help?

**Comment by inverse** [comment]
@hbhc please open a new issue
