### ISSUE TITLE
http://hqradio.ru / radiorecord.eu

### ISSUE THREAD

**Issue by szufla** [web-scrobbler/web-scrobbler#1717]
Hello world!

Web scrobbler used on chrome does not detect any music playing on 
http://hqradio.ru / radiorecord.eu
Extension shows that it is possible to scrobble from this site, but it does not happen.

### Expected behavior

Site http://hqradio.ru / radiorecord.eu is on the list of compatible soureces. It should scrobble.

### Current behavior

Extensions shows that it is possible to scrobble from http://hqradio.ru / radiorecord.eu but this is not happening.

### Possible solution

Update the code becouse something has changed on http://hqradio.ru / radiorecord.eu

### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by alexesprit** [comment]
Sorry, I didn't notice it's a bug report. We have `hqradio` connector some time ago, but it was broken, and I removed it. I'll move it back.
