### ISSUE TITLE
Update Radioparadise.com because of web site update

### ISSUE THREAD

**Issue by TokeRider** [web-scrobbler/web-scrobbler#1718]
Please update scrobbling for new.radioparadise.com.  They recently updated their web player(and it's awesome) to a new format that doesn't get songs scrobbled by Web Scrobbler.  Thank you.

**Comment by JeonHyungJin** [comment]
I updated [Radioparadise](https://www.radioparadise.com) `s source code.
So now this program will support this web site :)
I made [new PR](https://github.com/web-scrobbler/web-scrobbler/pull/1729) for this.

**Comment by alexesprit** [comment]
I think it was resolved already as the extension supports two player types (btw, the old one is gone, right?).

**Comment by TokeRider** [comment]
Yes the old one is gone.
    On Tuesday, April 23, 2019, 3:55:10 PM EDT, Alexey <notifications@github.com> wrote:  
 
 
I think it was resolved already as the extension supports two player types (btw, the old one is gone, right?).

**Comment by alexesprit** [comment]
Legacy player is available on legacy.radioparadise.com, but I broke support for that addresses. :D Not sure if we need to keep support.
