### ISSUE TITLE
please update deezer.com because of web player update

### ISSUE THREAD

**Issue by marcela666** [web-scrobbler/web-scrobbler#1719]
Please update scrobbling for deezer.com. They recently updated their web player to a new format that doesn't get songs scrobbled by Web Scrobbler. Thank you.

**Comment by Ivan-Roger** [comment]
As of today it still doesn't work so I guess not

**Comment by JeonHyungJin** [comment]
I think that it is why the updated code was not distributed yet.
I saw this issue and i tried to solve but when i compile web-scroller as now code(after fixed about that web site) it works very well!
Maybe you have to wait to republished new version. :)
