### ISSUE TITLE
Radio Paradise need update to web player.

### ISSUE THREAD

**Issue by TokeRider** [web-scrobbler/web-scrobbler#1732]
The previous ticket #1718 fixed the basic player on the homepage, however there is a separate web player with more features located at https://new.radioparadise.com/player.  This player isn't working with Web Scrobbler and needs to be fixed.  Thanks!

**Comment by alexesprit** [comment]
This URL redirects to https://radioparadise.com/player. Now the extension recognizes this URL and the issue is resolved.
