### ISSUE TITLE
ListenOnRepeat.com does not register scrobbles

### ISSUE THREAD

**Issue by MrKaKisen** [web-scrobbler/web-scrobbler#1736]
ListenOnRepeat.com does not register scrobbles despite stating site is supported.

This issue has been opened earlier, #1564 but I am unsure if it was fixed. Looks like the issue just got closed.

Described issue has been tested on two different devices (one running Linux and one running Windows).

### Expected behavior
Should register scrobbles as usual.

### Current behavior
As the initial description explains, the extension does not register that the song has started to play (even though it says "site supported").

### Possible solution
Either fix the connector or remove as supported site.

### Steps to reproduce (for bugs)
1. Visit ListenOnRepeat.com
2. Search for a song to play
3. Play it

Seems like the extension is able to register that the song is playing, but not enough information about the track.

```
Tab 1899029529: State from connector doesn't contain enough information about the playing track: {
  "track": null,
  "artist": null,
  "album": null,
  "uniqueID": null,
  "duration": null,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": null
}
```

Is it possible the site has recently changed?

### Context
ListenOnRepeat is a useful website if you're repeating a song several times and wan't that to be scrobbed to for example Last.fm. It uses YouTube.

### Steps for resolving the issue
- [x] Reauthenticate on Last.fm
- [x] Check other issues for duplicates

### Environment
* Version used: 2.6.0
* Browser name and version: Google Chrome for Linux 69.0.3497.100 and Google Chrome for Windows 69.0.3497.100.

**Comment by inverse** [comment]
Looks like it was previously resolved but now broken.
