### ISSUE TITLE
Connector needed for Radioparadise.com

### ISSUE THREAD

**Issue by nelsonhall53** [web-scrobbler/web-scrobbler#1744]
The new web player at https://new.radioparadise.com/player is not scrobbling.

I am expecting scrobbles, but nothing happens with the Web-Scrobbler Chrome extension when playing music from this site. 

Creating a connector for this site will resolve the issue.

This issue appears on Windows 10, Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by inverse** [comment]
Fixed on master - should be in the next release
