### ISSUE TITLE
Plex Web update broke track name recognition

### ISSUE THREAD

**Issue by krateng** [web-scrobbler/web-scrobbler#1755]
After Plex' [update 3.73.1 to its web application](https://forums.plex.tv/t/plex-web/20528/255), using the web scrobbler and Plex Web results in the album title being scrobbled as both album title and song title.

On editing the song title for the scrobbler, the new title is now also scrobbled as song title for subsequent different tracks by this artist. Playing a song by another artist resets the scrobbling to the original pattern (album as title).

### Possible solution

I can't test it, and I have never looked into the architecture of the scrobbler, but the new HTML element for the title seems to be the first a element under PlayerControlsMetadata-container-*. So, the following line 53 in src/connectors/plex.js:

    Connector.trackSelector = `${Connector.playerSelector} [class*=titlesContainer] > a`;

might be replaced with

    Connector.trackSelector = `${Connector.playerSelector} [class*=PlayerControlsMetadata-container] > a:nth-child(1)`;

### Environment

* Version used: v2.6.0
* Browser name and version: Vivaldi 1.14.1077.60 (Stable channel) (64-bit)

**Comment by Botanistt** [comment]
+1
Please fix this.
