### ISSUE TITLE
Deezer.com not working anymore

### ISSUE THREAD

**Issue by parigi-n** [web-scrobbler/web-scrobbler#1756]
So https://www.deezer.com just got a new HTML5 player and it's not working anymore. 
Would be perfect if you could update the scrobbler !

**Comment by hans-juergen** [comment]
You can disable the new web player layout in the Deezer Labs tab and/or settings of the new player, as the old layout still works with the browser extension. Of course it would be nice if it could also support the new player. See also [my related posting](https://getsatisfaction.com/lastfm/topics/deezer-down?topic-reply-list[settings][filter_by]=all&topic-reply-list[settings][reply_id]=19799416#reply_19799416) on Get Satisfaction.

**Comment by inverse** [comment]
Should be fixed on master and will be in the next release.

**Comment by hans-juergen** [comment]
Thank you very much. :-)

**Comment by ExpandingShapes** [comment]
thank you very much for your temporary fix! 
looking forward for the update.
Have a nice day!

**Comment by inverse** [comment]
Should be fixed!

**Comment by hans-juergen** [comment]
Indeed, scrobbling works with version 2.7.0 and the new layout of the Deezer web player. Thanks again!
