### ISSUE TITLE
https://www.youtube.com/watch?v=Wf9NRFFonzI

### ISSUE THREAD

**Issue by mum1234567** [web-scrobbler/web-scrobbler#1760]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by stephanebruckert** [comment]
?

**Comment by inverse** [comment]
Not sure what is meant by this? The video linked doesn't look like music.
