### ISSUE TITLE
Radio Paradise New player

### ISSUE THREAD

**Issue by PilcrowPilcrow** [web-scrobbler/web-scrobbler#1762]
Hi,

Radio Paradise has a new web player https://new.radioparadise.com/player and unfortunately it seems that it is not supported by the scrobbler. The scrobbler worked with the old player perfectly.

Could you please fix it?

Thanks!

**Comment by inverse** [comment]
A fix is already made and will be included in the next release.

**Comment by PilcrowPilcrow** [comment]
> A fix is already made and will be included in the next release.

Great, many thanks!

**Comment by pawel-zun** [comment]
> A fix is already made and will be included in the next release.

Could you please define approx. term of this release? :)

**Comment by inverse** [comment]
Its out of my control pending another core developer. If you want to run the extension unpacked feel free!

**Comment by inverse** [comment]
It's deployed!
