### ISSUE TITLE
Would it be possible to incorporate the Youtube player on this site?

### ISSUE THREAD

**Issue by Caramacks** [web-scrobbler/web-scrobbler#1772]
I wondered how I can or if it could be possible to scrobble the Youtube Player in rooms on https://www.ezcapechat.com ? Currently I can't seem to get it to work through custom URLS and I don't know if this is due to the pop-out player not showing the toolbar/extensions on the Chrome window or something else.

### Expected behavior
Scrobbling for the Youtube Player on Ezcapechat. 

### Current behavior
No scrobbling.

### Steps to reproduce (for bugs)
You can visit the 'main room' as a guest at https://www.ezcapechat.com/rooms/chat and open the Youtube Player by clicking the Youtube logo on the bottom right just above the text entry box.. I am using Chrome.

Thank you for your time, it is very much appreciated!

**Comment by alexesprit** [comment]
I can't find any players to scrobble. There's no YouTube logo in the bottom right corner. Probably, it's because of Flash player not being loaded. If it's in Flash container, we cannot implement the connector.
