### ISSUE TITLE
spotify has stopped recognizing songs

### ISSUE THREAD

**Issue by nvh61** [web-scrobbler/web-scrobbler#1774]
Hello, I'm using web scrobbler such a long time but today on my two PC spotify has stopped recognizing songs and a gray question mark appears next to the tracks. This only happens with songs played by the spotify web, every oter site recognizing songs properly.

**Comment by mjmaurer** [comment]
It's doubling the track name when trying to scrobble. I don't see any related commits, so I'm guessing Spotify changed something on their end

![scrobble](https://user-images.githubusercontent.com/3537081/47818088-af5a5600-dd2d-11e8-9c34-a016f2ee48d9.png)

**Comment by crinabucur** [comment]
Same here - the track name gets doubled on Spotify

![image](https://user-images.githubusercontent.com/2715895/47917116-279d5480-deb1-11e8-9e38-7439a396d91e.png)
