### ISSUE TITLE
YouTube won't scrobble my music anymore? 

### ISSUE THREAD

**Issue by DEADicatedMedia** [web-scrobbler/web-scrobbler#1779]
YouTube won't scrobble any of my music, wondering if the extension needs updating? 

### Expected behaviour
It should scrobble the tracks or at least try to search for them.

### Current behavior
It does not scrobble tracks and it doesn't even try to search for them.

### Steps to reproduce (for bugs)
This is a song that has always scrobbled before but does not at the moment, I also checked a lot of trending music.
https://www.youtube.com/watch?v=-nQessUrdk0

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
It's working for me - is this still an issue?

**Comment by Bourscheid** [comment]
It's working for me too

**Comment by dubwoc** [comment]
Not working for me.

**Comment by Whateverthing** [comment]
This has been a problem for me too. It used to work really well for me. But now it just says: "This site is supported: Play some music..." and doesn't recognize anything as a valid track.

**Comment by ksbrar** [comment]
Not working for me either.

**Comment by James-W2** [comment]
See the fix that worked for me at #1788

**Comment by ksbrar** [comment]
@James-W2 Thanks for the ref! But updating Chrome and even reinstalling Web Scrobbler to ensure v. 2.8.1 does not resolve it for me (on any YouTube videos - even official music videos).

**Comment by ksbrar** [comment]
@inverse Just updated to 2.9.0 and its working for me. Thanks!
