### ISSUE TITLE
Pandora no longer scrobbles

### ISSUE THREAD

**Issue by amar0q** [web-scrobbler/web-scrobbler#1780]
I noticed today that Pandora has stopped scrobbling again.

### Expected behavior

Pandora scrobbles songs.

### Current behavior

The extension says "This website is not supported"

### Steps to reproduce (for bugs)

Go to Pandora. Play a song.

This is on Chrome 68.0.3440.106

**Comment by alexesprit** [comment]
Any logs?

**Comment by James-W2** [comment]
I'm having **no problems** with Pandora.  I'm Using Google Chrome Version 70.0.3538.102 (Official Build) (64-bit) and Web Scrobbler 2.8.1 (also worked well with Web Scrobbler 2.6.0.  Scrobbling music and ads as always has.

**Comment by amar0q** [comment]
I'm actually not having any problems either. I'm not sure what the issue was those few days but it's not here anymore.
