### ISSUE TITLE
SiriusXM no longer scrobbles

### ISSUE THREAD

**Issue by jblattnerNYC** [web-scrobbler/web-scrobbler#1781]
Scrobbles have not registered since the re-design of the SiriusXM web player at https://player.siriusxm.com

**Comment by seferyetzirah** [comment]
Scrobbles had been working for sirusXM, but have ceased as of yesterday using multiple browsers with this extension (opera, chrome, vivaldi).

**Comment by jblattnerNYC** [comment]
Scrobbling worked on Google Chrome for me until yesterday but now, as stated above, the service is no longer available from any browser

**Comment by andrewc2** [comment]
![image](https://user-images.githubusercontent.com/7347608/51041442-f19edf80-1587-11e9-89db-c01f711ffcda.png)

I'm not sure why it isn't working, from what I can see everything is still named the same as it was before.

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/57579686-3db34f80-74a8-11e9-8f7b-eea7273dc5cd.png)
