### ISSUE TITLE
Radio Paradise New Player Not Working

### ISSUE THREAD

**Issue by TokeRider** [web-scrobbler/web-scrobbler#1782]
The [new player](https://new.radioparadise.com/player) for Radio Paradise at https://new.radioparadise.com/player is not scrobbling correctly.  The change log says this was fixed in 2.7.0, however it's still not working.
### Expected behavior
Songs should scrobble.

### Current behavior
The first song scrobbles, but after that scrobbling doesn't work.

### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
Sorry about that - could you try the branch I created and see if that resolves it. I briefly tried locally and it works.

**Comment by TokeRider** [comment]
Update:  There is still a problem with the scrobbling.  When manually skipping songs it will scrobble.  When the songs are playing automatically it's not detecting the song change and scrobbling the song.

**Comment by TokeRider** [comment]
Update 2:  It is scrobbling with both manually skipping songs and when they're automatically played.  It is not consistently working is what the problem is now. I'll try some more and try to isolate the condition causing the inconsistency and provide an update.

**Comment by inverse** [comment]
I'll see what I can do to resolve the song transition part

**Comment by inverse** [comment]
@TokeRider try the latest changes and let me know how it goes. If everything is good I'll merge this one!

**Comment by TokeRider** [comment]
The latest changes don't scrobble at all for me.  The previous changes worked, but inconsistently.

**Comment by TokeRider** [comment]
I figured out the problem.  The ; was missing after } on line 34.

**Comment by inverse** [comment]
Are you sure there is anything wrong? There is only 32 lines in the file. It works for me with what's on the PR

**Comment by TokeRider** [comment]
I'm seeing 34 lines in the file.  Am I looking at the wrong one?  https://github.com/web-scrobbler/web-scrobbler/pull/1785/commits/2226b4d332f41996fb8e109ee1815e8fab97e160

**Comment by TokeRider** [comment]
It's working for me now.   I rebooted my PC.  I guess Chrome was holding on to an old copy of the connector?

**Comment by inverse** [comment]
Will be in the next release - glad it was properly resolved this time!

**Comment by TokeRider** [comment]
Thanks for your work on this.  I tried to help the best I could.  Cheers!
