### ISSUE TITLE
Youtube: song title is recognized as artist name and vice versa

### ISSUE THREAD

**Issue by pseena** [web-scrobbler/web-scrobbler#1787]
Song title and artist name are recognized vice versa from some youtube videos 

### Current behavior
I scrobble video e.g. https://youtu.be/1eqhCEcQHhA
It is entitled in format Song title - Band name
In the scrobble history it goes with song title instead of band name and vice versa
https://www.screencast.com/t/ZAGkypm7VjV

### Possible solution
Add recognition, which of two values derived from youtube video title is the artist name with more probability (smth like comparing to knows artists in last.fm DB or getting info from video metadata)
Also a nice-to-have from example of this video - remove quotes from song/artist, if there are any in the youtube title

### Environment

* Version used: Web Scrobbler 2.7.0
* Browser name and version: Google Chrome 70.0.3538.77 (Win 7)

**Comment by inverse** [comment]
Most tracks follow the Artist - Track format which is why this is difficult. We could look into seeing if there is anything else we can do.

**Comment by ChineseOuchie** [comment]
Is it possible to search for "description-extra" in the description box?

Here is an image example https://prnt.sc/lvewk7

**Comment by alexesprit** [comment]
The only solution is extract data from the "Music in this video" section. This is proposed in #1904.

**Comment by jwozera** [comment]
I'm with this same problem, in my case BROCKHAMPTON put all their songs first, and the group name after. XD

I wonder if the RegEx importer could solve something like that. Do you guys find any solutions or have any suggestions?
