### ISSUE TITLE
Spotify stops scrobbling

### ISSUE THREAD

**Issue by Wunny12** [web-scrobbler/web-scrobbler#1789]
Hello I have that same problem like in this locked topic https://github.com/web-scrobbler/web-scrobbler/issues/1774 There are any chance to fix this problem or I should go looking for another plugin to scrobble?

**Comment by mikelin52** [comment]
Yep same here, would be nice if they fixed it

**Comment by inverse** [comment]
That issue was closed as master now has the fixes required. It will be in the next release to the Chrome store

**Comment by inverse** [comment]
Should be resolved.
