### ISSUE TITLE
Same video scrobbled differently on Youtube and Youtube Music

### ISSUE THREAD

**Issue by reitzig** [web-scrobbler/web-scrobbler#1795]
Let's have a look at two versions of the same video.

 * Watching on [youtube.com](https://www.youtube.com/watch?v=x0RV0kgdqJU), it scrobbles as:

	>  [Leo Moracchioli feat. Mary Spender](https://www.last.fm/music/Leo+Moracchioli+feat.+Mary+Spender) — Sultans of Swing 

	The artist is not ideal -- we'd want [Leo Moracchioli](https://www.last.fm/music/Leo+Moracchioli) -- but fair enough.

* However, on [music.youtube.com](https://music.youtube.com/watch?v=x0RV0kgdqJU), it scrobbles as:

	> [Leo](https://www.last.fm/music/Leo) — Sultans of Swing (Metal Version) (feat. Mary Spender) 

	Now that's a _very_ different artist!

	No wonder, those seem to be the data Youtube Music provides:

	![image](https://user-images.githubusercontent.com/4246780/48252580-7133f500-e405-11e8-9993-43c32e0a6ee0.png)
	![image](https://user-images.githubusercontent.com/4246780/48252585-75601280-e405-11e8-8724-354de63a1fb0.png)
	![image](https://user-images.githubusercontent.com/4246780/48252606-7ee97a80-e405-11e8-8a08-ccb880c75acd.png)

	(Note the different variants even _within_ the app. D'oh.)

I don't see a robust way to resolve this, given what Youtube Music provides (now).

Could the scrobbler maybe use the ID to query youtube.com about the track information? Internally, web-scrobbler treats music.youtube.com like youtube.com, so the video title from youtube.com should always be the better choice (in the sense of "contains what the addon expects").

**Comment by inverse** [comment]
If a video ID is exposed in theory we could use their data API to get more information if that's exposed in the video.

**Comment by jaccarmac** [comment]
Interesting idea for sure. As you noted I chose one of the slightly different sources of information to use. It wasn't a random choice, the playlist view is the only place where the format is consistent. Querying YouTube as a canonical source would be roughly equivalent, and unfortunately there's no great way to solve the problem "properly" as YouTube is a very fuzzy data source. Personally I'm sympathetic to my own solution as Google seems to be adding metadata to YouTube for YT Music purposes, but that they'll finish doing it is far from certain.

**Comment by reitzig** [comment]
Yeah, I noticed some flat-out wrong meta data on Youtube Music; apparently Google's heuristics are (very) faulty. Maybe that can't be avoided.

Another idea to circumvent this would be to leverage last.fm data: as an option (?), only scrobble if the track already exists (and is of "good enough quality", if that's possible to determine) on last.fm; otherwise ask the user what to do.

**Comment by alexesprit** [comment]
> Another idea to circumvent this would be to leverage last.fm data: as an option (?), only scrobble if the track already exists (and is of "good enough quality", if that's possible to determine) on last.fm; otherwise ask the user what to do.

This is default behavior. It does not work properly, because Last.fm's database is full of garbage (literally, it detects obviously wrong data as a valid song).

> If a video ID is exposed in theory we could use their data API to get more information if that's exposed in the video.

Using YouTube API is not solution; API have limitations (don't know exact numbers, but we reach this daily limit in few hours).
