### ISSUE TITLE
Not Scrobbling from Youtube

### ISSUE THREAD

**Issue by slipstream001** [web-scrobbler/web-scrobbler#1805]
### Expected behavior
Youtube music video should scrobble.

### Current behavior
Can't get any videos in Youtube to scrobble.

### Possible solution
Fix something with youtube scrobbling code

### Steps to reproduce (for bugs)
1. Open yt vid
2. wait for scrobbler
3. oh wait it's broken

### Context
Happens on all videos for me.

### Environment
Running Chrome 70.0.3538.77 on MacOS Mojave with the latest OS update.

**Comment by saverag** [comment]
Same issue with Firefox

**Comment by inverse** [comment]
Potential fix - anyone else able to test?
