### ISSUE TITLE
Add support for Primephonic web player

### ISSUE THREAD

**Issue by RyanDBooker** [web-scrobbler/web-scrobbler#1815]
Add support for the Primephonic web player: https://play.primephonic.com/

**Comment by KwonDae** [comment]
Hi RyanDBooker.
I added the site and tested it, but there were some problems.

1. I don't know if chrome web browser and safari browse are not supported, but it won't play.
like, 
![image](https://user-images.githubusercontent.com/33443660/49189987-d4d19280-f3b3-11e8-9d75-5e2a6d17c512.png)

2. 
I try to add the site and test it, but it doesn't play like  1, so I can't test it.
![image](https://user-images.githubusercontent.com/33443660/49190015-e9158f80-f3b3-11e8-9298-3bc9cd0a5365.png)

My Chrome version is 70.0.3538.110.
If there is any browser that Primephonic web player supports, I would appreciate it if you let me know.

**Comment by RyanDBooker** [comment]
Hello KwonDae,

That's very strange. I am successfully able to play using the Primephonic web player in Chrome version 70.0.3538.110 and also in Safari version 12.0.1 on MacOS.

**Comment by KwonDae** [comment]
Me too, Chrome version 70.0.3538.110 and also in Safari version 12.0.1 on MacOS.
But, the problem still exists.
I can't find why Unable to play audio stream problem.

**Comment by NamJinWoo** [comment]
Hi Ryan, this is Jinwoo. I've looked at it, and the same problem happens to me as it happened to @KwonDae.
I am not sure why this happens.
![image](https://user-images.githubusercontent.com/36990340/49263446-ec7d4980-f48d-11e8-8049-134e5bcf3263.png)
My chrome version is  70.0.3538.110 on MacOS.

**Comment by RyanDBooker** [comment]
Unfortunately, I haven't been able to recreate this; Primephonic plays in every browser I've tried. If I disable Javascript or cookies, I'm not even able to get to the player page. Perhaps the problem is related to an ad or other content blocker?

**Comment by KwonDae** [comment]
I think it is a phenomenon caused by blocking by ip.

**Comment by Maddieman** [comment]
It looks like Primephonic is only available in a limited number of countries (probably due to licensing reasons) - namely: Netherlands, United Kingdom, and United States. So you'd probably need a vpn to test outside of those countries.

https://primephonichelp.zendesk.com/hc/en-us/articles/360007144711-In-which-countries-can-I-access-Primephonic-

Someone else requested Primephonic support in the last.fm forums recently: https://getsatisfaction.com/lastfm/topics/primephonic-support
