### ISSUE TITLE
Xiami's design changed

### ISSUE THREAD

**Issue by cptchi** [web-scrobbler/web-scrobbler#1817]
Hi, Xiami just went through a huge redesign and the player isn't on a different tab anymore, so the scrobbler isn't working.

**Comment by KwonDae** [comment]
#1818 
I changed some code about Xiami.
please check my codes and If there's anything wrong, I'd appreciate it if you let me know.

**Comment by fanmuxxx** [comment]
Hi, I know this has been brought up a few weeks ago. However, my scrobbler doesn't work on xiami in the recent 3 days, and it was totally OK last week. Could someone please have a test and let me know?

**Comment by inverse** [comment]
@KwonDae any input on this?

**Comment by KwonDae** [comment]
No, i haven't. Is there any problem in xiami.com?

**Comment by fanmuxxx** [comment]
please see my last comment. My scrobbler doesn't work on https://www.xiami.com/play page

**Comment by KwonDae** [comment]
Because xiami.com/play was changed to xiami.com. 
xiami.com/play doesn't supported until page updated.

**Comment by cptchi** [comment]
fanmuxx, xiami got a new design and therefore the old scrobbler didn't work on it
if you haven't been redirected to it, click the little home icon on the bottom right corner of the xiami page
![new xiami](https://i.imgur.com/VAqM7yJ.png)

**Comment by fanmuxxx** [comment]
@KwonDae @cptchi Thank both for your help. It works for me now.

I preferred the old design but I suppose that now I have to switch to the new version for the scrobbler function.

**Comment by inverse** [comment]
The extension can be made to work with both designs. you just need a way to detect the design and wire up the behavior accordingly.
