### ISSUE TITLE
Keyboard shortcut for quickly enabling/disabling scrobbling for the current web service.

### ISSUE THREAD

**Issue by Rostov84** [web-scrobbler/web-scrobbler#1819]
Is it possible to add a configurable keyboard shortcut to quickly enable / disable scrobbling for the current internet service? For example, I would like AltGr + T. Maybe someone would like some other keyboard shortcut.

**Comment by inverse** [comment]
I know these kind of things are possible in Chrome, not sure about Firefox - I am sure they have some level of support for these sorts of things.

**Comment by alexesprit** [comment]
<kbd>Alt</kbd>+<kbd>R</kbd>: Toggle connector (controller) state.
<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>: Disable connector (controller) until tab is closed.

Works fine on both Chrome and Firefox.

These hotkeys are configurable using browser interface.
