### ISSUE TITLE
No more than 19 edited tracks possible?

### ISSUE THREAD

**Issue by vittusaatanaperkele** [web-scrobbler/web-scrobbler#1824]
I have the newest version of the scrobbler. I have a long Youtube playlist with shitty tags, so I'm trying to edit all their names for the correct ones (artist - song). I have 19 videos that have correct edited information but the extension refuses to save all other edited tags. I'll write the correct artist/song title, submit, wait for the app to recognize it, then refresh and it's all reset. It's frustrating as fuck.

**Comment by inverse** [comment]
Still an issue? There should be a way to save more than that in the local cache.

**Comment by marsjaninzmarsa** [comment]
And we may need info about browser version at least. 🙂

**Comment by alexesprit** [comment]
Any logs?
