### ISSUE TITLE
Right click/contextual menu to "Love" songs

### ISSUE THREAD

**Issue by limacohen** [web-scrobbler/web-scrobbler#1827]
When starting Chrome with the `--app` flag (amazing for [players like SomaFM](http://somafm.com/player/#/now-playing/groovesalad)) I'm missing the extension button, so I can't quickly "love" a song in Last.fm. Could we have a shortcut for this when right-clicking the page? and/or maybe a hotkey?

**Comment by alexesprit** [comment]
Added <kbd>Alt</kbd>+<kbd>L</kbd>shortcut to toggle love status of now playing song.

**Comment by limacohen** [comment]
Thank you very much! *Liked*
Looking forward to the release.
