### ISSUE TITLE
Filtering "with lyrics"

### ISSUE THREAD

**Issue by nemoload** [web-scrobbler/web-scrobbler#1829]
I was listening to a music on YouTube on a video named **The Doors - When the Music's Over (with Lyrics)**
### Expected behavior

The `(with lyrics)` to be omitted.
### Current behavior
The`(with lyrics)` string is still there.

### Possible solution

Some changes to the the lyrics regex filter.
### Steps to reproduce (for bugs)
https://www.youtube.com/watch?v=YkKRU1ajKFA

### Environment

* Version used: 2.10.0
* Browser name and version: Firefox 63.0.3

**Comment by NamJinWoo** [comment]
Hi @nemoload this is Jinwoo. I've looked this issue and also looked up your code in PR.

I have a question as I am studying js.

In src/core/content/filter.js,

![image](https://user-images.githubusercontent.com/36990340/49873466-47844880-fe5f-11e8-9d6f-9f34ab7ea9e5.png)

I am not fully understood in this part. If you don't mind, can you explain it to me please?

**Comment by nemoload** [comment]
Thank you, @NamJinWoo, I've just tweaked the regex used to filter the lyrics string in the song title. 
See: https://regex101.com/r/n64nIX/1

**Comment by NamJinWoo** [comment]
Thank you a lot @nemoload !! It was absolutely helpful!

Thank you for your kindness :)
