### ISSUE TITLE
Support for playapplemusic.com

### ISSUE THREAD

**Issue by stevygee** [web-scrobbler/web-scrobbler#1832]
Someone made a web player for Apple Music, which is a great alternative to iTunes but it doesn't scrobble yet.
https://github.com/naveedgol/apple-music-web-player

### Expected behavior

Songs scrobble to last.fm.

### Current behavior

No output in developer console.
No songs scrobble.

### Environment

* Version used: 2.10.0
* Browser name and version: Chrome 70.0.3538.110 (Official Build) (64-bit)

**Comment by DiegoMarcondesD** [comment]
Yes, It would be amazing!

**Comment by clasick** [comment]
@peterjosling any help here?
