### ISSUE TITLE
Youtube still not scrobbling when "Scrobble videos from "Music" category" is on

### ISSUE THREAD

**Issue by ChineseOuchie** [web-scrobbler/web-scrobbler#1836]
Same issue as #1805 and #1807 

When  "Scrobble videos from "Music" category is on", it won't scrobble any videos anymore.

Here is an image when the option is on: https://prnt.sc/lvf3ws
and here when it is off: https://prnt.sc/lvf3r9

Chrome version: 71.0.3578.98
Extension version: 2.10.0

**Comment by eternal-sorrow** [comment]
I confirm this. This bug makes the extension completely useless for me because when I disable "Scrobble videos from "Music" category", all the trash gets scrobbled that is not even music. And when I enable this option, nothing gets scrobbled at all.

**Comment by zejjnt** [comment]
Mine hasn't scrobbled in at least a month, I just haven't been bothered to write something about it...

**Comment by inverse** [comment]
@ChineseOuchie  @eternal-sorrow  @zejjnt  can you provide sample URL's that are problematic? 

For me this is working: https://www.youtube.com/watch?v=dQEmaj9C6ko

**Comment by ChineseOuchie** [comment]
> @ChineseOuchie @eternal-sorrow @zejjnt can you provide sample URL's that are problematic?
> 
> For me this is working: https://www.youtube.com/watch?v=dQEmaj9C6ko

Not working

**Comment by eternal-sorrow** [comment]
For me it now works normal. Don't know if there was an addon update or what.

**Comment by inverse** [comment]
There was an update 7 days ago, but nothing much changed with the YT integration.

**Comment by ChineseOuchie** [comment]
@inverse Are you sure that you have turned on the "Scrobble videos from "Music" category is on" settings and restarted your browser?

**Comment by inverse** [comment]
@ChineseOuchie - Yeah - I just did it again to be sure. I'm running the version from the store on my main chrome setup too.

**Comment by ChineseOuchie** [comment]
I reinstalled it from the Chrome web store, but it still won't scrobble when the setting is on

**Comment by ChineseOuchie** [comment]
Funny that I never though of that, but yes I have plenty errors:

![image](https://user-images.githubusercontent.com/10912994/50792006-de5bed80-12c3-11e9-841a-23a918d648ab.png)

![image](https://user-images.githubusercontent.com/10912994/50791999-d69c4900-12c3-11e9-9fb2-fb4b3bbfa630.png)

**Comment by inverse** [comment]
What do you get back when you paste this in? `$('ytd-watch-flexy')`

**Comment by ChineseOuchie** [comment]
![image](https://user-images.githubusercontent.com/10912994/50792125-3bf03a00-12c4-11e9-8c0b-71d30b35b0d3.png)

**Comment by inverse** [comment]
And what do you get back with this? `$('.html5-video-player.playing-mode .ytp-title-link')`

**Comment by ChineseOuchie** [comment]
![image](https://user-images.githubusercontent.com/10912994/50792182-6510ca80-12c4-11e9-8882-e43f06fc8b01.png)

**Comment by inverse** [comment]
:+1:  will patch it

**Comment by ChineseOuchie** [comment]
Thank you!

**Comment by inverse** [comment]
@ChineseOuchie published a fix :+1:

**Comment by ChineseOuchie** [comment]
Tested and it works again

**Comment by inverse** [comment]
Great!
