### ISSUE TITLE
Listen.moe tracks recognized but won't post scrobble to Last.fm

### ISSUE THREAD

**Issue by laurensmeijs** [web-scrobbler/web-scrobbler#1837]
When using the [Listen.moe](https://listen.moe/) site the web scrobbler extension recognizes the played track most of the time, but will not push to Last.fm. The majority of the time played and scrobbled tracks will not post to Last.fm.

Even when the extension works for a while, it can suddenly stop and no longer post any scrobbles.
I have not been able to identify any trigger to this behaviour. This issue occurs on both Chrome and Firefox.

I have attempted to modify the class listener to target both the homepage player and mini-size player, which seemed to work for a while, but the issue returned.

If I had to hazard a guess as to frequency, this would be occurring every half hour.

### Environment & steps
Using v2.10.0
I have re-authenticated with Last.fm.
I have restarted the browser.
I have restarted the extension.
I have reinstalled the extension.

Chrome - Version 70.0.3538.110 (Official Build) (64-bit)
Firefox - Version 63.0.3 (64-bit)
Windows 10

**Comment by laurensmeijs** [comment]
I've found a possible relevant error when logging errors in Chrome.

![image](https://user-images.githubusercontent.com/22469518/50058957-a3f9a780-0180-11e9-98cd-68b41525f07d.png)

**Comment by laurensmeijs** [comment]
I might have found the reason for tracks not being recognized;
![image](https://user-images.githubusercontent.com/22469518/50316925-2c49b680-04b9-11e9-8b2c-a4e68b972089.png)

A large amount of spaces/tabs in the spans with the song info might be preventing the proper recognition and subsequent scrobbling. Any idea how to fix this?

**Comment by Yarn** [comment]
some notes on the issue
This is mostly guess work. I don't know if the potential fix covers many cases or even fixes anything at all.

the last.fm api: https://www.last.fm/api/show/track.getInfo

the example track i was shown was
"つなぐもの             [Princess Connect!]" by "レイ(CV:早見沙織)                ,                     ユイ(CV:種田梨沙)                ,                     ヒヨリ(CV:東山奈央)"

[the song on lastfm](https://www.last.fm/music/%E3%83%A6%E3%82%A4(CV:%E7%A8%AE%E7%94%B0%E6%A2%A8%E6%B2%99),+%E3%83%92%E3%83%A8%E3%83%AA(CV:%E6%9D%B1%E5%B1%B1%E5%A5%88%E5%A4%AE),+%E3%83%AC%E3%82%A4(CV:%E6%97%A9%E8%A6%8B%E6%B2%99%E7%B9%94)/_/%E3%81%A4%E3%81%AA%E3%81%90%E3%82%82%E3%81%AE+%5B+Princess+Connect!+%5D)

I ran into some issues with the song showing up in searches but the artist not. This doesn't seem to be happening now.

it would seem adding a space after "CV:" makes it heuristically works out in this case.
I have no idea if the search and api are actually the same (and I'm too lazy to get an api key)

to change the behaviour it looks like you would override getArtist (to replace "CV:" with "CV: ")
https://github.com/web-scrobbler/web-scrobbler/blob/2bc5367904392965514a5aecec5f720293e28e39/src/core/content/connector.js#L148

in

https://github.com/web-scrobbler/web-scrobbler/blob/2bc5367904392965514a5aecec5f720293e28e39/src/connectors/listen.moe.js

**Comment by alexesprit** [comment]
> A large amount of spaces/tabs in the spans with the song info might be preventing the proper recognition and subsequent scrobbling. Any idea how to fix this?

In your first post you said the extension *recognizes* tracks.

> I might have found the reason for tracks not being recognized;

If you have no scrobbled tracks because they were *not recognized*, they're not scrobbled because they were not recognized, obviously (malformed names, garbage etc). If tracks were *recognized*, but weren't scrobbled, it's another situation (probably, Last.fm ignores tracks).

**Comment by Yarn** [comment]
Based on context I'm going to go out on a limb and assume in the first case refers to the extension being able to get the name of the song from the DOM and the second usage refers to that info being recognized by the last.fm api.
