### ISSUE TITLE
Connector Request: invidio.us

### ISSUE THREAD

**Issue by doronbehar** [web-scrobbler/web-scrobbler#1838]
As [invidio.us](http://invidio.us/) proves to be a very useful and privacy focused YouTube clone. Would it be hard to clone the code of YouTube's connector for Invidious? I've read a bit of YouTube's connector code and I saw you use an API key to get information about the video. Would that be a problem when scraping Invidious?

Thanks.

**Comment by chugylo** [comment]
I made PR with basic support for the site.

Youtube connector use API to get the category of the video to implement the feature of ignoring videos that are not in the specified categories. But this feature currently is supported only for Youtube site. As far as I understand, even embedded videos don't support it. Maybe it worth to extend this feature to cover also embedded videos and alternative interfaces for Youtube like Invidious or Zen Player.

**Comment by inverse** [comment]
Will be in the next release thanks to @chugylo
