### ISSUE TITLE
Connection to last.fm disappears every time I close and reopen chrome

### ISSUE THREAD

**Issue by Chemoralora** [web-scrobbler/web-scrobbler#1841]
### Expected behavior

When I reopen chrome, my connection to last.fm and my options choices should remain.

### Current behavior

I have to reconnect to last.fm every time I open Chrome, and untick the use google notifications setting.

### Steps to reproduce (for bugs)

Connect to Last.Fm
Close Chrome
Reopen Chrome

If it is useful or relavent, chrome is synced to a different PC, and on that PC the program works as intended ie last.fm connection and settings remain.

1.
2.
3.

### Context

I don't want to have to reconnect to last.fm every time and uncheck the google notification setting

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used: Chrome 71 on Windows 10
* Browser name and version: Chrome

**Comment by alexesprit** [comment]
Any logs?
