### ISSUE TITLE
Google Play Music has information about albums

### ISSUE THREAD

**Issue by plaxin** [web-scrobbler/web-scrobbler#1844]
Hello! Google Play Music has information about now listening albums. How about getting the album artist's to scrobble? 
_for example, in cases of Various Artists, the album cover of the scrobbles should be Various Artists, not the current artist._

t h a n x

**Comment by alexesprit** [comment]
Didn't understand the issue at all, but GPM connector uses album arts provided by GPM, and this behavior won't be changed.
