### ISSUE TITLE
Update Saavn to Jiosaavn

### ISSUE THREAD

**Issue by rohitjhawer** [web-scrobbler/web-scrobbler#1846]
Update Saavn to Jiosaavn.

Saavn streaming service has recently been updated to Jiosaavn. can you please update the scrobbler to the new URL so that we can start streaming our music. 

New URL: https://www.jiosaavn.com/

Thank you for the awesome scrobbler.

**Comment by longloop** [comment]
+1 I think we just need to update the domain name.
