### ISSUE TITLE
Make edit popup persistent across tabs

### ISSUE THREAD

**Issue by quietmansoath** [web-scrobbler/web-scrobbler#1850]
I don't necessarily think this is a bug, but would be a great feature. Usually I have VGMDB in another tab and would like to copy information over one field at a time. Right now, what I have to do is copy artist, album, and song title into a random field on a given open tab, then copy paste all of that into one of this addon's fields, then _while the popup is open_ copy from the field with everything in it to their respective fields.

I'd be great if I could navigate to another tab with the popup remaining open across tabs (or at least not close if I switch tabs)

### Environment

* Browser name and version: Firefox 64.0

**Comment by marsjaninzmarsa** [comment]
There is no way for WebExtension to prevent popup from closing.

**Comment by alexesprit** [comment]
As previously said, there's no way to keep the popup opened on tab switching.
