### ISSUE TITLE
Please add support for R-a-d.io

### ISSUE THREAD

**Issue by quietmansoath** [web-scrobbler/web-scrobbler#1852]
It would be great if you could add support for https://r-a-d.io/. Thanks for all of your hard work on this addon!

**Comment by ExpandingShapes** [comment]
Hi @quietmansoath !
I've implemented your requested. The feature will be added in the next release.

**Comment by quietmansoath** [comment]
Perfect!! Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alexesprit** [comment]
Implemented in #1852.
