### ISSUE TITLE
Youtube Mobile

### ISSUE THREAD

**Issue by duri2** [web-scrobbler/web-scrobbler#1853]
### Expected behavior
Should scrobble in Firefox Mobile (if Youtube is in destop mode in Firefox Mobile - it scrobbles perfectly)

### Current behavior
Not scrobbling, doesn't  recognize track even when used Custom URL patterns (*://*.youtube.com/*) - but in this case there's notification about unrecognised track (so it tries to scrobble). 

So maybe there's easy way to fix it?

### Possible solution
Maybe I'm using bad URL pattern?

### Context
It's possible to installl Web Scrobbler in Firefox Mobile, it's possible to access options, it even scrobbles Youtube when destop mode is forced. But in mobile version of Youtube it doesn't work. (This problem occurs with other supported services in mobile version - for example Bandcamp)

### Environment

* Version used: Web Scrobble 2.11.0
* Browser name and version: Firefox Mobile 64.0.1
* Youtube mobile site (m.youtube.com)

**Comment by palikcuiho** [comment]
I used to be able to scrobble (but not edit) with Youtube in desktop mode too, but it seems that it (very recently) stopped working.
