### ISSUE TITLE
Add an option to disable scrobbling in Firefox when private browsing mode is enabled

### ISSUE THREAD

**Issue by chugylo** [web-scrobbler/web-scrobbler#1854]
### Expected behavior

When I listen to music from a private window in Firefox the scrobbling ceases. The icon and the popup indicate this state. Also, the options page has a checkbox to enable/disable the proposed behavior.

### Current behavior

When I listen to music from a private window the scrobbling happens as usual.

### Context

Current behavior may unexpectedly reveal my private browsing. Unfortunately, Firefox doesn't have means for a user to disable the extension in private mode as Chrome does.

### Steps for resolving the issue

- [x] Try to use unpacked extension from latest master

- [x] Check other issues for duplicates

### Environment

* Version used: 2.11.0
* Browser name and version: Firefox 64.0

**Comment by alexesprit** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1380809

**Comment by alexesprit** [comment]
This feature will be implemented natively by Mozilla in upcoming Firefox 67.

A screenshot from Firefox 67.0b18:
![image](https://user-images.githubusercontent.com/1119267/57526971-7d0e5e80-7337-11e9-8904-1ecd4f7b6305.png)
