### ISSUE TITLE
Request: http://imago.fm/ 

### ISSUE THREAD

**Issue by dangodavid** [web-scrobbler/web-scrobbler#1862]
Hello guys,
 
I'm using for a long time your service with YouTube and Tidal and I can say that I love it.

Lately I have discover a very nice radio station called: http://imago.fm/ 
Can you please add support for this radio web station? I would appreciate your effort. 

Thank you and keep up the good work.
Best wishes and happy new year from Romania!

David

I have attached an image that might help you with a quick view ![imago](https://user-images.githubusercontent.com/28823686/50772134-6d054600-1295-11e9-87f1-51f0f7afa02b.jpg)

**Comment by clasick** [comment]
Added support for Imago Radio by implementing a connector. https://github.com/web-scrobbler/web-scrobbler/pull/2184
