### ISSUE TITLE
Scrobble from Amazon Echo

### ISSUE THREAD

**Issue by waynewilliamberninger** [web-scrobbler/web-scrobbler#1867]
Amazon music playing on Amazon Echo should scrobble. I have Amazon Echo "Now Playing" tab open in Google Chrome. I also have Last.fm profile page https://www.last.fm/user/emperor_ofdirt open with "Recent Tracks" chart visible.

I have already added Amazon Alexa "Now Playing" tab URL - https://alexa.amazon.com/spa/index.html#player - as a pattern that the connector should match in list of supported websites in Web Scrobbler settings. I also added an additional URL as follows - *://alexa.amazon.com/spa/index.html#player -

**Comment by andrewc2** [comment]
Mine scrobbles fine from that page.

**Comment by inverse** [comment]
Closing as resolved.
