### ISSUE TITLE
Is it possible to add support for https://www.xiami.com/?

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#1868]
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by inverse** [comment]
We already support https://www.xiami.com/play for some time. Is this not working for you?

**Comment by NomaanMalick** [comment]
> 
> 
> We already support https://www.xiami.com/play for some time. Is this not working for you?

You're right, https://www.xiami.com/play is supported. But there is no site-wide support for https://www.xiami.com/. When I play a song from the search, artist, or album page, the scrobbler is unable to pick that up since only https://www.xiami.com/play page is supported.

**Comment by cptchi** [comment]
I already talked about that here https://github.com/web-scrobbler/web-scrobbler/issues/1817

xiami.com/play shouldn't work because it doesn't exist anymore. the design changed.

https://github.com/web-scrobbler/web-scrobbler/pull/1848

**Comment by NomaanMalick** [comment]
So, does it work now? I played some music on xiami.com yesterday, but the scrobbler didn't pick up any of the music playing.

**Comment by inverse** [comment]
#1848 should fix it

**Comment by cptchi** [comment]
I can confirm it is working again - Thank you so much guys!!!!

**Comment by KwonDae** [comment]
Sounds good!
