### ISSUE TITLE
Ability to automatically scrobble YouTube's auto-generated music videos.

### ISSUE THREAD

**Issue by PlaylistsTrance** [web-scrobbler/web-scrobbler#1896]
### Description
YouTube has a lot of official music uploads where the video's title is just the song's title.
The video's description always follows this pattern:

> Provided to YouTube by ... // This line might be missing
> Title · Artist
> Album
> Extra info like publisher, release date and credits.
> Auto-generated by YouTube.

Some examples (with the uploader name format given): [Artist - Topic](https://youtu.be/qGXeIBNQuIk), [Artist](https://youtu.be/4mUPy84mdb0), [Various Artists - Topic](https://youtu.be/od9UKd-yvks).

[Example](https://youtu.be/fLpGWtSLsB0) where "Provided to YouTube by ..." is missing.

### Expected behavior
The extension should be able to identify these kinds of videos somehow, and then use the data in the description for the scrobble fields.

### Possible implementation

A possible way to detect these kinds of videos might be the first line of the description being "Provided to YouTube by ...", and/or the last line "Auto-generated by YouTube", and I think they're always categorized as Music.

**Comment by alexesprit** [comment]
All of these examples are recognized by the connector, except of [this one][example]. Unfortunately, this is true, if an user chose English language for YouTube.

To resolve this issue we should use description parser first. I made a simple parser that extracts track info from video description, but I doubt it covers all desc variations.

Currently supported 2 variants of description (with "Provided to YouTube by ..." line; with the missing "Provided" line). The parser assumes album title is always present in the description.

Example of implementation is available [here][parser].  I intentionally implemented this functionality as a script to easier testing.

[example]: https://www.youtube.com/watch?v=od9UKd-yvks&feature=youtu.be
[parser]: https://gist.github.com/alexesprit/8a20826d47a6bb99e0921b70bc9bee45

**Comment by alexesprit** [comment]
[Experimental branch][branch] with description parser implemented.

[branch]: https://github.com/web-scrobbler/web-scrobbler/tree/feature/yt-description
