### ISSUE TITLE
Could you add support for https://streetvoice.cn

### ISSUE THREAD

**Issue by Hermine2** [web-scrobbler/web-scrobbler#1898]
I really appreciate it if it'd been solved. And thanks for creating this extension.

**Comment by ExpandingShapes** [comment]
Hello! 
There are artists with chinese symbols only and with latin letters only.
However Street Voice sometimes adds to an artist name English translation like [here](https://streetvoice.cn/goodband/) or [here](https://streetvoice.cn/whocares2016/). In this cases artist name should be scrobbled without latin letters, right?
