### ISSUE TITLE
Providing incomplete track information causes error

### ISSUE THREAD

**Issue by ostpczk** [web-scrobbler/web-scrobbler#1899]
Opening a video on YouTube whose title does not happen to be properly processed by the parser, then feeding incomplete information onto it (for instance, only the artist name) causes an error. It does not allow to enter the track information again until it is deleted from the list of manually matched tracks.

### Steps to reproduce (for bugs)

1. [Open this video](https://www.youtube.com/watch?v=mlv95aY1dOE)
2. Click the extension icon
3. Insert "Александр Пистолетов" as the artist name
4. Leave track title and album title fields empty
5. Press Enter

```
Last.fm: track.updatenowplaying response:
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="failed">
  <error code="13">Invalid method signature supplied</error>
</lfm>
base-scrobbler.js:498:6
debugLog
moz-extension://05e96f65-48b5-4805-ae6f-d230d824ce35/core/background/scrobbler/base-scrobbler.js:498:6
doRequest/promise</<
moz-extension://05e96f65-48b5-4805-ae6f-d230d824ce35/core/background/scrobbler/base-scrobbler.js:274:7
```
### Environment
- Version used: v2.13.0
- Browser name and version: Mozilla Firefox for Linux Mint, 63.0.3 (64-bit)

**Comment by ExpandingShapes** [comment]
Hi, Jakub! Thanks for reporting. 
I don't quite understand why you try to scrobble a track with either artist or track name missing. 
(This is also forbidden by Last.fm [API](https://www.last.fm/api/show/track.scrobble) )
I've reproduced the bug in Chrome and I got 

> Service error
> Looks like something went wrong while scrobbling the music. Please open the options page and try to reauthenticate with services. If reauthentication doesn't help, and you still see this message, please create a new issue at the GitHub project page.

Indeed, it's not a convenient way to go to Options -> Edited tracks and remove the edited track. I guess we could add check that artist field and track field are filled before adding the edited track to the storage.

**Comment by ostpczk** [comment]
Thanks! Just in case, I entered only the artist name by accident as I was trying to copy a string containing both the artist name and the track name. The fact that pressing Ctrl causes the window to disappear doesn't help.

**Comment by ksbrar** [comment]
+1 - also get this error.

I could be totally misremembering, but I think I used to be able to enter incomplete track information and still have Last.fm recognize the track? At the very least, I do not remember getting this service error before the past few weeks in similar situations.
