### ISSUE TITLE
Scrobbling for Tidal isn't working

### ISSUE THREAD

**Issue by dStankiewicz** [web-scrobbler/web-scrobbler#1900]
Listening from Tidal web player, song isn't recognized. Scrobbling for this site is not working.

**Comment by daniel-stoneuk** [comment]
Which version of the extension are you using?
This has been fixed in the latest version of the extension.

**Comment by dStankiewicz** [comment]
I'm currently using version 2.13.0. Icon is getting red, with a message "This site is supported for scrobbling" but song is not recognized.

**Comment by daniel-stoneuk** [comment]
Interesting, which version of TIDAL are you using? Go to settings > about TIDAL

**Comment by dStankiewicz** [comment]
It's version 3.7.1--2 (NP: 2.3.8.1)

**Comment by daniel-stoneuk** [comment]
Ah okay, sorry I didn't realise earlier but the fix is actually implemented in a newer version of the extension.

 You can download the repository and then click "Load Unpacked" in the chrome extensions page to install the latest updates.

**Comment by dstankiewicz-pgs** [comment]
It worked. There are some errors in chrome extension manager, but basically, scrobbling is working :) Thanks.

**Comment by dStankiewicz** [comment]
It worked. There are some errors in chrome extension manager, but basically, scrobbling is working :) Thanks.

**Comment by daniel-stoneuk** [comment]
No worries! Don't mind the errors, these are just reporting that you don't have a Libre.fm or ListenBrainz account connected.

Make sure you check back for updates every so often, or whenever you encounter an issue!

**Comment by inverse** [comment]
@dStankiewicz can this be closed?

**Comment by dStankiewicz** [comment]
Yes, it's working, therefore I'm closing the issue. Thanks!
