### ISSUE TITLE
Scrobble from http://www.last.fm website player

### ISSUE THREAD

**Issue by john3voltas** [web-scrobbler/web-scrobbler#1902]
Hi there.
Very interesting FF extension. I usually login on last.fm website, click on my recommendations link and hear music using their youtube player implementation.

### Expected behavior
Browse to last.fm's website, click on my recommendations link, listen to music using their youtube player implementation and have web-scrobbler scrobble my listenings from that site.

### Current behavior
Instead, I browse to last.fm's website, click on my recommendations link, listen to music using their youtube player implementation but web-scrobbler doesn't scrobble my listenings from that site.

### Environment
- Version used: 2.13.0
- Browser name and version: Mozilla Firefox 65.0 (64 bits)
- Windows 7 Pro SP1

**Comment by inverse** [comment]
How do you see this? I'm only seeing the spotify connect option.

Previously I remember the YouTube player on last.fm scrobble automatically without us having to do anything.

**Comment by inverse** [comment]
Interesting. With this enabled scrobbling works for me. It's not picked up via the extension but managed by last.fm. Was this always not working?

**Comment by john3voltas** [comment]
> With this enabled scrobbling works for me. It's not picked up via the extension but managed by last.fm. 

Not in my case. When I'm listening from the website I don't get any scrobbling.

> Was this always not working?

I honestly don't know.

**Comment by ChelohHolmes** [comment]
Web Scrobbler doesn't scrobble from Last.fm because it shouldn't. When you listen to music directly from Last.fm with the YouTube player, it scrobbles automatically, you don't need to worry. If it isn't scrobbling as it should, it's probably a bug from the website itself, not the extension.

**Comment by john3voltas** [comment]
Interesting. I just noticed web-scrobbler failing to scrobble.
I am quite sure that last.fm's site wasn't scrobbling on it's own when I opened this issue, though...truth being that it is now scrobbling perfectly fine.
Thanks for the tip.
