### ISSUE TITLE
support brain.fm

### ISSUE THREAD

**Issue by douglasawh** [web-scrobbler/web-scrobbler#1907]
Support brain.fm. It's a bit different than the other 

I am not exactly sure. Since brain.fm is just a stream of music without separate tracks, it is different than most scrobbling. It would be cool to support it though in some way.

I'm just skipping the rest because I really don't know how it should work. Perhaps more thoughtful people could leave comments.

**Comment by inverse** [comment]
Not sure how feasible this one will be.

**Comment by jaccarmac** [comment]
As a brain.fm user, I can't imagine exactly how the tracks should scrobble. Could you give an example of how you would want scrobbles to be displayed on your profile if you could?

**Comment by douglasawh** [comment]
"Since 1990, it seems that the average song length has sort of stabilized around 250 seconds (over 4 minutes). Maybe that's because humans prefer 4 minute songs." - https://www.wired.com/2014/07/why-are-songs-on-the-radio-about-the-same-length/

Maybe just chop it into 5 minute intervals? There are actually a bunch of different stations. The shortest is sleep which has Ambient Music, Beach, Forest, Nightsounds, Rain, Thunder, Underwater, Wind.

Another option would be just to scrobble on station change. That certainly would be the easiest to implement.

**Comment by jaccarmac** [comment]
So you would want to see scrobbles in the form of:

- **Title:** _station name_
- **Artist:** _Brain.fm_

That's more what I'm wondering. Scrobbling on station change would probably make the most sense, since this scrobbler doesn't scrobble long tracks multiple times.

**Comment by inverse** [comment]
Does this make sense? @jaccarmac should this ticket be closed?

**Comment by douglasawh** [comment]
I think @jaccarmac's suggestion sounds good. Since I initially posted this, brain.fm has added some additional stations.

**Comment by jaccarmac** [comment]
If you can give a test, @douglasawh, go ahead and do so from the branch I just pushed. I didn't test extensively, but it seems to detect station change correctly.
