### ISSUE TITLE
Music played through URLs of the type https://www.xiami.com/radio/play/ while supported by Web Scrobbler isn't scrobbled.

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#1909]
### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [ ] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [ ] Check other issues for duplicates

### Environment

-   Version used:
-   Browser name and version:

**Comment by alexesprit** [comment]
Looks like it's a duplicate of #1817.
