### ISSUE TITLE
Youtube does not scrobble on Google Chrome, but Open Spotify scrobbles, uBlock Origin is disabled

### ISSUE THREAD

**Issue by stardepp** [web-scrobbler/web-scrobbler#1913]
### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [x] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [x] Check other issues for duplicates

### Environment

-   Version used: v2.14.0
-   Browser name and version: Google Chrome Version 72.0.3626.96

**Comment by ChineseOuchie** [comment]
Open your console while listening to music, does it print some errors?

**Comment by stardepp** [comment]
I had still deleted cookies and cache in Chrome after my request and now it works again, but thanks for your reply. I am very happy that Web Scrobbler exists.

**Comment by shatterhand19** [comment]
I am having this problem and clearing the cookies and the cache did not help. The console does not print anything out.

**Comment by cfare** [comment]
I'm guessing this is the same issue as #1911 - since it looks like an API rate limiting problem it will probably work randomly and then fail for everyone for certain periods

**Comment by anton0kurilov** [comment]
> Open your console while listening to music, does it print some errors?

![screenshot_2](https://user-images.githubusercontent.com/8565767/52761776-5ea20b00-3047-11e9-85ba-34b1719dd32c.png)

**Comment by mirobartovic** [comment]
Same here, suddenly stopped scrobbling youtube.

![image](https://user-images.githubusercontent.com/21225119/52769488-ba14ce80-3030-11e9-91d7-2693c9ea23dd.png)

**Comment by anton0kurilov** [comment]
Easy fix: just disable YouTube categories in the scrubber settings. Works for me.

**Comment by mirobartovic** [comment]
Disabling YouTube categories (Music, Entertainment) in the scrobbler settings fixes the problem. (Thanks to @anton0kurilov)

**Comment by mirobartovic** [comment]
Thanks!

št 14. 2. 2019 o 9:23 Anton Kurilov <notifications@github.com> napísal(a):

**Comment by tbechthomassen** [comment]
This works for me as well. Was getting the same error in console -- disabling Youtube categories restarts scrobbling.

**Comment by shatterhand19** [comment]
it works, but now it would scrobble entertainment videos as well, so this is not a perfect solution :/

**Comment by tbechthomassen** [comment]
Scrobbling with categories selected works for me as well now.

**Comment by shatterhand19** [comment]
Issue is back :/

**Comment by stardepp** [comment]
This resembles in Firefox, although I have completely extinguished Cookies and Cache, scrobbelt Websrobbler Youtube not.

**Comment by ChineseOuchie** [comment]
You get these errors when you use the youtube api too much. 
![image](https://user-images.githubusercontent.com/10912994/52904074-eb56ef80-3226-11e9-9135-faf49223e1f5.png)

**Comment by inverse** [comment]
The problem is we're being rate limited when trying to resolve the category information. We need a way to scale this.

**Comment by marsjaninzmarsa** [comment]
```
Web Scrobbler: Connector.playerSelector is empty. The current connector is expected to manually detect state changes starter.js:68:3
Web Scrobbler: Setup "timeupdate" event listener youtube.js:217:4
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
youtube player state transitioned from undefined to 1 youtube.com-orchestrator-pageScript.js:72:13
URI źródła elementu „script” jest niedozwolony w tym dokumencie: „https://static.doubleclick.net/instream/ad_status.js”. watch:1:1
Unable to get category for YgBzzRFWD_E: Invalid response youtube.js:190:4
URI źródła elementu „script” jest niedozwolony w tym dokumencie: „https://pagead2.googlesyndication.com/pagead/show_companion_ad.js”.
watch:1:1
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
youtube player state transitioned from 1 to 2 youtube.com-orchestrator-pageScript.js:72:13
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
youtube player state transitioned from 2 to 1 youtube.com-orchestrator-pageScript.js:72:13
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
(…)
Unable to get category for YgBzzRFWD_E: Invalid response
youtube.js:190:4
Unable to get category for YgBzzRFWD_E: Invalid response
```
partially connected?

**Comment by ChineseOuchie** [comment]
I often listen to the same music and everytime it will make a request to the api and when everyone do this it will reached the limit really fast.

Maybe add a cache? only make a request to the API when you listen to a new song?

**Comment by HimbeersaftLP** [comment]
Can't we just get the category directly from the already loaded page?

**Comment by inverse** [comment]
The problem with that is localisation AFAIK. Unless we map all locales. Also API driven approach means if the DOM changes it'll be lesser work to map.

**Comment by inverse** [comment]
Dupe of #1913

**Comment by stardepp** [comment]
> ### Expected behavior
> ### Current behavior
> ### Possible solution
> ### Steps to reproduce (for bugs)
> 1.
> 2.
> 3.
> 
> ### Context
> ### Steps for resolving the issue
> * [x]  Reauthenticate on Last.fm
> * [ ]  Try to use unpacked extension from latest master
> * [x]  Check other issues for duplicates
> 
> ### Environment
> * Version used: v2.14.0
> * Browser name and version: Google Chrome Version 72.0.3626.96

**Comment by HimbeersaftLP** [comment]
> The problem with that is localisation AFAIK. Unless we map all locales.

The name might be different in other languages, but they still link to the same channel (at least German and English do)

**Comment by kustek** [comment]
unchecking categories solved scrobbling issues for me.
Had this error previously
>Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
