### ISSUE TITLE
Support for the Qobuz web player

### ISSUE THREAD

**Issue by hans-juergen** [web-scrobbler/web-scrobbler#1914]
### Expected behavior
Scrobble their [web player](https://play.qobuz.com/).

### Current behavior
Currently it doesn't.

**Comment by hans-juergen** [comment]
It seems Qobuz is not supported yet, although they have a web player, too:

https://play.qobuz.com/

Now that they have started in the U.S., it would make sense to add their streaming site as well, I think.

**Comment by inverse** [comment]
Adding help-wanted as this is behind a paywall.

**Comment by hans-juergen** [comment]
OK, I have a free account at the moment enabling me to play 30 seconds excerpts. Here is a screenshot showing their web player, so it doesn't look unusual with playerbar at the bottom:

![Qobuz Webplayer](https://user-images.githubusercontent.com/4970867/88278271-6527be00-cce2-11ea-9eec-07e1f7488735.png)

**Comment by alexesprit** [comment]
It's also available for me in demo mode, but it's enough to develop a connector for the website.

The last time I checked Qobuz it was inavailable for me due to geolocation restrictions.

**Comment by hans-juergen** [comment]
Great, I wrote a Qobuz FAQ on the new support forum with two screenshots where to enable their internal scrobbling:
https://support.last.fm/t/qobuz-scrobbling/2876/3

**Comment by hans-juergen** [comment]
Thanks, will update the FAQ as well. :-)
