### ISSUE TITLE
Blocks of Untranslated Text in Polish version.

### ISSUE THREAD

**Issue by marsjaninzmarsa** [web-scrobbler/web-scrobbler#1915]
![image](https://user-images.githubusercontent.com/1119575/52952571-3dae2280-3385-11e9-8f6e-93352430c410.png)

I don't see that strings in `messages.json` on Transifex, tough i would bet that I've already translated them before…

**Comment by inverse** [comment]
This comes from https://github.com/web-scrobbler/web-scrobbler/blob/master/src/PRIVACY.md

@alexesprit should we go through transflex for these files? e.g. having `PRIVACY.pl.md` for example?

**Comment by inverse** [comment]
@marsjaninzmarsa File should be available for translation now :+1:

**Comment by alexesprit** [comment]
@inverse but the extension still doesn't handle translated privacy policy.

**Comment by inverse** [comment]
@alexesprit thought it be worth waiting for the first translated policies to come in first. Or should we make the logic work?

**Comment by inverse** [comment]
Partially resolved by #1936

**Comment by inverse** [comment]
@marsjaninzmarsa when the translation is complete it'll be solved.

**Comment by alexesprit** [comment]
Now this issue is fixable by the translators, so I close this one.
