### ISSUE TITLE
Request: option to disable last.fm corrections

### ISSUE THREAD

**Issue by borealissw** [web-scrobbler/web-scrobbler#1921]
Once a song is recognised, entered, or edited, any last.fm "correction" is automatically applied. Can there be an option to disable this? Alternatively, can a manual edit of the track take precedence over last.fm's suggestion.

The question of "correct" tagging is always a sensitive one on last.fm, but this is a tool to record scrobbles and should IMHO, behave according to the user's request rather than the service.

Thanks for the great tool.

**Comment by ChelohHolmes** [comment]
You can disable the correction feature on Last.fm here: https://www.last.fm/settings/website 
Go to 'Artist and track corrections' and uncheck the 'Auto-correct the spelling of your scrobbles' option.

**Comment by alexesprit** [comment]
This way, probably, won't fix the issue.
Currently, the algorigthm of correction is following:
1. An user starts to play a track.
2. The extension requests track info, grabs the proper info from the result.
3. Grabbed info is used to make `now playing` and `scrobble` requests.

I don't know if Last.fm applies the autocorrect option on `track.getinfo` request.

@borealissw can you provide any example of tracks are corrected by Last.fm?

**Comment by alexesprit** [comment]
Scrobbled [this](https://www.youtube.com/watch?v=YXwYJyrKK5A) video with autocorrection turned off both in the extension and in the Last.fm settings. The Last.fm website displays "Two Door Cinema Club — What You Know" is scrobbled, but "TWO DOOR CINEMA CLUB — WHAT YOU KNOW" is expected to be scrobbled.

I don't know if it's a correct example to test autocorrection; probably, the Last.fm has some "normalizing" corrections are required for each track (e.g. convert CAPS to CamelCase).

**Comment by borealissw** [comment]
> You can disable the correction feature on Last.fm here: https://www.last.fm/settings/website
> Go to 'Artist and track corrections' and uncheck the 'Auto-correct the spelling of your scrobbles' option.

**Comment by borealissw** [comment]
> I don't know if it's a correct example to test autocorrection; probably, the Last.fm has some "normalizing" corrections are required for each track (e.g. convert CAPS to CamelCase).

Thanks for the replies and apologies for the lack of response - I've been busy and not had much time.

The problem is definitely not down to last.fm's autocorrect - I've never used that. I tried to keep the language of the request generic but should have given a concrete example.

For example, try Yukihiro Takanashi's Blue Moon Blue at https://open.spotify.com/album/2dS5CPxm440BkBAxrgBXhb. When I start playing this, a trip will be made to last.fm and it will return with his native spelling in Kanji. If I edit the submission to use an anglicised spelling, it goes straight back to kanji.

That's admittedly all correct, but if I'm looking back to see who I played last night on a spotify radio that I enjoyed, I have to do some digging to find out who it is so that I can search in english on spotify. A bunch of kanji characters is no good for a non-japanese speaker with an english keyboard. 

I can boil my feature request down to: if I type something in, submit it exactly as-is. This can definitely happen without last.fm getting in the way - I use Simple last.fm Scrobbler on android which lets me edit tracks before submission and doesn't let last.fm change it.

Thanks again for the responses.

**Comment by alexesprit** [comment]
@borealissw thanks for the example.

I updated the extension code to disallow loading track info if the track was edited. But it didn't help too much. The request sent by the extension:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <nowplaying>
    <track corrected="0">EXIT TO REALITY</track>
    <artist corrected="0">Yukihiro Takahashi</artist>
    <album corrected="0">Blue Moon Blue</album>
    <albumArtist corrected="0"></albumArtist>
    <ignoredMessage code="0"></ignoredMessage>
  </nowplaying>
</lfm>
```
What Last.fm is displaying:
![image](https://user-images.githubusercontent.com/1119267/57928574-d9cec380-78b9-11e9-9b66-840d749b16c7.png)

Interesting that autocorrection is turned off in my Last.fm preferences.

**Comment by alexesprit** [comment]
> I can boil my feature request down to: if I type something in, submit it exactly as-is. This can definitely happen without last.fm getting in the way - I use Simple last.fm Scrobbler on android which lets me edit tracks before submission and doesn't let last.fm change it.

Yes, it totally makes sense to submit edited tracks as-is.

@borealissw Could you test the extension from [this branch][0]?

I changed the extension behavior, and now it doesn't update track info if a track was edited. This is hardcoded, and cannot be turned on/off. If this is applicable for you, I'll push these changes.

If you don't know how to install extensions from a zip file, please use [this howto][1].

[0]: https://github.com/web-scrobbler/web-scrobbler/tree/feature/no-correction
[1]: https://github.com/david-sabata/web-scrobbler#unpacked-extension

**Comment by borealissw** [comment]
Hi @alexesprit , thanks for the update. I won't be able to test today but I'll give it a try tomorrow and give you feedback

**Comment by borealissw** [comment]
Hi @alexesprit ,

sorry for the hold-up. Just built and installed the branch and all looks good. Odd that the now-playing doesn't change, but once scrobbled, its correct. Many thanks.

**Comment by alexesprit** [comment]
> Odd that the now-playing doesn't change, but once scrobbled, its correct.

Thanks for feedback. It's the same behavior for me.
