### ISSUE TITLE
https://myzcloud.me/en Scrooble support  Is it possible this website adds to Webscrobbler?

### ISSUE THREAD

**Issue by stardepp** [web-scrobbler/web-scrobbler#1923]
### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [ ] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [ ] Check other issues for duplicates

### Environment

-   Version used:
-   Browser name and version:

**Comment by alexesprit** [comment]
Was added in 203b5299c2ea9c5f6868d52dc604beefd8ce30f3.
