### ISSUE TITLE
Youtube tries to scrobble every single video when "scrobble from Music category" is enabled

### ISSUE THREAD

**Issue by eternal-sorrow** [web-scrobbler/web-scrobbler#1929]
### Expected behavior
Scrobble only videos in the Music category

### Current behavior
Scrobbles every video regardless of category

### Steps to reproduce (for bugs)
1. Play any video on Youtube
2. It tries to recognise and scrobble it

### Environment

-   Version used: 2.14.0
-   Browser name and version: Firefox 65.0

**Comment by alexesprit** [comment]
Can you reproduce it on v2.15.1?

**Comment by eternal-sorrow** [comment]
It's OK now.
