### ISSUE TITLE
Add support for nicovideo.jp

### ISSUE THREAD

**Issue by ohlookitsderpy** [web-scrobbler/web-scrobbler#1932]
Would be nice as I listen to music there a lot (though it also has video)

**Comment by takagiy** [comment]
Hello, I started working for this. [(on this folk, the branch isn't pushed yet)](https://github.com/takagiy/web-scrobbler/tree/master)
And finally it works!:

![Niconico Scrobbler Example](https://user-images.githubusercontent.com/18656090/104770628-3469a280-57b4-11eb-882c-be8ce4f19a18.jpeg)

I will create a pull request after some debugging after a while.

Thanks, so much.
