### ISSUE TITLE
Firefox 60.5.1esr can't connect to listenbrainz

### ISSUE THREAD

**Issue by moinmoi** [web-scrobbler/web-scrobbler#1937]
### Expected behavior

Getting signed in to ListenBrainz and be able to scrobble to it.

### Current behavior

I get redirected to an URL much like this one (id and state redacted): https://musicbrainz.org/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Flistenbrainz.org%2Flogin%2Fmusicbrainz%2Fpost&scope=profile&state=state&client_id=id

I login and end up on https://listenbrainz.org/profile/ where I can view my user token et.c, but it doesn't seem to link the account to the add on.

Last.fm login and scrobbling works fine.

### Steps to reproduce (for bugs)

1\. Preferences -> Accounts -> ListenBrainz -> click "Sign In" 
2\. Login on the website you get redirected to.

-   [X] Try to use unpacked extension from latest master
-   [X] Check other issues for duplicates

### Environment

-   Version used: 2.15.1 (2.15.0 when unpacked)
-   Browser name and version: Firefox 60.5.1esr

**Comment by inverse** [comment]
@moinmoi but when you start playing music does it show up on listenbrainz? e.g. https://listenbrainz.org/user/<your-username>

I can confirm your behaviour described but it seems working to me.

**Comment by alexesprit** [comment]
@inverse is it working for you on 60.5.1esr (or 60.6.1esr)? I can reproduce the issue on 0.6.1esr, but have no idea how to resolve it.

**Comment by moinmoi** [comment]
@inverse No, I'm afraid nothing shows up on listenbrainz, even though things do get scrobbled to last.fm.

Currently on 60.6.0esr.

**Comment by inverse** [comment]
That's strange. just verified again from fresh install.

I'm running FF 66.0 (64-bit)

**Comment by moinmoi** [comment]
Yea, works fine on non-esr firefox. And since I ran esr for no logical reason, I happily changed to FF 66.0.1 and don't mind at all if this issue is closed now.

Thanks for the help :)

**Comment by inverse** [comment]
I didn't even know ESR was a thing. Def worth having this ticket open to see if others are able to help. thnx for raising it!

**Comment by alexesprit** [comment]
Closed as fixed.
