### ISSUE TITLE
Can't scrobbling from Soundcloud

### ISSUE THREAD

**Issue by maegentae** [web-scrobbler/web-scrobbler#1938]
Soundcloud is nnot scrobbling again

**Comment by inverse** [comment]
Got a sample URL? It's working here.

**Comment by ultravio1et** [comment]
not working for me as well.

URL:

https://soundcloud.com/paulatemple/paula-temple-at-katharsis-2018

**Comment by alexesprit** [comment]
It works fine for me too. Any additional info (screenshots, logs etc)?

**Comment by gissupc** [comment]
i have the same problem , i can't scrobbling from soundcloud :c
