### ISSUE TITLE
Track Not recognised with Fill Screen option in TamperMonkey Scripts

### ISSUE THREAD

**Issue by deeplyarnab** [web-scrobbler/web-scrobbler#1944]
Whenever any of the scripts are used for a "Fill Window" option with tampermonkey, the scrobbler doesn't detect the track. First, I thought using a different script but after using 3 different scripts for it it still doesn't work. Thought report changes to the scriptwriter but with none of them working I thought I'd report here instead first. Not sure if just with scripts and didn't try any extension for the fill window yet.

### Expected behavior

Scrobble the tracks with video filling the screen.

### Current behavior

No detection or Scrobbling.

### Possible solution

Disable the scripts, pure and simple for now. I haven't read the code so not sure if some hook for the title doesn't work in it or not.
"Youtube player controls" works with everything else except that option so disabled it.

### Steps to reproduce (for bugs)

Install TamperMonkey, install any script providing option to fill the window with video, use it.

logs:- https://pastebin.com/xEDSratM
Logs taken after disabling tamper monkey, re-enabling it with disabling all youtube scripts, testing with individual scripts to confirm the cause.

### Context

Can't view a video at max screen usage without fullscreen for tab switching.
Images for context: https://imgur.com/a/DUrCqrh

### Environment

-   Version used: 2.15.1
-   Browser name and version: Google Chrome 73.0.3683.86 (Official Build) (64-bit)

**Comment by alexesprit** [comment]
> install any script providing option to fill the window with video, use it.

Could you post an URL to the script?

**Comment by deeplyarnab** [comment]
Currently using this script with the "fill window" option used (pics in the **Context**)
https://greasyfork.org/en/scripts/16323-youtube-player-controls

**Comment by alexesprit** [comment]
Thanks! I fixed the issue and will publish changes soon.
