### ISSUE TITLE
doesn't scrobble from youtube (chrome)

### ISSUE THREAD

**Issue by idontknowhowtoname** [web-scrobbler/web-scrobbler#1945]
few days ago everything worked fine, but i didn't change anything. i've got ublock origin and adobe acrobat as extensions too.

my logs are:
`chrome.storage.Options = {
  "disableGa": false,
  "disabledConnectors": [],
  "forceRecognize": true,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": true
}
wrapper.js:87 chrome.storage.LastFM = {
  "sessionID": "xxxxxjnqIBU_gDxQ8xWHpYbLxDvgLbJq",
  "sessionName": "nyname"
}
wrapper.js:87 chrome.storage.LibreFM = {}
wrapper.js:87 chrome.storage.ListenBrainz = {}
scrobble-service.js:62 Bind Last.fm scrobbler
scrobble-service.js:48 Unable to bind Libre.fm
(anonymous) @ scrobble-service.js:48
scrobble-service.js:48 Unable to bind ListenBrainz
(anonymous) @ scrobble-service.js:48
wrapper.js:87 chrome.storage.Core = {
  "appVersion": "2.15.1"
}
wrapper.js:87 chrome.storage.Notifications = {}
inject.js:37 Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
_generated_background_page.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
inject.js:61 Injecting core/content/reactor.js
inject.js:61 Injecting core/content/filter.js
inject.js:61 Injecting core/content/util.js
inject.js:61 Injecting core/content/connector.js
inject.js:61 Injecting connectors/youtube.js
inject.js:61 Injecting core/content/starter.js
controller.js:584 Tab 26: Created controller for YouTube connector
3inject.js:32 Subsequent ajax navigation, the scripts are already injected
inject.js:37 Loaded for the first time, injecting the scripts
inject.js:61 Injecting vendor/jquery.min.js
_generated_background_page.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
inject.js:61 Injecting core/content/reactor.js
inject.js:61 Injecting core/content/filter.js
inject.js:61 Injecting core/content/util.js
inject.js:61 Injecting core/content/connector.js
inject.js:61 Injecting connectors/youtube.js
inject.js:61 Injecting core/content/starter.js
main.js:342 Tab 26: Remove controller for YouTube connector
controller.js:584 Tab 26: Created controller for YouTube connector
main.js:342 Tab 26: Remove controller for YouTube connector`

**Comment by inverse** [comment]
What browser version are you using? Does restarting change anything?

**Comment by lukasgures** [comment]
It doesn't work for me too. I use Chrome. Restart and reinstall didn't help. It says that the scrobbling isn't allowed on this site (YouTube).

**Comment by lukasgures** [comment]
I found out that it doesn't work when I have checked two options (scrobbling only 2 categories). If I uncheck those options it works.

**Comment by somegirl** [comment]
Yep, same here. I usually have "Scrobble videos from "Music" category" CHECKED and "Scrobble videos from "Entertainment" category" NOT checked. I tested after UNCHECKING "Scrobble videos from "Music" category" and it worked then - so I'm guessing it's not able to figure out that the category is music?

Chrome 73.0.3683.86 (Official Build) (64-bit). Restarting didn't help. The video I was testing with was https://www.youtube.com/watch?v=DSoqC6ERnYA

**Comment by AwesomeAwesomeAwesome** [comment]
Same as posts above. It only scrobbles youtube with both options **unchecked**

**Comment by 3xploiton3** [comment]
> Same as posts above. It only scrobbles youtube with both options **unchecked**

it's work
![image](https://user-images.githubusercontent.com/19517680/55160992-1f62f000-5197-11e9-8e2f-6f88b8f550ef.png)

**Comment by sexyscientist** [comment]
YouTube scrobbling not working with "music" category checked. Working with both categories unchecked.
![image](https://user-images.githubusercontent.com/45147983/55287498-2b34f900-53c7-11e9-9f2d-a52f4bf12cd5.png)

**Comment by ChokoGrimm** [comment]
I haved the same problem, but only unchek this two opitions doesn't worked to me!
I needed to go in chrome extentions> deactvate the extention> refresh the youtube> activate the extention and the scrobble icon got yellow to me so a just realtenticate my last.fm acount logout and login.
And all working perfect here!

PS: the two options still unchecked.

**Comment by alexesprit** [comment]
Closing this in favor of #1955.
