### ISSUE TITLE
Something weird happening with a particular compilation

### ISSUE THREAD

**Issue by douglasawh** [web-scrobbler/web-scrobbler#1949]
### Expected behavior

This compilation should scrobble to last.fm: https://librarion.bandcamp.com/album/grim-reaper-records-grr-black-metal-compilation-vol-1-kompilacija-2018

### Current behavior

This compilation scrobbles to libre.fm, but not last.fm: https://librarion.bandcamp.com/album/grim-reaper-records-grr-black-metal-compilation-vol-1-kompilacija-2018

Perhaps last.fm is reject it as spam/incorrect? I don't know enough about the musicians but Libre.fm lists the artist as "Razni izvođači // Various artists" which is clearly wrong as some level. It turns out that "Razni izvođači" is "various artists" in Croatian. I don't know that there's anything that can be done, but I know some of compilations list as the label, so maybe that is something that could happen here? Maybe it's just a one-off and nothing can be done because garbage in, garbage out.

I use "Force track recognition"

I think it's probably clear what's happening, even if it's not fixable, but let me know if anything else would be useful!

**Comment by alexesprit** [comment]
If it's scrobbled to Libre.fm but not Last.fm, there're at least two reason why it happens:
1) Last.fm rejects scrobble request.
2) Last.fm auth issues. See #1950 for details.

Can you reproduce the issue and attach a debug log?
