### ISSUE TITLE
Is it working normally for you all? ( Youtube)

### ISSUE THREAD

**Issue by germanoochner** [web-scrobbler/web-scrobbler#1950]
So, I'm having some issues and the icon just stays "orange", tried to log out and log in of lastfm and it worked for a while, I'm still having the same problem. I'm using the last version of Google Chrome.

Thanks in advance.

**Comment by rederikgo** [comment]
I have the same issue scrobbling from Deezer. Last.fm issue maybe?

**Comment by nordaviento** [comment]
Yup, having the same problem with youtube and bandcamp. Also, for the last couple of days, the desktop scrobbler has been logging out each time i turn on the pc

**Comment by danivenk** [comment]
Sometimes it also happens to me (on Chrome/Youtube) but it is fixed by reauthorizing. However, this is already the third time in 2 days I had to do this...

**Comment by joseivanchechen** [comment]
For some reason it can't detect the music when it's in a playlist. I don't know if it's only here.

**Comment by waynelll** [comment]
Yeah, same with scrobbling from VK.

**Comment by yanfedorov** [comment]
Same sh1t

**Comment by coffeem1lk** [comment]
Same - youtube/chrome

**Comment by mikhail911** [comment]
Since Chrome 73 update, YouTube scrobbler stop working

**Comment by alexesprit** [comment]
I also got auth errors about 2-3 days ago, but on SLS for Android. Seems like it was temporary issues on Last.fm side. Now everything works fine for me (on Android and on PC using Web Scrobbbler).

**Comment by jessebaer** [comment]
It was working on Youtube playlists for me but now it's stopped. (The "Play some music to get started
/ Is it already playing?" error)

**Comment by ady7878** [comment]
Disabling chrome://flags/#network-service fixed it for me. [Chrome 73]

**Comment by mikhail911** [comment]
Thanks, disabling worked for me too!

**Comment by Sempraxiii** [comment]
Just disabled it and it works for me too, thank you, I was getting very frustrated!

**Comment by kuksenia** [comment]
Disabling #network-service did not help me, but I have unchecked both categories ("Music" and "Entertainment") in scrobbler's options and now it finally works. 
Found this workaround here https://github.com/web-scrobbler/web-scrobbler/issues/1945
