### ISSUE TITLE
Support request: Hoopla Digital

### ISSUE THREAD

**Issue by floorjoist** [web-scrobbler/web-scrobbler#1951]
as used by libraries online

https://www.hoopladigital.com/

**Comment by brandonjp** [comment]
I gave this a quick attempt.  It has some issues and needs some refining but mostly works. 
If there are any hoopla users who want to pull my changes and test locally, feel free:
https://github.com/brandonjp/web-scrobbler/commit/bda9c8dd3023d24e6edcf007107c4c47d18dfddc

**Comment by alexesprit** [comment]
Closed as a duplicate of #1636. Please don't duplicate issues, because it won't help to resolve them.

**Comment by floorjoist** [comment]
> 
> 
> Closed as a duplicate of #1636. Please don't duplicate issues, because it won't help to resolve them.

My mistake, I had totally forgotten I'd filed this request before!
