### ISSUE TITLE
Strange look of scrobbler's window.

### ISSUE THREAD

**Issue by Rostov84** [web-scrobbler/web-scrobbler#1956]
OS: Windows 7 Home Premium (x64)
Web browser: Firefox 56.0.2 (x64)
Extension: Web Scrobbler 2.16.0

After today's update (April 14, 2016) to version 2.16.0, the scrobbler's window looks like this. 

https://i.imgur.com/0s0CCNh.png

What's wrong?

**Comment by Rostov84** [comment]
After upgrading to version 2.16.1 it's the same.

**Comment by Rostov84** [comment]
After update to version 2.16.1 it's the same.

**Comment by Tscharbo** [comment]
i have the same problem

**Comment by muffinigans** [comment]
Same here. Updated to make it scrobble again and now I can't edit or even click. Sometimes it would look blank in the older versions, but you could still guess where the buttons were and they worked. Now they are not clickable...

**Comment by zsdedan** [comment]
Same problem.

Ubuntu 18.10 x64
Firefox 66.0.2
WebScrobbler 2.16.1

**Comment by RaylaLe100** [comment]
same problem

Windows 8.1
Firefox
WebScrobbler 2.16.1

**Comment by mortiis7** [comment]
i have exact the same problem? what is going on and will it be resolved? i think it happened today after that new update.....

**Comment by Mzusehir9** [comment]
Windows 10 Home Premium (x64)
Firefox 66.0.3 

Registered just to post about this exact problem. Never saw this issue until today with the update. Oddly, scrobbles still register, and the lower right pop-up shows the information that's also normally displayed in the edit pane. I can't edit what's playing at all though owing to this issue.

I also tried switching to several previous versions, but instead Web Scrobbler stops working, which entails the plugin icon turning yellow and the typical error message showing up.

**Comment by NighterNyx** [comment]
Same problem
FireFox

**Comment by mortiis7** [comment]
still the same problem :/ ..i hope that it will get fixed soon :/

**Comment by alexesprit** [comment]
I pushed new patch version (v2.16.3), please check and confirm if info popup is fixed. It work fine for me in v2.16.3.

**Comment by Rostov84** [comment]
For me works fine. Thanks! ;-)

**Comment by zsdedan** [comment]
Thanks, now it works!

**Comment by alexesprit** [comment]
Good to know it's fixed.

**Comment by mortiis7** [comment]
it is fixed :D thank you

**Comment by Phrynobatrachus** [comment]
thanks for the fix
