### ISSUE TITLE
spotify web isn't compatible

### ISSUE THREAD

**Issue by samynha** [web-scrobbler/web-scrobbler#1957]
I recently downloaded the extension and followed all the steps, logged in with my last.fm account and everything, but spotify web says the website isn't compatible. 
### Expected behavior
The extension icon should be red when I use spotify web.

### Possible solution

I would like to know if I did something wrong or if this is happening to other users as well. 

### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [ ] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [ ] Check other issues for duplicates

### Environment

-   Version used:
-   Browser name and version:

**Comment by kmehlin** [comment]
Same here. Was working yesterday.

**Comment by TheCheetahwings** [comment]
same. can this please be fixed soon? The site isn't compatible anymore.

**Comment by bangtangel** [comment]
Yes, me too, I need a solution please

**Comment by L7777777** [comment]
Same here

**Comment by TheCheetahwings** [comment]
please, any updates? This is very frustrating. :/

**Comment by alexesprit** [comment]
Can't reproduce. We need more details.
![image](https://user-images.githubusercontent.com/1119267/56498255-93c84f00-6509-11e9-94cf-bd2f9c0dff72.png)

**Comment by alexesprit** [comment]
Someone found an interesting thing:
https://i.gyazo.com/03752e41a37fb0bb699d26750c9c25d2.mp4
https://i.gyazo.com/d5764c077b90a1fbd90456444edec207.png

Looks like the extension does not recognize the Spotify because of endless loading. Can you guys confirm this?

**Comment by kmehlin** [comment]
That was my problem too yes. Then the other day it just started loading correctly and the scrobbler began working. I'm thinking the scrobbler is fine and Spotify is the culprit here.

**Comment by TheCheetahwings** [comment]
Still not working for me. I do have the endless loading issue.

**Comment by alexesprit** [comment]
The workaround is to press "X" button to stop page loading.

We can do nothing to fix endless loading on the extension side.
