### ISSUE TITLE
Pinguin Radio stopped scrobbling

### ISSUE THREAD

**Issue by Pan0fsky** [web-scrobbler/web-scrobbler#1959]
Penguin Radio was scrobbling just fine. It stopped working since a couple of weeks.

### Expected behavior
To scroble tracks from Pinguinradio.com automatically...

### Current behavior
The web scrobbler does not identify the track correctly but needs adjusting each time. The title field picks up the following:
`"Oats In The Water [bunch of spaces that get deleted on github] Oats In The Water - Ben Howard"`

### Possible solution
Mask/delete the second part (everything after the bunch of spaces) so the title matches the Last.fm database again.

### Steps to reproduce (for bugs)
Start listening here and see what happens https://pinguinradio.com/player/pinguin-radio

-   Browser name and version: Firefox 66.03

Love the plugin, keep on scrobbling!

**Comment by alexesprit** [comment]
Thanks! v2.17.0 will scrobble from Pinguin Radio again.
