### ISSUE TITLE
vk.com: Incomplete track title

### ISSUE THREAD

**Issue by zsdedan** [web-scrobbler/web-scrobbler#1960]
Some tracks on the vk.com contains information about remixes not in the title of the track, but as a separate entry in gray.

![bug](https://user-images.githubusercontent.com/3087460/56466654-19220580-641d-11e9-83e2-4f934ccfa547.png)

### Expected behavior

It's should scrobble track title like "Go (Extended Mix)"

### Current behavior

It's scrobbles track title like "Go"

### Environment

-   Version used: 2.16.3
-   Browser name and version: Firefox 66.0.2 (x64)
-   OS: Ubuntu 18.04.2 (x64)

**Comment by alexesprit** [comment]
Thanks! Will be resolved in the enext release.
