### ISSUE TITLE
Radioparadise not scrobbling

### ISSUE THREAD

**Issue by TokeRider** [web-scrobbler/web-scrobbler#1961]
radioparadise.com is no longer scrobbling.  The last scrobble I'm showing is from March 24 so it hasn't been working for a few weeks.

### Current behavior

The Web Scrobbler icon in Chrome for Windows 10 says Web Scrobbler doesn't support this website.

**Comment by alexesprit** [comment]
I updated URL pattern, and now the extension recognizes the website and scrobbles tracks fine for me.

**Comment by etshell** [comment]
> I updated URL pattern, and now the extension recognizes the website and scrobbles tracks fine for me.

Still not working for me (Chrome for Mac Os)...

**Comment by alexesprit** [comment]
It's not published.

**Comment by TokeRider** [comment]
What's an ETA on getting it published?  Thanks.
    On Wednesday, April 24, 2019, 3:43:02 PM EDT, Alexey <notifications@github.com> wrote:  
 
 
It's not published.

**Comment by alexesprit** [comment]
> What's an ETA on getting it published?  Thanks.

This is a project we develop in out free time, so there's no ETA.

A temporary solution is to add URL pattern for the website in the extension settings:
`https://radioparadise.com/*`

![image](https://user-images.githubusercontent.com/1119267/56728673-06c90400-675c-11e9-9a70-afae45cd7a2d.png)
