### ISSUE TITLE
Spotify no longer recognised

### ISSUE THREAD

**Issue by Maddieman** [web-scrobbler/web-scrobbler#1962]
When trying to scrobbling music via the spotify web player (https://open.spotify.com/browse/featured), the extension is greyed out and shows:

_"This website is not supported
Web Scrobbler does not support scrobbling from this website."_

I think this started some time over the weekend, it was working fine until at least Thursday.  Probably Spotify have changed something.

### Environment

Version 2.16.3, 
Chrome Version 73.0.3683.103 (Official Build) (64-bit)
Tried with and without other browser extensions (e.g. ad, tracking, & script blocking) no difference.

**Comment by alexesprit** [comment]
This issue duplicates #1957.
