### ISSUE TITLE
Slacker is/has become LiveXLive (new URL and UI)

### ISSUE THREAD

**Issue by scruff67** [web-scrobbler/web-scrobbler#1963]
### Slacker is moving/merging
Slacker merged with LiveXLive... the new URL is now https://www.livexlive.com/
Adding the pattern https://www.livexlive.com/* to slacker in options will not work... apparently there are some systematic changes along with the URL & and UI changes.

**Comment by alexesprit** [comment]
It still redirects to Slacker for some events, e.g. [this one][10]; clicking on "Listen" button leads to a Slacker page. I think we should keep Slacker connector and add new connector for LiveXLive until they remove Slacker.

What do you propose to scrobble from LiveXLive? I found some videos ([1][1], [2][2] and other similar videos) that can be potentially scrobbled. Let us know if any other content should be scrobbled too.

[1]: https://www.livexlive.com/video/b636f073-6728-4d52-9b14-9bd7086e4e18
[2]: https://www.livexlive.com/video/b4bc2791-2a9d-47ef-a280-4c2b94dfafdb

[10]: https://www.livexlive.com/live-events/festival/country-500

**Comment by TheSkuggi** [comment]
With slacker now being completely taken in by livexlive and the entire slacker domain seeming to redirect to the LXL service I think support can be dropped entirely for slacker and shifted to LXL's player which is looking like a copy/paste and some URL tweaks / page formatting. https://www.livexlive.com/music is basically the old slacker with a paint job.

**Comment by alexesprit** [comment]
Will be available in the next release.
