### ISSUE TITLE
last.fm won't permanently register youtube scrobbles

### ISSUE THREAD

**Issue by madcapwhothat** [web-scrobbler/web-scrobbler#1964]
Expect youtube scrobbles to permanently register last.fm (as viewed in recent tracks)
 
When scrobbling from youtube only the most recently played scrobble will appear on last.fm scrobble list and will then be replaced by next scrobble from youtube without registering permanently. 

Extension shows that track is recognized when on youtube.com and browser pop-up appears with track notification. 

Tried uninstalling and re-authenticating several times. Tested by opening youtube videos in new tab from the last scrobble to see if that changed anything as well as allowing all videos to run until end. Waited period of time to allow for any lag. No impact. 

Only thing I noticed was that last.fm did permanently register youtube scrobbles when it was initiated within last.fm (preference is set to play tracks in youtube and not spotify within last.fm). 
 
1\. Play song on youtube via youtube.com 
2\. Check last.fm account recent tracks

Saw similar problem from closed issue in 2014 that resolved itself, see  [https://github.com/web-scrobbler/web-scrobbler/issues/316](https://github.com/web-scrobbler/web-scrobbler/issues/316 )

Chrome 73

**Comment by alexesprit** [comment]
> Extension shows that track is recognized when on youtube.com and browser pop-up appears with track notification.

Does it also show a now playing track is scrobbled (a green tick icon)?
