### ISSUE TITLE
Feature request: Option to disable automatic scrobbling.

### ISSUE THREAD

**Issue by kvdrrrrr** [web-scrobbler/web-scrobbler#1967]
**Is your feature request related to a problem? Please describe.**
Youtube scrobbler often scrobbles ordinary, non-music videos, which I find rather annoying.

**Describe the solution you'd like**
An option to disable automatic scrobbling - instead an user would have to explicitly click a button in the plugin's UI to scrobble a song from a certain tab. Thanks to this change, the need for clicking skip button on each consequent non-music YouTube video would vanish. This may also apply to other supported websites.

**Comment by alexesprit** [comment]
This issue duplicates #1560.
