### ISSUE TITLE
WEB SCROBBLER NÃO ESTÁ FUNCIONANDO PARA YOUTUBE

### ISSUE THREAD

**Issue by raquellcabrall** [web-scrobbler/web-scrobbler#1969]
Mesmo com todos os sites compatíveis selecionados na página de opções, **a extensão simplesmente não está reconhecendo as faixas no Youtube**. Diferentemente, no Youtube Music funciona normalmente. O que há de errado com o Youtube?

**Comment by alexesprit** [comment]
Sorry, but we accept issues written in English only,
