### ISSUE TITLE
Permanent Swap

### ISSUE THREAD

**Issue by pollorojo1147** [web-scrobbler/web-scrobbler#1970]
I have a station I listen to on TuneIn where pretty much every single track needs an Artist/Title swap. Would it be possible to either add the ability to swap per site, or to toggle swap on/off?

**Comment by alexesprit** [comment]
If it's few or one stations only, I'd hardcode this functionality. I do not prefer deep customization for each supported service.

Could you provide URLs of such stations?

**Comment by pollorojo1147** [comment]
Sure. Here's one station local to me. It seems that they just seem to format things backward from the norm. Having the swap functionality is a lifesaver in this case, but I have to swap at every song, or go back and edit on the Last.fm site manually after.

https://tunein.com/radio/Cat-Country-987-s41848/

**Comment by alexesprit** [comment]
Thanks!

I've updated the TuneIn connector, and now the extension swaps track info if the Cat Country station is playing. I also found another one station has the same issue. It should scrobble this station correctly too.

Don't know when the new version will be released, but you can install the extension from sources to use this feature now: https://github.com/david-sabata/web-scrobbler#unpacked-extension

This feature does not require any configuration.

Feell free to post here other stations that should be scrobbled with swapped artist-track info.

**Comment by pollorojo1147** [comment]
That works beautifully! Thanks for the quick reply!
