### ISSUE TITLE
PlayIrish

### ISSUE THREAD

**Issue by stephenjudge** [web-scrobbler/web-scrobbler#1972]
**Provide information about website**
PlayIrish is a new web radio station dedicated to playing new unsigned Irish artists as a showcase for radio stations to pick up the artists music and add them to their playlist.

The information webpage is at https://playirish.ie
The online webplayer is at https://playirish.ie/popup/
Looking at the code for the webplayer player you can extracted the stream feed from http://tx.sharp-stream.com/http_live.php?i=iasca.mp3 which includes current playing track metadata and plays fine in VLC. There is also references in the page code to Icecast XML so this might also be useful
A short description of the website, sample URLs, (demo) accounts for testing purposes. If (demo) accounts are not for public use, you can mail them to the project developers.

**Additional context**
I understand this is a very very niche music website, but as these are all new emerging Irish artists that are trying to get exposure and airtime, I really want to at least including my listenership in scrobbled data.

**Comment by alexesprit** [comment]
I think it won't be implemented, because there's no track info on the page, and using other sources (mp3 stream or Icecast) is quite hard.

**Comment by clasick** [comment]
Added a pull request that implements this player.
