### ISSUE TITLE
New version 2.17.0 filter rule for Spotify

### ISSUE THREAD

**Issue by hans-juergen** [web-scrobbler/web-scrobbler#1973]
> Added a rule to remove a "| Something" string from a track title.

I think this filter rule for YouTube would also make sense for the Spotify web player, or maybe even all sites which add strange things to their artist and track titles.

**Comment by alexesprit** [comment]
Could you provide examples of Spotify tracks?

**Comment by hans-juergen** [comment]
From my new Release Radar playlist:

Repeating "- Live at the Beacon Theatre, November, 2018" from the release title (a single in this case and using a hyphen in the track title instead of brackets):
https://open.spotify.com/track/4CNlBQ08DsipaFBSdbPOOE

Another "- Live" addition:
https://open.spotify.com/track/0V6raeW4AX6y7DBq6Kfzg8

And another:
https://open.spotify.com/track/2uF3AsLTgzmztIQTyvZir8

Tons of "- Remastered 2009" for Beatles tracks:
https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2

Same for many other band like Pink Floyd etc.

**Comment by alexesprit** [comment]
Well, there's no "| Something" in these tracks, right? The issue title is confising.

I'll add "- Live" filter to "Remastered" filters (and I'm going to rename it to "Spotify", as it used in Spotify connector, generally).

> Tons of "- Remastered 2009" for Beatles tracks:
> https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2

These tracks are already filtered.

**Comment by hans-juergen** [comment]
OK, thanks.
