### ISSUE TITLE
Plug.dj does not scrobble

### ISSUE THREAD

**Issue by thatrahrahbitch** [web-scrobbler/web-scrobbler#1974]
Although music is playing, Web Scrobbler says "Play some music to get started. Is it already playing?" I am then told to navigate to this page. 

1. Go to plug.dj
2. Join a community with music playing
3. View Web Scrobbler button

**Expected behavior**
I expected music to be scrobbled to my last.fm.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Firefox
-   Extension version: 2.17.0

**Additional context**

**Comment by alexesprit** [comment]
As you can see, scrobbling from plug.dj works fine. Any debug log or additional info?

![image](https://user-images.githubusercontent.com/1119267/57725289-71070180-7695-11e9-91e4-71923fcee929.png)
![image](https://user-images.githubusercontent.com/1119267/57725243-5a60aa80-7695-11e9-8ee7-7e121ee36313.png)
