### ISSUE TITLE
Where is edited metatdata stored?

### ISSUE THREAD

**Issue by lucccien** [web-scrobbler/web-scrobbler#1980]
Hi,

First, thank you for such a useful extension.

My issue is that whenever I move to a new browser or computer, I lose my edited scrobbles. That is to say, when I play a song that it did not recognize before, and that I manually edited the metatdata, it forgets everything I have typed, and I have to start over again, with EVERY video I have edited. Questions:

* Where is the data stored, so I may copy it over to my new browser or PC?

* Some extensions can save data to your google profile. I don't know how this is done, but is it possible to save edited scrobbles to someone's google account, so that it follows them?

Thanks!

Vince

**Comment by alexesprit** [comment]
> Where is the data stored, so I may copy it over to my new browser or PC?

It's stored in [Chrome Storage][0] (Chrome storage for extensions). You cannot copy this data directly, but you can export/import the data using "Export" and "Import" buttons in the extension settings.

![image](https://user-images.githubusercontent.com/1119267/57973913-e554e400-79b8-11e9-8b5b-44e98fe1c515.png)

> Some extensions can save data to your google profile. I don't know how this is done, but is it possible to save edited scrobbles to someone's google account, so that it follows them?

I wanted to implement importing/exporting saved data to cloud services ([ViolentMonkey][1] has such feature to sync userscripts), but it haven't been done yet.

[0]: https://developer.chrome.com/apps/storage
[1]: https://github.com/violentmonkey/violentmonkey

**Comment by lucccien** [comment]
Hi, thanks for such a quick response! I was blind before, I figured out the export not soon after I posted. I am glad to know you are considering importing and exporting to cloud services! In the meantime, I will just sync a folder to google drive, and manually save versions with dates. I'm sure you are busy; thanks for your time.
