### ISSUE TITLE
Resonate not scrobbling on Firefox

### ISSUE THREAD

**Issue by lindner** [web-scrobbler/web-scrobbler#1981]
**Describe the bug**
Despite changes in #1953 I am still not seeing scrobbles.

**How to reproduce**
1. Use Firefox Stable
2. Install Plugin, verify that it is the May 17th, 2019 version
3. Browse to beta.resonate.is
4. Note that the button changes to the last.fm icon with "This site is supported".
5. Play a track.

**Expected behavior**
Play status recognized and scrobbles made.

**Debug logs**
```
Injecting core/content/connector.js inject.js:62:7
Unchecked lastError value: Error: Script 'moz-extension://c8e19b88-d4dc-bb4b-abd6-393207d81128/connectors/resonate.js' result is non-structured-clonable data inject.js:63
Unchecked lastError value: Error: redeclaration of const Util inject.js:63
Injecting connectors/resonate.js inject.js:62:7
Unchecked lastError value: Error: redeclaration of const Connector inject.js:63
Tab 351: Remove controller for Resonate.is connector main.js:341:4
Tab 351: Created controller for Resonate.is connector controller.js:565:6
Injecting core/content/starter.js inject.js:62:7
Unchecked lastError value: Error: Script 'moz-extension://c8e19b88-d4dc-bb4b-abd6-393207d81128/connectors/resonate.js' result is non-structured-clonable data inject.js:63
Tab 351: Remove controller for Resonate.is connector main.js:341:4
Tab 351: Created controller for Resonate.is connector controller.js:565:6
```

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Firefox 66.0.5
-   Extension version: 2.17.1a

**Additional context**

**Comment by alexesprit** [comment]
I'm able to reproduce this issue on Firefox, but not on Chrome-based browsers.

The reason is [chrome.onUpdated][0] event is emitted twice with "complete" status.

[0]: https://developer.chrome.com/extensions/tabs#event-onUpdated

**Comment by alexesprit** [comment]
Figured out the real reason why it does not work.

Chrome:
![image](https://user-images.githubusercontent.com/1119267/58043480-f0894a80-7b45-11e9-847d-91bc5530543f.png)

Firefox:
![image](https://user-images.githubusercontent.com/1119267/58043113-0e09e480-7b45-11e9-8e3a-ea719a02a950.png)

Don't know if this issue is related to Firefox, or the website itself.

To be fair I don't want to add workarounds for Firefox, especially in connector code. @lindner AFAIK you're related to the Resonate project, right? It's could be good to update the website to indicate play/pause state as a attribute of some element, e.g.:
```html
<div class="player-component paused flex flex-column h-100">
   ...
</div>
```
or
```html
<div class="player-component playing flex flex-column h-100">
   ...
</div>
```

**Comment by lindner** [comment]
@alexesprit I filed an issue in the new stream2own repo.  (Resonate player is now open source!!)

**Comment by lindner** [comment]
Also is there a standard way to supply metadata for web apps?  I've noticed that when using Resonate Chrome updates the Bluetooth device with track/album/artist.

**Comment by inverse** [comment]
@lindner what do you mean by supplying metadata for web apps?

**Comment by inverse** [comment]
@lindner are you able to try this branch? https://github.com/web-scrobbler/web-scrobbler/pull/1994

I verified it on chrome and it seems to work just fine.

**Comment by alexesprit** [comment]
It works for me on both Chrome and Firefox after the 1994 is applied.

**Comment by alexesprit** [comment]
> Also is there a standard way to supply metadata for web apps?

AFAIK, there's no a such way. Current connectors use two different ways to get track info:
1. Parsing DOM.
2. Using internal website API.

Neither or these seems like standardized.

> I've noticed that when using Resonate Chrome updates the Bluetooth device with track/album/artist.

That's pretty insteresting. Does Chrome update the info from other websites?
