### ISSUE TITLE
Shazam

### ISSUE THREAD

**Issue by sheb667** [web-scrobbler/web-scrobbler#1982]
I use auto-shazam and I would really appreciate to have all my shazamed ttitles from the radio to be added to my lastfm account. Is it possible ?

thx

**Comment by alexesprit** [comment]
What is auto-shazam?

I know Shazam is an app for mobile smartphones, but the extension is for PC and Mac.

**Comment by sheb667** [comment]
Auto shazam is Just à function of shazam that recognizes all thé titles you play.
its on Android but thé rxtension works on firefox

**Comment by alexesprit** [comment]
> its on Android but thé rxtension works on firefox

Webextensions cannot interact with other apps.

**Comment by sheb667** [comment]
Shazam is also à Web site that can be reached on firefox too. Thé app is not mandatory
