### ISSUE TITLE
Support custom ListenBrainz url

### ISSUE THREAD

**Issue by FoxxMD** [web-scrobbler/web-scrobbler#1986]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use a custom URL for the ListenBrainz account, along with an api key. This [self-hosted, lastfm-esque application](https://github.com/krateng/maloja) can be [scrobbled to with the ListenBrainz protocol.](https://github.com/krateng/maloja#standard-compliant-api)

**Describe the solution you'd like**

Implement an alternative authentication method for a ListenBrainz account that allows a user to input a URL and api key.

**Comment by ZackBoe** [comment]
I've confirmed Web Scrobbler works with [Maloja](https://github.com/krateng/maloja) by hardcoding my token and replacing `https://api.listenbrainz.org` with `https://maloja.example.org/api/s/listenbrainz`

**Comment by FoxxMD** [comment]
I know this is probably a low priority but was wondering if there is any progress in adding more authentication options?

**Comment by inverse** [comment]
AFAIK no progress has been made. Feel free to work on it if you want

**Comment by alexesprit** [comment]
Added an initial support for custom ListenBrainz URL/token via user properties.

These properties are accessible by clicking on a "Properties" button in the extension settings.
![image](https://user-images.githubusercontent.com/1119267/80308883-2add7c00-87da-11ea-9334-f055bfeb51e7.png)

This button is displayed even if a user haven't signed in to ListenBrainz.

![image](https://user-images.githubusercontent.com/1119267/80308898-38930180-87da-11ea-8d25-62e03da02106.png)

Here are steps how to sign in with a custom token and to apply a custom URL.
1. Open the extension settings.
2. Click on the ListenBrainz "Properties" button.
3. Enter your API URL and token.
4. Click the "OK" button.

The extension will authenticate you automatically. Note that it doesn't validate your inputs.

Clicking on the "Sign out" button will also clear your API URL and your token.

@FoxxMD could you check this feature? It's not public, so you need to install the extension from the one of these zips to check it.
[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4535396/web-scrobbler-chrome.zip)
[web-scrobbler-firefox.zip](https://github.com/web-scrobbler/web-scrobbler/files/4535397/web-scrobbler-firefox.zip)

**Comment by FoxxMD** [comment]
@alexesprit I can confirm that the extension is working insofar as it is posting to the custom endpoint with my supplied api key. Thank you for doing the work to get this working!!

I've linked the issue I'm having with the scrobbler server -- I'm not sure whether its the extension or server having issues with the payload at this point.

**Comment by FoxxMD** [comment]
Issue was user error (of course). @alexesprit it works perfectly!

**Comment by alexesprit** [comment]
@FoxxMD sure, it will be available in the next version.
