### ISSUE TITLE
Not scrobbling Google Play Music on Chrom

### ISSUE THREAD

**Issue by spjcc** [web-scrobbler/web-scrobbler#1987]
**Describe the bug**
Removed and re-added Web scrobbler. Connected extension to my Last.fm account. Opened Google Play music and pressed play. No music scrobbling. 

**Environment (please complete the following information)**
-   Windows
-   Chrome 73.0.3683.103 
-  2.17.1

**Comment by alexesprit** [comment]
Can't reproduce.
<details>
  <summary>Screenshot (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/58326456-8dddca80-7e35-11e9-94b1-79f9517379f7.png)
</details>

[How to debug the extension.][1]

[1]: https://github.com/david-sabata/web-scrobbler/wiki/Debug-the-extension

**Comment by spjcc** [comment]
Resolved issue. Steps

- Closed all Chrome windows
- Restarted machine
- Updated Chrome
- Removed extension and re added
