### ISSUE TITLE
pls add the-radio and radiorecord

### ISSUE THREAD

**Issue by Greeple** [web-scrobbler/web-scrobbler#1989]
Сan you add http://the-radio.ru and http://www.radiorecord.ru/ on the radio record site all track titles in the same place http://prntscr.com/nt6ofu and the the-radio site is just a good combine from different radios, better than all you have in connectors
Thanks!

**Comment by alexesprit** [comment]
Closed as duplicate of #1869.

**Comment by Greeple** [comment]
> Closed as duplicate of #1869.
> 
> Please, don't duplicate issues, it won't help to resolve them. :)

Why removed both issues? would leave this one if it was really so necessary, just you, for half a year, did not add them, and I did not see my message, and I thought that it had already been deleted, so I wrote again

**Comment by alexesprit** [comment]
#1869 is not closed. If you open that issue, you can see it still is open and ready for someone who will resolve it.

**Comment by Greeple** [comment]
ok
