### ISSUE TITLE
Plex not working anymore

### ISSUE THREAD

**Issue by GabrielCalin** [web-scrobbler/web-scrobbler#1990]
I read that now the scrobbler supports the unified UI instead of the legacy UI.
I can only assume the unified UI is available only after you update the media server.
In my case, and probably many others, update is not always desirable (for example, in the new versions there is a bug with music rating that prevents me from using newer versions).
Scrobbler should support both legacy and new UI at least for some time (couple of years?).
For me, it's not scrobbling anymore because of this issue.

**Comment by alexesprit** [comment]
I can revert some changes and bring support for legacy UI back, but I cannot test it.

Did Plex work for you in previous version?

**Comment by GabrielCalin** [comment]
OK, I will test it :)
I now downgraded to 2.15.1 and it's working so you can take this version as a model.
Please let me know when you update the plugin and I'll update it and test it.

**Comment by alexesprit** [comment]
> I now downgraded to 2.15.1 and it's working so you can take this version as a model.

Thanks for the info.

> I can only assume the unified UI is available only after you update the media server.

IIRC, there were two types of Plex UI. One of them was available at `app.plex.tv`, and the second (legacy) UI at `127.0.0.0:32400`. Since some Plex update, only one type of UI is available at both addresses. I think you can access this UI by using `app.plex.tv` address, but I'm not sure if this UI has no bug you mentioned.

**Comment by GabrielCalin** [comment]
app.plex.tv shows the same (legacy) interface as localhost for me.
I can only assume that the new UI is only available after a media server upgrade.

**Comment by alexesprit** [comment]
@GabrielCalin I updated the Plex connector to support legacy UI. You can test the extension by installing it from the repository.

**Comment by GabrielCalin** [comment]
Hi,
I downloaded the repository as a zip file, I installed it from src folder, but still it doesn't recognize the music playing..

**Comment by alexesprit** [comment]
That's odd. I've just copied the code from v2.15.1 and adjusted it a little (but that shouldn't break the connector).

What's Plex version do you use?

**Comment by alexesprit** [comment]
@GabrielCalin could you install the extension from this branch? https://github.com/web-scrobbler/web-scrobbler/tree/feature/fix-plex

It works for me fine on both Plex 1.9.4 (Plex UI 3.20.7) and Plex 1.15.6 (Plex UI 3.100.1). Don't know which version do you use, but I hope it's fixed for you too.

**Comment by GabrielCalin** [comment]
You are right , I think earlier I had installed from the master branch.
But unfortunately the fix doesn't seem right either.

Now the album field is never filled but instead the second field in the notification shows a concatenation between the name of the song and the artist.

![image](https://user-images.githubusercontent.com/2115076/58749242-40440c00-848c-11e9-8daa-44a25ece2606.png)

When the correct fields should be (according to Plex's player):
![image](https://user-images.githubusercontent.com/2115076/58749251-623d8e80-848c-11e9-8443-c79ec9fe014c.png)

I am using Plex Version 1.12.2.4929 with UI Version 3.39.5

**Comment by alexesprit** [comment]
Updated the `fix-plex` branch. @GabrielCalin Could you download the extension again and check if the issue is fixed?

Works for me in 1.9.4 (3.20.7), 1.12.2 (3.39.5) and 1.15.6 (3.100.1).

**Comment by GabrielCalin** [comment]
It seems to work now, but I only tested it very quickly.
I will try listening to music on Monday with this fixed version and if I notice anything weird I'll come back to you.
Thanks for the good work!
