### ISSUE TITLE
Normalise other track titles with variations of "- Remix" to "(Remix)"

### ISSUE THREAD

**Issue by pgl** [web-scrobbler/web-scrobbler#1991]
**Is your feature request related to a problem? Please describe.**
This relates to #1984.

After listening to more of my playlist, I've come across more examples of Spotify's unusual naming scheme, eg:

```Track A - Remix
Track A - Group X dub
Track A - Group X edit
Track A - Group X mix
Track A - Group X Remix Edit
Track A - VIP
Track A - Radio Edit
Track A - X Radio Edit
Track A - Short Version
Track A - Original Mix
Track A - Radio Version
Track A - Group X Radio Mix
Track A - Continuous Mix
Track A - Factoria Vocal Mix
```

**Describe the solution you'd like**
It would be great to normalise track titles to include modifications like these in brackets, as with the change made in #1984.

I have forked the source and tested an alternative (more complicated) regex that I think solves this issue.

**Comment by alexesprit** [comment]
I merged #1992, so I think the issue is resolved.
