### ISSUE TITLE
Support Bandcamp User Collection

### ISSUE THREAD

**Issue by TheSacredPixel** [web-scrobbler/web-scrobbler#1996]
Playing tracks from a user's collection (e.g. https://bandcamp.com/sacredpixel) don't get recognized by the extension, even though playing from an album or artist's page (e.g. https://city-girl.bandcamp.com/album/chroma-velocity) works just fine. I can't remember if this was always the case, or a result of the new player on the user page.

**Comment by alexesprit** [comment]
@TheSacredPixel these webpages seem like just demos. Have you any examples of real user collections?
Also, I see no playback buttons on artist's page. Is it for me only?

@inverse the bandcamp connector is quite messy now. Can we refactor it to look like other connectors with multiple players supported? I don't know all cases covered by the connector, so you could help.

**Comment by inverse** [comment]
Will take a look when I have some time.

**Comment by TheSacredPixel** [comment]
@alexesprit Sorry, I just used artist and album as generic terms, didn't mean to seem like they were actual links. I've updated my comment with real examples.

**Comment by jaccarmac** [comment]
I'll take a look at this as well, noticed it the other day. Think it affects the player for Weekly as well?

**Comment by alexesprit** [comment]
I tried to refactor the connector to split support for different players, and found out a single Bandcamp page can contain at least two different players. For example, the [main page][main] contains elements of two players (album and weekly).

Another way to rewrite the connector is to using upcoming Connector API changes, where I added support for multiple selectors.

Also, I noticed the same player on [discover][discover] page.

> Think it affects the player for Weekly as well?

Weekly is already supported, isn't it? The updated connector should not affect weekly player (I mean it should not break support for Weekly).

[main]: https://bandcamp.com/
[discover]: https://bandcamp.com/tag/discover

**Comment by inverse** [comment]
I don't have much time at the moment so feel free to take it. I think the whole connector needs some :heart:  since it's trying to do too much at once. 

I suggest we split it into per page usage. like booting up like

```
(() => {
	if ($('.inline_player')) {
		console.log('Setting up inline player');
		inlinePlayer();

		return;
	}

	if ($('#collection-player')) {
		console.log('Setting up collection player');
		collectionPlayer();

		return;
	}


etc

	console.log('No player identified');
})();
```

**Comment by alexesprit** [comment]
@inverse we cannot split it:

> I tried to refactor the connector to split support for different players, and found out a single Bandcamp page can contain at least two different players. For example, the main page contains elements of two players (album and weekly).

**Comment by inverse** [comment]
@alexesprit surely there is a way to target which one that's playing. I mean you'll have to init the "connector" bootstrap based on the now playing one.  

Perhaps if we switch on the page. e.g. "homepage" detection based on some meta information?
