### ISSUE TITLE
Youtube unable to scrobble when language is Chinese

### ISSUE THREAD

**Issue by nershman** [web-scrobbler/web-scrobbler#1997]
**Describe the bug**
When youtube language is set to Chinese (中文（简体）) the scrobbler says it's unable to recognize a track. Sometimes it will give you the option to scrobble manually, and sometimes it gives you an error page with a link to github bug reporting.

**How to reproduce**
1. Go to any track that would normally scrobble on youtube
2. In the top right corner click on your avatar
3. In the drop-down menu, click on the language tab.
4. Scroll down to the bottom where you will find "中文（简体)" which is Simplified Chinese, change the language to this.
5. Reload the page, observe that the add-on does not recognize a track.

**Expected behavior**
It should recognize Chinese language and scrobble the track with the same behavior as the language was set to anything else.

**Environment (please complete the following information)**
-   OS: Mac OSX
-   Browser: Firefox 65.0.1
-   Extension version: I can't find this information :(

**Comment by alexesprit** [comment]
> When youtube language is set to Chinese (中文（简体）) the scrobbler says it's unable to recognize a track.

Could you try to turn on "Force track recognition" and tell if the extension recognizes tracks?

> Sometimes it will give you the option to scrobble manually, and sometimes it gives you an error page with a link to github bug reporting.

Does this behavior depends on playing track? Or is it happen ocassionally?

---

Some videos named using my native language (RU) have different name when English language is set. I think it's the same for you.

**Comment by nershman** [comment]
Hey, I think my extension was out of date. I hit update while trying to find the version number and haven't been having problems anymore.
