### ISSUE TITLE
Support for Telegram Web version

### ISSUE THREAD

**Issue by kilometrix** [web-scrobbler/web-scrobbler#1998]
The URL is https://web.telegram.org.
Is it possible to scrobble from this site?

**Comment by alexesprit** [comment]
I use Telegram, but I can't remember any scrobbleable data? Could you add some examples?

**Comment by kilometrix** [comment]
I thought of scrobbling audio file that is currently played:

![Скриншот 2019-06-19 13 37 58](https://user-images.githubusercontent.com/18598133/59758894-37767700-928f-11e9-9076-2316b3a3a2ea.png)

However I'm not sure that it is possible to implement scrobbling here. Maybe this [link](https://core.telegram.org/constructor/audio) to Telegram API where audio file is described will help somehow?

**Comment by alexesprit** [comment]
> Maybe this link to Telegram API where audio file is described will help somehow?

No, it won't help.

Theoretically, it's possible to implement scrobbing from Telegram, but it will rely on audio tags filled correctly (e.g. ID3 for MP3 files).

I'll take a look later and tell if it's implementable.

**Comment by alexesprit** [comment]
I'm not sure it it's possible to implement the connector. There's no a single player on the page, but a bunch of "mini-players" for each track.
