### ISSUE TITLE
Cannot write @ symbol in chrome when extension is active

### ISSUE THREAD

**Issue by spank79** [web-scrobbler/web-scrobbler#1999]
Since a couple of versions of chrome I cannot enter an "@" symbol with alt+L on mac OSX with this extension active in chrome

1. Install extension
2. Try entering an "@" symbol in address bar or any text field
3. does not work
4. now deactivate the extension
5. does work

**Environment (please complete the following information)**
-   OS: Mac OS 10.14.5
-   Browser: Chrome version 75.0.3770.100 but also last version 74.x
-   Extension version: 2.20.1

**Comment by alexesprit** [comment]
Could you open `chrome://extensions/shortcuts` and change Alt+L combination to Cmnd+L?

Is Alt+L common shortcut on all Macs or is it for your setup only?

I can change default shortcut, but I have no Mac and I cannot test if other shortcuts are not bound.

**Comment by Zielak** [comment]
I'll just add that `ALT` + `L` creates letter `Ł` in polish language. So even a combination like `ALT+SHIFT+L` will cause us trouble.

**Comment by alexesprit** [comment]
@Zielak could you suggest alternative shortcut for Mac? It's possible to define different hotkeys for different systems.

Currently, Alt+L is used to toggle love status of now playing track.

**Comment by Zielak** [comment]
I'm checking at `chrome://extensions/shortcuts ` and looks like `CONRTOL`+`ALT`+`L` would we fine. Anything with control+alt looks to be available, with one exception:
- while editing some text, control+alt+`B` and control+alt+`F` sends a cursor 1 word Back and 1 word Forward (never actually used it)

Keep in mind, that any shortcut with just `ALT` key, even on Windows, may interfere with letters of some European countries. Some letters are accessible through combination of `ALT` and for example `[ ] ; ' \ , . /` (all the keys to the right of the letters).

**Comment by Zielak** [comment]
Note: `CONTROL` and `COMMAND` are different keys on Mac ;)

**Comment by spank79** [comment]
Alt+l is default for the @ symbol on Mac osx so you should never overwrite
this. All it does is confuse people!

Darek Greenly <notifications@github.com> schrieb am Do. 20. Juni 2019 um
12:25:

**Comment by Zielak** [comment]
@spank79 depends on the language. For me `@` is at `shift`+`2`. What keyboard layout do you use?

Generally, `alt` + _any single key_ should be avoided.

**Comment by spank79** [comment]
I have it in the German layout, but thought US English would be the same. 🙄

Darek Greenly <notifications@github.com> schrieb am Do. 20. Juni 2019 um
13:06:

**Comment by alexesprit** [comment]
> Anything with control+alt looks to be available

We cannot use Ctrl+Alt or Cmd+Alt: https://developer.chrome.com/apps/commands (see "Usage" section).

Cmd+Shift+Key works fine, though.

We have the following commands with default shortcuts:
Alt+L: Toggle love status of now playing song.
Alt+R: Toggle connector (controller) state.
Alt+Shift+R: Disable connector (controller) until tab is closed.

I'd probably keep these for Windows and Unix.

Could you suggest default combinations for these commands applicable for Mac?

**Comment by goshki** [comment]
I don't want to create another issue so I'll just write here that currently when the extension is active it's not possible to write polish "ł" letter on Mac because it's typed using OPTION+L combination, so some kind of ability to redefine those key shortcuts (or disabling them altogether) would be great.

**Comment by alexesprit** [comment]
@goshki as I previously said I have no Mac and I don't know what keys are not used by iOS. You could suggest default shortuts, though.

All extension shortcuts can be redefined or cleared here: chrome://extensions/shortcuts

**Comment by goshki** [comment]
It's not just Mac, ALT+L is used to get "ł" on Windows. Great info about chrome://extensions/shortcuts, I wasn't aware of this. I see that most of the extensions I have installed do not define default shortcuts even though they have shortcut actions available.

Maybe this is the proper route to go – leave the shortcuts blank but inform the WebScrobbler user (for example in Options / FAQ) that there is an option to configure those shortcuts in Chrome extension options? After all, shortcuts are for power-users. 😉

**Comment by alexesprit** [comment]
> Maybe this is the proper route to go – leave the shortcuts blank but inform the WebScrobbler user (for example in Options / FAQ) that there is an option to configure those shortcuts in Chrome extension options? After all, shortcuts are for power-users. 😉

Yes, I think it's a perfect solution.

**Comment by alexesprit** [comment]
https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.20.3
