### ISSUE TITLE
Popup says "Service error" even though the song gets submitted to Listenbrainz

### ISSUE THREAD

**Issue by smurfpandey** [web-scrobbler/web-scrobbler#2000]
**Describe the bug**
Since past few days I am noticing that I am getting service error even if the song gets submitted to Listenbrainz successfully.

**How to reproduce**
1. Go to 'https://www.youtube.com/watch?v=0vnL46Q2-YE'
2. Wait for song to get scrobbled.
3. Notice the browser icon turn yellow instead of green.
4. Click on the icon to see Service Error popup

**Expected behavior**
The icon should get green, and I should get the edit box on clicking the icon.

**Screenshots**
![error-web-scrobbler-1](https://user-images.githubusercontent.com/3392699/59861036-b1952180-939d-11e9-9340-d0abfaa9c18d.png)
![error-web-scrobbler-2](https://user-images.githubusercontent.com/3392699/59861037-b22db800-939d-11e9-96d5-b480b6d54d3d.png)

**Debug logs**
```
Found album artwork via MusicBrainz
util.js:127 Tab 108: Song finished processing: {
  "parsed": {
    "track": "Asim Azhar",
    "artist": "Khuwahish",
    "album": null,
    "uniqueID": "0vnL46Q2-YE",
    "duration": 283,
    "currentTime": 5,
    "isPlaying": true,
    "trackArt": null
  },
  "processed": {
    "track": "Asim Azhar",
    "album": "",
    "artist": "Khuwahish",
    "duration": null
  },
  "internalId": "0vnL46Q2-YE",
  "metadata": {
    "userloved": false,
    "startTimestamp": 1561044062,
    "label": "YouTube",
    "artistThumbUrl": "http://coverartarchive.org/release/21051ba8-0a36-4e04-a369-62e01ad23bae/front",
    "artistUrl": "https://www.last.fm/music/Khuwahish",
    "trackUrl": "https://www.last.fm/music/Khuwahish/_/Asim+Azhar",
    "albumUrl": "",
    "musicBrainzId": "21051ba8-0a36-4e04-a369-62e01ad23bae"
  },
  "flags": {
    "isProcessed": true,
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  }
}
util.js:127 Tab 108: The song will be scrobbled in 138.5 seconds
scrobble-service.js:106 Send "now playing" request: 1
_generated_background_page.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
util.js:127 ListenBrainz: {"status":"ok"}

util.js:127 Tab 108: Song isn't set as now playing
util.js:127 Tab 108: isPlaying state changed to false
util.js:127 Tab 108: isPlaying state changed to true
util.js:127 Tab 108: isPlaying state changed to false
```

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: v2.20.1

**Additional context**
I tried to find out the root cause, and I found that it's going to `else` statement here. Maybe because the result is string instead of object. Not very sure why it's going in else.
https://github.com/web-scrobbler/web-scrobbler/blob/master/src/core/background/object/controller.js#L504

**Comment by alexesprit** [comment]
Thanks for reporting the issue!

Fixed in v2.20.2.

**Comment by smurfpandey** [comment]
Wow! That was fast. :)

**Comment by inverse** [comment]
... and this was issue #2000 :dancer:
