### ISSUE TITLE
Make clear whether a song was loved or unloved when using hotkeys

### ISSUE THREAD

**Issue by CennoxX** [web-scrobbler/web-scrobbler#2003]
When the hotkey is used, it is not clear whether a song was loved or unloved. The only way to find out is to open the popup, which makes the hotkey kinda useless.
Also, in terms of usability, it would be good to get feedback whether using the hotkey has had any effect.

Possible solutions would be:
* only love the song with the hotkey
* two hotkeys, one to love, one to unlove the song
* whenever the hotkey is used once, love the song when twice unlove
* display a notification if a song has been loved or unloved

**Comment by alexesprit** [comment]
I'm for the 4th option. Other ways have no feedback.

**Comment by CennoxX** [comment]
A combination of the 2nd and the 4th option would be possible to.
If using only the 4th option you'll still have to read the notification after first hotkey use and if song was already in desired state, you'll have to use it a second time (and get a second notification in short time).
If there are two hotkeys, you could have a short glance at the notification and continue working.

**Comment by CennoxX** [comment]
Another possibility would be to show the loving/unloving in the scrobbler icon, this would be less pervasive than a notification.

**Comment by alexesprit** [comment]
@CennoxX do you mean to update the browser icon like this?
![image](https://user-images.githubusercontent.com/1119267/61171042-8952aa00-a57a-11e9-86a0-c8db01c548e2.png)

If so, I can update the extension to display love/unlove icon few seconds after hotkey is pressed.

I tested love/unlove with notifications displayed, and it's really weird, especially on Opera and Windows 10.

**Comment by alexesprit** [comment]
I splitted "toggle love" hotkey to two ones: "love" and "unlove", added a temporary browser icon change after hotkey use. Captured demo record of the feature: https://www.youtube.com/watch?v=fTQPyuMBkt0. I'm bad at video editing, so I put some description in subtitles, so make sure to turn them on. :)

What's your thoughts on this implementation?

**Comment by CennoxX** [comment]
That looks great to me!

Alexey <notifications@github.com> schrieb am Mo., 15. Juli 2019, 21:59:

**Comment by alexesprit** [comment]
> How fast does it react?

The extension updates the icon icon after a response from Last.fm is received. So, if the network connection is good, it reacts almost immediately.
