### ISSUE TITLE
About custom URL patterns

### ISSUE THREAD

**Issue by lifeproofminds** [web-scrobbler/web-scrobbler#2004]
Hello,
I'm struggling to make a correct URL pattern for one artist found at Bandcamp website - https://blankembrace.com. I looked FAQ about custom URL patterns and also checked how match patterns works in Chrome, tried several patterns but without results. 
Is it possible to scrobble this artist and if it is, what URL pattern I have to add? Thank you.

**Comment by alexesprit** [comment]
Try to add `*://blankembrace.com/*`. It works for me.

**Comment by lifeproofminds** [comment]
Oh! Yes, now it works with your pattern. Somehow I misunderstood how to use * character. Thank you for your quick response.
