### ISSUE TITLE
Clicking "sign in" links under options/accounts doesn't open anything 

### ISSUE THREAD

**Issue by aaroncolichia** [web-scrobbler/web-scrobbler#2005]
Using firefox 67.0.3 after installing web scrobbler v2.20.3 and opening options, I try to click "Sign in" links for the supported scrobbling services under the accounts section.  This results in no action taken as though the link is dead.  Copying and pasting the link this is what firefox shows they contain: 

"moz-extension://83c8dcca-51a3-4e77-8abe-6b8e292a25ef/options/index.html#"

1. On android PIE, using firefox 67.0.3
2. Install web scrobbler addon v2.20.3
3. Open web scrobbler options, click 'accounts'
4. Click "Sign in" links next to any scrobble provider
5. Note no action taken

**Expected behavior**
Tab opened to respective scrobbling provider asking for authorization 

**Environment (please complete the following information)**
-   OS: Android PIE
-   Browser: Firefox 67.0.3
-   Extension version: v2.20.3

**Additional context**
This was working a couple of months ago just fine

**Comment by alexesprit** [comment]
Seems like it was broken in a3f326ca80e38ee140d735b6cef435e62738ff32. Interestingly, v2.20.x works fine on Firefox for desktop.
