### ISSUE TITLE
Mixcloud doesn't scrobble

### ISSUE THREAD

**Issue by muhomoru** [web-scrobbler/web-scrobbler#2008]
I think it happens for a couple of months, first I thought that's temporary but it doesn't seem so anymore.

It looks like the page is constantly loading (the circle keeps spinning) but it actually is loaded and everything works fine except for scrobbling. It just says that it doesn't support this site.

**Comment by alexesprit** [comment]
It works fine for me:
![image](https://user-images.githubusercontent.com/1119267/60769892-e44d5280-a0dd-11e9-91a6-da0529f79fb3.png)

Have you any additional information? Logs, screenshots etc.

**Comment by inverse** [comment]
Can't reproduce either :(

**Comment by muhomoru** [comment]
seems like an adblock was the problem. i turned it off and now everything mostly works fine. sorry for bothering!

**Comment by alexesprit** [comment]
@muhomoru no worries!

That's quite strange the extension does conflict with AdBlock. Btw, I use uBlock Origin, and it's compatible with Web Scrobbler on Mixcloud. Anyway, I'm glad it's working fine for you.
