### ISSUE TITLE
Not scrobbling music from bandcamp

### ISSUE THREAD

**Issue by duramato** [web-scrobbler/web-scrobbler#2009]
**Describe the bug**
It is not scrobbling a song, it should be

**How to reproduce**
1. Go to https://khoven.bandcamp.com
2. Listen to the song
3. It will recognize the song
4. It won't scrobble

**Expected behavior**
It should scrobble the song.

**Debug logs**
https://gist.github.com/duramato/244d73d53ba5c66f37686edf6ffd1233

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.20.3

**Comment by alexesprit** [comment]
> It will recognize the song
> It won't scrobble

The track isn't scrobbled because it's not recognized by Last.fm. This is expected behavior and won't be changed in near future.

You can force scrobbling with the "Force song recognition" option turned on.

**Comment by duramato** [comment]
I already have option turned on, and it doesn't make a difference.

**Comment by alexesprit** [comment]
I found out why this track is not scrobbled:
```xml
Last.fm: track.updatenowplaying response:
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <nowplaying>
    <track corrected="0">khovendeath.flac</track>
    <artist corrected="0">gone</artist>
    <album corrected="0">Untitled Album</album>
    <albumArtist corrected="0"></albumArtist>
    <ignoredMessage code="1"></ignoredMessage> <!-- Last.fm ignored request -->
  </nowplaying>
</lfm>
```

As you can see, Last.fm ignored this song. To fix this, I changed the track title to `khovendeath`:
```xml
Last.fm: track.updatenowplaying response:
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <nowplaying>
    <track corrected="0">khovendeath</track>
    <artist corrected="0">gone</artist>
    <album corrected="0">Untitled Album</album>
    <albumArtist corrected="0"></albumArtist>
    <ignoredMessage code="0"></ignoredMessage> <!-- Accepted -->
  </nowplaying>
</lfm>
```

Could you tell if changing track resolves the issue?

**Comment by hans-juergen** [comment]
It probably will, as file extensions in an artist, album or track name like WAV, FLAC, MP3 are filtered by Last.fm to prevent the database from adding too many wrong ID3 tags = new pages. There are other filters in place as well, e.g. for song numbering etc.

**Comment by duramato** [comment]
Changing the track name works. If lastfm doesn't accept file extensions in the filename, shouldn't they be filtered out?

**Comment by alexesprit** [comment]
> If lastfm doesn't accept file extensions in the filename, shouldn't they be filtered out?

We can, but doesn't make sense if there's one or two tracks on Bandcamp with extension suffixed. They can be edited, and edits are saved.

**Comment by hans-juergen** [comment]
Furthermore there are some bands who insist on having a name with a file extension or use album or track titles that look like file names on purpose. Last.fm has to put those in a whitelist then which may take time or could get wrong for other reasons.
