### ISSUE TITLE
Add support for wynk music https://wynk.in/music

### ISSUE THREAD

**Issue by nishantjulian** [web-scrobbler/web-scrobbler#2012]
**Provide information about website**

Wynk Music is a music app, web player owned by Bharti Airtel, used extensively in India. Login is through mobile number.

Webplayer link - [https://wynk.in/music](https://wynk.in/music)

**Additional context**
<img width="1440" alt="Screenshot 2019-07-10 at 1 09 26 PM" src="https://user-images.githubusercontent.com/23497194/60950095-22cc5280-a314-11e9-98c1-8ecd691800ad.png">

**Comment by anuragbhd** [comment]
Hi @nishantjulian. I've created a PR #2069 that adds Wynk support. Hopefully someone will review and merge soon.
