### ISSUE TITLE
Add support for LivePhish

### ISSUE THREAD

**Issue by aybesea** [web-scrobbler/web-scrobbler#2016]
**Provide information about website**
LivePhish is a paid service that streams all live Phish performances. A free trial is available at https://www.livephish.com/

Thank you!

**Comment by aybesea** [comment]
I would be willing to pay for a month for a developer if they need it to get this working!

**Comment by goldwave315** [comment]
this would be a great addition and much appreciated!

**Comment by inverse** [comment]
It's in the next release - thanks @goldwave315
