### ISSUE TITLE
Online scrobbler stopped working

### ISSUE THREAD

**Issue by pumpking44** [web-scrobbler/web-scrobbler#2019]
Few weeks ago scrobbler stopped working on Firefox. All the pages I tried play music with, make the icon yellow (as you may see in the picture). I tried it on Chrome and it worked - until today, now I've got the same problem there. What can I do?
![aa](https://user-images.githubusercontent.com/53211811/61692019-28229780-ad2d-11e9-9785-3914a85eae1d.jpg)

**Comment by alexesprit** [comment]
Have you tried to reauthenticate?

Also, [how to debug the extension.][1]

[1]: https://github.com/david-sabata/web-scrobbler/wiki/Debug-the-extension

**Comment by MarcoSimon** [comment]
Hey there, I recognized the same issue. The extension worked as expected in Chrome until yesterday, but now it doesn't anymore (v2.21.0).

Log: [https://pastebin.com/Tge5yH2T](https://pastebin.com/Tge5yH2T)

**Comment by alexesprit** [comment]
@MarcoSimon according to your logs, everything works fine for you. Do you see yellow icon too?

**Comment by MarcoSimon** [comment]
@alexesprit thanks for your quick response! No, I see a green icon, it seems to be fine. But on [Last.fm](https://www.last.fm/user/MrFahrenheit200), nothing appears. When you say everything _is_ fine, maybe an issue with Last.fm…?! I found [this post on their service community](https://getsatisfaction.com/lastfm/topics/nothing-is-scrobbling-r752w997ku8e9) and according to the last comments, it seems scrobbling has stopped working a couple of hours ago.

Anyway, thanks for your effort!

**Comment by alexesprit** [comment]
@MarcoSimon seems like Last.fm API works fine (that's why you see the green icon), but website has some issues.

**Comment by alexesprit** [comment]
@pumpking44 @MarcoSimon is it still an issue for you guys? Someone [posted][post] it works again for them.

[post]: https://getsatisfaction.com/lastfm/topics/nothing-is-scrobbling-r752w997ku8e9?topic-reply-list[settings][page]=2#topic-reply-list

**Comment by emilironnytea** [comment]
Not working...

**Comment by IRainman** [comment]
Hello. I use 2.21 and 2.21.1. Based on the recommendation from the extension, I’ve logged out from last.fm when there is an "internal error" problem and now I can’t even enter.

**Comment by MarcoSimon** [comment]
@alexesprit I think this issue was a consequence of Last.fm issues. For two days, it worked again as expected – until now.

@IRainman yes, I had the same problem. I also logged out and couldn't login again. After a few minutes, it worked and I was able to grant access to the webscrobbler to Last.fm. But there are still problems with the **Last.fm API**, this is what my console says when trying to scrobble or authenticate:

![2019-07-26 09_43_12-Window](https://user-images.githubusercontent.com/6904649/61935803-8947a680-af8b-11e9-81b0-49131cf56864.png)

**Comment by emilironnytea** [comment]
I think  problem and is in the extension too, as it does not try to re-scrobble of track on YouTube played on repeat

**Comment by alexesprit** [comment]
I'm closing this one, as it's not related to this extension.

We can partially resolve the issue by implementing #211.

**Comment by emilironnytea** [comment]
What do you have in mind? How does this solve the problem?

**Comment by alexesprit** [comment]
Users will be able to scrobble cached tracks later if Last.fm API is down. We can do nothing else with broken API.

**Comment by emilironnytea** [comment]
At than here API, when the extension doesn't even try to re-recognize the track, as it was before
That sad ... especially for those, who are listening to the track for half a day - he now has one scrobble... 
Scrobbling from AIMP is coming without lossed - another question is that there are many of things,  now simply to which is not in form of audio files, and youtube was enough ...

**Comment by IRainman** [comment]
@alexesprit Hmm, I checked the method described by @emilironnytea with AIMP - there are no problems, everything works. I have a problem with Yandex-Music, not from Youtube. For example, [this track](https://music.yandex.ru/album/5666060/track/42784128) is obviously written and everything is clear, but it will not be scrobbling.  It's a problem, really.

**Comment by emilironnytea** [comment]
problem exactly is with YouTube, with a regular scrobbler there are no problems

**Comment by alexesprit** [comment]
@emilironnytea @IRainman здесь мы обсуждали проблему, которая возникала из-за того, что у Last.fm отвалился API. Я понимаю, что у вас есть какие-то проблемы/ошибки, но не надо их писать в одном issue. Поймите, что если кто-то захочет это починить, то он не будет искать описание проблемы в комментариях к другому issue. Для этого лучше создать новый.

@IRainman this track у меня почему-то заскробблился. Если у тебя не скробблится, то это фигня какая-то, и надо смотреть логи, чтобы разобраться.

@emilironnytea если честно, то я не понял в чём у тебя проблема. Напиши мне на русском на почту или куда-нибудь ещё (контакты [тут][сайт]), попробуем решить проблему.

На русском языке или на ломаном английском, мне кажется, на Гитхабе писать особо не стоит, поэтому для связи я предложил почту или что-то ещё.

Тред я заблокировал.

[сайт]: https://alexesprit.github.io/
