### ISSUE TITLE
Add Nugs.net support

### ISSUE THREAD

**Issue by aybesea** [web-scrobbler/web-scrobbler#2020]
**Provide information about website**
Nugs.net is a streaming service that covers about 100 jam bands, notably Dead & Co, Widespread Panic, Pearl Jam, Gov't Mule and Umphrey's McGee. This is very closely related to the LivePhish request that I put in earlier. Granted, it is a separate service, but both are run by Nugs and both use extremely similar software apps.

**Additional context**
A free trial is available at www.nugs.net

**Comment by bsutich** [comment]
I have an account for the site, and would love to help in any testing of the scrobbling tool. Currently using macOS. Can test on Safari, Chrome, Firefox, etc.

**Comment by circlecube** [comment]
I set up a PR to add support for nugs.net scrobbling, hopefully we can get it merged in soon!

**Comment by inverse** [comment]
Should be in the recently published release. 

Thanks @circlecube
