### ISSUE TITLE
Cannot disable YouTube using toolbar icon

### ISSUE THREAD

**Issue by andreymal** [web-scrobbler/web-scrobbler#2021]
**Steps to reproduce**

1. Go to any youtube page
2. Right-click the toolbar icon
3. Click "Disable YouTube" (NOT "Disable connector until tab is closed"), it will be disabled
4. Refresh the page or open a new tab
5. It's enabled again, but I didn't click "until tab is closed"

**Expected behavior**
YouTube should be disabled forever until I enable it manually again

**Screenshots**
![](https://i.imgur.com/SFiz2H5.gif)

**Debug logs**

<details>
<summary>Click me</summary>

```
Injecting vendor/jquery.min.js inject.js:56:12
Injecting vendor/browser-polyfill.min.js inject.js:56:12
Injecting core/content/util.js inject.js:56:12
Injecting core/content/reactor.js inject.js:56:12
Injecting core/content/filter.js inject.js:56:12
Injecting core/content/connector.js inject.js:56:12
Injecting connectors/youtube.js inject.js:56:12
Error: "Script 'moz-extension://0053b372-c7be-41d0-993a-e93b95c9882b/connectors/youtube.js' result is non-structured-clonable data" inject.js:61:13
Injecting core/content/starter.js inject.js:56:12
Tab 457: Remove controller for YouTube connector extension.js:336:12
Tab 457: Created controller for YouTube connector
```

</details>

**Environment**
-   OS: Arch Linux
-   Browser: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
-   Extension version: v2.21.0

**Additional context**

I also tried to disable all other extensions, but it's still not working.

Polymer on YouTube is not enabled for me.

**Comment by alexesprit** [comment]
Hi, I'm aware of this, and I've fixed the issue in master. Will publish a patch update.
