### ISSUE TITLE
BBC Sounds scrobbles one song and nothing that comes after. 

### ISSUE THREAD

**Issue by loppy25** [web-scrobbler/web-scrobbler#2027]
BBC Sounds is now a connector on the application yet when using the website to listen to radio live, the web-scrobbler scrobbles one song from the metadata and nothing else that comes after it. 

**How to reproduce**
1. Go to bbc sounds
2. Click on any radio station 
3. Scrobbles one song/piece
4. Next song plays "Live" and the web-scrobbler does not respond.

**Comment by alexesprit** [comment]
Can't reproduce. Have you any additional information?

**Comment by loppy25** [comment]
> 
> 
> Can't reproduce. Have you any additional information?

Using Firefox is about the only additional information I can give at the moment/think of. 

Below are some screenshots attached. 

![BBC Sounds 1](https://user-images.githubusercontent.com/53440050/62122468-aa770280-b2bd-11e9-960c-61f693429735.PNG)

This screenshot shows the landing page of BBC Sounds. The time at this moment is 1126am BST 

![BBC Sounds 2](https://user-images.githubusercontent.com/53440050/62122507-bfec2c80-b2bd-11e9-9f0f-97dcb166605f.PNG)

This screenshot shows the web-scrobbler which has scrobbled correctly. The time is still 1126am BST 

![BBC Sounds 3](https://user-images.githubusercontent.com/53440050/62122548-db573780-b2bd-11e9-8deb-26ad71803b70.PNG)

Now I have refreshed the webpage and have been greeted with the same landing page as screenshot 1. The time is now 1129am BST and now the web-scrobbler acknowledges that a new track has been played and inputs the data. If I would have stayed on the same page as 1126am, hundreds of songs could play without any scrobbling. 

![BBC Sounds 4](https://user-images.githubusercontent.com/53440050/62122682-2b35fe80-b2be-11e9-8680-1c25ca7a7d62.PNG)

I think one reason why this issue is occurring is due to the BBC themselves not updating the "recently played" bar unless you refresh the page. I think before this used to refresh itself but now, this only refreshes if you refresh the webpage.

**Comment by alexesprit** [comment]
> I think one reason why this issue is occurring is due to the BBC themselves not updating the "recently played" bar unless you refresh the page. I think before this used to refresh itself but now, this only refreshes if you refresh the webpage.

Yes, I have the same behavior on Firefox, but not Chrome.

Unfortunately. we cannot resolve this issue on the extension side.

**Comment by loppy25** [comment]
> 
> 
> > I think one reason why this issue is occurring is due to the BBC themselves not updating the "recently played" bar unless you refresh the page. I think before this used to refresh itself but now, this only refreshes if you refresh the webpage.
> 
> Yes, I have the same behavior on Firefox, but not Chrome.
> 
> Unfortunately. we cannot resolve this issue on the extension side.

Ah right. Thanks. Hopefully the BBC get it sorted on their side quickly. :)

**Comment by alexesprit** [comment]
I submitted the issue via BBC feedback form.
