### ISSUE TITLE
Display number of scrobbles of a song

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#2028]
Display the number of scrobbles of the song being played

**Comment by alexesprit** [comment]
Where do you want to display the number?

**Comment by pedrojvaz** [comment]
Apologies for the late reply.
I'm not a designer, but I'd say somewhere inside the box? A notification with number might be too much, too distracting, IMO

Thanks!

![image](https://user-images.githubusercontent.com/4522620/65073384-0ba08580-d993-11e9-85d1-7c8762494684.png)

**Comment by anuragbhd** [comment]
@pedrojvaz I've submitted a PR #2070 that hopefully addresses your feature request. I also personally find it useful to see my scrobble count for a song more often than not.
