### ISSUE TITLE
Youtube video is not getting scrobbled even if it's in Music category

### ISSUE THREAD

**Issue by smurfpandey** [web-scrobbler/web-scrobbler#2030]
**Describe the bug**
I have configured the extension to only scrobble videos with category Music. It's been working as expected, except for this video: https://www.youtube.com/watch?v=IO-mxkUImMA

The videoCategory being picked up is `/channel/UC3_S4mH9ugGxUIpqhrSU7yQ`, which is not correct.

**How to reproduce**
1. Configure the extension to only scrobble videos from Music category on Youtube.
2. Go to 'https://www.youtube.com/watch?v=IO-mxkUImMA'
3. Wait for sometime
4. The extension popup says "Play some music to get started", instead of scrobbling.

**Expected behavior**
The song should get scrobbled.

**Screenshots**
![web-scrobbler-bug](https://user-images.githubusercontent.com/3392699/62380669-47a89400-b567-11e9-8611-d0c348dc7853.png)

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: 2.21.1

**Comment by smurfpandey** [comment]
I am not sure if it's helpful, but I did some more digging into this. It seems the selector for getting the category is not working on this video.

I wrote another selector which seems to be working:
```Javascript
$('yt-formatted-string:contains("Category")').parent().next().find('a.yt-simple-endpoint').attr('href')
```

On this video, the current selector is picking up "Caption authors" which is just above Category in the description.

I tested the above selector on few more videos, and it's working for me. But I am not sure if it will work everywhere, as the Category text might be in some other language on localized version of YouTube (if it exists).

**Comment by alexesprit** [comment]
> I tested the above selector on few more videos, and it's working for me. But I am not sure if it will work everywhere, as the Category text might be in some other language on localized version of YouTube (if it exists).

Yes, this string is different if another language is selected, so we cannot use this selector to fix the issue.
