### ISSUE TITLE
Option to manually approve each new scrobble source

### ISSUE THREAD

**Issue by kini** [web-scrobbler/web-scrobbler#2031]
**Is your feature request related to a problem? Please describe.**

I find my last.fm profile constantly getting polluted with stuff on youtube that happened to have a hyphen in the video title, etc. My current workaround is to just go to last.fm every couple weeks and try to clean up and delete erroneous scrobbles, which is not very fun :)

**Describe the solution you'd like**

I would like an option that would let me approve each scrobble manually. That way I can make sure nothing wrong gets into my last.fm data.

Ideally, if I have already approved a scrobble from a particular page in the past (e.g. a particular youtube video), then the scrobble can be submitted automatically. But I'm not sure whether web scrobbler keeps track of a list of previously scrobbled pages to check against. If implementing this would be too much work, then please ignore this paragraph.

**Describe alternatives you've considered**

In #1496, it's suggested that scrobbles only be done automatically if musicbrainz or last.fm API returns a positive hit for the guessed scrobble, and otherwise the user should be consulted. I think my request is easier to implement since it doesn't require any logic related to talking to the mbz or last.fm API, just some UI programming to provide a way for the user to accept a scrobble.

**Comment by alexesprit** [comment]
This is probably a duplicate of #1560.

**Comment by kini** [comment]
Yes, I think you are right. Closing as duplicate.
