### ISSUE TITLE
Please add support to Newgrounds Audio Portal

### ISSUE THREAD

**Issue by nikos3194** [web-scrobbler/web-scrobbler#2033]
**Provide information about website**
Newgrounds is a website founded in 1995 that offers space for artists, game designers and musicians. As regards the audio portal ( [https://www.newgrounds.com/audio](https://www.newgrounds.com/audio) ), many artists publish their own musical productions in the style of sites such as Bandcamp or Soundcloud.

Despite the age of the site, in the last year it gained popularity by receiving a large number of users who left the Tumblr social network.

Here are some examples of popular tracks:
https://www.newgrounds.com/audio/listen/105753
https://www.newgrounds.com/audio/listen/361366
https://www.newgrounds.com/audio/listen/75190

List of other popular tracks:
https://www.newgrounds.com/audio/browse/sort/score

**Additional context**
Screenshot:
![ng](https://user-images.githubusercontent.com/3865571/62569962-94d97e00-b865-11e9-8683-368d6f60fffe.png)

Thank you!

**Comment by Ydeu** [comment]
Hello there,

As this is labelled as "good first issue", as a newcomer to the Github, I would like to try my best to resolve the issue. 

With that in mind, any additional tips on how to proceed with the "connector request" type of issues? (Tips not mentioned in wiki/Connectors-development and wiki/Setup-development-environment)

Best regards, Ydeu

**Comment by alexesprit** [comment]
> With that in mind, any additional tips on how to proceed with the "connector request" type of issues? (Tips not mentioned in wiki/Connectors-development and wiki/Setup-development-environment)

No additional tips; you can freely start to write a code. After you decide it's complete you can submit a PR for review.

**Comment by Ydeu** [comment]
Hello there,

I have stumbled upon some interesting names of tracks on the site. I would like to maximize the amount of successful scrobbles but I am not sure what is considered a valid track name in these cases. Also, how and if I should "bother" with some of the cases bellow. Track name examples:

"Black Cat" by Libby Shimmz feat. Black Dog
Axeph-Null - Menger's N-Arc Theorem
.- KIRBY 64 | Boss 2 -
{Heim} Ethnic Battle
-[PK]- Blue world
"The Bacon Song"
'All I Got'' (Billis23)
N3Ogouds - City of imagination (glitch hop)
<PS> A Heart Worth Mending
[Knox]Brokendeck

These names may negatively impact the result of scrobbling, as people sometimes tend to:
- Mention a genre or artist of the song in the track name in (), [], {} braces or in <>.
- Mention song name in double quotes, single quotes or different chars.
- Use separators as -, by, | and "" and may do so in the track name more than once.
- A separator is part of a track name or artist name. 
- Combinations of cases mentioned above.

**Comment by alexesprit** [comment]
Closed via #2155.
