### ISSUE TITLE
Issue scrobbling for pandora

### ISSUE THREAD

**Issue by GreenYuran** [web-scrobbler/web-scrobbler#2034]
Don't scrobbling any track from Pandora's Web Player
https://www.pandora.com/station
Skreen: http://prntscr.com/opivjo
Browser: Firefox
OS: Windows7

**Comment by alexesprit** [comment]
It works fine for me on Firefox and Chrome.

[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by inverse** [comment]
Unable to verify here - geo-fenced :/

**Comment by alexesprit** [comment]
Closed as outdated.

P.S. It still works fine for me:
![image](https://user-images.githubusercontent.com/1119267/67159571-fda5a200-f34e-11e9-8099-113dbaab61a9.png)
