### ISSUE TITLE
Listen.moe not scrobbeling.

### ISSUE THREAD

**Issue by calvinc64** [web-scrobbler/web-scrobbler#2035]
**Describe the bug**
Well, after another Design update, listen.moe does not work again.

**How to reproduce**
1. Go to 'https://listen.moe/'
2. Click on 'play'
3. Not playing

**Expected behavior**
Should normally scrobble songs.

**Environment (please complete the following information)**
-   OS: Win10 1903
-   Browser: Firefox 68.0.1
-   Extension version: 2.21.2

**Comment by calvinc64** [comment]
Well, like I said, in this version of the Scrobbler, the scrobbeling does not work...
![grafik](https://user-images.githubusercontent.com/5560381/63100900-4a988100-bf78-11e9-90fa-2abbe6312478.png)

**Comment by alexesprit** [comment]
It will in the next one.
