### ISSUE TITLE
Lastfm not recognizing Bandcamp scrobbles?

### ISSUE THREAD

**Issue by franconia2022** [web-scrobbler/web-scrobbler#2036]
**Describe the bug**

Streamed some stuff on Bandcamp, noticed it didn't come up on last.fm on recent tracks or "now playing", and last.fm has been recognizing all my Spotify plays today so the servers aren't down on that end. Yellow "service error" comes up on bandcamp now.

**How to reproduce**

Try streaming anything on bandcamp.

**Expected behavior**

I don't use bandcamp that much but it's always scrobbled for me (except for on the mobile app, still annoyed by that), and last.fm has been working fine for a while so I expected the streams to transfer.

**Screenshots**

![image](https://user-images.githubusercontent.com/54127809/63069336-78cc8100-bee4-11e9-909d-9785521559ab.png)

![image](https://user-images.githubusercontent.com/54127809/63069352-897cf700-bee4-11e9-88ce-10ab297ebd72.png)

**Debug logs**

**Environment (please complete the following information)**
Windows, using Chrome latest version

**Additional context**
Can't find anyone else complaining about this issue here.

**Comment by alexesprit** [comment]
Can't reproduce.

[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by inverse** [comment]
@franconia2022 any sample URLs?

**Comment by Williwood** [comment]
I get the exact same error. But I use Vivaldi as browser. I hope the log-file will help.

[Bandcamp.txt](https://github.com/web-scrobbler/web-scrobbler/files/3509150/Bandcamp.txt)

**Comment by alexesprit** [comment]
@Williwood you have an authentication error, have you tried to reauthenticate?
```xml
core/background/util/util.js:160 Last.fm: track.updatenowplaying response:
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="failed">
  <error code="9">Invalid session key - Please re-authenticate</error>
</lfm>
```
