### ISSUE TITLE
Complete public list of supported websites

### ISSUE THREAD

**Issue by hans-juergen** [web-scrobbler/web-scrobbler#2045]
**Is your feature request related to a problem? Please describe.**
Somehow the public list of supported streaming sites got lost on all related support pages, although it is mentioned that it would be available e.g. on the Web Scrobbler page which it is not. You can only check the supported streaming sites in the settings of an already installed extension, so interested people don't realise how many sites are supported. Also people googling for scrobbling support of their favorite streaming site will not find your extension anymore.

**Describe the solution you'd like**
At least mention that you can only check all supported sites in the settings, and/or post a complete list again on your support pages.

**Comment by inverse** [comment]
What support page are you referring too that it mentions such things?

**Comment by alexesprit** [comment]
It's mentioned on Chrome Web Store page: https://chrome.google.com/webstore/detail/web-scrobbler/hhinaapppaileiechjoiifaancjggfjm, although no URL is provided.

I think we can add the list on the new website, but it's should be gathered from latest release, not master branch.

**Comment by hans-juergen** [comment]
Right, it says on the Chrome extension page:
> You can view a list of supported websites at this page: https://web-scrobbler.github.io/.

And on that page it only says:
> A lot of websites supported

Earlier versions of the Chrome Web Store page had this list, but probably it was too long for the details there.

**Comment by inverse** [comment]
Could be part of the deployment process where we export the list and commit into the other repo

**Comment by MXMLLN** [comment]
I had no idea the extension even had options. Could not find the list of supported sites until I came to the Support page. From my professional UX viewpoint, this is a fundamental requirement for the extension: To state where it works.

> You can only check the supported streaming sites in the settings of an already installed extension, so interested people don't realise how many sites are supported.

**Comment by alexesprit** [comment]
> Could be part of the deployment process where we export the list and commit into the other repo

I'm not sure if there's a simple way to commit files to another repository, so I decided to save a list of connectors in this one.

**Comment by hans-juergen** [comment]
Thanks, maybe linking to each of the listed sites is possible, too? That should also improve the Google ranking of https://web-scrobbler.github.io/ ;)

**Comment by alexesprit** [comment]
It's possible, but it requires a lot of work to add URLs and maintain the list.
