### ISSUE TITLE
one track scrobles MANY times from Google Play Music

### ISSUE THREAD

**Issue by RomaKoks** [web-scrobbler/web-scrobbler#2046]
**Screenshots**
![2019-09-05_213239](https://user-images.githubusercontent.com/8873242/64371168-9ba40e00-d028-11e9-8f27-704fe1a9ab57.png)
![2019-09-05_220133](https://user-images.githubusercontent.com/8873242/64371276-dc038c00-d028-11e9-88b7-678a3c2b8ce2.png)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.
[debug.log](https://github.com/web-scrobbler/web-scrobbler/files/3580832/debug.log)

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: v2.20.0

**Comment by alexesprit** [comment]
Probably, it's the same as #1588.

If it happens when the browser is minimized, or the tab with GPM is not active, this is a known issue.

**Comment by alexesprit** [comment]
@RomaKoks also I see no duplicated scrobbles in the logs.

**Comment by RomaKoks** [comment]
@alexesprit but they are on last fm. Browser was not minimized. I've noticed that if notifications about playing track is turned on - track scrobles ~ every 2 seconds, if turned off - 2 times per track.

**Comment by alexesprit** [comment]
> but they are on last fm

I see.

We cannot understand details, if we have no info in the logs.

I use GPM pretty often, and I cannot reproduce the issue.

**Comment by RomaKoks** [comment]
@alexesprit second screenshot is in log. You can find track "Drinking From The Bottle (feat. Tinie Tempah)" by search. And on screenshot you can mention that it is scrobled more than 10 times.

**Comment by alexesprit** [comment]
@RomaKoks this track is scrobbled once according the logs (one time per each registered scrobbler).

**Comment by alexesprit** [comment]
> I've noticed that if notifications about playing track is turned on - track scrobles ~ every 2 seconds, if turned off - 2 times per track.

Could you record a screencast where you're reproducing the issue?

**Comment by RomaKoks** [comment]
sorry, I forget to delete previous extension (https://chrome.google.com/webstore/detail/google-play-lastfm-scrobb/llpepekkleeoeiloijhcafgpjdnhhcbl?hl=ru) from this browser (which actialy causes so many scrobles). Thats why every track was scrobled at least two times.
