### ISSUE TITLE
Please add support for sectorradio.ru

### ISSUE THREAD

**Issue by totalkek** [web-scrobbler/web-scrobbler#2050]
Sector Radio is a Russian internet radio station currently with 5 channels broadcasting in 3 different quality streams – 56 & 160 kbps Ogg Vorbis and CD Quality lossless FLAC. The lossless FLAC streams can be accessed either directly from the web player or using the listening links in a media player of your choice (foobar, VLC, Roon etc).

**Comment by inverse** [comment]
Will be in the next release!
