### ISSUE TITLE
Youtube videos aren't scrobbled

### ISSUE THREAD

**Issue by Akimore** [web-scrobbler/web-scrobbler#2053]
I was listening to music through Youtube as always but then all of a sudden, it stopped scrobbling. Whenever I put a video, it just says there's been an error. How can I fix this?

**Comment by egoforth** [comment]
Same situation here. It was working 3 hours ago.

**Comment by Inseut** [comment]
I'm having this problem too, but it's only with Last.fm. My scrobbles worked in Listenbrainz and Libre.fm

**Comment by Akimore** [comment]
It's working now
