### ISSUE TITLE
Scrobbling dead again (external bug in last.fm API)

### ISSUE THREAD

**Issue by IRainman** [web-scrobbler/web-scrobbler#2054]
Today last.fm API dead again. This is [issue](https://getsatisfaction.com/lastfm/topics/scrobbling-is-dead-again) on official tracker.

**Comment by alexesprit** [comment]
If it's Last.fm's issue, why do you submit the one here?

**Comment by IRainman** [comment]
I'm sorry for that. That's my fault.
