### ISSUE TITLE
No more scrobbling for Last.fm

### ISSUE THREAD

**Issue by heliobalione** [web-scrobbler/web-scrobbler#2055]
**Describe the bug**
Scrobbling not working from Youtube to Last.fm. When music starts playing, a message saying that the song could not be scrobbled appears. It suggests to reauthenticate but that is not working. I disconnected my Last.fm account and cannot sign back in.

**How to reproduce**
1. Play any song on Youtube.
2. Click on the Last.fm icon on the top right corner.
3. See error

**Expected behavior**
Usually a little box with artist, song and album title would appear instead of the message. Shortly the song would appear on my Last.fm page.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Mozilla Firefox
-   Extension version: 2.22.2

**Comment by playhell** [comment]
+1 spotify

**Comment by lukasgures** [comment]
The same for me. Doesn't recognize any song. I tried many.
Windows, Chrome, Youtube for LastFM

**Comment by RogellParadox** [comment]
Same happening. I actually went further and reinstalled the extension. Then, in the login screen, the Last.fm option won't work at all.

OS: Windows 10
Browser: Google Chrome
Extension version: 2.22.1

**Comment by alexesprit** [comment]
https://getsatisfaction.com/lastfm/topics/scrobbling-is-dead-again

**Comment by RogellParadox** [comment]
It's working like a charm again.
