### ISSUE TITLE
Scrobbling from official "Topic" YouTube artist profiles

### ISSUE THREAD

**Issue by hans-juergen** [web-scrobbler/web-scrobbler#2056]
**Describe the bug**
YouTube has automatically created official "Topic" channels for many artists where the artist may not be mentioned in the individual video titles, so Web Scrobbler does not recognise the artist and album, although both exist on Last.fm. The term " - Topic" is always used in the name of the artist profile though, so it could be used as a search filter.

**How to reproduce**
1. Go e.g. to 'Ian Cussick – Topic' https://www.youtube.com/channel/UCZ_EF_scJsOgOhKJk6v9cKw
2. Click on any of the videos with 'Ian Cussick - Topic' in the title
3. See the grey Web Scrobbler icon and click on it - no info except the title of the song 

**Expected behavior**
Web Scrobbler should use the " - Topic" indicator to fill in the artist and album title automatically.

**Environment (please complete the following information)**
-   OS: Windows 10 version 1903
-   Browser: Opera 63.0.3368.88
-   Extension version: 2.22.1

**Comment by alexesprit** [comment]
That's bad. The connector is supposed to work exactly as you described.

**Comment by alexesprit** [comment]
I'll publish a patch update in a few hours.

**Comment by hans-juergen** [comment]
Great, thank you!

**Comment by hans-juergen** [comment]
I just tested it with version 2.22.3, and it is better than before, but still not fixed. The track title is automatically filled in, and the artist name has " - Topic" still added. So Last.fm recognises it, and the track gets scrobbled (green icon, not greyed out), but creates a wrong database entry. "- Topic" should be used to trigger the search, but must be deleted from the actual scrobble then. Probably it will also fill in the correct album as well.

Tested with the Topic channel for Guy Forsyth and his album Steak: https://www.youtube.com/playlist?list=OLAK5uy_la5tx0VM88aXjKhDv1pSCp9TYcMYUuzvc

**Comment by alexesprit** [comment]
@hans-juergen What language have you selected on YouTube? I have English language selected, and "Topic" suffix is not applied:
![image](https://user-images.githubusercontent.com/1119267/65165272-20d6ec00-da47-11e9-88c5-0268716acf8b.png)

This feature works correctly if language is English only.

**Comment by hans-juergen** [comment]
You're right, I'm using German, and actually it says " -Thema" in my browser, sorry.

**Comment by alexesprit** [comment]
Thanks for the info!

I'll update the code to support "Thema" label along with "Topic" one. If you want, you can submit a new issue as a reminder for me.

Currently, the extension searches for "Topic" string only, and does not support any other strings in different languages. YouTube has a lot of languages supported, so it's not an easy task to fix the issue for ALL languages (I'll fix it for German and few popular ones).

In future, as an alternative solution, I want to add a feature to parse the video description. AFAIK every "topic" video has an autogenerated description, which has a common format for different videos, and the most important thing it's language-independent. This feature requires a lot of testing, so I won't publish it in next updates.

**Comment by hans-juergen** [comment]
Right, in the video description it always says "Auto-generated by YouTube." in English as the last line, although I'm currently using German on YouTube.

**Comment by kakolykia** [comment]
I have the same problem. It is really disturbing ((

**Comment by kakolykia** [comment]
BTW, i use Russian language

**Comment by alexesprit** [comment]
Sorry, I completely forgot I was assigned to the issue.

It should be fixed now for EN, RU, DE and some other languages.

Note that I used different approach to cut "Topic" suffix, so let me know if you find any regressions.

**Comment by hans-juergen** [comment]
Thanks Alexey, I just checked with two albums by Forq, and it works fine with version 2.23.3 in Opera with German language setting. :-)

**Comment by alexesprit** [comment]
@kakolykia could you post an URL to this video?

**Comment by kakolykia** [comment]
> @kakolykia could you post an URL to this video?

https://www.youtube.com/watch?v=g1TM_o5lslY

Here you are

**Comment by alexesprit** [comment]
@kakolykia thanks! I submitted a new issue (for history).

I've fixed the issue, and will publish a patch update soon.

**Comment by hans-juergen** [comment]
Seems to be broken again in version 2.31.0, at least when using the German version of YouTube, e.g. for this album:

https://www.youtube.com/playlist?list=OLAK5uy_m_IsNiaA0liY43wylqjm-FOtzfFPTmKzM

The artist field reads "Poco - Thema", and album and album artist are empty then.

**Comment by alexesprit** [comment]
There's no "Topic" support, but the extension should get the track info from the video description. I'll check this one.

**Comment by alexesprit** [comment]
@hans-juergen the videos from that playlist are detected by the extension on German version, as well as on English version.

Could you copy the video description?

**Comment by hans-juergen** [comment]
That's strange, maybe it works now, because I edited while scrobbling? Before I did that with all 9 songs from the album, they all had Poco - Thema as the artist. My screenshot looks the same, as I had saved my edits:

![Web Scrobbler automatic parsing of Poco Legend](https://user-images.githubusercontent.com/4970867/81834293-0a832080-9541-11ea-8124-ed7790908a24.png)

I will pay attention if this happens again and make a screenshot then before editing.

**Comment by alexesprit** [comment]
> I will pay attention if this happens again and make a screenshot then before editing.

If you find a way how to reproduce it, please let me know. You can open a new issue, if you want.

> By the way, the character between the title and the artist in the description is a dot, not a hyphen, but I don't know if that would make a difference.

Yes, that's expected.

**Comment by misaka00251** [comment]
I'm still having this issue..."Topic" in Chinese is "主题".

![image](https://github.com/web-scrobbler/web-scrobbler/assets/3908746/38c1d0b0-876e-4628-930f-e7a62e6cb801)
