### ISSUE TITLE
Please add poolside.fm 🌴

### ISSUE THREAD

**Issue by thomasbnt** [web-scrobbler/web-scrobbler#2057]
## Information about website

URL : https://poolside.fm/ 
He's uses Soundcloud API for requests musics. 

![poolsidefm](https://user-images.githubusercontent.com/14293805/64993791-39c08f80-d8d7-11e9-8848-0a34c8c7a59a.png)

**Comment by jamescdcarter** [comment]
Cool website!

I've just taken a look and it seems pretty easy to get this working. 

I'll start this sometime next week.

**Comment by inverse** [comment]
@jamescdcarter did you make any progress?

**Comment by alexesprit** [comment]
#2099
