### ISSUE TITLE
kompakt.fm support

### ISSUE THREAD

**Issue by lilzetha** [web-scrobbler/web-scrobbler#2058]
Hi there, really love the services you provide. Was wondering if support for the record label Kompakt's website could be incorporated. They allow streaming of many of their releases at kompakt.fm

**Comment by inverse** [comment]
Once you purchase can you listen to the full thing or is it only samples?

**Comment by lilzetha** [comment]
Hmm I could have sworn I was able to listen to their older (pre-2000) releases all the way through just a few weeks ago. But you're right, it's been just playing samples now. Either they changed it or I'm losing my mind. At any rate I guess it wouldn't be that helpful to be able to scrobble that! Sorry!
