### ISSUE TITLE
Cannot scrobble from youtube

### ISSUE THREAD

**Issue by amdaza** [web-scrobbler/web-scrobbler#2059]
**Description**
Scrobble from youtube (Mozilla Firefox) is not working

**Steps**
1. Go to youtube song video
2. See error: "Error del servicio
Parece que algo salió mal mientras se hacía scrobbling de la canción. Abra la página de opciones e intente volver a autenticarse con los servicios. Si la reautenticación no ayuda, y aún ve este mensaje, cree un nuevo problema en la página del proyecto en GitHub."

**Screenshots**
![image](https://user-images.githubusercontent.com/7770701/65224576-badc7a00-dac3-11e9-8cbd-511683ffeff6.png)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Mozilla firefox
-   Extension version: 2.22.3

**Additional context**

**Comment by icyDora** [comment]
I have the same issue (in Chrome), not only with youtube but also with other sites too. I tried logging out of last.fm and when I try to log in again, the extension throws authentication error without even asking for credentials.

**Comment by mortiis7** [comment]
i have the same problem....

**Comment by affinage** [comment]
i have the same problem with Firefox on soundcloud.com 
FF 68.0.2 (64-bit)
web scrobbler: 2.22.3

attaching logs. 

[scrobbler.txt](https://github.com/web-scrobbler/web-scrobbler/files/3630248/scrobbler.txt)

**Comment by erdnaxeli** [comment]
It seems to be fixed. I bet it was a Last.fm issue.

**Comment by Fulgryn** [comment]
> 
> 
> It seems to be fixed. I bet it was a Last.fm issue.

Yep, other stuff like openscrobbler were not working either (and even spotify)

**Comment by amdaza** [comment]
Seems fixed. Closing issue, thanks!
