### ISSUE TITLE
Web Scrobbler suddenly stopped working on supported sites

### ISSUE THREAD

**Issue by Mzusehir9** [web-scrobbler/web-scrobbler#2060]
Since the newest update, I've been finding Web Scrobbler isn't working on supported sites such as Youtube, Bandcamp and Soundcloud. I first noticed it when I was getting a general error where the plugin icon (on Firefox) turned to yellow when I tried scrobbling something on Youtube, so I reinstalled. Then I'd get a "this website is not supported" error with the icon remaining grey, and I couldn't login with my Last.fm account through the plugin. Same error on Bandcamp and Soundcloud.

This is the second time I've found the plugin becoming unusable following an update.

**Comment by alexesprit** [comment]
Yellow icon almost always means it's on Last.fm side. Probably, it's related to #2059.

**Comment by inverse** [comment]
Could def do with some #211

**Comment by Mzusehir9** [comment]
> 
> 
> Yellow icon almost always means it's on Last.fm side. Probably, it's related to #2059.

As I said, it was only yellow before I reinstalled it. Now it's grey on Youtube, Bandcamp and Soundcloud.

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by Mzusehir9** [comment]
There is no debug option, just a "Manifest URL." This is the console for a Youtube video where Web Scrobbler isn't working:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).

MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. base.js:1094:359
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).

url=https%3A%2F%2Fr4---sn-8xgp1vo-cvne.googlevideo.com%2Fvideoplayback%3Fexpire%3D1569043031%26ei%3D912FXbW6KpiFhgao2oLoAw%26ip%3D96.230.215.73%26id%3Do-ABWKFiW5Ch-Zq5y-z84wybv-KMUf3e8vMDP7H7HuwzMH%26itag%3D18%26source%3Dyoutube%26requiressl%3Dyes%26mm%3D31%252C29%26mn%3Dsn-8xgp1vo-cvne%252Csn-ab5szn7s%26ms%3Dau%252Crdu%26mv%3Dm%26mvi%3D3%26pl%3D16%26initcwndbps%3D1856250%26mime%3Dvideo%252Fmp4%26gir%3Dyes%26clen%3D21595182%26ratebypass%3Dyes%26dur%3D237.934%26lmt%3D1541208818963862%26mt%3D1569021340%26fvip%3D4%26c%3DWEB%26txp%3D5531432%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cmime%252Cgir%252Cclen%252Cratebypass%252Cdur%252Clmt%26lsparams%3Dmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Cinitcwndbps%26lsig%3DAHylml4wRQIgGO_yyfqrEjPsI7iBQmpMTUEwkNEiuNBdDS39rAR0zEgCIQC8yA3omV4ZUdIqphVYUQGuuQyuKWvv98XbMD5589TXBA%253D%253D&s=XFNeH88Nu3QBEB9a8WtTJUHGm8H29vhnDnhtVzMSA7MFIC4Vom2Ika0l7_9dhoWb8CeF6Jrg1KnCUuHY7dEix_EtagIARww2IxgLAgLA&sp=sig watch:1:850
https://r4---sn-8xgp1vo-cvne.googlevideo.com/videoplayback?expire=1569043031&ei=912FXbW6KpiFhgao2oLoAw&ip=96.230.215.73&id=o-ABWKFiW5Ch-Zq5y-z84wybv-KMUf3e8vMDP7H7HuwzMH&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-8xgp1vo-cvne%2Csn-ab5szn7s&ms=au%2Crdu&mv=m&mvi=3&pl=16&initcwndbps=1856250&mime=video%2Fmp4&gir=yes&clen=21595182&ratebypass=yes&dur=237.934&lmt=1541208818963862&mt=1569021340&fvip=4&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgGO_yyfqrEjPsI7iBQmpMTUEwkNEiuNBdDS39rAR0zEgCIQC8yA3omV4ZUdIqphVYUQGuuQyuKWvv98XbMD5589TXBA%3D%3D&sig=XFNeH88Nu3QBEB9a8WtTJUHGm8H29vhnDnhtVzMSA7MFIC4Vom2Ika0l7_9dhoWb8CeF6Jrg1KnCUuHY7dEix_EtagIARww2IxgLAgLA&dec=1 youtube-video-downloader.js:641:12
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/ads?lact=-1&ytdev…l=u&rsz=%7C%7Cn%7C&dssz=37&icsg=4194303&mdo=0&mso=0&lact=929. (Reason: CORS request did not succeed).

2
Loading failed for the <script> with source “https://static.doubleclick.net/instream/ad_status.js”. watch:1:1
uncaught exception: Object

**Comment by alexesprit** [comment]
The log contains no useful information. We need logs of background script.

**Comment by alexesprit** [comment]
I doubt it becomes broken after update. Could you rollback to the previous version that worked for you and reproduce the issue on that version?

**Comment by Mzusehir9** [comment]
> 
> 
> The log contains no useful information. We need logs of background script.

As I said, there is no debug option on any add-ons under the "Debug Add-ons" menu, just "Manifest URL" instead. Why is the debug option not available?

The closest I could see was "inspect" on that page. Here's what the console for that turned up, though it has information on other plug-ins I have installed: https://pastebin.com/BhPeKYNq (this is the current version, not a rollback)

Again, I didn't experience issues like this until the update. The icon showing up as yellow isn't exactly new, but reinstalling with it being greyed out everywhere is new.

**Comment by alexesprit** [comment]
Yes, the "Inspect" button leads to debug logs. But these logs are incomplete (have no initialization data).

The basic actions to get proper logs:
 - Close and launch the browser (that's important!).
 - Reproduce the issue (in your case you should open any supported website).
 - Get debug logs and post them.

<details>
  <summary>Here's an example how logs should look like (Click to expand)</summary>
Logs

````
Webconsole context has changed
storage.Options = {
  "disableGa": false,
  "forceRecognize": false,
  "disabledConnectors": "[Array(0)]",
  "useNotifications": true,
  "useUnrecognizedSongNotifications": false
} wrapper.js:68:12
storage.ListenBrainz = {
  "sessionID": "************************************",
  "sessionName": "**********"
} wrapper.js:68:12
storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "**********"
} wrapper.js:68:12
storage.LibreFM = {
  "sessionID": "********************************",
  "sessionName": "******"
} wrapper.js:68:12
storage.Connectors = {
  "GoogleMusic": {
    "scrobblePodcasts": true
  },
  "Tidal": {
    "useShortTrackNames": false
  },
  "YouTube": {
    "scrobbleMusicOnly": false,
    "scrobbleEntertainmentOnly": false
  }
} wrapper.js:68:12
storage.Notifications = {
  "authDisplayCount": 1
} wrapper.js:68:12
storage.Core = {
  "appVersion": "2.22.3"
} wrapper.js:68:12
Bind Last.fm scrobbler scrobble-service.js:62:13
Bind Libre.fm scrobbler scrobble-service.js:62:13
Bind ListenBrainz scrobbler scrobble-service.js:62:13
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 4
Injecting vendor/jquery.min.js inject.js:56:12
Injecting vendor/browser-polyfill.min.js inject.js:56:12
Injecting core/content/util.js inject.js:56:12
Injecting core/content/reactor.js inject.js:56:12
Injecting core/content/filter.js inject.js:56:12
Injecting core/content/connector.js inject.js:56:12
Injecting connectors/google-play.js inject.js:56:12
Error: "Script 'moz-extension://abe5a2a0-f5d2-4802-8ee3-6792475581ad/connectors/google-play.js' result is non-structured-clonable data" inject.js:61:13
Injecting core/content/starter.js inject.js:56:12
Tab 9: Created controller for Google Play Music connector util.js:163:3
````
Content
</details>

**Comment by Mzusehir9** [comment]
Is this any more accurate?: https://pastebin.com/ZPW1KWQH

This was after close and launching the browser and immediately opening a tab with a Youtube video. These are also from the console, not the debugger. There's a large number of folders under debugger I can only view individually.

**Comment by alexesprit** [comment]
Yes. What Firefox version do you use?

**Comment by Mzusehir9** [comment]
69.0.1 (64-bit)

**Comment by alexesprit** [comment]
I have the same version, and I can't reproduce the issue.

**Comment by Mzusehir9** [comment]
No, I did not remove anything that I can recall. What else could I be missing?

**Comment by alexesprit** [comment]
> No, I did not remove anything that I can recall. What else am I missing?

If you asking about info regarding to the extension, I supposed to see some error output.

I see missing Last.fm/Libre.fm/ListenBrainz data in the logs, so I guessed you removed something. I posted an example of my debug output where this data is available:
```
storage.ListenBrainz = {
  "sessionID": "************************************",
  "sessionName": "**********"
} wrapper.js:68:12
...
```
It's available (but in another form) even if a user is not logged in. So, anyway, this info is supposed to be in **all logs**. That's really odd you have nothing similar in the logs.

Did you also try reinstalling the extension?

**Comment by alexesprit** [comment]
As an alternative you could rollback to one of the previous versions and tell if any of them works fine for you: https://addons.mozilla.org/ru/firefox/addon/web-scrobbler/versions/

**Comment by Mzusehir9** [comment]
Ok, I tried a few previous versions first, and I noticed I couldn't even sign in last.fm with them. When I clicked "Sign in" nothing happens, except a # is added to the end of the URL.

This persists even on the newest version when I reinstalled it. I don't recall that happening before. I did try playing something off soundcloud nonetheless. Here's what I get: https://pastebin.com/a0hCmyhW

Also, the URL for previous versions you posted is the russian version.

**Comment by Mzusehir9** [comment]
Things work fine in Chrome, and this is the first time I've used it in Chrome.

**Comment by alexesprit** [comment]
> Things work fine in Chrome, and this is the first time I've used it in Chrome.

> Ok, I tried a few previous versions first, and I noticed I couldn't even sign in last.fm with them. When I clicked "Sign in" nothing happens, except a # is added to the end of the URL.

So, it's probably something wrong with Firefox, if previous versions don't work well for you, even if they are worked before. 

I tested the extension on Firefox on Windows 10 and I have no issue. What OS do you use? Probably, it depends on platform.

> Also, the URL for previous versions you posted is in Russian.

Sorry, I just copied an URL from my browser, and didn't notice the page is on Russian language. The extension has multiple languages, though.
