### ISSUE TITLE
Not scrobble at Google Play Music site

### ISSUE THREAD

**Issue by olexandr-perepiyaka** [web-scrobbler/web-scrobbler#2068]
Does not scrobble for Google Play Music

When song is played extension recognize song, show notification, after awhile change icon to show that song is scrobbled, but on last.fm site and database this song is absent. But I also signed in my listenbrainz accont and songs missed in lastfm is listed in my listenbrainz recent list

Extension "Google Play Last.fm Scrobbler" (llpepekkleeoeiloijhcafgpjdnhhcbl) scrobbles all songs well and I have to use it to scrobble my songs from google play music. 

Using 
Web Scrobbler 2.22.4
Google Chrome 77.0.3865.90 (Official Build) (64-bit)

**Comment by alexesprit** [comment]
> But I also signed in my listenbrainz accont and songs missed in lastfm is listed in my listenbrainz recent list

This could be related to Last.fm's issues.

[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by inverse** [comment]
@elfernesto  does this happen to you?

**Comment by elfernesto** [comment]
> @elfernesto does this happen to you?

That was the behaviour before yes, but it's working fine currently. Last time it turned out to be last.fm website issue.
