### ISSUE TITLE
Some Youtube music not recognized

### ISSUE THREAD

**Issue by GodSponge** [web-scrobbler/web-scrobbler#2080]
Some songs not recognized by scrobbler.

Only one song on [this playlist](https://www.youtube.com/playlist?list=PLQcrnaKg3AIrfnCKnFk70IDVNJdGE1FKJ) is recognized by the scrobbler as a song. I get the "Play some music to get started" message on all tracks except *When the Sun Goes*. As an example, the song [Hatchet by As We Ascend (OFFICIAL AUDIO)](https://www.youtube.com/watch?v=6QP7o0BsmeI&list=PLQcrnaKg3AIrfnCKnFk70IDVNJdGE1FKJ&index=3) does not trigger the scrobbler, but the music video of the same song, by the same artist [Hatchet (OFFICIAL LIVE MUSIC VIDEO) by As We Ascend](https://www.youtube.com/watch?v=vQPz1s7rnY0) does.

The only thing I can think of is that the (OFFICIAL AUDIO) is somehow messing with the detection since the only one on that playlist that does scrobble is the one without (OFFICIAL AUDIO) in the title.

**Debug logs**
https://pastebin.com/anYQc0CD

**Environment**
-   OS: Windows 10
-   Browser: Firefox 
-   Extension version: 2.22.4

**Comment by alexesprit** [comment]
These videos aren't recongized because of how they are named. "by" can't be a valid separator between a track name and an artist name.
