### ISSUE TITLE
Soundcloud scrobbling doesn't work at all

### ISSUE THREAD

**Issue by AwesomeAwesomeAwesome** [web-scrobbler/web-scrobbler#2090]
**Describe the bug**
Soundcloud scrobbling stopped working altogether. I'm getting the red icon on all of SC tracks and the regular 'Play some music to get started. Is it already playing?' text. Debug log says there's no metadata discovered.

**Debug logs**
<details>
  <summary>Debug log</summary>
  Here is the content of debug log:

  ```
  controller.js:541 Tab 80: State from connector doesn't contain enough information about the playing track: {
  "track": null,
  "artist": null,
  "album": null,
  "uniqueID": null,
  "duration": null,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": null
}
  ```
</details>

**Environment (please complete the following information)**
-   OS: Windows 10/1903 Pro x64 build 18362.418
-   Browser: Google Chrome 77.0.3865.120 (64-bit)
-   Extension version: 2.23.0

**Comment by alexesprit** [comment]
It's the same for me. They changed some internal things.

**Comment by inverse** [comment]
:cry:

**Comment by inverse** [comment]
https://github.com/webpack/webpack/issues/6985 - Looks like they upgraded WebPack

**Comment by fatalerrrors** [comment]
I have the same issue. Hope it is fixed soon as I pretty much only use SoundCloud for my music :(

**Comment by alexesprit** [comment]
@inverse Looks like we should use DOM to get track info. I don't know how to fix the issue using internal SC things.

**Comment by alexesprit** [comment]
Fixed the connector using DOM as a track info. Will publish the patch update soon.
![image](https://user-images.githubusercontent.com/1119267/66852470-b5206a00-ef85-11e9-9ad0-e15f6fad62ed.png)

**Comment by githubsucks-usegitlab** [comment]
Thanks for working on this. Please push the patch asap. Took me about 40+ tracks to realise this wasn't working. Gotta scrobble them all manually now.

**Comment by alexesprit** [comment]
> Please push the patch asap. 

It will be published as soon as Google reviewers will approve the extension. I already did my best.
