### ISSUE TITLE
Music.youtube.com

### ISSUE THREAD

**Issue by lordton** [web-scrobbler/web-scrobbler#2095]
Hey! Thanks for an awesome plugin!
Youtube launched their music branch:
https://music.youtube.com

Could you please add it?
Thx!

**Comment by lordton** [comment]
(to clarify) youtube-music has two types of content:
1) videos (like regular youtube videos), they scrobble okay
2) auto-generated album art videos from songs library (they don't scrobble)

**Comment by alexesprit** [comment]
> videos (like regular youtube videos), they scrobble okay
> auto-generated album art videos from songs library (they don't scrobble)

I can't agree with you. Here's how regular YouTube videos are recognized:
![image](https://user-images.githubusercontent.com/1119267/67027424-33aa1280-f112-11e9-8672-557469440b51.png)

and "generated" music videos (feel the difference):
![image](https://user-images.githubusercontent.com/1119267/67027693-b03cf100-f112-11e9-9b37-9cb6ad4e2496.png)

**Comment by alexesprit** [comment]
I fixed scrobbling music videos in #2106. Now the connector works fine (at least for me).
