### ISSUE TITLE
epicmusictime.com connector request

### ISSUE THREAD

**Issue by Ydeu** [web-scrobbler/web-scrobbler#2097]
epicmusictime.com is online radio with playlist composed of epic music, trailer music and video game music. The site has only main site and embedded music player in it. This site is not really popular, but I would like to create a connector for the site as I like the genre. If you would not mind, I would be really glad if you could assign me to this issue. I am newcomer to the whole github thing and also javascript, but I will try my best. Thank you :)

URL: [epicmusictime.com](url)
Site screenshot:
![Screenshot from 2019-10-15 10-40-23](https://user-images.githubusercontent.com/52825693/66815765-24bc3800-ef39-11e9-8ccd-daf441a26e37.png)

**Comment by alexesprit** [comment]
Hi! The extension already supports scrobbling from this website:
![image](https://user-images.githubusercontent.com/1119267/66818156-91d5ca80-ef45-11e9-9c47-3c247d884c42.png)
