### ISSUE TITLE
Doesn't scrobble on soundcloud.com

### ISSUE THREAD

**Issue by ALKAxSELTZER** [web-scrobbler/web-scrobbler#2100]
The extension works fine on every website I use (Youtube, Bandcamp) but stopped working for Soundcloud a few days ago.
The scrobbler is stuck on the "play some music to get started" window while I play any track on Soundcloud.

I'm using Firefox 69.0.3 (64 bits) and Web Scrobbler 2.23.0

**Comment by alexesprit** [comment]
Have you tried to use v2.23.3? We fixed scrobbling for SoundCloud yesterday.

**Comment by ALKAxSELTZER** [comment]
> 
> 
> Have you tried to use v2.23.3? We fixed scrobbling for SoundCloud yesterday.

Thanks a lot for the quick reply, just re-installed and it works perfectly !
