### ISSUE TITLE
Can not connect to Listenbrainz in Firefox

### ISSUE THREAD

**Issue by onnyyonn** [web-scrobbler/web-scrobbler#2108]
**Description**
When I am trying to connect to Listenbrainz, I am being redirected to https://listenbrainz.org or https://listenbrainz.org/profile . But it doesn't connect Listenbrainz to the extension. This bug is similar to https://github.com/web-scrobbler/web-scrobbler/issues/1937 . However I am not using Firefox ESR. I am on Firefox 69.0.2 on Ubuntu.

**How to reproduce**
Preferences -> Accounts -> ListenBrainz -> click "Sign In"

**Environment**
-   OS: Ubuntu 19.04
-   Browser: Firefox 69.0.2
-   Extension version: 2.23.4

**Debug logs**
ListenBrainz: Use https://listenbrainz.org/profile/ util.js:163:3
Request to access cookie or storage on “<URL>” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. 14
ListenBrainz: Use https://listenbrainz.org/login/musicbrainz?next=%2Fprofile%2F util.js:163:3
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChannel.asyncOpen]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 174"  data: no] FaviconLoader.jsm:174:20
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChannel.asyncOpen]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 174"  data: no] FaviconLoader.jsm:174:20
ListenBrainz: Failed to get session util.js:163:3
ListenBrainz: Auth url: https://listenbrainz.org/login/musicbrainz?next=%2Fprofile%2F util.js:163:3
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1507
ListenBrainz: Use https://listenbrainz.org/profile/ util.js:163:3
ListenBrainz: Use https://listenbrainz.org/login/musicbrainz?next=%2Fprofile%2F util.js:163:3
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChannel.asyncOpen]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 174"  data: no] FaviconLoader.jsm:174:20
[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChannel.asyncOpen]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 174"  data: no] FaviconLoader.jsm:174:20
ListenBrainz: Failed to get session

**Comment by treeshateorcs** [comment]
it's a  bug in listenbrainz. tracking protection must be disabled for this site

**Comment by notpushkin** [comment]
A workaround is to open the extension options page and run the following snippet:

```js
browser.storage.local.set({
  "ListenBrainz": {
    "sessionName": "your username",
    "sessionID": "your user token from https://listenbrainz.org/profile/",
  },
});
```

**Comment by alexesprit** [comment]
Closed as an issue non-related to the extension (Firefox bug).
