### ISSUE TITLE
Youtube Classic on Firefox not scrobbling

### ISSUE THREAD

**Issue by treeshateorcs** [web-scrobbler/web-scrobbler#2109]
**Describe the bug**
When [this](https://addons.mozilla.org/en-US/firefox/addon/youtube-classic/) extension (it basically restores the old youtube layout. youtube on firefox is very slow without it) is enabled scrobbling does not happen,

**How to reproduce**
1. Install Youtube Classic addon
2. go to a youtube music video
4. it won't scrobble

**Screenshots**
![image](https://user-images.githubusercontent.com/44036082/67138464-314bd380-f24c-11e9-949d-134866829629.png)

**Debug logs**
https://0x0.st/z3-p.txt

**Environment (please complete the following information)**
-   OS: Arch Linux fully up to date
-   Browser: Firefox Nightly (71.0a1)
-   Extension version: 2.23.4

**Comment by alexesprit** [comment]
This is not a bug, because the extension is not supposed to work with non-standard layouts.

**Comment by treeshateorcs** [comment]
it is standard, just old

well, that's too bad

**Comment by AHTOLLlKA** [comment]
can you add support for classic? bcz many ppl using this plugin

**Comment by treeshateorcs** [comment]
seems to be working now
