### ISSUE TITLE
Lack of caching support

### ISSUE THREAD

**Issue by baudtack** [web-scrobbler/web-scrobbler#211]
It would be really cool if when last.fm is unavailable (like now for instance) if the scrobbles could be cached for later uploading.

**Comment by marsjaninzmarsa** [comment]
How about now, free to go?

**Comment by MartinL0815** [comment]
"Some" years later … how is the state?
I already got the answer, that the scrobbler is currently not able to cache.

From my point of view and my experiences with suddenly failing scrobbles (LibreFM and LastFM), I'd be glad to have failure management by caching failed scrobbles and "replay" those cached scrobbles later, retrying to get the scrobbles out.

**Comment by inverse** [comment]
This totally could be done. Sounds like the task for a web-worker. As per the definition:

> A web worker is a JavaScript that runs in the background, independently of other scripts, without affecting the performance of the page.

Not sure of browser compatibility. but could be a progressive thing if the vendor supports.

**Comment by OwnageIsMagic** [comment]
@inverse no need in second background process
Just cache on entry and delete from cache on success

**Comment by inverse** [comment]
So you would try to submit and on fail cache? But then how would you retry? What would be the mechanism for that?

**Comment by OwnageIsMagic** [comment]
notification on start up if cache is not empty and submit on click
or manual one by one scrobble of failed tracks from settings menu
Not a problem

**Comment by inverse** [comment]
@alexesprit did you start on this one?

**Comment by alexesprit** [comment]
@inverse no, have no free time. :(

**Comment by alexesprit** [comment]
Preview: https://github.com/web-scrobbler/web-scrobbler/issues/291#issuecomment-643820390.

**Comment by d4goo** [comment]
Very cool.  Good luck.  Looking fwd to v3!
