### ISSUE TITLE
Double scrobbling on Google Play Music site

### ISSUE THREAD

**Issue by olexandr-perepiyaka** [web-scrobbler/web-scrobbler#2122]
**Describe the bug**
When one song is short (with duration is less than 2 minutes) is played than next one (duratoin more than 3 minutes) is scrobbled two times and shorter song does not scroll at all.
Long longs (with duration is less than 6 minutes) also scrobbles 2 times.

**How to reproduce**
Open google play music site and play album where there short songs and not short songs is played one after another. (play.google.com/music/listen?u=0#/album/Bfs6yc77mwcpvmjv7dpkpjxxisa/)

**Environment (please complete the following information)**
-   OS: (e.g. Windows)
-   Browser: (e.g. Chrome, 77.0.3865.120)
-   Extension version: (e.g. v2.23.4)

**Additional context**
Why the official lastfm android app scrobble ALL short songs? Every one of them? They ignore they own rule - not scrobble song with duration less than 2 minutes. Why can you ignore that rule?

**Debug log**
https://pastebin.com/raw/mzSBkr8E

**Comment by alexesprit** [comment]
Please use either pastebin or spoiler to wrap your debug logs.

This is related to #1588. GPM UI isn't updated when minimized.

**Comment by alexesprit** [comment]
Like I said in that issue, the best solution is to remove duration getter from the connector. So, in this case, the extension will get track duration from Last.fm, but not from the GPM website (which returns wrong duration if it's inactive). It won't fix scrobbling for all tracks, but it will for most of all cases.

**Comment by olexandr-perepiyaka** [comment]
Row Log
https://pastebin.com/raw/mzSBkr8E

**Comment by alexesprit** [comment]
Thanks, I updated your comment.

> Why the official lastfm android app scrobble ALL short songs? Every one of them? They ignore they own rule - not scrobble song with duration less than 2 minutes. Why can you ignore that rule?

Where did you find this rule? AFAIK the minimal duration is 30 seconds. Could you post a URL to documentation where is said the minimal duration is 120 seconds (2 minutes as you said)?

**Comment by alexesprit** [comment]
Also, the issue should be fixed in https://github.com/alexesprit/web-scrobbler/commits/feature/gpm-inject this branch. This one is outdated a little, though.

You can install the extension from that branch and test it, if you are insterested. Unfortunately, this is not cross-browser solution. :(

**Comment by alexesprit** [comment]
@olexandr-perepiyaka  Could you install the extension from this zip and tell if it works better for you?

https://github.com/alexesprit/web-scrobbler/archive/feature/gpm-no-duration.zip

**Comment by olexandr-perepiyaka** [comment]
Installed extension from zip and listened for two songs. Both request for song duration to lastfm resolve wrong songs durations (0 seconds), both scrobbled after 30 second of playing. Removed debugged version of extension and use actual version from web store.

I don't think it is the way to get track duration from Last.fm. Google play music page has all information about playback and about track duration (IMHO). When song is playing page title contain song author and song title. When playback paused  - web page title changes accordingly. 

I think that when songs played one after another then your scrobbling code have to scrobbble song if page title changed even if durarion of song not yet reached, because page title is a signal - "song is over - time to scrobble now". After this moment the other song playback is started - new timer was set (IMHO).

**Comment by alexesprit** [comment]
> I think that when songs played one after another then your scrobbling code have to scrobbble song if page title changed even if durarion of song not yet reached, because page title is a signal - "song is over - time to scrobble now".

So, do you propose to scrobble songs on every next song switch (even after few seconds)?

Also, I don't know why you're talking about the page title; the extension relies on the song info in the player bar, which is changed **even if GPM is inactive or minimized** (i.e. the tab contains GPM is not active, or the browser is minimized).

> I don't think it is the way to get track duration from Last.fm.

I fully agree with you. That's why this solution is not published. But I don't know other (cross-browser) ways to resolve the issue.

> Google play music page has all information about playback and about track duration (IMHO).

That's not true for current time or duration. Unfortunately, there's a bug (or a feature, lol?) that does not allow UI to be updated if **GPM is minimized or inactive**. And the song duration is **required** to detect a scrobbling point (50% of song *duration* of 240 seconds) to prevent scrobbling after track change (which could be done in few seconds, e.g. you're switching tracks quite often to find a song you like). So, due to this bug, the extension cannot calculate this point properly.

**Comment by alexesprit** [comment]
I'm closing this one as we cannot fix the connector due to GPM website limitations. Unfortunately, the Chrome-only fix is a hack and it's not acceptable.
