### ISSUE TITLE
Can you have last.fm number of scrobbles also available in the 'Now Playing' notification?

### ISSUE THREAD

**Issue by GabrielCalin** [web-scrobbler/web-scrobbler#2123]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
I noticed that the extension is able to show how many times I scrobbled a track when I press the extension icon. I wish we could have that in the Now Playing notification - maybe not mandatory but as an option to be checked in the extension's settings. It could be shown next to the title (for example, in parentheses) as I now that Chrome notifications allow only a predefined format containing a limited number of lines to be shown.
For me it would be helpful, as I'm always curios how many times I listened to a track (one of the reasons I have last.fm) and as a notification the information would be accessible easier.

**Describe alternatives you've considered**
To check this by pressing the extension icon.

**Additional context**

**Comment by alexesprit** [comment]
> It could be shown next to the title (for example, in parentheses)

I think displaying in this way will look weird, plus, w/o additional info/tips it's not obvious it's a number of scrobbles.

**Comment by GabrielCalin** [comment]
I actually have a script which only shows the notification, I added a print screen below. I don't believe it looks ugly. To be honest I hoped I can stop using it and use web scrobbler both for scrobbling and the notifications, of course, if it's considered a useful feature.

![image](https://user-images.githubusercontent.com/2115076/67406227-78282900-f5be-11e9-8b7f-d56b428e00df.png)

**Comment by alexesprit** [comment]
> I don't believe it looks ugly.

As I understand, in your example you use "Artist - Track" as a title, and "Play count" string as a message. It does not look ugly, but the "Artist - Track" string will be cut it an artist name and/or a track title is long enough:
![image](https://user-images.githubusercontent.com/1119267/67618347-e48d6d00-f7f6-11e9-81ac-39d44e62e7df.png)

My suggestion is to use a track title as a notification title, and an artist name and the play count label joined by a LF character as a notification message:
![image](https://user-images.githubusercontent.com/1119267/67618398-b3fa0300-f7f7-11e9-8e3e-671457331458.png)

Optionally we could add an album name in the notification message to match the info popup format and resolve #1628:
```
Track title
Artist name
Album name (if available)
Play count (if greater than zero)
```
![image](https://user-images.githubusercontent.com/1119267/67618452-83669900-f7f8-11e9-847d-a41eb12907eb.png)

What do you think?

**Comment by GabrielCalin** [comment]
Hi and thanks for the detailed research!

Considering #1628, I would say the last option is the best. 
Personally, I also like the second option, but it doesn't contain the album name.
Or maybe the fields could be configurable, but I don't think the amount of work needed would justify the feature. 
So, I would go with the last option.

Best regards!

**Comment by inverse** [comment]
How would this work with multiple scrobblers registered? 

I'm starting to think our options page will need an overall to handle all these changes.

**Comment by alexesprit** [comment]
> How would this work with multiple scrobblers registered?

It will behave like the user play count in the info popup window.

I'll probably make the feature toggleable, but I'm not sure if it makes sense. I used the extension with this feature about 2 days, and changes look acceptable for me (first I was against this feature).
