### ISSUE TITLE
Scrobbling from Indie Vision Music (and other Bandcamp-based websites)

### ISSUE THREAD

**Issue by schw1804** [web-scrobbler/web-scrobbler#2125]
https://music.indievisionmusic.com/ is pretty clearly based on Bandcamp (it even has the same icon in the browser tab), from which tracks can be scrobbled. Is it possible/simple to enable scrobbling from all websites using the same template?

**Comment by alexesprit** [comment]
It's possible by using custom URL patterns:
![image](https://user-images.githubusercontent.com/1119267/67300049-13090080-f4f6-11e9-9830-a714edf80e4b.png)

For this website the pattern is `*://music.indievisionmusic.com/*`.

Sorry for RU language.

**Comment by schw1804** [comment]
Aha, perfect. Thanks. Apparently I forgot to RTFM.
