### ISSUE TITLE
Add support for Global Player

### ISSUE THREAD

**Issue by pixiekat** [web-scrobbler/web-scrobbler#2126]
**Describe the bug**
I listen to Heart in Chrome and I checked off "RadioPlayer" in the options (as detailed here #1213) but when listening the icon says the website is not supported.

**How to reproduce**
1. Go to https://www.heart.co.uk
2. Click the play icon
3. Go to https://www.heart.co.uk/localise/
4. Pick a station (My current is https://www.heart.co.uk/edinburgh/)
5. Click the play icon again.
6. Redirected to globalplayer.com (https://www.globalplayer.com/live/heart/edinburgh/)
7. Press play.
8. Icon will say website is not supported.

**Expected behavior**
Song should scrobble.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.23.4

**Comment by alexesprit** [comment]
Technically, it's not a bug, but a request, because `globalplayer.com` is a different website.
