### ISSUE TITLE
Support for audiomack

### ISSUE THREAD

**Issue by MrFojo** [web-scrobbler/web-scrobbler#2129]
While listening to music on [audiomack](https://audiomack.com), the web scrobbler icon in chrome browser shows 'This website is not supported' message.

Music on the [audiomack website](https://audiomack.com) can be accessed without registering an account.

**Comment by JanStevcik** [comment]
.

**Comment by qualitymanifest** [comment]
I'd like to give this a try. If it works out I'll submit a PR in a bit

**Comment by alexesprit** [comment]
Closed in #2131.
