### ISSUE TITLE
Webscrobbler creates wrong info flag in Vivaldi browser

### ISSUE THREAD

**Issue by stardepp** [web-scrobbler/web-scrobbler#2139]
Yesterday I installed the latest version of Webscrobbler in Vivaldi for Windows 10. The notification flag of webscrobbler is simply grayed out and prevents the original Windows notification. Please fix this bug.

Details can be read here in PDF in English in Google Drive:

https://drive.google.com/file/d/1bbn-eptcXT-85OryvzMW_7C-gXpvZwnH/view?usp=sharing

**Comment by alexesprit** [comment]
@stardepp as I said before, extensions cannot set notifications position.

I found out it happens because you have the taskbar is located at the top of screen.
