### ISSUE TITLE
Scrobbling from official "Topic" YouTube artist profiles (STILL DOESN'T WORK PROPERLY)

### ISSUE THREAD

**Issue by kakolykia** [web-scrobbler/web-scrobbler#2146]
**Describe the bug**
YouTube has automatically created official "Topic" channels for many artists where the artist may not be mentioned in the individual video titles, so Web Scrobbler does not recognise the artist and album, although both exist on Last.fm. It got better from the previous version but still **scrobbler doesn't work well.**

**How to reproduce**
1. Go to 'official **Iron Maiden** channel'
2. Click on 'any track from any album. for instance: https://www.youtube.com/watch?v=ClUB7_8xjEw&list=OLAK5uy_lf_LhJoD5mfEGNSRjZ8Je2oN8aU3AB4EA&index=3&t=0s'
3. See empty album box in scrobbler plugin window.

**Expected behavior**
Web Scrobbler should use the track's information to fill in the artist and album title automatically.

**Environment**
-   OS: Windows 10 1803 64-bit Pro
-   Browser: Vivaldi 2.9.1705.34
-   Extension version: 2.24.0

**Additional context**
The weird thing - it seems that for scrobbler all the tracks now are kinda separated to 2 categories: ones that are applicable for scrobbling and those which are not.
For example: 
![Снимок](https://user-images.githubusercontent.com/55627403/68085936-6e70b200-fe57-11e9-8dcc-3dcfab02beb7.PNG)
![Снимок2](https://user-images.githubusercontent.com/55627403/68085937-6f094880-fe57-11e9-8d56-e059934be4ae.PNG)
All the tracks from official Iron Maiden topic scrobbles like that - "Track name" is ok, "Artist's name" is ok, "Album name" is empty. (btw, in the previous version of scrobbler, "Album name" box was filled with some trash from the comment section for some reason. So, it got better)
On the other hand, the tracks from oficial Rainbow topic - every box is ok.
And i never modified the information manually.

I'm not a programmer, so i couldn't tell what's the key difference between the information attached to annotations of those videos. I hope, you'll do.

**Comment by alexesprit** [comment]
> See empty album box in scrobbler plugin window.

I see both artist name and track title are filled (they are filled on your screenshot too). 

> "Album name" is empty. (btw, in the previous version of scrobbler, "Album name" box was filled with some trash from the comment section for some reason. So, it got better)

Does it means "STILL DOESN'T WORK PROPERLY"? If so, it will be fixed for autogenerated videos.

**Comment by alexesprit** [comment]
I really don't understand why it "STILL DOESN'T WORK PROPERLY":
![image](https://user-images.githubusercontent.com/1119267/68086039-81d04d00-fe58-11e9-96bd-40ede71c1461.png)

Please, define what is "PROPERLY".

**Comment by alexesprit** [comment]
I'm closing this one, as it's similar to #1896.

**Comment by kakolykia** [comment]
> I see both artist name and track title are filled (they are filled on your screenshot too).

Well, as i said, "album name" box is empty. On screenshot it is written "album" in russian language.


> Does it means "STILL DOESN'T WORK PROPERLY"? If so, it will be fixed for autogenerated videos.

Of course it means. Because that problem applicable not only to Iron Maiden channel but for a great number of other music videos.

**Comment by kakolykia** [comment]
Так ты русский? Красава, мужик.
Такая хрень почти во всех видео с ютуба, а не только с Iron Maiden

**Comment by alexesprit** [comment]
> Well, as i said, "album name" box is empty. On screenshot it is written "album" in russian language.

Sorry, I misread your comment and didn't understand the issue.

> Так ты русский? Красава, мужик.
> Такая хрень почти во всех видео с ютуба, а не только с Iron Maiden

Спасибо!

Я это исправил уже для всех "autogenerated" роликов (т.е. тех, что в конце описании содержат "Auto-generated by YouTube", и в них есть информация об альбоме), но пока не публиковал изменения. В следующей версии будет как надо (для подавляющего большинства видео, по-крайней мере).

P.S. На будущее лучше писать только на английском, т.к. здесь много англоязычных людей. :)

**Comment by kakolykia** [comment]
> P.S. На будущее лучше писать только на английском, т.к. здесь много англоязычных людей. :)

Okey, spasibo! ;)
