### ISSUE TITLE
doesn't scrobble Vulfpeck, probably because //// in song name

### ISSUE THREAD

**Issue by HoxVox** [web-scrobbler/web-scrobbler#2147]
Doesn't scrobble songs by Vulfpeck

1. Go to 'https://www.youtube.com/watch?v=AWBUnr0F3Zo'
2. play song and see it doesn't scrobble

**Comment by alexesprit** [comment]
It's because the video in the "People & Blogs" category. It will be scrobbled if you turn off the both options in the "YouTube" section.
![image](https://user-images.githubusercontent.com/1119267/68090992-8f52fa80-fe8b-11e9-8f68-549bac4947ee.png)

**Comment by HoxVox** [comment]
Thank you very much, sorry for my wrong report

Il giorno dom 3 nov 2019 alle ore 20:45 Alexey <notifications@github.com>
ha scritto:
