### ISSUE TITLE
Atomic Music Space scrobbling

### ISSUE THREAD

**Issue by Vyktory** [web-scrobbler/web-scrobbler#2152]
**Is your feature request related to a problem? Please describe.**
A new streaming service recently launched in Australia named the Atomic Music Space. There is no web scrobbler for it. I'd like this one to be compatible.

**Additional context**
https://stream.atomicmusic.space/ is the website's URL. It's small but the people behind it have a network of radio stations in regional Australia where it will be the focus of a radio countdown and A&R scouting.

**Comment by clasick** [comment]
Added support for this through PR as mentioned above.
