### ISSUE TITLE
SoundCloud only showing "Currently scrobbling", not saving history

### ISSUE THREAD

**Issue by pgl** [web-scrobbler/web-scrobbler#2153]
**Bug description**
SoundCloud scrobbles on Last.fm don't "take" - tracks show as "Scrobbling now" but they disappear from history.

**How to reproduce**
1. Go to SoundCloud
2. Listen to a track
3. View Last.fm profile while listening - you will see "Scrobbling now"
4. Wait for track to finish and the next track to start playing
5. View Last.fm profile again, the previous track will no longer display

**Expected behavior**
Previous tracks should stay in listening history.

**Screenshots**
While listening:

![image](https://user-images.githubusercontent.com/1181139/68747505-f5adea80-05fa-11ea-9b7b-ba9ead1bee1d.png)

After track has ended and new track starts:

![image](https://user-images.githubusercontent.com/1181139/68747625-37d72c00-05fb-11ea-847a-c68b971ee272.png)

**NB:** the previous track was scrobbled (successfully) from YouTube.

**Debug logs**

https://pastebin.com/JjFaAzQ2

<details>

controller.js:541 Tab 1796: New song detected: {
  "track": "Ghost",
  "artist": "Confetti",
  "album": null,
  "albumArtist": null,
  "uniqueID": null,
  "duration": -169,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://i1.sndcdn.com/artworks-000607058911-pvxhb1-t200x200.jpg"
}
pipeline.js:46 Execute processors: 4
scrobble-service.js:90 Send "get info" request: 1
base.js:239 Last.fm: track.getinfo response:
<?xml version="1.0" encoding="UTF-8" ?>
<lfm status="ok"><track><name>Ghost</name>
<url>https://www.last.fm/music/Confetti/_/Ghost</url>
<duration>169000</duration>
<streamable fulltrack="0">0</streamable>
<listeners>848</listeners>
<playcount>3466</playcount>
<artist><name>Confetti</name>
<mbid>866e50dc-b6b3-4c6b-91ae-3a872765dac9</mbid>
<url>https://www.last.fm/music/Confetti</url>
</artist>
<album><artist>Confetti</artist>
<title>Ghost</title>
<url>https://www.last.fm/music/Confetti/Ghost</url>
<image size="small"></image>
<image size="medium"></image>
<image size="large"></image>
<image size="extralarge"></image>
</album>
<userplaycount>4</userplaycount><userloved>1</userloved><toptags></toptags>
</track>
</lfm>

coverartarchive.js:10 Using local/parsed artwork
controller.js:541 Tab 1796: Song finished processing: {
  "parsed": {
    "track": "Ghost",
    "artist": "Confetti",
    "album": null,
    "albumArtist": null,
    "uniqueID": null,
    "duration": -169,
    "currentTime": null,
    "isPlaying": true,
    "trackArt": "https://i1.sndcdn.com/artworks-000607058911-pvxhb1-t200x200.jpg"
  },
  "processed": {
    "track": "Ghost",
    "album": "Ghost",
    "artist": "Confetti",
    "duration": 169
  },
  "internalId": "bbd7761d70e0f72596b6215d6dc3b97e",
  "metadata": {
    "userloved": true,
    "startTimestamp": 1573635341,
    "label": "SoundCloud",
    "artistThumbUrl": "",
    "artistUrl": "https://www.last.fm/music/Confetti",
    "trackUrl": "https://www.last.fm/music/Confetti/_/Ghost",
    "albumUrl": "https://www.last.fm/music/Confetti/Ghost",
    "userPlayCount": 4
  },
  "flags": {
    "isProcessed": true,
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  }
}
controller.js:541 Tab 1796: The song is too short to scrobble
scrobble-service.js:106 Send "now playing" request: 1
base.js:239 Last.fm: track.updatenowplaying response:
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <nowplaying>
    <track corrected="0">Ghost</track>
    <artist corrected="0">Confetti</artist>
    <album corrected="0">Ghost</album>
    <albumArtist corrected="0"></albumArtist>
    <ignoredMessage code="0"></ignoredMessage>
  </nowplaying>
</lfm>

controller.js:541 Tab 1796: Song set as now playing
controller.js:541 Tab 1796: New song detected: {
  "track": "Dear God",
  "artist": "Confetti",
  "album": null,
  "albumArtist": null,
  "uniqueID": null,
  "duration": -202,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://i1.sndcdn.com/artworks-000479510757-za25si-t200x200.jpg"
}
pipeline.js:46 Execute processors: 4
scrobble-service.js:90 Send "get info" request: 1
base.js:239 Last.fm: track.getinfo response:
<?xml version="1.0" encoding="UTF-8" ?>
<lfm status="ok"><track><name>Dear God</name>
<url>https://www.last.fm/music/Confetti/_/Dear+God</url>
<duration>202000</duration>
<streamable fulltrack="0">0</streamable>
<listeners>868</listeners>
<playcount>6736</playcount>
<artist><name>Confetti</name>
<mbid>866e50dc-b6b3-4c6b-91ae-3a872765dac9</mbid>
<url>https://www.last.fm/music/Confetti</url>
</artist>
<album><artist>Confetti</artist>
<title>Dear God - Single</title>
<url>https://www.last.fm/music/Confetti/Dear+God+-+Single</url>
<image size="small"></image>
<image size="medium"></image>
<image size="large"></image>
<image size="extralarge"></image>
</album>
<userplaycount>3</userplaycount><userloved>1</userloved><toptags></toptags>
</track>
</lfm>

coverartarchive.js:10 Using local/parsed artwork
controller.js:541 Tab 1796: Song finished processing: {
  "parsed": {
    "track": "Dear God",
    "artist": "Confetti",
    "album": null,
    "albumArtist": null,
    "uniqueID": null,
    "duration": -202,
    "currentTime": null,
    "isPlaying": true,
    "trackArt": "https://i1.sndcdn.com/artworks-000479510757-za25si-t200x200.jpg"
  },
  "processed": {
    "track": "Dear God",
    "album": "Dear God - Single",
    "artist": "Confetti",
    "duration": 202
  },
  "internalId": "d6075bbbcec02437df54fbc9111e53a6",
  "metadata": {
    "userloved": true,
    "startTimestamp": 1573635510,
    "label": "SoundCloud",
    "artistThumbUrl": "",
    "artistUrl": "https://www.last.fm/music/Confetti",
    "trackUrl": "https://www.last.fm/music/Confetti/_/Dear+God",
    "albumUrl": "https://www.last.fm/music/Confetti/Dear+God+-+Single",
    "userPlayCount": 3
  },
  "flags": {
    "isProcessed": true,
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  }
}
controller.js:541 Tab 1796: The song is too short to scrobble
scrobble-service.js:106 Send "now playing" request: 1
base.js:239 Last.fm: track.updatenowplaying response:
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <nowplaying>
    <track corrected="0">Dear God</track>
    <artist corrected="0">Confetti</artist>
    <album corrected="0">Dear God - Single</album>
    <albumArtist corrected="0"></albumArtist>
    <ignoredMessage code="0"></ignoredMessage>
  </nowplaying>
</lfm>

controller.js:541 Tab 1796: Song set as now playing
controller.js:541 Tab 1796: isPlaying state changed to false
controller.js:541 Tab 1796: isPlaying state changed to true

</details>

**Environment**
-   OS: Windows 10
-   Browser: Chrome 78.0.3904.97 (Official Build) (64-bit)
-   Extension version: (e.g. v2.24.0)

**Additional context**
I'm not sure if this might be resolved by the patch from issue #1106 - that seemed to be related to repeated scrobbles, but perhaps it might be relevant.

Seems this is related to receiving "Track is too short to scrobble" - I guess because the `"duration"` is always negative. The `New song detected` shows:

```
Tab 1796: New song detected: {
...
  "duration": -202,
...
```

The `"get info" request` does show the correct duration though:

```
Last.fm: track.getinfo response:
...
<duration>202000</duration>
...
```

Testing scrobbling from other services (eg YouTube) works fine.

I'm at work right now, but later I can try and diagnose this.

**Comment by alexesprit** [comment]
The SoundCloud player has a toggleable remaining/duration timer, the timer mode can be toggled via clicking on the timer element.

As a temporary workaround, you can set the timer as a song duration. Next version will recognize remaining time correctly.

**Comment by pgl** [comment]
Thanks, @alexesprit!
