### ISSUE TITLE
Apple Music connector not working

### ISSUE THREAD

**Issue by anuragbhd** [web-scrobbler/web-scrobbler#2156]
**Describe the bug**
Tracks playing on on Apple Music Web (beta) are not being picked up anymore by the extension Clicking the button in either Chrome or Firefox shows the "Play some music to get started" message.

**How to reproduce**
1. Go to https://beta.music.apple.com
2. Play any track from an album or playlist.
3. Click the extension icon button in extensions toolbar.

**Environment (please complete the following information)**
-   OS: Windows 10 Enterprise version 1809
-   Browser: Chrome 78, Firefox 70
-   Extension version: 2.24.0

**Additional context**
It seems the Apple's web player selectors have changed.

**Comment by roseannejordan** [comment]
How do you fix this issue?

**Comment by alexesprit** [comment]
@roseannejordan what do you mean?
