### ISSUE TITLE
Option to remember Artist/Album name correction

### ISSUE THREAD

**Issue by RAM237** [web-scrobbler/web-scrobbler#2157]
**Is your feature request related to a problem? Please describe.**
Sometimes Artist or Album name is misspelled on website (e.g. Yandex Music).  
Thus, I want to modify info for each and every song on the album currently playing.  
This is very annoying when I do some parallel activities. Because:
1. I have to modify the data for each song separately (e.g. when album has 15 songs - I have to do the same action 15 times!)
2. I have to switch to the tab where my music is playing (yep, 15 times! and 15 times back... - #1581 is already raised for this)
3. I have to be quick enough - since I can only modify the data during the 1st half of the song (this is a room for another improvement I have in mind - to be able to configure extension to send the scrobble only after song is finished, hence allowing to modify the data during the whole track length; _update_ - raised #2158 for this)

**Describe the solution you'd like**
Add some option (checkbox?) to remember my Artist/Album name correction and auto-correct all the tracks the same way on those page.

**Comment by RAM237** [comment]
Raised #2158 for Item №3.

**Comment by alexesprit** [comment]
This could be implemented as an semi-automatical way (no checkboxes, additional actions etc):
1. A user edits a track.
2. The extension saves the edited data in (existing) storage A as usual.
3. The extension saves edited artist name and album name (new behavior) in additional storage B.

When a new track is playing:
1. The extension looks for track in the storage A (current behavior).
2. If the data from storage A is missing, then it looks for data (an artist name and a album name only) in storage B (new behavior) and applies this data if available.

The question is how to apply data from storage B, where only artist and album names are stored.
a. Use an artist name and an album name separately, e.g. edited artist names can be applied to *any track from any album*; edited album names can be applied to *any track by any artist names*.
b. Use an artist name and an album name together, so the data will be applied to all track by given artist from given album.
c. (This is a kinda trade-off between `a` and `b`) Apply an artist name to any track by this artist, but use an album name in context of this artist.

I think the `c` option is a best choice.

**Comment by RAM237** [comment]
Agree, option **C** looks most applicable here.  
Thanks for your reply.

**Comment by alexesprit** [comment]
I started to implement this feature, and I have a question.

What we should to do on "Revert" link click?
1. Do a full revert, including an artist name and an album title. In this case, edited artists and albums **will be removed** and **won't be applied** to this song and **other** songs.
2. Revert only edited track title. Removing edited artist names and album names can be done in the extension options. In this case, edited artist and album **won't be removed** and **will be applied** to this song and other songs.

**Comment by RAM237** [comment]
Cool!

Regarding the "Revert" link - depends on how this is going to be implemented. If this is an option in settings, then, since its purpose is to save people's time, if it is enabled - to do a full revert. If disabled - revert only current track.

As an alternative solution (may be a bit more complex) - after clicking "Revert" three links appear on the line instead: "Revert full" , "Revert current" and "Cancel", and then, after choosing the initial items appear again ("Edit", "Skip", and "Revert" - if still applicable).

**Comment by alexesprit** [comment]
There won't be a new option in the extension settings.

I think I will go with the first way, as it covers most cases, and also keeps the previous behavior. This is not a final decision, though.

I was also thinking about marking edited fields, e.g. using an italic font style to display these fields. Not sure if this feature will be useful.

**Comment by Infinitay** [comment]
Any update on global edits?
