### ISSUE TITLE
Option to allow track data editing until it's finished and then send scrobble

### ISSUE THREAD

**Issue by RAM237** [web-scrobbler/web-scrobbler#2158]
**Is your feature request related to a problem? Please describe.**
Just want more time to be able to edit track data.  
When track is quite short, I'm often late to edit the data in time, though track is still playing.

In **scroblr** (from which I moved to **web-scrobbler**) it was possible to edit the data during the whole track, and the scrobble was submitted only after the track is over. It was cool!

Currently it is very inconvenient:
1) I have to go to Lastfm and delete the wrong scrobble
2) I have to play the same song again and edit the data this time to scrobble correctly

**Describe the solution you'd like**
Add option for such behavior - allow editing during the whole track and submit only after it is finished playing.

**Comment by alexesprit** [comment]
> Add option for such behavior - allow editing during the whole track and submit only after it is finished playing.

I think the more correct solution is to add an option to set scrobble percentage.

The extension scrobbles tracks after 50% of their duration or 240 seconds (depends on which value is smaller), and this is Last.fm requirements. If other scrobblers do this differently, they violate rules.

**Comment by alexesprit** [comment]
Another way to keep 50% or 240 seconds rule is to scrobble tracks after they're finished, or after a user swiches next track (but scrobble only tracks reached "50%/240 sec) limit).

Some limitations of this approach (and that's why it's not aceptable for me):
1. A last track won't be scrobbled until it's **fully** finished.
2. A last track on a website A won't be finished, if you start a track on a website B (even if you don't close the website A).

**Comment by RAM237** [comment]
Hmm, I do not see the necessity to stick to those seconds/percents (aka "Last.fm rules/requirements").  
Since most of the advanced scrobblers support offline work, which means scrobbles are sent to the site in a single pack once the network is available, I guess it's no matter if the info is edited in 240 seconds or 480, or even on the next day =)

If I am not wrong, native Last FM scrobbler counts the track after 30 seconds of playback. That's also why tracks shorter than 30 seconds are not scrobbled.

Personally I think you can only say you heard the song if you listened to 100% of it. But I understand there are cases when one wants just to add tracks to their library because they heard it earlier being not able to scrobble it.

The limitations you are talking about are a bit technical and I do not presume to judge about such details, I believe you know better how to deal with them :)  
Maybe, something like **scrobble tracks after they reached 99% or after user switches next track (but scrobble only tracks reached "50%/240 sec)** ?

Will option to vary the percentage from 50 to 100% violate Last.fm rules in your opinion?

**Comment by alexesprit** [comment]
> Since most of the advanced scrobblers support offline work, which means scrobbles are sent to the site in a single pack once the network is available, I guess it's no matter if the info is edited in 240 seconds or 480, or even on the next day

The offline scrobbling is a different thing.

> The limitations you are talking about are a bit technica

Yes, my example has a technical issue, but in near future the core architecture won't be changed.

> Maybe, something like scrobble tracks after they reached 99% or after user switches next track (but scrobble only tracks reached "50%/240 sec) ?

It seems like good for you, but this behavior can be unobvious for other users. The percentage option is the only way to *clearly* understand, *when exactly* a track will be scrobbled.

**Comment by RAM237** [comment]
> It seems like good for you, but this behavior can be unobvious for other users. The percentage option is the only way to _clearly_ understand, _when exactly_ a track will be scrobbled.

Yes, I totally agree.  
So, I am still not on the same page with you - are you against adding 50-100% percentage slider option or you find it acceptable?

**Comment by alexesprit** [comment]
> So, I am still not on the same page with you - are you against adding 50-100% percentage slider option or you find it acceptable?

Sorry for long delay, totally missed your comment.

I think adding a new option is a good way to resolve the issue. Plus it will satisfy #453. But I would keep this option hidden by default, and make it visible by Alt-clicking on the page, for example.

**Comment by RAM237** [comment]
No problem :)
Sounds good, thank you!

**Comment by RAM237** [comment]
Works pretty cool on v2.29! :white_check_mark:
Meanhwile, I had to look into source code to find out how to enable it 🤣

**Comment by RAM237** [comment]
Hey guys @alexesprit , @yayuyokitano !
The new v3.0.9 looks amazing, but was the [scrobble percent slider](https://github.com/web-scrobbler/web-scrobbler/commit/9c192a4f372a1863b029961480d8102f6253a8a0) implemented under current issue removed in the latest code ?  
Are there any plans to recover it in the near future?
