### ISSUE TITLE
Allow manual input

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#2173]
https://www.youtube.com/watch?v=tLPZmPaHme0 isn't detected, but i could enter the info manually if that were possible.

**Comment by alexesprit** [comment]
Hi, it's detected if you turn off both YouTube options, as this video is in Comedy category.

**Comment by CTimmerman** [comment]
Thus destroying Last.fm history more than Entertainment recipes, trailers, etc. alone. See bug 3272.
