### ISSUE TITLE
Scrobbling on Jango Radio

### ISSUE THREAD

**Issue by saraonmars** [web-scrobbler/web-scrobbler#2177]
Hello to the whole community,
I write to report that scrobbling has stopped working with Jango Radio. Is it just my problem?
I'm on Mac OS X 10.11.6
Chrome 78.0.3904.108
Web Scrobbler 2.25.0
Thank you!

**Comment by alexesprit** [comment]
Hi @saraonmars!

Jango connector was broken, and I removed it some time ago, as no one used it (according to Google Analytics stats).

I'll add support for Jango again, and it will be available in the next release.

**Comment by saraonmars** [comment]
Thanks! If you do that, I will be grateful to you ;D
