### ISSUE TITLE
Problems with The Current connector

### ISSUE THREAD

**Issue by tscbnk** [web-scrobbler/web-scrobbler#2183]
Connector works in all the streams operating with this architecture, **except** the main Current one. Not sure what happened, as it worked as expected until Nov 29.

How to reproduce???:
a) hit play on any of the following: https://www.thecurrent.org/listen/local -- https://www.thecurrent.org/listen/heartland -- https://www.thecurrent.org/listen/rock-the-cradle --https://www.thecurrent.org/listen/purple-current
b) scrobble whatever's playing.
c) then, hit play on https://www.thecurrent.org/listen
d) wait.

Maybe it has something to do with the URL? I have no clue, my area of expertise is grammar.

I'm running on Win 7 and Chrome 78.0.3904.108, by the way.

**Comment by alexesprit** [comment]
Hi!

I can't reproduce the issue:
![image](https://user-images.githubusercontent.com/1119267/70255048-2cf55e80-1797-11ea-85de-6581437855ca.png)

Have you any additional information? Could you also attach a screenshot where the extension does not recognize/scrobble tracks?

**Comment by tscbnk** [comment]
sure.

![image](https://user-images.githubusercontent.com/54915390/70258531-294be280-176b-11ea-88c2-cadd58dc0176.png)

**Comment by tscbnk** [comment]
...and for good measure:

![image](https://user-images.githubusercontent.com/54915390/70258684-6617d980-176b-11ea-8388-222ddf754744.png)

![image](https://user-images.githubusercontent.com/54915390/70258734-7d56c700-176b-11ea-931f-7f5a4e2b2509.png)

![image](https://user-images.githubusercontent.com/54915390/70258766-8d6ea680-176b-11ea-8c88-d6109168c731.png)

![image](https://user-images.githubusercontent.com/54915390/70258834-b3944680-176b-11ea-8cd3-a266f67fa4ca.png)

**Comment by alexesprit** [comment]
@tscbnk That's odd.

[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by inverse** [comment]
It's working for me too - I can't reproduce :(

**Comment by tscbnk** [comment]
apologies for the delay.

here are the debug logs:

https://pastebin.com/y1EqwBiB

https://pastebin.com/HbsTqnhg
