### ISSUE TITLE
Dealing with old issues

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#2188]
We have a lot of legacy tickets - some feature requests, others issues that cannot be reproduced. To help reduce the noise and to keep our issues under control how about using some of the bots that are available on the marketplace such as: https://github.com/apps/stale

Opinions?

**Comment by alexesprit** [comment]
This is really useful tool, but I don't know how to apply it to this project properly.

> We have a lot of legacy tickets - some feature requests

They still can be implemented (most of them are connector requests). I'm not sure if we should close these tickets.

I think it could be used to close non-reproducable issues (i.e. marked with `can't reproduce` label), but I see no way to achieve this with stalebot.

**Comment by inverse** [comment]
We could use `exemptLabels` to stop `feature` tickets being flagged as stale. The rest could just fade away...

**Comment by alexesprit** [comment]
@inverse what about connector requests? Should we drop them?

**Comment by inverse** [comment]
`exemptLabels` is a list :)

**Comment by inverse** [comment]
we could have

```
exemptLabels:
  - feature
  - request
```

**Comment by alexesprit** [comment]
I understand that. I meant should we add `requests` in this list?

**Comment by inverse** [comment]
We could do.

Feel like we should tidy up our label usage first though...

**Comment by alexesprit** [comment]
If we keep both `request` and `feature`, I'm for it. :)

**Comment by inverse** [comment]
:tada: 

I always look at projects like https://github.com/home-assistant/home-assistant for inspiration on how they operate on scale :)

**Comment by inverse** [comment]
Okay - I'll PR something and assign you ;)

**Comment by alexesprit** [comment]
Oops, I forgot about `confirmed` bugs.

**Comment by inverse** [comment]
@alexesprit updated :)

**Comment by alexesprit** [comment]
@inverse Awesome, thanks!
