### ISSUE TITLE
Yandex browser (Chrome-based) compatibility

### ISSUE THREAD

**Issue by Chudesnov** [web-scrobbler/web-scrobbler#219]
Just installed the extension on a Chromium-based browser from Yandex (browser.yandex.ru). It doesn't seem to scrobble on any of listed sites or even ask for Last.fm auth even though it shows the address bar icon (aka the scrobble toggle) when visiting such sites. 

It's certainly not a compatibility issue with some another Chrome extension (because I don't have any of them else enabled right now), so maybe it's because of some built-in stuff by Yandex. Please check on this.

**Comment by galeksandrp** [comment]
Fun is that yandex use https://addons.opera.com/en/extensions/ as extension store. Looks like extension developing experience be like in Opera.
