### ISSUE TITLE
Firefox doesn't scrobble a looped YouTube video unless mouse is moved when it replays

### ISSUE THREAD

**Issue by forwardrawkcab** [web-scrobbler/web-scrobbler#2194]
**Describe the bug**
If YouTube is set to loop a video and my cursor is either a) on the video page but still or b) on a different tab or window when the video replays, Web Scrobbler will show its icon as red and not detect the video nor scrobble it to Last.fm until I either a) move the cursor, b) switch back to the tab the YouTube video is replaying on and move around my cursor on the video page, c) move my cursor onto the window the video is replaying on, or d) switch focus to the video page and press a YouTube keybinding (e.g. "m" for mute).

I'm on Arch Linux with the bspwm window manager and replicated the issue using i3 window manager. Chromium and Chrome don't have the same issue and work as expected on both window managers.

The focus of the tab or window doesn't seem to matter, but whether the mouse is moving on the video page does, and Web Scrobbler will also scrobble by pressing any keybinding for YouTube, so the issue is apparently making Web Scrobbler and Firefox aware a page is active again when a video loops on it even if the page is in the background.

In the past the Web Scrobbler did work as expected and this issue only started happening within the past 4ish months.

**How to reproduce**
1. Right-click a YouTube video and select loop.
2. Keep your cursor still, or switch to a different tab, or focus on a different window. Wait for the video to replay.
3. The video doesn't scrobble to Last.fm (unless you move your cursor on the video page or press a YouTube keybinding on it). You may see that the Web Scrobbler icon on the page with the YouTube video is red (so Web Scrobbler hasn't detected a video started playing after automatically replaying; it only detects manual replays).

**Debug logs**
<details>In Add-ons > Debug Add-ons > Inspect > Debugger > Errors, it says: "Unchecked lastError value: Error: Missing host permission for the tab", "Error: Could not establish connection. Receiving end does not exist. bg.js:503:22", and "Unchecked lastError value: Error: No matching message handler".

...

In Debugger > Logs, it says:

Tab 2: Song set as now playing util.js:163:10 (When the video first plays)

Tab 2: isPlaying state changed to false util.js:163:10 (When the video first ends)

Tab 2: isPlaying state changed to true util.js:163:10 (When the video loops)

Tab 2: Received empty state - resetting</details>

**Expected behavior**
To scrobble looped YouTube videos on Firefox even if the tab or window a YouTube video is replaying on isn't the one being used at the time it replays.

**Environment (please complete the following information)**
-   OS: Arch Linux
-   Browser: Firefox
-   Extension version: 2.26.0

**Comment by alexesprit** [comment]
@forwardrawkcab Thanks for very detailed description. This is at least 3rd bug report related to the YouTube loop function, but now I finally know how to reproduce it.

I updated the connector, and the issue is resolved for me. Could you install the extension from [web-scrobbler.zip](https://github.com/web-scrobbler/web-scrobbler/files/3936659/web-scrobbler.zip) and tell if the issue is fixed for you?

**Comment by forwardrawkcab** [comment]
@alexesprit Hi, you're welcome. Yes, I installed the extension from the zip file and that fixes the issue completely. Thank you.

**Comment by alexesprit** [comment]
@forwardrawkcab thank you for testing. I'll push these changes asap, and will publish a patch update to stores.
