### ISSUE TITLE
Dat Piff Connector

### ISSUE THREAD

**Issue by questionmarkexclamationpoint** [web-scrobbler/web-scrobbler#2196]
**Provide information about website**
Dat Piff is a free website mostly used for streaming mixtapes from hip hop and rap artists. It would be nice if it could get some support.
[Dat Piff home page](https://www.datpiff.com)
[Dat Piff player](https://www.datpiff.com/player/m37daf45?tid=1)

No account needed.

**Comment by inverse** [comment]
Will be working in the next release!
