### ISSUE TITLE
How feasible for musicforprogramming.net

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#2199]
Provide support for http://musicforprogramming.net/

**Additional context**

Since the site only exposes track-list and plays from a mix there is no way to determine real track transitions but here is my proposal.

We can get the total duration and split it by the number of tracks and use these as the "rough" bounds for track transitions.

Opinions?

**Comment by alexesprit** [comment]
> We can get the total duration and split it by the number of tracks and use these as the "rough" bounds for track transitions.

I think it's a only (but not ideal) way to bring support for this website. This is okay-ish for those who listen a whole episode: all tracks will be scrobbled at the end of episode.

**Comment by inverse** [comment]
wish they pushed a cue file of sorts to make this feasible :/

**Comment by inverse** [comment]
Happy to close it either way - just wanted to put this out to discuss.

**Comment by inverse** [comment]
Closing as I dont think it'll be worth it...
