### ISSUE TITLE
ability to edit unrecognized scrobbles even after the song has ended

### ISSUE THREAD

**Issue by palikcuiho** [web-scrobbler/web-scrobbler#2200]
**Is your feature request related to a problem? Please describe.**
Currently, if you don't notice immediately that a track is unrecognized (ex. you're busy and don't see the notification on time), the scrobble is lost. 

**Describe the solution you'd like**
The ability to see and edit scrobbles even after the end of the songs, especially for unrecognized tracks. Maybe a list/cache? 

Thanks a lot for this great extension!

**Comment by alexesprit** [comment]
Hi, this is requested in #291.
