### ISSUE TITLE
Support for Kodi/Chorus in Local mode

### ISSUE THREAD

**Issue by Terrance** [web-scrobbler/web-scrobbler#2202]
Currently, the Kodi connector only captures playback information from the Chorus web interface when playing media on Kodi itself (which works fine, though is perhaps better suited to a server-side plugin).

Chorus can also stream media to the browser when the toggle in the top-right is set to Local.  The player interface remains the same, though it looks like a separate copy of the DOM can be found in `#player-local` (as opposed to `#player-kodi`).

**Comment by alexesprit** [comment]
Chorus web interface allows to play tracks from both "local" and "kodi" players. In this case the extension reads track info from the active player, and completely ignores non-active player (even if it's playing).
