### ISSUE TITLE
Support for LiveXLive.com, formerly Slacker.com

### ISSUE THREAD

**Issue by Druid42** [web-scrobbler/web-scrobbler#2209]
Looking to get support for [LiveXLive](http://livexlive.com), which was formerly slacker.com.

**Comment by jaccarmac** [comment]
Does the existing Slacker connector work if the URL patterns are updated manually in preferences?

**Comment by alexesprit** [comment]
@jaccarmac someone says it does not work.

**Comment by alexesprit** [comment]
I'm closing this one as a duplicate.

I asked about implementation of LiveXLive in #1963.

**Comment by alexesprit** [comment]
@Druid42 Hi! The next release will support for scrobbling from LiveXLive.
