### ISSUE TITLE
Web Scrobbler to Recognize Track Under Different Albums

### ISSUE THREAD

**Issue by monasux** [web-scrobbler/web-scrobbler#2213]
Hi! I wonder if Web Scrobbler recognizing the same track being played under different albums is possible to be added as a feature, for example: if I'm playing a song under a compilation or a live album 
![image](https://user-images.githubusercontent.com/59259113/71547126-7e62c900-29a4-11ea-8196-d12b70a1e05c.png)
the Scrobbler sometimes suggests another album even though the album name is already in the blanks
![image](https://user-images.githubusercontent.com/59259113/71547147-afdb9480-29a4-11ea-9c1e-a37245e51e6f.png)
so I wonder if there's a way for me to add multiple versions of the edited track and to have the extension recognizing the album I'm playing instead of suggesting an album from last fm data by manually turning off the album suggestion or something. I really hope this made sense.

**Comment by alexesprit** [comment]
@monasux Hi! It won't be fixed for Spotify, as it does not provide album info in the **player bar**, like other services (e.g. Google Play Music) do. The only way to get album is to get it from Last.fm.

**Comment by inverse** [comment]
@alexesprit what about doing a ajax request for the album which is exposed in the player? then pulling it from that? Not sure how feasible that is in reality though.

**Comment by alexesprit** [comment]
@inverse it would be a hack, rather than a solution of the issue. Unfortunately, there's no way to get track info asynchronously.

**Comment by inverse** [comment]
@alexesprit we could try and leverage their Web API ( https://developer.spotify.com/documentation/web-api/) but that'll be a whole world of fun ;)

**Comment by alexesprit** [comment]
@inverse it's still asynchronous, plus, we can get the same issue as we had with YouTube when we used API.

**Comment by alexesprit** [comment]
Was fixed in f232d6ae80e8c5b12b2d2548633d35f9ac3299ea by using MediaSession API. It's experimental API, though, but all modern browsers support this.
