### ISSUE TITLE
Stopped working correctly

### ISSUE THREAD

**Issue by LunarJunkie** [web-scrobbler/web-scrobbler#2219]
It scrobbles the first track, but the next  tracks are "copies" of the first one. The problem occurred on December 14.
![scrobb](https://user-images.githubusercontent.com/59344025/71562502-22766e00-2a92-11ea-8c7e-2ed9dfd255b5.png)

**Comment by inverse** [comment]
We'll need more information than this to go on.

- Where you scrobbling from?

**Comment by LunarJunkie** [comment]
> We'll need more information than this to go on.
> 
> * Where you scrobbling from?

VK com, this is a  social networking service
