### ISSUE TITLE
Doesnt work scrobbling from web

### ISSUE THREAD

**Issue by ButcherNensy** [web-scrobbler/web-scrobbler#2220]
**Describe the bug**
Tracks from vk.com and bandcamp.com do not appear in library from 29/12/2019
But web scrobbler still worked
![image](https://user-images.githubusercontent.com/59360271/71577576-4b950e00-2b27-11ea-917a-54c644d348c8.png)

-   Browser: Chrome

**Additional context**
I think that somesing going wrong with LastFM API cose of it doesnt work in standard deezer scrobbler too

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension
