### ISSUE TITLE
"Love" a track when clicking "Like" on YT, "Love" on SoundCloud, "Favorite" on Spotify, etc.

### ISSUE THREAD

**Issue by pgl** [web-scrobbler/web-scrobbler#2229]
**Description**
I think it would be great if when clicking "Like" on YouTube, "Love" on SoundCloud, "Favorite" on Spotify, etc, it would be the same as hitting the heart button in Web Scrobbler, so that it gets registered as a loved track.

**Comment by CennoxX** [comment]
Duplicate of #1424

**Comment by pgl** [comment]
True! Thanks for finding that, I did search but obviously didn't find it.
