### ISSUE TITLE
Scrobbling for https://music.youtube.com/ not working at all

### ISSUE THREAD

**Issue by njack21** [web-scrobbler/web-scrobbler#2233]
Not scrobbling for any tracks.

**Comment by alexesprit** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/1119267/71935968-31a79b00-31b9-11ea-8b09-88c41211ad28.png)

**Comment by njack21** [comment]
100% reproducible for me.

![Annotation 2020-01-07 150121](https://user-images.githubusercontent.com/25303759/71936544-9c77b880-315e-11ea-9ab3-13079f69dd97.jpg)

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by njack21** [comment]
https://pastebin.com/7uWz0tK7

**Comment by alexesprit** [comment]
What's your OS, browser name and browser version, exension version?

**Comment by njack21** [comment]
Windows 10 - 1903
Version 80.0.3987.16 (Official Build) beta (64-bit) 
Extension - 2.27.0

**Comment by njack21** [comment]
Also happens with Chrome Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by ormulum** [comment]
not working for me either
ubuntu budgie 19.04
firefox (sorry, don't know)
extension 2.27.0

**Comment by njack21** [comment]
This is still an issue. Would love to see it get fixed.

**Comment by alexesprit** [comment]
@njack21 is it happening on YouTube Music only? Can you reproduce the issue on other browsers, e.g. Firefox?

**Comment by njack21** [comment]
Seems to also be happing for Google Play Music. Scrobbling works for Spotify.

Chrome Version 80.0.3987.132

**Comment by alexesprit** [comment]
Could you also check scrobbling from YouTube, and from YouTube Music on Firefox?

**Comment by alexesprit** [comment]
If the extension does not work for YouTube too, the issue could be related to #1576.

**Comment by njack21** [comment]
Will install Firefox and test there.

Scrobbling does not work for YouTube either. Checking out linked report.

**Comment by njack21** [comment]
Will also validate on personal computer, based on info in #1576

**Comment by njack21** [comment]
Scrobbling works on non work machine, so it appears to be Chrome policy being enforced by organization.

**Comment by alexesprit** [comment]
I've fixed a small issue, and now the extension displays the "Unsupported" browser action icon for blocked websites. I also added a note about the ExtensionSettings policy:
![image](https://user-images.githubusercontent.com/1119267/76590075-306a5580-64fd-11ea-90a8-2cf184d48ef3.png)
