### ISSUE TITLE
No notification or tab on first install to give permissions, and nothing happens when clicking "sign in" links in options

### ISSUE THREAD

**Issue by thecommissar** [web-scrobbler/web-scrobbler#2236]
I've installed Web Scrobbler for the first time. I opened the options because I did not get a notification to configure the extension, as the description says I should. Similarly, I also did not get a tab open in the place of a notification either.

I opened the options to try and manually sign in. I click the link to sign in for Last.fm and nothing happens, as if the link is dead. Copying and pasting the link I get this:

moz-extension://8c684068-3895-429b-aff0-288bc9dd23d7/ui/options/index.html#

Steps to reproduce:

1. On Windows 10, using Firefox 69.0.3
2. Install web scrobbler addon 2.27.0
3. Note no notification or configuration tab opens
4. Open web scrobbler options, click accounts
5. Click "sign in" links
6. Nothing happens.

Expected behaviour:

1. Expected a notification popup or tab on first time installing the addon, etc as noted in addon description
2. Expected a tab to open for a respective provider asking for authorization when clicking sign in link in web scrobbler options.

Environment: 

OS: Windows 10
Browser: Firefox 69.0.3
Extension version: 2.27.0

Additional context:

Disabling NoScript, uBlock Origin, and Privacy Badger did not resolve any of the above issues.

**Comment by alexesprit** [comment]
> moz-extension://8c684068-3895-429b-aff0-288bc9dd23d7/ui/options/index.html#

The extension generates login link opens a new tab, when you click on "Sign in" link, so you cannot copy it.

If you click on "Sign in" link with middle-click, it won't work. This is a known issue.

If you click on the link with left-click, and have this issue, please read this: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-the-options-page

**Comment by thecommissar** [comment]
I'm wasn't actually trying to copy and paste it into a tab; I just put that there for extra detail in the bug report. Left clicking the sign-in links do nothing.

Here is the log as requested:

> Error: UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 3 ExtensionUtils.jsm
> storage.Options = {
>   "disableGa": false,
>   "forceRecognize": false,
>   "disabledConnectors": "[hidden]",
>   "useNotifications": true,
>   "useUnrecognizedSongNotifications": false,
>   "scrobblePodcasts": true
> } wrapper.js:68:12
> storage.Connectors = {
>   "Tidal": {
>     "useShortTrackNames": false
>   },
>   "YouTube": {
>     "scrobbleMusicOnly": true,
>     "scrobbleEntertainmentOnly": false
>   }
> } wrapper.js:68:12
> Request to access cookie or storage on “https://akamai.mathtag.com/event/img?akam_state=0&no_log&mt_…v4oZphbUpQ417gte9s%2f14LwWIJ8DZyvHG2QX8uRA6lZUoiO923W%2fDmqK” was blocked because it came from a tracker and content blocking is enabled.
> 2 index.html
> Error: Could not establish connection. Receiving end does not exist. accounts.js:79:20
> Source map error: TypeError: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://8c684068-3895-429b-aff0-288bc9dd23d7/vendor/bootstrap/css/bootstrap.min.css
> Source Map URL: bootstrap.min.css.map
> 
> Error: Could not establish connection. Receiving end does not exist.

**Comment by alexesprit** [comment]
@thecommissar Is it reproducable on Firefox 69.0.3 only? Have you tried to use newer version of Firefox?

**Comment by thecommissar** [comment]
I downloaded the portable version of Firefox 70 to test it out in that. It appears to work in that version of the browser. It may be specific to this version.
