### ISSUE TITLE
Pandora scrobbling not working in Firefox

### ISSUE THREAD

**Issue by SilverlightPony** [web-scrobbler/web-scrobbler#2237]
In Firefox, the extension does not detect songs playing on Pandora website.

**Steps to reproduce the behavior:**
1. Open Firefox desktop browser
2. Go to Pandora.com
3. Start playing a song

**Expected behavior**
Scrobbler recognizes that a song is playing, correctly identifies it, and sends info to Last.fm

**Screenshots**
![scrobbler2](https://user-images.githubusercontent.com/4299310/72479708-3aa0f980-37c3-11ea-828c-644f8be51661.PNG)

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Firefox v72.0.1
-   Extension version: 2.27.0

**Additional context**
Chrome version of extension, also installed today, works fine.

**Comment by monokrome** [comment]
Hey - this is still an issue for what it's worth :)
