### ISSUE TITLE
Disabled site settings are not saved

### ISSUE THREAD

**Issue by toby3d** [web-scrobbler/web-scrobbler#2240]
**Describe the bug:** If you turn off the site through by removing the checkbox from the site in the list on the settings page, these exceptions will not be saved.

**How to reproduce:**
* Open Yandex.Music
* Start playback, track will be recognized for scrobbling (thats ok, but...)
* Open extension settings
* Remove the checkbox opposite the Yandex.Music website
* Close the extension page
* Play a different track in the service, track recognized and queued for scrobbling (why?)

**Expected behavior:** The site will be disabled for scrobbling immediately after unchecking.

**Debug logs:** [console-export-2020-1-22_18-30-45.txt](https://github.com/web-scrobbler/web-scrobbler/files/4097529/console-export-2020-1-22_18-30-45.txt)

**Environment:**
-   OS: Linux 5.4.13-3-MANJARO
-   Browser: Firefox Developer Edition v73.0b5 (64-bit)
-   Extension version: v2.27.0

**Additional context**
Disabling the site through the context menu (RMB - Disable site...) does add an exception, but it works until the browser closes. After restarting, this exception disappears.

**Comment by alexesprit** [comment]
> Play a different track in the service, track recognized and queued for scrobbling (why?)

You should reload that tab to apply settings. This is expected behavior.

> Disabling the site through the context menu (RMB - Disable site...) does add an exception, but it works smoothly until the browser closes. After restarting, this exception disappears.

I can't reproduce that - using "Disable AAA connector" permanently turns off the connector for the current tab.

**Comment by toby3d** [comment]
> You should reload that tab to apply settings. This is expected behavior.

The effect is similar. The setting does not apply. Here is a demo:

![Peek 2020-01-23 12-58](https://user-images.githubusercontent.com/5412322/72966341-89145080-3de0-11ea-8332-ffa62bd61be3.gif)

In the first attempt, I turn off the site, close the settings tab, and then I immediately open them again to check the status in the second attempt. The exception is canceled when the tab is closed, respectively, reloading the tab with music no longer makes sense.

Also, disabling the site through the context menu does not affect the settings page in any way:

![Peek 2020-01-23 13-03](https://user-images.githubusercontent.com/5412322/72966527-fc1dc700-3de0-11ea-9450-3793f7b591d7.gif)

**Comment by alexesprit** [comment]
I still cannot reproduce the issue.

https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-the-options-page

**Comment by toby3d** [comment]
The bug is still repeated in v2.28.2. After closing the settings page, the status of all connectors is reset to "on".

Some logs:
```
09:21:37.092 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:21:37.180 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
09:21:38.487 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:21:38.507 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
09:21:48.142 Error: Could not establish connection. Receiving end does not exist. 2 page.js:93:16
09:21:49.118 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
09:21:51.239 storage.ListenBrainz = {
  "sessionID": "************************************",
  "sessionName": "******"
} wrapper.js:68:12
09:21:51.241 storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "******"
} wrapper.js:68:12
09:21:51.242 storage.LibreFM = {
  "sessionID": "********************************",
  "sessionName": "******"
} wrapper.js:68:12
09:21:51.881 storage.Options = {
  "disabledConnectors": "[Array(0)]",
  "disableGa": true,
  "forceRecognize": false,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": false,
  "scrobblePodcasts": false
} wrapper.js:68:12
09:21:52.315 storage.Connectors = {
  "Tidal": {
    "useShortTrackNames": true
  },
  "YouTube": {
    "scrobbleMusicOnly": true,
    "scrobbleEntertainmentOnly": false
  }
} wrapper.js:68:12

<!-- The settings page completely loaded, I turned off several random connectors like Yandex.Music, Amazon and Flo. -->

09:21:55.113 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:21:55.159 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
09:22:05.332 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:22:05.488 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
09:22:07.544 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:22:07.558 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
09:22:09.242 Error: Could not establish connection. Receiving end does not exist. background.js:1:761
09:22:09.354 Error: Could not establish connection. Receiving end does not exist. page.js:79:15

<!-- Here I close settings page and open it again -->

09:22:11.133 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:22:11.133 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
09:22:15.652 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:22:20.351 storage.Options = {
  "disabledConnectors": "[Array(0)]",
  "disableGa": true,
  "forceRecognize": false,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": false,
  "scrobblePodcasts": false
} wrapper.js:68:12
09:22:20.407 storage.ListenBrainz = {
  "sessionID": "************************************",
  "sessionName": "******"
} wrapper.js:68:12
09:22:20.421 storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "******"
} wrapper.js:68:12
09:22:20.425 storage.LibreFM = {
  "sessionID": "********************************",
  "sessionName": "******"
} wrapper.js:68:12
09:22:23.397 storage.Connectors = {
  "Tidal": {
    "useShortTrackNames": true
  },
  "YouTube": {
    "scrobbleMusicOnly": true,
    "scrobbleEntertainmentOnly": false
  }
} wrapper.js:68:12
09:22:29.034 Error: Could not establish connection. Receiving end does not exist. page.js:93:16
09:22:29.116 Error: Could not establish connection. Receiving end does not exist. page.js:79:15
```

**Comment by alexesprit** [comment]
@toby3d I think I found the reason of the issue. I'm publishing v2.28.3 contains the fix for this issue. Could you update and tell me if it's fixed for you?

**Comment by toby3d** [comment]
@alexsprit Sure. I will report the results immediately after updating the add-on in the browser.

**Comment by toby3d** [comment]
Yes, It works as expected in v2.28.3! :+1:
