### ISSUE TITLE
Don't add scrobbles multiple times

### ISSUE THREAD

**Issue by CennoxX** [web-scrobbler/web-scrobbler#2242]
If two or more tabs of the same music-site are opened a song is srobbled more than once.

**How to reproduce**
1. Open in one tab: https://open.spotify.com/
2. Open in another tab: https://open.spotify.com/
3. Play a song in one tab
4. The song is scrobbled twice

**Expected behavior**
The same song shouldn't be scrobbled several times at the same time.

**Environment**
-   OS: Windows
-   Browser: Firefox
-   Extension version: v2.27.0

**Comment by alexesprit** [comment]
I can turn off scrobbling from a Spotify tab, if a connect bar (a green bar at the bottom of the page) is visible.

But songs are won't be scrobbled, if you listen music from another source (e.g. Spotify app or Android app), and have a tab with Spotify opened.
