### ISSUE TITLE
Bandcamp daily tracks not recognised

### ISSUE THREAD

**Issue by no1joel** [web-scrobbler/web-scrobbler#2245]
**Describe the bug**
Tracks played on daily.bandcamp.com pages are not recognised as playing.

**How to reproduce**
1. Go to https://daily.bandcamp.com/lists/a-beginners-guide-to-unwounds-otherworldly-post-hardcore
2. Click on Play button
3. Scrobbler does not recognise playing tracks

**Expected behavior**
A scrobbler to recognise playing tracks

**Debug logs**
```
Injecting vendor/jquery.min.js
inject.js:56 Injecting vendor/browser-polyfill.min.js
inject.js:56 Injecting core/content/util.js
inject.js:56 Injecting core/content/reactor.js
inject.js:56 Injecting core/content/filter.js
inject.js:56 Injecting core/content/connector.js
inject.js:56 Injecting connectors/bandcamp-embed.js
inject.js:56 Injecting core/content/starter.js
extension.js:337 Tab 2020: Remove controller for Bandcamp Daily connector
util.js:163 Tab 2020: Created controller for Bandcamp Daily connector
```

**Environment (please complete the following information)**
-   OS: macOS Mojave (10.14.6)
-   Browser: Chrome 79.0.3945.130
-   Extension version: 2.27.0

**Additional context**
It seems to recognise that it's on a bandcamp page, but the daily.bandcamp.com player appears to be new and different to your standard album pages. Apologies if this warrants a new connector issue instead.

**Comment by alexesprit** [comment]
Seems like they changed the UI layout, so the extension does not work on Bandcamp.

**Comment by inverse** [comment]
Ouch - this is a major overhaul

**Comment by alexesprit** [comment]
@inverse album pages are covered by another connector. We use `bandcamp-embed` for Bandcamp Daily.

**Comment by no1joel** [comment]
I've created a pull request which seems to work with the new design, though as I say on the PR I think the `playerSelector` I'm using is too broad.
If it's not OK to go in as-is at least someone could probably use it as a starting point.
