### ISSUE TITLE
FIP direct radioplayer doesn't scrobble anymore

### ISSUE THREAD

**Issue by papposilene** [web-scrobbler/web-scrobbler#2249]
**Describe the bug**
FIP direct radioplayer doesn't scrobble anymore.

**How to reproduce**
1. Go to https://www.fip.fr
2. Click on play on any radio : direct, electro, groove, world, new, jazz, etc.
3. Scrobbler does not recognize playing tracks

**Expected behavior**
A clear and concise description of what you expected to happenLast week, the web crobbler worked perfectly on the FIP website. It doesn't work anymore : bug in the extension or change in the website.

**Debug logs**
Debug logs on [pastebin](https://pastebin.com/FUkifkqt).

**Environment (please complete the following information)**
-   OS: Windows at work, Mac OS at home.
-   Browser: Chrome at work, Firefox at home.
-   Extension version: 2.25.0

**Additional context**

**Comment by echomadman** [comment]
Website front end has changed in the last week, scrobbler has not worked for ~3 weeks now
