### ISSUE TITLE
Archive.org LP listening - keeps scrobbling same title even though tracks are changing.

### ISSUE THREAD

**Issue by newmusicmark** [web-scrobbler/web-scrobbler#2262]
If you play an album on the somewhat new LP collection on archive.org, web scrobbler comes up and you can edit the song title.  However, web scrobbler recognizes when you get to a new track on the album, but it keeps scrobbling the previously entered song title.  It seems like it should recognize you are listening to a new file and allow for the new track title.

Go to: https://archive.org/details/lp_organ-sounds-and-percussion_eddie-layton/disc1/01.03.+Sugar+Blues.mp3   play a track...  add the title if not in web scrobbler.  When the next song plays, the URL changes to the next track, but web scrobbler will scrobble the previous data making it look like you listened to the same song twice.

**Comment by inverse** [comment]
@newmusicmark will be fixed in the next release :+1:
