### ISSUE TITLE
Youtube Music video is not scrobbled on firefox

### ISSUE THREAD

**Issue by LaHaine** [web-scrobbler/web-scrobbler#2264]
**Describe the bug**
I was trying to play a music video, it didn't scrobble. I have tested this one:
https://www.youtube.com/watch?v=a8QwxdF_oMQ

**How to reproduce**
Click on the music video
Play it
It is not scrobbled, the extension doesn't notice that the song has been started.

**Expected behavior**
It should scrobble the song.

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   Ubuntu 18.04 Linux
-   Firefox 72.0.2
-   Extension version: 2.27.0

**Additional context**
The same video is working fine on chrome 80.0.3987.106 with the same extension version.

**Comment by alexesprit** [comment]
This video is in `People & Blogs` category. You should uncheck these checkboxes to scrobble it:
![image](https://user-images.githubusercontent.com/1119267/74864521-c4af2580-5360-11ea-90e1-807fdcfd8be9.png)
