### ISSUE TITLE
short track titles on vk.com

### ISSUE THREAD

**Issue by hellpanderrr** [web-scrobbler/web-scrobbler#2266]
vk.com has additional info for the tracks such remastered, reissued and so on:
![image](https://user-images.githubusercontent.com/2708297/74590803-e471e100-5022-11ea-8a1e-713589161904.png)
 written in grey here, `2015 Remaster`
Despite having selected "short titles" (Tidal) option in the settings, this song is still getting scrobbled as `Moonchild (2015 Remaster)`. Is it possible to not scrobble that part?

**Debug logs**
https://pastebin.com/MCBEZ1gT

**Environment (please complete the following information)**
-   OS: Windows 10 1903
-   Browser: Chrome 79.0.3945.130
-   Extension version: 2.27.0

**Comment by alexesprit** [comment]
Yes, it's possible. We have remaster filter for other websites, but it can be added to vk.com.
