### ISSUE TITLE
Failing to detect tracks on the new Mixcloud UI

### ISSUE THREAD

**Issue by KillTheBuzz** [web-scrobbler/web-scrobbler#2271]
**Describe the bug**
The plugin is not recognizing music on the new Mixcloud UI update
**How to reproduce**
1. Go to www.mixcloud.com
2. Click on click on any music mix
3. Check the extension 
4. Says website not supported 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/19752692/75031924-66955600-54b8-11ea-82de-d2ca8b1e9b30.png)

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Edge Beta(chromium version)
-   Extension version: 2.27.0

**Comment by alexesprit** [comment]
It's fixed in v2.28.0.
