### ISSUE TITLE
Strip out track numbers from YouTube titles

### ISSUE THREAD

**Issue by stephanebruckert** [web-scrobbler/web-scrobbler#2272]
Either CD or vinyl track numbers are currently being scrobbled as part of the artist. I suggest to detect and remove them (I'm currently doing this manually by editing all scrobbles).

Examples:
 - `02. Dub FX- Sooth Your Pain` => `Dub FX - Sooth Your Pain`
   - https://www.youtube.com/watch?v=18ex8FSl4Z4
 - `A1. Janeret - Critical` => `Janeret - Critical`   
    - https://www.youtube.com/watch?v=CT1ZOpymxHE 
 - `D3. Peter F. Spiess - Emergency Radio` => `Peter F. Spiess - Emergency Radio`
   - https://www.youtube.com/watch?v=eZRrhMS5xbg
 - `D. Bruno Pronsato - Part 4` => `Bruno Pronsato - Part 4`
   - https://www.youtube.com/watch?v=Hf7Vnl6BkyY

Also I found that some vinyl tracks could be numbered [`AA1`](https://www.youtube.com/watch?v=gclL1-0p2Qo) or [`AA`](https://www.youtube.com/watch?v=hKP7U21tfCw).

FYI I'm doing this in python for vinyl tracks only and this is the regex I've been using:

    ^([a-zA-Z]{1,2}[1-9]?. )?

Edit: also on Soundcloud this could be needed in that kind of situation https://soundcloud.com/cabanne-fr

**Comment by inverse** [comment]
Sounds like it could be setup as a filter for services like YouTube, Soundcloud.

https://regex101.com/r/gHh2TB/1

I modified your regex to strip out the numeric

**Comment by stephanebruckert** [comment]
Updated your regex101 with some invalid ones https://regex101.com/r/gHh2TB/2

**Comment by stephanebruckert** [comment]
Hey @inverse, @alexesprit,

I would like to open a PR for that one but it's unclear to me whether this should go into utils.js:

https://github.com/web-scrobbler/web-scrobbler/blob/0605772afb376b611674457815ddd1f3cb3b30c9/src/core/content/util.js#L561

or in the new metadata repo https://github.com/web-scrobbler/metadata-filter/?

Is `processYtVideoTitle` a left-over?

Thanks for enlighting me on how/where you would solve this
