### ISSUE TITLE
Mixcloud not working

### ISSUE THREAD

**Issue by Mavoy** [web-scrobbler/web-scrobbler#2275]
After the recent "fancy" Mixcloud interface update, Web Scrobbler is broken. While the tags for the tracks still appear in the player, they're not grabbed by Web Scrobbler and therefore the extension is worthless on the site.  To reproduce it, just go to Mixcloud and try to scrobble any show (I mostly visit NTS Radio profile, but I also tried one show from Jazzcat).

Here is the content of debug log: https://pastebin.com/837zZkVc

The bug happens on Windows 10, on both Chrome and Firefox, updated browsers and updated extension.

**Comment by alexesprit** [comment]
What is the version of the extension you have installed?

**Comment by Mavoy** [comment]
The current one, 2.27.0. I checked for updates before sending report, obviously.

**Comment by alexesprit** [comment]
Hmm, it was fixed in v2.28.0, which is not in Chrome Web Store for some reason.

**Comment by powderedegg** [comment]
I've install v2.28.0 from the builds, but have noticed that tracks aren't being recognised because the artist field has "-- Buy" appended to it.

Eg.  

Sweet Harmony | Liquid — Buy

**Comment by alexesprit** [comment]
Yes, I know about this issue. I will fix it and will try to publish the updated extension (will be v2.28.2 in stores).

**Comment by alexesprit** [comment]
Currently v2.28.1 is reviewing in Chrome Web Store. Unfortunately, Chrome Web Store does not allow to upload the new version, until the review process is complete. I'll upload v2.28.2 after v2.28.1 is approved.
