### ISSUE TITLE
Connect to RadioTunes

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#2277]
**Provide information about website**
The website is https://www.radiotunes.com and it is a part of the group that also has Jazz Radio (https://www.jazzradio.com) and Digitally Imported (https://www.di.fm).

**Additional context**
The Radio Tunes website is a copy of Zen Radio #2259 and Jazz Radio, for which you already support, so I would expect a simple integration

**Comment by alexesprit** [comment]
It's already supported, isn't it?

**Comment by pedrojvaz** [comment]
![image](https://user-images.githubusercontent.com/4522620/75426729-8a87ea00-5945-11ea-91f5-5ebd3982372e.png)
It's not recognizing…

**Comment by pedrojvaz** [comment]
Apologies, you are right. I'm closing this
