### ISSUE TITLE
Connect http://jellyfin.org

### ISSUE THREAD

**Issue by ldexterldesign** [web-scrobbler/web-scrobbler#2278]
**Provide information about website**

Jellyfin - basically the FOSS [E]mby fork

Simplest demo is to spin up a [D]ocker container

Yours hopefully

PS thanks for wonderful software!

d: http://hub.docker.com/r/linuxserver/jellyfin
e: http://emby.media
j: http://jellyfin.org

**Comment by ldexterldesign** [comment]
FYI https://www.reddit.com/r/jellyfin/comments/d1mtd5/we_have_now_surpassed_the_member_count_of_the/

**Comment by Xalaxis** [comment]
It's worth noting that the current Emby connector seems to work fine with Jellyfin on my local instance.  Perhaps we should simply rename the Emby connector to Emby/Jellyfin for now, until the codebases become further distinct?

**Comment by alexesprit** [comment]
Hi!

We have default URL patterns for Emby (see `matches` section):
```js
{
	label: 'Emby',
	matches: [
		'*://*8096/web/*',
		'*://*8920/web/*',
		'*://app.emby.media/*'
	],
	js: 'connectors/emby.js',
	id: 'emby',
}
```

What are default URLs for Jellyfin?

**Comment by ldexterldesign** [comment]
https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Model/Configuration/ServerConfiguration.cs#L14

Presume it's the same

With regards

**Comment by alexesprit** [comment]
I made a small change to allow `emby` connector to work for both Jellyfin and Emby.

I also made other improvements and fixes for Emby/Jellyfin, e.g. displaying a large cover arts. :) These changes will be available in the next version.
