### ISSUE TITLE
Disabling spotify doesn't work

### ISSUE THREAD

**Issue by 0hmyrowling** [web-scrobbler/web-scrobbler#2279]
**Describe the bug**
I want to disable spotify to prevent duplicate scrobbling. When I uncheck the box then close and open a new window it hasn't saved that the box is unchecked and still scrobbles spotify. 

**How to reproduce**
1. go to options
2. uncheck spotify
3. close window
4. open spotify, play music
5. see that it is still scrobbling

**Expected behavior**
There should be some kind of save button so that it saves the box that is unchecked.

**Screenshots**

**Debug logs**
https://pastebin.com/9VPPegie

**Environment (please complete the following information)**
-   OS: windows
-   Browser: chrome 
-   Extension version: 2.28.1
**Additional context**

**Comment by alexesprit** [comment]
Hi, it's related to #2240, so I close this as a duplicate.
