### ISSUE TITLE
[Mixcloud] The "— Buy" suffix is being scrobbled again

### ISSUE THREAD

**Issue by Betmax** [web-scrobbler/web-scrobbler#2280]
I found that this bug had been solved [in the past](https://github.com/web-scrobbler/web-scrobbler/issues/1713), but it seems like it returned. When I listen to the show and there is a tagged track, Web Scrobbler gets it with "— Buy" in the artist name. As a result, I get messy stats at last.fm.

See the screenshot for the suffix.

![image](https://user-images.githubusercontent.com/61538608/75427415-06e7f080-5979-11ea-89dd-23c084dd1206.png)

Debug logs
https://pastebin.com/wfuCb5ir

-   OS: Windows
-   Browser: Chrome
-   Extension version: (e.g. v2.28.1)

First-time posting, so sorry, if I did something wrong!
Love your extension.

**Comment by alexesprit** [comment]
Thanks for reporting. This was already mentioned in https://github.com/web-scrobbler/web-scrobbler/issues/2275#issuecomment-590232385.

I fixed this regression in v2.28.2. I've just published it in Chrome Web Store, and it will be available after it's reviewed.

**Comment by Betmax** [comment]
Thanks!
