### ISSUE TITLE
Missing scrobbles when song is on repeat.

### ISSUE THREAD

**Issue by subiabre** [web-scrobbler/web-scrobbler#2281]
**Describe the bug**
When a song is on repeat on Amazon Music it will only scrobble it once and miss the rest of plays of the same song.

**How to reproduce**
1. Go to music.amazon.com
2. Click on any song of your choice.
3. Put it on repeat.
4. Check the only scrobble of the song on your last.fm profile.

**Expected behavior**
It should scrobble the song for as many times it has been repeated.

**Environment (please complete the following information)**
-   OS: Ubuntu 18.04 64 bits
-   Browser: Firefox 73.0
-   Extension version: v2.28.2

**Additional context**
I've only seen it happen consistently on Amazon Music site, but it also randomly happens on other sites such as YouTube and bandcamp. Haven't tested other sites.

**Comment by merciersj** [comment]
I came here to report this, also.  Since this has been closed I will create another because I see this as an issue.

**Comment by alexesprit** [comment]
It was closes because no one provided debug logs. :)

As for me, I have no access to Amazon, so I cannot verify and fix the issue.
