### ISSUE TITLE
Mixcloud - new problems

### ISSUE THREAD

**Issue by Mavoy** [web-scrobbler/web-scrobbler#2287]
So, you can scrobble with Mixcloud again, but I'm having problems with detecting songs.

When you scrobble the track successfully, it gets stuck and it doesn't detect when the different track starts playing. You have to refresh the website to get the extension working again.

For example In this case it got stuck at Yma Sumac's song from here  https://www.mixcloud.com/NTSRadio/phils-jazz-disjunction-23rd-february-2020/ 

I started listening to different mix (https://www.mixcloud.com/NTSRadio/alexander-nut-25th-february-2020/) but despite the tracks being properly tagged, Web Scrobbler is still showing me that Sumac's track was scrobbled and it doesn't detect that a new song is being played.

Log: https://pastebin.com/XcuZMMbp 

new Chrome, Windows 10, Web Scrobbler 2.28.2

**Comment by alexesprit** [comment]
Could you test the extension from this zip? [web-scrobbler.zip](https://github.com/web-scrobbler/web-scrobbler/files/4270156/web-scrobbler.zip)

https://github.com/web-scrobbler/web-scrobbler/wiki/Install-an-unpacked-extension#install-the-extension

**Comment by Mavoy** [comment]
Thanks! I installed the zip update and the scrobbling is working now. But now, after the update, I'm getting pop-up notifications about played track, even if I have the option turned off in the settings. Not just on Mixcloud - on YouTube, for example, as well. I even restarted the browser. I guess it needs a new fix....

**Comment by alexesprit** [comment]
> But now, after the update, I'm getting pop-up notifications about played track

It's not an update, tecnically, but a sort of copy of the extension installed from a zip file. It works independently, and uses default settings, one of them is to display now playing notifications (true by default).

You can freely remove this copy after new version is published.

This is not a bug, so it should not be fixed. :)

**Comment by alexesprit** [comment]
Should be fixed in v2.28.4. Don't know when it will be published - v2.28.3 is being reviewed, and I cannot publish other versions.
