### ISSUE TITLE
Option to only scrobble edited tracks (track whitelist).

### ISSUE THREAD

**Issue by RudeySH** [web-scrobbler/web-scrobbler#2290]
I'm using Web Scrobbler exclusively for scrobbling music on YouTube. I have a couple of playlists and I'm currently editing the tracks so that the metadata is correct. I have not enabled "Force track recognition" because I don't want messy scrobbles. I'd like to take it one step further and only scrobble tracks that I have edited. Only when the metadata of a track was edited by me, should it be scrobbled. When YouTube or any service plays a track that I have already edited before, it should scrobble automatically of course.

A checkbox option to enable the "Scrobble edited tracks only" behavior would help greatly. One thing to consider after implementing such checkbox, is how to deal with tracks that already have proper metadata and don't need to be edited (as far as the user is concerned). For those tracks, I'd imagine I would have to press the "edit" button, just to press "submit" without editing anything, just to get them into the edited tracks list,

Perhaps it would be even better to implement a whitelist option (and a blacklist if that sounds useful to you).  Adding tracks to the whitelist would lead to only those tracks being scrobbled, which is what I need. You could make it so that editing tracks would automatically add them to the whitelist.

**Comment by alexesprit** [comment]
> One thing to consider after implementing such checkbox, is how to deal with tracks that already have proper metadata and don't need to be edited (as far as the user is concerned). For those tracks, I'd imagine I would have to press the "edit" button, just to press "submit" without editing anything, just to get them into the edited tracks list,

This feature could be implemented by marking all tracks as unknown, except that ones are edited by a user. So, you're almost right: you would just click on "Submit" button; you don't need to click on the "Edit" button, because the info popup displays edit controls for unknown tracks by default. Of course, this behavior is enabled, when the respective option is turned on.

> Perhaps it would be even better to implement a whitelist option (and a blacklist if that sounds useful to you). Adding tracks to the whitelist would lead to only those tracks being scrobbled, which is what I need. You could make it so that editing tracks would automatically add them to the whitelist.

I'm not sure if it's worth adding a whitelist, since it can be resolved by using current features.

**Comment by yayuyokitano** [comment]
Added by #3222
