### ISSUE TITLE
Web Scrobbler does not "read" the spotify tracks

### ISSUE THREAD

**Issue by Ernsthemingway** [web-scrobbler/web-scrobbler#2291]
Greetings and thank you very much for your web app Web Scrobbler. Now I want to report a problem. The Web Scrobbler does not want to "recognize" Spotify tracks when it "reads" them, moreover, the screen with the track with its titles is not displayed. So I can't "edit them" so they look like it should be on my last.fm profile ...

**Comment by SydneyNS** [comment]
I am also having the same issue, seems to have happened since the latest FF update.

**Comment by Ernsthemingway** [comment]
What is that of the "FF" ???

**Comment by GoHoo** [comment]
For me, it's not scrobbling at all on spotify.

**Comment by brenofreire** [comment]
It's not working for me as well :/

**Comment by DrakkMike** [comment]
I have the same problem :(

**Comment by phot-da-phuk** [comment]
I think this is being addressed in #2289
