### ISSUE TITLE
Donation button doesn't work

### ISSUE THREAD

**Issue by skywinder** [web-scrobbler/web-scrobbler#2295]
https://github.com/web-scrobbler/web-scrobbler/blob/99e1d4316aff0bd15919aae94b56bfbf1b62ae79/src/ui/options/index.html#L285

link https://www.paypal.com/cgi-bin/webscr redirects to the main page. 

Please help me to donate! 🙌 😉

**Comment by alexesprit** [comment]
Hmm, clicking on the button works fine for me. That URL is not supposed to be opened manually.

**Comment by skywinder** [comment]
So, from the extension setting page, it redirects me to the login window: https://www.paypal.com/

if I'm registered, just to my account: https://www.paypal.com/myaccount/summary

**Comment by alexesprit** [comment]
Yes, Firefox doesn't open the proper URL. It works on Chrome, though.

Unfortunately, I don't know how to fix this. Probably, we can go with PayPal.Me, but this button is bound to the account of the former developer, and I don't even know if he has PayPal.Me account. :)

**Comment by skywinder** [comment]
Ok. Anyway, it would be great to have an option to support you, guys with an awesome project! 
Paypal, bitcoin, patreon - everything works. ;)

cc @inverse

**Comment by skywinder** [comment]
There is also simple service for donations, that integrated into github with "sponsor" button on top: https://ko-fi.com/

**Comment by inverse** [comment]
We could def change things here but we should probably ask the original author @david-sabata too :)

**Comment by david-sabata** [comment]
Go ahead! :+1: 

I haven't contributed to the codebase for a really long time, so it's only fair if you direct the occasional donations elsewhere :wink:
