### ISSUE TITLE
YouTube won't scrobble in Firefox / message unclear

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#2303]
**Describe the bug**
https://www.youtube.com/watch?v=LHv2dIM3t9I doesn't scrobble despite enabling the scrobble options for YouTube. It works in Chrome.

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=LHv2dIM3t9I
2. Press play.
3. Notice Web Scrobbler in Forefox only saying "Play some music to get started. Is it already playing?"

**Expected behavior**
Scrobble like in Chrome.

**Screenshot

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

about:devtools-toolbox?type=extension&id=%7B799c0914-748b-41df-a25c-22d008f9e83f%7D errors and warnings say:

<details>
  <summary>Summary (Click to expand)</summary>

```
Unable to bind Libre.fm scrobble-service.js:48:14
Unable to bind ListenBrainz scrobble-service.js:48:14
Unable to get song info from Last.fm scrobble-service.js:94:14
Error: "Script 'moz-extension://31711db8-faa9-463d-8382-03e7fa5f1bd2/connectors/spotify.js' result is non-structured-clonable data" inject.js:61:13
Error: "Script 'moz-extension://31711db8-faa9-463d-8382-03e7fa5f1bd2/connectors/spotify.js' result is non-structured-clonable data" inject.js:61:13
Error: "Script 'moz-extension://31711db8-faa9-463d-8382-03e7fa5f1bd2/connectors/spotify.js' result is non-structured-clonable data" inject.js:61:13
Use of nsIFile in content process is deprecated. 6 NetUtil.jsm:253:8
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://31711db8-faa9-463d-8382-03e7fa5f1bd2/vendor/md5.min.js
Source Map URL: md5.min.js.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://31711db8-faa9-463d-8382-03e7fa5f1bd2/vendor/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map
```
</details>

But those appear to be old as clearing the log and reloading the YouTube page gives only:

<details>
  <summary>Summary (Click to expand)</summary>

```
Injecting vendor/jquery.min.js inject.js:56:12
Injecting vendor/browser-polyfill.min.js inject.js:56:12
Injecting core/content/util.js inject.js:56:12
Injecting core/content/reactor.js inject.js:56:12
Injecting core/content/filter.js inject.js:56:12
Injecting core/content/connector.js inject.js:56:12
Injecting connectors/youtube.js inject.js:56:12
Injecting core/content/starter.js inject.js:56:12
Tab 122: Remove controller for YouTube connector extension.js:337:12
Tab 122: Created controller for YouTube connector
```
</details>

**Environment (please complete the following information)**
-   OS: Ubuntu 19.10
-   Browser: Firefox 74.0 (64-bit)
-   Extension version: 2.28.5

**Comment by alexesprit** [comment]
It's in "Gaming" category. Make sure you allowed to scrobble from this category:

![image](https://user-images.githubusercontent.com/1119267/76788055-44e37200-67cb-11ea-9d08-59c63c54c13e.png)

**Comment by CTimmerman** [comment]
Unchecking both scrobble options (filters) worked. Thanks! The icon's message could be better.

**Comment by alexesprit** [comment]
I think this could be resolved by skipping excluded tracks like we skip podcasts if they're disallowed. In this case users will see the video is recognized, but is blocked due to some reasons.

Ref https://github.com/web-scrobbler/web-scrobbler/issues/1769#issuecomment-623089511.

**Comment by ricki-k** [comment]
Hi. I'm having this same trouble. I would prefer not to enable the "Scrobble videos from entertainment category" options because it leads to me having a bunch of scrobbles from random YouTubers. I have "Force Track Recognition" on, but there are still some videos that do not allow me to scrobble them, for example, [this video](https://www.youtube.com/watch?v=sn3cHUtNZKo).

I would like to be able to whitelist certain videos and have them scrobble from that point forward, even if they aren't in the "Music" category

**Comment by yayuyokitano** [comment]
I think this can be considered solved by the new controller state, though I think I still have some plans to improve it to be more specific.
