### ISSUE TITLE
shuffle.one support

### ISSUE THREAD

**Issue by martouss** [web-scrobbler/web-scrobbler#2307]
I wonder if you can add [shuffle.one](https://shuffle.one), an Iranian web-based streaming service to your extension support?

**Comment by inverse** [comment]
We should be able to support it. Might be a bit of a problem calculating duration correctly but we can get round that.

**Comment by martouss** [comment]
`> We should be able to support it. Might be a bit of a problem calculating duration correctly but we can get round that.`

thanks for your quick reply.

**Comment by inverse** [comment]
Will be in the next release!
