### ISSUE TITLE
Mixcloud not scrobbling

### ISSUE THREAD

**Issue by Mihkach** [web-scrobbler/web-scrobbler#2310]
Tried to scrobble Mixloud e.ghttps://www.mixcloud.com/ and getting the "play some music" prompt even though the API does tell you which track is playing.

How to reproduce:

1. Open https://www.mixcloud.com/ 
2. Wait for the non-existent scrobbling to begin.

**Comment by alexesprit** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/1119267/77218639-79925900-6b3e-11ea-938c-fb06e6b40a73.png)

Mixcloud doesn't display track info for some tracks, so they cannot be scrobbled.

Where did you find Mixcloud API, by the way?

**Comment by Mihkach** [comment]
Sorry, it was a temporary problem. It's working now.
