### ISSUE TITLE
Youtube are not scrobling

### ISSUE THREAD

**Issue by AnnaSt777** [web-scrobbler/web-scrobbler#2323]
Scrobblings for last.fm are not working on youtube ( i were trying a lot of scrobblers)
Web Scrobbler
Last.fm scrobbler youtube canary
last.fm scrobbler for Youtube
I were trying all of that, it's not working
**Environment 
-   OS:Windows 10
-   Browser: Chrome

Service error from Web Scrobbler text:
Looks like something went wrong while scrobbling the music. Please open the options page and try to reauthenticate with services. If reauthentication doesn't help, and you still see this message, please create a new issue at the GitHub project page.

**Comment by jaccarmac** [comment]
Did you reauthenticate? I can't duplicate.

**Comment by AnnaSt777** [comment]
Hey, i were trying to fix that more then one day, also i were try different
aps.
Now i solve this problem by reinstallation the Web Scrobbler. After total
deleting and installing this again it looks like it works! So thank you
But i think all of another scrobbles didnt work for me

thank you have a nice day

pá 27. 3. 2020 v 3:14 odesílatel Jacob MacDonald <notifications@github.com>
napsal:
