### ISSUE TITLE
Export MetadataFilter into an NPM package

### ISSUE THREAD

**Issue by FOSSforlife** [web-scrobbler/web-scrobbler#2324]
**Is your feature request related to a problem? Please describe.**
Not a problem with this extension. I love the work that you've done with the MetadataFilter and would like to use this code in my project. I could download the filter.js file and use that (which I've done so far and it works great), but then I'd have to redownload it if any updates are made.

**Describe the solution you'd like**
I've created a git repo where I will attempt to modularize this file into an NPM package. I will also make some adjustments to improve the developer experience of working with it (adding TypeScript types, unit tests, possibly some refactoring if needed). Once this work is done, I can hand it over to the maintainers of this project if you'd like to retain control of it and manage publishing to the NPM registry. I'll also make a PR to this project so it uses the NPM package instead of the local file.

**Describe alternatives you've considered**
The alternative is to continuously pull the filter.js file from GitHub, which is not as efficient or stable.

**Additional context**
Nothing I can think of. Feel free to ask questions if needed.

**Comment by alexesprit** [comment]
I like this idea, and I'm in as long, as it works fine for this project.

> From **patricianapp/metadata-filter#readme.md**:
> My expectation is that, once I've made a PR to the Web Scrobbler to have their extension use this NPM package instead of the filter.js file, they will likely want to maintain this repository as well (since it's their code). I'm happy to hand control over to them, but I'd also be happy maintaining it inside this forked repo as well, if that would be helpful to them. That decision is completely up to the maintainers of Web Scrobbler.

This also could be done via adding the repo to this organization, and providing you a write access to the `metadata-filter` repository, so we both can contribute.

What do you think?

**Comment by FOSSforlife** [comment]
That would be perfect! Thanks for the quick response.

**Comment by FOSSforlife** [comment]
I'll update it with a proper readme and then you can clone it and upload it to this organization.

**Comment by alexesprit** [comment]
@FOSSforlife I'm currently making a repo with all base configs and tests, and will publish it soon. :)

**Comment by alexesprit** [comment]
I will publish it after we prepare the module for publishing. For now it's missing a basic readme file.

I suggest to contribute via PRs (I will too) to allow other members review proposed changes.

**Comment by FOSSforlife** [comment]
Great! I will get a readme written with some documentation in it. The tests look really good! Is there anything else needed before we can publish?

**Comment by alexesprit** [comment]
No, I think we have everything to publish an initial version.

**Comment by inverse** [comment]
@alexesprit would the next steps be to depend on this lib internally? We'll also need to update 3rd party deps if so.

**Comment by alexesprit** [comment]
@inverse sure, but after it's published.

**Comment by inverse** [comment]
Nice :+1: Thanks for getting this done so quickly! I wonder what else could eventually be extracted and all.

**Comment by alexesprit** [comment]
https://www.npmjs.com/package/metadata-filter
