### ISSUE TITLE
Spotify not scrobbling both on app and on web player

### ISSUE THREAD

**Issue by marioxgarofano** [web-scrobbler/web-scrobbler#2334]
Spotify has not been scrobbling any tracks for more than 24 hours now, both on the app and on the web scrobbler. The icon of the scrobbler extension is not red, but yellow, indicating an issue. 
When I go to the scrobbler's settings to check, spotify is still listed as an app/site that should scrobble tracks. 
Am I the only one facing this issue?

-   OS: Windows
-   Browser: Chrome

**Comment by alexesprit** [comment]
The yellow icon often means Last.fm/authentication issues. Please try to reauthenticate.

**Comment by inverse** [comment]
Also if it's not working on the app that would imply a deeper issue with last.fm itself.

**Comment by inverse** [comment]
Scrobbling is working natively from the app. 

@marioxgarofano is this still an issue?

**Comment by marioxgarofano** [comment]
Yes it is still an issue and I just realised it's not only Spotify but
bandcamp and youtube also. Not scrobbling on my phone too.

**Comment by inverse** [comment]
Sounds like an issue with the authentication like @alexesprit mentioned. 

Did you try and reuth through the options?

**Comment by marioxgarofano** [comment]
Yes I did. Tonight it's working again fine, I can't understand what could
have possibly changed since I didn't do anything else to make it work.
Anyways thank you all for your time and help. Glad it's been resolved!

Στις Κυρ, 29 Μαρ 2020 στις 11:07 μ.μ., ο/η Malachi Soord <
notifications@github.com> έγραψε:
