### ISSUE TITLE
Yandex Music doesn't scrobble

### ISSUE THREAD

**Issue by jelsomina** [web-scrobbler/web-scrobbler#2336]
Describe the bug:
The music service Yandex Music stopped scrobbling tracks via Web Scrobbler extension. A notification shows an extension service error. Reauthorization didn't help.

1. Go to https://music.yandex.ru/home
2. Click on any track to play.
3. Take a look at the Web Scrobbler button.
4. The button is yellow and shows the service error.

Expected behavior:
Normally the Web Scrobbler button is red and you can see a pop-up window with the recognition of the track.

Screenshots:
![Снимок экрана 2020-03-31 в 13 12 45](https://user-images.githubusercontent.com/62935439/78014997-61e27e00-7351-11ea-9fdd-f455d1e75a62.png)

Debug logs:
core/background/storage/wrapper.js:68 storage.Core = {
  "appVersion": "2.29.0"
}
core/background/storage/wrapper.js:68 storage.Notifications = {}
scrobble-service.js:48 Unable to bind Last.fm
bindAllScrobblers @ scrobble-service.js:48
scrobble-service.js:48 Unable to bind Libre.fm
bindAllScrobblers @ scrobble-service.js:48
scrobble-service.js:48 Unable to bind ListenBrainz
bindAllScrobblers @ scrobble-service.js:48
extension.js:470 No scrobblers are bound

Environment:
-   OS: Mac
-   Browser: Chrome
-   Extension version: v2.29.0

**Comment by alexesprit** [comment]
See https://github.com/web-scrobbler/web-scrobbler/issues/2334#issuecomment-605642208.
