### ISSUE TITLE
Bandcamp Daily connector newly broken.

### ISSUE THREAD

**Issue by jaccarmac** [web-scrobbler/web-scrobbler#2339]
I just pulled down about 50 commits from master. Haven't bisected them yet, but somewhere along the way the Bandcamp Daily connector broke. It looks to be a connector ordering issue, as moving the `bandcamp-embed` connector definition earlier in `src/core/connectors.js` fixes the problem.

**Comment by jaccarmac** [comment]
Yep, looks like a combination of d61ec9078f79527449d30d098d346f93fbf0a6a0 and aa5ba3c79120c6850a59f8c4e7802bfe3dbc626f. Is `allFrames` intended to be the way that the embed connector gets fired on BC Daily pages? I'm not particularly familiar with the injection implementation, but https://github.com/web-scrobbler/web-scrobbler/blob/9f2b59380e5732561b714bd6cea2e6c9c90061b5/src/core/background/browser/inject.js#L50 seemed interesting.

**Comment by alexesprit** [comment]
@jaccarmac yes, it's because of ordering.
