### ISSUE TITLE
Scrobbling wrong names

### ISSUE THREAD

**Issue by Sharvyn** [web-scrobbler/web-scrobbler#2345]
https://www.youtube.com/watch?v=4iCclRWEBQc&t=1s
https://www.youtube.com/watch?v=lJySmeYWdeg
https://www.youtube.com/watch?v=Mi8UlFYjuD4

Open these videos and look at title of the scrobble in the chrome extension. I guess, I don't have explain the issue further.

Please do allow an option to ignore the " - ", " : " or " | " when scrobbling.

**Comment by alexesprit** [comment]
> Please do allow an option to ignore the " - ", " : " or " | " when scrobbling.

This won't help to resolve the issue. The extension uses a channel name, if it's failed to split a video title.
