### ISSUE TITLE
SNDTST is not recognized as a supported site

### ISSUE THREAD

**Issue by edelstone** [web-scrobbler/web-scrobbler#2347]
**Describe the bug**
Looks like SNDTST - [https://sndtst.com/](https://sndtst.com/) - isn't being supported although it was [implemented a while back](https://github.com/web-scrobbler/web-scrobbler/pull/743)

**How to reproduce**
1. Ensure that SNDTST is enabled in scrobbling preferences.
1. Go to an album page like '[https://sndtst.com/Blazing_Lazers/index.html](https://sndtst.com/Blazing_Lazers/index.html)' and play a song.
1. See extension window indicate site is not supported

**Expected behavior**
Expected site to be recognized and songs to scrobble

**Screenshots**
<img width="213" alt="Screen Shot 2020-04-06 at 8 53 18 AM" src="https://user-images.githubusercontent.com/8269046/78566437-d2bbe700-77e4-11ea-96f6-64b0f06eceea.png">
<img width="1301" alt="Screen Shot 2020-04-06 at 8 53 38 AM" src="https://user-images.githubusercontent.com/8269046/78566429-d0f22380-77e4-11ea-8d17-728212c8dae1.png">

**Debug logs**
<details>
<summary>Debug logs</summary>
core/background/storage/wrapper.js:68 storage.Options = {
  "disableGa": true,
  "disabledConnectors": "[hidden]",
  "forceRecognize": false,
  "scrobblePercent": 50,
  "scrobblePodcasts": false,
  "useNotifications": false,
  "useUnrecognizedSongNotifications": false
}
core/background/storage/wrapper.js:68 storage.ListenBrainz = {
  "isAuthStarted": true
}
core/background/storage/wrapper.js:68 storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "*******"
}
core/background/storage/wrapper.js:68 storage.LibreFM = {}
core/background/storage/wrapper.js:68 storage.Connectors = {
  "Tidal": {
    "useShortTrackNames": false
  },
  "YouTube": {
    "scrobbleEntertainmentOnly": false,
    "scrobbleMusicOnly": false
  }
}
core/background/storage/wrapper.js:68 storage.Core = {
  "appVersion": "2.29.0"
}
core/background/storage/wrapper.js:68 storage.Notifications = {}
core/background/object/scrobble-service.js:62 Bind Last.fm scrobbler
core/background/object/scrobble-service.js:48 Unable to bind Libre.fm
bindAllScrobblers @ core/background/object/scrobble-service.js:48
core/background/util/util.js:158 ListenBrainz: Use https://listenbrainz.org/profile/
core/background/util/util.js:158 ListenBrainz: Use https://listenbrainz.org/login/musicbrainz?next=%2Fprofile%2F
core/background/util/util.js:158 ListenBrainz: Failed to get session
debugLog @ core/background/util/util.js:158
core/background/object/scrobble-service.js:48 Unable to bind ListenBrainz
bindAllScrobblers @ core/background/object/scrobble-service.js:48
</details>

**Environment (please complete the following information)**
-   OS: Macbook Pro running 10.15.4
-   Browser: Chrome Version 80.0.3987.149 (Official Build) (64-bit)
-   Extension version: 2.29.0

**Additional context**
N/A

**Comment by alexesprit** [comment]
@edelstone Hi! Thanks for reporting.

There was an issue with a URL pattern for this website that prevented the extension to recognize it. I've already fixed the issue, and a new version of the extension will detect the website.

**Comment by alexesprit** [comment]
As a temporary solution you can add a custom URL pattern for the SNDTST connector via a "gear" button near a connector label.

Here is the URL pattern for the SNDTST: `*://sndtst.com/*`
