### ISSUE TITLE
Bandcamp pages with custom domains are not getting scrobbled

### ISSUE THREAD

**Issue by Atakku** [web-scrobbler/web-scrobbler#2349]
**Describe the bug**
Bandcamp pages with custom domains are not scrobbled.

**How to reproduce**
1. Go to https://music.disasterpeace.com
2. Play some music
4. See that it doesn't scrobble

**Expected behavior**
The scrobbler should scrobble it like any other bandcamp album

**Environment (please complete the following information)**
-   OS: Arch Linux
-   Browser: Firefox
-   Extension version: v2.29.0

**Additional context**
Should be an easy fixed by making the scrobbler check if the domain cname points to bandcamp

**Comment by alexesprit** [comment]
Duplicate of #334 and #1882.

A temporary solution: https://github.com/web-scrobbler/web-scrobbler/issues/334#issuecomment-62688246.
