### ISSUE TITLE
Please add support for audius.co

### ISSUE THREAD

**Issue by quentincaffeino** [web-scrobbler/web-scrobbler#2350]
**Provide information about website**
Audius is a decentralized, community-owned audio sharing protocol.
[audius.co](https://audius.co)

**Additional context**
A free trial is available at [audius.co/trending](https://audius.co/trending)

**Comment by corrupteddrive** [comment]
When is the feature going to be added?

**Comment by quentincaffeino** [comment]
Devs of my favorite distro have a saying: it will be out when it's ready.
If it would be in development it would be told so here, as you can see, no plans on it currently.

**Comment by inverse** [comment]
We happy accept contributions to the project so feel free to implement it if you want it done quicker.

**Comment by fckawe** [comment]
Just had a look on the free trial. Shouldn't be very difficult to find the right selectors... but!...: The info that is given within the artist and the title element doesn't seem to be consistent.

For Example:

![image](https://user-images.githubusercontent.com/1059389/157911427-195e2bea-8c73-4a12-8804-b122dda6ca1f.png)

The first entry has "Quality Good Records" as artist and "sebjin - Ring feat. MARS 88". So the title also contains the actual artist. The third entry follows the same rules, I think.
In the second entry, though, the title element contains the title only and the artist can be found in the artist element.

I have no idea how both types of entries could be distinguished by the connector...
