### ISSUE TITLE
Tracks scrobbled twice on Spotify

### ISSUE THREAD

**Issue by ivanprfbs** [web-scrobbler/web-scrobbler#2361]

**Comment by alexesprit** [comment]
Can't reproduce.

**Comment by duttaditya18** [comment]
You might have turned on Spotify scrobbling on last.fm [here](https://www.last.fm/settings/applications). You have two scrobbles (one from web-scrobbler and one from last.fm's scrobbler

**Comment by phmarqui** [comment]
I see occasional doubles from Google Play Music, but it doesn't seem to have any pattern. Some are double, some are not. e.g. my [last.fm](https://www.last.fm/user/djgrandmarquis/library?date_preset=LAST_7_DAYS)

**Comment by alexesprit** [comment]
@phmarqui it's a known issue for Google Play Music, and it cannot be fixed so far, unfortunately.

GPM doesn't update a player element if the website is inactive, so the extension could not get track duration properly. That leads to double scrobbles sometimes.

**Comment by CennoxX** [comment]
If we can't find out on GPM, if a track has been scrobbled multiple times, could we still fix the issue by accessing the last scrobbled track on last.fm/etc.?

**Comment by alexesprit** [comment]
If we even could access the last scrobbled track from Last.fm, what do you suggest to do with it?

**Comment by CennoxX** [comment]
Before scrobbling a track, check that it is not the same as the last track in the last 5 minutes ([user.getRecentTracks](https://www.last.fm/api/show/user.getRecentTracks), with params like `from`) or so.
