### ISSUE TITLE
Srobble embedded players

### ISSUE THREAD

**Issue by Stuffedbird** [web-scrobbler/web-scrobbler#2364]
I use sites like Pitchfork.com and the theQuietus.com to discover new music. Tracks from embedded players don't seem to scrobble. They mostly use soundcloud, bandcamp & youtube. I would like to be able to scrobble tracks from the mentioned embedded players. I use Firefox browser on PC. 

Examples: 
SC-embed: https://pitchfork.com/reviews/albums/bladee-exeter/
YT-embed: https://thequietus.com/articles/28104-melt-yourself-down-100-yes-review
BC-embed: https://thequietus.com/articles/28076-hilary-woods-birthmarks-review

1. Is this possible? 
2. If so, how, cause I can't seem to figure it 
3. If no, could this possibly be added? 

Help would be appreciated, but in any case, thank you very much for making the scrobbler. It's a beauty!

**Comment by alexesprit** [comment]
Unfortunately, there's no way to do it automatically.

But we have "bandcamp-embed" and "youtube-embed" connectors which could work on any website. As a workaround, you can add custom URL patterns for The Quetus to Discogs (which utilizes "youtube-embed"), and for Bandcamp Embed (which uses "bandcamp-embed" connectors).
![image](https://user-images.githubusercontent.com/1119267/79637363-a9596e80-8187-11ea-971c-9044163aff0a.png)

Yes, this is weird solution, but it should work.

I'm closing this one, as it's already suggested in other issues.
