### ISSUE TITLE
YouTube scrobbling category bug

### ISSUE THREAD

**Issue by dannyisokay** [web-scrobbler/web-scrobbler#2369]
**Describe the bug**
I have set to only scrobble uploads from the Music category, but whenever I watch a video with an other category like Gaming, it recognizes and scrobbles even though I have set it to only scrobble the Music category.

**Expected behavior**
Whenever I click on a video from any other category than Music it shouldn't recognize and scrobble it.

**Environment (please complete the following information)**
-   OS: Windows 10 OS Version 1909 (Build 18363.778)
-   Browser: Vivaldi 2.11.1811.52 (Stable channel) (64-bit)
-   Extension version: 2.30.6

**Comment by alexesprit** [comment]
@dannyisokay Hi! Could you check if a video category is present in the video description? See https://github.com/web-scrobbler/web-scrobbler/issues/2368#issuecomment-616157298 for details.

**Comment by dannyisokay** [comment]
![image](https://user-images.githubusercontent.com/63978169/79700446-e2800480-8295-11ea-8e38-4363b4fc7038.png)
Yes, it is present.

**Comment by alexesprit** [comment]
Did it worked correctly on v2.30.5?

**Comment by dannyisokay** [comment]
I don't pay attention to this extension's version history but I am getting this like 4 hours after the last update was released. Worked fine before

**Comment by alexesprit** [comment]
Could you install the extension from this zip? [web-scrobbler.zip](https://github.com/web-scrobbler/web-scrobbler/files/4500424/web-scrobbler.zip)

This version contains an additional debug output for YouTube, plus, some attempts to fix the issue.

If this version still does not work, please collect logs using [this][1] howto. I need logs of content scripts only (see the respective section in that howto for details). Note that you should play a video first, then collect logs.

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-content-scripts

**Comment by alexesprit** [comment]
@dannyisokay seems like I found out why it happens. You were right, this happens for Gaming category, which was ignored recently. :)

**Comment by alexesprit** [comment]
Should be fixed in v2.30.7.

**Comment by flatulation** [comment]
I was going to file an issue on this but was struggling to debug the extension, the new update makes it go from scrobbling nothing, to scrobbling every video

**Comment by alexesprit** [comment]
@flatulation Make sure a video category is present in the video description. See #2368 (comment) for details.
