### ISSUE TITLE
Support for YouTube video chapters

### ISSUE THREAD

**Issue by WhiteAls** [web-scrobbler/web-scrobbler#2371]
[YouTube is rolling out video chapters](https://youtu.be/BvyQ70PVI4s?t=105). It can be useful to determine individual tracks in mixes.
Example video https://www.youtube.com/watch?v=eYLbteOm42k
![image](https://user-images.githubusercontent.com/1255404/79795055-03ab2880-835c-11ea-8d9e-be3524df74b1.png)

**Comment by alexesprit** [comment]
It can't be used, as these chapters aren't updated, if a YouTube player bar is hidden (and it almost always is hidden).

**Comment by WhiteAls** [comment]
I just checked it myself, it seems YouTube uses timestamps included in video description. Can't we just parse and use them too?

**Comment by alexesprit** [comment]
Yes, we can, but it's not an easy task. This was already suggested in #122.

**Comment by alexesprit** [comment]
I have a working prototype, where a couple of timestamp types are supported, so it isn't supposed to work everywhere. https://github.com/web-scrobbler/web-scrobbler/tree/feature/yt-playlists You can install it from sources, if you want.

**Comment by alexesprit** [comment]
Closing as "won't fix" as chapters cannot be used. :( Will add them, if it will be possible to use them.

**Comment by alexesprit** [comment]
@WhiteAls I added support for MediaSession API in v2.31.0. This API is used to provide track metadata for external applications; e.g. Chrome-browser browsers use them for displaying now playing tracks in a popup window.

![image](https://user-images.githubusercontent.com/1119267/81472935-ccfe5a80-9203-11ea-8e7f-1c0c0ae51360.png)

Unfortunately, the MediaSession API does not provide chapters info. If you use any Chrome-based browser, and you notice it's changed (you'll see a correct artist name/a track title in that popup window), please let me know.

**Comment by alexesprit** [comment]
Seems like they changed something on YouTube, and now YouTube refreshes the chapter element even if the player bar is hidden (at least for me).

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/89096284-2ed2f880-d3de-11ea-9eb0-4953541b8f22.png)

**Comment by BasedDrainer** [comment]
How do I use this feature, is there a setting?
