### ISSUE TITLE
Youtube scrobbling "Education" category

### ISSUE THREAD

**Issue by rxmntk** [web-scrobbler/web-scrobbler#2376]
**Describe the bug**

Web Scrobbler is scrobbling videos in the "education" category of youtube when I have the option to only scrobble "music" selected.

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=yS53AA_WaUk&list=UUZYTClx2T1of7BRZ86-8fow&index=1675
2. Web scrobbler will identify the track and scrobble it.

**Expected behavior**
I didn't expect SciShow to scrobble. I've watcjed over 1500 videos on this channel now, all in the "education" category and scrobbling has only happened in the last ten or so videos.

![image](https://user-images.githubusercontent.com/64075074/79856165-16873100-8420-11ea-9e3d-aad8897ac4d5.png)

**Environment (please complete the following information)**
-   OS: Win10
-   Browser: Chrome
-   Extension version: v2.30.7

**Comment by alexesprit** [comment]
Thanks for reporting! Will be fixed in v2.30.8.
