### ISSUE TITLE
Web Scrobbler doesn't scrobble from YouTube in Firefox.

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#2378]
It asked me to reauthenticate, and I did. But, it still doesn't work.

![2020-04-22 17_09_59-Greenshot](https://user-images.githubusercontent.com/46681247/79977815-7cc19180-84bc-11ea-9378-5a958442cead.png)

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by maturanomx** [comment]
Same error. I just logout and reconnect the extension.

**Comment by alexesprit** [comment]
The yellow icon means Last.fm issues in most cases.
