### ISSUE TITLE
Won't Scrobble on YouTube anymore (Chrome Engine / Brave Browser) / Logs Included

### ISSUE THREAD

**Issue by gothboiclique** [web-scrobbler/web-scrobbler#2379]
**Describe the bug**
The bug is no longer scrobbling on YouTube.

**How to reproduce**
1) Open a video

**Expected behavior**
The video to be scrobbled and added to LastFm.

**Screenshots**
https://i.gyazo.com/92cb0238dd4cb71140c2bd48a63313ac.jpg
https://i.gyazo.com/8d84ef8ef51c5e2e0c2f1530650f52ad.png

**Debug logs**
https://i.gyazo.com/c4e1a0cca4bb993848be213e0f2a6164.png

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Brave (Runs on Chrome Engine)
-   Extension version: 2.30.8

**Additional context**
This works flawlessly 99.99999% of the time and I have been using this for over 1-2 years. Thank you for all your hard work.

**Comment by alexesprit** [comment]
Have you any extensions/userscripts installed that change YouTube interface?

**Comment by gothboiclique** [comment]
I have TamperMonkey but there are no scripts running and it has never interfered with it before. I think its because I am using the old version of YouTube because I hate the new version.

I tested on the newer version of YouTube and the Scrobbler works perfect. I'm sorry for wasting your time.

**Comment by gothboiclique** [comment]
<img src="https://i.gyazo.com/840599299c0231459411d6f287d2d9d7.jpg">
