### ISSUE TITLE
Add a custom/local scrobbler 'account'.

### ISSUE THREAD

**Issue by aero31aero** [web-scrobbler/web-scrobbler#2380]
**Is your feature request related to a problem? Please describe.**
Usecase: show a system wide now-playing notification or desktop widget.

I have a statusbar script on linux that works with my local players, cmus and clementine. Now, I wanna show the current playing track from YT Music/Spotify in my taskbar, for which I need a way to get the status info out of the browser.

**Describe the solution you'd like**
Add a new 'account' that allows us to specify a POST URL where web-scrobbler just sends a POST request with JSON data, or a similar easy to parse format.

**Describe alternatives you've considered**
I've considered writing my own extension for this data, but it feels like a natural fit for this scrobbler, even though I'd probably not get the playtime or remaining time information.

I've also considered reading this data from last.fm but that again requires setting up an app with their API.

**Comment by alexesprit** [comment]
I think this feature is suitable for [this][ext] extension, where you can add an adapter that will allow you to send data to 3rd-party apps.

[ext]: https://github.com/f1u77y/web-media-controller

**Comment by aero31aero** [comment]
Ah, thanks for pointing to that. I don't see any docs for writing a new adapter so I'll try something up myself.

Is it okay if I keep this issue open in case I need to ping for help?

**Comment by aero31aero** [comment]
Closing, this is supported already by wmc-mpris (along with playerctl). Thanks for pointing me in the right direction.
