### ISSUE TITLE
track.updateNowPlaying ("Scrobbling now") isn't implemented correctly?

### ISSUE THREAD

**Issue by RudeySH** [web-scrobbler/web-scrobbler#2381]
When Web Scrobbler scrobbles a track after listening half of it, Last.fm starts displaying the track twice on my profile. The track appears to be both scrobbled and "Scrobbling now". After the track finishes, the track fortunately won't be scrobbled twice. I've seen this happening with both the YouTube and bandcamp connecter, I assume it happens for every connector.

![image](https://user-images.githubusercontent.com/3918757/80256827-d58d5780-867f-11ea-8826-f8a942808aa3.png)

This doesn't happen when scrobbling using the official Spotify connection, so it's probably Web Scrobbler's fault. I checked the code and wasn't able to figure out what's wrong though.

My current theory is that Web Scrobbler doesn't send the correct (or enough) metadata when calling `track.updateNowPlaying`, causing Last.fm to think the "Scrobbling now" track is not the same track that gets scrobbled soon after. Any ideas?

**Comment by RudeySH** [comment]
Sometimes Last.fm displays the "Scrobbling now" track below the latest scrobble. Strange.

![image](https://user-images.githubusercontent.com/3918757/80258871-957ca380-8684-11ea-93e0-5c8e1f570742.png)

**Comment by alexesprit** [comment]
1. `updateNowPlaying` request is used, when a track starts playing. The extension uses song duration from website, if it's available, or from Last.fm as a parameter of this request.

2. `scrobble` request is used, when a track reaches 50% or 240 seconds of the song duration, as it's recommended in official API.

What's wrong here?

**Comment by RudeySH** [comment]
Not sure, but somehow Last.fm doesn't understand that the same track from `updateNowPlaying` is still playing when the `scrobble` request happens, causing it to display weirdly like I've shown in the screenshots above.

**Comment by alexesprit** [comment]
Other scrobblers send `scrobble` request when a track is finished.

**Comment by RudeySH** [comment]
Huh, it seems you're right. I just tried Spotify scrobbling again, and indeed it doesn't scrobble the track until the track stops playing after reaching at least 50% or 240 seconds.

I guess it's a Last.fm issue after all. I'll see if I can open an issue about it on their forum.

**Comment by alexesprit** [comment]
Noticed Last.fm uses the same algorithm, as this extension does, to scrobble music via YouTube.
<details>
  <summary>Summary (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/80304068-8e58b100-87bc-11ea-8379-241e3d1ff16b.png)
</details>
