### ISSUE TITLE
Support for Youtube videos within Last.fm pages

### ISSUE THREAD

**Issue by AndreGoldvasser** [web-scrobbler/web-scrobbler#2384]
**First of all, thanks to all contributors on this project. It's been really useful for me for so long.**

I would like to know if it is viable to scrobble from Youtube videos within Last.fm pages.
I know it's possible in Discogs, so therefore the same on Last.fm would be nice.

Have a good day to you all,
André

**Comment by alexesprit** [comment]
Last.fm scrobbles music from their website for themselves.

![image](https://user-images.githubusercontent.com/1119267/80303811-32415d00-87bb-11ea-905c-6919856a2138.png)
![image](https://user-images.githubusercontent.com/1119267/80303813-366d7a80-87bb-11ea-97e5-79ecf6408dd4.png)

**Comment by AndreGoldvasser** [comment]
Oh god, I'm sorry, I never ever noticed that.
Thanks and sorry for the trouble.
Once again, thank you so much for the extension.
