### ISSUE TITLE
WFMU Audio Player not working

### ISSUE THREAD

**Issue by rcase128** [web-scrobbler/web-scrobbler#2396]
The WFMU Audio Player is no longer scrobbling. The WFMU audio player used to be hosted on their own site but now it is on a radiorethink.com url. The archive player still works.

1. Go to http://www.radiorethink.com/tuner/?stationCode=wfmu&stream=hi&launchedFrom=chromeMessage or go to wfmu.org and click the large 'play' icon.
2. Play station in popup.
3. See the website is not supported.

Windows Chrome, extention version v2.31.0

**Comment by alexesprit** [comment]
I will remove support for a former WFMU player in `wfmu` connector, and will add a new `radiorethink` connector which will be used for WFMU streams as well as for other radio stations hosted on Radio Rethink.
