### ISSUE TITLE
therock.nz

### ISSUE THREAD

**Issue by Jbenci** [web-scrobbler/web-scrobbler#2400]
Im unable to scrobble music from https://www.therock.net.nz/home.player.html though it says its a supported website. Is there anything I can try?

**Comment by alexesprit** [comment]
It says it's not supported for me (and this is expected). Could you post debug logs? 
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by Jbenci** [comment]
Ive just realised there is more than one rockFM. I was attempting therock.net.nz which isnt actually supported. Perhaps a furture release can support it. Thanks and good day.

**Comment by alexesprit** [comment]
Closed as a duplicate of #1931.
