### ISSUE TITLE
invidio.us

### ISSUE THREAD

**Issue by harcesz** [web-scrobbler/web-scrobbler#2402]
invidio.us is a proxy service for youtube, particularly useful on very slow hardware, still it would be nice to be able to scrobble from it.

**Comment by alexesprit** [comment]
It's already supported, isn't it?
![image](https://user-images.githubusercontent.com/1119267/82096851-69e05c80-970a-11ea-9e3a-a6bd538122e5.png)

**Comment by alexesprit** [comment]
I think I know why it's not supported for you. The extension doesn't recognize Invidoius, if the website URL is prefixed with "www". I will fix it.
