### ISSUE TITLE
Scrobbles missing

### ISSUE THREAD

**Issue by Guigas13** [web-scrobbler/web-scrobbler#2404]
I use Youtube Music on Google Chrome and some scrobbles are missing. Some songs play enterely and don't scrobble or show the recognized scrobble icon.
In the log below, the songs Fetish by Selena Gomez and Capital Letters by Hailee Steinfeld didn't scrobble, but the others did.

Dubug log:
https://pastebin.com/BVtx0fSh

-   OS: Windows 7
-   Browser: Google Chrome
-   Extension version: 2.31.0

**Comment by alexesprit** [comment]
```
util.js:40 Tab 2: New song detected: {
  "track": "Fetish (feat. Gucci Mane)",
  "artist": "Selena Gomez",
  "album": null,
  "albumArtist": null,
  "uniqueID": null,
  "duration": 16,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://i.ytimg.com/vi/STO4-8vkG0U/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs",
  "isPodcast": false
}
...
util.js:40 Tab 2: The song is too short to scrobble
```
Could you post a link to this song?

**Comment by alexesprit** [comment]
I used a video ID from track art URL to find this video. That's odd the extension parsed duration as 16 seconds.

Could you post a screenshot of your YouTube Music page with that song? Maybe you have something different on the page.

**Comment by Guigas13** [comment]
Here's the print

![IMG-20200516-WA0000](https://user-images.githubusercontent.com/65452826/82123121-0720ac80-976e-11ea-94fc-10d6d0964fe3.jpg)

**Comment by Guigas13** [comment]
Some songs don't do scrobble, but if I put it to play again it does.  I put Fetish to play now on the last song and the scrobble worked.  That always happens with no specific song.

Sending another print and log:

https://pastebin.com/yMt7czAW

![IMG-20200516-WA0001](https://user-images.githubusercontent.com/65452826/82123363-63380080-976f-11ea-869e-cd7bb96ff553.jpg)

**Comment by alexesprit** [comment]
@Guigas13 hmm, it looks the same for me.

I don't know why the extension parses duration incorrectly, so I changed it to get duration directly from a video element. Could you test the extension from this zip? [web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4638596/web-scrobbler-chrome.zip)

https://github.com/web-scrobbler/web-scrobbler/wiki/Install-an-unpacked-extension

**Comment by alexesprit** [comment]
> That always happens with no specific song.

Google Play Music doesn't update time info, if a tab with GPM opened is not active. This could be similar to your issue, since they both are Google services, and probably use the same technologies for their websites.

**Comment by alexesprit** [comment]
According to your latest log, you have this very issue. The update I posted above as a zip file should resolve the issue for you. Please let me know if it's fixed for you or not.

**Comment by Guigas13** [comment]
I left scrobbling for a few hours and all the songs on the playlist were scrobbled. I think the bug has been fixed. Thank you so much!!!

**Comment by alexesprit** [comment]
@Guigas13 nice, thanks for the info! I'm glad it's fixed for you.

I'll publish a patch release with this fix and few others included.

**Comment by alexesprit** [comment]
@Guigas13 Hi!

The change I made to resolve this issue broke scrobbling for some other users (see #2415 for example). I have a possible solution that should resolve both ones.

Could you install this build and try to reproduce the issue again?
[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4684237/web-scrobbler-chrome.zip)

**Comment by Guigas13** [comment]
Hi! I tested it and it looks like everything is normal here, all the songs were scrobbled. No problems found.

**Comment by alexesprit** [comment]
Thanks for the feedback.
