### ISSUE TITLE
Random tracks not scrobbling

### ISSUE THREAD

**Issue by jivison** [web-scrobbler/web-scrobbler#2415]
**Describe the bug**
Sometimes the extension doesn't scrobble my tracks. When this happens, I can see it "now playing" in last.fm, but web scrobbler never commits it (or at least I don't see the green checkmark on the extension, and it doesn't stick around in last.fm). This has been happening for about a week now.

It doesn't appear to be a problem with specific songs (as I can listen to a song, have it not scrobble, then listen to the same song again and have it scrobble)

**How to reproduce**
* Unsure on what's causing this, I haven't found any sort of pattern yet

**Expected behavior**
Every track should scrobble if I listen to it in its entirety 

**Screenshots**
![image](https://user-images.githubusercontent.com/32883726/82607873-80edd700-9b6e-11ea-9cc4-e7c15a5f6607.png)
![image](https://user-images.githubusercontent.com/32883726/82607890-8814e500-9b6e-11ea-878c-6ab0bd929a5c.png)
_last.fm vs. my youtube music history_

**Debug logs**
I can't reliably reproduce this issue

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Chrome _Version 81.0.4044.138 (Official Build) (64-bit)_
-   Extension version: 2.31.2

**Additional context**
I see in the changelog you put out an update to the youtube music connector to fix the problem 5 days ago, and that's about when I've been having this issue, I'm guessing it's related?

I have reinstalled the extension, and logged out and back in again and the problem still persists

**Comment by alexesprit** [comment]
@jivison Hi! Thanks for reporting.

Seems like it's the same problem I tried to fix in v2.31.2. Don't know why it does not fix the issue for you, though.

> I can't reliably reproduce this issue

It should happen when you minimize the browser, or switch to another tab, so the YouTube Music tab becomes inactive. Could you do this and try to reproduce the issue, and copy logs then?

**Comment by alexesprit** [comment]
According to your screenshot you have the same issue described in #2404. The extension haven't scrobbled a shorter track due to invalid duration received from the website ("3:34" received, but "1:27" actually).

If so, this one probably cannot be fixed.

**Comment by jivison** [comment]
@alexesprit 
I managed to grab the logs for one of them: https://pastebin.com/tg8JGYVL
It looks like there are some duration issues going on as I see three different durations from "parsed", "processed", and the last.fm response.

Also I've been using web scrobbler for months without this issue, and never had the issue in #2404 , so I think that fix might've broken it for me

**Comment by alexesprit** [comment]
> so I think that fix might've broken it for me

It probably was something changed in YouTube Music a week ago.

Could you downgrade to v2.31.0 and try to reproduce the issue again?

[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4669967/web-scrobbler-chrome.zip)

**Comment by jivison** [comment]
@alexesprit I've been using that older version for a couple days now and I haven't noticed the same problem

**Comment by jivison** [comment]
I should mention that I did actually see the duration mismatch once when I first downgraded, but
1.The track still scrobbled; and
2. I haven't seen it since then.
It happened quite often before (a couple times a day, and for streaks of tracks in a row).

**Comment by alexesprit** [comment]
I found out the video element on YouTube Music page returns `NaN` when a tab is minimized. Plus, it isn't updated when a tab is maximized, but it should.

Will investigate this.

**Comment by alexesprit** [comment]
@jivison could you install this build and try to reproduce the issue?

[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4681116/web-scrobbler-chrome.zip)

**Comment by jivison** [comment]
@alexesprit
Happened immediately missed 2 of 3 songs I listened to

ALso some weird behaviour I wasn't noticing before: https://pastebin.com/D3yZ0mQD

**Comment by alexesprit** [comment]
@jivison ok, thanks for testing this.

I have another build for you :) Could you check it and tell how it work for you?
[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4684237/web-scrobbler-chrome.zip)

> Also some weird behaviour I wasn't noticing before:

I made a slight change to make the extension to update the duration if it's different to a previous value. But for some reason it's constantly being updated for you, that's why you see a lot of "Update duration" messages. I think it could happen because of video buffering.

It should disappear in this build, but the extension should also update duration every time it differs from a previous value (so there should be no duration mismatch).

**Comment by jivison** [comment]
@alexesprit Looks good to me :) Not seeing the problem anymore, and I don't see the "Update duration" thing for youtube.

**Comment by jivison** [comment]
@alexesprit It broke again :/

https://pastebin.com/yzXfzw0W

**Comment by jivison** [comment]
I think that it was just last.fm having a moment, haven't seen it again

**Comment by alexesprit** [comment]
I'll publish a patch update that fixes this issue in a few hours.
