### ISSUE TITLE
Correct unique ID is not generated in Free Music Archive connector

### ISSUE THREAD

**Issue by eih** [web-scrobbler/web-scrobbler#2417]
**Describe the bug**
Free Music Archive uses numeric IDs for tracks but in [src/connectors/freemusicarchive.js](../tree/master/src/connectors/freemusicarchive.js#L64), a certain class name (`tid-XXXXX`) for the track is returned as the unique ID. The `tid-` bit should be stripped off the returned value for a correct ID.

**How to reproduce**
1. Go to a track page, or to [Süper FM Dub](https://freemusicarchive.org/music/Hayvanlar_Alemi/Visions_of_a_Psychedelic_Ankara/04_Sper_FM_Dub) as an example.
2. Inspect the track row in the table. You can see that the id is appended to `tid-` to use it as a class name:
```
<div class="play-item gcol gid-electronic tid-25638" style="height: 51px;">
```
When you inspect the embed code for the track, you can see that `tid-` is not part of the unique ID but an addition to use id value as a class name:
```
<object width="300" height="50"><param name="movie" value="/swf/trackplayer.swf"/><param name="flashvars" value="track=/services/playlists/embed/track/25638.xml"/><param name="allowscriptaccess" value="sameDomain"/><embed type="application/x-shockwave-flash" src="/swf/trackplayer.swf" width="300" height="50" flashvars="track=/services/playlists/embed/track/25638.xml" allowscriptaccess="sameDomain" /></object>
```

**Expected behavior**
This is not an error but for the sake of correct data, unique ID should be returned without `tid-`.

**Environment (please complete the following information)**
-   OS: macOS 10.14.6
-   Browser: Firefox 76.0.1 (64-bit)
-   Extension version: 2.31.2

I have fixed the issue and will create a PR shortly along with some other improvements.

**Comment by alexesprit** [comment]
Not sure if it's a bug, but changing ID format may lead to other issues like #2403.

**Comment by eih** [comment]
I think this is not a bug but more like a maintenance but I see your point. I thought it would be nice to keep the returned value inline with the FMA's unique ID schema.
