### ISSUE TITLE
Free Music Archive connector can't return correct album on song pages

### ISSUE THREAD

**Issue by eih** [web-scrobbler/web-scrobbler#2418]
**Describe the bug**
Free Music Archive connector can't return correct album on song pages. Currently it returns the song name as album name because the album selector targets the song name in the breadcrumb. See [src/connectors/freemusicarchive.js#98](../tree/master/src/connectors/freemusicarchive.js#L98):
```
Connector.albumSelector = '.bcrumb .txt-drk';
```

**How to reproduce**
1. Go to [a song page](https://freemusicarchive.org/music/Monplaisir/Lack_of_Feedback/Monplaisir_-_Lack_of_Feedback_-_01_Bonsoir)
2. Click play and see in the debugging statements, the song name (Bonsoir) is used as the album name (Lack of Feedback). See the debugging logs below.

**Expected behavior**
In this case, instead of "Bonsoir", "Lack of Feedback" should be returned.

**Debug logs**
<details>
  <summary>Debug log with wrong album name</summary>
  ```
Tab 140: New song detected: {
  "track": "Bonsoir",
  "artist": "Monplaisir",
  "album": "Bonsoir",
  "albumArtist": null,
  "uniqueID": "149055",
  "duration": null,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": null,
  "isPodcast": false,
  "originUrl": "https://freemusicarchive.org/music/Monplaisir/Lack_of_Feedback/Monplaisir_-_Lack_of_Feedback_-_01_Bonsoir"
}
  ```
</details>

**Environment (please complete the following information)**
-   OS: macOS 10.14.6
-   Browser: Firefox 76.0.1 (64-bit)
-   Extension version: 2.31.2

The album title could be returned by selecting the last `a` element in the breadcrumb but in compilation albums, last `a` tag is used for the track artist. Also album names longer than 25 characters are truncated and appended an ellipsis. Extension can't rely on the data from the breadcrumb. I couldn't find any other identifying information for the album in the song page.

My first idea was to get the album URL from the first `lbut`, run an XMLHttpRequest to get the contents of the page, return the album name from the content, but as far as I know base connector expects a selector and we can't set valuse as strings directly. What do you think about this issue and idea? If you have a proposed solution, I can create a PR for this ticket.

**Comment by alexesprit** [comment]
> My first idea was to get the album URL from the first lbut, run an XMLHttpRequest to get the contents of the page, return the album name from the content, but as far as I know base connector expects a selector and we can't set valuse as strings directly.

You can return a string using getters, but they are synchronous. The best solution is to remove an album selector for "song" pages to avoid scrobbling wrong track info.

**Comment by eih** [comment]
Alright, I'll remove album from the song page and create a PR by tomorrow 👍 Thanks.
