### ISSUE TITLE
Automatically change artist name

### ISSUE THREAD

**Issue by RaReMoDz** [web-scrobbler/web-scrobbler#2425]
My problem is that when an artist has two different names, I listen to Lil Peep a lot and his name on Soundcloud is "☆LiL PEEP☆" while his name on Spotify is just Lil Peep. So it's kinda annoying to change his name for all his songs on Soundcloud.

I would like an option where you can change an artist's name for all songs. So for example if I listen to ☆LiL PEEP☆ on Soundcloud I would want a feature that changes this to Lil Peep automatically. This would save a lot of time and a lot of struggle.

So far I've edited the songs manually which takes a lot of time and is kinda annoying. I only took Lil Peep as an example but this has happened with a lot of other artists as well so it would be dope to have such an option.

Thanks.

**Comment by alexesprit** [comment]
@RaReMoDz Hi! Thanks for the suggestion!

This issue and a possible solution was already discussed in #2157, so I close this one as a duplicate.
