### ISSUE TITLE
Duplicate Plays on Plex 

### ISSUE THREAD

**Issue by cancanman** [web-scrobbler/web-scrobbler#2427]
Almost every play on Plex gets tagged at least twice, sometimes more.  Currently the only solution is to manually delete the scrobbles from the Last.fm page.

Plex Web  Version 4.30.2

![image](https://user-images.githubusercontent.com/66024365/83040429-3c9a8500-a00d-11ea-92e8-476107633975.png)

**Comment by alexesprit** [comment]
Can't reproduce. I use Plex mainly, and I never see double scrobbles.

[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by cancanman** [comment]
Error logs posted to pastebin.,

[https://pastebin.com/ZkSHw9Ei](url)

**Comment by alexesprit** [comment]
What song was scrobbled twice, but played once in your log?

**Comment by cancanman** [comment]
> What song was scrobbled twice, but played once in your log?

Every single track.

**Comment by cancanman** [comment]
Item can be closed,  removed all chrome plug ins and re-installed.
Everything scrobbling as normal.

**Comment by alexesprit** [comment]
Glad it's working for you now. :)

**Comment by cancanman** [comment]
Great Plug-In!
