### ISSUE TITLE
New extension icon

### ISSUE THREAD

**Issue by alexesprit** [web-scrobbler/web-scrobbler#2430]
Although the current icon is pretty nice, it has some issues:
- Use of Last.fm "as" symbols
The extension supports Libre.fm, and ListenBrainz as well.
- Use of Chrome-stylized borders
The extension support Firefox, and every browser based on Chromium.
This point was partially fixed by adding a Firefox-stylized icon for Firefox, but the main icon (Chrome version) is used elsewhere (other browsers, a extension website, a social media preview, etc), and it's still an issue.

Again, the current icon is great, but it became outdated a little since the extension is being actively developed.

I'm a bad designer, and I have no idea how the new icon should be look like. Perhaps, we can play with "W" and "S" letters somehow. Suggestions are very welcome!

I know designing is pretty hard, and there're no chances to resolve the issue, but there was a suggestion some time ago (#650, thanks @Paszt!), so I'm giving a try and submitting this one.

The current icons for reference:
![Chrome](https://raw.githubusercontent.com/web-scrobbler/web-scrobbler/master/src/icons/icon_chrome.svg) ![Firefox](https://raw.githubusercontent.com/web-scrobbler/web-scrobbler/master/src/icons/icon_firefox.svg)

**Comment by inverse** [comment]
Yeah - the original one comes from audioscrobbler days :)

While I love the current one, you're right - it's not a true representation of the scope of the extension now.

**Comment by Paszt** [comment]
> Perhaps, we can play with "W" and "S" letters somehow.

I had the same idea and played around a bit a while ago but couldn't come up with anything I really like. Modifying an existing icon was easier (and in hindsight probably shouldn't have been done), but creating a new one is beyond me. I'll attach what I came up with. I'm again without Adobe Illustrator and using Inkscape is just too painful, so I won't be able to do a pull request. But anyone can use the attached files. 

![icon_128](https://user-images.githubusercontent.com/1742693/85909082-1ae81580-b7e6-11ea-9a84-83472229acff.png)  

https://drive.google.com/file/d/1pI5A4vpYuPEAWsVwWmBobhKueOncSjsa/view?usp=sharing

**Comment by alexesprit** [comment]
@Paszt Thanks for the suggestion! The blue one looks nicer IMO. :)

I have Adobe Illustrator... well, that's all I have. If someone have an idea, they could share a sketch scan, and I will try to make an icon/logo from it.

Also, I don't mind if we use a some abstraction symbol instead of "WS" letters.

**Comment by alexesprit** [comment]
Some my ideas (the comment will be probably updated with more icons). The icon colors I used can be changed.

<details>
  <summary>1 (Click to expand)</summary>

![web-scrobbler-1](https://user-images.githubusercontent.com/1119267/89571153-e5e0d100-d82f-11ea-9f3a-3101d93cc3ab.png)
*The idea is a sound wave like the "W" letter. I'm not sure if's already a similar icon.*
</details>
<details>
  <summary>2 (Click to expand)</summary>

![web-scrobbler-2](https://user-images.githubusercontent.com/1119267/89571165-e8dbc180-d82f-11ea-96b6-f22cce533141.png)
*Playing with the "W" letter. Personally, I don't like this one.*
</details>

**Comment by inverse** [comment]
I like the top one more - it feels more in-line with the current one which reflects the good old audioscrobbler days :D

**Comment by Paszt** [comment]
The one that looks like a sound wave is really good.

**Comment by alexesprit** [comment]
Thanks for the feedback, guys.

I played with the first icon more, added a circle version, and added outline for circle icon.

To get the icon color I used https://mycolor.space/. So I was need to get the initial color to generate a color palette to choose the icon color from the palette. Since I plan on using the icon on the new WS website, I generated colors from the website header background, and picked one of them (`#9C7F6B`) and used as the initial color.

https://mycolor.space/?hex=%239C7F6B&sub=1

From that palettes I used some colors I liked. Initially I wanted to get rid of the red color, but `#B8422C` from the palette looks good for me; the green versions also great. What do you think?

<details>
  <summary>Preview (Click to expand)</summary>

![icons](https://user-images.githubusercontent.com/1119267/89704998-0a3cca80-d962-11ea-9b09-473ace71aa30.png)
</details>

Also I want to keep both default and outline version, but I can't choose between inner and outer border.
<details>
  <summary>Outer (2nd) vs Inner (3rd) border (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/89705079-df9f4180-d962-11ea-9f39-7412af6f14a6.png)
</details>

**Comment by inverse** [comment]
All three look nice - yeah it's a tough one to choose

**Comment by Paszt** [comment]
I like the red, no outer circle. The red is similar to the previous version.

**Comment by arkhi** [comment]
I was thinking maybe you could find a S with the outter white border. Just brainstorming in 5 seconds. :)

![image](https://user-images.githubusercontent.com/277773/104157278-23ebad80-53eb-11eb-81b4-f0aa11da6765.png)

**Comment by alexesprit** [comment]
Looks interesting!

**Comment by jeanravenclaw** [comment]
This looks way better than the square icon, which looks a little outdated with all the circle icons nowadays

**Comment by nath1as** [comment]
@arkhi  it's the same as[ an accessibility extension I use ](https://addons.mozilla.org/en-US/firefox/addon/wave-accessibility-tool/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

**Comment by bes-internal** [comment]
Any flirtation with letter "W" and "S" always sucked into WC idiom... 🚾🚽 
So i came up with something better:

![image](https://user-images.githubusercontent.com/2046529/134745687-8e4ba1bd-b694-4ad8-8d74-d5fe0d1df1b5.png)

1. It is best to write the title below or on the side of the logo icon in plain text. The font can be easily changed to trends.
2. Сhoose the fill color yourself.
3. Put all the icons for the panel inside cloud, so its can combine information and identity.

The device is scrobbler. For scrobbling music, lol. 
Once I was impressed by the icon of [Audiograbber](https://en.wikipedia.org/wiki/Audiograbber).
![image](https://user-images.githubusercontent.com/2046529/134745881-5fa8d121-6625-46ef-8934-82ab5c7e50b3.png)
When the Audioscrobbler website came up I was sure they should have had the same impressive logo. If you remember it was a separate application that actually did this (even on the first androids) a device that grabbed the data of the playing track and uploaded it to its cloud.

**Comment by yayuyokitano** [comment]
It has become necessary to change logo quickly due to apple review (they do not allow usage of the audioscrobbler as). Circular icons are quite rare on app store, and the previous icon doesn't feel like it has much of a connection to scrobbling, so I tried my hand at yet another variant by sbubbying the lastfm logo.

It does remain somewhat closer to lastfm though, but is not flat out using the lastfm logo anymore. I feel like it more clearly represents what the application does, but I've been wrong before.

This currently has the different colored edges of v2, so that issue is not really solved.

The decision will have to be relatively quick since v3 cannot go out before it has been decided, but there is one other issue that needs resolution first anyway that probably takes a couple days at best.

svg: 
![safaricurrent](https://github.com/web-scrobbler/web-scrobbler/assets/69117606/501f631a-eb31-4cfc-a1d2-405e8aff33ad)
