### ISSUE TITLE
Scrobbler disconnects last.fm with forceful Chrome close

### ISSUE THREAD

**Issue by Mariekorbel** [web-scrobbler/web-scrobbler#2434]
Every time Chrome is forcefully stopped, whether through task manager or the computer turning off, the Web Scrobbler disconnects my last.fm profile.

Bug is reproduced by using task manager to force stop Google Chrome.

Console log here: [Pastebin](https://pastebin.com/XcP0znMM)

Environment:
Windows 10 Home Version 1909
Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
Web Scrobbler Version 2.32.2

**Comment by alexesprit** [comment]
What are steps to reproduce this? I tried the following ones:
1. Open Chrome
2. Sign out of Last.fm.
3. Close Chrome normally, then start again.
4. Sign in to Last.fm
5. Make sure I signed in.
6. Close Chrome forcefully via the task manager.
7. Open Chrome again.

I still see I signed in to Last.fm. What am I missing?

**Comment by Mariekorbel** [comment]
You aren't missing anything there, I'm pretty sure. I'm always signed into my last.fm account, however I have to reconnect it to Web Scrobbler every time chrome restarts.

**Comment by alexesprit** [comment]
Does it happen for you on Firefox?

**Comment by alexesprit** [comment]
Also, I need more debug logs.

Part 1.
1. Open Chrome.
2. Open Web Scrobbler options.
3. You should be not signed in. Sign in to Last.fm.
4. Press Ctrl+Shift+I, then select "Console" tab, and copy all logs from that tab.
5. Post logs here.
6. Close Chrome.

Part 2.
1. Open Chrome.
2. Open Web Scrobbler options.
3. You should not be signed in. Copy logs using [this instructions](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-background-scripts).
4. Post logs here.

**Comment by alexesprit** [comment]
Does also the extension reset options?

**Comment by Mariekorbel** [comment]
Thank you for the patience with my slow responses. Here are the logs for both.

P1: [Pastebin](https://pastebin.com/wQXxggpQ)
P2: [Pastebin](https://pastebin.com/u3WEg2Wg)

**Comment by alexesprit** [comment]
That's odd. Seems like Chrome does not save your Last.fm credentials for some reason.

**Comment by alexesprit** [comment]
Could you capture a screencast where you reproduce this issue?

**Comment by alexesprit** [comment]
I made an experimental build where I added debug output related to saving data to the Chrome storage. Could you install it and and copy P1 logs again?

[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4733721/web-scrobbler-chrome.zip)

**Comment by Mariekorbel** [comment]
Interestingly enough, the experimental build you gave keeps my data. The bug can't be reproduced in it. 

> Does it happen for you on Firefox?

No, it does not. Firefox keeps the data.

Here's a log of P1 with the experimental version: [Pastebin](https://pastebin.com/3XFqH9Wu)

And I have made two videos of the P1 process. One with the experimental version you gave me, and one with the public/store build where I still get the bug.

Experimental: [Youtube](https://youtu.be/4oTE73a1VEQ)
Public/Store: [Youtube](https://youtu.be/V0GMqFnKsgE)

I hope this gets some things cleared up!

**Comment by alexesprit** [comment]
That's odd. I haven't changed anything related to saving/loading from storage. Just added an additional debug log.

I think this could be happen because of storage limits (Chrome storage has a limitation to 5 MB). Do you have a lot of edited songs saved in the extension storage?

**Comment by Mariekorbel** [comment]
> Do you have a lot of edited songs saved in the extension storage?

No, I don't have any edited songs in my storage. Now I wonder if it's because of other extensions.

**Comment by alexesprit** [comment]
I have no other ideas what causes this issue.

Can you remember exactly when the issue appeared?
