### ISSUE TITLE
Cannot connect my Last.fm account.

### ISSUE THREAD

**Issue by aja675** [web-scrobbler/web-scrobbler#2435]
This is what I get when I try: chrome-extension://hhinaapppaileiechjoiifaancjggfjm/ui/options/index.html#

**Comment by alexesprit** [comment]
What is this?

**Comment by aja675** [comment]
That's what I get when I try to connect my account to the Web Scrobbler.

**Comment by alexesprit** [comment]
Where do you get this?

**Comment by aja675** [comment]
Why wouldn't it?

**Comment by aja675** [comment]
You mean ''sign in'' doesn't work at all?

**Comment by alexesprit** [comment]
It works fine if you left-click on "Sign in" link. Broken middle-clicking is a known issue, but it's not critical.

These authorization URLs are very tricky and cannot be generated immediately, so it's generated when you click on the link. Unfortunately, this does not work when you middle-click on the link (but seems like there's a workaround for this).

**Comment by aja675** [comment]
Is it actually possible to left-click with a trackpad though?

**Comment by alexesprit** [comment]
> Is it actually possible to left-click with a trackpad though?

I don't have a trackpad, so I don't know. But double-tap on my touchpad on my laptop generates left-click event, and clicking on "Sign in" button works.

> but seems like there's a workaround for this

This workaround does not work, unfortunately.

I made an experimental build where I tried to fix clicking on the elements. Could you install it and check if the button does work for you?

[web-scrobbler-chrome.zip](https://github.com/web-scrobbler/web-scrobbler/files/4721177/web-scrobbler-chrome.zip)
[How to install the extension from a zip file][install-from-zip]

[install-from-zip]: https://github.com/web-scrobbler/web-scrobbler/wiki/Install-an-unpacked-extension
