### ISSUE TITLE
Add Triple J to list of supported websites

### ISSUE THREAD

**Issue by DarkSunsetLove** [web-scrobbler/web-scrobbler#2436]
Hi,

I recently started using Last.fm and in order to start scrobbling as much music as possible, I added the Web Scrobbler extension to my browser. Because I listen to internet radio quite a lot, I would really appreciate it if you could add support for Triple J, specifically the Triple J Unearthed Jukebox website.

Thanks!

**Comment by alexesprit** [comment]
Could you post a link to this website?

**Comment by Volkor3-16** [comment]
[This link](https://www.abc.net.au/triplej/listen-live/player/) contains 3 steams, triple j, double j and triple j unearthed.
normally shows up as a pop-up window
