### ISSUE TITLE
Youtube Scrobbling Ignores Categories

### ISSUE THREAD

**Issue by Volkor3-16** [web-scrobbler/web-scrobbler#2438]
**Describe the bug**
It seems like YouTube doesn't show the categories anymore, and that is breaking the category filtering. 

**How to reproduce**
1. Ensure "Scrobble videos from "Music" category" is checked
2. Play YouTube Videos
3. Watch Watch Web Scrobbler try to scrobble non music categories

**Expected behavior**
Only Youtube Videos in the 'Music' category should be scrobbled

**Screenshots**
https://volkor.me/UjmN.png - Music Filter on
https://volkor.me/Bku3.png - Music still scrobbling
https://volkor.me/-1Qt.png - Description still missing
https://volkor.me/_W6f.png - category set as Comedy

**Debug logs**
I couldn't actually click on the 'Debug' on firefox :/

**Environment**
-   OS: Linux
-   Browser: Firefox
-   Extension version: 2.32.2

**Additional context**
I don't know how web scrobbler gets the category, but from looking back at previous issues, it seems like it reads the description, which youtube must have removed recently.

It's still possible to find it, in a <script> I found it by ctrl + f "category"

**Comment by alexesprit** [comment]
> It's still possible to find it, in a <script> I found it by ctrl + f "category"

Not sure if it's possible to get a category name from that object. IIRC it's was language-specific before. I'll take a look at this.

**Comment by Volkor3-16** [comment]
The last screenshot in the original post shows the category name. No idea about the language specific part though :/

**Comment by CTimmerman** [comment]
Comedy songs and bits are more relevant audio than Entertainment, which includes recipes like https://www.youtube.com/watch?v=nUqPOsgu0uo trailers like https://www.youtube.com/watch?v=agnpaFLo0to hobbies like https://www.youtube.com/watch?v=Na9_kU3TvVw see also issue #3272.
