### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by Lees26** [web-scrobbler/web-scrobbler#2450]
Web v 66.0.3 
Спасибо за обновление. _Кому-то._
Не появляется окно авторизации, и там где указаны поддерживаемые сайты - ничего больше нет.

**Comment by alexesprit** [comment]
Такой версии расширения нет.

**Comment by Lees26** [comment]
Firefox Quantum.
Зная, что есть местный гуру Алексей, и немного из-за огорчения неработающего плагина, обошёлся без английского.
Если всё в порядке с плагином, значит эта проблема появилась из-за откатка, браузер обновился до последней, он просто отвратителен, откатил - работает, иногда после закрытия крашит, надо бы его переустановить, но это нужен оффлайн установщик определённой версии, с отключением автообновления. Не думал, что буду извиняться за русский. Прошу прощения.

**Comment by Lees26** [comment]
Firefox Quantum.
Зная, что есть местный гуру Алексей, и немного из-за огорчения неработающего плагина, обошёлся без английского.
Если всё в порядке с плагином, значит эта проблема появилась из-за откатка, браузер обновился до последней, он просто отвратителен, откатил - работает, иногда после закрытия крашит, видимо не все файлы успешно восстановились, винда же... Надо бы его переустановить, но это нужен оффлайн установщик определённой версии, с отключением автообновления. Не думал, что буду извиняться за русский. Прошу прощения.
