### ISSUE TITLE
Support scrobbling from bandcamp's feed page

### ISSUE THREAD

**Issue by Mopper** [web-scrobbler/web-scrobbler#2452]
**Is your feature request related to a problem? Please describe.**
Scrobbling works fine when playing a full album from a band's page, but on the feed page (https://bandcamp.com/`username`/feed), where bandcamp shows you music liked/bought by people you follow, and where you can play one track for each of the items shown, it currently doesn't scrobble.

**Describe the solution you'd like**
Playing anything on the feed page also gets scrobbled.

**Describe alternatives you've considered**
Opening up the song/album in a new tab brings you to the band's page, where scrobbling does work.

**Comment by alexesprit** [comment]
It displays nothing for me on this page. How can I get something on that page?

**Comment by inverse** [comment]
For me too - I Remember there used to be a page where you could see your follower purchased but I can't see it anymore.

**Comment by Mopper** [comment]
Oh, weird. I had a bit of the URL in brackets and it did something odd with the formatting. I think I fixed it in the original comment (hard to see, I'm on mobile atm)

**Comment by inverse** [comment]
That was it! 

I can take a look when I have some time - unless someone else wants too?

**Comment by Mopper** [comment]
Thanks guys!
