### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by LunaLanaLuana** [web-scrobbler/web-scrobbler#2453]
Scrobbling does not work, no matter how much I connect and reconnect, or sign in and out.

It happens whenever I try to scrobble something.

I expected it to, well, scrobble, but it still doesn't work

Windows 10
Opera

**Comment by alexesprit** [comment]
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension
