### ISSUE TITLE
Qutebrowser (Qt5 Webengine) support 

### ISSUE THREAD

**Issue by basedtho** [web-scrobbler/web-scrobbler#2456]
**Is your feature request related to a problem? Please describe.**
I'm using QB. This browser does not support extensions, but it does support userscripts (greasemonkey, tampermonkey and the like). I would like to know if there is any way to adapt this extension to run as a userscript. There are other browsers that are based on this browser engine too, such as (if my memory serves me well) Falcon, Otter, etc...

**Describe the solution you'd like**
`web-scrobbler.user.js`

**Describe alternatives you've considered**
I've googled "web-scrobbler userscript", "webengine scrobble" and permutations to no avail

**Comment by basedtho** [comment]
Something i just found
https://github.com/sunny/deezer-scrobbler-userscript

**Comment by alexesprit** [comment]
There's no way to run the extension as a userscript. Web Scrobbler is quite complex to port it as a userscript.

I'd say the only way to resolve the issue is to build a new userscript for each website. But this is the task for another project.

**Comment by alexesprit** [comment]
Not sure if it's probably exists, but here's an idea for a such project:
- Write a Last.fm-related stuff as a separate module
- Write a website-related stuff as separate modules (like we have connectors for websites)
- Use a bundler to build a userscript for each website
