### ISSUE TITLE
Issue with Scrobbling on Youtube Music

### ISSUE THREAD

**Issue by GreenDXT** [web-scrobbler/web-scrobbler#2457]
Hi, first thank u so much for creating this such awesome featurs. but now i need help because my youtube music not being counted on last.fm. Before this issue all my song being counted on last.fm (yt music/spofiy), but today only spotify being counted on last.fm via web scrobble.

here the debugs logs on pastebein
https://pastebin.com/iQadWri8

thank u

**Comment by alexesprit** [comment]
Can't reproduce. Although I see something weird in the logs.

[How to debug the extension.][1] Please read the "Introduction" section more carefully, and please provide proper logs again.
In that ones you have a lot of entries related to Spotify, this is redundant.

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by alexesprit** [comment]
```
{
  "error": 29,
  "message": "Rate Limit Exceeded - Too many scrobbles in a short period. Please try again later."
}
```

**Comment by alexesprit** [comment]
By the way, the extension should display a yellow icon the extension bar. Does it display the icon for you?
