### ISSUE TITLE
jango.com not scrobbling

### ISSUE THREAD

**Issue by ormulum** [web-scrobbler/web-scrobbler#2458]
the red webscrobbler icon appears but that's all, it doesn't respond to the playing songs.
they just changed their page layout, perhaps that's caused the problem

firefox on ubuntu

thanks

**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by ormulum** [comment]
thanks for working on the bug so quickly
but it's still not scrobbling for me, on firefox or chromium
ubuntu budgie
thanks again for trying

**Comment by alexesprit** [comment]
It's fixed, but it's haven't been published yet.

**Comment by ormulum** [comment]
thanks for the explanation and thanks again for your work fixing it

**Comment by alexesprit** [comment]
I published a v2.32.4 update which will be available soon.

**Comment by ormulum** [comment]
jango.com switched back to their old format for a few days to iron out 
some bugs, and it wasn't until today that they went to the new page 
style again and your newly published fix could be checked. and the fix 
works fine.
thanks again

**Comment by alexesprit** [comment]
Good to know it works fine, thanks for the info!

**Comment by ormulum** [comment]
jango switched to the original website one more time, but they're back 
to the new one again, and the scrobbler works, but with a strange 
aspect. before they changed to the new format i would have to sign in, 
a song would start, but the webscrobbler symbol would remain red. i 
would open another tab, go to jango in the new tab and start a song, 
then the webscrobbler would show the magnifying glass and switch to the 
green box. a little weird, but hey, it worked. now i have to open a 
third tab for jango before it starts to scrobble. even weirder, but i'm 
not complaining, it works just fine if i follow the process i 
described. i just thought you might find this behavior interesting, i 
can scrobble from jango and that's what we want,
thanks again,
phil

**Comment by alexesprit** [comment]
Interesting. I'll take a look if we can do something on the extension side.
