### ISSUE TITLE
Webradio.de

### ISSUE THREAD

**Issue by hans-juergen** [web-scrobbler/web-scrobbler#2463]
Because of a [current Reddit thread](https://www.reddit.com/r/lastfm/comments/hg41hd/list_of_lastfm_accounts_for_radio_stations/) about scrobbling radio stations I just tested if Web Scrobbler supports the German station Rock Antenne already. It is not listed as supported site on the home page, and if you visit [their site](https://www.rockantenne.de/), the Web Scrobbler icon signals it is not supported. BUT: if you start their live stream, it opens a new browser tab with another site providing a web player, obviously for other radio stations as well:

https://www.webradio.de/rock-antenne/live?gd=NTMuNisxMC4xMQ==

At first the Web Scrobbler only scrobbles the title of the current programme like "Rock Nonstop", but if you open the Edit window, it recognises the currently playing track, even with correct album info and artwork. Clicking on the Edit/Scrobble button adds this track then and even the next tracks on the station plus longer spoken parts, short ones are neglected.

So I was very surprised that this actually works which seems to be unknown yet, and so this posting is rather a FYI, not a connector request. Maybe it would be nice if the longer spoken parts and ads could also be automatically left out.

**Comment by alexesprit** [comment]
I know it's supported, since I was the one who added this support. :)

It's powered on the `radioplayer` connector, which have a single "Radioplayer" entry for several websites. That's why Webradio.de is not listed.

```
{
	label: 'RadioPlayer',
	matches: [
		'*://www.webradio.de/*',
		'*://www.thebreeze.com/*/radioplayer/*',
		'*://ukradioplayer.*/*',
		'*://radioplayer.*/*',
		// Generic patterns
		'*://*/radioplayer/*',
		'*://*/radio/player/',
		'*://*/*/radio/player/',
	],
	js: 'connectors/radioplayer.js',
	id: 'radioplayer',
}
```
Probably, we should extract URL patterns for certain websites to separate entries, so they will appear in the list of supported websites.

> Maybe it would be nice if the longer spoken parts and ads could also be automatically left out.

If they marked somehow in internal code, they could be skipped. AFAIK, they don't.

**Comment by hans-juergen** [comment]
It's no big deal anyhow to delete those scrobbles from your Last.fm library afterwards by simply clicking on the "artist" profile Rock Antenne and then delete this artist from your library with one click. The three related programme sections would be longer spoken parts, ads and news, always having the same "track title".

In the meantime I have checked the Webradio.de site for supported radio stations, and it is a massive list of maybe all German radio stations including the big ones like WDR, NDR etc. You can open an akphabetical list by clicking on the menu button in the upper left corner and then choosing the tab "Sender A-Z".
