### ISSUE TITLE
Repeated Tracks Not Scrobbling on Amazon Music

### ISSUE THREAD

**Issue by merciersj** [web-scrobbler/web-scrobbler#2465]
**Describe the bug**
When a song is on repeat on Amazon Music it will only scrobble it once and miss the rest of plays of the same song.

**How to reproduce**

Go to music.amazon.com
Click on any song of your choice.
Put it on repeat.
Check the only scrobble of the song on your last.fm profile.
Expected behavior
It should scrobble the song for as many times it has been repeated.

Environment (please complete the following information)

OS: Ubuntu 18.04 64 bits
Browser: Firefox 73.0
Extension version: v2.28.2
Additional OS (to reproduce issue): Windows 10 64-bit
Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
Extension version: v232.4
Additional context
I've only seen it happen consistently on Amazon Music site, but it also randomly happens on other sites such as YouTube and bandcamp. Haven't tested other sites.

**Comment by alexesprit** [comment]
Repeating is quite tricky in the extension, but it should work in most cases.

[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by alexesprit** [comment]
@inverse Could you verify this issue?

**Comment by merciersj** [comment]
I have access to Amazon Music, I can try to get debug logs and attach later today if @inverse does not.

**Comment by merciersj** [comment]
Attaching the log here.  It looks like after the first play, no logs are showing up to set any of the state change flags or to scrobble.

> Send "now playing" request: 1
util.js:40 Last.fm: track.updatenowplaying response:
{
  "nowplaying": {
    "artist": {
      "corrected": "0",
      "#text": "Grey"
    },
    "ignoredMessage": {
      "code": "0",
      "#text": ""
    },
    "album": {
      "corrected": "0",
      "#text": "Chameleon"
    },
    "albumArtist": {
      "corrected": "0",
      "#text": ""
    },
    "track": {
      "corrected": "0",
      "#text": "Crime"
    }
  }
}
util.js:40 Tab 443: Song set as now playing
scrobble-service.js:123 Send "scrobble" request: 1
util.js:40 Last.fm: track.scrobble response:
{
  "scrobbles": {
    "@attr": {
      "accepted": 1,
      "ignored": 0
    },
    "scrobble": {
      "artist": {
        "corrected": "0",
        "#text": "Grey"
      },
      "ignoredMessage": {
        "code": "0",
        "#text": ""
      },
      "albumArtist": {
        "corrected": "0",
        "#text": ""
      },
      "timestamp": "1593448266",
      "album": {
        "corrected": "0",
        "#text": "Chameleon"
      },
      "track": {
        "corrected": "0",
        "#text": "Crime"
      }
    }
  }
}
util.js:40 Tab 443: Scrobbled successfully
util.js:40 Tab 443: isPlaying state changed to false
util.js:40 Tab 443: isPlaying state changed to true

**Comment by alexesprit** [comment]
It's not a full log, e.g. a part where a song is being recognized is missing.

Please either use a pastebin service, or a special spoiler for logs.

**Comment by merciersj** [comment]
Does this work?
[hhinaapppaileiechjoiifaancjggfjm-1593448580220.log](https://github.com/web-scrobbler/web-scrobbler/files/4846906/hhinaapppaileiechjoiifaancjggfjm-1593448580220.log)

**Comment by alexesprit** [comment]
Yes, that's more helpful.

I see the extension does not get song duration, that's why it cannot detect replays. Is song duration available on the page?

**Comment by merciersj** [comment]
Yes, let me attach here.
![screenshot](https://user-images.githubusercontent.com/29819120/86034375-7c87ca00-ba08-11ea-9b57-55a99f09bca2.PNG)

**Comment by alexesprit** [comment]
No, it's not available. I was talking about duration in the player bar. It should be always available on the page.

**Comment by merciersj** [comment]
Ah ok so no, it does not do that on the player bar!

**Comment by merciersj** [comment]
So without the duration on the page will the plugin not work?

**Comment by alexesprit** [comment]
By the way, is the remaining time on the player bar is toggleable? Some websites toggle current/remaining time on time element click.

> So without the duration on the page will the plugin not work?

It works, but won't detect replays.

**Comment by merciersj** [comment]
I was able to click the "maximize" button on the currently playing album and it made the song duration show up.  This fixed the scrobbling and repeats work now!  Thank you so much!

**Comment by alexesprit** [comment]
> By the way, is the remaining time on the player bar is toggleable? Some websites toggle current/remaining time on time element click.

If it's toggleable and both available in DOM, we can calculate duration.
