### ISSUE TITLE
Scrobbler is stuck on loading

### ISSUE THREAD

**Issue by Bestuser111** [web-scrobbler/web-scrobbler#2471]
**Describe the bug**
So I've had the web scrobber for about 2 years now (since February 2018) and it's been working fine. But however, today it's been acting strange, When you try to scrobble something it first searches for the song then  it knows you're scrobbling it, but with mine it stays on the searching/loading for song thing. 

**How to reproduce**

**Expected behavior**
I expected it too scrobble my music and not be stuck on the loading screen 

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   Browser: (e.g. Chrome, Safari)

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension
