### ISSUE TITLE
Emby/Jellyfin does not work on Jellyfin.

### ISSUE THREAD

**Issue by oldshensheep** [web-scrobbler/web-scrobbler#2479]
Emby/Jellyfin does not work on Jellyfin.
The song name is empty
![0.png](https://i.loli.net/2020/07/11/Pd2RkwfJZF3DBlN.png)
Here is the PlayingBar
![1.png](https://i.loli.net/2020/07/11/6NbBS5723a9p4Oz.png)

**Environment**
-   Browser: Firefox and edge
-   Extension version: v2.33.0
-  Jellyfin v10.5.5

**Comment by alexesprit** [comment]
I can't reproduce the issue on Jellyfin v10.5.5 and MS Edge/Firefox.

Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

![image](https://user-images.githubusercontent.com/1119267/87446496-08514700-c602-11ea-8159-8d00c2529cb8.png)
