### ISSUE TITLE
Incorrect Title Detection for tracks with Quotations

### ISSUE THREAD

**Issue by JP-Ellis** [web-scrobbler/web-scrobbler#2481]
## Describe the bug
When the track isn't recognized, I've been noticing issues with the automatic detection of the title for tracks names which have quotations.  For example, listening to the [Elgar: Enigma Variations](https://music.youtube.com/playlist?list=OLAK5uy_nnUy3C4IwqteZc1SbUgfZNzmg1SaawjdA) album has song titles of the form:

1. Elgar: Variations On An Original Theme, Op.36 "Enigma" - Theme (Andante)
2. Elgar: Variations On An Original Theme, Op.36 "Enigma" - 1. C.A.E. (L'istesso tempo)
3. ...

and Web Scrobbler just picks out "Enigma" for all of them and puts that as the default prefill when it doesn't recognize the track. 
 This is an issue which appears mostly with classical albums (as it is pretty common to have text in quotes), and I've only noticed it on tracks which weren't recognized to begin with.  I'm not sure whether now that I've added them for this particular album, it will still appear to others.

Another (likely linked) issue encountered is that once I fixed the title for the first track, the next track is detected as being the same as the first.  So in the above case, I would label the first track correctly, and once I start playing the 2nd track it thinks I'm listening to the first again, and so on for all 14 variations.

## Environment (please complete the following information)
- OS: Linux
- Browser: Brave
- Extension version: 2.33.0
- Website: [YouTube Music](https://music.youtube.com)

**Comment by alexesprit** [comment]
This happens due to a special rule to extract track info from videos like [this](https://www.youtube.com/watch?v=zYGCcpF-7nI). Not sure how to fix the issue properly for both cases. 

Perhaps, we can modify the rule to require a dash symbol before a track title, but the extension won't recognize `Artist "Track"` titles (if they exist).

> Another (likely linked) issue encountered is that once I fixed the title for the first track, the next track is detected as being the same as the first. So in the above case, I would label the first track correctly, and once I start playing the 2nd track it thinks I'm listening to the first again, and so on for all 14 variations.

Not sure if it's linked. Saving/loading edited track info is a separate process. Please open a new issue with a more detailed description including steps to reproduce.

**Comment by JP-Ellis** [comment]
I understand the need for that with YouTube itself, but is this parsing necessary for YouTube Music?

**Comment by alexesprit** [comment]
> but is this parsing necessary for YouTube Music?

Well, I think it's not necessary after we dropped support for YouTube videos in YouTube Music. See #2391 for details.

Removing YouTube filters competely gives this result:
![image](https://user-images.githubusercontent.com/1119267/87451528-a6481000-c608-11ea-88d2-56825492c442.png)

Not sure if it's correct, though.

**Comment by JP-Ellis** [comment]
From the part that I can see, it appears correct.  It is at least definitely more correct than just "Enigma", though without seeing the full name I obviously can't say for certain that it is correct.

**Comment by alexesprit** [comment]
> though without seeing the full name I obviously can't say for certain that it is correct.

```
{
  "track": "Elgar: Variations On An Original Theme, Op.36 "Enigma" - Theme (Andante)",
  "artist": "BBC Symphony Orchestra",
  "album": "Elgar: Enigma Variations"
}
```

**Comment by JP-Ellis** [comment]
Yeah, this seems correct assuming you were playing the first song in the album :+1:

**Comment by alexesprit** [comment]
Thanks for response!

I'll remove the YouTube filter then, since we don't parse YouTube videos in YouTube Music. We can add other filters, e.g. removing "Remastered" etc.
