### ISSUE TITLE
Issues with Mixcloud 

### ISSUE THREAD

**Issue by mfshill** [web-scrobbler/web-scrobbler#2482]
Since the 5th July add-on update on FireFox, Mixcloud will no longer scrobble. Add-on shows the 'Is it already playing?' notification. Was working fine before the update and I'm not sure Mixcloud have changed anything. FF version 78.0.2 (64-bit). Still scrobbling other sites fine.

**Comment by inverse** [comment]
Confirmed - sample URL https://www.mixcloud.com/peel600/mix/

**Comment by alexesprit** [comment]
> Was working fine before the update and I'm not sure Mixcloud have changed anything.

It's broken due to Mixcloud changes.

**Comment by inverse** [comment]
@alexesprit you a mix cloud user?

**Comment by mfshill** [comment]
Thanks for the quick reply, hopefully Mixcloud revert the change thier end.

**Comment by inverse** [comment]
@mfshill they wont revert their change - @alexesprit fixed the connector to work with their new design. But you'll have to wait for the next release. Which should be each few weeks.

**Comment by alexesprit** [comment]
I'll push a patch update soon.

**Comment by mfshill** [comment]
Excellent. 👍🏾

**Comment by clayrat** [comment]
Mixcloud still doesn't seem to work for me, Firefox 79.0, webscrobbler 2.35.2
