### ISSUE TITLE
Issue assignment + PR Assignment

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#2484]
We often have a problem where there are integrations that we do not use and that are  either:

- Geo-restricted 
- Behind a paywall that restricts us from accessing

In order to help speed up the process of diagnosing the problem and getting a fix out.

## Solving issues

I've seen some OSS like [Home Assistant](https://github.com/home-assistant/core) solve this by using structured PR templates and Github bots to automate this. 

See: https://github.com/home-assistant/core/issues/37855#issuecomment-658430926

## Solving PRs

This one is a little easier to solve and could be done via `CODEOWNERS` which would just require maintaining a file in our repo of people who have contributed and are willing to help maintain. 

See: https://github.com/home-assistant/core/blob/dev/CODEOWNERS

What's your stance of this?

**Comment by alexesprit** [comment]
Looks interesting, although I doubt if it's worth applying this to our project which is a way smaller.

The only issue I see is we have no regular contributors.

**Comment by inverse** [comment]
Yeah - the ack of regular contributors would make this difficult. Closing for now.
