### ISSUE TITLE
Add support for Buy Music Club (basically playlists for Bandcamp)

### ISSUE THREAD

**Issue by PiotrDabrowskey** [web-scrobbler/web-scrobbler#2489]
[Buy Music Club](https://buymusic.club/) was created to promote buying music on Bandcamp as an alternative to streaming services that pays very little to the creators. [Here](https://www.residentadvisor.net/news/42967) is a little broader context if anyone's interested. Main and probably only feature of the website is an option to create a playlist consisting tracks and albums from Bandcamp. As far as I know, all the playlists are public.

Playing the position on the playlist opens an embedded Bandcamp players in the lower right corner of the screen. I'm pretty sure the existing Bandcamp connector may be reused somehow in this particular case.

Here are some example playlists (you can open an embedded player by clicking on the playlist entry):
- https://buymusic.club/list/unsound-playlista-newonce-radio (this one consists only of tracks I think),
- https://buymusic.club/list/resident-advisor-2019s-best-tracks (this one too),
- https://buymusic.club/list/resident-advisor-2010-19-albums-of-the-decade (this on, on the other hand, consists of albums).

This is how it looks like in the browser:
![image](https://user-images.githubusercontent.com/9080823/88284220-572b6a80-cced-11ea-8b43-a466807b8240.png)

**Comment by inverse** [comment]
@alexesprit so this page works by loading iframes containing a bandcamp embedded player. Different to the one that's currently implemented for the daily one.

Do we support delayed iframe injection yet?

**Comment by alexesprit** [comment]
> Do we support delayed iframe injection yet? 

No, it's not supported now, but it should be possible in theory (this way is dirty and hacky, though).
