### ISSUE TITLE
TruckersFM Connector

### ISSUE THREAD

**Issue by OfficialCRUGG** [web-scrobbler/web-scrobbler#2491]
**Provide information about website**
TruckersFM is the second biggest Radio Station in the Simulator Games Community, some times hitting over 1,000 Listeners _([source](https://radiostats.info/))_ Their Website is a simple Nuxt Website using Bootstrap and getting Information such as the Track should not be hard. There is no Account or anything similar required and the Player is at the top of every Page.

**Additional context**
N/A

**Comment by alexesprit** [comment]
Hi! Could you add an URL to this website?

**Comment by OfficialCRUGG** [comment]
Whoops. I knew I forgot something... The URL is [truckers.fm](https://truckers.fm/).
