### ISSUE TITLE
no scrobling from bandcamp.com 

### ISSUE THREAD

**Issue by vnvslvch** [web-scrobbler/web-scrobbler#2493]
Добрый день
Играет и не скроблит
 "Для начала включите любую композицию

Уже что-то играет? "

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: firefox
-   Extension version: 2.34.0

**Comment by alexesprit** [comment]
Can't reproduce.

Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

![image](https://user-images.githubusercontent.com/1119267/88752694-3cc91500-d163-11ea-8148-2b814536ad25.png)

**Comment by vnvslvch** [comment]
Everything is fine today.Idk what was wrong. Sorry
