### ISSUE TITLE
Scrobble Error

### ISSUE THREAD

**Issue by matizealves** [web-scrobbler/web-scrobbler#2496]
The web scrobbler for last.fm is not working since yesterday, it doesn't recognize any song. Please, fix it asap.

**Comment by alexesprit** [comment]
Can't reproduce. It's working fine for me, and worked fine yesterday.

Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

![image](https://user-images.githubusercontent.com/1119267/89060042-f2b28000-d36a-11ea-9a19-6b4c65bf94ab.png)

**Comment by matizealves** [comment]
still not working. i've done everything but it keeps not scrobbling. I use this extension for at least 4 years and it never happened to stop working for so many days like now. I don't know if it's only happening to me, but I just want it to work again. Now that I deleted the extension and added again, I can't even log in with my last.fm account, it just doesn't work. Please, fix it asap, thanks!
![erro lastfm](https://user-images.githubusercontent.com/69051902/89217945-7d7dbf80-d5a3-11ea-897a-7743df3ea640.png)

**Comment by inverse** [comment]
@matizealves could you please provide logs like @alexesprit posted above.

**Comment by matizealves** [comment]
<details>
  <summary>Debug log</summary>
  Here is the content of debug log: ``` storage.Core = {
  "appVersion": "2.34.0"
}
scrobble-service.js:53 Unable to bind Last.fm
bindAllScrobblers @ scrobble-service.js:53
scrobble-service.js:53 Unable to bind Libre.fm
bindAllScrobblers @ scrobble-service.js:53
scrobble-service.js:53 Unable to bind ListenBrainz
bindAllScrobblers @ scrobble-service.js:53
extension.js:75 No scrobblers are bound
start @ extension.js:75 ```
</details>

**Comment by matizealves** [comment]
is it correct?

**Comment by alexesprit** [comment]
It's almost correct.

You have no accounts you're signed in. That's why it does not work for you.

**Comment by matizealves** [comment]
That's the problem, I was signed in, but I logged out and now I can't log in again...

**Comment by alexesprit** [comment]
There's a special section for this kind of issue: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-the-options-page

Please read this carefully and provide the logs.

But I'm pretty sure there's something on your side: an extension blocked Last.fm, the provider, or Last.fm itself. :)
