### ISSUE TITLE
Monstercat Gold Player

### ISSUE THREAD

**Issue by TBSliver** [web-scrobbler/web-scrobbler#2497]
So, the basic monstercat.com/music player works fine, however they also have a gold only player at monstercat.com/player (you need to be logged in to use obviously). This currently doesnt work, it doesnt detect any music playing.

If you need any help with this let me know, such as data dumps etc.

**Comment by TBSliver** [comment]
Took a quick look at the connector for monstercat thats currently there, and did some inspector playing:

Track Title:

```
document.querySelector('.song-title .scroll-item').innerHTML
"Voices"
```

Artist(s):

```
document.querySelector('.artists .artist-list').innerHTML
"<span class="artist-name"><a href="/player/artist/bossfight" class="artist-link">Bossfight</a></span><span class="artist-name"><a href="/player/artist/philipstrand" class="artist-link">Philip Strand</a></span>"
```

Play/Pause Button seems to be the same as the main one:

```
document.querySelector('.fa-pause')
<span class=​"hover-on fas fa-pause">​</span>​
```

The artist one would probably take the most work as not sure without diving further in your docs how to pull out a double artist setup like that, but hopefully that helps :D

**Comment by alexesprit** [comment]
@TBSliver Hi! Thanks for discovering this. 👍 This player also contains additional info, like cover arts, current time, and duration.

I've just purchased a gold subscription, and I'm improving the connector right now.

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/89205030-baf04600-d5bf-11ea-9a6d-3151b578d3ef.png)
