### ISSUE TITLE
Scrobble https://relax-fm.ru/

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#2506]
**Provide information about website**
https://relax-fm.ru/

Relax FM is a radio station out of Moscow, Russia, that features instrumental, English, and foreign music curated to relax you.  

**Additional context**
No registration needed

**Comment by inverse** [comment]
Is this even possible? When I visit and click play I see no meta data for us to scrape?

**Comment by alexesprit** [comment]
@inverse Yes, they have metadata, so it's not a problem to make the connector.

![image](https://user-images.githubusercontent.com/1119267/89577540-825ba100-d839-11ea-89ca-9d1ad85f4596.png)
