### ISSUE TITLE
Web Scrobbler Extension Problem

### ISSUE THREAD

**Issue by hauntedgh** [web-scrobbler/web-scrobbler#2510]
I download the extension for google chrome then I go to the extension bar and click on it. It says the following : 
![ce](https://user-images.githubusercontent.com/69223653/89356116-e86aeb80-d6b4-11ea-8f2d-f24318488d28.PNG)

**Comment by alexesprit** [comment]
Hi! What do you want to see instead?

**Comment by alexesprit** [comment]
Hmm, looks like the Chrome suggest to click on the extension icon to get started (even if an extension is not supposed to work in that way, like Web Scrobbler).

![image](https://user-images.githubusercontent.com/1119267/92326175-e223b280-f058-11ea-9f50-487eab59afbd.png)

**Comment by K0media** [comment]
> Hmm, looks like Chrome suggests to click on the extension icon to get started (even if an extension is not supposed to work in that way, like Web Scrobbler).
> 
> ![image](https://user-images.githubusercontent.com/1119267/92326175-e223b280-f058-11ea-9f50-487eab59afbd.png)

Similar to what's happening to me here:
https://github.com/web-scrobbler/web-scrobbler/issues/2559#issuecomment-707991875
