### ISSUE TITLE
The tracks are "repeated" 

### ISSUE THREAD

**Issue by Ernsthemingway** [web-scrobbler/web-scrobbler#2513]
I am used to using the Web Scrobbler to edit long tracks so that they can be seen in my last.fm profile (When I use Spotify or some other streaming program). The problem arises when the song ends, the original track always appears in my profile despite having edited it (Even when I don't use the device that has last.fm for this purpose).
https://i1087.photobucket.com/albums/j471/ernsthemingway/2020-08-07%2011.30.25%20www.last.fm%2020076653b21e.jpg

**Comment by alexesprit** [comment]
I can't reproduce this. I did the following steps:
1. Open https://www.youtube.com/watch?v=lZV_4QKiLdg which was not recognized by the extension.
2. Apply proper metadata, so this video is recognized.
3. Wait for 50% of the video duration to make sure it's scrobbled.
4. After the video ends, open my Last.fm profile.
5. See no duplicates, but expected to see duplicates according to the issue description.

What I missed?

Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension
