### ISSUE TITLE
Jellyfin doesn't scrobble properly

### ISSUE THREAD

**Issue by zovt** [web-scrobbler/web-scrobbler#2515]
**Describe the bug**
When I visit my jellyfin instance, the scrobbler doesn't appear to work. It gets stuck saying "Play some music to get started"

**How to reproduce**
1. Go to jellyfin instance
2. Play some music
3. Click on addon, expect to see scrobble info

**Expected behavior**
I would expect the scrobbler to detect the music playing, but it just says "Play some music to get started".

**Environment (please complete the following information)**
-   OS: Linux
-   Browser: Firefox
-   Extension version: Latest git master
-   Jellyfin version: Jellyfin Web 10.6.2

**Additional Information**
I've attached a diff which fixes the issue for me. Like I said, I'm not sure if this is weirdness from just my instance, or is a more widespread issue. The patch also fixes track detection (which was also broken)

[jellyfin.patch.txt](https://github.com/web-scrobbler/web-scrobbler/files/5042834/jellyfin.patch.txt)

Let me know if you need any more info from me

**Comment by alexesprit** [comment]
Looks like  they changed layout, as the extension works fine with v10.5.0.
