### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by TAKosice** [web-scrobbler/web-scrobbler#2524]
After opting in and login into last.fm account, it does not scrobble from Google Play Music: https://prntscr.com/tz19u7.
It looks like it does not recognise even the Google Play Music website.

OS: Windows 10 64-bit.
Browser: Chrome 84.0.4147.105 (64-bit version) and 86.0.4232.1 (32-bit version).
Extension: 2.35.2.

What to do with this?
Thanks.

**Comment by alexesprit** [comment]
Can't reproduce.

Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by inverse** [comment]
I'm unable to reproduce either.
