### ISSUE TITLE
Auto-deleting "Premiere:" prefix on Soundcloud

### ISSUE THREAD

**Issue by sc113** [web-scrobbler/web-scrobbler#2537]
There are quite a few channels on Soundcloud that always add "Premiere:" to the title of the tracks. It would be nice if such headings were automatically corrected, because every day you have to do this one single correction in a dozens of tracks.

Channels with such prefix:
https://soundcloud.com/the-ransom-note
https://soundcloud.com/houseum
https://soundcloud.com/moskalus
https://soundcloud.com/maslowunknown
https://soundcloud.com/gary-j
https://soundcloud.com/boltingbits
https://soundcloud.com/les-yeux-orange (they use "PREMIERE : " with a space)
https://soundcloud.com/berlinhousemusic
https://soundcloud.com/slothboogie (they use "SB PREMIERE:" sometimes)

**Comment by clasick** [comment]
@alexesprit Trying to add this as a filter but I'm no longer seeing a filter.js at `src/core/content/filter.js`. Is there a new way of handling this now?

**Comment by alexesprit** [comment]
@clasick The `metadata-filter` is a separate package now, which is installed from NPM. It's copied to the `src/vendor` directory after executing `npm install`.

**Comment by clasick** [comment]
@alexesprit Ah, cool. So basically the big streaming services are the ones we are adding to the main module and keeping the filters of individual sites inside their own connectors? That makes sense.

**Comment by clasick** [comment]
Actually, now that I think about it, Soundcloud is a big enough streaming service that should warrant it's own place in the `metadata-filter` right? I see that it is directly using the Youtube filter right now. Maybe if it requires many tweaks on its own, idk.

**Comment by alexesprit** [comment]
> So basically the big streaming services are the ones we are adding to the main module and keeping the filters of individual sites inside their own connectors? That makes sense.

Initially the `filter.js` container predefined filters and filter functions that multiple connectors utilize.

@clasick If we add Soundcloud-based connectors, we should move the filter to the `metadata-filter` module. For now it's ok to have it locally.
