### ISSUE TITLE
Cannot detect album title for uploaded tracks in YouTube Music

### ISSUE THREAD

**Issue by oquno** [web-scrobbler/web-scrobbler#2541]
https://github.com/web-scrobbler/web-scrobbler/blob/5c53ae8c8aaf5cb33cbe38d3f3c07151ad093ab3/src/connectors/youtube-music.js#L24

Selector in this line, `href*="browse/MPREb_"` may be like `href*="browse/FEmusic_library_privately_owned_release_detailb_"` in case when playing uploaded tracks.

**Comment by alexesprit** [comment]
Could you post a link to a uploaded video (if it's available for all, of course)?

**Comment by oquno** [comment]
@alexesprit 
Sorry, YouTube Music's uploaded tracks can only be played by the user who uploaded.
To reproduce the issue, you have to upload MP3 or something with your own YouTube Music account and play it.

**Comment by jaccarmac** [comment]
I can confirm that the `FEmusic_library...` selector is correct for uploaded tracks.

**Comment by alexesprit** [comment]
@jaccarmac thanks for the info. Feel free to open a PR to fix the issue. :)

**Comment by alexesprit** [comment]
@jaccarmac If we use `.ytmusic-player-bar [href*="browse/"]` selector for an album name, will this work? Or `MPREb_`/`FEmusic` suffixes should be added to avoid selecting wrong data?

**Comment by jaccarmac** [comment]
A `browse/` prefix catches the artist as well. I have a working patch, let me push it right quick and you can tell me how you want the long line handled.
