### ISSUE TITLE
No more categories on YouTube?

### ISSUE THREAD

**Issue by stephanebruckert** [web-scrobbler/web-scrobbler#2549]
**Describe the bug**
I found that non-music videos are being scrobbled. It seems that video categories have disappeared from youtube video descriptions.

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=J_HgR0mWllw
2. See that the video description doesn't show a category anymore

**Expected behavior**
should scrobble music or entertainment videos categories only

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Chrome
-   Extension version: 2.35.2

**Additional context**
Not sure if we can find about the category in a different way but this looks problematic for now

**Comment by alexesprit** [comment]
> See that the video description doesn't show a category anymore

Yes, but we still can get a category for the video.

```
Fetched category for J_HgR0mWllw: Music
util.js:580 Web Scrobbler: isPlaying state changed to false
util.js:580 Web Scrobbler: {
  "track": "Up Maroon",
  "artist": "Liuos",
  "album": null,
  "albumArtist": null,
  "uniqueID": "J_HgR0mWllw",
  "duration": 446,
  "currentTime": 3,
  "isPlaying": false,
  "trackArt": null,
  "isPodcast": false,
  "originUrl": "https://www.youtube.com/watch?v=J_HgR0mWllw"
}
```

**Comment by stephanebruckert** [comment]
Nice, does that use the YT API?

**Comment by alexesprit** [comment]
No. See [connectors/youtube.js](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/youtube.js) for details.

**Comment by stephanebruckert** [comment]
Ha ok so we are still getting categories correctly, my bad.

So if I rescope the problem, I would expect these non-music videos to not be scrobbled:
 - https://www.youtube.com/watch?v=leHb2hdCLqo
 - https://www.youtube.com/watch?v=IHrrPk3sleM

because they have no category: 

> Fetched category for IHrrPk3sleM: YT_DUMMY_CATEGORY_UNKNOWN

would it make sense to return false here?

https://github.com/web-scrobbler/web-scrobbler/blob/f808ae60d012fbca9c15795fa78ea6b0db9b2688/src/connectors/youtube.js#L106

**Comment by alexesprit** [comment]
The connector fetched categories for both videos.

> would it make sense to return false here?

No, this is a bugfix for #2368.

**Comment by stephanebruckert** [comment]
> The connector fetched categories for both videos.

I have the latest 2.35.2 but in my case no category could be found on both videos. Is this a bug on my side or am I missing something?

Fetched category for leHb2hdCLqo: YT_DUMMY_CATEGORY_UNKNOWN
Fetched category for IHrrPk3sleM: YT_DUMMY_CATEGORY_UNKNOWN

This person reported the same issue but the issue is closed? https://github.com/web-scrobbler/web-scrobbler/issues/2369#issuecomment-616614914

> it should scrobble if a category is missing
> https://github.com/web-scrobbler/web-scrobbler/issues/2368#issuecomment-616159016

I don't think it should scrobble if a category is missing. Watching non-music videos on YT for an hour _will_ most of the time lead to a bunch of bad scrobbles that I need to cleanup on my last.fm

However I also understand that some people might just listen to music on youtube, then that should perhaps be an option in the extension settings? for example:

[x] scrobble uncategorized

**Comment by alexesprit** [comment]
> However I also understand that some people might just listen to music on youtube, then that should perhaps be an option in the extension settings? for example:

We should fix fetching categories instead of adding new options. :)

> Is this a bug on my side or am I missing something?

I don't know, but if you can reproduce this, you could find out why it happens.

**Comment by stephanebruckert** [comment]
Right, looks more like a bug now indeed.

> Access to fetch at 'https://youtube.com/watch?v=J_HgR0mWllw' from origin 'https://www.youtube.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

<img width="508" alt="Screenshot 2020-09-05 at 17 42 01" src="https://user-images.githubusercontent.com/1932338/92308603-23578c00-ef9f-11ea-9677-fd0a2bb9eacc.png">

which only happens when at least one of these 2 is selected:


<img width="531" alt="Screenshot 2020-09-05 at 17 42 41" src="https://user-images.githubusercontent.com/1932338/92308616-3a967980-ef9f-11ea-8c49-283ce2e1f244.png">

**Comment by alexesprit** [comment]
Does the connector work for you if you change the URL to the video in the `fetchCategoryName` function?
```diff
- const videoUrl = `https://youtube.com/watch?v=${videoId}`;
+ const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
```

**Comment by stephanebruckert** [comment]
@alexesprit great catch, that works!

**Comment by inverse** [comment]
I noticed this too but assumed I had mis-configured my extension. Great finding + reporting!

**Comment by stephanebruckert** [comment]
I'm happy to open a quick PR for it but I'm not sure exactly why this fix works. Is it because the `videoUrl` needs to use the same domain as:

https://github.com/web-scrobbler/web-scrobbler/blob/26c540f3c4e81803426cc9f097b5a339dad39a4f/src/core/connectors.js#L23

or is it because https://youtube.com always redirects to https://www.youtube.com and the extension needs to fetch from the same domain?

@alexesprit if you do the same change, does it still work for you?

**Comment by alexesprit** [comment]
> I'm happy to open a quick PR for it but I'm not sure exactly why this fix works.

This is how [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) works.

When CORS is used, web applications (content scripts in the context of Chrome extension) are not allowed to fetch cross-origin resources (unless it's explicitly allowed). Technically, `www.youtube.com` and `youtube.com` are different domains.

> @alexesprit if you do the same change, does it still work for you?

Sure, this will work for me too. I'm on MS Edge, and both URLs work fine for me. Seems like MS haven't applied CORS-related changes to Edge.

Although the simplest way is to add "www" prefix to the `videoUrl` value, this is also the worst way to fix the issue. I suggest to construct the URL with using the `location.origin` value.

Note that we cannot just use `location.href` to get the full URL to the video.
