### ISSUE TITLE
Cannot scrobble tracks from deezer radio stations.

### ISSUE THREAD

**Issue by lucumon** [web-scrobbler/web-scrobbler#2558]
Today I was trying to scrobble songs listened through Deezer radio, and I wasn't able to do it. Scrobbling songs without being from a radio works flawlessly. Note that the radio stations I'm listening through deezer provide current song info, and deezer succesfully shows it.

**Comment by alexesprit** [comment]
How can I find radio stations on Deezer?

**Comment by lucumon** [comment]
You can use the search box to search any radio station, and then you have an specific tab for live radio search results.


![image](https://user-images.githubusercontent.com/24960275/94727115-877f2d00-035e-11eb-9a44-898f255929cd.png)

**Comment by alexesprit** [comment]
It displays no radio stations for me. :(

@inverse Could you check this?

![image](https://user-images.githubusercontent.com/1119267/95288397-d6eabf00-0870-11eb-9779-364cd29b37d9.png)

**Comment by inverse** [comment]
@alexesprit same:( 

![image](https://user-images.githubusercontent.com/713525/95302125-ce4eb480-0881-11eb-8722-b503ba6b2078.png)

**Comment by lucumon** [comment]
@inverse Your "Top Result" is a live radio. I'm not sure why you don't have the live tab, but at least you get results.

**Comment by alexesprit** [comment]
I found a way to reproduce the issue.

We use Deezer's internals to get track info, and looks like it's not available in case when a radio station is played. I'll try to find a way to get track info from Deezers API; if it's not possible, we can go with grabbing track info from DOM as a fallback.
