### ISSUE TITLE
Web scrobbler doesn't work anymore?

### ISSUE THREAD

**Issue by slyvanose** [web-scrobbler/web-scrobbler#2559]
Hi, I've had web/chrome scrobbler for like half a year now and there weren't any problems before but it stopped working yesterday and I have no idea how to fix it + my browser didn't change at all, I'm still using chrome extension.
All it says that:
"This website is not supported
Web Scrobbler does not support scrobbling from this website.
Some Google websites supported by the extension (e.g. Google Play Music, YouTube) can be blocked due to an ExtensionSettings policy. Learn more"
And when I press "learn more" 
The first thing that it says is: "Supported on:
Google Chrome (Linux, Mac, Windows) since version 62
Google Chrome OS (Google Chrome OS) since version 62"
But I am using chrome 85. I tried downloading 64 then because that was the only one similar to 62 and it still didn't work
I'm using windows by the way.

![119597841_2603738979956692_7727487116889045327_n](https://user-images.githubusercontent.com/54599205/93264847-a34fd400-f79f-11ea-8e23-26e27e8adf8c.jpg)
![119524777_729564584266456_8725034761643923545_n](https://user-images.githubusercontent.com/54599205/93264946-cc706480-f79f-11ea-8286-81baac21158b.png)
![119662349_3112280898867001_3503697964530121899_n](https://user-images.githubusercontent.com/54599205/93265087-ff1a5d00-f79f-11ea-9704-0e8bc079f144.png)

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension
