### ISSUE TITLE
Improve YouTube Music connector

### ISSUE THREAD

**Issue by bezo97** [web-scrobbler/web-scrobbler#2564]
**Description**
The song title and artist is very often wrongly recognized on [YouTube Music](https://music.youtube.com/). The track field contains both the artist and title, and the artist field contains a channel name. I looked into the issue and found that it happens on songs that are from a music promotion channel (more precisely, where the channel name is not the artist).

1. Go to a music video from a promotion channel, such as [this one](https://music.youtube.com/watch?v=6DcghQ_kCH8&feature=share).
2. Open the extension's panel and see the wrong data

**Expected behavior**
The channel name should not be scraped since it has nothing to do with the artist or song title. The artist name should appear in the artist field instead of the track field.

**Screenshot**
![tmp](https://user-images.githubusercontent.com/26039350/93996466-9419e900-fd92-11ea-8c8e-3f5831f48eeb.jpg)

**Logs**
Here's a [Pastebin link](https://pastebin.com/2GfTMkkV) with the logs.

**Environment**
-   OS: Windows
-   Browser: Chrome
-   Extension version: v2.36.0

**Comment by jaccarmac** [comment]
This was changed a while ago. You can read the reasoning for the change on #2391. In short, the decision was to treat videos like the example as second-class citizens due to the perceived intent of YouTube Music vs YouTube. For the record, I prefer the way it was before, but as YouTube music evolves the decision made seems correct to me. Of course, it's your call whether you want to continue the discussion about reverting the change.

**Comment by jaccarmac** [comment]
#2481 is also related.

**Comment by alexesprit** [comment]
Yes, YouTube Music contains both music (actually generated YouTube video) and video (YouTube videos), and AFAIK there's no way to distinguish them.

**Comment by alexesprit** [comment]
If all music tracks contain album names, we could use this information to support music and videos in a single connector. @jaccarmac Any thoughts on this?

**Comment by jaccarmac** [comment]
That seems like it would be a better solution than both of the other approaches. There will always be a certain number of edge cases, it's just the nature of the beast. I should check what the UI looks like for the specific videos which were noted as problem cases; I haven't encountered a lot of songs with delimiters in the title which I want to keep.

**Comment by bezo97** [comment]
@alexesprit 's solutions seems good to me.
I checked the possible edge case you mentioned and apparently YouTube Music assigns the title to the album name for singles, which is good for us.

**Comment by jaccarmac** [comment]
@bezo97 Can you link an example of a single that behaves like you are talking about? For example, I noticed that this video plays with no indication of its album, even though it's in the Cape God playlist. That seems to be due to the fact that it's a lyric video. https://music.youtube.com/watch?v=xRPyeNt5Wdg&list=OLAK5uy_lyXtkHz-379v_Xf59_5sXPzfkNfnbxTSw

**Comment by bezo97** [comment]
@jaccarmac Sorry I meant that for music tracks, not videos. Indeed that's a problem. Here's a possible fix:
```
if (hasAlbumName()) {
    // This is a music track, so we return the data like we do now.
} else {
   // Assume it's a YouTube video

  // Try to split video title into artist and track name
  // Fallback to original approach if the title can't be split
}
```

**Comment by jaccarmac** [comment]
PR pushed, though it looks like it's out of date with master (hopefully not irreparably). I propose we let it sit a while and see if it works properly. @bezo97, if you are able, please build the version from my branch and see if it addresses your needs. @aamelin and @JP-Ellis, I want to make sure I'm not stepping on your toes either with my reverts.

**Comment by bezo97** [comment]
@jaccarmac Hats off, I've just tested the build on many songs and couldn't find one where it fails. 👍 To my surprise it recognizes the album name on promotional videos too, which is awesome.

**Comment by bezo97** [comment]
@jaccarmac I've been using your version for a week now without a single issue, it's ready 👍
