### ISSUE TITLE
how do i install on opera

### ISSUE THREAD

**Issue by uknot** [web-scrobbler/web-scrobbler#2565]
when i go to get build only options r firefox and chrome idk how to do it for opera, it says it supports chrome based browsers but how

**Comment by alexesprit** [comment]
From our readme:
> Opera users can install the extension from Chrome Web Store using the
[Download Chrome Extension][DownloadChromeExt] addon for Opera.

[DownloadChromeExt]: https://addons.opera.com/extensions/details/app_id/kipjbhgniklcnglfaldilecjomjaddfi
