### ISSUE TITLE
Youtube scrobbler does not scrobble sometimes

### ISSUE THREAD

**Issue by franzbona** [web-scrobbler/web-scrobbler#2566]
On specific (random?) pages, while listening to a song on Youtube, this doesn't get scrobbled even if refreshing the page.

1. Go for example to this song's Youtube page: https://www.youtube.com/watch?v=8LIy-n8xuBk
2. Check the scrobbler: it doesn't turn GREEN and should be saying "Play some music to get started: Is it already playing?"

**Environment**
-   OS: Mac, 10.15.6 (19G2021)
-   Browser: Chrome, Version 85.0.4183.102 (Official Build) (64-bit)
-   Extension version: 2.36.0

![image](https://user-images.githubusercontent.com/4178676/94119167-cee15700-fe4e-11ea-9161-7f180bfd0ad9.png)

**Comment by alexesprit** [comment]
This video is in the "People and Blogs" category. You should disable these options to scrobble videos from all categories:
![image](https://user-images.githubusercontent.com/1119267/94156038-4aabc580-fe88-11ea-8d88-6fc502d20427.png)

**Comment by franzbona** [comment]
Hi @alexesprit, thanks for answering! Oh wow, I missed that - thought at least the first box should always be ticked. Interesting! Thanks so much!

**Comment by alexesprit** [comment]
@franzbona my pleasure!

YouTube removed the category label a while ago, so now it's hard to figure out why some videos are not scrobbled.

**Comment by franzbona** [comment]
Thanks for the detail and keep rocking!
Cheers!
