### ISSUE TITLE
Mixcloud connector problem

### ISSUE THREAD

**Issue by Idamalin** [web-scrobbler/web-scrobbler#2574]
It seems like the connector is not working properly with Mixcloud, since it is not detecting the music playing and not crobbling it for Last FM

**Comment by alexesprit** [comment]
I can't reproduce the issue.

![image](https://user-images.githubusercontent.com/1119267/94699632-33b31a80-0343-11eb-8d43-7ced38742439.png)

**Comment by Idamalin** [comment]
![image](https://user-images.githubusercontent.com/72115620/94763044-89baa900-03a9-11eb-9620-f79ec0f9b42f.png)

**Comment by Idamalin** [comment]
Oh, I see. I was suprised because it wouldn't pick up even "mainstream" and very well known tracks. Thanks for your answer.

**Comment by yoGhurrt1** [comment]
Hi,
I would like to re-open this ticket because addon again has problem with scrobbling from Mixcloud

![obraz](https://user-images.githubusercontent.com/13383620/108232541-2c9a7680-7143-11eb-987f-40148e31058c.png)

**Comment by alexesprit** [comment]
@yoGhurrt1 Hi!

I've just select a random mix, and it was recognized by the extension.

Could you post a URL to the mix you're trying to scrobble?

**Comment by yoGhurrt1** [comment]
@alexesprit for me it was for all mixes. I would suggest other way, please link me any mix that worked for me and I'll try it and compare with some other mixes.
