### ISSUE TITLE
TuneIn

### ISSUE THREAD

**Issue by lswysocki** [web-scrobbler/web-scrobbler#2575]
Hello,
For a few days I see that they are not adding scrobbles from TuneIn.com.

**Comment by lswysocki** [comment]
When will you fix this?

**Comment by alexesprit** [comment]
When we have time to verify and fix this.

**Comment by clasick** [comment]
It works just fine for me on TuneIn.com

Stations I tried:
* https://tunein.com/radio/NME-2-s155539/
* https://tunein.com/radio/WERS-889-s28589/

Which specific station doesn't work for you?

**Comment by alexesprit** [comment]
It works fine for me too.

![image](https://user-images.githubusercontent.com/1119267/94889033-8e539000-0483-11eb-9d1c-957026d91422.png)

**Comment by lswysocki** [comment]
https://tunein.com/radio/Caf-del-Mar-Radio-(official)-s280322/

**Comment by alexesprit** [comment]
This station does not provide track info.

**Comment by lswysocki** [comment]
I wrote to the radio station, they fixed it, they broadcast track info.

**Comment by alexesprit** [comment]
Wow, that's cool.

**Comment by inverse** [comment]
Very impressive :)
