### ISSUE TITLE
Does not scrobble a supported site

### ISSUE THREAD

**Issue by Jaff1** [web-scrobbler/web-scrobbler#2582]
I have a working and authenticated last.fm account.
Installed the extension, but it reports "This website is not supported" message for a song played on https://libre.fm/listen.php?tag=blues, which is a 'supported' site.

Steps to reproduce the behaviour:
1. Check your last.fm account works, authenticated, and scrobbles.
2. play a track on https://libre.fm
3. check for scrobble on  https://last.fm
4. See no update to scrobble list.

**Expected behaviour**

**Environment (please complete the following information)**
-   Windows 10
-   Chrome
-   Web Scrobbler, Version 2.36.0

Also I'd like it to support https://player.fm

**Comment by alexesprit** [comment]
> for a song played on https://libre.fm/listen.php?tag=blues, which is a 'supported' site.

Where is this said?

**Comment by Jaff1** [comment]
https://web-scrobbler.com/....
Web Scrobbler
Scrobble music all around the web!
Chrome Web Store Addons.mozilla.org GitHub release
Web Scrobbler helps music listeners to scrobble their online playback
history.

Key features
Support for Last.fm, *Libre.fm*, and ListenBrainz
Now playing notifications
Built-in track metadata filter
A lot of websites supported

**Comment by alexesprit** [comment]
Libre.fm is supported as a scrobbling service, but not a music website.

**Comment by inverse** [comment]
@Jaff1 player.fm is supported. I haven't tried it but it should work

Technically we could support libre.fm as a connector though.
