### ISSUE TITLE
Scrobbling from some bandcamp.com pages isn't working (extension stuck at "looking up")

### ISSUE THREAD

**Issue by eignatenkov** [web-scrobbler/web-scrobbler#2583]
**Describe the bug**
Extension is stuck in "looking up" state when playing music from some pages on bandcamp.com. Though the same tracks are being scrobbled when played from the personal "wishlist" page. 

**How to reproduce**
1. Go to https://nobusinessrecords.bandcamp.com/album/duck-walks-dog-with-mixed-results
2. Start playing any track
3. See that the scrobbler has an icon with the looking glass and status "looking up"
4. Add album to wishlist
5. Go to https://bandcamp.com/%username/wishlist, find album there, click on the play sign that appears when you hover the mouse pointer over the album cover
6. See that the scrobbler scrobbles.
7. The problem does not appear on every bandcamp page but on some.

**Expected behavior**
The tracks are being scrobbled successfully from https://nobusinessrecords.bandcamp.com/album/duck-walks-dog-with-mixed-results

**Environment (please complete the following information)**
-   OS: Ubuntu
-   Browser: Chrome
-   Extension version: 2.36.0

**Comment by catte-ish** [comment]
I am having the same issue and just started a thread about it.

**Comment by alexesprit** [comment]
Thanks for reporting this. I reproduced the issue, and I'll take a look at it.

**Comment by Skyfire2008** [comment]
Same, except I didn't check if it works with the wishlist. 
And the OS is Windows 10 64 bit.
Chrome version is 85.0.4183.121.

**Comment by catte-ish** [comment]
here is the bug log.

[bug.log](https://github.com/web-scrobbler/web-scrobbler/files/5334379/bug.log)

**Comment by xKittieKat** [comment]
i'm having the same issue on firefox

**Comment by blackieblack13** [comment]
It was ok for a moment, but now  I have  the same  BandCamp 'looking up'  scrobbling problem again.
