### ISSUE TITLE
Does the web scrobbler work with ghostery and ublock origin?

### ISSUE THREAD

**Issue by yaowser** [web-scrobbler/web-scrobbler#2594]
sometimes, when my lists for these blockers activates or when youtube gets a new update there ads sneak through, somehow, the scrobbler does not work as well anymore. It works currently, thanks for updating it.

**Comment by alexesprit** [comment]
Web Scrobbler will work fine, unless some extension blocks Last.fm, Libre.fm and ListenBrainz URLs.
