### ISSUE TITLE
Extension for Opera GX

### ISSUE THREAD

**Issue by BrunoHoltz5** [web-scrobbler/web-scrobbler#2595]
Hello, I started using the Opera GX browser by recommendation of friends, the browser it's better for gamers but it doesn't have any extension for scrobbles, since I use and like a lot of the Web Scrobbler for Google Chrome, I'd like to ask if it's possible to you guys implement the extension for the browser? Thank you for your attention!

**Comment by BrunoHoltz5** [comment]
I wanted to put this on the request labels, but I don't know how to use GitHub properly, I'm sorry...

**Comment by alexesprit** [comment]
Hi!

https://github.com/web-scrobbler/web-scrobbler/blob/master/README.md
