### ISSUE TITLE
TuneIn not scrobbling

### ISSUE THREAD

**Issue by antisatori** [web-scrobbler/web-scrobbler#2605]
Hello I have a problem with TuneIn. It says that the site isn't supported, but on the extension website it says it is. You can reproduce it by installing the extension and trying to scrobble TuneIn. Is it actually not supported or this is a bug, I don't know. Thank you

**Comment by langtall** [comment]
Was working fine 3 hours before your report, I'm experiencing the same issue now.

**Comment by diedie2** [comment]
Same here. I scrobbled almost 12 hours from TuneIn yesterday. Now I'm listing to the same station but scrobbling not working :-(
