### ISSUE TITLE
Also update Media Session when changing metadata

### ISSUE THREAD

**Issue by haeckle** [web-scrobbler/web-scrobbler#2607]
**Is your feature request related to a problem? Please describe.**
I update the information of the current track so it scrobbles right. But the Media Session still has the wrong (or even no) values.

**Describe the solution you'd like**
On editing also update [MediaMetadata](https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata) (metadata interface of the Media Session).

**Describe alternatives you've considered**
Their are an [addon](https://gitlab.com/zhanibek/mediasession-provider) and scripts for [Bandcamp](https://github.com/cvzi/Bandcamp-script-deluxe-edition/blob/b41f1bda281dc8003db8eb288a1ebb12de9606bb/Bandcamp-script-Deluxe-Edition.user.js#L844) and [Deezer](https://greasyfork.org/en/scripts/397299-deezer-media-session-support) (the former is obsolete isn't it?). But having an one-stop solution would be nice. Also their is already some sophisticated logic on detecting metadata in web-scrobbler so it would be nice to reuse this.

**Additional context**
Firefox just added MPRIS-Integration via the Media Session API which makes this very visible.

**Comment by alexesprit** [comment]
Not sure if MediaMetadata should be updated on the extensions side.

I think it should be updated by the website scripts; extensions and other apps (e.g. mobile browsers) should use this info, but should not update it.

**Comment by alexesprit** [comment]
It's quite tricky to edit MediaMetadata with the extension. Not sure if it will not conflict with website scripts.

**Comment by f1u77y** [comment]
BTW, many popular websites support MediaSession API, so maybe you could this for fetching metadata and playback state rather then parsing web page and/or relying on internal scripts.

**Comment by alexesprit** [comment]
MediaSession API is a primary source now, but it should be enabled in the connector explicitly. I'll probably enable it by default in future.

As I understand OP asked about modifying MediaMetadata after after an user edits track info via the info popup window.

**Comment by alexesprit** [comment]
Unfortunately we can't edit MediaSession contents - this will break data flow in the extension.

**Comment by haeckle** [comment]
Just saw your answers right now. Thanks for your investigation. To sad it's not possible :crying_cat_face:
