### ISSUE TITLE
Option to automatically convert latest comma in artists field into ampersand

### ISSUE THREAD

**Issue by sc113** [web-scrobbler/web-scrobbler#2608]
I.e. scan artist field for the rightmost ", " and replace it to " & " automatically. 

It would help in converting spotify\deezer tags into last.fm standards automatically, that I usually do manually.

**Comment by inverse** [comment]
Sound related to #1552

**Comment by alexesprit** [comment]
Not sure if it's related to #1552.

I think this could be resolved by using a global transformation enabled by default for all websites.

AFAIK, the most common format is `Artist — Track (feat. Artist 2, Artist 3, ...)`, whereas Spotify uses `Artist, Artist 2, Artist 3 — Track` or even `Artist, Artist 2, Artist 3 — Track (feat. Artist 2, Artist 3, ...)`.

**Comment by alexesprit** [comment]
By the way, we can just search for comma in the artist field directly: some artist names contain comma, e.g. "Time, The Valuator", "Invent, Animate".

Spotify (and some other websites) uses different DOM elements for each artist, so we can get an array of artist names from such websites. Using an array instead of a raw string to transform track info is much robust.

**Comment by sc113** [comment]
Yeah, that's would be much better, and probably could be implemented for all the major streaming services.
Things would be quite less complicated, if last.fm moved towards implementing multiply artists for single scrobble. There is [discussion started on that on last.fm forums](https://support.last.fm/t/allow-multiple-artists-on-the-same-scrobble/4435), but unfortunately without any reaction from last.fm stuff so far.

**Comment by alexesprit** [comment]
> Spotify (and some other websites) uses different DOM elements for each artist, so we can get an array of artist names from such websites. Using an array instead of a raw string to transform track info is much robust.

We use [MediaSession](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API) API for Spotify and other websites, and this API [does not support multiple artists](https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata/artist). The data received via API has a higher priority over data from DOM, so we should handle this somehow too.

**Comment by sc113** [comment]
Just bumping, as still hoping for an option to separate the last artist with an ampersand. I'm getting bloody tired of adding "&" to every track on Spotify.
