### ISSUE TITLE
Its not loading when I want to log in to my lastfm and also hasnt been scrobbling tracks showing website isnt supported.

### ISSUE THREAD

**Issue by ketanvaidya25** [web-scrobbler/web-scrobbler#2610]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by alexesprit** [comment]
What?

**Comment by inverse** [comment]
They were having issues - but It's gone https://twitter.com/lastfmstatus
