### ISSUE TITLE
Scrobbling doesn't work for Youtube anymore

### ISSUE THREAD

**Issue by mu-zzi** [web-scrobbler/web-scrobbler#2611]
**Describe the bug**
Since I updated Google Chrome yesterday, Youtube music videos are no more scrobbled with the webscrobbler extensions. I selected and deselected the options for YT music scrobbling but none of them changes the behaviour. The extension still shows the text "Play some music to get started" while I'm playing a music video on YT. Reloading the browser or YT doesn't help either.

**How to reproduce**
1. Go to YT, play a music video
2. Click on the web scrobbler extension
3. See that it webscrobbler is not scrobbling or recognizing YT

**Expected behavior**
Scrobbling music videos from YT

**Environment (please complete the following information)**
-   MacOS 10.14
-   Google Chrome Version 86.0.4240.111
-   Web Scrobbler 2.37.1

**Comment by alexesprit** [comment]
I can't reproduce this issue.

![image](https://user-images.githubusercontent.com/1119267/97172032-7976cd80-179f-11eb-9776-97933070caa8.png)

**Comment by mu-zzi** [comment]
It seems, it is only this video. Other videos are now functioning.

[image: Screenshot 2020-10-26 at 13.37.29.png]

**Comment by inverse** [comment]
@mu-zzi do you have the video in question? Please share a link so we can see what's the problem.

**Comment by mu-zzi** [comment]
It was this video:
https://www.youtube.com/watch?v=W_OyMM8lyn4&t=48s&ab_channel=BoilerRoom
However, today it works again like a charm. When I posted the issue 2 days
ago I used/played an "instant playlist" which I created by myself.
Unfortunately I do not have this temporary playlist anymore to test it
again. I guess you can close the ticket.
