### ISSUE TITLE
Add Scrobbling Support for Business Casual 

### ISSUE THREAD

**Issue by junenewflavor** [web-scrobbler/web-scrobbler#2613]
**Provide information about website.**
They seem to run on bandcamp with a custom url.

**Additional context**
https://music.businesscasual.biz/
![Screenshot 2020-10-27 at 7 50 46 AM](https://user-images.githubusercontent.com/73541993/97318487-26e1f380-1829-11eb-863f-e9c999ccaa91.png)

**Comment by inverse** [comment]
@junenewflavor this is just Bandcamp.

Please consult our Wiki page on adding [Custom URL patterns](https://github.com/web-scrobbler/web-scrobbler/wiki/Custom-URL-patterns).

If something is not clear let us know and we can try and make this easier.
