### ISSUE TITLE
Web Scrobbler can't scrobbling youtube and soundcloud

### ISSUE THREAD

**Issue by elakimth** [web-scrobbler/web-scrobbler#2614]
**Describe the bug**
My web scrobbler can't scrobbling youtube and soundcloud anymore when i'm playing music.

**How to reproduce**
1. Go to youtube/soundcloud, play a music video
2. Click on the web scrobbler extension
3. See that it webscrobbler is not scrobbling or recognizing anymore

**Expected behavior**
Scrobbling music videos from youtube and souncloud

**Screenshots**
![image](https://user-images.githubusercontent.com/73507046/97335090-0315c080-18b0-11eb-9770-970312b13e74.png)
![image](https://user-images.githubusercontent.com/73507046/97335215-2a6c8d80-18b0-11eb-83b3-c0e61598024a.png)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome 86.0.4240.111
-   Extension version: v2.37.1

**Comment by alexesprit** [comment]
Have you tried to reauthenticate?

**Comment by elakimth** [comment]
how to reauthenticate ?


Pada tanggal Rab, 28 Okt 2020 pukul 03.10 Alexey <notifications@github.com>
menulis:

**Comment by alexesprit** [comment]
Just open the extension options page, then expand the "Accounts" section. CLick on the "Sign out" link, then on the "Sign in" link to reauthenticate.

**Comment by elakimth** [comment]
there is no "sign out" and when i click sign in, nothing happened
![image](https://user-images.githubusercontent.com/73507046/97408471-b624ff00-192e-11eb-82a8-ea382ff47c63.png)

**Comment by elakimth** [comment]
i can't click "sign in" on last.fm but when i tried to click on libre.fm and listenBrainz, it works

**Comment by alexesprit** [comment]
> i can't click "sign in" on last.fm

Why?

**Comment by elakimth** [comment]
what should i do with the logs ?
![image](https://user-images.githubusercontent.com/73507046/97414183-431f8680-1936-11eb-8a63-25bcda22dfc7.png)

**Comment by alexesprit** [comment]
https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#providing-debug-logs

By the way, these are logs of *the background page*. I asked for logs of *the options page*.

**Comment by elakimth** [comment]
<details>
  <summary>Debug log</summary>
  Here is the content of debug log: 
wrapper.js:74 storage.LocalCache = {
  "5f7de9b5f7c0ad220985259097783e66": {
    "album": null,
    "albumArtist": null,
    "artist": "BTS",
    "track": "Winter Bear By V Of BTS"
  },
  "9c093cc72a3b79b37f3cb0464fbf76cd": {
    "album": null,
    "albumArtist": null,
    "artist": "BTS",
    "track": "Nothing Like Us (cover) By JK Of BTS"
  },
  "BQ7vGQn5GzA": {
    "album": "WINGS",
    "albumArtist": null,
    "artist": "BTS",
    "track": "Stigma"
  },
  "ITc-om9SVr4": {
    "album": "LOVE YOURSELF 轉 'Tear'",
    "albumArtist": null,
    "artist": "BTS",
    "track": "The Truth Untold (Feat. Steve Aoki)"
  },
  "N5ShoQimivM": {
    "album": null,
    "albumArtist": null,
    "artist": "V (BTS)",
    "track": "Sweet Night"
  },
  "hoj8SNde8qU": {
    "album": null,
    "albumArtist": null,
    "artist": "Dionysus (디오니소스)  (교차편집 stage mix)",
    "track": "BTS(방탄소년단)"
  }
}
wrapper.js:74 storage.LastFM = {}
wrapper.js:74 storage.LibreFM = {
  "token": "********************************"
}
wrapper.js:74 storage.ListenBrainz = {
  "isAuthStarted": true
}
util.js:40 ListenBrainz: Use https://listenbrainz.org/profile/
wrapper.js:74 storage.Options = {
  "disableGa": true,
  "disabledConnectors": "[hidden]",
  "forceRecognize": false,
  "scrobblePercent": 50,
  "scrobblePodcasts": true,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": false
}
wrapper.js:74 storage.Connectors = {
  "Tidal": {
    "useShortTrackNames": false
  },
  "YouTube": {
    "scrobbleEntertainmentOnly": false,
    "scrobbleMusicOnly": true
  }
}
util.js:40 ListenBrainz: Use undefined
undefined:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
util.js:40 ListenBrainz: request session timeout
debugLog @ util.js:40
util.js:40 ListenBrainz: Failed to get session
debugLog @ util.js:40
util.js:40 Libre.fm: auth.getsession response:
{
  "error": 14,
  "message": "This token has not yet been authorised"
}
util.js:40 Libre.fm: Failed to trade token for session
debugLog @ util.js:40
util.js:40 ListenBrainz: Use https://listenbrainz.org/profile/
util.js:40 ListenBrainz: Use undefined
undefined:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
util.js:40 ListenBrainz: request session timeout
debugLog @ util.js:40
util.js:40 ListenBrainz: Failed to get session
debugLog @ util.js:40
util.js:40 Libre.fm: auth.getsession response:
{
  "error": 14,
  "message": "This token has not yet been authorised"
}
util.js:40 Libre.fm: Failed to trade token for session
debugLog @ util.js:40
DevTools failed to load SourceMap: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/md5.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
util.js:40 ListenBrainz: Use https://listenbrainz.org/profile/
util.js:40 ListenBrainz: Use undefined
listenbrainz-scrobbler.js:227 GET chrome-extension://hhinaapppaileiechjoiifaancjggfjm/ui/options/undefined net::ERR_FILE_NOT_FOUND
fetchSession @ listenbrainz-scrobbler.js:227
requestSession @ listenbrainz-scrobbler.js:203
async function (async)
requestSession @ listenbrainz-scrobbler.js:203
getSession @ listenbrainz-scrobbler.js:91
async function (async)
getSession @ listenbrainz-scrobbler.js:86
createAccountView @ accounts.js:62
createAccountViews @ accounts.js:41
(anonymous) @ accounts.js:32
util.js:40 ListenBrainz: request session timeout
debugLog @ util.js:40
debugLog @ base-scrobbler.js:242
requestSession @ listenbrainz-scrobbler.js:205
async function (async)
requestSession @ listenbrainz-scrobbler.js:203
getSession @ listenbrainz-scrobbler.js:91
async function (async)
getSession @ listenbrainz-scrobbler.js:86
createAccountView @ accounts.js:62
createAccountViews @ accounts.js:41
(anonymous) @ accounts.js:32
util.js:40 ListenBrainz: Failed to get session
debugLog @ util.js:40
debugLog @ base-scrobbler.js:242
getSession @ listenbrainz-scrobbler.js:93
async function (async)
getSession @ listenbrainz-scrobbler.js:86
createAccountView @ accounts.js:62
createAccountViews @ accounts.js:41
(anonymous) @ accounts.js:32
util.js:40 Libre.fm: auth.getsession response:
{
  "error": 14,
  "message": "This token has not yet been authorised"
}
util.js:40 Libre.fm: Failed to trade token for session
debugLog @ util.js:40
debugLog @ base-scrobbler.js:242
getSession @ audio-scrobbler.js:90
async function (async)
getSession @ audio-scrobbler.js:77
createAccountView @ accounts.js:62
createAccountViews @ accounts.js:41
(anonymous) @ accounts.js:32
</details>

**Comment by elakimth** [comment]
oh now it works, thank you
