### ISSUE TITLE
Web scrobbler not working with amazon music browser

### ISSUE THREAD

**Issue by chimkle** [web-scrobbler/web-scrobbler#2615]
**Describe the bug**
Amazon updated the UI to their amazon music browser, and since then the web scrobbler has not been recognizing songs like it had before.

**How to reproduce**
Play a song with amazon music browser

**Expected behavior**
The scrobbler will not recognize any song playing
**Screenshots**
n/a

**Debug logs**
n/a

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Firefox
-   Extension version: 2.36.1

**Additional context**
n/a

**Comment by alexesprit** [comment]
Duplicate of #2604.
