### ISSUE TITLE
Exclude certain websites

### ISSUE THREAD

**Issue by RoelJanssens** [web-scrobbler/web-scrobbler#2617]
Is it possible to exclude certain websites from scrobbling? The site isn't in the "Options list"

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/97588440-8b5da800-1a0d-11eb-8da0-2424204fae22.png)

**Comment by RoelJanssens** [comment]
> > The site isn't in the "Options list"
> 
> What do you mean?

There is an option called 'Supported Websites' but I can't find out how to add a custom website here.

**Comment by alexesprit** [comment]
Initially you asked about *excluding* websites from scrobbling. What do you want to add?

**Comment by inverse** [comment]
@RoelJanssens any update on this?
