### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by fabioxavi10** [web-scrobbler/web-scrobbler#2620]
When I try to login last.fm it shows the error: Token expired. Please return to Last.fm scrobbler for web and try again.

**Comment by alexesprit** [comment]
How do you authenticate?

**Comment by Firewalker95** [comment]
Had the same error yesterday, but its working as expected today.
Retry it and it should work now 😄

**Comment by fabioxavi10** [comment]
Yes, it's working perfectly now. Thanks

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
