### ISSUE TITLE
New connector for vodafone.fm

### ISSUE THREAD

**Issue by duramato** [web-scrobbler/web-scrobbler#2622]
**Provide information about website**

[Vodafone.fm](https://vodafone.fm/) is a a website, for the vodafone.fm FM radio. 
It has info about current shows and more important it has a web player for the radio stream. 
The player has relevant information to whats currently playing: artist name and track name.

**Additional context**

Screenshoot of the site:
<details><summary>Screenshoot</summary>

![image](https://user-images.githubusercontent.com/10121067/98043959-06fc9200-1e1e-11eb-92ed-de2786825a19.png)

</details>

**Comment by jfcabral** [comment]
With the PR https://github.com/web-scrobbler/web-scrobbler/pull/2872 this is now available subce https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.44.0

So I'd say this can now be closed 😃 @duramato @alexesprit

**Comment by alexesprit** [comment]
Oh, thank you! Closing the issue right now.
