### ISSUE TITLE
Web-Scrobbler not detecting Jellyfin

### ISSUE THREAD

**Issue by crushingteeth** [web-scrobbler/web-scrobbler#2625]
**Describe the bug**
After going to Jellyfin server URL, the extension remarks "Web Scrobbler does not support this website".

**How to reproduce**
Go to Jellyfin server, extension automatically does not detect Jellyfin with the above remark. None of the sub-domains of Jellyfin work either. I can specifically add URL's for Web-Scrobbler via the settings for each service, however that does not fix the issue, and would require me to put in every single URL for every single URL in the Jellyfin server.

I've tried restarting Firefox, re-installing the Extension after clearing data, and adding URL's for Web-Scrobbler to detect.

**Expected behavior**
For web-scrobbler to detect Jellyfin, and scrobble listens from there.

**Screenshots**
https://i.imgur.com/G16MUbS.png

**Debug logs**
https://pastebin.com/FXQvATrX

**Environment (please complete the following information)**
-   OS: Debian
-   Browser: Firefox
-   Extension version: 2.36.1

**Additional context**
I suspect, that this didn't start happening until I put Jellyfin behind a reverse proxy. That's my only guess as to why it's refusing to parse that it is indeed a Jellyfin server. The URL contains Jellyfin, I have it whitelisted. From the debug logs, it only connects to the URL's that I've provided web-scrobbler via the settings cog beside the service, which is why there is a tab 44 connection, but otherwise it fails to connect. 

Thank you for your time.

**Comment by crushingteeth** [comment]
Update: I seem to have bypassed the issue by adding the specific URL followed by /*. so, in my case " https://jellyfin.tr909.sh/* ". 

I suppose this is not the default route by Web-Scrobbler for detecting a Jellyfin server, as it worked a day or so ago, but it does indeed work as far as I can tell.

**Comment by alexesprit** [comment]
The default URL patterns for Jellyfin are:
```js
{
	label: 'Emby/Jellyfin',
	matches: [
		'*://*8096/web/*',
		'*://*8920/web/*',
		'*://app.emby.media/*',
	],
	js: 'connectors/emby.js',
	id: 'emby',
}
```
If the URL does not match these patterns, the extension won't recognize the Jellyfin web interface.

**Comment by alexesprit** [comment]
In your case you should add a custom URL by yourself. I'm not sure if this is an issue.

**Comment by crushingteeth** [comment]
Sounds good! I'll go ahead and do that. Thanks for the response!
