### ISSUE TITLE
BBC Radio 6 is not scrobbling

### ISSUE THREAD

**Issue by thrustfault** [web-scrobbler/web-scrobbler#2637]
**Describe the bug**
No scrobbles are being submitted from the BBC Radio 6 web player.
Eg https://www.bbc.co.uk/sounds/play/m000pj1c

**How to reproduce**
1. Go to 'https://www.bbc.co.uk/sounds/play/m000pj1c'
2. Click on 'Play'
3. Scroll down to the track list - the currently playing track is denoted by a red equalizer icon.
4. The currently playing track is not detected by the extension.

**Expected behavior**
Currently playing track should be detected and submitted.

**Screenshots**
Now playing track is denoted with an icon:
![image](https://user-images.githubusercontent.com/2392934/99881728-6f52be00-2be9-11eb-9604-af7fb759e9c3.png)

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Firefox 82.0.3 (64-bit)
-   Extension version: 2.36.1

**Comment by alexesprit** [comment]
It still works for live streams, e.g. https://www.bbc.co.uk/sounds/play/live:bbc_radio_one.

Though it's still an issue, and I'll fix it.
