### ISSUE TITLE
Soundcloud "Premiere" prefixes filter still not working

### ISSUE THREAD

**Issue by sc113** [web-scrobbler/web-scrobbler#2638]
It should be fixed with #2579 on [2.7.0](https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.37.0) release. But those prefixes are still never cut anywhere:

![Preview](https://i.imgur.com/N1I0yTK.png)

**Comment by alexesprit** [comment]
Could you provide the URL to this track?

**Comment by sc113** [comment]
https://soundcloud.com/maslowunknown/premiere-huxley-patsy

or any other tracks from the listed channels:

https://soundcloud.com/the-ransom-note
https://soundcloud.com/houseum
https://soundcloud.com/moskalus
https://soundcloud.com/maslowunknown
https://soundcloud.com/gary-j
https://soundcloud.com/boltingbits
https://soundcloud.com/les-yeux-orange (they use "PREMIERE : " with a space)
https://soundcloud.com/berlinhousemusic
https://soundcloud.com/slothboogie (they use "SB PREMIERE:" sometimes)

**Comment by alexesprit** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/1119267/99886485-e4f07580-2c4d-11eb-9a98-afd47fa2cb5a.png)

Make sure you have v2.37.0 installed. If you're on Firefox, this version is not published to AMO.

**Comment by sc113** [comment]
> 
> 
> Works fine for me.
> ![image](https://user-images.githubusercontent.com/1119267/99886485-e4f07580-2c4d-11eb-9a98-afd47fa2cb5a.png)
> 
> Make sure you have v2.37.0 installed. Note that this version is not published on AMO (if you're on Firefox).

Ah, right, sorry. Firefox still has 2.36.1. Haven't noticed when reinstalled it :(
