### ISSUE TITLE
Add a connector for Live365.com

### ISSUE THREAD

**Issue by thomwim** [web-scrobbler/web-scrobbler#2643]
**Live365.com**
Live365 is a website that has user-created radio stations. Here is a sample station.

https://live365.com/station/Third-Rock-a76979

**Additional context**
For the metadata on the website:
player light-on-dark
media-info
track-name
track-artist
media-art player-image
play-button

**Ignore:**
Live365 : 30 Second Ad Break, 60 Second Ad Break, 90 Second Ad Break, 120 Second Ad Break

**Comment by tape-** [comment]
Seconding. I listen to this one often. http://player.live365.com/a23389

**Comment by spudart** [comment]
Does live365 continue to scrobble for others? It doesn't scrobble for me. I'm listening to: https://live365.com/embed/popout.html?station=a10277&s=md&m=dark&c=mp3
