### ISSUE TITLE
Double scrobbling of songs from Tidal

### ISSUE THREAD

**Issue by umpfh** [web-scrobbler/web-scrobbler#2645]
Tidal's songs are double scrobbling, screen below:

![t](https://user-images.githubusercontent.com/75166911/100515345-bdcd0300-317b-11eb-96ac-404c91f907d4.png)

- OS: Windows
- Browser: Firefox
- Extension version: 2.36.1

The song should only be scrobbled once.

Logs:

[console-export-2020-11-28_13-22-37.txt](https://github.com/web-scrobbler/web-scrobbler/files/5610571/console-export-2020-11-28_13-22-37.txt)

**Comment by alexesprit** [comment]
I see no double scrobbling in your debug log. Make sure you have no other apps that scrobbles music from Tidal.

**Comment by jaccarmac** [comment]
@umpfh, do you have Tidal connected to your Last.fm account? I tried setting that up when I first started using Tidal, but it didn't work, so I disconnected the account and switched to the extension. If you have the account connected, it's possible that they have fixed their scrobbling recently, causing the doubles.

**Comment by umpfh** [comment]
@jaccarmac Thanks, I turned off the Tidal + Lastfm connection and left the scrobbler - it's ok.
