### ISSUE TITLE
Short YouTube videos at 2x speed aren't scrobbled properly

### ISSUE THREAD

**Issue by ev3commander** [web-scrobbler/web-scrobbler#2651]
**Describe the bug**
If you play a short song on Youtube at 2x playback speed (e.g. https://www.youtube.com/watch?v=mAFSBpPxkok), scrobbling isn't done properly (while playing, last.fm will show "scrobbling now", but it won't record it after the song ends). 

**How to reproduce**
1. Go to a short song, like https://www.youtube.com/watch?v=mAFSBpPxkok.
2. Set playback speed in Youtube to be 2x. 
3. Play through the song.
After the song finishes, it will not have counted as a scrobble on last.fm recent tracks.

**Expected behavior**
The scrobble is counted on last.fm.

**Screenshots**

**Debug logs**
https://pastebin.com/AV2ENGac

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome and Firefox
-   Extension version: Chrome v2.38.0, Firefox v2.36.1

**Additional context**
Presumably, this functionality is because of the last.fm guidelines for when scrobbles count: "The track must be longer than 30 seconds. And the track has been played for at least half its duration, or for 4 minutes (whichever occurs earlier.)". For videos less than 8 minutes long, if played at 2x speed it won't be "for at least half its duration" or for 4 minutes. It would be nice to have an option in settings to halve the "duration" of youtube videos for it to count the scrobbles, but I understand this is a niche issue. It's just unfortunate that none of my scrobbles count for this reason.

**Comment by alexesprit** [comment]
Interesting case - I wonder why you want to listen to music on 2x speed.

Not sure if we have a way to get the current speed value. I'll take a look on this.

**Comment by ev3commander** [comment]
I listen to all youtube videos on 2x speed and am too often to change it, lol. I think another way to do it might to just count the scrobble when the current time value is more than half of the duration value, but I don't think that's easy to do and might generate false positives.

**Comment by ev3commander** [comment]
It turns out that you can use `document.getElementsByTagName("video")[0].playbackRate` -- it seems playback rate is built into HTML.
