### ISSUE TITLE
YouTube chapter numbers included in title

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#2654]
**Describe the bug**
title.replace(/\d+\.\s+/, "") is missing.

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=phacy_sGY8M
2. Click on Web Scrobbler icon.
3. See "01. One Vision" instead of "One Vision".

**Expected behavior**
Scrobble "One Vision" etc.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Edge
-   Extension version: Probably the latest. 2.38.0 according to edge://extensions/?id=hhinaapppaileiechjoiifaancjggfjm

**Comment by jaccarmac** [comment]
I had code written in response to #2509 that I never brought up to speed, so now we have a slightly different version of the chapter-parsing code which has been merged. I haven't yet brought the implementations together, but I think the current logic can be tweaked to fix the numbers.

**Comment by CTimmerman** [comment]
The 19 december 2020 version still shows this bug on https://www.youtube.com/watch?v=eclMFa0mD1c as it lacks a space after the period. Rick Cook's law?

**Comment by alexesprit** [comment]
I haven't added a rule for "NN -" prefix.

**Comment by CTimmerman** [comment]
`title.replace(/\d+\s*[.:-]\s*/, "")` should work.
