### ISSUE TITLE
Fip connector doesn't work

### ISSUE THREAD

**Issue by vctls** [web-scrobbler/web-scrobbler#2657]
**Describe the bug**
Scrobbling doesn't work anymore on www.fip.fr

**How to reproduce**
1. Go to https://www.fip.fr/
2. Click play on the main page or any of genre specific links
3. Current track is not detected

**Expected behavior**
Current track is found and scrobbled

**Screenshots**
![image](https://user-images.githubusercontent.com/18054077/101676382-640de800-3a5b-11eb-9654-b91ce0edb16a.png)

**Debug logs**
<details>
  <summary>Debug log</summary>
  Here is the content of debug log:

```
Injecting vendor/filter.js inject.js:52:12
Injecting vendor/jquery.min.js inject.js:52:12
Injecting vendor/browser-polyfill.min.js inject.js:52:12
Injecting core/content/util.js inject.js:52:12
Injecting core/content/reactor.js inject.js:52:12
Injecting core/content/connector.js inject.js:52:12
Injecting connectors/fip.js inject.js:52:12
Injecting core/content/starter.js inject.js:52:12
Tab 37: Remove controller for FIP connector util.js:40:10
Tab 37: Created controller for FIP connector util.js:40:10
```

That's it. No errors.
</details>

**Environment**
-   Windows 10
-   Firefox 84 and Chrome 89
-   Extension version: 2.36.1

**Comment by 4rion** [comment]
Same bug in Win10/Chrome 87/v2.38.0

**Comment by denknl** [comment]
The solution will be to change line 3 in the FIP connector from `const playerBar = '.player';` to `const playerBar = '.player-gui';`
Unfortunately I'm un-experienced with branches and pull requests in Git since I'm not a real developer. Maybe I'll learn and contribute later.
