### ISSUE TITLE
YouTube not scrobbling

### ISSUE THREAD

**Issue by saturnz11** [web-scrobbler/web-scrobbler#2662]
Hello, since three days ago for some reason YouTube is not scrobbling, I tried disconnecting the connector and connecting again but still nothing. I use Microsoft Edge in Windows 10 64-bit and the latest version of Web Scrobbler. The extension looks like this, is not detecting any songs
![Screenshot_522](https://user-images.githubusercontent.com/75949071/102020852-49d15400-3d52-11eb-8f31-ce19f3c771d4.png)

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by saturnz11** [comment]
Extension logs: https://pastebin.com/f3cLzz3Y
YouTube logs: https://pastebin.com/Bxa42Wf5

**Comment by alexesprit** [comment]
Unfortunately, I cannot reproduce the issue. Do you have any YouTube-related extensions installed?

![image](https://user-images.githubusercontent.com/1119267/102023432-73639d00-3d9d-11eb-99a6-8c60e15b3167.png)

**Comment by saturnz11** [comment]
Not really, just adblock, I don't know if that affects in something
![Uploading Screenshot_523.png…]()

**Comment by saturnz11** [comment]
I just tried reinstalling the extension and it scrobbles again

**Comment by alexesprit** [comment]
If you reopened because v2.39.0 does not work with YouTube, I will close it.

https://twitter.com/web_scrobbler/status/1339625550000885762?s=20

**Comment by alexesprit** [comment]
I guess I can close this. :)
