### ISSUE TITLE
Pinguin Radio stopped scrobbling due to site update

### ISSUE THREAD

**Issue by nautje** [web-scrobbler/web-scrobbler#2663]
Pinguin Radio (pinguinradio.com) was scrobbling to last.fm just fine when I was using it last Friday, but apparently they changed their site over the weekend so this morning I noticed scrobbling stopped working.

Could you look into this? All I can tell you is that when choosing a stream on their site it used to open in a separate window, but that's no longer the case, now you can select it from a dropdown menu at the bottom of the main page and it loads into a bar at the bottom of the screen.

I listen to them all the time when working, would be nice to see scrobbling working again soon. Thanks in advance!

**Comment by nautje** [comment]
Apparently it is still possible to open the stream in a pop-up window by pressing the + in the address bar (Chrome), but that's not scrobbling as well. The Web Scrobbler icon even remains grey.

**Comment by alexesprit** [comment]
I can't find any ways to listen to radio on the website. Could you post instructions or links to find any station?
![image](https://user-images.githubusercontent.com/1119267/102073703-bf9df400-3e14-11eb-9eeb-e6e85badfea8.png)

**Comment by nautje** [comment]
The black bar at the bottom should contain stream info and the option to open the dropdown menu by clicking on the stream name. Otherwise you should be able to install the browser app by clicking the + in the address bar. Which browser are you using?

![Schermafbeelding 2020-12-14 121327 Pinguin Radio](https://user-images.githubusercontent.com/75971003/102074966-dbe66480-3e05-11eb-9bb7-a5f3760a33f7.png)

**Comment by alexesprit** [comment]
I'm on MS Edge @ Windows 7. I'll check it again on my home PC with other browsers.
