### ISSUE TITLE
Pandora Scrobbling Not Working

### ISSUE THREAD

**Issue by mandahays** [web-scrobbler/web-scrobbler#2665]
Pandora songs are not being scrobbled to my profile. There don't appear to be any bugs in the log. It says everything is scrobbling successfully... it just doesn't show up on my profile. Thanks.

**Comment by alexesprit** [comment]
> It says everything is scrobbling successfully... it just doesn't show up on my profile. 

If you mean the extension displays the green tick icon, it's not the extension issue.

But the extension does not recognize music from Pandora for me.

**Comment by mandahays** [comment]
> If you mean the extension displays the green tick icon, it's not the extension issue.

I meant in the logs. There doesn't appear to be any actual error happening. But it just... doesn't post to lastfm for some reason. All other services are working fine with it except Pandora and that's the one I really wanted to use it with. D:

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension
