### ISSUE TITLE
Please support KXSF

### ISSUE THREAD

**Issue by bamjuggler** [web-scrobbler/web-scrobbler#2666]
**Provide information about website**

http://www.radiorethink.com/tuner/?stationCode=kxsf&stream=hi

**Additional context**

Player link from https://kxsf.fm/

**Comment by inverse** [comment]
Hi @bamjuggler what track information does the player disclose? I could only see shows listed on that page and nothing about whats currently being played.

![image](https://user-images.githubusercontent.com/713525/102535946-35ba8900-40a9-11eb-9558-bba995185af5.png)

**Comment by alexesprit** [comment]
Their website contains no information about now playing song as well.
