### ISSUE TITLE
Google Chrome - Youtube.com not being read

### ISSUE THREAD

**Issue by joffre12345** [web-scrobbler/web-scrobbler#2667]
The extension is not reading any music or videos that are being played through youtube. Today is the first day that I ran into the problem and no I didn't do any editing to settings or update anything as of recently. The extension turns red when music/videos are being played and when I click the extension it says "play some music to get started" and "is it already playing" but I tried playing hours of different content on Youtube and the extension never read any of it. In the past, the extension turned green and would show a cover photo artist name and song name if available but now I get nothing. I've tried uninstalling and reinstalling chrome and the extension multiple times. Is this a known issue as of late? Any help is appreciated.

**Comment by aja675** [comment]
Same.

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by shifgrethorr** [comment]
Same thing here

**Comment by eitch-h** [comment]
> Could you provide debug logs? [How to debug the extension.](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension)

Hi, I'm not the OP but i've had the same issue, you can find my debug log in the pastebin link below.

https://pastebin.com/5ptyMMGm

**Comment by shifgrethorr** [comment]
> Could you provide debug logs? [How to debug the extension.](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension)

I have the same problem as the others here. I have AdBlock installed in my browser as well, if that's relevant 
Logs of background scripts: https://pastebin.com/wwL73QxM
Logs of content script: https://pastebin.com/kAFXZJd1

**Comment by antmyx** [comment]
Same logs as above, web-scrobbler shows "Play some music to get started Is it already playing?"

Google Chrome
Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by alexesprit** [comment]
I can't reproduce it on MS Edge. Will check it later on Chrome.

Interesting, the extension recognizes the video category, but for some reason it got stuck with video recogition.

**Comment by alexesprit** [comment]
Could you guys also test if these videos are recognized by the extension?
1. https://www.youtube.com/watch?v=3RE1knDfqJ8
2. https://www.youtube.com/watch?v=zlLljcLHqHQ
3. https://www.youtube.com/watch?v=eYLbteOm42k

The extension uses different ways to read track info, perhaps, one of them is no longer works. If one of this video was recongized by the extension, please let me know.
