### ISSUE TITLE
Web Scrobble not functioning

### ISSUE THREAD

**Issue by georget3** [web-scrobbler/web-scrobbler#2672]
At first, the web scrobbler was failing to scrobble anything from any website, including YouTube. So I removed the extension and reinstalled it, and now it is permanently greyed out, and doesn't scrobble anything. Not sure what to do

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by dana-scroll** [comment]
I have the same issue on YouTube. Here is my debug log, I hope I did it right, because it is the first time I do this. 

https://pastebin.com/Hk87bdc2

**Comment by alexesprit** [comment]
If it's related to YouTube only, see #2667 and https://twitter.com/web_scrobbler/status/1339625550000885762?s=20 for details.

**Comment by andrei-dracea** [comment]
+1

**Comment by vnckppl** [comment]
Same here for the last couple of days now: Scrobbling is not working on Youtube. I have not tested other sites.

**Comment by eldexterr** [comment]
Looks like you need to go to the Web Scroobler settings > Options > YouTube > Check "Scrooble from Music Category"
I never needed to do this before, but it worked for me, I'm in Chrome btw

**Comment by silversonicaxel** [comment]
I've an issue in YouTube.
It works on Bandcamp.

**Comment by dana-scroll** [comment]
I didn't do anything after all and it's been a few days that it started working again on yt, so I guess you could close this issue. Thank you for the support.
