### ISSUE TITLE
Please add Radio Willy

### ISSUE THREAD

**Issue by nielsfred** [web-scrobbler/web-scrobbler#2679]
Please add Radio Willy. That's a rock radio that really helps me study! They have a streamlink, namely http://20723.live.streamtheworld.com/WILLY.mp3

**Comment by inverse** [comment]
Hi @nielsfred not sure how we can support that. Do they provide a web player that shows the current playing information?

 With that we could try and work with but a direct stream is not something we can do right now.

**Comment by uwueviee** [comment]
@nielsfred Is https://www.willy.radio/ the same radio station as you linked?

**Comment by nielsfred** [comment]
Yes it is!! :)

Op wo 30 dec. 2020 18:10 schreef Evie Viau <notifications@github.com>:

**Comment by inverse** [comment]
Will be in the next release 👍🏼

**Comment by nielsfred** [comment]
Thanks a lot. When will that be, please?

Op zo 27 feb. 2022 om 17:50 schreef Malachi Soord ***@***.***

**Comment by inverse** [comment]
https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.54.0

Just published

**Comment by nielsfred** [comment]
Ok, thank you very much. I am going to try it this right way. Let's see if
I can figure it out, because I'm not very good with computers.

Op ma 28 feb. 2022 om 21:44 schreef Malachi Soord ***@***.***

**Comment by softguitar** [comment]
The website has changed its radio player to [this link](https://www.willy.radio/luister/willy)

The [old webplayer](https://www.willy.radio/player/willy/index.html) is still working.

Is it possible to add the new one?
