### ISSUE TITLE
[Chrome] Can't Sign in to last.fm

### ISSUE THREAD

**Issue by tarikalmashni** [web-scrobbler/web-scrobbler#2684]
While being on www.deezer.com the extension showed a question mark while I played "Fashion" by "David Bowie".
As usual I clicked the icon to check the meta info of the current track, clicked the checkmark at the bottom and than an error message occured telling me I should head to the extension's options site and reauthenticate with my account.
So I logged it out from my last.fm account. However, clicking on "sign in" again does absolutely **nothing.**
I also restarted Chrome. Any ideas?

**Comment by terrypoot** [comment]
Same for me in all respects, except I was on youtube.

**Comment by pauloabr18** [comment]
Same for me, but in Firefox.

**Comment by tarikalmashni** [comment]
Seems that last.fm have changed something on their side then. Hopefully this can be fixed. :)

**Comment by inverse** [comment]
It looks like last.fm is having issues on their API. There is nothing we can do to change this right now.

```
Failed to load resource: the server responded with a status of 500 ()
```

@alexesprit perhaps we should highlight this case better on the UI to avoid this confusion

```
util.js:40 Last.fm: auth.getsession response:
{
  "error": 8,
  "message": "Temporary failure, please retry"
}
```

**Comment by tarikalmashni** [comment]
Seems to work again. Was able to reallow access to my last.fm account and now it's scrobbling.
