### ISSUE TITLE
Use the same cleanup rules for Youtube Music as for Spotify

### ISSUE THREAD

**Issue by vaartis** [web-scrobbler/web-scrobbler#2685]
**Is your feature request related to a problem? Please describe.**
Youtube music titles and albums, when official and not from videos, tend to feature things such as "remaster" or "deluxe version". This data is cleaned up for e.g. spotify, but not for youtube music.

**Describe the solution you'd like**
Use the same or similiar rules for youtube music.

**Describe alternatives you've considered**
Not doing it, I guess? If there are any serious problems with that.

**Additional context**
N/A

**Comment by alexesprit** [comment]
Yes, that makes a sense.

Also, ref: https://github.com/web-scrobbler/web-scrobbler/issues/2062#issuecomment-626154864
