### ISSUE TITLE
I can't scrobble some muscivideos from YouTube/YouTubeMusic/YouTubeMusicDesktop. Why?

### ISSUE THREAD

**Issue by ketchupfreak88** [web-scrobbler/web-scrobbler#2687]
Hello,

I can't scrobble some muscivideos from YouTube (Browser), YouTubeMusic(Browser) or YouTubeMusicDesktop(Win10).
What can I doo? O_o
Only SOME musicideos  I can't scobble from YouTube.
I can't scobble only a few NOT.

But that's sad! :(

For example:
https://www.youtube.com/watch?v=2yfwePfD-iU
(Scrobbling works NOT!)
It doesn't work!

But a lot of other musicvideos work!
For example:
https://www.youtube.com/watch?v=GukNjYQZW8s
(Scrobbling WORKS!)

Can this problem be solved? O_o

sincerely,
ketchupfreak88

**Comment by alexesprit** [comment]
> For example:
> https://www.youtube.com/watch?v=2yfwePfD-iU
> (Scrobbling works NOT!)
> It doesn't work!

What does it mean? How *exactly* does it not work?

Could you provide debug logs (**see the "Logs of content scripts" section**)? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by ketchupfreak88** [comment]
@alexesprit 
I am glad, that you answer to me. :)
Well, curiously enough the message is in German, not in English.
German error message:
Höre Musik um loszulegen
Läuft es schon?

I will translate from German into English:
Listening music to start
Is it running (at the moment)?

I also did 2 screenshots (1 from error, 1 from scrobbling).
What should I do with them?
E-Mail? Upload somewhere? What...?

sinceryl,
ketchupfreak88

**Comment by alexesprit** [comment]
@ketchupfreak88 ok, I got it. I don't need screenshots - unfortunately, they won't help me to understand why it does not work for you.

But you could provide debug logs using instructions in our wiki to help investigating this. I posted a link to these instructions above. :)

**Comment by ketchupfreak88** [comment]
@alexesprit
I can't see a button for "debug logs".
I just see a sine which shows a field with germany language.
=>
"Höre Musik um loszulegen
Läuft es schon?"

I will translate:
"Listen music to start
Is it running?"

There is just a link which a german message.
=>
"Der Verbinder für diese spezielle Webseite muss upgedatet werden. Du kannst auf die Liste der Issues gehen und schauen ob diese Webseite schon gemeldet wurde. "

"Issue" ist a link which guided me to this forum.

As written in the first post, this failure just happens with some musicvideos, NOT with all. :(
So normally it's actived and it's working, but not wirt every musicvideo. :(

What should I do now?

sincerely,
ketchupfreak88

**Comment by pankuleczka** [comment]
> For example:
> https://www.youtube.com/watch?v=2yfwePfD-iU
> (Scrobbling works NOT!)
> It doesn't work!

this video has category "entertainment" and not "music" - you probably have this category unchecked in the options; what would be cool is to have a per-video scrobble enable override which is what I came here looking for :)

**Comment by ketchupfreak88** [comment]
@pankuleczka
Hey, thank you very much for your help! :)
You were totally right.
It was only "music" activated. The catergory "entertainment" wasn't activated.
I did it know and it WORKS!
Wow! 👍 
Again: Thank you very much! 🥇 

sincerely,
ketchupfreak88
