### ISSUE TITLE
Primephonic not scrobbling

### ISSUE THREAD

**Issue by egoebelbecker** [web-scrobbler/web-scrobbler#2688]
**Describe the bug**
Web Scrobbler does not detect music playing on Primephonic. I'm using 84.0.1 (64-bit) on macOS Catalina.

**How to reproduce**
1. Go to primephonic
2. Play some music
3. Click on toolbar icon for web scorbbler
4. It will tell you to start playing music.

**Expected behavior**
It should scrobble.

-   OS: (e.g. Windows, Mac) Mac
-   Browser: (e.g. Chrome, Safari) Firefox 84.0.1
-   Extension version: 2.39.2f

![CleanShot 2020-12-28 at 21 58 32](https://user-images.githubusercontent.com/5241455/103255625-0254e580-4958-11eb-965d-5c116fd3d282.png)

**Comment by egoebelbecker** [comment]
Chrome on Mac, too.

![CleanShot 2020-12-28 at 22 06 33](https://user-images.githubusercontent.com/5241455/103255873-07666480-4959-11eb-9abf-3e491a7b5ca0.png)

**Comment by slvr2314** [comment]
Facing the same problem with Chrome on Windows 10.
v2.39.2

**Comment by egoebelbecker** [comment]
Thank you!

**Comment by Ivnslv** [comment]
Hello! Im having problems scrobbling, what should I do? It says that its not supported but some weeks before this was not happening

![image](https://user-images.githubusercontent.com/67914903/103480952-579c5700-4d9d-11eb-80b7-ea48a2b4816c.png)

**Comment by alexesprit** [comment]
> Hello! Im having problems scrobbling, what should I do?

Well, the update is not published, so you have two options:
1. Wait until it's published to stores.
2. Install the extension from sources.

**Comment by Ivnslv** [comment]
cool, but what mean from sources?

**Comment by alexesprit** [comment]
[How to get a build zip file][get-build-file]
[How to install the extension from a zip file][install-from-zip]

[get-build-file]: https://github.com/web-scrobbler/web-scrobbler/wiki/How-to-get-builds
[install-from-zip]: https://github.com/web-scrobbler/web-scrobbler/wiki/Install-an-unpacked-extension

**Comment by slvr2314** [comment]
Brilliant! Works fine now. Thanks @alexesprit
