### ISSUE TITLE
Some YouTube track numbers not being stripped

### ISSUE THREAD

**Issue by euangeleo** [web-scrobbler/web-scrobbler#2689]
I've noticed some YouTube videos that have tracks defined aren't getting track numbers stripped properly. Some examples:

https://youtu.be/fYuOnQBdETo
`01. Bossa Nostra - Life`
_The track title and artist are being parsed, but the "01." is not getting stripped from the song title_

https://youtu.be/06vMXxnHmW0
`1. Old Skool Joint  -  Loop Therapy`
_The track title and artist again are parsed, but the "1." is not getting stripped_

https://youtu.be/PWUxqdCZ1H4
`1) Universal Mother (Let Yourself Flow) -  Jestofunk`
_Track title and artist are split, but here the track number "1)" is not getting stripped_

I'm working on one addition to the TypeScript rules that would strip one or two digits followed by ".", ")", or ".." (the latter is one I can remember seeing, but I can't find an example of it now).

**Comment by CTimmerman** [comment]
I found another one: "(2).Silver Pozzoli" from https://www.youtube.com/watch?v=KyabZRQeQgk

**Comment by alexesprit** [comment]
@CTimmerman thanks! Could you open a new issue as a reminder for me to fix it?

**Comment by CTimmerman** [comment]
More track number parsing issues #2727

**Comment by Offbeatmammal** [comment]
looks like https://www.youtube.com/watch?v=YT28Xfl8sEs is another example of a mix with chapters that are not processing correctly.

not knowing how the extension works, does it just see the current chapter, or can it see all chapters in a video ... if the former, would being able to see if the list starts with sequential numbers followed by punctuation help filter them out?
