### ISSUE TITLE
PCloud connector not working

### ISSUE THREAD

**Issue by aldeano** [web-scrobbler/web-scrobbler#2690]
The addons isn't scrobbling from my.pcloud.com in firefox 84.0.1 win 10 up to date.

It was functioning with 83.0.

In the pop up appears the messages  `This website is not supported` and `Web Scrobbler does not support scrobbling from this website.`

**Comment by alexesprit** [comment]
@aldeano Works fine for me.

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/103423415-77722600-4bb7-11eb-9611-d584cd2b55f6.png)
</details>

If the extension does not recognize a *website* that means the website URL is changed, and the extension cannot detect it. Could you post a screenshow with pCloud opened and with that popup window?

**Comment by aldeano** [comment]
I don't know why, but now it works right. Marking as closed.
