### ISSUE TITLE
Spotify won't scrobbler

### ISSUE THREAD

**Issue by ofdrykkjaa** [web-scrobbler/web-scrobbler#2692]
The title basically tells all - however the last time it shows a scrobble was from 00:58 (2/1/21) UK time. And as i write this it is 2:30pm. Is there a current issue on scrobbling from spotify web player (without connected spotify account). I have yet to check youtube but the extension is completely grey.

**Comment by elakimth** [comment]
same case

**Comment by alexesprit** [comment]
Can't reproduce.

<details>
  <summary><b>Summary</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/104020818-d85cb800-51ce-11eb-88c4-d39ed0edca82.png)
</details>
