### ISSUE TITLE
iheart/youtube not scrobbling while jango does

### ISSUE THREAD

**Issue by MXB2001** [web-scrobbler/web-scrobbler#2701]
**Describe the bug**
iHeart & Youtube don't scrobble right away, Jango does. The icon does turn red indicating supported site but only on Jango does it turn into a musical note when it scrobbles. I double checked at last/libre and only the Jango plays were recorded. When you refresh the page or click on a link it starts to scrobble only then.

**How to reproduce**
1. Go to iheart or youtube
2. Click on play

**Expected behavior**
Scrobbling

**Environment (please complete the following information)**
-   OS: Debian 9 Linux
-   Browser: Firefox
-   Extension version: latest (just installed it)

**Comment by alexesprit** [comment]
Can't reproduce it for YouTube.

Please use separate issues per each website next time.

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/104016357-3e454180-51c7-11eb-9ca4-a14f2d0dfb33.png)
</details>
