### ISSUE TITLE
Connector for Stingray Music

### ISSUE THREAD

**Issue by jbwharris** [web-scrobbler/web-scrobbler#2707]
I created a connector for Stingray Music in Canada. I'm not much of a developer, but I was able to get this working, though had some issues with regards to using an Ad Blocker would cause issues on the free player. If you're using the subscriber version it seems to work pretty well. I've just been sitting on this for awhile and thought sharing it might be worthwhile.

connectors.js
` label: 'Stingray Music',
    matches: ['*://webplayer.stingray.com/*'],
    js: 'connectors/stingray.js',
    id: 'stingray',`

stingray.js
`'use strict';`
`Connector.playerSelector = 'player';`
`Connector.artistSelector = 'cover-with-info.current.cover artist-names div.value';`
`Connector.trackSelector = 'cover-with-info.current.cover div.title-content > span.title';`
`Connector.onReady = Connector.onStateChanged;`

**Comment by alexesprit** [comment]
Why don't you create a PR for this?
