### ISSUE TITLE
Add Audius.co to list of websites

### ISSUE THREAD

**Issue by corrupteddrive** [web-scrobbler/web-scrobbler#2717]
I use this extension alot to scrobble my music, but there is one service I use that is not supported on the extension. It is certainly possible and would like audius.co added to the supported websites list.

Here's the URL for convenience;
https://audius.co

**Comment by alexesprit** [comment]
It's already requested in #2350.

**Comment by corrupteddrive** [comment]
Oh Sorry, thanks
