### ISSUE TITLE
Can't open ext settings in Firefox

### ISSUE THREAD

**Issue by spiilmusic** [web-scrobbler/web-scrobbler#2722]
Can't find link to this moz-extension://.../ui/options/index.html
It looks like it's issue to Firefox itself.
In chrome we have "options" context menu item.
Anyway, other extensions have gear icon in the main window to open options.

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/106147946-841f7500-6189-11eb-8d4a-c62717c499cb.png)

**Comment by alexesprit** [comment]
> Anyway, other extensions have gear icon in the main window to open options.

Where is it? Can you make a screenshot?

**Comment by spiilmusic** [comment]
It's strange. Didn't see this menu item today, but now it's here. Thanks.

**Comment by spiilmusic** [comment]
> > Anyway, other extensions have gear icon in the main window to open options.
> 
> Where is it? Can you make a screenshot?

Here's examples of other extensions JFUI
![Снимок экрана 2021-01-28 в 19 03 35](https://user-images.githubusercontent.com/11190533/106165096-c5208500-619b-11eb-84a9-d5af343e8427.png)
![Снимок экрана 2021-01-28 в 19 03 03](https://user-images.githubusercontent.com/11190533/106165100-c651b200-619b-11eb-96aa-3d3041fd1ee5.png)
