### ISSUE TITLE
Hey, I'd love if you add Mixcloud.com

### ISSUE THREAD

**Issue by XaviPlones** [web-scrobbler/web-scrobbler#2726]
It's really soundcloud-like, but it has a lot of bands and artists that aren't in the first one, thx

https://www.mixcloud.com/

**Comment by alexesprit** [comment]
It's already supported.

**Comment by dbl-mm** [comment]
unfortunately the extension does not work for me on mixcloud.com.
tested under macOS 11.5 with Chrome version 92.0.4515.131 and Firefox 92.0b1
