### ISSUE TITLE
More track number parsing issues

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#2727]
I found another bunch, eg: "(2).Silver Pozzoli" from https://www.youtube.com/watch?v=KyabZRQeQgk

TRACKLIST

(1) 00:00​ David Gray - Let's Dance Tonight
(2) 02:13​ Silver Pozzoli - Around My Dream
(3) 04:26​ Brian Ice - Talking To The Night
(4) 06:07​ Lee Marrow - Shanghai
...
(10) 17:40​ Fred Ventura - Night And Day (London Version)

That one turns into:
Track: Night And Day (London Version
Artist: .Fred Ventura

The tracklist of https://www.youtube.com/watch?v=5m8blzZ1lkA isn't even being used by YouTube:

```
TRACKLIST:
 0:00​ Happy Children - P.Lion
5:45​ Pretty Face - Styloo
11:40​ Hey You - Joe Lockwood
18:36​ Tonight - Ken Laszlo
24:12​ Love In Stereo - Cristal
29:25​ You And Me - Lazerdance(remix)
34:21​ The Night - Valerie Dore
39:48​ Vampires - Radiorama
45:35​ Acapulco Nights G.F Lunghi
52:45​ Perfect Love - Linda Jo Rizzo
58:42​ I'm your lover - Joe Yellow
1:03:50​ Run To Me(Extended Version) - Lena
1:08:20​ Take Me Mr Love(Vocal Version) - Spy 71
1:14:00​ Pripyat(Original Mix) - Aron Scott
```

**Comment by alexesprit** [comment]
> (10) 17:40​ Fred Ventura - Night And Day (London Version)
>
> That one turns into:
> Track: Night And Day (London Version
> Artist: .Fred Ventura

The missing space is a YouTube chapters bug. But I can add removing `(n).` prefix.

> https://www.youtube.com/watch?v=5m8blzZ1lkA

Very interesting - I see nothing wrong in the playlist format.

Can we submit an issue related to chapters to YouTube somehow?

**Comment by alexesprit** [comment]
I've just found the [get-youtube-chapters](https://www.npmjs.com/package/get-youtube-chapters) package for parsing chapters from a video description. I'm curious how it works compared to YouTube's internal parser.

**Comment by CTimmerman** [comment]
You're fast. I'm currently manually scrobbling parts of https://www.youtube.com/watch?v=7xO5XRv-hXw because the track names prefixed with "." aren't recognized and/or i've created too many new artists recently.
