### ISSUE TITLE
Some Youtube channels are not being scrobbled, others work fine.

### ISSUE THREAD

**Issue by KnowsyKnowsBest** [web-scrobbler/web-scrobbler#2732]
**Screenshots**
[Here are some screenshots](https://imgur.com/a/x48gwUR)

These channels does not have their music scrobbled for some reason. Other channels work fine. There might be more channels, but i cant recall those right now.

**Debug logs**
https://pastebin.com/T1JKDuDb
Those debugs should be the ones of interest. If not, tell me.

**Environment**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.40.1

**Comment by alexesprit** [comment]
Could you try to open "https://www.youtube.com/" (with "www")?

**Comment by KnowsyKnowsBest** [comment]
> Could you try to open "https://www.youtube.com/" (with "www")?
Opening www.Youtube.com was no problem. 
Tried playing a video from one of those channels (Wobblecraft) but the issue remained the same

**Comment by alexesprit** [comment]
Could you post any URL?

**Comment by KnowsyKnowsBest** [comment]
[Underground](https://www.youtube.com/watch?v=3vMYLUv8B9c&ab_channel=Underground)
[Wobblecraft](https://www.youtube.com/watch?v=46XF-4s564Y&ab_channel=Wobblecraft)
[MrSuicideSheep](https://www.youtube.com/watch?v=BVomQtrtMTM&ab_channel=MrSuicideSheep)
More examples
[Tom Days personal channel](https://www.youtube.com/watch?v=-Nr6bp9Cweg&ab_channel=TomDay)
[Epic Rap Battles Of History](https://www.youtube.com/watch?v=njos57IJf-0&ab_channel=ERB)
[Trap and Bass](https://www.youtube.com/watch?v=Q_2Snli7e3U&ab_channel=TrapandBass)

**Comment by alexesprit** [comment]
I can scrobble all of them.

**Comment by KnowsyKnowsBest** [comment]
Thats weird.. it isnt that huge of an issue, since can "manually" add scrobbles using another wesite. But it still irks me that it doesnt work. Nothing in the debug blog helped with the issue either?

**Comment by alexesprit** [comment]
I see nothing wrong in the log (there's an error, but it's not related to the issue).

Could you also grab logs of content scripts? We have the instruction on the same page. These logs contain non-relevant information, so make sure to add "Web Scrobbler" filter before copying contents.
![image](https://user-images.githubusercontent.com/1119267/107235412-b5bff800-6a35-11eb-9395-ba717692cc70.png)

**Comment by alexesprit** [comment]
By the way, have you enabled one of YouTube checkboxes in the extension options? If any of them is enabled, could you disable them, and check scrobbling again?

![image](https://user-images.githubusercontent.com/1119267/107236061-61694800-6a36-11eb-99c2-15d00e84567c.png)

**Comment by KnowsyKnowsBest** [comment]
> By the way, have you one of YouTube checkboxes enabled in the extension options? If any of them is enabled, could you disable them, and check scrobbling again?

Hey! That worked! I knew about that, but i was sure that i had disabled both. Apparently not, the. "Music" box was checked. 
This fixed it

**Comment by alexesprit** [comment]
That's good. But it's not should be fixed by toggling checkboxes.

Could you enable it again and provide logs of **content scripts**, as I asked above?

Also, could you enable any of options and send me a link to the video which is scrobbled for you?

**Comment by KnowsyKnowsBest** [comment]
ok here are the content scripts (i think)
chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/content/util.js:503 Web Scrobbler: Allowed categories: Music
chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/content/util.js:503 Web Scrobbler: Setting up observer
chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/content/util.js:503 Web Scrobbler: Used '#content' to watch changes.
chrome-extension://hhinaapppaileiechjoiifaancjggfjm/core/content/util.js:503 Web Scrobbler: Fetched category for M6tHyLnH6-I: Entertainment

for [this](https://www.youtube.com/watch?v=M6tHyLnH6-I&ab_channel=Wobblecraft) track
I re-enabled "Scrooble from Music Category" and it did not scrobble.

**Comment by KnowsyKnowsBest** [comment]
[This ](https://www.youtube.com/watch?v=Gf1kT2m57IQ&list=WL&index=327&ab_channel=UKF) track is scrobbled **with** the music-box checked

**Comment by alexesprit** [comment]
Sorry, I haven't noticed you said you have only "Music" category enabled only. All of them are from other categories (from Entertainment, mostly), so the extension does not scrobble them. Enabling Entertainment option should allow to scrobble these videos.

YouTube removed the category information from the description some time ago, and it makes even harder to understand why some videos aren't scrobbled. There's [an extension](https://chrome.google.com/webstore/detail/youtube-categories/eddhbfndofdkljemlhkldinjpbkhdpcm) that brings categories back again, but it replaces the number of subscribers, and personally I don't like this.

I knot the extension should display the video is blocked due to category settings (see #2303). I'll try to add it once I rework the extension core.
