### ISSUE TITLE
Bug with channels or videos related to mirrored dance practices

### ISSUE THREAD

**Issue by Mrmrjoe** [web-scrobbler/web-scrobbler#2738]
**Describe the bug**
The scrobber is having trouble to recognize musical videos from channels with the word 'MIRRORED', it happens with a lot of music videos or channels with this word, even if it's a full track playing at the video.

**How to reproduce**
1. Go to https://youtu.be/X_-IzWOOmNk or https://youtu.be/FPjbtai9rx0
2. See that the track ins't scrobbling at all.

**Expected behavior**
The behavior expected it's that the video should scrobble the track even if it's not the original channel, cause the format of most of the tittles are the same from most music videos or music audios on youtube.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.40.1

**Additional context**
I expect that you guys can solve it letting channels or videos with "Dance Practice" or "Mirrored" at least a track recognition question.
 
 
![2021-02-15 (1)](https://user-images.githubusercontent.com/79122240/108008647-926ded80-6fdf-11eb-8ee7-212285291473.png)
![2021-02-15](https://user-images.githubusercontent.com/79122240/108008654-9568de00-6fdf-11eb-8c1e-64755d89dc98.png)
![2021-02-15 (2)](https://user-images.githubusercontent.com/79122240/108008661-98fc6500-6fdf-11eb-9850-a0c065329edd.png)
![image](https://user-images.githubusercontent.com/79122240/108009710-07422700-6fe2-11eb-9bbe-9c7d32d96b9c.png)

**Comment by alexesprit** [comment]
I guess they are not in Music or Entertainment, and you allowed to scrobble from these categories only.

Check these options:
![image](https://user-images.githubusercontent.com/1119267/108020562-af311200-702d-11eb-9c84-f5cc3dd750f2.png)

**Comment by alexesprit** [comment]
```
Web Scrobbler: Fetched category for X_-IzWOOmNk: Education
```
