### ISSUE TITLE
Issue that it keeps bringing me the yellow box on the extention

### ISSUE THREAD

**Issue by Mazen0018** [web-scrobbler/web-scrobbler#2740]
I've been streaming for a while but this has been appearing up every while and then, it stopped working and isn't scrobbling anything. I've disconnected my Last.fm, then reconnected but the same message has been reappearing, and so far no new scrobbles have been scanned.
<img width="307" alt="Screen Shot 2021-02-17 at 10 26 27 PM" src="https://user-images.githubusercontent.com/69061409/108250726-03440f80-7170-11eb-84a6-a68d70681d89.png">

**Comment by alexesprit** [comment]
@Mazen0018 Is it still an issue for you? Yellow icons almost always means it's something wrong with authentication, but there are cases when Last.fm is down/has issues.
