### ISSUE TITLE
Artist not parsed

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#2744]
**Describe the bug**
Uploader is seen as the artist instead of it being parsed from the video title or metadata.

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=fSZCT147tTo

**Expected behavior**
Parse "BIF NAKED" from "BIF NAKED ~I Bificus [FULL ALBUM]".

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.40.1

**Comment by alexesprit** [comment]
It can be fixed by adding the tilde symbol to the list of artist-track separators. Have you seen other videos where `~` was used as a separator, or as a part of a song name?

**Comment by CTimmerman** [comment]
Probably as a separator. This similar tracklist does get completed with the artist: https://www.youtube.com/watch?v=Oe49MMOZZZg
