### ISSUE TITLE
song not scrobbling

### ISSUE THREAD

**Issue by skull** [web-scrobbler/web-scrobbler#2745]
https://www.youtube.com/watch?v=gTWa6DL0EeQ
this song is on last.fm, and even listed as music in the description but isnt being recognised by the scrobbler

**Comment by alexesprit** [comment]
Can't reproduce this.

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/109188291-d4e3b700-77a3-11eb-9dad-d04ebefcb489.png)
</details>

**Comment by alexesprit** [comment]
This video is in "People & Blogs" category, and you probably have at least one of these options enabled:
![image](https://user-images.githubusercontent.com/1119267/109307992-7fb2ae80-7852-11eb-8e49-e9104062eb06.png)
