### ISSUE TITLE
Artist and album not being scrobbled from YouTube Music

### ISSUE THREAD

**Issue by Mumumurilo** [web-scrobbler/web-scrobbler#2747]
I have just noticed this issue on Windows. All tracks I've been listening to are not being recognized due to the scrobbler only picking up the song name and album cover.

![image](https://user-images.githubusercontent.com/8595653/109894689-b3d00a00-7c6c-11eb-8840-5794b4bbd031.png)

I've used the extension on macOS during the whole day with no issues, so I believe it may be related to the OS (Windows).
I'm on Chrome ver. 88.0.4324.190.

**Comment by alexesprit** [comment]
I have the same issue. Looks like they updated website's internals, and now scrobbling is broken for everything.

**Comment by alexesprit** [comment]
I have the same issue. Looks like they updated website's internals, and now scrobbling is broken for everyone.

**Comment by Dare2python** [comment]
+1

**Comment by G4Zz0L1** [comment]
Yep, same thing on Chrome on Arch Linux. It doesn't involve only windows.

**Comment by olexandr-perepiyaka** [comment]
I have the same issue.

**Comment by alexesprit** [comment]
I see. I'll fix it when I come home.

**Comment by mpdgraev** [comment]
Fwiw:

I fixed it in a local build with 
artistSelector:  '.ytmusic-player-bar.byline .yt-formatted-string:first-child'
albumSelector:  '.ytmusic-player-bar .yt-formatted-string.style-scope.yt-simple-endpoint[href^="/channel/MPREb_"]'

Seems to work well, but don't have time to test it right now whether or not this breaks other things (I haven't used jquery in years).

**Comment by alexesprit** [comment]
It should not break anything. Note that there're also selectors to handle uploaded songs, and I guess they should be updated too. I have no uploaded tracks atm, so I cannot check it.

**Comment by mpdgraev** [comment]
Ah, I didn't know that the other selectors were for user uploaded tracks, using the x-th child approach has the advantage that both ytm tracks and user uploaded tracks both work without each needing 2 selectors, which is a bit easier on the eye imo.

Created a pull request since I had the code ready anyway now.

**Comment by alexesprit** [comment]
I submitted the new release (v2.41.0) which also includes fix by @mpdgraev. It will be available in store once this version will be reviewed.

When I was writing this comment, it was approved by AMO, and it's now available on Addons.mozilla.org.
