### ISSUE TITLE
Deezer scrobbling stopped working with version 2.41.0

### ISSUE THREAD

**Issue by abatistas1709** [web-scrobbler/web-scrobbler#2749]
Deezer scrobbling stopped working with version 2.41.0...

Can you help, please?

Tks in advance.

**Comment by alexesprit** [comment]
Can't reproduce.

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/110008078-5dc29b80-7d2c-11eb-88ca-1858edde5d04.png)
</details>

**Comment by abatistas1709** [comment]
> Can't reproduce.
> 
> Screenshot (Click to expand)

You're right. My mistake. Sorry.
