### ISSUE TITLE
Web scrobbler not working

### ISSUE THREAD

**Issue by vdekkernl** [web-scrobbler/web-scrobbler#2751]
It's seems the scrobbler isn't working as of yesterday. It picks up the song title, but not the band or album. So it doesn't scobble.

**Comment by alexesprit** [comment]
Can't reproduce.

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/110092232-6c4f9800-7daa-11eb-9647-4a86ec732ce7.png)
</details>

**Comment by vdekkernl** [comment]
Hmm strange.... I have this with all the songs. This didn't happend before with the same songs:

![image](https://user-images.githubusercontent.com/4243727/110098883-fa268580-7da0-11eb-9d64-81c0d9af5fd9.png)

**Comment by alexesprit** [comment]
Make sure you have v2.41.0 installed.

**Comment by vdekkernl** [comment]
I had it already, but it seems it works again. I'm playing the songs that didn't scrobble and now they do! Weird but okay.

**Comment by alexesprit** [comment]
Good! I'm glad it's working for you. :)
