### ISSUE TITLE
Add turntable.fm

### ISSUE THREAD

**Issue by laurenraddatz** [web-scrobbler/web-scrobbler#2752]
can you add support for turntable.fm?

**Comment by inverse** [comment]
Looks like it's invite only at the moment - is it a relaunch of the old one?

**Comment by laurenraddatz** [comment]
Yes it is. The password is "speakeasy" if you want to get in. Otherwise I can make a PR!

**Comment by edelstone** [comment]
Oh hell yeah.

**Comment by alexesprit** [comment]
> yes it is. the password is "speakeasy" if you want to get in. otherwise I can make a PR!

Feel free to open a PR! :)
