### ISSUE TITLE
YouTube Music unique ID.

### ISSUE THREAD

**Issue by jaccarmac** [web-scrobbler/web-scrobbler#2758]
Currently, the YouTube Music connector does not store edits to tracks, as it does not have a `getUniqueID` implementation. Porting this function from the normal YouTube connector is trivial; However, I'm curious if there are any ideas about sharing unique ID's between certain connectors. In the YouTube/YouTube Music case, tracks will have the same ID on both sites. Thus, it could be useful for edits to work across both connectors.

**Comment by alexesprit** [comment]
It's fine to have shared IDs for multiple services, especially if they are connected to each other (in this particular case YouTube Music and YouTube).

**Comment by alexesprit** [comment]
> Currently, the YouTube Music connector does not store edits to tracks,

By the way, the extension actually stores edited tracks even if a now playing tracks has no `uniqueID` property. The ID is calculated based on track info.

**Comment by jaccarmac** [comment]
> By the way, the extension actually stores edited tracks even if a now playing tracks has no `uniqueID` property. The ID is calculated based on track info.

I must have missed this, or encountered a bug, then. Now I see my edits reflected on YouTube Music where I did not before.

> It's fine to have shared IDs for multiple services, especially if they are connected to each other (in this particular case YouTube Music and YouTube).

Does this functionality already exist to hook into? And if not, where do edits get persisted? Grep hasn't helped me, though I haven't done a deep dive.

**Comment by alexesprit** [comment]
Sorry, I don't understand what functionality are you talking about.

[src/core/background/storage/saved-edits.model.js](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/core/background/storage/saved-edits.model.js) is where all logic for edits placed.

**Comment by jaccarmac** [comment]
Thanks, I'll read around that.

I was referring to the comment from here: https://github.com/web-scrobbler/web-scrobbler/blob/ffe5bceb7275bdc62b0dad4d9ca03c52d3eb4b7e/src/core/content/connector.js#L310-L312

If the unique ID's are namespaced by connector ID, I imagine there would need to be a way for two connectors to use the same namespace for their edits.

**Comment by alexesprit** [comment]
We never had namespaced IDs; perhaps this comment was added before edited tracks were implemented, and the original idea was to separate IDs.

Thanks for the reference, I'll update this comment.

**Comment by jaccarmac** [comment]
Good to know. I remember discovering the comment when I implemented the pan y rosas discos connector. Hopefully my implementation isn't bugged absent namespaces.
