### ISSUE TITLE
Plex/Quoboz not Scrobbling 

### ISSUE THREAD

**Issue by ZGolem** [web-scrobbler/web-scrobbler#2764]
Plex and Qobuz are not recognizing music being played, I've tried different browsers, rebooting, and even removing the extension and reassigning the account, nothing will work. Spotify, Deezer, and Youtube all work for me, unfortunately, I don't have Tidal so I can't test that (I'd like to cause it's also high res), is anyone else getting issues with plex or qobuz?

-   OS: Windows 10
-   Browser: Chrome/Firefox 
-   Extension version: 2.41.0

As for Plex I;ve also done a database update, and closed and reopened the server, neither of which fixed the issue

Update: Tested on another device, still not working

**Comment by jaccarmac** [comment]
Tidal's working.

I'm unfamiliar with both Plex and Qobuz, but I think Plex, at least, can run as a server. Is that correct? If so, make sure that the URL it's running on is being recognized.

Plex matches: https://github.com/web-scrobbler/web-scrobbler/blob/d8e62656f4e0de74b264ca871bbfd770f41e9068/src/core/connectors.js#L232-L237

Qobuz matches: https://github.com/web-scrobbler/web-scrobbler/blob/d8e62656f4e0de74b264ca871bbfd770f41e9068/src/core/connectors.js#L1567-L1569

**Comment by ZGolem** [comment]
> .plex.tv/web/

Yes, these are both matching, I've even added app.plex.tv to it and it's still not working

**Comment by jaccarmac** [comment]
1. When you visit the pages, is the extension icon greyed out completely or does it just not recognize anything as playing?
2. Are you comfortable debugging the extension, and if so what happens to the background page when visiting those sites?

**Comment by alexesprit** [comment]
I've reproduced the issue on https://app.plex.tv/, but it works on localhost:32400 for me.
