### ISSUE TITLE
Add turntable.fm

### ISSUE THREAD

**Issue by fluteds** [web-scrobbler/web-scrobbler#2765]
**Provide information about website**

This website is what inspired plug.dj and uses the same features as plug.dj. It's been revived 10 years after initial closing.

> "Listening to music has always been one of those experiences that's better together, whether at a concert or hanging out with friends. But the digital music revolution so far has been defined by a solitary experience. Turntable is bringing the social value of music to the digital music experience by letting people experience and discover music together."

**Additional context**

At the moment, turntable.fm uses YouTube to stream videos and also uses a direct mp3 uploader. While I'm not sure if there is API for this mp3 uploader/database it would be easily obtainable to grab the currently playing YouTube title and artist off of the display as shown in the image below. 

-  Room URL format
turntable.fm/{room_name}

The website is in it's early teething stages with updates expected to follow. 

**Image of turntable.fm**

![image](https://user-images.githubusercontent.com/34608301/110785843-50913980-8263-11eb-91ee-4cb6e8cd4c98.png)

**Comment by alexesprit** [comment]
Hi! It was already added in #2763, and will be included in next version,
