### ISSUE TITLE
Add playlist-randomizer

### ISSUE THREAD

**Issue by Quorthon13** [web-scrobbler/web-scrobbler#2786]
www.playlist-randomizer.com is a simple youtube playlist randomizer. It exists because youtube shuffle feature [does not work properly with playlists](https://piunikaweb.com/2020/10/30/youtube-shuffle-feature-hasnt-worked-properly-with-longer-playlists-for-quite-some-time-no-official-fix-yet/). The user simply provides the playlist's URL and the website plays the shuffled playlist using an embedded youtube component.

I'll also provide an example playlist for testing purposes: 
https://www.youtube.com/playlist?list=PL2NfnFyWyDdJKfdl-MiIpKQTGBOyO4Hk6

If there is already another connector from a website with a youtube shuffle feature, please inform me.

**Comment by willfolsom** [comment]
I started to code this out:

`'use strict';

Connector.playerSelector = '.html5-video-player';
Connector.pauseButtonSelector = '.ytp-play-button';
Connector.durationSelector = '.ytp-time-duration';

const videoTitleSelector = '.html5-video-player .ytp-title-link';
let { artist, track } = Util.processYtVideoTitle(
    Util.getTextFromSelectors(videoTitleSelector)
)
Connector.artistSelector = artist;
Connector.trackSelector = track;
`

but the YT video is tucked in an iframe, and a lot of the elements have generic MUI class names. Maybe someone with more knowledge can find this stub useful.

**Comment by Quorthon13** [comment]
I don't know if this will be of any use, but the website is open source.
https://github.com/stefanpaduraru/playlist-randomizer

**Comment by alexesprit** [comment]
@willfolsom we don't need to use YouTube iframe, the video title is available in the website `document`. You can quickly check it by executing `document.querySelector('.Mui-selected').textContent` in the DevTools console.

**Comment by willfolsom** [comment]
@alexesprit Thanks for the comment. I'll take another crack at it in a bit.

**Comment by alexesprit** [comment]
Closed via #2798.
