### ISSUE TITLE
Tidal not scrobbling

### ISSUE THREAD

**Issue by saturnz1** [web-scrobbler/web-scrobbler#2787]
Tidal web just updated and the extension broke on the site. The extension icon shows in red

Logs: https://pastebin.com/jNeT8tRc

-   OS: Windows 7
-   Browser: Opera
-   Extension version: 2.41.0

**Comment by inverse** [comment]
@jaccarmac is this one you could look at?

**Comment by jaccarmac** [comment]
Yeah, I will. My Tidal just updated, but I haven't reloaded yet so my extension is working fine for now.

**Comment by jaccarmac** [comment]
@saturnz1, If you are able to pull that branch, please do and give me any feedback you have.

The "Use short track names" option no longer has any effect.

The way albums are handled has also changed. If you want albums to be scrobbled correctly, either play from an album page or open the maximized now playing window and click on credits. You should be able to minimize the window again after doing that.

I don't use the full screen view, but it seems like it may have changed as well.
