### ISSUE TITLE
Apple Music Web Player Not Scrobbling

### ISSUE THREAD

**Issue by DontAskWy** [web-scrobbler/web-scrobbler#2790]
This happened at around midnight. After, the web scrobbler extension icon became gray, and when clicked, a pop-up would say that this website is not supported. I know potential workarounds to issues like this include things like creating a custom url, I'm just curious how much my URLS have to match to work.

**Comment by alexesprit** [comment]
> I know potential workarounds to issues like this include things like creating a custom url, I'm just curious how much my URLS have to match to work.

What are your URLs? For me it's still "music.apple.com".

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/112284881-c43b3980-8c9a-11eb-963d-8a83fc03b129.png)
</details>

**Comment by DontAskWy** [comment]
my url is still music.apple.com as well, I actually managed to get it to scrobble again by removing and reinstalling the extension, only catch is that it doesn't show album art when scrobbling. Scrobbling is still perfectly fine on mobile.

**Comment by alexesprit** [comment]
> that it doesn't show album art when scrobbling

Indeed.

I've just checked the Apple's website, and I see they provide small album art images (88x88 px). I would keep the connector as is, and let the extension to load missing arts via Last.fm.
