### ISSUE TITLE
Plex not scrobbling

### ISSUE THREAD

**Issue by EwanRoycroft** [web-scrobbler/web-scrobbler#2791]
**Description**
Similar to issue #2764, my Plex app is no longer scrobbling. 
I have tried on both app.plex.tv and on the localhost:32400. Like @alexesprit noted, the extension does work when using localhost, but not when using app.plex.tv. 

**Environment**
-   OS: Mac
-   Browser: Firefox
-   Extension version: 2.41.0

**Comment by alexesprit** [comment]
What's your Plex UI version?

**Comment by alexesprit** [comment]
Works fine for me on Plex UI 4.53.0 / Plex 1.22.1.4228 on localhost and Plex UI 4.54.4 on remote.

**Comment by EwanRoycroft** [comment]
I have Plex UI 4.51.3 / Plex 1.22.0.4163 on localhost and Plex UI 4.54.4 on remote. 
Are you also using Mac OS / Firefox 87.0?

**Comment by alexesprit** [comment]
I'm on Windows 10 / Latest MS Edge. Btw, when I said it works fine for me I mean the version from the master branch, not from store.

**Comment by benmayne** [comment]
for what it's worth, also stopped about the same time for me. 

plex ui Version 4.54.4
plex server: 1.22.0.4163
brave: 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
ubuntu 18.04.05

**Comment by benmayne** [comment]
2.42.0 works for me now.

**Comment by alexesprit** [comment]
Yup, it should work fine now. :)
