### ISSUE TITLE
iheartradio.com not scrobbling

### ISSUE THREAD

**Issue by j4g3rb0mb3d** [web-scrobbler/web-scrobbler#2792]
**Describe the bug**
iheartradio songs recently stopped scrobbling. The songs aren't being recognized.

Issue can be recreated by going to https://www.iheart.com/live/rock-955-857/ and listening to the station. You'll notice that songs aren't being scrobbled.

**Comment by alexesprit** [comment]
This particular station does not share information about now playing tracks. But I checked another one with that info available, and I reproduced the issue.

**Comment by j4g3rb0mb3d** [comment]
For clarity, I was able to scrobble from that site as early as last week using Web Scrobbler.
