### ISSUE TITLE
Add QueUp.net

### ISSUE THREAD

**Issue by dreamingbleu** [web-scrobbler/web-scrobbler#2793]
QueUp is a new version of the deactivated website Dubtrack that was already compatible in the past. People create rooms on this website to listen music from YouTube and Soundcloud.
It seems to have the same design and funcionality that it had in Dubtrack, so I think it's not hard to make a new connector.
https://www.queup.net

Thank you!

**Comment by alexesprit** [comment]
> of the deactivated website Dubtrack

Hmm, thanks for the info. I'll take a look on it.
