### ISSUE TITLE
web scrobbler stops working every weekend?

### ISSUE THREAD

**Issue by d4goo** [web-scrobbler/web-scrobbler#2796]
Firstly, apologies if this has been reported before and I've missed it.  I did search as deeply as I could.

Bug: I use the Chrome extension daily, and every weekend (usually from approx Sat 9AM to Sun 9AM, UK time) the extension stops working. 

**How to reproduce**
1. Play a track on music.youtube.com
2. Extension scrobbling initially looks good/normal (first screenshot)
3. After approx 50% of the song, it goes yellow and notes a problem (second screenshot)

**Expected behavior**
I would expect it to work as it does the other 5-6 days per week.

**Screenshots**
see below

**Debug logs**
included a portion as a screenshot
![IMG_9751](https://user-images.githubusercontent.com/78661725/112719500-2e4d1c00-8ef1-11eb-973b-bc557e7f8a46.jpg)
![IMG_9752](https://user-images.githubusercontent.com/78661725/112719501-3016df80-8ef1-11eb-9ba9-1cd706ec00da.JPG)
![Screenshot 2021-03-27 at 11 32 06](https://user-images.githubusercontent.com/78661725/112719503-30af7600-8ef1-11eb-8870-69dbeb3895c0.png)
![Screenshot 2021-03-27 at 11 34 05](https://user-images.githubusercontent.com/78661725/112719504-30af7600-8ef1-11eb-9a9c-5cf0d83ade90.png)

**Environment (please complete the following information)**
-   OS: Mac OS Big Sur 11.2.3
-   Browser: Chrome
-   Extension version: v2.41.0

**Additional context**
As noted, only occurs on weekends.  This usually resolves after 24 hours, though scrobbles are not possible during this period.  The screenshots of logs/errors shows the response of 'too many scrobbles', but it's not operating any differently to how it would be the rest of the week, hence the confusion.  Also worth noting that it's only scrobbles using this extension that regularly fail during this time.  Spotify, MacOS Scrobbler and Plex all work as normal.

**Comment by alexesprit** [comment]
> web scrobbler stops working every weekend?

Yes, we have a special code that prevents scrobbling on weekend. :)

Okay, to be serious, it's not the extension fault. You can see it in the error description - Last.fm for some reason blocks your requests to scrobble tracks you listen to. Obviously, we don't spam scrobble requests, only one request per each track.

**Comment by d4goo** [comment]
I know what the errors say :).  I'm curious about why my scrobbling only breaks for 24 hours or so on the weekend.  The behaviour is the same 7 days a week, but this error only happens 1 day per week.  It's all legit, not spamming.  There must be something deeper than last.fm not allowing it 1 day per week?

**Comment by alexesprit** [comment]
AFAIK, Last.fm blocks for too many requests from a single IP, and you probably share the same IP with someone else (e.g. you're under NAT). And I guess scrobbling activity level is higher, so you have more chance to be blocked :)

It could be partially solved by implementing #211.

**Comment by d4goo** [comment]
All very strange - but last.fm is definitely strange at times!  I'll have a look at #211 in any case.  Cheers!

**Comment by alexesprit** [comment]
By the way, you mentioned other scrobblers work fine. Do they work fine on the same device (or to be more precise, in the same network)?

**Comment by d4goo** [comment]
Same device, same network.

Note that this is my only web-based scrobbler through.  Spotify is via their app, not the web.  Same with Last.fm Scrobbler for OS (scrobbling from iTunes).  Plex is on their tvOS app.

**Comment by alexesprit** [comment]
Aha, thanks for the info. They all use the same network to send requests; perhaps, Last.fm takes API keys into account.

**Comment by d4goo** [comment]
Sure.  Still curious that the issue only happens 1 day per week, and always the same day.  It never happens mid-week.  Usage patterns are fairly stable every single day.  It's just really odd.
