### ISSUE TITLE
Stops scrobbling half way through song (Chrome)

### ISSUE THREAD

**Issue by iJxshy** [web-scrobbler/web-scrobbler#2799]
It was working fine for about a day but now every time I play a music video it works for around half the video then turns orange saying there's a problem and doesn't scrobble, please help!

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

This one can be related to #2796.

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by iJxshy** [comment]
where do you find the debug logs sorry, is it view, import, export etc?

**Comment by alexesprit** [comment]
Have you checked the howto I posted above?

**Comment by iJxshy** [comment]
https://pastebin.com/nnvj2B4Q

**Comment by iJxshy** [comment]
I noticed it says too many plays but it still counts through spotify so why wouldnt it count through my apple music, itunes or web?

**Comment by alexesprit** [comment]
https://github.com/web-scrobbler/web-scrobbler/issues/2796#issuecomment-808732275

**Comment by iJxshy** [comment]
So I guess for one day a week on the weekend you can only scrobble through spotify?
