### ISSUE TITLE
scrobbles for the JBFM radio

### ISSUE THREAD

**Issue by ssertt** [web-scrobbler/web-scrobbler#2809]
Hello, greetings. I would love it if you implemented scrobbles for JBFM radio, which is very well known in Rio de Janeiro, which has been on the air since the 70s and I have been listening via internet for at least 7 years.

The site is: https://jb.fm/player/
An account is not necessary

Thank you guys, I loved your initiative and dedication. Have a good day :)

**Comment by jfcabral** [comment]
Hi

With PR #2873 this is now available since https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.44.0

So I'd say this can now be closed 😃 @ssertt @alexesprit

**Comment by ssertt** [comment]
Thank you!! ❤️
