### ISSUE TITLE
Is Web Scrobbler/ The Last.fm app down?

### ISSUE THREAD

**Issue by iJxshy** [web-scrobbler/web-scrobbler#2810]
Since like yesterday afternoon every time i scrobble a song on either YouTube or edge, half way through the scrobbler extension turns yellow and says there's an error, as well as the lastfm failing to update scrobbles saying they will be saved for later? Is this just a bug i have t wait out or is there something I can do? Thanks!

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by iJxshy** [comment]
https://pastebin.com/jL9f7UA5

**Comment by iJxshy** [comment]
Spotify seems to be the only one working fine

**Comment by alexesprit** [comment]
```
{
  "error": 29,
  "message": "Rate Limit Exceeded - Too many scrobbles in a short period. Please try again later."
}
```

Ref #2796.
