### ISSUE TITLE
Apple Music not scrobbling anymore

### ISSUE THREAD

**Issue by gabrielesanti** [web-scrobbler/web-scrobbler#2817]
**Describe the bug**
The extension is not scrobbling on music.apple.com anymore 

**Environment (please complete the following information)**
-   OS: Mac OS 11.2
-   Browser: Chrome 89.0.4389.114
-   Extension version: 2.42.0

**Comment by alexesprit** [comment]
Can't reproduce.

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/114162896-3914a180-9932-11eb-99df-3a0ed6924094.png)
</details>
