### ISSUE TITLE
can't sign in to last.fm

### ISSUE THREAD

**Issue by martouss** [web-scrobbler/web-scrobbler#2818]
I want to sign to last.fm but on the options page, the link doesn't work.

OS: Ubuntu
browser: Firefox 87.0 (64-bit)

**Comment by alexesprit** [comment]
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-the-options-page

**Comment by martouss** [comment]
@alexesprit after multiple installs and installing the problem has been solved.
