### ISSUE TITLE
Local files not recognized (Spotify)

### ISSUE THREAD

**Issue by flickur** [web-scrobbler/web-scrobbler#2820]
I'm using Spotify desktop app and keeping spotify web open for scrobbling with web-scrobbler. If I'm playing a local file, it doesn't get recognized. Probably cause local files aren't available on Spotify web to listen to, but the track info is still there like seen below. So I was wondering if the scrobbler could still pull the info from there?

![image](https://user-images.githubusercontent.com/40724723/114703622-31883a80-9d2e-11eb-8467-8f44f362bb45.png)

![image](https://user-images.githubusercontent.com/40724723/114703645-3b11a280-9d2e-11eb-8031-c9cf898c0f32.png)

but not recognized:
![image](https://user-images.githubusercontent.com/40724723/114703847-875ce280-9d2e-11eb-9583-812568a31c28.png)

**Comment by alexesprit** [comment]
Yes, it's possible. There was the logic for podcasts/ads, that prevented scrobbling local files.
