### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ronajestem** [web-scrobbler/web-scrobbler#2824]
scrobbler extension on google has been crushing so many times, its not counting my scrobbles for like 30 minutes?
![image](https://user-images.githubusercontent.com/82675943/115071548-ab6b2000-9ef6-11eb-8466-0497e67f6271.png)

**Comment by Invisible40** [comment]
I have this issue too.  I'm playing music on a YouTube playlist.

**Comment by patriciawf** [comment]
I'm getting this issue as well, using Firefox on my mac (trying to stream from Amazon Music).
