### ISSUE TITLE
Automatically add album title to manual scrobbles

### ISSUE THREAD

**Issue by speedycatfish** [web-scrobbler/web-scrobbler#2830]
**Is your feature request related to a problem? Please describe.**
All the tracks I have manually edited (on Youtube) have empty album titles, and I think it would be cool if the web scrobbler automatically added the album title like it does for tracks that aren't edited. 

**Describe the solution you'd like**
After manually editing a track, if the album title is left empty, the extension would automatically grab the album title (if one exists) from Last.fm and add it to the scrobble.

**Describe alternatives you've considered**
I could manually add all the album titles, but that would be a pain as I have around 500 edits. Also, the extension already automatically adds the album for tracks that aren't manually scrobbled (on Youtube), so I feel like this feature wouldn't be too hard to add.

**Comment by alexesprit** [comment]
There was an issue where a user asked not to grab album title, if it was edited. :)

**Comment by speedycatfish** [comment]
I guess you could make it an option then? I understand if you don't want the album title changed if you added your own one, but if you leave the album title empty, I don't really see the issue with automatically getting the album title. Oh well.
