### ISSUE TITLE
https://www.oxigenio.fm/

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#2835]
**Provide information about website**
Radio station based in Lisbon, PT

There is a player on the website that scroll information about the current program and the music being played, in blue

![image](https://user-images.githubusercontent.com/4522620/115844563-3df04f80-a420-11eb-9bd2-1f69fedf510b.png)

**Additional context**
No account needed

**Comment by fckawe** [comment]
I tried to build a connector for oxigenio.fm, here's the content so far:

```
'use strict';

Connector.playerSelector = '.wp-lunaradio.lunaaudioplayer';

Connector.artistTrackSelector = 'div[id^="wp"][id$="texttitle"] span:nth-child(1)';

Connector.playButtonSelector = 'div[id^="wp"][id$="buttonplay"]';

Connector.onReady = Connector.onStateChanged;
```

It seems to work pretty well. But quite often the player shows information that doesn't seem to be a "artist - track" combination, but rather the name of a show or something like that. A few minutes before it showed "hip-hop - instrumental" for example, or this:

![image](https://user-images.githubusercontent.com/1059389/157906410-2179d627-89ca-4ca9-ac9e-67868f374056.png)

So, the connector would scrobble these "titles", which imho is pretty nonsense. I don't have a clue how to prevent that, since it doesn't seem to follow any rules.

Ideas anyone?

**Comment by inverse** [comment]
@fckawe thanks for looking! 


You could try adding something like

```js
Connector.isStateChangeAllowed = () => {
	return Util.getTextFromSelectors(Connector.artistTrackSelector).includes('-');
};
```

Which would restrict the scrobbling to when it matches `-` in the matcher.

**Comment by fckawe** [comment]
@inverse Hmm, that wouldn't scrobble regular tracks either, would it?

The connector has to "understand" that "Oxigenio - Insistencia!" isn't a track to scrobble but "Nirvana - Lithium" is.

Okay, it could check if the artist equals "Oxigenio" and if so doesn't scrobble (assuming that "Insistencia!" is a show on that radio and so this could follow a general pattern like "Oxigenio - Show name").

But what about "Hip-hop - Instrumental", then? Doesn't seem to contain an artist at all and looks like some kind of "generic track name".

**Comment by inverse** [comment]
@fckawe Ahh perhaps I misinterpreted the needs and lacking PT language skills. 

Yeah will be a tough one to implement is track names are not actual unless you can map a list of things to ignore.

**Comment by pedrojvaz** [comment]
Have a look at the
https://onlineradiobox.com/pt/oxigenio/playlist/?cs=pt.oxigenio&lang=en&tzLoc=Europe%2FLisbon&useStationLocation=1

Because it changes, I'm also putting a screenshot for reference
![image](https://user-images.githubusercontent.com/4522620/158038418-f944259e-72d8-43e6-a403-86212765a287.png)

Here are some rules I could derive:
1. If there is no dash in the name, then it's a show. Example, first row is the show "A REVOLTA DO VINYL COM RICARDO GUERRA", or a bit below "INTERFERENCIAS COM TO RICCIARDI". Songs played in that radio show are not made available. Maybe you could make the artist the station name and tag the song as the radio show's name?
2. Each song with the name Oxigénio is actually an _ident_ (https://en.wikipedia.org/wiki/Station_identification), so it's safe to ignore them all, or keep them, since they are small enough to skipped (too short?)

Thanks for your effort!

**Comment by fckawe** [comment]
@pedrojvaz Alright, sounds doable. Thanks for the clarification. I'll give it a try... disabling scrobbling everytime the artists/name-element starts with "OXIGENIO" or doesn't contain a dash.

(That won't work properly if there's a show name containing a dash, of course. And the "HIP-HOP - INSTRUMENTAL" I mentioned before would be scrobbled, too. But I think that's acceptable, then...)

**Comment by inverse** [comment]
Fixed in https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.56.0 - thanks @fckawe
