### ISSUE TITLE
Uploaded tracks on YouTube music not recognized 

### ISSUE THREAD

**Issue by gregersn** [web-scrobbler/web-scrobbler#2838]
As of yesterday (April 23rd 2021), only the title of the track is automatically recognized when playing uploaded track on YouTube Music.

Tracks that are provided by YouTube Music still works okay.

Clicking the icon and adding artist manually then scrobbles the track.

Tested in both Chrome and Firefox on Linux.

**Comment by bpepple** [comment]
Can confirm this bug.

**Comment by no452** [comment]
This seems to be the same issue I reported in #2833. Didn't realise you could sort of work around this by filling in the artist name manually. Good call!

**Comment by beanoboo** [comment]
I have the same issue with it in Chrome. No uploaded tracks to YouTube music scrobble. The track name itself is recognized. However, the artist is not. I tried manually entering the artist name on one track. It took at first but game me that yellow error box about halfway through the song. Tried separate computer and Chrome restarts. Same issue. Cleared my browser history, uninstalled/reinstalled/relinked the scrobbler to my profiles, and had the same issue. Other scrobbling apps work just fine (i.e. Android-linked ones). Get well soon!

**Comment by yayuyokitano** [comment]
This is caused by an update to ytm behind the scenes.
I have updated my PR #2834 to include self-uploaded tracks.

**Comment by jaccarmac** [comment]
Did the recent PR introduce a regression? The extension isn't picking up the artist from [Rasputin by Majestic & Boney M](https://music.youtube.com/watch?v=cZwYpAh3bXQ) automatically.

**Comment by alexesprit** [comment]
@jaccarmac Seems like so. I have the same thing.
