### ISSUE TITLE
No longer scrobbling my personal library?

### ISSUE THREAD

**Issue by maxcastle64** [web-scrobbler/web-scrobbler#2846]
This seemed to be working fine until the last couple of days, but currently any songs that I uploaded to my own library on You Tube Music don't seem to be scrobbling.  If I select a mix or artist thru the regular channels, they show up ok.  Has something changed whereby the scrobbler doesn't register files that somehow aren't part of You Tube's native catalogue (not sure if that's the right language, but I assume you know what I mean...)

**Comment by alexesprit** [comment]
What is the extension version you have installed?

**Comment by maxcastle64** [comment]
Hi Alexey – it’s Version 2.42.0.  I do note now that you ask, that there seems to be a new release!  I wasn’t notified of an update, but I can try to run it myself…

 

C

**Comment by maxcastle64** [comment]
Ok, actually I’m stumped and don’t know how to update it.  😊

 

C

 

 

From: ***@***.*** ***@***.***> 
Sent: April 27, 2021 2:35 PM
To: 'web-scrobbler/web-scrobbler' ***@***.***>
Subject: RE: [web-scrobbler/web-scrobbler] No longer scrobbling my personal library? (#2846)

 

Hi Alexey – it’s Version 2.42.0.  I do note now that you ask, that there seems to be a new release!  I wasn’t notified of an update, but I can try to run it myself…

 

C

**Comment by maxcastle64** [comment]
Is the only way for me to update thru the Microsoft store (i.e. is it a matter of waiting for them to make the most recent version available?)

**Comment by alexesprit** [comment]
If you're using MS Edge, there're two ways for you:
- Update via Microsoft Edge Add-ons
- Install the extension from Chrome Web Store

For MS Edget I'd recommend the first option.

By the way, it was approved on Microsoft Edge Add-ons about half an hour ago.

**Comment by maxcastle64** [comment]
OK, it’s still showing 2.42.0 at my end, and I’m getting the same behaviour, so will wait a while and then reinstall it…

 

Thanks so much!

 

Chris

**Comment by maxcastle64** [comment]
OK, new version installed and we’re back in business!  Many thanks for your help!  😊

 

C
