### ISSUE TITLE
Spotify tracks are scrobbled on 30 seconds

### ISSUE THREAD

**Issue by sc113** [web-scrobbler/web-scrobbler#2847]
Scrobbling used to happen in the first ~2 minutes of the track, but about 2 weeks ago it started happening in the first 30 seconds. The hidden settings (alt+click) are still set to 50% of composition

**Comment by alexesprit** [comment]
The extension no longer gets song duration from Spotify, so it fallbacks to duration from Last.fm or 30 seconds. I'll take a look on it.

**Comment by bogdan-astrohub** [comment]
I have the same problem. Also, what are the hidden settings?

**Comment by sc113** [comment]
> I have the same problem. Also, what are the hidden settings?

https://github.com/web-scrobbler/web-scrobbler/issues/453#issuecomment-598781704
