### ISSUE TITLE
Supress scrobble while editing

### ISSUE THREAD

**Issue by myfonj** [web-scrobbler/web-scrobbler#2849]
**Problem:**
When manual edit takes longer and automatic scrobble moment occurs, unfinished edit is discarded and "wrong" automatic scrobble is sent.

**Solution I'd like**
Do not send automatic scrobble while edit mode is active.

**Alternatives I've considered**
For "fuzzy" recognized tracks do not auto scroble at all, just, open playing notification in edit mode and wait for manual confirmation, or just #1560.

**Additional context**
Sorry if dupe, haven't found prior report. And as always, thanks for all the ext!

**Comment by yayuyokitano** [comment]
To be added in V3. Already working in the fork at least until you start playing a new song.
