### ISSUE TITLE
"MV" cut off

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#2858]
https://www.youtube.com/watch?v=5M_jh4CA8a8 name is "DMV", not "D".

**Comment by CTimmerman** [comment]
Conversely, "HD" is not cut off in https://www.youtube.com/watch?v=H3Ioxh3OTSU

**Comment by yayuyokitano** [comment]
> Conversely, "HD" is not cut off in https://www.youtube.com/watch?v=H3Ioxh3OTSU

This should be unrelated to the original issue, and should probably be submitted as an issue to web-scrobbler/metadata-filter
