### ISSUE TITLE
Radio Cuca (https://www.radiocuca.es/)

### ISSUE THREAD

**Issue by VincentOostelbos** [web-scrobbler/web-scrobbler#2864]
Hi! This is a fantastic extension, I love it.

If you could, please add support for [Radio Cuca](https://www.radiocuca.es/). In spite of the Spanish domain, it's a French-language radio station that plays a lot of French chansons (and some international hits).

There's a player at the top of the website, and there are several broadcasts (_émissions_) listed in a menu at the top. They are on [TuneIn](https://tunein.com/), and in fact the link for listen live (_Ecoute en direct_) only gives some information linking to TuneIn. However, on TuneIn [this station](https://tunein.com/radio/Radio-Cuca-s301983/) does not seem to provide artist and title information, which means Web Scrobbler currently does not work for this station via TuneIn. The player at the top of the actual website, however, does give this information.

Thank you very much for your consideration!

**Comment by inverse** [comment]
Will be in the next release!
