### ISSUE TITLE
Lofi.cafe

### ISSUE THREAD

**Issue by thomasbnt** [web-scrobbler/web-scrobbler#2868]
**Provide information about website**

**👉🏼 https://www.lofi.cafe/**

> Lofi music streams for studying, working, and relaxing.

![image](https://dc85enhu9zukf.cloudfront.net/gifs/NnMH7LDpZTPZS.gif)

**Comment by jfcabral** [comment]
Hi @thomasbnt 

Lofi.cafe is great but how can you see retrieve the song name and artist?

**Comment by thomasbnt** [comment]
> Lofi.cafe is great but how can you see the song name and artist playing?
@jfcabral hello! I don't know :c

**Comment by jfcabral** [comment]
I see 😮 

Well, I am by no means an expert on `web-scrobbler`, but, from my understanding, the extension works by parsing the song metadata from the website itself. 

For this reason, I'm not sure `loli.cafe` can be supported, as it doesn't show which song is being played 😞 

Maybe @alexesprit can share some lights on this.

**Comment by inverse** [comment]
Indeed the page would have to expose track meta data which Im not sure this site does... Although only checked on mobile

**Comment by jfcabral** [comment]
@alexesprit how do you handle these requests where the track metadata isn't available on the website?

Is it considered out-of-scope, or do you plan to integrate with Shazam or something like that in the future? 😅

**Comment by alexesprit** [comment]
@jfcabral if this website supports [MediaSession API](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) it's possible to use data via this API. Otherwise, these's no way to get track info. Can't say about Shazam/SoundHound/etc integration details, but I'm not sure if it's possible, though I haven't made a research on it.

**Comment by alexesprit** [comment]
No chances to use MediaSession API. :(

![image](https://user-images.githubusercontent.com/1119267/121050844-98bbeb80-c7c1-11eb-9e02-b9fa20b0051b.png)

**Comment by jbwharris** [comment]
From what I can tell this site is just hiding a [YouTube player](https://www.youtube.com/watch?v=-5KAN9_CzSA) that is doing a 24/7 live stream on multiple channels. The data is embedded in that video, which doesn't do us a lick of good in this instance. This one feels pretty unlikely unless they changed their format to expose the current track data on the site.
