### ISSUE TITLE
Amazon Music India not scrobbling songs unless I'm on the main page

### ISSUE THREAD

**Issue by melancholyxo** [web-scrobbler/web-scrobbler#2870]
When I play any playlist on Amazon Music India and I'm on the playlist page, the Web Scrobbler doesn't recognize the track until I leave the playlist page and return to the main page. 
This is the same with singles, albums, and everything else other than the main page. 
I don't know if this is specific to Amazon Music India, but that is what I use.

**How to reproduce**
1. Play any playlist on Amazon Music Web
2. Check Web Scrobbler (it doesn't scrobble the song)
3. Go to the main page
4. Check Web Scrobbler (it starts scrobbling the song)

**Expected behavior**
It should be scrobbling whatever song is playing regardless of what page I am on.
I like to have the playlist on a separate window so I see which song comes next. I'd rather not have to click into the playlist, and click back out to make sure it scrobbled the song.

**Screenshots**
![Screenshot 2021-05-21 at 18 08 05](https://user-images.githubusercontent.com/79659752/119159155-a6ead780-ba5f-11eb-8a0b-00ddab3a9aa7.png)
^^this is what happens when I'm in the playlist
![Screenshot 2021-05-21 at 18 08 27](https://user-images.githubusercontent.com/79659752/119159173-a9e5c800-ba5f-11eb-801b-adf0e2bb9b9e.png)
^^this is what happens when I'm on the main page

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Google Chrome
-   Extension version: v2.43.0

**Comment by alexesprit** [comment]
Perhaps, it related to other Amazon issues. Unfortunately, I have no access to Amazon and I can't check and fix that issues.

@inverse Could you check if it works fine on Amazon DE?

**Comment by oomoepoo** [comment]
I'm having the same issue with Amazon DE.

OS: Windows 10
Browser: Firefox 89
Extension version: 2.44.0
