### ISSUE TITLE
Website not supported

### ISSUE THREAD

**Issue by edsonmedina** [web-scrobbler/web-scrobbler#2875]
Nothing gets scrobbled.

![image](https://user-images.githubusercontent.com/5449/119389428-88851600-bcc3-11eb-9ffc-01f26d734ed3.png)

**Comment by inverse** [comment]
We need more context to diagnose this. What's the URL you were trying to scrobble from?

**Comment by edsonmedina** [comment]
https://music.youtube.com/

**Comment by inverse** [comment]
Not a premium subscriber but it's working for me. Are you able to provide any logs?

 Please follow https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by edsonmedina** [comment]
...and now it's suddenly working. Sigh. 
Sorry.

**Comment by inverse** [comment]
No need to say sorry 👍🏼 

Glad it worked out :)
