### ISSUE TITLE
Spotify non-stop scrobbling (paused tracks + inactive tabs)

### ISSUE THREAD

**Issue by sc113** [web-scrobbler/web-scrobbler#2880]
Со вчерашнего дня начались проблемы с нон-стоп скробблингом неактивного плеера. 
У меня была открытая вкладка со спотифаем (в хроме), ничего не проигрывалось, а в плеере стоял трек на 0:00, который я включал днём ранее. В течении часа аддон наскробблил этот трек около 10 раз. И даже если один скроббл уже прошел и аддон показывает зеленую галку - он всё равно продолжает скробблить. 
Кроме того, у меня стоит аддон, который делает вкладки неактивными (Auto Tab Discard) - это тоже не помогает со вчерашнего дня, аддон всё равно продолжает скробблить с неактивных вкладок со спотифаем.

== loose auto-translate:
Since yesterday, I started having problems with non-stop scrobbling from the inactive player. 
I had a tab open with spotify (in chrome), nothing was playing, and the player had a track at 0:00, which I had played the day before.  Within an hour the addon had scrobbled that track about 10 times. And even if one scrobble already passed and the addon shows a green tick - it still continues to scrobble. 
Also, I have an addon that makes tabs inactive (Auto Tab Discard) - that hasn't helped either since yesterday. The addon keeps scrobbling tracks even if the tabs with the spotify are inactive.

**Comment by sc113** [comment]
Теперь, вместо этого, если переключился на вкладку со спотифаем которая была неактивной, то аддон пишет что сайт не поддерживается. Если открыть новую вкладку - то пишет "Для начала включите любую композицию". Помогает только перезапущенный браузер - тогда проигрывает скробблит нормально, но и скробблинг также потом продолжается даже если ставить музыку на паузу.

**Comment by alexesprit** [comment]
Yes, seems like they changed play/pause button selectors.

**Comment by alexesprit** [comment]
I fixed this.
