### ISSUE TITLE
YouTube connector hangs in the "Looking up" state.

### ISSUE THREAD

**Issue by jaccarmac** [web-scrobbler/web-scrobbler#2881]
This seems to happen only for YouTube and for most videos. Occasionally the state will change to "scrobbling" for a short period, but other times it will skip straight to "scrobbled", giving no chance to edit the track information.

I haven't pulled logs or looked into a fix yet, and am mostly dropping this as a bookmark so I don't forget to investigate.

**Comment by alexesprit** [comment]
Hmm, it works fine for me now.

**Comment by jaccarmac** [comment]
I'll reopen if I keep encountering it. May have been an API issue: The severity seemed to decrease after my initial submission.
