### ISSUE TITLE
Request to add Stream Elements' Media Request to "Supported Websites"

### ISSUE THREAD

**Issue by aquinox77** [web-scrobbler/web-scrobbler#2884]
I use this to play media on stream, and would really appreciate it if I could scrobble the music I play from this site:

https://streamelements.com/dashboard/mediarequest/general

Cheers! <3

**Comment by alexesprit** [comment]
Looks like it's a duplicate of #2527.

By the way, I still don't understand what is this, and how we should add support for this. Have you any examples?

**Comment by alexesprit** [comment]
Close as a duplicate of #2527.
