### ISSUE TITLE
 Scrobbling from 1001tracklists.com not working?

### ISSUE THREAD

**Issue by Perica000** [web-scrobbler/web-scrobbler#2886]
Hi everyone,

I've noticed that scrobbling from a web-site 1001tracklists.com doesn't work anymore.
It used to work quite well, until recently...

I would be very very thankful if someone has a solution to this problem.

Kind regards
Peter

**Comment by WhiteAls** [comment]
@Perica000 it is fixed in #2869. Waiting for the merge

**Comment by Perica000** [comment]
> @Perica000 it is fixed in #2869. Waiting for the merge

@WhiteAls thank you!
