### ISSUE TITLE
(Unreleased Demo Version) cut off

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#2887]
https://www.youtube.com/watch?v=WYXuTxLKbME
"My Little Pony: Friendship Is Magic - Pinkie's Present (Unreleased Demo Version)" is parsed as "My Little Pony: Friendship Is Magic - Pinkie's Present". Same issue with the others on https://www.equestriadaily.com/2021/06/a-bunch-of-awesome-unreleased-demo.html

**Comment by alexesprit** [comment]
It's intentional behavior, I guess.

**Comment by CTimmerman** [comment]
Live versions usually sound a little different and have noise according to the place and time, but unreleased versions like these have different singers, lyrics, instruments, and lengths.
