### ISSUE TITLE
Remove track numbers from youtube mixes

### ISSUE THREAD

**Issue by stephanebruckert** [web-scrobbler/web-scrobbler#2892]
In this example https://www.youtube.com/watch?v=7tP-maqyNs0 

```
00:00 01 Concrete Wave - The Subway
04:20 02 Francisco Aguado - Earth (Original Mix)
10:31 03 Garpo – Vind
```

<img width="365" alt="Screenshot 2021-06-05 at 17 35 36" src="https://user-images.githubusercontent.com/1932338/120898814-8b1d2f00-c624-11eb-90d3-e4c0d5e1c4b9.png">
 
The scrobbler should remove the track number "02"

Edit: Actually in the above example we can't know if it's a track number. This is a better example cause it is followed by a `.` https://www.youtube.com/watch?v=NDJn0SQehb4

**Comment by stephanebruckert** [comment]
@stale the issue is still relevant

**Comment by stephanebruckert** [comment]
@Stale the issue is still relevant

**Comment by stephanebruckert** [comment]
@inverse how are you? 😺  would love it if you could allocate bit of your time for some of the stale PRs here, thanks!

**Comment by stephanebruckert** [comment]
@Stale the issue is still relevant

**Comment by fishstik** [comment]
On 25.0.0, still getting ![image](https://user-images.githubusercontent.com/4278123/150868727-ffab8c0d-a357-49eb-9adc-8e1a342b6239.png) with track numbers in the titles for https://www.youtube.com/watch?v=C2m8GUJDeVM.

**Comment by stephanebruckert** [comment]
@fishstik yeah this is an issue I have too.

Currently it works with separators for example `01. Track` but not without: `01 Track`. The reason for that is that we wouldn't want to remove `13` from a track that would be called `13 things`.

I'm not too sure how we should handle that, knowing we have a common regex for both mixes and single songs.

https://github.com/web-scrobbler/web-scrobbler/blob/c47f4f8ddd13368ba34b980c17e2613d62318d3f/src/core/content/util.js#L597

A solution could be, to look at other tracks/segments in the mix to determine if track numbers are used. Could be complex and require some refactoring though.

**Comment by fishstik** [comment]
@stephanebruckert ah, interesting problem. Though I think it's also failing to parse some properly separated numbers as well:
> 00:00 01 - Ari No Daiido
04:37 02 - Neko To Kororin No Fushigina Tabi
11:15 03 - Ryuhyo
20:41 04 - Dancer
21:33 05 - Nagai Rail
27:01 06 - Dandanbatake De Onigokko
32:48 07 - Yuyake
39:26 08 - Crosswind
45:20 09 - Ari No Daiido (Live)
50:50 10 - Ryuhyo (Live)

from https://www.youtube.com/watch?v=l0fkjusVcSY

**Comment by stephanebruckert** [comment]
> In this case it's confusing the numbers with the artist name.

Yes because `-` is how artists and tracks are usually seperated. To me, but I could be wrong, the normalized way to add track numbers is `01. Track`, then not everyone follows that.

> Maybe an machine-learning solution could work? XD
You are not too wrong about that, but maybe some simple logic to detect a suite of numbers in order to find the appropriate separator could work for us. I haven't checked though, if the current code for the current track/segment allows accessing the other tracks. But technically, looks feasible

**Comment by stephanebruckert** [comment]
@inverse do you believe we should create a new issue for that or re-open the current one?
