### ISSUE TITLE
Scrobbler has issues with artist names with a period (.) in them 

### ISSUE THREAD

**Issue by ile1** [web-scrobbler/web-scrobbler#2895]
Specifically, Mr. Bill is listed as Bill, same with Mr. Oizo being Oizo. It also lists A. G. Cook as G. Cook only

**Comment by alexesprit** [comment]
Where is it?

**Comment by ile1** [comment]
like if you come to a song on youtube and the scrobbler hasn't identified it yet, it will have the g. cook in place of a. g. cook and most people will just save it as g.cook
