### ISSUE TITLE
FMA (Free Music Archive) not scrobbling on album page (chart page works)

### ISSUE THREAD

**Issue by douglasawh** [web-scrobbler/web-scrobbler#2911]
**Describe the bug**
Album page scrobbling does not work.

**How to reproduce**
1. Go to a FMA album page (such as https://freemusicarchive.org/music/Audiobinger/quarantine-beats-vol-2). 
2. Press play button. 
3. Notice that scrobbling does not start.

**Expected behavior**
Scrobbling should begin after play button is pressed

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

https://pastebin.com/QqYKH6S3

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Firefox or Chrome
-   Extension version: 2.44.0

**Additional context**
Upon inspection of the logs, it looks like that the artist name is getting pulled as the track title and the track title is not getting pulled at all. I am guessing a track title is required (which makes sense).

**Comment by douglasawh** [comment]
does anybody need additional info for this?

**Comment by alexesprit** [comment]
Wow, they added a bottom player bar.

**Comment by douglasawh** [comment]
@alexesprit thanks for fixing! Do you need people to test this? Which version should it be released in?

**Comment by alexesprit** [comment]
@douglasawh this should be available in v2.45.0.

I tested this locally and everything worked fine for me, though I appreciate any testing/feedback, and we can improve the FMA connector together.
