### ISSUE TITLE
Youtube song wont detect on scrobbler extension

### ISSUE THREAD

**Issue by mapma1** [web-scrobbler/web-scrobbler#2918]
When viewing this song (https://www.youtube.com/watch?v=yygBx6-Ia6k) on YouTube, the scrobbler does not detect it. The song "ブラウニー／和ぬか【Music Video】", the song is also here (https://www.last.fm/music/%E5%92%8C%E3%81%AC%E3%81%8B/_/%E3%83%96%E3%83%A9%E3%82%A6%E3%83%8B%E3%83%BC)

and the youtube video is added to the last.fm profile there, so I don't know why it doesn't scrobble.

**Comment by douglasawh** [comment]
@mapma1 I have noticed that sometimes a browser restart fixes these issues. Have you tried that? It would be helpful if you uploaded the debugging info from the plugin.

**Comment by mapma1** [comment]
> @mapma1 I have noticed that sometimes a browser restart fixes these issues. Have you tried that? It would be helpful if you uploaded the debugging info from the plugin.

Here is the debug https://0bin.net/paste/dPkXU0cr#1L7iPE0Ohn88wjGRxz9T4rlid4jnn2NDshCyg4Qw4MX
Sorry for the late reply

**Comment by mapma1** [comment]
The issue still occurs and has not been fixed.

**Comment by inverse** [comment]
@mapma1 is this still an issue? I noticed this only when I have the scrobble from music category option enabled. With this off it picks up track shared.

![image](https://user-images.githubusercontent.com/713525/156940905-d15acec5-228a-4e29-ae4b-5900bb731710.png)

**Comment by mapma1** [comment]
> @mapma1 is this still an issue? I noticed this only when I have the scrobble from music category option enabled. With this off it picks up track shared.
> 
> ![image](https://user-images.githubusercontent.com/713525/156940905-d15acec5-228a-4e29-ae4b-5900bb731710.png)
> 
> ![image](https://user-images.githubusercontent.com/713525/156940918-242fbdf6-eb4a-411a-ba97-e398fe9a7b43.png)

Thanks for this reply! I enabled the "entertainment" category as well and it fixed my issue.
