### ISSUE TITLE
Connector for BNDCMPR.CO

### ISSUE THREAD

**Issue by summervillain** [web-scrobbler/web-scrobbler#2927]
**Provide information about website**
BNDCMPR.CO is a platform for sharing playlists of bandcamp tracks.
Sample playlist: https://bndcmpr.co/3ef4c6ad

**Additional context**
free sign up at bndcmpr.co
playlists are built as a series of bandcamp track urls eg. https://amarofreitas.bandcamp.com/track/dona-eni
Neither the current bandcamp or bandcamp daily connector magically works

Initial look, it seems Track Title and Artist are exposed but Artist is not explicitly tagged as a class (Title is first child, Arist is 2nd child of a classed element), and Album/Album Artists are not included in meta data

**Comment by summervillain** [comment]
Inspecting the page I see 
`<div data-v-3fd86466="" class="track-title"><h2 data-v-3fd86466="">Dona Eni</h2><h3 data-v-3fd86466="">Amaro Freitas</h3></div>`

**Comment by inverse** [comment]
Will be in the next release 👍🏼
