### ISSUE TITLE
Chrome tab not srobbling  from spoitfy  and VLC

### ISSUE THREAD

**Issue by TigermaskV** [web-scrobbler/web-scrobbler#2929]
im try to scrobble from Spotify  im chrome  nad the  scroobler mark just remain red

**Comment by TigermaskV** [comment]
will this issue be fixed

**Comment by alexesprit** [comment]
I guess it's related to #2932.

**Comment by alexesprit** [comment]
@TigermaskV please do not create duplicate issues (I mean #2930). This won't help to resolve them. :)
