### ISSUE TITLE
Primephonic Not Scrobbing

### ISSUE THREAD

**Issue by ZewenSenpai** [web-scrobbler/web-scrobbler#2931]
**Describe the bug**
Web Scrobbler does not detect music playing on Primephonic. I'm using  Windows 10 Chrome 64-bit Chrome 92.0.4515.107

**How to reproduce**
1. Go to primephonic
2. Play some music
3. Click on toolbar icon for web scorbbler
4. It will tell you to start playing music.

**Expected behavior**
It should scrobble.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: v. 2.44.0

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/61039687/126405607-87059e48-0581-4145-88a8-daa80994a5f7.PNG">

**Comment by TigermaskV** [comment]
im hvage the same issues on  Spotify and  VLC

**Comment by jfcabral** [comment]
Hi @ZewenSenpai 
This issue duplicates https://github.com/web-scrobbler/web-scrobbler/issues/2910
A fix is already pending review: https://github.com/web-scrobbler/web-scrobbler/pull/2913

@alexesprit would you plz check the opened PRs? 😅

**Comment by alexesprit** [comment]
@jfcabral Hi!

I'll try to find time on weekend to check and review PRs.

Sorry for being inactive.

**Comment by jfcabral** [comment]
It’s ok @alexesprit, we all have your lives 😉
Thank you for your response.
