### ISSUE TITLE
Connector code for iBroadcast needs update

### ISSUE THREAD

**Issue by WeGotApples** [web-scrobbler/web-scrobbler#2933]
The site iBroadcast went through a new update recently, which is likely the reason why it no longer scrobbles anything. A fix would be greatly appreciated. Thank you.

**Comment by ctrueden** [comment]
:+1: from me for updating the iBroadcast scrobbling—it's my primary way of listening+scrobbling these days.

@inverse I drilled into the new iBroadcast UI. Here is a patch that approximates the needed changes:

```diff
diff --git a/src/connectors/ibroadcast.js b/src/connectors/ibroadcast.js
index a0b7d00f..9ff9e074 100644
--- a/src/connectors/ibroadcast.js
+++ b/src/connectors/ibroadcast.js
@@ -6,12 +6,12 @@ Connector.trackSelector = '.mgr-player-nowplaying .mgr-player-title';
 
 Connector.artistSelector = '.mgr-player-nowplaying .mgr-player-artist';
 
-Connector.albumSelector = '.mgr-player-nowplaying .mgr-player-album';
+Connector.albumSelector = '.mgr-list-playqueue-container .mgr-track-album'; // WIP
 
-Connector.currentTimeSelector = '.mgr-player-top .jp-current-time';
+Connector.currentTimeSelector = '.mgr-player-current-time';
 
-Connector.durationSelector = '.mgr-player-top .jp-duration';
+Connector.durationSelector = '.mgr-player-duration';
 
-Connector.trackArtSelector = '.mgr-player-nowplaying .mgr-player-artwork';
+Connector.trackArtSelector = '.mgr-player-artwork-image';
 
-Connector.isPlaying = () => Util.getAttrFromSelectors('.mgr-player-top .mgr-player-play', 'src') === '/svg/btn-pause.svg';
+Connector.isPlaying = () => Util.getAttrFromSelectors('.mgr-player-play.icon-player-pause') != null;
```

Comments:

1. `mgr-player-title` and `mgr-player-artist` classes are still named the same.

2. The time and duration classes changed as above, but are straightforward.

3. The track art is now a `div` with class `mgr-player-artwork-image` with an `img` inside; here's how it looks from the console:
    ```javascript
    >>> document.querySelector('.mgr-player-artwork-image')
    <img class="mgr-player-artwork-image" src="//artwork.ibroadcast.com/artwork/xxxxxx-xxx" onclick="ibui.togglePlayQueue();">
    ```

4. The controls changed a bit. There is no longer an explicit svg AFAICT, but instead the classes change when play/pause is pushed. While a track is playing:
    ```javascript
    >>> document.querySelector('.mgr-player-play').classList
    DOMTokenList(4) [ "icon", "mgr-player-icon", "mgr-player-play", "icon-player-pause" ]
    ```
    And while paused:
    ```javascript
    >>> document.querySelector('.mgr-player-play').classList
    DOMTokenList(4) [ "icon", "mgr-player-icon", "mgr-player-play", "icon-player-play" ]
    ```
    And the `mgr-player-play` class only appears once, on that button, so I expect the above null test is enough to differentiate, no? (I'm not totally sure of the syntax here regarding the `Util.getAttrFromSelectors` function, though.)

5. A remaining problem is the album selector. Unfortunately, while the play queue is collapsed at the bottom, the dynamic HTML does not appear to contain the album info anywhere. It is grabbable by expanding the play queue tray, at which point it is listed in the album column of the first row of the queue, accessible as written above. But when the play queue is collapsed, the element with class `mgr-track-album` does not exist. :frowning_face: I do not know the web-scrobbler architecture, so am not sure if there is any cleverness that could be done here; maybe we just need to contact the iBroadcast folks and ask them to put the album name into the HTML even when the queue is collapsed?

Hope this helps! I am not primarily a webdev person, so please be gentle on me for anything stupid I wrote above. :smile:

**Comment by flagoworld** [comment]
Hi, we added a hidden element with the class "mgr-player-album" to the new UI so this connector could be made to work. We also created a pull request that fixes the connector so that it works with the new UI. #2974

**Comment by ctrueden** [comment]
I wrote to the iBroadcast team and they kindly added an invisible `mgr-player-album` div to the `mgr-player-nowplaying`! :tada: So a fix for this connector can now move forward. Stay tuned for a PR from me.
