### ISSUE TITLE
Add a connector for Online Radio Box

### ISSUE THREAD

**Issue by thomwim** [web-scrobbler/web-scrobbler#2936]
Online Radio Box is an online website with thousands of radio stations from around the world. I don't think this site has a connector, which is why I'm requesting one.

Here is an example radio station.

https://onlineradiobox.com/us/977todayshits

The player bar displays as "Artist name - Track name".

**Comment by leyarotheconquerer** [comment]
The attached PR appears to add support for this website. Is there a reason it wasn't merged?

**Comment by inverse** [comment]
Some how it slipped past us maintainers. Apologies - It'll be in the next release

**Comment by leyarotheconquerer** [comment]
Thanks for the help!
