### ISSUE TITLE
Broken YouTube track list format

### ISSUE THREAD

**Issue by clr134** [web-scrobbler/web-scrobbler#2937]
The following track list format will result in the extension detecting `.Artist` instead of `Artist`.

```
01. (0:00) Artist - Ttile
02. (3:36) Artist - Title
03. (7:30) Artist - Title
04. (11:27) Artist - Title
05. (14:53) Artist - Title
```

Platform information:
Windows 10, Mozilla Firefox v90, Web Scrobbler v2.44.0

**Comment by alexesprit** [comment]
It's broken YouTube track list parser. :)

**Comment by clr134** [comment]
A bot closing old issues? Weird. It still happens on the latest version (2.45.0), so it's not outdated.

**Comment by clr134** [comment]
Still occurs.

**Comment by clr134** [comment]
Still an issue on 2.59.1, in fact it's gotten worse, because the track list is not recognized at all.

**Comment by clr134** [comment]
The issue should not be closed.
