### ISSUE TITLE
Spotify web connector is not working

### ISSUE THREAD

**Issue by yuuna999** [web-scrobbler/web-scrobbler#2939]
**Describe the bug**
When i try to scrobble with Spotify web it doesn't work
**How to reproduce**
1. Go to 'https://open.spotify.com'
![image](https://user-images.githubusercontent.com/87952710/126916142-ad198ce5-9531-45f6-bbe7-eacd27fa3457.png)

-   OS: Windows
-   Browser: Opera GX
-   Extension version: 2.44.0

**Comment by hurmaqny** [comment]
I have the same issue. The only difference is that I'm using the latest version of Edge (92.0.902.55).

**Comment by alexesprit** [comment]
Maybe it's related to #2904?
