### ISSUE TITLE
Regex-based filters

### ISSUE THREAD

**Issue by awsms** [web-scrobbler/web-scrobbler#2943]
Recently, another great scrobbling service I use on my smartphone added a way to remove unwanted parts to scrobble thanks to regexes.
For example, removing ' (Album Version)', ' (Original Mix)' etc from the tracknames; or letting the user set custom filters for the album and artist names. As you imagine, manually editing every single 'Original Mix' is quite redundant.

I think it would be great if web-scrobbler could implement something similar.

**Comment by jaccarmac** [comment]
Which scrobbler does this? (Interested both to see the implementation and for personal use.)

**Comment by afoxie** [comment]
This would be an amazing feature, as it stands right now I have to manually edit (almsot) every YT Music track to remove the "(feat. xxxxx)

**Comment by awsms** [comment]
> Which scrobbler does this? (Interested both to see the implementation and for personal use.)

It's https://github.com/kawaiiDango/pScrobbler

> This would be an amazing feature, as it stands right now I have to manually edit (almsot) every YT Music track to remove the "(feat. xxxxx)

Same here..

**Comment by djmattyg007** [comment]
Doesn't web-scrobbler already do this? The key functionality was spun out into a library that you can install and use separately:

https://github.com/web-scrobbler/metadata-filter

I've also ported it to python:

https://github.com/djmattyg007/music-metadata-filter

**Comment by flickur** [comment]
> Doesn't web-scrobbler already do this? The key functionality was spun out into a library that you can install and use separately:
> 
> https://github.com/web-scrobbler/metadata-filter
> 
> I've also ported it to python:
> 
> https://github.com/djmattyg007/music-metadata-filter


Can this be implemented in the scrobbler addon itself with an UI for easier use?

**Comment by flickur** [comment]
Bumping this since I've been using pano scrobbler on my phone for some time now and the pattern filter is awesome. It would fix most of my problems with webscrobbler. Please make this happen.

**Comment by djmattyg007** [comment]
It isn't clear exactly what you're asking for. The `metadata-filter` package is already integrated into `web-scrobbler`.

Are you after the ability to define custom patterns?

**Comment by flickur** [comment]
Same thing OP is suggesting. Ability to set pattern filters that apply to all your scrobbles. There is no such function in the webscrobbler options, only the list of your edited single tracks. Here's an example from pano scrobbler where it gets rid of every "- radio edit" that appears in the track name.

![Screenshot_20210919-150645](https://user-images.githubusercontent.com/40724723/133926930-6b0dc937-7421-4f90-963d-2dd543fe8cb1.jpg)

**Comment by djmattyg007** [comment]
So, yes, you’re after the ability to define custom patterns 👍
