### ISSUE TITLE
Youtube isn't working now :( 

### ISSUE THREAD

**Issue by IRainman** [web-scrobbler/web-scrobbler#2949]
1. Go to https://www.youtube.com/watch?v=PiJuKcLFpUk

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Firefox 90.0
-   Extension version: 2.45.0

**Comment by fakeheal** [comment]
Can confirm this. Now my friends won't know about the "Most Epic Badass Action Music Mix"-es I am listening to :(
