### ISSUE TITLE
Add preferences link to toolbar icon

### ISSUE THREAD

**Issue by ronech** [web-scrobbler/web-scrobbler#2962]
**Is your feature request related to a problem? Please describe.**
When a YouTube video isn't scrobbling, i have to go to Preferences > Extensions & Themes >  Web Scrobbler Preferences to turn off the Music & Entertainment checkboxes.

**Describe the solution you'd like**
When you click the toolbar icon and get the popup, "Play some music to get started // Is it already playing?" add a link to the Scrobbler Preferences page.

**Comment by yayuyokitano** [comment]
Closing, as this was implemented with the V3 redesign.
