### ISSUE TITLE
Plex Connector Not Working

### ISSUE THREAD

**Issue by davidblasiak** [web-scrobbler/web-scrobbler#2975]
On Chrome on any platform playing music from https://app.plex.tv/ doesn't detect the song or scrobble.

**Comment by cam1170** [comment]
It seem to work on the locally run version, for instance http://127.0.0.1 Plex Web 4.63.0, but not on https://app.plex.tv Plex Web 4.67.0

**Comment by datakid** [comment]
Confirming that it doesn't work on plex.tv in Firefox.

**Comment by cam1170** [comment]
On http://127.0.0.1 it works initially but when you leave it and come back and stuff it gets stuck, not detecting anything, until you refresh the page, so it’s not exactly stable.

**Comment by jonrandy** [comment]
I have fixed this. The fix #3078 is awaiting review

**Comment by jaivalis** [comment]
Is there a release planned with @jonrandy's fix?

**Comment by inverse** [comment]
@jaivalis we had some issues with the release pipeline which are now fixed. Expect a release this week.

**Comment by inverse** [comment]
@jaivalis new version being rolled out

**Comment by jaivalis** [comment]
Works better than before, prior it would lose the tracks from time to time and needed a page reload to work. Very happy with it so far. Thanks team!

**Comment by inverse** [comment]
Closing the issue
