### ISSUE TITLE
Generic origin_url in Soundcloud connector

### ISSUE THREAD

**Issue by MonkeyDo** [web-scrobbler/web-scrobbler#2977]
Hello!

**Describe the bug**
When scrobbling from Souncloud, the resulting `origin_url` (used for ListenBrainz submissions) is the current browser location.
This does not always represent the location of the track being played.

For example, listening to tracks from the home page, the `origin_url` will be `https://soundcloud.com/discover` for each track.
Similarly, if playing from a set (playlist) , the `origin_url` will be that of the set rather than the URL of the track itself.

**Expected behavior**
While getting the actual resource URL might prove a bit tricky without access to the Soundcloud player, I would expect the origin_url to represent the actual resource URL rather than a generic page.

**Debug logs**
Output from browser console:
```
Web Scrobbler: {
  "track": "Midnight Walk",
  "artist": "Richard Griffith",
  "album": null,
  "albumArtist": null,
  "uniqueID": null,
  "duration": 120,
  "currentTime": null,
  "isPlaying": false,
  "trackArt": "https://i1.sndcdn.com/artworks-000124055312-ghsz4i-t120x120.jpg",
  "isPodcast": false,
  "originUrl": "https://soundcloud.com/discover"
}
Web Scrobbler: isPlaying state changed to true
```

**Additional context**
I am a developer for ListenBrainz and currently working on playback features on our website.
It would be helpful to have access to a URL or unique ID for playback purposes, and more generally to have a more descriptive URL.
I am happy to help implement an improvement but being new to the codebase I would appreciate help with pointing me in the right direction.
Also happy to provide more information as necessary. Thanks for your time!

**Comment by MonkeyDo** [comment]
This issue is still valid and current.

**Comment by MonkeyDo** [comment]
Thank you so much !

**Comment by inverse** [comment]
It's published - let me know if that suffices? p.s. let me know what else we can do to help!

Def should make sure that these fields are populated correctly.

**Comment by MonkeyDo** [comment]
I updated the extension, restarted my browser, made sure I'm on 2.60.0, but I'm not seeing an improvement playing from various non-album bandcamp pages.

Heres the logged output from the home page:
```
Web Scrobbler: {
  "track": "Conspiranoia",
  "artist": "Primus",
  "album": "Conspiranoid",
  "albumArtist": null,
  "uniqueID": null,
  "duration": null,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://f4.bcbits.com/img/a2114664258_2.jpg",
  "isPodcast": false,
  "originUrl": "https://bandcamp.com/?g=rock&s=top&p=0&gn=0&f=all&w=0"
}
```

and from the feed page:
```
Web Scrobbler: {
  "track": "The Afrorack",
  "artist": "par Afrorack",
  "album": null,
  "albumArtist": null,
  "uniqueID": null,
  "duration": null,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://f4.bcbits.com/img/a1301788768_15.jpg",
  "isPodcast": false,
  "originUrl": "https://bandcamp.com/mr_monkey/feed?from=menubar"
}
```

No `uniqueID` for either it seems.

I tried running `document.querySelector('.playbackSoundBadge__titleLink')` in the console on both pages; in both cases that returns `null` (at least it's consistent :) )


I'm not sure if there is any way to get the uniqueID that will work for all Bandcamp pages, but I can help figure out the different scenarios for each page and which DOM elements to target to get the appropriate href, if that helps.
Happy to help in any way I can.

**Comment by inverse** [comment]
Ouch - that's another connector - unfortunately the way the setup is that by default it resolves the current URL unless it's overridden like in the Soundcloud one.

**Comment by inverse** [comment]
@MonkeyDo https://github.com/web-scrobbler/web-scrobbler/pull/3236 this should fix it for the Bandcamp collections

**Comment by MonkeyDo** [comment]
I'm terribly sorry, I got confused!
That ticket was so old I forgot the issue was about Soundcloud and was focusing on Bandcamp.

Thank you for both of those fixes !

The Soundcloud PR fixed this issue perfectly.

For Bandcamp, now that you have set up the mechanism to retrieve the album URL, I'll be able to open another PR if the mechanism ends up being different for the different Bandcamp pages.

Thanks again !
