### ISSUE TITLE
Amazon Music bug

### ISSUE THREAD

**Issue by superjuninha** [web-scrobbler/web-scrobbler#2978]
Hello!
When I try to scrobble to Amazon Music, even with the connector enabled, the song doesn't scrobble as the screenshot below:
![image](https://user-images.githubusercontent.com/90423555/132765151-0b1d8db6-d2f7-4b51-b5ab-7541fb986a98.png)
![image](https://user-images.githubusercontent.com/90423555/132765222-93585523-4878-4b75-b001-2966964bf0d6.png)
Kindly request your help to solve it.
Thank you!

**Comment by syberphunk** [comment]
I have the same problem with Google Chrome.

**Comment by viniciusbdzn** [comment]
doesn't work in opera browser
