### ISSUE TITLE
Jango.com's new layout cannot scrobble

### ISSUE THREAD

**Issue by effluviummist** [web-scrobbler/web-scrobbler#2980]
Hello, ever since jango.com has new layout, the web scrobbler cannot scrobble anymore

Opera Windows 10

**Comment by effluviummist** [comment]
![jango.com issue](https://user-images.githubusercontent.com/90512000/132948487-9a7bf627-77a1-4f80-bf46-127e3791f71b.png)

**Comment by MXB2001** [comment]
Same here. The old problem of not working until you reloaded doesn't apply anymore. Nothing makes it scrobble now. (Well I haven't tried magic incantations... ; - )

**Comment by MXB2001** [comment]
2022 and jango still doesn't scrobble.
