### ISSUE TITLE
Metadata editor width is wrong

### ISSUE THREAD

**Issue by Spekular** [web-scrobbler/web-scrobbler#2983]
The width of the metadata editor is too low, and as such the fields and edit buttons are not visible.

**How to reproduce**
Go to any page where the scrobbler detects a song playing, click the extension icon.

**Expected behavior**
Editor window should be sized to fit content as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/8918426/132965768-36f2d062-ff0f-4881-b486-d1b4c50a481d.png)

**Debug logs**
Unsure if I grabbed these correctly
<details>
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/md5.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
</details>

**Environment**
-   OS: Windows 10 64 bit
-   Browser: Chrome Version 94.0.4606.41 (Official Build) beta (64-bit)
-   Extension version: 2.45.0

**Comment by danilobalen** [comment]
The same error happens here.

**Comment by jaccarmac** [comment]
This is reproducible on the last commit I made, and I didn't encounter it until I updated. Thus, it seems like the issue is with Chrome and not with a dependency update. There is a possibility of lockfile weirdness, though: My NPM likes to edit the lockfile from Git (mostly updating the version, it seems).

**Comment by Andreasvb** [comment]
As a temporary workaround, you can change from grid in CSS with inspector.

```css
.main-container { display: inline-flex; }
```

**Comment by jaccarmac** [comment]
#2992, #2993, #2994 are duplicates of this issue.
