### ISSUE TITLE
Info Popup Width Bug 

### ISSUE THREAD

**Issue by SketchTurnerrr** [web-scrobbler/web-scrobbler#2992]
Scrobbling window gets wrong width
I'm using Chrome Canary, haven't tested in other browsers

![image](https://user-images.githubusercontent.com/23274681/134161726-8ccc8ed6-ee40-409b-a4f4-1ac35b7db2cb.png)

setting fixed width to the .main-container class solves the problem

![image](https://user-images.githubusercontent.com/23274681/134162857-e560a451-6b8c-4905-ae34-a88acafe7739.png)

![image](https://user-images.githubusercontent.com/23274681/134162786-20ae4533-dfad-4303-a9b1-689f37aa9110.png)

**Comment by SketchTurnerrr** [comment]
Tested in Firefox all works fine

**Comment by czwarty-4** [comment]
How to make it stay? It works after I edit the width but the moment I click away from the window everything resets, the window again is very narrow and after I inspect element again the width line is gone. Is there any way to edit it permanently? This stuff makes me furious for last few days
