### ISSUE TITLE
Unable to edit track details

### ISSUE THREAD

**Issue by P3anutDude** [web-scrobbler/web-scrobbler#2993]
When I tried to edit a track's details (name/artist/album), clicking on the Web Scrobbler icon just made this pop up rather than allowing me to edit the details.
![help hgelp help](https://user-images.githubusercontent.com/91164513/134260914-07e1b349-0ad0-4e1d-b2ef-19ae7963151b.png)
It's just a thin strip of the little track editing menu, so the only thing I was able to click on was the album cover which didn't help at all. I would restart my PC, and it was still there. Removing and reinstalling the extension doesn't work either, I'm on the latest version of Chrome as well. There just isn't a way I can currently edit the track details right now so how do I get this fixed?

**Comment by KnowsyKnowsBest** [comment]
I have the same problem. Using Chrome. [https://github.com/web-scrobbler/web-scrobbler/issues/2992](This) guy had the same issue but in Firefox. He fixed it by manually setting the width, but i can figure out how he did it sadly.

**Comment by SketchTurnerrr** [comment]
The issue is only in Chrome Canary. Firefox works fine and has no such problem. To fix it you have to manually set the width of the popup but the changes don't persist. Just right click inspect the pop up and follow the screenshot from [my](https://github.com/web-scrobbler/web-scrobbler/issues/2992) closed issue

**Comment by KnowsyKnowsBest** [comment]
> The issue is only in Chrome Canary. Firefox works fine and has no such problem. To fix it you have to manually set the width of the popup but the changes don't persist. Just right click inspect the pop up and follow the screenshot from [my](https://github.com/web-scrobbler/web-scrobbler/issues/2992) closed issue

Just tried it. Hopefully this bug is fixed soon, as i cant be bothered to do this over and over all the time i want to edit songs

**Comment by foragemon** [comment]
same problem after updating chrome to 94.0.4606.54

**Comment by SUPERJEFF6** [comment]
I tried doing that (using Chrome), but whenever I clicked away from it, it went back to the way it was, it was not a permanent fix.

**Comment by ksbrar** [comment]
Same problem in Edge stable (94.0.992.31)

**Comment by Mavoy** [comment]
Since it wasn't specifically mentioned - the bug doesn't seem to be affecting Firefox so my temporary solution is simply to use FF, at least for websites that I scrobble. Hopefully the dev will roll out the updated Chromium extension soon.
