### ISSUE TITLE
something went wrong with my scrobler

### ISSUE THREAD

**Issue by Jimelia** [web-scrobbler/web-scrobbler#3002]
it stops scrobbing

**Comment by dominikmatus** [comment]
Mine too. It says at Youtube: This website is not supported
Web Scrobbler does not support scrobbling from this website.

Some Google websites supported by the extension (e.g. Google Play Music, YouTube) can be blocked due to an ExtensionSettings policy. Learn more

**Comment by AntaresShao** [comment]
> Mine too. It says at Youtube: This website is not supported Web Scrobbler does not support scrobbling from this website.
> 
> Some Google websites supported by the extension (e.g. Google Play Music, YouTube) can be blocked due to an ExtensionSettings policy. Learn more

Mine too... But my scrobbler show this massage on every website I opened which is listed in the support list.
