### ISSUE TITLE
Web Scrobbler Pinned Box on Chrome very small

### ISSUE THREAD

**Issue by PineAppleCola** [web-scrobbler/web-scrobbler#3005]
When I click on the pinned extension the boc is small and does not display the full album cover and name. A clear and concise description of what the bug is.

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by RenRenIsWeird** [comment]
![Capture](https://user-images.githubusercontent.com/56497824/135005227-cddb316a-ed1b-45c5-b010-a8d999f463e1.PNG)

I believe this one that happened to you? because I'm also having the same problem

**Comment by DanielVG29** [comment]
i have the same problem 😥

**Comment by GabrielCalin** [comment]
Me too, the good news is that the scrobbler works, the bad one is that you can't see much when clicking on the icon.

**Comment by emilironnytea** [comment]
That's right, for me too, editing is impossible, as well as adding new ones.

**Comment by metabohaid** [comment]
same problem here after installation of the  latest google chrome version (Version 94.0.4606.61)

**Comment by BaconShoes** [comment]
I'm having the same issue on Microsoft Edge too

**Comment by ivanarena** [comment]
same here with Chrome

**Comment by skurinski** [comment]
I'm having the exact same problem on Chrome, which is really annoying cause I always edit the songs and now I can't do that.

**Comment by LolicoreExpress** [comment]
Yep, everybody already said so but.... _Me too._
(On Microsoft Edge Canary v94.0.992.31)
Probably a Chromium thing. It'd be nice if somebody had Firefox handy to test if it happens there too.

**Comment by inverse** [comment]
Works fine on Firefox - it must be a chromium thing.

**Comment by aja675** [comment]
Same, how could it be fixed?

**Comment by inverse** [comment]
Will be in the next release 👍🏼

**Comment by inverse** [comment]
@alexesprit one for you. Looks like it's failing on the Chrome publish.

See: https://github.com/web-scrobbler/web-scrobbler/runs/3743813199?check_suite_focus=true#step:7:8

See: https://github.com/trmcnvn/chrome-addon#troublehooting

> In case your action returns an HTTP 400 error code from Chrome web store, make sure all needed information are filled in your developer dashboard (privacy etc.)

**Comment by skurinski** [comment]
So what can we do? Uninstall the extension and reinstall it?

**Comment by inverse** [comment]
Either:

1. Wait for a fix from @alexesprit  as I don't have access to the Chrome dashboard
2. Run it unpacked as per the [wiki](https://github.com/web-scrobbler/web-scrobbler/wiki/Install-an-unpacked-extension)

**Comment by inverse** [comment]
@skurinski Turns out to be a transient issue. Rerunning seemed to work
