### ISSUE TITLE
Bug on Microsoft Edge. Information Box of the song being scrobbled is too tiny, making editing information impossible.

### ISSUE THREAD

**Issue by AdeMoraez** [web-scrobbler/web-scrobbler#3012]
The bug is pretty much what I said in the title. It's been happening on Microsoft Edge for about a week, I think.

Here is a screenshot:

![Screen Shot 2021-10-05 at 12 25 12](https://user-images.githubusercontent.com/91969786/136053586-7603f2a8-8c20-4955-b210-f00a16be0cd9.png)

Does anyone know a fix?

**Comment by Klopek619** [comment]
I have the same issue. Same in Chrome too. The only thing I can do it click the tiny white window which opens the album art in a new tab.

**Comment by viniciuspcorrea** [comment]
I am also experiencing this issue. :( 

Already searched but I haven't found a fix for it.

**Comment by AdeMoraez** [comment]
Hi. I'm glad to see that this has already been fixed in version 2.45.2 and beyond. Unfortunately, Microsoft Edge's extensions store only provides the 2.45.0 version yet. I guess I'll wait until the updated versions are available. Thanks!

**Comment by forenta** [comment]
Still 2.45.0 in the Edge store 🕰️

**Comment by inverse** [comment]
Edge publishing is not automated on CI and I don't think I have the permissions to do that. 

@alexesprit are you able to publish it?

**Comment by alexesprit** [comment]
I guess this one can be closed.
