### ISSUE TITLE
Not scrobbling on spotify

### ISSUE THREAD

**Issue by rafoconchetumare** [web-scrobbler/web-scrobbler#3020]
Yesterday by mistake I deactivated the scrobbling in spotify, I turned it on again and turned off the pc to go to sleep, today when I entered the pc again I went to listen to music and I noticed that it did not scrobble the music I was listening to.
It just said:
"Play some music to start.
Already playing?"
I don't know if this is just happening to me or someone else, help please!!!!
![image](https://user-images.githubusercontent.com/92479744/137210018-6b7816ca-d100-415a-a25c-08313fa6fb2e.png)

**Comment by rgoudie** [comment]
Same for me, this morning. I have changed absolutely nothing from last night.

**Comment by azula999** [comment]
same here

**Comment by captooin** [comment]
Same

**Comment by 0edit** [comment]
same problem here. works on bandcamp and other sites but no spotify atm.

**Comment by inverse** [comment]
Fixed in aa896c3
