### ISSUE TITLE
Web scrobbler not wrking

### ISSUE THREAD

**Issue by azula999** [web-scrobbler/web-scrobbler#3021]
ok, since today's morning the bot stopped scrobbling on spotify for chrome. tit says "this website is not compatible. web scrobbler is not compatible with this website's scrobbles" 

![image](https://user-images.githubusercontent.com/92491832/137229082-d1e1e408-3449-45e3-a5e9-391568587985.png)

**Comment by rafoconchetumare** [comment]
i have the same problem
