### ISSUE TITLE
Youtube videos not being recognized as playing

### ISSUE THREAD

**Issue by fillycolt** [web-scrobbler/web-scrobbler#3027]
**Describe the bug**
Youtube videos not recognized, getting the "play some music to get started; is it already playing?" pop up

**How to reproduce**
Try to play any Youtube video, with the web scrobbler enabled to register videos in the music category

**Expected behavior**
For the Youtube video to have scrobbled like normal

**Debug logs**
I don't know how to do this unfortunately

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: 2.46.0

**Additional context**
I've been having the same problem with Spotify since yesterday. I have only the web scrobbler enabled as Spotify's own scrobbler for Last.FM gives me issues. I'm sorry if any of this is unhelpful or wrong, I'm new to this site

**Comment by chrish-d** [comment]
This seems to work sometimes and other times not. Yesterday it was picking up scrobbles, but it was wrongly listing the uploader as the artist (A Tribe Called Quest labelled as Recreational Mixtapes).

Today it's not picking up anything at all from this link, or from some others I tried.

https://www.youtube.com/watch?v=oHoiPn8agK4&list=PUZ-IRNvpmsiJmjar5V5Ksew&index=55

Scrobbles:
https://www.last.fm/user/himynameschrish

**Comment by Tenome** [comment]
Same. The other Scrobbler that I sometimes use didn't detect it as playing either. I wonder what's causing it.
https://youtu.be/9BQnBNHs06U

**Comment by rgoudie** [comment]
I am finding that when the issue occurs (very rarely), I just have to close my Chrome browser and restart it and the extension will kick-in. An easy workaround for the time being.
