### ISSUE TITLE
Service Error

### ISSUE THREAD

**Issue by easybreezyb** [web-scrobbler/web-scrobbler#3029]
**Describe the bug**
Web Scrobbler is unable to register scrobbles for YouTube and Soundcloud. The extension states: "Looks like something went wrong while scrobbling the music. Please open the options page and try to reauthenticate with services. If reauthentication doesn't help, and you still see this message, please create a new issue at the GitHub project page."

Attempts to reauthenticate did not resolve the issue. Attempts to reinstall the extension did not resolve the issue. Restarting device did not resolve the issue.

**How to reproduce**
1. Check to see that Web Scrobbler extension is pinned and allowed access to chosen sites.
2. Open any video on Youtube / play any song on Soundcloud.

**Expected behavior**
My expectation is that Web Scrobbler will be able to register the played videos/music on the sites and that the same will reflect on Last.fm.

**Screenshots**
![image](https://user-images.githubusercontent.com/79884044/138099568-9e20bd95-8619-4394-abb9-c05cf3a5955c.png)

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: v2.46.0

**Comment by Eyeball753** [comment]
Same issue here.

OS: Windows 10
Browser: Firefox 93.0
Extension version: v2.48.0 (but it's been an issue for older versions, too)

**Comment by 9e9e9e9** [comment]
Same issue as well. It's resolved itself a few times but reverts to the same error message depending on the hour.

OS: macOS Big Sur
Browser: Firefox 93.0
Extension version: v2.48.0

**Comment by ipkpjersi** [comment]
I had this issue happen here on YouTube and Spotify and Tidal etc. I reauthenticated on last.fm but it didn't work, but what did work was disabling and re-enabling the browser extension. Might be worth trying for anyone still experiencing this issue.

OS: Ubuntu 20.04 Linux
Browser: Firefox 99.0.1
Extension version: v2.58.0
