### ISSUE TITLE
Please include pattern edits with the extension!

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#3046]
**Is your feature request related to a problem? Please describe.**
The Web Scrobbler's built-in metadata filter doesn't automatically remove the " - Single", " - EP", " - Bonus" / "Bonus Tracks Version" and many other suffixes from the album field when scrobbling music using the Apple Music web player. It's too time consuming and cumbersome to have to do it manually everytime I play music. 

**Describe the solution you'd like**
I want the functionality to be available in the extension to have the extension do this automatically or at least the ability to import the pattern edits (see the attached picture) from the scrobbler app on my phone to the Web Scrobbler extension.

![Screenshot_20211105_151052_com arn scrobble](https://user-images.githubusercontent.com/46681247/140490810-e1f73167-6a2c-40a4-a432-b37ae69f201b.jpg)

**Comment by flickur** [comment]
Second this, Panoscrobbler is awesome and has other functionality which webscrobbler could implement. Like the scrobbling history where you can edit past scrobbles and it both saves the edit for the scrobbler and edits said past scrobble on last.fm at the same time.

**Comment by NomaanMalick** [comment]
> 
> 
> Second this, Panoscrobbler is awesome and has other functionality which webscrobbler could implement. Like the scrobbling history where you can edit past scrobbles and it both saves the edit for the scrobbler and edits said past scrobble on last.fm at the same time.

That would be great! But I think the developers here have been busy for some time now. They haven't responded to any of my requests either here or on Discord.
