### ISSUE TITLE
Extension published on Microsoft Edge Store is outdated.

### ISSUE THREAD

**Issue by gunjanmane** [web-scrobbler/web-scrobbler#3058]
Version 2.45.0, Updated July 26, 2021 on Edge Store.
Version 2.48.0, Updated October 28, 2021 on Chrome Web Store.

**Comment by alexesprit** [comment]
Yes, sorry for this.

I'm submitting the extension for review right now.

**Comment by gunjanmane** [comment]
![image](https://user-images.githubusercontent.com/80813004/142644131-9a4aab81-420f-4f90-939d-6af50a8e53ab.png)
this might be directly related as well, the track info does not load.

cheers, have a good day.

**Comment by alexesprit** [comment]
v2.48.0 is in review queue in MS Edge Store. It usually take 1-2 days to approve.

I believe the issue you screenshooted is fixed in v2.48.0.

**Comment by gunjanmane** [comment]
Amazing, thank you.
