### ISSUE TITLE
open.fm - year in the album name

### ISSUE THREAD

**Issue by clr134** [web-scrobbler/web-scrobbler#3060]
Album name contains year in square brackets which causes incorrect scrobbles.

**How to reproduce**
1. Go to https://open.fm/stacja/impreza
2. Check album name.

**Expected behavior**
Year should be stripped out.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Firefox
-   Extension version: 2.48.0

**Comment by inverse** [comment]
Will be fixed in the next release! Thanks @fckawe
