### ISSUE TITLE
Create Sintax Rules

### ISSUE THREAD

**Issue by maxelo** [web-scrobbler/web-scrobbler#3069]
**Is your feature request related to a problem? Please describe.**

I'm a longtime last.fm user of many years. Right know I'm a Youtube Music user with the spanish language as the primary language of the site (I know I can change it to english). 
The problem is that Youtube Music is forcing the translation of TITLE ID of any song like this:

SONGTITLE (feat. ARTISTNAME) 

to

SONGTILE (con ARTISTNAME)

"featuring" to "con"

I would love to know if maybe you could add the option add a rule to whenever this happens we can force the "con" to "feat." so I can scrobble the same songs I have on my hard drive and sd card music collection.

thanks for your work

**Comment by maxelo** [comment]
All credits to Pano Scrobbler for Last.FM [https://play.google.com/store/apps/details?id=com.arn.scrobble](url)

this is the REGEX patterns of Pano Scrobbler, the last one is the one I created myself, hope you can add it to web scrobbler =)

1. Album Version
Regex Pattern:
 ([/-] .*)? ?album version.*| [(\[][^()\[\]]*?album version[^()\[\]]*[)\]]
Regex Replacement:

Field:
TITLE
Replace:
First
- if found first, continue to match other regular expressions

2. Explicit (album)
Regex Pattern:
 ([/-] )? ?explicit ?(.*?version)?| [(\[][^()\[\]]*?explicit[^()\[\]]*[)\]]
Regex Replacement:

Field:
ALBUM
Replace:
First
- if found first, continue to match other regular expressions


3. Explicit (title)
Regex Pattern:
 ([/-] )? ?explicit ?(.*?version)?| [(\[][^()\[\]]*?explicit[^()\[\]]*[)
Regex Replacement:

Field:
TITLE
Replace:
First
- if found first, continue to match other regular expressions

4. Remastered (album)
Regex Pattern:
 [(\[][^()\[\]]*?remastere?d?[^()\[\]]*[)\]]| ([/-] )?([(\[]?\d+[)\]]?)? ?remastere?d? ?(version)?([(\[]?\d+[)\]]?)?
Regex Replacement:

Field:
ALBUM
Replace:
First
- if found first, continue to match other regular expressions

5. Remastered (title)
Regex Pattern:
 [(\[][^()\[\]]*?remastere?d?[^()\[\]]*[)\]]| ([/-] )?([(\[]?\d+[)\]]?)? ?remastere?d? ?(version)?([(\[]?\d+[)\]]?)?
Regex Replacement:

Field:
TITLE
Replace:
First
- if found first, continue to match other regular expressions

6. tema (con artista)
Regex Pattern:
(\s?\(con\s)
Regex Replacement
(feat.
Field:
TITLE
Replace:
First

**Comment by maxelo** [comment]
any love for this?

**Comment by inverse** [comment]
Perhaps it would be better suited for https://github.com/web-scrobbler/metadata-filter?

**Comment by maxelo** [comment]
> Perhaps it would be better suited for https://github.com/web-scrobbler/metadata-filter?

looks great, but I'm a newbie here, is there anything I could read or watch to install that script into my firefox or chrome?
