### ISSUE TITLE
Short tracks in segmented YT videos are not being scrobbled. Is this a web scrobbler bug?

### ISSUE THREAD

**Issue by Talvalin** [web-scrobbler/web-scrobbler#3075]
Apologies if this should be reported as a bug, but I'm not sure if the behaviour is related to last.fm or the scrobbler.

It seems as if short tracks in a segmented YT video are being recognised by the web scrobbler - a pop-up notification shows up with the correct track and last.fm shows the correct track in my Recent Tracks list as "Scrobbling now" - but the track is not shown in Recent Tracks after the next track starts playing and the new pop-up notification appears.

For a test example, [Blind Guardian's Nightfall in Middle-Earth](https://www.youtube.com/watch?v=9o1Rxyt-ro4) features a lot of short interlude tracks that are 20-40 seconds in length and it seems that only those tracks with a length greater than 30 seconds are being played ([a full track listing with correct lengths is here](https://www.metal-archives.com/albums/Blind_Guardian/Nightfall_in_Middle-Earth/19))

Environment:
OS: Windows 11 Pro (21H2)
Browser: Firefox 94.0.2
Extension: Web Scrobbler 2.48.0

**Comment by jaccarmac** [comment]
web-scrobbler doesn't scrobble tracks under 30 seconds. In some cases, I've observed tracks _around_ that length getting missed: I believe it's due to the delay in initial detection.

**Comment by Talvalin** [comment]
If it were an initial detection issue, then I wouldn't expect to see a pop-up notification nor for last.fm to show the track as "Scrobbling now". My theory is that there is a minimum track length being enforced somewhere in the chain, and based on the length of the interlude tracks that were scrobbled (everything over 30 seconds shows up), I think that minimum length is 30 seconds.

**Comment by jaccarmac** [comment]
You're correct, and I was unclear. The 30 second limit is not related to initial detection.

**Comment by Talvalin** [comment]
So it's a built-in limitation of the web scrobbler to ignore tracks that are less than 30 seconds in length? Bugger. Having incorrect scrobbles for that particular album is going to bug me, but I guess I'll just have to deal with it. Cheers for the responses!

**Comment by jaccarmac** [comment]
[Technically, it's a limitation of the Last.fm API as well](https://www.last.fm/api/scrobbling#when-is-a-scrobble-a-scrobble). I manually scrobble missed tracks myself - don't tell anyone! - but it is annoying.
