### ISSUE TITLE
Edited tracks verses Global track edits

### ISSUE THREAD

**Issue by gworley** [web-scrobbler/web-scrobbler#3082]
### Discussed in https://github.com/web-scrobbler/web-scrobbler/discussions/3081

<div type='discussions-op-text'>

<sup>Originally posted by **gworley** December 13, 2021</sup>
Edited tracks verses Global track edits.  The options say that:

>This extension stores edited tracks.

However I have done many edits (in the past 3 days I have done over 300 edits) in last.fm.  The extension is reporting I have done none.  How do I get the tracks to be added to the Edit function?

Also I do I correct bad global edit tracks .  I was playing a The Sister of Mercy track and it had in a - where the Remaster 2018 after the - was removed however the space- wasn't.

Thanks in advance,

George</div>

**Comment by yayuyokitano** [comment]
The edits of web scrobbler are completely unrelated to the edits of last.fm, and were implemented before that was a feature of last.fm, when the need was bigger.
What is meant by edits in web scrobbler is that when a song is detected by web scrobbler, you can hit the pen icon in web scrobbler to change how web scrobbler scrobbles it. When you do this, it will save it and do it again next time. Last.fm is not made aware of this at all, it all happens in your browser.
There is no official way web scrobbler could implement syncing this with last.fm's list, and there's not a big need either I think. You can view your last.fm edits in the last.fm pro tab of last.fm settings.
Global edits are a last.fm issue, web scrobbler is not affiliated with last.fm at all and there is nothing that can be done on web scrobbler's end to help you here. However, I can tell you that at the moment last.fm states they cannot modify existing global edits and there is no official method of reporting incorrect edits, so there is probably nothing to be done. That said I have heard of instances of global edits being fixed, but very rarely. You can also choose to disable global edits entirely for your account in the website tab of the last.fm settings. It's still janky though.
