### ISSUE TITLE
You Tube not recognized or permitted

### ISSUE THREAD

**Issue by pgueckel** [web-scrobbler/web-scrobbler#3084]
**Describe the bug**
When I click on the extensions icon in Google Chrome, the Web Scrobbler icon shows a greyed-out Last.fm icon, even though I am logged in to You Tube and am on the You Tube tab. I click on the Web Scrobbler line and a tab appears, variously asking whether the video is already playing; other times, I get a message stating that some Google sites (You Tube etc) are not permitted or supported (not sure of exact wording) and a link directs me to a Google Chrome Enterprise Help Configure ExtensionSettings policy page.

**How to reproduce**
1. Play a You Tube video.
2. See a Greyed-out Web Scrobbler in the extensions dropdown menu in Google Chrome with a Last.fm icon beside it.

**Environment (please complete the following information)**
Fedora Linux 35
Chrome 96.0.4664.110
Extension Version 2.48.0

**Additional context**
I have the Web Scrobbler extension configured to only record Music and not Entertainment listens. I have concluded that this might not, strictly speaking, be a problem with Web Scrobbler, but one with YouTube: some music videos appear not to be recognized as music. When I change the extension options to record all listens (deselect both Music and Entertainment), then it appears to work.

**Comment by pgueckel** [comment]
<details>
storage.LocalCache = {
  "8tAWPIFD1_w": {
    "album": null,
    "albumArtist": null,
    "artist": "Fausto Romitelli, Schallfeld Ensemble",
    "track": "Amok Koma"
  },
  "JVMX-hDQdEM": {
    "album": null,
    "albumArtist": null,
    "artist": "Edgard Varèse, Paris Percussion Group",
    "track": "Ionisation"
  }
}
wrapper.js:74 storage.LastFM = {}
wrapper.js:74 storage.LibreFM = {}
wrapper.js:74 storage.ListenBrainz = {
  "properties": {
    "userToken": "************************************"
  }
}
wrapper.js:74 storage.Maloja = {}
wrapper.js:74 storage.Options = {
  "disabledConnectors": "[hidden]",
  "forceRecognize": false,
  "scrobblePercent": 50,
  "scrobblePodcasts": false,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": true
}
wrapper.js:74 storage.Connectors = {
  "YouTube": {
    "scrobbleEntertainmentOnly": false,
    "scrobbleMusicOnly": true
  }
}
wrapper.js:74 storage.ConnectorsOverrideOptions = {}
wrapper.js:74 storage.Core = {
  "appVersion": "2.48.0"
}
scrobble-service.js:55 Unable to bind Last.fm
bindAllScrobblers @ scrobble-service.js:55
scrobble-service.js:55 Unable to bind Libre.fm
bindAllScrobblers @ scrobble-service.js:55
scrobble-service.js:69 Bind ListenBrainz scrobbler
scrobble-service.js:55 Unable to bind Maloja
bindAllScrobblers @ scrobble-service.js:55
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/md5.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
</details>

**Comment by pgueckel** [comment]
I just noticed something curious: when I log in to ListenBrainz in a separate tab in the browser, then recording listens from You Tube to my ListenBrainz account works again! I haven't tried opening a second You Tube tab and closing the first one, as I did when the problem was initially revealed; nor have I logged in to ListenBrainz in the options section of Web Scrobbler—why should this be necessary, as I have entered my token?

**Comment by pgueckel** [comment]
Just when I thought it was working, after having played 2 recordings in 2 separate browser tabs...

I decided to listen to a 3rd piece, so I queued it in You Tube. I didn't want to hear 2-3 minutes of applause at the end of the 'playing now' piece, so I clicked on the next piece. Suddenly, the green check mark turned into a red Last.fm logo and hovering says:

This site is supported for scrobbling.
Has access to this site

When I click on this popup, it asks whether I am playing music.

I next tried opening the same piece in a different browser tab, but nothing has changed. It is stuck on Last.fm and refuses to record further listens. ListenBrainz shows the previous track as 'playing now'.

**Comment by eggbean** [comment]
Are you using YouTube as an app? I got asked if I wanted to use it as an app, so there are no buttons or address bar, but now web-scrobbler is not recognised.

**Comment by pgueckel** [comment]
@eggbean I am using the Web Scrobbler extension with Google Chrome on my laptop. I was not aware that the Web Scrobbler extension could also be installed on Android.

**Comment by pgueckel** [comment]
I did more experimentation today. This time, I did not even bother to log in to ListenBrainz on a separate browser tab. Later, after my listening session, I had a look and I think that all my listens—3, perhaps 4—were recorded.

This issue is complex, as it sometimes occurs, sometimes not. What could be triggering it? Is it possible that some music videos are not recognized as music and are therefore not counted as listens? I have the Web Scrobbler extension configured to only record Music and not Entertainment from the You Tube and You Tube Music sites only.

**Comment by eggbean** [comment]
In Chrome (desktop)

**Comment by eggbean** [comment]
In Chrome (desktop), in the main menu (alt-f) > More Tools > Create ShortCut.. > And then select "Open as window". Now when you open that shortcut you get YouTube (or whatever you saved as a shortcut) open 'as an app' with no address bar or buttons. This is great for PWAs (Progressive Web Apps) and I have a of them saved.

But I was mistaken when I made that comment, as web-scrobbler does work for me when using that shortcut, but it doesn't work as the very similar YouTube Desktop, which appears the same, but has the ability to save and download videos for offline viewing. I think you need YouTube Premium for this. I describe the problem here: https://github.com/web-scrobbler/web-scrobbler/issues/3087

**Comment by lionnamedari** [comment]
Came by to say I'm having a similar issue in Opera GX. Though, it only seems to be music videos from Gorillaz. Tried letting the web scrobbler record entertainment, but that didn't fix the issue.
