### ISSUE TITLE
Direct link to "Your Scrobbles" page for track on Last.fm

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#3088]
Clicking the number of  scrobbles for track on the **web scrobbler** should take you to that page on last.fm

When we click the song name, **web scrobbler** takes you the page on last.fm and it should do the equivalent when clicking "Your Scrobbles"

**Example:**

When clicking the song name _This is the One_ the browser opens
https://www.last.fm/music/The+Stone+Roses/_/This+Is+the+One
![image](https://user-images.githubusercontent.com/4522620/146911363-28d06d41-e096-4fce-807b-3b6021695943.png)

When clicking the #7, it should open the list of scrobbles for the current user
![image](https://user-images.githubusercontent.com/4522620/146910499-218050c8-6ac6-4fe0-95e9-64fe524de2bf.png)

https://www.last.fm/user/[____LASTFM_USER____]/library/music/The+Stone+Roses/_/This+Is+the+One
![image](https://user-images.githubusercontent.com/4522620/146912371-35bba1b5-f202-491e-b989-f070263e3206.png)

**Additional context**

**Comment by yayuyokitano** [comment]
Closing, as this was implemented in V3 redesign
