### ISSUE TITLE
Bandcamp connector - filter out record side names

### ISSUE THREAD

**Issue by th0mk** [web-scrobbler/web-scrobbler#3093]
**Is your feature request related to a problem? Please describe.**
Some records on bandcamp have the side and track number in the track name. This is not part of the track name, but is only used to indicate where on the record the track is located. Since they're not part of the track name, I want to scrobble the track without it.

**Describe the solution you'd like**
It would be nice if the connector could detect the usage of these indicators and remove them from the track name.

**Describe alternatives you've considered**
Manually editing the track name is possible, but it requires some extra work.

**Additional context**
Some examples below:
![image](https://user-images.githubusercontent.com/9088316/147670409-0ddbae30-baf2-4d44-b560-23c64bde4f22.png)

![image](https://user-images.githubusercontent.com/9088316/147670455-3105de7a-db9f-4ae9-9a00-42fcea181eb2.png)

Examples on Bandcamp: 
- https://zementrec.bandcamp.com/album/002
- https://hectoroaks.bandcamp.com/album/neanderthal-disco

Note that it is possible for bandcamp listings to go further then A and B in case of multiple records in 1 listing (for example C1, C2, D1 etc)

**Comment by jaccarmac** [comment]
Another example I've noticed and been annoyed by: Anything by Psychic Liberation e.g. https://psychicliberation.bandcamp.com/album/in-gods-image
