### ISSUE TITLE
Qobuz web player adds artist to the album tag

### ISSUE THREAD

**Issue by Alsweider** [web-scrobbler/web-scrobbler#3095]
Playing songs on [Qobuz web player](https://play.qobuz.com/), the artist name is always added to the title of the album in the scrobbler, so I have to fix it manually for every song to avoid scrobbling incorrect album names like "Metallica - Metallica".

Browser: Brave 1.33.106 Chromium: 96.0.4664.110
Web Scrobbler version: 2.48.0

![2022-01-04 06_34_03-Window](https://user-images.githubusercontent.com/30653982/148014614-f7a45586-580a-4985-b4a1-6f7239e9fab7.jpg)

**Comment by justathoughtor2** [comment]
Same issue here. I infinitely prefer web scrobbler over Qobuz's built-in scrobbling capability, but this is a bit of a problem. I'll see if I can figure out a pull request. Should be simple enough to resolve.

**Comment by justathoughtor2** [comment]
Pull request #3194 submitted. This should resolve it, unless I overlooked something. It definitely works on my end, and all the CI tests pass. Hopefully this will get resolved for all users soon!

**Comment by inverse** [comment]
Will be in the next release! Thanks @justathoughtor2 for the fix

**Comment by justathoughtor2** [comment]
> Will be in the next release! Thanks @justathoughtor2 for the fix

Of course! Thanks so much for merging so quickly!
