### ISSUE TITLE
Scrobbler cannot detect music playing on Spotify web

### ISSUE THREAD

**Issue by ahnesther** [web-scrobbler/web-scrobbler#3105]
**Describe the bug**
When I am playing music on Spotify web, the scrobbler does not detect that it is playing music. 
Instead, the scrobbler looks like this: 
![image](https://user-images.githubusercontent.com/52338697/150402175-2ca4cc9f-3dcd-4d99-94d8-783b8594a4ad.png)
I suspect the scrobbler isn't picking up the music due to some UI changes on Spotify web.

**How to reproduce**
1. Go to play/open.spotify.com
2. Go to a song/album of your choice.
3. Press the play button.

**Expected behavior**
The scrobbler should detect Spotify web is playing music and should be scrobbling.

**Screenshots**
I threw in some screenshots.

**Debug logs**
I couldn't find debug logs, but I did take a look at the console and saw there was no info: 
![image](https://user-images.githubusercontent.com/52338697/150402934-de1141aa-2967-48d3-b564-159eec1bd0e9.png)
Playing music on bandcamp, console messages did show up: 
![image](https://user-images.githubusercontent.com/52338697/150403215-e634111f-a212-4936-a617-22d2eb2ff5f0.png)

**Environment (please complete the following information)**
-   OS: Mac, Windows 10 (reported by fillycolt)
-   Browser: Chrome Version 97.0.4692.71 (Official Build) (x86_64),  FF 96.0.2 (64-bit)
-   Extension version: 2.49.0

**Additional context**
N/A

**Comment by fillycolt** [comment]
Happening here too on Windows 10

**Comment by inverse** [comment]
![image](https://user-images.githubusercontent.com/713525/150434121-98497611-04be-49fc-8d74-42a383f05e66.png)

Not able to reproduce it :(

**Comment by flickur** [comment]
Stopped working after a chrome update this week for me.

**Comment by inverse** [comment]
@jaccarmac are you able to reproduce? perhaps its a Spotify feature rollout?

**Comment by jaccarmac** [comment]
I'm also unable to reproduce it in Chrome 99.0.4818.0.

@flickur What's your Chrome version after the update? You can see it in Help->About Google Chrome.

**Comment by ahnesther** [comment]
Oh yes, in lieu of @vertest-yt's comment, I should note that I am able to scrobble music on Bandcamp and Soundcloud as well.

**Comment by flickur** [comment]
> I'm also unable to reproduce it in Chrome 99.0.4818.0.
> 
> @flickur What's your Chrome version after the update? You can see it in Help->About Google Chrome.

Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by jaccarmac** [comment]
That sounds a lot like a web player update being rolled out. Right now, my browser is pulling `https://open.scdn.co/cdn/build/web-player/vendor~web-player.b55b20c9.js`, which I believe is the main script in question. I don't use Spotify much, but I'll watch it and see what I can do.

**Comment by inverse** [comment]
Could be an update. still not rolled out to here in DE.

**Comment by Ernsthemingway1** [comment]
I'm having exactly that problem with my web spotify...
![Sin-título-1](https://user-images.githubusercontent.com/93142555/151050463-2f2fe88a-6be8-43a9-ba67-ca0f57a00f71.jpg)

**Comment by vertest-yt** [comment]
yeah, i'm using web-spotify too

**Comment by 0edit** [comment]
Same. Was working two hours ago. It works on Bandcamp and other sites.

**Comment by jaccarmac** [comment]
I got the update and will work on getting the connector up to speed.

**Comment by jaccarmac** [comment]
Anyone who is comfortable doing so: I welcome your feedback on that PR. The solution may be brittle, but it does seem to work for me.

**Comment by shodate76** [comment]
> Anyone who is comfortable doing so: I welcome your feedback on that PR. The solution may be brittle, but it does seem to work for me.

what is  the solution

**Comment by jaccarmac** [comment]
There's a fix in https://github.com/web-scrobbler/web-scrobbler/pull/3109, but it should be rolling out soonish, eventually to the extension stores.

**Comment by vertest-yt** [comment]
can't see the fix, it's still not working

**Comment by inverse** [comment]
It'll be in the next release

**Comment by shodate76** [comment]
> Anyone who is comfortable doing so: I welcome your feedback on that PR. The solution may be brittle, but it does seem to work for me.
what about the fix  3108

**Comment by hans-juergen** [comment]
So this only happened when pausing Spotify in Firefox, or do I understand something wrong here?

**Comment by inverse** [comment]
It's not just Firefox - seems to be they are rolling out a new design

**Comment by vertest-yt** [comment]
so despite it's said it's been rolled out, it still doesn't work on web FF spotify

**Comment by hans-juergen** [comment]
Thanks, I was asking due to the frequent support forum threads about Spotify not scrobbling, so I'll have to check if users are using Web Scrobbler in which browser etc.

**Comment by inverse** [comment]
@vertest-yt working for me in both Chrome and Firefox

@hans-juergen unfortunately the Edge version is manually pushed. @alexesprit if you have a few minutes would be great if you could push there 👍🏼

**Comment by vertest-yt** [comment]
@inverse inversehow can it be.. i've just updated FF one more time and still see "Play some music to get started. Is it already playing?" Did you reinstall the scrobler from the bar or it's starts working for you?
