### ISSUE TITLE
Way to disable logging to console?

### ISSUE THREAD

**Issue by Tamarindo94** [web-scrobbler/web-scrobbler#3110]
The logs might be useful, but they become annoying when trying to debug other scripts by using logs. I haven't found a way to disable them...

**Comment by inverse** [comment]
Could be exposed as a setting within core - happy to have someone contribute this 👍🏼

**Comment by EvHaus** [comment]
console.log spam seems to have gotten a lot worse in v3.x.x. Is it possible to disable this?

![image](https://github.com/web-scrobbler/web-scrobbler/assets/226640/c1ecc039-f65e-4bd9-87e5-1d1fa9d87b84)

**Comment by Tamarindo94** [comment]
The logging seems to be done by function Util.debugLog() in file util.ts; it could be modified to print only if a certain variable is true - the variable could be a user setting, or the installType of the extension, something like: 
```
if(chrome.management.get('installType') == "development" || userSetting === true) {
  // print debug
} else {
  // don't print
}
```

**Comment by xul7** [comment]
I'm sure it was added for debugging and then forgot to remove it

https://github.com/web-scrobbler/web-scrobbler/blob/a4d2d0de1753532c905aaa1a9527d1ea191679f1/src/core/storage/wrapper.ts#L241

**Comment by mklusak** [comment]
This is insane, how am I supposed to develop something and find my output to Dev console, when I have the dev console full of hundreds of useless lines from this extensions?

But, I found a quick solution how to remove Chrome extensions outputs from Dev console -> https://superuser.com/a/1346827

**Comment by busybox11** [comment]
You can also just right click on any of webscrobbler's logs and click on 'Hide messages from main.js' (it will only hide WebScrobbler's index.js logs)
![image](https://github.com/web-scrobbler/web-scrobbler/assets/29630035/3c8c1f8e-3082-4f51-869d-1e278fc37457)

**Comment by inverse** [comment]
Some noisy logs have been removed from production builds - which should improve things. 


But as @busybox11 said you can easily filter out logs from our extension.

**Comment by on3dd** [comment]
It's ridiculous that you're logging something using console.log in production environment. When will we be able to turn it off without messing with "Hide messages from..."? 🤦🏻

**Comment by LasseGuldhammer** [comment]
There should definitely be an option to disable the logging. As a developer, these logs are simply noise that I can't turn off.

**Comment by inverse** [comment]
> There should definitely be an option to disable the logging. As a developer, these logs are simply noise that I can't turn off.


Pull requests welcome :)

**Comment by blimpage** [comment]
I've submitted a pull request that implements an option that silences logging now: #4067 I'd love any feedback on it!

**Comment by yayuyokitano** [comment]
Just noticed this is still open. This is already implemented. In newer versions it is under advanced settings and defaults to not displaying logs in console. Exceptions may still ignore the setting though, since those could be thrown outside our error logging system.
