### ISSUE TITLE
Web Scrobbler 2.50.1 does not scrobble on Chrome

### ISSUE THREAD

**Issue by rgoudie** [web-scrobbler/web-scrobbler#3113]
The new version does not scrobble on Chrome. My previous workaround of closing and restarting the browser no longer works. (Tried multiple times.)

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: 2.50.1

**Comment by inverse** [comment]
Unable to reproduce - the only change that went into the patch release was a fix for Spotify due to the rollout of a new design. Where you having issues?

**Comment by rgoudie** [comment]
Yes, the extension icon remains red, indicating that it is not recognizing Spotify. Nothing has changed on my side other than the update to the extension and, perhaps, Chrome updating itself.

Previously, when the icon would remain red after starting some music on Spotify, I could relaunch the browser and the icon would turn green and start scrobbling. That workaround did not work today.

**Comment by rgoudie** [comment]
I just tried listening to a song and the icon remained red. the extension does not seem to be recognizing Spotify.

**Comment by painchen88** [comment]
I got the same trouble. I use Chrome. I can not scrobble from Spotify. It does not work.

**Comment by megamig20** [comment]
I've got the same issue today - tried logging in/out of last.fm and Spotify as well disconnecting the app permissions.

**Comment by kakyoins** [comment]
this is also happening to me

**Comment by luthor000** [comment]
It's not working for me either.

**Comment by Joe-Degs** [comment]
I just realised I have the same problem. Can't scrobble from spotify on chrome

**Comment by ahnesther** [comment]
I'm able to scrobble on Firefox (93.0, 64bit) but not Chrome either (Version 97.0.4692.99 (Official Build) (x86_64)).

**Comment by r0ck3tracc00n1** [comment]
Same issue: Windows 10 21H1, Chrome  97.0.4692.99 x64, Web Scrobbler v2.50.1
Spotify won't scrobble. Plugin is red and said "Play some music to get started".

**Comment by inverse** [comment]
@jaccarmac looks like we might need to support both selectors :/

**Comment by inverse** [comment]
Pushed a change & released a new version that used both the new and old selector which should resolve the issue. 

Please comment on this if it hasn't after updating to `v2.50.2`

**Comment by rgoudie** [comment]
The issue has indeed been resolved for me with version 2.50.2. My icon is green and songs are again being scrobbled.

Thank you for your dedication to this project.
