### ISSUE TITLE
last fm not scrobbling on any website

### ISSUE THREAD

**Issue by ben4xd** [web-scrobbler/web-scrobbler#3115]
hi! my last.fm scrobbler has been working fine for the past year, however today it has been playing up and not scrobbling anything. i logged out and logged in on everything but still no sign of any scrobbling. any help? 

thanks.

**Comment by inverse** [comment]
Hi @ben4xd, 

What websites do you normally scrobble on that are having issues? 

There was an issue with Spotify due to a layout change that we fixed today - https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.50.2

It should be available in Chrome and Firefox extension stores already.

**Comment by yasminviana** [comment]
I can't scrobble youtube songs on chrome browser for windows 10
