### ISSUE TITLE
Plex not working

### ISSUE THREAD

**Issue by jag426** [web-scrobbler/web-scrobbler#3121]
Doesn't recognize that music is playing anymore. Both Chromium and Firefox, both via app.plex.tv and visiting the server directly.

I'm on version 2.50.2 and plex version 1.24.3.5033.

**Comment by fckawe** [comment]
I was able to reproduce the error.

The connector defines pauseButtonSelector as an array:

```
Connector.pauseButtonSelector = [
	`${Connector.playerSelector} [data-testid="pauseButton"]`,
	`${Connector.playerSelector} [class^=plex-icon-player-pause]`,
];
```

Not sure what that means exactly, but obviously both of the two selectors have to match. The first one does, but the second one does not.
So if I change the pauseButtonSelector to:

```
Connector.pauseButtonSelector = `${Connector.playerSelector} [data-testid="pauseButton"]`;
```
... it works here.

Can someone say if this would be a proper solution?

**Comment by mjb187** [comment]
Adding onto this:

It appears that music detection only works when the play/pause button along the bottom of the screen is clicked. This means that, if you click "play" on an album or song outside of that context (ex: from the library screen), the scrobbler doesn't detect it. I've been working around this by clicking play, letting the song play for a few seconds, reloading the page, and then clicking "play" on the player at the bottom of the screen. This works every time, but obviously it's an imperfect solution.

**Comment by alexesprit** [comment]
Is this still an issue? I use Plex and Web Scrobbler daily, and it works flawlessly. I use UI from my Plex server (though the one from app.plex.tv works fine as well).
