### ISSUE TITLE
Bandcamp not scrobbling

### ISSUE THREAD

**Issue by cissipissi** [web-scrobbler/web-scrobbler#3122]
Bandcamp is currently not scrobbling anymore, though the web scrobbler icon says it is supported. 

Using Firefox v, 96.0.3, WIN 10, extension v. 2.51.0

**Comment by inverse** [comment]
Do you have a URL that's problematic? I'm unable to reproduce it on any page.

**Comment by Robronie** [comment]
https://bandcamp.com/?show=522 scrobbling doesn't work anymore when playing the bandcamp shows

**Comment by cissipissi** [comment]
It's all of them for me but here's one:

https://theluyas.bandcamp.com/track/i-cant-forget

**Comment by jilherme** [comment]
1. Browser: Firefox V96.0.3
2. Extension: WS V2.51.0
3. Problematic URL: https://aliceglass.bandcamp.com/

Tryied @cissipissi 's URL and didn't work either.

**Comment by inverse** [comment]
Verified the issue and will get a fix rolled out when I have time

**Comment by inverse** [comment]
Just published https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.51.1

**Comment by cissipissi** [comment]
Sorry is it supposed to work now? It still doesn't for me. It works on pages with albums, but ones with a single track don't scrobble. 
Works: https://lucydacus.bandcamp.com/album/home-video
Doesn't work: https://lucydacus.bandcamp.com/track/kissing-lessons

**Comment by inverse** [comment]
@cissipissi did you upgrade to `v2.51.1`?

**Comment by cissipissi** [comment]
@inverse How do I do that? Sorry I'm a dummy.

**Comment by inverse** [comment]
Your browser should automatically do it but you can force check for update in settings.

**Comment by cissipissi** [comment]
Oh I've done that but it just says that no updates were found.

**Comment by cissipissi** [comment]
@inverse Nevermind I reinstalled it so I got the update now. Thanks!
