### ISSUE TITLE
Unable to scrobble on Street Voice

### ISSUE THREAD

**Issue by seiweg** [web-scrobbler/web-scrobbler#3132]
Describe the bug
The web scrobbler is unable to track on https://streetvoice.com/, but on chrome-extension://hhinaapppaileiechjoiifaancjggfjm/ui/options/index.html, it clearly says Street Voice is supported. 

How to reproduce
1. Go to https://streetvoice.com/
2. Click on the web scrobbler extension 
4. A message pops up, which reads "Web Scrobbler does not support scrobbling from this website".

Expected behavior
I hope this problem can be fixed, and scrobbling is allowed on Street Voice. 

Screenshots
![image](https://user-images.githubusercontent.com/99791084/154219274-fa60f16b-13cc-4dd5-ac49-2b750a0a1d1c.png)

Debug logs
<details>
  <summary>Debug log</summary>
  Here is the content of debug log: ``` storage.ConnectorsOverrideOptions = {
  "soundcloud": {
    "forceRecognize": false,
    "scrobblePodcasts": false,
    "useNotifications": false,
    "useUnrecognizedSongNotifications": false
  }
}```
</details>

Environment:
-   OS: Windows
-   Browser: Google Chrome
-   Extension version: 2.52.0

**Comment by inverse** [comment]
Should be fixed in the latest release 👍🏼

**Comment by seiweg** [comment]
> Should be fixed in the latest release 👍🏼

thank you!
