### ISSUE TITLE
Like/Edit/Reset/etc buttons are squared out

### ISSUE THREAD

**Issue by ahnesther** [web-scrobbler/web-scrobbler#3133]
**Describe the bug**
I noticed that the Like/Edit/Reset/etc buttons have been squared out instead of seeing aa heart/pencil/loop/etc button.

**How to reproduce**
1. Go to a site where you play music (I used Spotify)
2. Play music
3. Click the Web Scrobbler extension

**Expected behavior**
The buttons should have its respective buttons like below:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/52338697/154311129-6fe038b2-8b6d-405d-8241-ddb1d544beca.png">

**Screenshots**
Actual behavior:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/52338697/154310993-9fa19e67-844e-41ef-ae7a-7dac0bec8ddb.png">

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Mac Catalina, 10.15.7
-   Browser: Chrome Version 98.0.4758.80 (Official Build) (x86_64)
-   Extension version: 2.52.0

**Additional context**

**Comment by fetzu** [comment]
Same here (on Firefox 97.0); it is very likely due to the recent bump  to FontAwesome 6.0.0. 

I had a look at their changelog, but they do specifically mention that everything is backwards-compatible.

I found an issue on their repo mentioning something similar (will edit here when I find it).

**Comment by fetzu** [comment]
There you go, fiddling around with GitHub was more time-consuming than the actual fix ^^...

**Comment by inverse** [comment]
@fetzu thanks for the fix 👍🏼
