### ISSUE TITLE
Connector for fluxfm.de doesn't work anymore

### ISSUE THREAD

**Issue by fckawe** [web-scrobbler/web-scrobbler#3142]
The connector for the web radio on fluxfm.de ("Flux FM Berlin", already listed as supported website) does not work anymore. They have recently redesigned their website including the web player.
Any chance of getting this back to work?
Thanks in advance!

**Comment by ichmoimeyo** [comment]
https://www.fluxfm.de/channels/f71292b4-14b1-4353-96b5-2114a0793334

Jazzradio Schwarzenstein not working.
