### ISSUE TITLE
Randomly Scrobbles on YouTube, Never consistent

### ISSUE THREAD

**Issue by CainDev** [web-scrobbler/web-scrobbler#3143]
**Describe the bug**
The bug will only scrobble random songs when it feels like it. I have tried different pages/songs and its completely random. Although there is one song I can consistently break the Scrobbler with. "EDEN - End Credits (feat. Leah Kelly)"

**How to reproduce**
1. Click a song

**Expected behavior**
Scrobble the song

**Screenshots**
https://imgur.com/a/iKAq8wz

**Debug logs**
The only thing that is logged is "Tab 8: Received empty state - resetting". This is logged 100% of the time when playing "EDEN - End Credits (feat Leah Kelly)

**Environment (please complete the following information)**
-   Windows 10
-   Chrome
-   2.52.3

**Comment by MXB2001** [comment]
Same here, under Linux with Firefox. Reloading YT seems to fix it sometimes for a little while.

**Comment by jaccarmac** [comment]
I'm unable to duplicate the issue on that track.

**Comment by CainDev** [comment]
> 

Thats odd. Because if you check on Last.fm you can see that literally no one is scrobbling the song.
![image](https://user-images.githubusercontent.com/36238059/155743492-9d32af1b-18d6-493a-96db-628793857be4.png)

**Comment by jaccarmac** [comment]
I don't doubt that this is breaking for folks; I simply can't duplicate the 100% failure rate you describe.

However, that isn't the version of the song which would be picked up by this scrobbler from [the YouTube video](https://www.youtube.com/watch?v=0pVABElms84), as the feature is in the artist field and not the track field. You see low scrobble counts on album pages for that reason from time to time.

On top of that, I took the liberty of [scrobbling several variations manually](https://web.archive.org/web/20220226054637/https://www.last.fm/user/jaccarmac/library). So it's not that Last.fm is rejecting the scrobble.
