### ISSUE TITLE
Can scrobble through Youtube but can't scrobble through Soundcloud

### ISSUE THREAD

**Issue by kevinluong2505** [web-scrobbler/web-scrobbler#3155]
So my scrobbler worked for Youtube but not on Soundcloud even though it was fine few days ago. Is there any way I can fix this problem? 
![image](https://user-images.githubusercontent.com/100891091/156693433-55aa2d72-20a7-4f9e-b5ed-459a7703ca62.png)
![image](https://user-images.githubusercontent.com/100891091/156693485-1d1d1962-b425-42bb-ae9a-fd838bab9719.png)

**Comment by inverse** [comment]
Are you able to provide any logs? It's working for me :(

**Comment by kevinluong2505** [comment]
> 

DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/md5.min.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by kevinluong2505** [comment]
DevTools failed to load source map: Could not load content for http://ent/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/52-35c65882.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/50-da11f65d.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/51-30d383c2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/1-e3547258.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/3-ca0404ff.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/2-df01f315.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/0-1932678d.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/49-986052a3.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/12-ac572341.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/29-98afbf5d.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for http://ent/web-sourcemaps/css/app-d056f868f2b77590d70a.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Comment by kevinluong2505** [comment]
idrk which one it is

**Comment by inverse** [comment]
Wonder why your browser is trying to load source maps for everything.

Check https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension And report back with full logs to help us diagnose this further.
