### ISSUE TITLE
Not scrobbling 

### ISSUE THREAD

**Issue by McKenziehht** [web-scrobbler/web-scrobbler#3160]
I'm having trouble scrobbling on every website, when I click on the extension it says this website is not supported, I've tried on multiple websites including; YouTube, YouTube Music, Spotify Web Player and Soundcloud.

**Comment by inverse** [comment]
Could you provide more information for us to diagnose the problem?

- What browser/version? 
- What extension version?

Have you tried restarting your browser?

**Comment by McKenziehht** [comment]
I am using Google Chrome, and it is the current version 
And the version of the extension is version 2.55.0 (this is what it says on the chrome web store) 
and I have tried restarting my browser many times. no luck.

**Comment by inverse** [comment]
Are you able to provide any logs? See: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

I'm unable to reproduce the issue from my side.

**Comment by ahnesther** [comment]
Hi, I've seen the same issue but on Firefox 98.0 (64-bit) and Youtube. Have not tried Chrome or Spotify.
![image](https://user-images.githubusercontent.com/52338697/157363434-fdadf7a2-db4b-4508-8ce1-84a34daa08e3.png)

**Comment by Pepegoose** [comment]
Hey, thanks for the great extension. But with the last Chrome update having the same issue: doesn't scrobble YT Music (other music sites work fine) 
From YT Music page: https://pastebin.com/DizhiY9E
From extension page: https://pastebin.com/9dZV2tMx

**Comment by leniel** [comment]
Same thing here: Listening to some YouTube music https://www.youtube.com/watch?v=tqgTSGVs0yc and the extension is not scrobbling at all... Google Chrome Version 99.0.4844.51 (Official Build) (arm64)

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/764854/157542805-3cbcf269-3d87-428f-9113-a1600655e88f.png">

**Comment by inverse** [comment]
@McKenziehht are you still having issues? some users reported   a recent chrome update broke things

Try: https://github.com/web-scrobbler/web-scrobbler/issues/3166#issuecomment-1065272378

**Comment by MaciekBaron** [comment]
It's broken for me again (commenting here as the previous issue was closed).

Reauthorised Last.fm and still no luck.

**Comment by McKenziehht** [comment]
> @McKenziehht @Pepegoose are you still having issues? some users reported a recent chrome update broke things
> 
> Try: [#3166 (comment)](https://github.com/web-scrobbler/web-scrobbler/issues/3166#issuecomment-1065272378)

I am no longer having issues after trying #3166 thank you
