### ISSUE TITLE
please add WorldFusionRadio

### ISSUE THREAD

**Issue by jonpsp** [web-scrobbler/web-scrobbler#3164]
Hello.

Please add WorldFusionRadio.com.  It has two streams:-
https://worldfusionradio.com/home-page/world-revolutions/
https://worldfusionradio.com/home-page/global-chillout/

It looks like the now playing info is loaded from another page
by this: 
`<td class="column-2"><center><iframe title="now_playing" src="https://marci666.marci.io/" name="now_playing" scrolling="no" width="340" height="440" frameborder="0"></iframe></center></td>`

The actual now playing details look like this:-
`<div class="clearfix" id="block1" style="display:block;min-height:98px;width:100%;background:#ffff99 url(img/tiles/pixelated_04.png) center right;border-top:1px solid #000;border-bottom:1px solid #000;"><p class="time">12:27  GMT</p><p class="title">Le temps s'immobilise</p><p class="artist">Samia Farah</p><p class="album">Samia Farah</p><div class="iconBench"><ul class="raterWare" style="float:left;"><li><a target="_blank" href="http://www.amazon.com/s?ie=UTF8&amp;tag=worfusrad03-20&amp;index=digital-music&amp;link_code=qs&amp;field-keywords=Samia%20Farah%20Le%20temps%20s%26apos%3Bimmobilise" class="amazon"><img src="img/icons/amazon.png" alt="Buy Samia Farah - Le temps s'immobilise on Amazon MP3" width="16" height="16"></a></li></ul></div></div>`

**Comment by inverse** [comment]
Will be in the next release
