### ISSUE TITLE
some bandcamp albums don't scrobble

### ISSUE THREAD

**Issue by marado** [web-scrobbler/web-scrobbler#3165]
**Describe the bug**
Some bandcamp albums get the plugin indication that they're recognized and going to be scrobbled, but the scrobbles don't show up on last.fm.

**How to reproduce**
1. Go to https://houseofmythology.bandcamp.com/album/slava-ukraini (or another release with the same issue, but this is one of them) on Firefox 97.0.2 (I did not try in another browser or version)
2. Click on play and see the plugin indicator correctly identifying the tracks, just like it shows when the tracks get scrobble (including firing up the notification when a new track starts)
3. Watch the configured last.fm account and realize that the tracks don't show up there

**Expected behavior**
The tracks should be scrobbled.

**Screenshots**
I can make any screenshots you want/need if this description is not enough and you are not able to reproduce the problem.

**Debug logs**
I did not grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension), but if you can't reproduce it or in any case think that they'd be useful let me know, and I'll gladly get them.

**Environment (please complete the following information)**
-   OS: Ubuntu GNU/Linux
-   Browser: Firefox
-   Extension version: 2.55.0

**Comment by inverse** [comment]
Unable to reproduce - the album sscrobbles properly.

**Comment by marado** [comment]
I wasn't counting on that. I'll see how to fetch the logs.

**Comment by marado** [comment]
Scrobbling bandcamp compilations is working in others, and here's the "content log" when it works...
![content-ok](https://user-images.githubusercontent.com/33163/157890234-f0a77cb0-eadc-4c23-8b08-ae9291e81f7d.png)
and here's in the compilation it doesn't:
![content-fail](https://user-images.githubusercontent.com/33163/157890241-372c209b-a608-4390-8370-6d25d8879d48.png)
(No observable difference).

Full console logs (on the page that does not work) in this file: 
[console-export-2022-3-11_14-53-22.txt](https://github.com/web-scrobbler/web-scrobbler/files/8232931/console-export-2022-3-11_14-53-22.txt)

I tried to look at how can I get the "Logs of the background script", but the How-To at https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#how-to-get-logs-on-firefox points to a "Debug" button that does not seem to exist in my version of Firefox version; I tried to find some Firefox documentation on how to do that in this version, but... my search was fruitless. I'll gladly gather those logs too, if someone can guide me on how to gather them in this version of Firefox.

**Comment by MaciekBaron** [comment]
I'm having the same issue, none of the bandcamp pages work for me anymore.

Version: 2.55.0
Browser: Chrome
OS: Windows

URLs tested:

https://acorntapes.bandcamp.com/album/detours
https://tmshallibrukit.bandcamp.com/album/stealin-tribe-monsta-zero-rejigz
https://egoellamay.bandcamp.com/album/fieldnotes-pt-ii
etc..

Message displayed:

![image](https://user-images.githubusercontent.com/1668712/157897358-d96e5655-8b8c-4583-a7c7-385eae09cff9.png)

**Comment by inverse** [comment]
@marado interesting the logs displayed seem to show it picked up the state change. I'm not too familiar with Firefox but I updated that page with how to get the logs.

Can't reproduce in Firefox either :/

If you could check the logs with the updated wiki page let me know..

**Comment by fckawe** [comment]
@inverse I could reproduce that on Chrome (Vivaldi) - see [log.txt](https://github.com/web-scrobbler/web-scrobbler/files/8237294/log.txt).

I first had Spotify running to ensure it works and had that title "scrobbling now". Stopped Spotify then and started the track on the given bandcamp link. Log said track would be "scrobbling now" but couldn't see it on my last.fm profile. Later log said that it has been scrobbled, but still no scrobble on last.fm.

Same behaviour with other tracks of that bandcamp album...

**Comment by inverse** [comment]
@fckawe thanks for confirming. Yeah I dug in deeper and the connector is picking things up correctly and sending stuff to last.fm and getting valid responses back from the logs I saw.. but for whatever reason is not showing up as now playing. 

what's even more interesting is I connected my libre.fm account too and that works just fine so it appears to be something on last.fm side for this album.

**Comment by marado** [comment]
That is quite weird: the compilation, including C93's tracks, have been getting scrobbles…

https://www.last.fm/music/Current+93/Slava+Ukraini!

**Comment by fckawe** [comment]
I've made a test with my desktop music player, that scrobbles via plugin: Took some random .mp3 file and changed the tags to match the data that web-scrobbler sends to last.fm. Didn't scrobble either.

I then changed the artist to something else - didn't work.
Shortened the album artist to "Various Artists Foo" - didn't work.

But if you change the album artist to "(Fundraiser for Ukraine)" it scrobbles, while "Foo Various Artists" also doesn't work.
So it seems like last.fm didn't want the album artist to contain "Various Artists"...

**Comment by inverse** [comment]
@fckawe good investigation - so it's the fact we're mapping the album artist with this connector.

**Comment by fckawe** [comment]
@inverse ... on the other hand: isn't the album artist inteded exactly for this reason, to be "Various Artists" if it's a soundtrack album or something like that?
Maybe it has to be "Various Artists" without anything around. I'll give this another try...

**Comment by inverse** [comment]
Thanks for investigating! We could add a filter to clean that up then.

**Comment by marado** [comment]
Another nice enhancement would be to not indicate visually that the scrobble was s succcess when ignoredMessage is 1.

**Comment by inverse** [comment]
Added new filter https://github.com/web-scrobbler/metadata-filter/pull/216

Need to see how to release new package for this



@marado good idea! Will create new issue for this!

**Comment by marado** [comment]
Tracks from https://heimatderkatastrophe.bandcamp.com/album/hdk-120-hdk-dungeon-synth-magazine-6 aren't being scrobbled either (they appear to scrobble, but then don't show up on last.fm), and the album artist is "V. A.", so I am wondering if this isn't a similar case. Since this issue is still open, I thought it didn't make sense to open a new one for this case, but let me know if you prefer having distinct issues!

**Comment by inverse** [comment]
Just published a new release with the fix! Thanks @fckawe for helping 🙏🏼
