### ISSUE TITLE
wont scrobble ( chrome ) 

### ISSUE THREAD

**Issue by pinlias** [web-scrobbler/web-scrobbler#3166]
Im having trouble on all websites, tried soundcloud and youtube and spotify but it just didnt work. Keeps saying the website isnt supported. Tried refreshing page and restarting browser and the pc.
extension version 2.55.0
chrome version  99.0.4844.51 64 bits
logs: https://pastebin.com/rQtvtuUs
sorry if i messed w the logs i dont really know how to do them, tried following the instructions on debug page

**Comment by MaciekBaron** [comment]
In #3165 I thought that only Bandcamp is broken, but actually the extension stopped working for me everwhere too.

**Comment by pinlias** [comment]
> In #3165 I thought that only Bandcamp is broken, but actually the extension stopped working for me everywhere too.

are you using the same browser and extension versions than me ?

**Comment by inverse** [comment]
Interesting I just reinstalled the extension on my laptop from the Chrome store and it's working fine.

Chrome: 99.0.4844.51
OS: Linux
Extension: 2.55.0

@pinlias in your report I can see it trying to load  `.map` suffixed files...

**Comment by MaciekBaron** [comment]
I reauthorized Last.fm and did `chrome://restart` and it works now 👍

**Comment by andybe29** [comment]
> I reauthorized Last.fm and did `chrome://restart` and it works now 👍

did same and works

**Comment by MaciekBaron** [comment]
I'm having the same issue again. I've tried reauthorising and resetting and no luck this time.

**Comment by Yakffey** [comment]
Having the same issue on YouTube. Seems Spotify and such are fine but YouTube won't scrobble whatsoever as of today

**Comment by inverse** [comment]
@MaciekBaron anything in the logs?

**Comment by MaciekBaron** [comment]
It's suddenly working again. I didn't change anything.

**Comment by inverse** [comment]
Perhaps something with last.fm API? But usually the extension warns on this.

**Comment by MaciekBaron** [comment]
I don't think it's the API as the extension says the website is incompatible, unless this is how it behaves when there is an API issue?

**Comment by andybe29** [comment]
Web Scrobbler disappeared from Suggested Applications in last.fm's Settings page

**Comment by yayuyokitano** [comment]
I see there's still some activity here. I suspect this issue is probably related to #3184 which should be fixed in the next version. For the time being the workaround seems to be just restarting until it works.

**Comment by inverse** [comment]
New version has been published with that fix 👾 https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.57.1

**Comment by MaciekBaron** [comment]
Thank you @inverse ! Appreciate all your hard work.
