### ISSUE TITLE
Won't scrobble kkbox

### ISSUE THREAD

**Issue by Mif-cl** [web-scrobbler/web-scrobbler#3171]
**Describe the bug**
Cannot detect any song on KKBOX

**How to reproduce**
1. Go to 'https://play.kkbox.com'

**Debug logs**
https://pastebin.com/NC1vtXy9

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.55.0

**Comment by inverse** [comment]
Hi @Mif-cl !

Looks like things were injected fine on the backend side of things.

Are you able to provide any logs from the webpage itself?

See: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-content-scripts

Unfortunately I don't have an account on kkbox :(

**Comment by Pepegoose** [comment]
Hey @inverse, thanks for the great extension. But with the last Chrome update having the same issue: doesn't scrobble YT Music (other music sites work fine)
From YT Music page: https://pastebin.com/DizhiY9E
From extension page: https://pastebin.com/9dZV2tMx

**Comment by inverse** [comment]
Hi @Pepegoose please open a new issue regarding this. It could be that you're facing similar issues to other recent issues.

Check: https://github.com/web-scrobbler/web-scrobbler/issues/3166#issuecomment-1065272378 to see if that solves it.

**Comment by Pepegoose** [comment]
@inverse thank you, that helped

**Comment by Mif-cl** [comment]
> Hi @Mif-cl !
> 
> Looks like things were injected fine on the backend side of things.
> 
> Are you able to provide any logs from the webpage itself?
> 
> See: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension#logs-of-content-scripts
> 
> Unfortunately I don't have an account on kkbox :(

Hey, first of all, Thanks for the great extension and the hard works that everybody put in.
Here's the log: https://pastebin.com/t7FuiHsd

**Comment by inverse** [comment]
hi @Mif-cl I can see the issue

```
util.js:541 Web Scrobbler: Element '.right-column' is missing
```

It looks like they changed the selectors. Looking at our code I see we have two integrations for the legacy and beta layouts. Perhaps they finally switched.

@yayuyokitano would you be able to handle the update of this as I saw you contributed to this recently? 🙏🏼

**Comment by yayuyokitano** [comment]
I'll have a look into it

**Comment by Mif-cl** [comment]
@yayuyokitano Thanks so much but I am getting a new error like this: https://pastebin.com/jG6iJ8yF

**Comment by Mif-cl** [comment]
@inverse ah yes the error is gone now. However, the inspector does show that:

Web Scrobbler: Element '._2eEzN2' is missing

(Since it is just 1 line I thought I'll drop it here instead of going to pastebin.

**Comment by yayuyokitano** [comment]
> @inverse ah yes the error is gone now. However, the inspector does show that:
> 
> Web Scrobbler: Element '._2eEzN2' is missing
> 
> (Since it is just 1 line I thought I'll drop it here instead of going to pastebin.

Looks like they updated the site again yesterday breaking the connector, gonna reopen this and create another PR

**Comment by Mif-cl** [comment]
Thank you all for all the hard work. orz
