### ISSUE TITLE
Automatically remove the " - Single" and " - EP" suffixes from scrobbles when playing music from the Apple Music web player.

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#3186]
**Is your feature request related to a problem? Please describe.**
The Web Scrobbler's built-in metadata filter doesn't automatically remove the " - Single", " - EP", and many other suffixes from the album field when scrobbling music using the Apple Music web player. It's too time-consuming and cumbersome to have to do it manually every time I play music.

**Describe the solution you'd like**
I want the functionality to be available in the extension to have the extension do this automatically.

**Comment by xCakes** [comment]
this would be fire ^^
