### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by RadioDemon27** [web-scrobbler/web-scrobbler#3202]
I using Opera browser and when i try to use the Web Scrobbler with Deezer its shows up this message:

Looks like something went wrong while scrobbling the music. Please open the options page and try to reauthenticate with services. If reauthentication doesn't help, and you still see this message, please create [a new issue](https://github.com/web-scrobbler/web-scrobbler/issues) at the GitHub project page.

**Comment by yayuyokitano** [comment]
Some immediate steps you can try to take (please let us know your results)

Step 1:
Try to authenticate/reauthenticate with the scrobbling service you use on the web scrobbler options page (linked in the error message)

Step 2 if not fixed:
Please try to scrobble with openscrobbler
If openscrobbler doesnt work you are most likely temporarily unable to scrobble to your account. Either the scrobbling service is temporarily down or your account is rate limited (for instance, lastfm has a rate limit of about 3000 scrobbles per day after which third party applications no longer are able to scrobble. Note that the official lfm spotify integration bypasses this)

Step 3 if openscrobbler works but web scrobbler doesn't:
Please go into the settings of your scrobbling service such as lastfm and remove web scrobbler if it is already there. In lastfm you can do this [here.](https://www.last.fm/settings/applications)
Restart your browser, go to deezer and try to play a song.
Follow the error message to options menu and authenticate with your scrobbling service.
If it still doesnt allow you to scrobble please send background script logs as described [here.](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) Please also let us know whether or not web scrobbler displays in your applications list on your scrobbling service.

**Comment by RadioDemon27** [comment]
[image: Tarzan Boy - Baltimora - Deezer - Opera 2022. 04. 04. 16_14_24.png]This
is what i get when i play something in deezer

yayuyokitano ***@***.***> ezt írta (időpont: 2022. márc. 31.,
Cs, 20:02):

**Comment by RadioDemon27** [comment]
*everywhere

Bendegúz Kis ***@***.***> ezt írta (időpont: 2022. ápr. 4.,
H, 16:16):

**Comment by yayuyokitano** [comment]
Have you followed the steps I have written in my previous comment?
If so and you still have issues, please post logs as described in my previous comment.
If you are stuck at some part of the steps, please let me know what you are stuck on and I can help to specify.

**Comment by RadioDemon27** [comment]
is it a problem that im not logged into any of these?[image: image.png]

yayuyokitano ***@***.***> ezt írta (időpont: 2022. ápr. 4.,
H, 19:40):

**Comment by yayuyokitano** [comment]
I cannot see your image, but yes, you have to log in with either last.fm, libre.fm, listenbrainz, or maloja to use the extension, if you're not logged into any of them it will display the error you describe.

**Comment by yayuyokitano** [comment]
Hello, could you let me know whether or not you still have this issue, or if you were able to sort it out

**Comment by RadioDemon27** [comment]
Yes it still works but i don't use it currently bc i had to re install my
browser and i was lazy to reinstall that too

yayuyokitano ***@***.***> ezt írta (időpont: 2022. ápr. 20.,
Sze 14:22):

**Comment by yayuyokitano** [comment]
Gotcha, I will close this issue then, thank you.
