### ISSUE TITLE
Using web scrobbler on last.fm itself (e.g. listening to Similar Artists via YouTube)

### ISSUE THREAD

**Issue by blackenedstar** [web-scrobbler/web-scrobbler#3204]
I'm not sure if this feature is tied to YouTube scrobbling, or Last.fm in particular.

I don't see Last.fm listed among the sites supported, so perhaps this is the issue.

Request: I'd love to be able to listen to Similar Artists "radio" on Last.fm, which uses either Spotify (didn't try), or YouTube (this is what I'm using). Here is an example link, where one can click on "Play All", which brings up a YouTube player in a separate container:

https://www.last.fm/music/Depeche+Mode/+similar

However, the web scrobbler doesn't recognize it as YouTube (which should already be supported) and is greyed out.

Thank you,

**Comment by roobscoob** [comment]
IIRC listening directly in last.fm autoscrobbles

**Comment by yayuyokitano** [comment]
Last.fm should be scrobbling this all on its own, if web scrobbler added support it would cause double scrobbling.
If you have any issue with scrobbling in lastfm please get in touch with the [lastfm support forum](https://support.last.fm/)
