### ISSUE TITLE
Add support for scrobbling from https://fm.douban.com/.

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#3209]

**Comment by yayuyokitano** [comment]
Looks like the existing douban.fm connector works fine from initial look, and theres just need for a pattern update to connectors.json. Should be a simple PR, though I can't make one right now.
For the time being, while the change is being globally implemented, you can make it work on your end by adding `*://fm.douban.com/` to the list of patterns for Douban.FM connector, as described [here](https://github.com/web-scrobbler/web-scrobbler/wiki/Custom-URL-patterns)
