### ISSUE TITLE
Favorites not saved on Listenbrainz

### ISSUE THREAD

**Issue by heyarne** [web-scrobbler/web-scrobbler#3212]
**Describe the bug**

Likes are not saved to Listenbrainz. I'm not sure if this is new, but I think I can recall this having worked in the past.

**How to reproduce**

1. Login to Listenbrainz
3. Listen to any song on a platform supported by this addon
4. Open the addon flyover menu, giving you the track details
5. Press ❤️

**Expected behavior**

The track should be loved / favorited on any platform that I logged in to and that supports this.

**Environment (please complete the following information)**
-   OS: Linux
-   Browser: Firefox
-   Extension version: 2.57.2

**Comment by heyarne** [comment]
@MonkeyDo That's fantastic!

**Comment by amCap1712** [comment]
Hey all!

I have examples to ListenBrainz documentation on how to add love/hate feedback if the player does not have MBIDs.
Please see the Lookup MBIDs and Love/hate feedback sections at https://listenbrainz.readthedocs.io/en/latest/users/api-usage.html#lookup-mbids

**Comment by inverse** [comment]
This feature is still valid - Happy to have someone implement :+1:

**Comment by heyarne** [comment]
> This feature is still valid - Happy to have someone implement +1

Just did that! :) See #3369
