### ISSUE TITLE
I can't scrobble from youtube :( windows 10

### ISSUE THREAD

**Issue by stereocode99** [web-scrobbler/web-scrobbler#3213]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by yayuyokitano** [comment]
Hello!
Your web scrobbler icon (has text "as" on it), what does it look like when you try to play a YouTube video? Red, yellow, or gray? What text pops up when you click it?

**Comment by stereocode99** [comment]
Red. The text says "Play some music to start
Is it already playing?"

**Comment by yayuyokitano** [comment]
> Red. The text says "Play some music to start Is it already playing?"

In the extension settings, do you have "scrobble music category" and/or "scrobble entertainment category" activated?
