### ISSUE TITLE
NOT SCROBBLING IN YOUTUBE :(

### ISSUE THREAD

**Issue by rdew2** [web-scrobbler/web-scrobbler#3217]
I have a few days with this problem, some videos works but mostly all doesnt get srobbled :(

OS:WIN10 / CHROME

![screenshot](https://user-images.githubusercontent.com/103342965/162597466-10318af0-4b14-43e5-b9dd-d3dcac6dcf16.JPG)

**Comment by yayuyokitano** [comment]
in the extension settings, do you have "scrobble music category" or "scrobble entertainment category" activated?

**Comment by rdew2** [comment]
yes, i have the 2 ones activated :(

**Comment by yayuyokitano** [comment]
> yes, i have the 2 ones activated :(

Then the most likely thing to be happening is that the videos are incorrectly not marked as music or entertainment.
You can live with that or you can disable both of the two options to allow web scrobbler to try to scrobble all youtube videos.

Unfortunately there is currently no single video override option #1769 

Please let me know if the issue still occurs without the two boxes checked.
