### ISSUE TITLE
Relisten.net tracks appear in Edge extension not on site

### ISSUE THREAD

**Issue by planetneutral** [web-scrobbler/web-scrobbler#3218]
I recently installed the Edge extension in order to be able to scrobble from Relisten.net. The extension appears to be working like a champ. It recognizes songs and says it is scrobbling them. But 12 hours later, after 20 or so tracks like that, none of them have appeared on the last.fm site as scrobbled tracks.

I am running the current build of Edge Version 100.0.1185.36 (Official build) (64-bit) on Win10 Home 21H2 19044.1586.

**Comment by yayuyokitano** [comment]
Cannot reproduce on my end.
Are you still having the issue? If so, what does the web scrobbler icon look like throughout the scrobbling process?
When you start the song you get a green icon with a musical note, right?
Does the icon turn yellow at some point through the song? Does the music note icon turn into a checkmark at some point?
Additionally, can you give an example of a song this happened to you with, in case this is an issue only affecting some songs.

**Comment by planetneutral** [comment]
After a full reboot, I was able to get songs to scrobble. The extension
looks exactly the same as when it wasn't scrobbling in that first session,
but the songs show up now. The songs that were being detected in the first
session never showed up on last.fm. But I am not having an ongoing issue.
Thanks for following up.

-Greg
