### ISSUE TITLE
Nothing happens when I click on Last.fm "Sign in"

### ISSUE THREAD

**Issue by elainma** [web-scrobbler/web-scrobbler#3220]
![image](https://user-images.githubusercontent.com/66527205/163059826-9cd40a3e-2fb2-484e-bd6e-75e68db2f450.png)

This bug appeared in about 1st-2nd of April. No reaction when I click on Last.fm's "Sign in" in plugin settings. But with Libre.fm, ListenBrainz everything works fine. Also, the sign in button under Maloja just opens a new tab.

I've tried to reinstall the plugin.

* OS: Windows 10
* Browser: Opera 85.0.4341.60

**Comment by inverse** [comment]
unable to reproduce the issue on Firefox or Chrome.

Is there anything in the JS console of the options page?

**Comment by elainma** [comment]
![image](https://user-images.githubusercontent.com/66527205/163715554-8f28cb1c-bfe0-4b1a-a38c-e74b4b2b02d6.png)
Yep, this. But no errors or warnings when I click on last fm sign in.

**Comment by inverse** [comment]
Interesting - nothing obvious comes to mind. The logic to do the authentication is the same for libre and last.fm so I would suspect them both to fail in such case.

**Comment by yayuyokitano** [comment]
Unable to reproduce in Edge/Chrome/Opera, however I am on macos currently. I can try again on my windows computer later
Able to reproduce the Maloja thing, but I assume this is intended and is just lack of an error message when Maloja is not running

**Comment by elainma** [comment]
Very interesting, VPN helped. Sorry for disturb you guys.

**Comment by inverse** [comment]
> Very interesting, VPN helped. Sorry for disturb you guys.

We're here to help - no need to apologise :)
