### ISSUE TITLE
Dash Radio

### ISSUE THREAD

**Issue by Jonahrf** [web-scrobbler/web-scrobbler#3227]
The connector on dash radio needs to be updated as the scrobbler isn’t scrobbling from the site anymore

**Comment by Drew-Daniels** [comment]
I've been looking into this one and I've found that the HTML element attributes change depending on the size of the viewport - likely causing the issue you're seeing?

### Large Viewport:
![image](https://user-images.githubusercontent.com/62859552/173922291-fdbde4af-8e1b-4279-a358-00317ddba0ce.png)

### Small Viewport:
![image](https://user-images.githubusercontent.com/62859552/173922369-a682d911-cabf-4569-ab76-31c0c07a6fd7.png)

You can see that the span id and class for the song title disappears in the smaller viewport but do appear when viewing the element in a larger viewport. It appears that the breakpoint is at ~1450px width.

I should also mention that it appears that the children themselves of the `#music-dataview-container` also change from direct children `span`s with ids of `title-text` and `artist-text` resp. to nested `spans` inside of `.marquee-container > marquee[1 or 2]`.

I would be interested to see if anyone can help with providing clarification on if it is possible to conditionally use certain selectors depending on the size of the viewport.

**Comment by Drew-Daniels** [comment]
https://github.com/web-scrobbler/web-scrobbler/pull/3283
