### ISSUE TITLE
Migrate to V3 manifest

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#3228]
We need to migrate to V3 manifest to avoid issues with Chrome.

See: https://developer.chrome.com/blog/mv2-transition/

We have until 2023 to act.

**Comment by inverse** [comment]
@alexesprit  @yayuyokitano looks like we might need to migrate to the V3 setup before then. As the background workers section only takes a single script.

See: https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#manifest

**Comment by yayuyokitano** [comment]
Working on a mini side project in yayuyokitano/Eggs-Enhancement-Suite
Getting a feel for manifest V3 and modern extension compilation

**Comment by inverse** [comment]
Not stale

**Comment by inverse** [comment]
Valid
