### ISSUE TITLE
YouTube don't work.

### ISSUE THREAD

**Issue by The-World-Ender** [web-scrobbler/web-scrobbler#3229]
YouTube isn't tracking my scrobbles from my new computer. This feature works just fine on my old computer and I'm not sure what the hold up is. Can you please fix the issue?

**Comment by yayuyokitano** [comment]
When you try to play a song on youtube, what does the extention icon look like?

**Comment by lucienimmink** [comment]
Gray icon. YouTube isn't working anymore

**Comment by lucienimmink** [comment]
Ticked the boxes, now it's red: still no scrobbling

**Comment by lucienimmink** [comment]
Then I refreshed the browser and it switched to green; scrobbling now works again...
Thx for being my rubber duck
