### ISSUE TITLE
YouTube Music wrong artist selector

### ISSUE THREAD

**Issue by erikKeresztes** [web-scrobbler/web-scrobbler#3242]
When manually trying the 3 artist selectors from https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/youtube-music.js, none of them work. I have come up with another selector that works, `.subtitle.style-scope.ytmusic-player-bar > yt-formatted-string`, although I'm not sure if it's ideal.

![image](https://user-images.githubusercontent.com/58667141/166302377-3209952d-9707-4f84-8d48-ccb5d2942c9b.png)

**Comment by jaccarmac** [comment]
I'm unable to duplicate the issue on the video here: https://music.youtube.com/watch?v=SJ9arRuuQp8. Can you link the track you're having trouble with?

**Comment by erikKeresztes** [comment]
Right, it does work now, but I keep running into this issue when sometimes only the title is being used for scrobbling and it can't find the track on last.fm. Refreshing fixes the issue though. I have found a way to reproduce this:
1. Open music.youtube.com directly in a new tab
2. Find a playlist in the main page
3. Click the play button on the cover

I am using Librewolf though which is a privacy oriented fork of Firefox, maybe it has something to do with the issue but I doubt it

**Comment by jaccarmac** [comment]
Thanks. I was unable to duplicate the issue in a small number of tries, but those details might point us in the right direction.

> I am using Librewolf though which is a privacy oriented fork of Firefox, maybe it has something to do with the issue but I doubt it

I doubt it, too, but in the interest of thoroughness: Can you duplicate the issue with no other extensions enabled in your browser?
