### ISSUE TITLE
Lastfm login not working on edge

### ISSUE THREAD

**Issue by Elfanaarg** [web-scrobbler/web-scrobbler#3247]
**Describe the bug**
Using Edge the notification says that it was a service error and i shoud try to login again. i closed my last.fm session but i cant login again, i click the login button and nothing happens, but im able to login to other services (ListenBrainz for example)

**How to reproduce**
1. Go to options page
2. Click on login to last.fm
3. See error

**Expected behavior**
i should be ble to log in last.fm

**Screenshots**
![image](https://user-images.githubusercontent.com/20009261/167121871-6a3417fe-73f0-43fc-a5a4-56d4732a8626.png)
![image](https://user-images.githubusercontent.com/20009261/167121919-913a42fd-f9b8-49b8-8990-4d6f4bbbe387.png)

**Environment (please complete the following information)**
-   OS: Win 11
-   Browser: Edge
-   Extension version: (e.g. v2.50.2)

**Comment by AaronPinto** [comment]
Same issue on Chrome Version 101.0.4951.54, Windows 10, Extension version: 2.62.0

**Comment by lucasorigami** [comment]
I'm having the same issue on Firefox version 100.0, MacOS 12.3.1, Extension version: 2.62.0.

**Comment by AaronPinto** [comment]
I think this could be related [https://twitter.com/lastfmstatus/status/1522522584004317185](https://twitter.com/lastfmstatus/status/1522522584004317185)

**Comment by yayuyokitano** [comment]
Correct, both the API and website are having severe issues today, I highly doubt this is a web scribbler issue.
Please restart your browser and try logging into web scrobbler every now and then, the issue should correct itself in a few hours.
Please let me know if the issue resolves itself, or if it still persists tomorrow.

**Comment by Elfanaarg** [comment]
Its working again
