### ISSUE TITLE
non music Youtube videos scrobbling

### ISSUE THREAD

**Issue by stmv** [web-scrobbler/web-scrobbler#3248]
My scrobb take production from youtube in last fm  (video https://www.youtube.com/watch?v=s2G9KCCQKiI) but this video had no music
![image](https://user-images.githubusercontent.com/66771304/167126293-7be5c863-4087-4f2f-b346-575f7ac19324.png)

**Comment by Aareksio** [comment]
You can restrict scrobbles to "Music" only in settings.
