### ISSUE TITLE
"Hot loading" custom connectors

### ISSUE THREAD

**Issue by leranjun** [web-scrobbler/web-scrobbler#3259]
This is a super useful extension! I'm interested in writing a connector for a private web media player (i.e. I don't think it's necessary to contribute the connector to this repo in the future as it's mainly for myself). However, from the development instructions, it seems like I need to rebuild the extension with my custom connector every time a new version is released…

Is there a way to directly load a connector from within the extension itself, like an "import" function?

Thanks in advance!

**Comment by inverse** [comment]
What do you mean by private media web player? like something hand made and not generally available to the public? 

Aside creating a pull request and getting it into the code base you could maintain your own fork with the changes and periodically pull from us as an upstream and run the extension in an unpacked mode.

**Comment by leranjun** [comment]
> What do you mean by private media web player? like something hand made and not generally available to the public?
> 
> Aside creating a pull request and getting it into the code base you could maintain your own fork with the changes and periodically pull from us as an upstream and run the extension in an unpacked mode.
> 
> We don't have a import feature - I'm not sure what use that would serve as we normally like our users to contribute support for their media players.

Yep, that was what I meant. But right - I completely forgot I might as well just fork it. Thanks a lot for the suggestion!
