### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by imyourkhuyen** [web-scrobbler/web-scrobbler#3262]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by yayuyokitano** [comment]
Hello, could you please detail what the bug is? What are you trying to do, and what is happening instead of what you want to happen?

**Comment by inverse** [comment]
closing due to lacking context
