### ISSUE TITLE
Unable to scrobble on Spotify

### ISSUE THREAD

**Issue by MarcoTgn** [web-scrobbler/web-scrobbler#3266]
The track is recognised by the extension and the song in the site is in the stato of "scrobbling now" but it won't update his status in "scrobbled" on LastFm site afer the condition for being scrobblled is meeting.
If I try to scrobble song on Youtube it works great.
I have this issue only with the website.
It's been a while i have this problem but didn't see anyone mention it. Am I doing something wrong?
I use this extension on Firefox 100.0.2.

**Comment by yayuyokitano** [comment]
Oops, don't know how but I apparently accidentally closed this while going through trying to repro, my bad.
Unable to reproduce on Win11 Edge 101.0.1210.47 and M1 Firefox 100.0 for now.
Could you provide content and background script as described [here](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension)
Please play a song and allow it to play at least 30 seconds/50% (whichever is longer) before copying logs
Also, when the song reaches the mentioned threshold, what does the web scrobbler icon look like? Yellow? Green? Is it a checkmark, lastfm logo, music note?

**Comment by MarcoTgn** [comment]
No problem @yayuyokitano , i'll post the information you required.
The icon when it reaches the mentioned treshold remain green with the music note, it's not changing to checkamark.
It's like the song didn't reach the treshold.

<details>
  <summary>Debug Extension </summary>
 
storage.Options = {
  "forceRecognize": false,
  "scrobblePodcasts": false,
  "useNotifications": false,
  "scrobblePercent": 50,
  "disabledConnectors": "[hidden]",
  "useUnrecognizedSongNotifications": false
} wrapper.js:74:12
storage.Connectors = {
  "Tidal": {
    "useShortTrackNames": false
  },
  "YouTube": {
    "scrobbleMusicOnly": true,
    "scrobbleEntertainmentOnly": true
  }
} wrapper.js:74:12
storage.ConnectorsOverrideOptions = {} wrapper.js:74:12
storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "*********"
} wrapper.js:74:12
storage.LibreFM = {} wrapper.js:74:12
storage.ListenBrainz = {} wrapper.js:74:12
storage.Maloja = {} wrapper.js:74:12
storage.LocalCache = {
  "spotify:track:7qaJfp7zJoJoLxdkVnwgC2": {
    "artist": "Interpol",
    "track": "Fables",
    "album": "The Other Side of Make-Believe",
    "albumArtist": null
  }
} wrapper.js:74:12
storage.Core = {
  "appVersion": "2.62.1"
} wrapper.js:74:12
Bind Last.fm scrobbler scrobble-service.js:69:13
Unable to bind Libre.fm scrobble-service.js:55:14
Unable to bind ListenBrainz scrobble-service.js:55:14
Unable to bind Maloja scrobble-service.js:55:14
Injecting vendor/filter.js inject.js:52:12
Injecting vendor/jquery.min.js inject.js:52:12
Injecting vendor/browser-polyfill.min.js inject.js:52:12
Injecting core/content/util.js inject.js:52:12
Injecting core/content/reactor.js inject.js:52:12
Injecting core/content/connector.js inject.js:52:12
Injecting connectors/spotify.js inject.js:52:12
Error: Script 'moz-extension://f9218a03-ab50-497f-a808-fa0851788a2d/connectors/spotify.js' result is non-structured-clonable data inject.js:57:13
Injecting core/content/starter.js inject.js:52:12
Tab 1: Created controller for Spotify connector util.js:40:10
Tab 1: State from connector doesn't contain enough information about the playing track: {
  "track": null,
  "artist": null,
  "album": null,
  "albumArtist": null,
  "uniqueID": null,
  "duration": null,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": null,
  "isPodcast": false,
  "originUrl": "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg"
} util.js:40:10
Tab 1: New song detected: {
  "track": "United In Grief",
  "artist": "Kendrick Lamar",
  "album": "Mr. Morale & The Big Steppers",
  "albumArtist": null,
  "uniqueID": "spotify:track:05zd5Nv0e02ZqrlC8A2cwx",
  "duration": -255,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://i.scdn.co/image/ab67616d00001e02f30764d5fa1e439ad6a7742f",
  "isPodcast": false,
  "originUrl": "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg"
} util.js:40:10
Send "get info" request: 1 scrobble-service.js:97:12
Last.fm: track.getinfo response:
{
  "track": {
    "name": "United In Grief",
    "url": "https://www.last.fm/music/Kendrick+Lamar/_/United+In+Grief",
    "duration": "255000",
    "streamable": {
      "#text": "0",
      "fulltrack": "0"
    },
    "listeners": "356679",
    "playcount": "1239455",
    "artist": {
      "name": "Kendrick Lamar",
      "mbid": "381086ea-f511-4aba-bdf9-71c753dc5077",
      "url": "https://www.last.fm/music/Kendrick+Lamar"
    },
    "album": {
      "artist": "Kendrick Lamar",
      "title": "Mr. Morale & the Big Steppers",
      "url": "https://www.last.fm/music/Kendrick+Lamar/Mr.+Morale+&+the+Big+Steppers",
      "image": [
        {
          "#text": "https://lastfm.freetls.fastly.net/i/u/34s/98050f67524ffee7af6edd314b767ac4.png",
          "size": "small"
        },
        {
          "#text": "https://lastfm.freetls.fastly.net/i/u/64s/98050f67524ffee7af6edd314b767ac4.png",
          "size": "medium"
        },
        {
          "#text": "https://lastfm.freetls.fastly.net/i/u/174s/98050f67524ffee7af6edd314b767ac4.png",
          "size": "large"
        },
        {
          "#text": "https://lastfm.freetls.fastly.net/i/u/300x300/98050f67524ffee7af6edd314b767ac4.png",
          "size": "extralarge"
        }
      ]
    },
    "userplaycount": "6",
    "userloved": "0",
    "toptags": {
      "tag": [
        {
          "name": "jazz rap",
          "url": "https://www.last.fm/tag/jazz+rap"
        },
        {
          "name": "Conscious Hip Hop",
          "url": "https://www.last.fm/tag/Conscious+Hip+Hop"
        },
        {
          "name": "rap",
          "url": "https://www.last.fm/tag/rap"
        },
        {
          "name": "experimental hip hop",
          "url": "https://www.last.fm/tag/experimental+hip+hop"
        },
        {
          "name": "jazzstep",
          "url": "https://www.last.fm/tag/jazzstep"
        }
      ]
    }
  }
} util.js:40:10
Using local/parsed artwork coverartarchive.js:10:12
Tab 1: Song finished processing: {
  "parsed": {
    "track": "United In Grief",
    "artist": "Kendrick Lamar",
    "album": "Mr. Morale & The Big Steppers",
    "albumArtist": null,
    "uniqueID": "spotify:track:05zd5Nv0e02ZqrlC8A2cwx",
    "duration": -255,
    "currentTime": null,
    "isPlaying": true,
    "trackArt": "https://i.scdn.co/image/ab67616d00001e02f30764d5fa1e439ad6a7742f",
    "isPodcast": false,
    "originUrl": "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg"
  },
  "processed": {
    "track": "United In Grief",
    "album": null,
    "artist": "Kendrick Lamar",
    "albumArtist": null,
    "duration": 255
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  },
  "metadata": {
    "userloved": false,
    "startTimestamp": 1653215212,
    "label": "Spotify",
    "trackArtUrl": "https://lastfm.freetls.fastly.net/i/u/300x300/98050f67524ffee7af6edd314b767ac4.png",
    "artistUrl": "https://www.last.fm/music/Kendrick+Lamar",
    "trackUrl": "https://www.last.fm/music/Kendrick+Lamar/_/United+In+Grief",
    "albumUrl": "https://www.last.fm/music/Kendrick+Lamar/Mr.+Morale+&+the+Big+Steppers",
    "userPlayCount": 6
  },
  "connectorLabel": "Spotify"
} util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Send "now playing" request: 1 scrobble-service.js:113:12
Last.fm: track.updatenowplaying response:
{
  "nowplaying": {
    "artist": {
      "corrected": "0",
      "#text": "Kendrick Lamar"
    },
    "track": {
      "corrected": "0",
      "#text": "United In Grief"
    },
    "ignoredMessage": {
      "code": "0",
      "#text": ""
    },
    "albumArtist": {
      "corrected": "0",
      "#text": ""
    },
    "album": {
      "corrected": "0",
      "#text": "Mr. Morale & The Big Steppers"
    }
  }
} util.js:40:10
Tab 1: Song set as now playing util.js:40:10
Tab 1: Update duration: -254 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -253 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -252 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -251 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -250 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -249 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -248 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -247 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -246 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -245 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -244 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -243 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -242 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -241 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -240 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -239 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -238 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -237 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -236 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -235 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -234 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -233 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -232 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -231 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -230 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -229 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -228 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -227 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -226 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -225 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -224 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -223 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -222 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -221 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -220 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -219 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -218 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -217 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -216 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -215 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -214 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -213 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -212 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -211 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -210 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -209 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -208 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -207 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -206 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -205 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -204 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -203 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -202 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -201 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -200 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -199 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -198 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -197 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -196 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -195 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -194 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -193 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -192 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -191 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -190 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -189 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -188 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -187 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -186 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -185 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -184 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -183 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -182 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -181 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -180 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -179 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -178 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -177 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -176 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -175 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -174 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -173 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -172 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -171 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -170 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -169 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -168 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -167 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -166 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -165 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -164 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -163 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -162 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -161 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -160 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -159 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -158 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -157 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -156 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -155 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -154 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -153 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -152 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -151 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -150 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -149 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -148 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -147 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -146 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -145 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -144 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -143 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -142 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -141 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -140 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -139 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -138 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -137 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -136 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -135 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -134 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -133 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -132 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -131 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -130 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -129 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -128 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -127 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -126 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -125 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -124 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -123 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -122 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -121 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -120 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -119 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -118 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -117 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -116 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -115 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -114 util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
Tab 1: Update duration: -113 util.js:40:10
Tab 1: isPlaying state changed to false util.js:40:10
Tab 1: The song is too short to scrobble util.js:40:10
</details>

<details>
  <summary>Debug Content </summary>

extension:33:9
Caricamento non riuscito per lo <script> con sorgente “https://www.googleoptimize.com/optimize.js?id=GTM-W53X654”. 2YZyLoL8N0Wb9xBt1NhZWg:3:1
Bloccata richiesta multiorigine (cross-origin): il criterio di corrispondenza dell’origine non consente la lettura della risorsa remota da https://sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7. Motivo: richiesta CORS non riuscita. Codice di stato: (null).

Content Security Policy: Ignorato “'unsafe-inline'” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “https:” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “http:” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “'unsafe-inline'” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “https:” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “http:” in script-src: è stato specificato “strict-dynamic”
InstallTrigger è deprecato e verrà rimosso in futuro. sandbox eval code:494:20
Content Security Policy: Ignorato “'unsafe-inline'” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “https:” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “http:” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “'unsafe-inline'” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “https:” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Ignorato “http:” in script-src: è stato specificato “strict-dynamic”
Content Security Policy: Il caricamento di una risorsa su inline è stato bloccato dalle impostazioni della pagina (“script-src”). moz-extension:33:9
Web Scrobbler: Setting up observer util.js:541:10
Web Scrobbler: Used '.Root__now-playing-bar' to watch changes. util.js:541:10
Bloccata richiesta multiorigine (cross-origin): il criterio di corrispondenza dell’origine non consente la lettura della risorsa remota da https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location. Motivo: richiesta CORS non riuscita. Codice di stato: (null).

Content Security Policy: Il caricamento di una risorsa su inline è stato bloccato dalle impostazioni della pagina (“script-src”). moz-extension:33:9
Error: Promised response from onMessage listener went out of scope 15 background.js:842:170
Il cookie “sp_consent” verrà presto rifiutato in quanto l’attributo “SameSite” è impostato a “None” o un valore non valido, senza l’attributo “secure”. Per ulteriori informazioni sull’attributo “SameSite”, consultare https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite vendor~web-player.30aa9380.js:1:2561679
Content Security Policy: Il caricamento di una risorsa su inline è stato bloccato dalle impostazioni della pagina (“script-src”). moz-extension:33:9
Web Scrobbler: isPlaying state changed to false util.js:541:10
Web Scrobbler: {
  "track": "Fables",
  "artist": "Interpol",
  "album": "Fables",
  "albumArtist": null,
  "uniqueID": "spotify:track:7qaJfp7zJoJoLxdkVnwgC2",
  "duration": -71,
  "currentTime": 202,
  "isPlaying": false,
  "trackArt": "https://i.scdn.co/image/ab67616d00004851d90758410a1b514d3373dbca",
  "isPodcast": false,
  "originUrl": "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg"
} util.js:541:10
Error: Promised response from onMessage listener went out of scope 2 background.js:842:170
La risorsa con indirizzo “https://open.scdn.co/cdn/fonts/CircularSpUIv3T-Light.afd9ab26.woff2”, precaricata con “link preload”, non è stata utilizzata entro un intervallo di alcuni secondi. Assicurarsi che tutti gli attributi del tag preload siano impostati correttamente. 2YZyLoL8N0Wb9xBt1NhZWg
Questo sito utilizza un effetto di posizionamento “scroll-linked” che potrebbe non funzionare correttamente in combinazione con il panning asincrono. Consultare https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html per ulteriori dettagli e partecipare alla discussione su strumenti e caratteristiche. 2YZyLoL8N0Wb9xBt1NhZWg
Web Scrobbler: isPlaying state changed to true util.js:541:10
Web Scrobbler: {
  "track": "United In Grief",
  "artist": "Kendrick Lamar",
  "album": "Mr. Morale & The Big Steppers",
  "albumArtist": null,
  "uniqueID": "spotify:track:05zd5Nv0e02ZqrlC8A2cwx",
  "duration": -255,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://i.scdn.co/image/ab67616d00001e02f30764d5fa1e439ad6a7742f",
  "isPodcast": false,
  "originUrl": "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg"
} util.js:541:10
Error: Promised response from onMessage listener went out of scope 10 background.js:842:170
Web Scrobbler: isPlaying state changed to false util.js:541:10
Error: Promised response from onMessage listener went out of scope 2 background.js:842:170 
</details>

Let me know if something is missing or you don't understand because there are italian word because i'm Italian.
Thanks!

**Comment by yayuyokitano** [comment]
It looks like for some reason the duration is not being parsed correctly, and it is thinking that the song you are playing has a negative duration, (so say, in this instance -255 seconds instead of 255 seconds)
Because of this, the scrobbler is not scrobbling it, due to the lastfm 30 second track minimum.

**Comment by yayuyokitano** [comment]
Looking at the background script, could it be that you have some sort of extension, setting, or script that makes it so that the right side of the player bar in spotify displays the time remaining, instead of the total duration?

**Comment by MarcoTgn** [comment]
OOOOH Now I understand what happened.
It's not a script or extension, it's becuase if you click on total time of the track it's changing into time remaining and that's why the duration was negative.
After switching back the extension working perfect as usual.
Sorry to bother you @yayuyokitano, for that stupid thing.

**Comment by yayuyokitano** [comment]
Gotcha. It might still be worth looking at implementing support for this option regardless on our part, but glad you are able to use extension again!
