### ISSUE TITLE
not staying logged in, missing many scrobbles

### ISSUE THREAD

**Issue by neyel8r** [web-scrobbler/web-scrobbler#3267]
title pretty much says it... i don't know why i keep getting logged out of the extension, but it is very frustrating to have to reconnect almost every day

**Comment by yayuyokitano** [comment]
This sounds abnormal. Being displayed as being logged out could happen if web scrobbler is unable to reach lastfm API, but it shouldn't happen this often.
Is it possible that something is erasing your browser's localstorage? For instance, do you maybe get reliably get logged out every time you restart your browser, or restart your computer, or at some specific timing? This would log you out of web scrobbler if it happens.
Also, just to be sure its not something with the interaction with lastfm, the next time this happens, could you provide background script log as described [here?](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension)
