### ISSUE TITLE
Cant login to lastfm

### ISSUE THREAD

**Issue by kz-hny** [web-scrobbler/web-scrobbler#3268]
Hi, there seems to be a service issue (on my end?) suddenly. Songs aren't scrobbling, and it says I need to reaunthenticate... but after logging out I can't log back in to lastfm. First time experiencing this, never had any problems before

**Comment by yayuyokitano** [comment]
Last.FM API is currently globally and completely down. Every request is returning an error 8.
There is nothing web scrobbler can do about this except wait, unfortunately.
Keep in mind that as web scrobbler does not currently cache rejected scrobbles, any scrobbles done during this downtime will be lost unless you write them down and scrobble them with something like openscrobbler later.
Leaving this issue open until I see the API working again

**Comment by kz-hny** [comment]
Oh I see. I've never experienced this before, so I wasn't sure what was going on. If that's the case, thank you so much for the information then. Guess we'll just have to wait

**Comment by yayuyokitano** [comment]
Yeah, I've seen random API instability before but nothing quite like this, I'm surprised too.

Going to reopen this for the time being even though it's not a web scrobbler issue, just so people see this immediately when they go to web scrobbler issue page.

**Comment by yayuyokitano** [comment]
Ok the API seems to be back up now, closing the issue.
Thank you for your patience.

**Comment by kz-hny** [comment]
Oh lol, that was fast. Was expecting we'd have to check back tomorrow.
