### ISSUE TITLE
Songs aren't recognized.

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#3272]
**Describe the bug**
Site not supported/song not recognized.

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=X0DeIqJm4vM
2. See error

**Expected behavior**
At least parse and fill the fields to manually scrobble it.

**Screenshots**
![image](https://user-images.githubusercontent.com/9662163/171963340-623c5a5b-0baf-4ee3-909e-8eb99e767c54.png)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.62.1

**Additional context**
Scrobbling everything fills Last.fm with garbage.

**Comment by yayuyokitano** [comment]
Hello, the song is categorized as comedy, so if you are restricting your web scrobbler to only scrobbling music and/or entertainment, this will not scrobble, please see #1769 
Can you verify if the issue is occurring with both "only scrobble from music category" and "only scrobbler from entertainment category" boxes unchecked?

**Comment by CTimmerman** [comment]
Additional context: Scrobbling everything fills Last.fm with garbage.

I'd spend more time trying to remove said garbage from Last.fm, so now use https://chrome.google.com/webstore/detail/lastfm-manual-scrobbler/bononpbmihomjbnfaaapbbhfkifjcekn to add comedic songs manually.

**Comment by CTimmerman** [comment]
And whatever this is (not) detected as: https://www.youtube.com/watch?v=kLWSQRNnGY8
