### ISSUE TITLE
Scrobbling from Napster web player stopped working

### ISSUE THREAD

**Issue by Hekemon** [web-scrobbler/web-scrobbler#3276]
Scrobbling from Napster web player stopped working today when the site updated. Any way to make it work again?

**Comment by mindianajones** [comment]
Not sure if I can comment here to reopen this request or if I need to post a new one. Trying this first. I installed this extension specifically to scrobble from Napster, but it's not working on that site. Any chance this can be fixed? Thanks for considering!
