### ISSUE TITLE
Add support for https://beta.music.apple.com.

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#3277]
**Provide information about website**
It's the Apple Music Web Player's beta website.

**Comment by shaig19** [comment]
yes!!!!!

**Comment by ethmac007** [comment]
Yes! Apple Music Beta is much better.

**Comment by hans-juergen** [comment]
I guess the new beta web player by Apple Music is still not supported, although the icon in the browser (Edge in my case) is red? I have justed tested both the normal vs. the beta version, and the former still works, but the latter does not. The playbar on top of the page looks the same, by the way.

Older related issues: #3199 and #2512

**Comment by ericcirone** [comment]
Would like this as well!

**Comment by anatsymbol** [comment]
Yes please

**Comment by inverse** [comment]
@hans-juergen is this still valid?

**Comment by hans-juergen** [comment]
As far as I can tell, the beta version of the Apple Music web player still does not scrobble, although the icon is still red. When I switch back in the player to the normal version, the same page can be scrobbled. The difference is only in the URL using "beta" or not.

**Comment by Nirzak** [comment]
> 

No, the diffference is actually in the apple's method to describe song's metadata information. the beta version was an updated version that uses JS to dump metadata information instead of sourcing them in the HTML content. That's why it was not working. Now the beta website has become the general website and makes that one also broken.

**Comment by hans-juergen** [comment]
Right, I just tested music.apple.com again, and it does not scrobble anymore. Thanks for the info, also for the link to the new issue. Guess I'll have to check the Last.fm support forum for new related user reports.

**Comment by Nirzak** [comment]
Finally with a fix. Thanks a lot!
