### ISSUE TITLE
Crashes whenever I play anything (that I set to be scrobbleable)

### ISSUE THREAD

**Issue by holyshithelp** [web-scrobbler/web-scrobbler#3285]
I have it set to scrobble youtube and bandcamp tracks, listening to something from either of these crashes my browser instantly. I'm using opera and have tried reinstalling the extension and giving it every privilege several times to no avail. I simply cannot scrobble music on my browser anymore.

**Comment by yayuyokitano** [comment]
Cannot reproduce this on my end off the bat.
Could you test and provide these details:

What is your operating system and version?
What is your version of Opera?
Does the issue still occur if you disable every other extension in your browser?
When does the issue occur? As soon as the page loads? As soon as you hit play? Or some other timing?

**Comment by holyshithelp** [comment]
Edition	Windows 10 Pro
Version	20H2
Installed on	‎16/‎06/‎2022
OS build	19042.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

opera version Version:88.0.4412.40

oddly enough disabling every single other extension seems to make it work, but i only had adblock plus and the default opera adblock

it happens a few seconds after playing, and it just restarts the browser to the home page with all tabs closed rather than outright crashing. probably should have mentioned

**Comment by yayuyokitano** [comment]
Unable to reproduce on same version of opera with adblock plus and default opera adblock enabled, however I used win11, as I do not currently have access to a win10 machine.

A couple more questions to try to figure out what could be going on:

Does the issue persist if you turn off now playing notifications in the extension settings?
What version of adblock plus are you using?
Does the issue persist with abp enabled, but opera adblock disabled?
Does the issue persist if abp is replaced by another adblocker like ublock?
