### ISSUE TITLE
Strip unneeded data from submitted YouTube links

### ISSUE THREAD

**Issue by staticssleever668** [web-scrobbler/web-scrobbler#3290]
**Is your feature request related to a problem? Please describe.**
If a track you listen to is in a playlist, e.g. the link is like so: https://youtube.com/watch?v=xRPyeNt5Wdg&list=OLAK5uy_lyXtkHz-379v_Xf59_5sXPzfkNfnbxTSw, the link in the submitted listen contains the playlist link.
It may make sense if the playlist is a compilation of tracks in the album, but I think this is generally privacy-invading, especially if the playlist is link-access-only. 

**Describe the solution you'd like**
The submitted originUrl should only contain the video ID and it only, no playlist link or anything else.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by inverse** [comment]
This will also help with listenbrainz :+1:
