### ISSUE TITLE
playlist-randomizer selectors need updating

### ISSUE THREAD

**Issue by Californ1a** [web-scrobbler/web-scrobbler#3293]
**Describe the bug**
Some time ago, the dev of playlist-randomizer pushed an update that breaks some of the selectors on this connector.

The simple one is that `.MuiAvatar-circle` changed to `.MuiAvatar-circular` for the trackArtSelector, but the other issue is that the channel name is now getting appended to the track name:

**Screenshots**
In the playlist:
![](https://i.imgur.com/r4ynlZy.png)

In web scrobbler:
![](https://i.imgur.com/GoH3XED.png)
This one should be track "Cosmo Funk" with artist "Snail's House"

And in cases where the artist name isn't in the video title, it's using the channel name for the track name:
![](https://i.imgur.com/dYXpMFC.png)
![](https://i.imgur.com/S28DwEu.png)
This one should be track "Vision" with artist "Pop Up!"

And without any dashes in either the title or channel name, it puts both the title and channel name for both the track and artist:
![](https://i.imgur.com/wl7x9Hf.png)
![](https://i.imgur.com/7L0Lhgc.png)
This one should be track "POGO Live 18.0.1.19" with artist "Pogo"

**Comment by yayuyokitano** [comment]
Thank you for raising this issue!
I see you've done quite a bit of research into the details of the issue, are you planning on self-assigning this, or would you like for someone else to handle the implementation?

**Comment by Californ1a** [comment]
I would have just sent a PR since the first one is a simple class rename, but I don't know how to fix the second issue.

**Comment by yayuyokitano** [comment]
Not in position to test this properly rn, but replacing Util.getTextFromSelectors with a call to something along the lines of the following function should work I think
`const getYtVideoTitleFromSelector = (selector) => document.querySelector(selector).firstChild.nodeValue;`

**Comment by Enferlain** [comment]
Did the fix work? I'm trying the website now and it seems inactive 

![image](https://user-images.githubusercontent.com/15861396/178124863-518a11a7-9c33-4e81-9d7e-aba3e7e4bd3a.png)

**Comment by Californ1a** [comment]
Yes, it is working in PR #3295. It just hasn't been merged yet.
