### ISSUE TITLE
Changes in ListenBrainz submission format

### ISSUE THREAD

**Issue by MonkeyDo** [web-scrobbler/web-scrobbler#3296]
The ListenBrainz team has recently reviewed and consolidated feedback about the listen submission format, and come up with a few conclusions. To follow the process, see https://github.com/metabrainz/listenbrainz-server/pull/1607 and https://github.com/metabrainz/listenbrainz-server/pull/1832

WebScrobbler was one of the use cases we looked at specifically, and you will find a submission example [here](https://listenbrainz.readthedocs.io/en/latest/users/json.html#listening-to-a-recording-from-bandcamp-and-submitting-with-the-browser-extension-webscrobbler)

In short, there are a few additional fields in `track_metadata.additional_info`:

* `music_service`: This is the canonical URL of the music service, for example  "bandcamp.com", "spotify.com", etc.
    > The music_service field should be a domain name rather than a textual description or URL. This allows us to refer unambiguously to a service without worrying about capitalization or full/short names (such as the difference between “Internet Archive”, “The Internet Archive” or “Archive”). If we use this data on ListenBrainz, we will perform a mapping from the domain name to a canonical name. 
    See the note in the [payload docs](https://listenbrainz.readthedocs.io/en/latest/users/json.html#payload-json-details) for a list of canonical music service urls
* `music_service_name`: A fallback field in case you do not know the canonical domain name of the music service: for example "Bandcamp", "Spotify"
* `submission_client`: The name of the software submitting the listen to ListenBrainz, i.e. "WebScrobbler"
* `submission_client_version`: Free text field that can help debug some issues with specific versions of submitters:  "v2.63.0"
* `origin_url`: This is already implemented, but to clarify we expect a URL to the place where the track or album is available, for example "https://greencookierecords.bandcamp.com/track/shake", "https://open.spotify.com/album/4u3DR7kACs2BSegDxoq3GL"
This is more reliable than music-service-specific fields such as `spotify_id`

As with anything related to ListenBrainz I am happy to help answer questions, open or review PRs.

**Comment by inverse** [comment]
I started implementing the changes in https://github.com/web-scrobbler/web-scrobbler/pull/3297 however Struggling to resolve `music_service` What would you suggest for this? 


Right now I am using the origin URL and turning it into the hostname but for example this would turn `https://hypnus.bandcamp.com/album/deep-blue-volume-3` into `hypnus.bandcamp.com` which I suspect is not what you are after?

**Comment by MonkeyDo** [comment]
About my 1. above: perhaps the canonical domain can be added to https://github.com/web-scrobbler/web-scrobbler/blob/master/src/core/connectors.js instead, in the same way each connector has a label?

**Comment by inverse** [comment]
Yeah I think It's going to be problematic as some of the connectors map to multiple sites and also some operate on local domains.

It sounds like using label could be a solid bet - the PR is ready for review :+1:
