### ISSUE TITLE
Spotify edit format changed in 2.64.1

### ISSUE THREAD

**Issue by yayuyokitano** [web-scrobbler/web-scrobbler#3298]
The format for keys for spotify edits was changed as a side effect of #3278 
It is now being stored as url, rather than spotify ID.
This means no old edits for spotify tracks are recognized.
Either a migration should be implemented (iirc something like this already exists somewhere in the codebase, right?), or the format used for the keys reverted, ASAP.

**Comment by inverse** [comment]
Ouch :( totally overlooked that one.

We could I'd say migrate back to the URN - right now `getTrackUri` returns a URL which we could add something like `getTrackUrn` that returns the old format and maps it to `getUniqueID`

**Comment by yayuyokitano** [comment]
yep, im thinking the same thing, gonna try and see what i can do rn

**Comment by inverse** [comment]
I drafted https://github.com/web-scrobbler/web-scrobbler/pull/3299 but didn't test it yet
