### ISSUE TITLE
Radiorecord.ru not scrobbled

### ISSUE THREAD

**Issue by Satont** [web-scrobbler/web-scrobbler#3300]
**Describe the bug**
Not scrobbling from radiorecord because of ui changes.

**How to reproduce**
1. Go to https://radiorecord.ru
2. Click on any radio

**Expected behavior**
Should be scrobbled.

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: v2.64.2

**Additional context**

**Comment by enot444** [comment]
still not working

**Comment by d9k** [comment]
@alexesprit, still not working :'(

**Comment by d9k** [comment]
See https://github.com/web-scrobbler/web-scrobbler/blame/master/src/connectors/radiorecord.js
