### ISSUE TITLE
YouTube: "Comedy" category videos are treated differently than those in "Entertainment".

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#3301]
Why is https://www.youtube.com/watch?v=X_DdGRjtwAo scrobbled but not https://www.youtube.com/watch?v=lQlIhraqL7o ?

**Comment by jaccarmac** [comment]
You've pretty much identified the issue in the title: Category matches are done on a simple string basis. The connector checks for either "Music" or "Entertainment", and the Lonely Island video comes back as "Comedy".

I didn't implement and am not very familiar with this feature, so can't speak to solutions (Do we know all the available categories?/Is there some kind of family tree structure we can make out of them?/Is it worth adding another option?/etc.)

**Comment by CTimmerman** [comment]
Related to issue #3272. Same with https://www.youtube.com/watch?v=nUqPOsgu0uo scrobbling a dang recipe and https://www.youtube.com/watch?v=J-ifjIAoleI not scrobbling a song.

**Comment by jaccarmac** [comment]
As described, you can use the options checked and manually scrobble things outside those categories or leave them unchecked and scrobble garbage. The "garbage" problem is real, but it's a consequence of the way YouTube is organized and there is not a simple way to disambiguate based on only titles. FWIW, I use a separate browser instance for YouTube music listening and YouTube video watching, and only enable the extension in the former. You can also leave the scrobbler disabled for the site and enable it temporarily when listening to music.

**Comment by CTimmerman** [comment]
It's a consequence of this add-on scrobbling garbage instead of music. https://www.last.fm/music/Day+1/_/study+schedule

**Comment by jaccarmac** [comment]
That video is categorized as Entertainment. If you don't want it scrobbled, uncheck the checkbox. Or delete the scrobble. Or disable the extension while you watch it. We can't magically determine that the video isn't music. The chapters are similar in format to the chapters in an album upload.

**Comment by CTimmerman** [comment]
You mean temporarily "Disable the YouTube connector" from the add-on's context menu, assuming you check that for every video before it already scrobbled the intro chapter of some hardware review. I think Comedy is more worthy of scrobbling than Entertainment.

**Comment by jaccarmac** [comment]
> You mean temporarily "Disable the YouTube connector" from the add-on's context menu, assuming you check that for every video before it already scrobbled the intro chapter of some hardware review.

I can't tell you what works best for your use case, but keeping scrobbling disabled on YouTube except when I'm specifically listening to music works for me. If your watching and listening are interleaved and in equal proportion, this extension might not be a great choice for you.

> I think Comedy is more worthy of scrobbling than Entertainment.

Please open an issue to that effect and we can discuss whether it warrants another option.

> You can check whether something is music by checking whether it exists on Last.fm. That should already be done but i guess some people forced recognition for trash.

We do do that. The problem is, indeed, that lots of non-music YouTube videos get scrobbled. That's not a web-scrobbler-specific problem.

**Comment by CTimmerman** [comment]
> The problem is, indeed, that lots of non-music YouTube videos get scrobbled. That's not a web-scrobbler-specific problem.

Except Web Scrobbler is a major contributer to incorrect scrobbles, as i've widely reported here as well.
