### ISSUE TITLE
SiriusXM DJ breaks being scrobbled on certain stations

### ISSUE THREAD

**Issue by pixiekat** [web-scrobbler/web-scrobbler#3319]
I don't know if this is technically a bug report or not since I wasn't sure if anything can be done about it.

When I listen to certain stations - Lithium, Pop Rocks, etc - you'll occasionally get an interlude scrobbled which looks like the following:

`@JuliaCunningham | @SXMPopRocks | 5 minutes ago`

Is there any way to filter these out or have them not scrobble? It's not a big deal but it just irks me while I'm trying to curate my Last.fm. :)

**Comment by inverse** [comment]
It looks like some effort was made to remove these. 

Is what you provided the artist?

If it's the artist we could include `@SXMPopRocks` into the filter to ignore. Right now this filter includes `siriusxmu`

**Comment by pixiekat** [comment]
When it scrobbled it linked to a page like this: https://www.last.fm/music/@radiomadison/_/@sxmlithium (this is another station but it's similar). So, I think the station is the track. 

But after I made this post, it also scrobbled a little advert for the station on Facebook too (That was on the 1st Wave channel)
