### ISSUE TITLE
Hoopla connector is broken

### ISSUE THREAD

**Issue by thomwim** [web-scrobbler/web-scrobbler#3321]
I'm trying to play the album "Chopped & Screwed" by Korn, which I borrowed from Hoopla. I have posted a picture of the track player.

https://www.hoopladigital.com/title/11250844

![image](https://user-images.githubusercontent.com/7088284/183870197-cd9ca7f3-9c3c-4215-9dec-5b8fecb586ee.png)

**Comment by inverse** [comment]
@hornbuckle would you be able to take a look at this issue?

**Comment by hornbuckle** [comment]
@inverse Sure. Looks like they may have updated their player, so I'll take a look and try to get it working again in the next few days.

**Comment by inverse** [comment]
No rush - glad to have some help on this one :pray:

**Comment by inverse** [comment]
Should be shortly available :+1:

**Comment by Amraan-Amjad** [comment]
@hornbuckle @inverse 
Again, it is down 
I was trying to download the audiobook but it showed
![image](https://github.com/web-scrobbler/web-scrobbler/assets/121578485/7a427fe6-e5bb-4b70-bf5b-4c6bdc5caf0e)
Kindly update it

**Comment by hornbuckle** [comment]
@Amraan-Amjad It does not support audiobook scrobbling; only music.

**Comment by Amraan-Amjad** [comment]
> @Amraan-Amjad It does not support audiobook scrobbling; only music.

Could you add it please :)

**Comment by hornbuckle** [comment]
@Amraan-Amjad No, it does not work. I tried it before.
