### ISSUE TITLE
youtube scrobbling no longer working

### ISSUE THREAD

**Issue by JayFlowGT** [web-scrobbler/web-scrobbler#3334]
youtube aswell as youtube music no longer scrobble for me.
things on my side are unchanged from yesterday when it still worked.
soundcloud still works fine.

https://pastebin.com/QDs4hhtq

windows 10
google chrome 
web scrobbler v2.67.1

**Comment by jaccarmac** [comment]
Can't reproduce.

Line 39 of that paste suggests that it's from a video in a non-music category, and I see that the option to only scrobble videos in Music is checked. If you uncheck that option, does the video scrobble?

**Comment by JayFlowGT** [comment]
checked in today again and things seem to be working again.
there seem to be some cases where youtube songs listed under music category do not get recognized as being in the category.

**Comment by jaccarmac** [comment]
We're relying on a rather blunt instrument to pull out category information. There's discussion about something likely-related in #3301. If these issues keep popping up we may need to dive into the guts and sharpen it.
