### ISSUE TITLE
Deezer not working

### ISSUE THREAD

**Issue by kachan64** [web-scrobbler/web-scrobbler#3337]
When I press play on Deezer, web scrobbler doesn't detect it playing until I scroll to the start of the track. Sometimes the track is continuously stays scrobble and doesn't scrobble the next track.

**Comment by hans-juergen** [comment]
I just checked Deezer scrobbling with the extension, for me it still works as usual. But they are currently rolling out gapless playback in their web player since last week, so maybe you already have it and I do not. Not sure if this could be the reason though, as the player layout will not be changed, as far as I know.

**Comment by kachan64** [comment]
Thanks for the response. It might be, I dono. It was working the week before. Thanks anyways 1:52 pm, 22 August 2022, "Hans-Jürgen" ***@***.***>:
I just checked Deezer scrobbling with the extension, for me it still works as usual. But they are currently rolling out gapless playback in their web player since last week, so maybe you already have it and I do not. Not sure if this could be the reason though, as the player layout will not be changed, as far as I know.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by Tscharbo** [comment]
The extension has not worked properly since yesterday! It is red, if I play a song, then I have to stop the song and play it again, only then it turns green, but the song is not transmitted, or a song we skipped and not transmitted, or a song is transmitted twice, although I only heard it once!!!

**Comment by mariomarinato** [comment]
+1 here.  I'm facing the same behavior.

> The extension has not worked properly since yesterday! It is red, if I play a song, then I have to stop the song and play it again, only then it turns green, but the song is not transmitted, or a song we skipped and not transmitted, or a song is transmitted twice, although I only heard it once!!!

**Comment by hans-juergen** [comment]
I think I know what is going on: the first track when starting to scrobble e.g. an album which should be played without gaps will not be shown anymore, not even as "Scrobbling now" in your recent tracks list on your user profile. The second track will then initiate the scrobbling and show the first track as "Scrobbling now", but not the second track. So it is always one track behind for some reason which is the same behaviour you get from the internal Deezer scrobbling option which never shows "Scrobbling now" and only the last track you have scrobbled. Maybe the Web Scrobbler was changed to adapt to that behaviour?

**Comment by derek-gz** [comment]
Same thing happening here.

If I press forward, rewind, forward, rewind after a track starts, I can get it to be scrobbled normally.

That is not convenient at all, though.

**Comment by MatF2F** [comment]
It seems that the probléme isn't only with webscrobbler and deezer. 
On my phone use the lastfm app and I have the same problem with deezer and also bandcamp

**Comment by kachan64** [comment]
Interesting. I use Pano Scrobbler on my phone, so I had no problem.

**Comment by mariomarinato** [comment]
No problems on my Android phone, using either Deezer's Last.fm integration and Last.fm scrobbler itself.
