### ISSUE TITLE
Support for Bandcamp Pro with custom domains

### ISSUE THREAD

**Issue by cenobitedk** [web-scrobbler/web-scrobbler#334]
Some artists have Bandcamp Pro accounts that allows them to use custom domains, see here: http://bandcamp.com/help/custom_domain

e.g. http://disasterpeace.com/album/fez-ost

Currently the scrobbler does not detect and scrobble sites like that. I know that would require a _very_ long list if the sites are only detected based on the url.

As an alternate detection method would it be possible to check for the "og:url" meta tag which holds the complete url _with_ bandcamp.com?

`<meta property="og:url" content="http://disasterpeace.bandcamp.com/album/fez-ost">`

**Comment by galeksandrp** [comment]
Now in chrome stable if extension have access to all sites PageStateMatcher can inject script based on page content.
https://developer.chrome.com/extensions/declarativeContent#type-PageStateMatcher

	// Update the declarative rules on install or upgrade.
	chrome.runtime.onInstalled.addListener(function() {
	  chrome.declarativeContent.onPageChanged.removeRules(undefined, function() {
		chrome.declarativeContent.onPageChanged.addRules([{
		  conditions: [
			// When a page contains a <video> tag...
			new chrome.declarativeContent.PageStateMatcher({
			  css: ["video"]
			})
		  ],
		  // ... inject script.
		  actions: [new chrome.declarativeContent.RequestContentScript({js: ['bower_components/jquery/dist/jquery.min.js', 'script.js']}) ]
		}]);
	  });
	});

**Comment by ValentinDrean** [comment]
As the screenshot suggests, do I need to add each time I listen to labels or artists that have a bandcamp pro account ?

**Comment by inverse** [comment]
@ValentinDrean indeed

**Comment by ValentinDrean** [comment]
goooooooooosh..!
Thanks for your response !
