### ISSUE TITLE
Filtering station IDs so they don't get scrobbled between songs?

### ISSUE THREAD

**Issue by jbwharris** [web-scrobbler/web-scrobbler#3344]
I have been working on a connector for [Indie 102.3](https://indie.cpr.org/) and it does work, the problem is between songs they'll throw a tag in there for the station ID and the current DJ. Now I've been recently using the [WYEP](https://wyep.org/) connector which I see having a similar behaviour, but it doesn't seem to have this problem. And when I look at the code for this connector, there doesn't seem to be anything implicit that filters the output. Is there something within the Web Scrobbler that handles filtering, or am I just missing something here?

**Indie 102.3 page output**
![image](https://user-images.githubusercontent.com/2962327/187498430-ec5e4569-2a48-463f-9393-49ea00364892.png)
**Scrobbled station ID I just deleted**
![image](https://user-images.githubusercontent.com/2962327/187498756-67b264a8-57a8-43e8-bf8f-502517ec02c0.png)

**WYEP station ID output that doesn't get scrobbled**
![image](https://user-images.githubusercontent.com/2962327/187504951-4fd15dce-b313-47c4-a62f-aa4e1a0e9230.png)

**Comment by inverse** [comment]
I don't know why that scrobbler would be working... perhaps it's due to the way it parses out the artist on `.` and if that doesnt match then nothing scrobbles.

For your case you could try something like...

```
Connector.isScrobblingAllowed = () => !document.querySelector('.qtmplayer__artist').textContent.startsWith('With ');
```

To block playback when artist matches `With `

**Comment by jbwharris** [comment]
Thanks for pointing me in the right direction. I need to test it a bit more and see if there might be more conditions that I might need to hedge against, but it seems to be working so far.
