### ISSUE TITLE
Libre.FM "invalid token"

### ISSUE THREAD

**Issue by gwerbin** [web-scrobbler/web-scrobbler#3347]
**Describe the bug**

The Web Scrobbler login state for LibreFM is out of sync with LibreFM itself. I am not logged in, but when I try to log in with LibreFM, that site says "invalid token".

The bad URL is: https://www.libre.fm/api/auth/?api_key=r8i1y91hz71tcx7vyrp9hk1alhqp1898&token=d0665fe4e4e20e9015e382d10303790c

**How to reproduce**

1. Click "log in" for LibreFM *twice*
2. Log in using the first page that opens and close the 2nd without taking action
3. In the settings age, it should still say "log in" under LibreFM, click that again.

**Expected behavior**

Either re-trigger the login flow, or some kind of "no-op" that updates the settings UI to show that we are logged in.

**Screenshots**

* https://files.catbox.moe/wu6q3r.png
* https://files.catbox.moe/uvxvgs.png

**Debug logs**

```
Libre.fm: auth.getsession response:
{
  "error": 14,
  "message": "This token has not yet been authorised"
}

Libre.fm: Failed to trade token for session
```

**Environment (please complete the following information)**

-   OS: MacOS 12.4
-   Browser: Firefox 104.0.1
-   Extension version: 2.69.0

**Additional context**

I am logged in on the Libre.FM side, but I had the same problem when I was logged out.

**Comment by gwerbin** [comment]
I am still having this issue.

**Comment by inverse** [comment]
I'm unable to reproduce - the 3rd  step just auths correctly

**Comment by gwerbin** [comment]
Thanks for looking @inverse . I actually just checked and it seemed like the login information has "settled down". I will re-open if I can reproduce.
