### ISSUE TITLE
Dandelion Radio scrobbling issue

### ISSUE THREAD

**Issue by rg-gapa** [web-scrobbler/web-scrobbler#3355]
**Describe the bug**
After recent addition of Twitter link at [Dandelio Radio player website](http://www.dandelionradio.com/player.htm) Web Scrobbler is broken - it adds "Tell your friends: Twitter" at the end of detected track name.

**How to reproduce**
1. Go to http://www.dandelionradio.com/player.htm
2. Start playing radio
3. Web Scrobbler detects "Song Title  Tell your friends: Twitter" instead of "Song Title"

**Expected behavior**
Properly detecting song title.

**Screenshots**
![image](https://user-images.githubusercontent.com/99292249/189434803-fe87e40c-33a8-46f6-876e-1a07ba98117c.png)
![image](https://user-images.githubusercontent.com/99292249/189434830-9eee977b-06b4-4648-b68e-4e55cfd297d9.png)
![image](https://user-images.githubusercontent.com/99292249/189434840-9c78af44-431a-4d93-8735-74c7801b34d8.png)

**Debug logs**
-

**Environment (please complete the following information)**
-   Windows 11
-   Edge
-   WebScrobbler v2.69.0

**Comment by inverse** [comment]
Will be fixed in the next release
