### ISSUE TITLE
Edge addon out of date in MS site

### ISSUE THREAD

**Issue by jbwharris** [web-scrobbler/web-scrobbler#3357]
I just noticed that the Edge addon is out of date on the Microsoft site. Thought that was worth flagging. 

[MS Addons page](https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc)

I know the newer version of the addon works fine, as I'm using the newer Chrome version in Edge for developing new connectors.

**Comment by rg-gapa** [comment]
> I just noticed that the Edge addon is out of date on the Microsoft site. Thought that was worth flagging.
> 
> [MS Addons page](https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc)
> 
> I know the newer version of the addon works fine, as I'm using the newer Chrome version in Edge for developing new connectors.

Newer version gives you more supported websites to scrobble from. That's why I've switched to Chrome Store version after discovering that version difference.

**Comment by inverse** [comment]
The Edge version was manually uploaded I believe by one of the maintainers. I'm not aware that Microsoft provide a way for us to automate the distribution there. Perhaps they do now but previously that was the issue.

**Comment by inverse** [comment]
Looks like it's supported now https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api

**Comment by hornbuckle** [comment]
Firefox seems to have fallen behind now, as well.

**Comment by inverse** [comment]
That's interesting - wonder why its not working.

CI reported successful - thanks for raising.

**Comment by jbwharris** [comment]
@inverse I wanted to mention the Edge and Firefox latest versions seem to be behind. Not sure if they're related issues, but thought worth flagging.

**Comment by inverse** [comment]
@jbwharris thanks for the update.

- Edge updates are manually pushed - working on a GitHub Action to automate this
- Firefox reported they are delayed in reviewing the extension - I guess with Christmas staff are on vacation

**Comment by inverse** [comment]
Was struggling with JS around the lib I was using and eslint couldnt resolve the module so ported the lib to Python and rewote using that.

- https://github.com/inverse/python-edge-addons-api
- https://github.com/inverse/edge-addon-python
