### ISSUE TITLE
Non-music YouTube video detected as music

### ISSUE THREAD

**Issue by CTimmerman** [web-scrobbler/web-scrobbler#3365]
A while ago I set Web Scrobbler to only scrobble Music from YouTube, but it still scrobbles https://www.youtube.com/watch?v=w8yWXqWQYmU

**Comment by inverse** [comment]
Unfortunately this Video has been tagged as music from the way we resolve the category from the DOM.

```json
"viewCount":"525052","category":"Music","publishDate":"2020-11-24"
```
