### ISSUE TITLE
Not detecting music whilst it is playing on Youtube music

### ISSUE THREAD

**Issue by hsworkss** [web-scrobbler/web-scrobbler#3371]
**Describe the bug**
Extension is not detecting music playing whilst being enabled and on the tab where it is playing

**How to reproduce**
Steps to reproduce the behaviour:
Unsure if it can be reproduced as it has just stopped working

**Expected behaviour**
I expected the plugin to autodetect my music playing as I have used it for the past week and not had this issue before.

**Screenshots**
![image](https://user-images.githubusercontent.com/114172685/191791436-8627c1d1-b834-4763-9aec-41e6f6e21b5b.png)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
Chrome 105.0.5195.127
Windows 10 Home 21H2

**Additional context**

**Comment by hsworkss** [comment]
i think its due to youtube music having a website update, because some small items changed ( icons on the bottom of the screenshot)

**Comment by forsureitsme** [comment]
[My debug logs](https://pastebin.com/raw/PgkjURw3) although irrelevant

The playing icon has indeed changed (as stated by @hsworkss) and the connector is not detecting the playstate correctly.
Previously the path `d` attribute was `M6 19h4V5H6v14zm8-14v14h4V5h-4z` and now it's `M9,19H7V5H9ZM17,5H15V19h2Z`.

**Comment by inverse** [comment]
Publishing a new version with the change - lets see if it fixes it. 

https://github.com/web-scrobbler/web-scrobbler/releases

**Comment by hornbuckle** [comment]
Curiously, this update seems to have broken YT Music scrobbling for me.

**Comment by furquim87** [comment]
> Curiously, this update seems to have broken YT Music scrobbling for me. FWIW I'm still seeing the path d attribute as `M6 19h4V5H6v14zm8-14v14h4V5h-4z` even after refreshing the browser window. Perhaps they're slowly rolling out the change, and it hasn't gone out to all users yet.

Yeah, I had to download the source code for version 2.72.0 and build it in order to get it working on my Microsoft Edge PWA.
