### ISSUE TITLE
YouTube: SponsorBlock popups are detected as artist/track names

### ISSUE THREAD

**Issue by Terrance** [web-scrobbler/web-scrobbler#3377]
#### Describe the bug

When a [SponsorBlock](https://sponsor.ajay.app) prompt appears in the YouTube player (asking to skip a section of a type that's set to manually skip), the text in the popup is parsed as an artist and title, and the currently-playing song is replaced by that text.

This also breaks data corrections -- having replaced the captured text the first time with the song playing at the time, other songs which trigger the same skips end up being reported as the original song.

#### How to reproduce

1. Install SponsorBlock and set the skips to manual:
  ![Non-Music Section set to Manual Skip](https://user-images.githubusercontent.com/4025899/192070240-4bcf6be3-7e50-4bdb-9eea-eaa004b93f2a.png)
2. Go to a music video with a segment at the start or end that SponsorBlock recognises (e.g. [this one](https://youtu.be/EVBsypHzF3U)).

* When a "Non-Music" popup appears, the detected song is "Music" by "Non".
* When a "Endcards/Credits" popup appears, the detected song changes to "Credits" by "Endcards".

#### Expected behaviour

SponsorBlock popups shouldn't be parsed when looking for the song title and artist name.

#### Screenshots

These are the in-player popups:
![Non-Music popup](https://user-images.githubusercontent.com/4025899/192070440-2abd3c18-043d-48bb-b672-662501f710c6.png) ![Credits popup](https://user-images.githubusercontent.com/4025899/192070435-469e98c9-6cd8-4c93-bfc2-f74df41a3a08.png)

And the resulting song detection:
![Non by Music](https://user-images.githubusercontent.com/4025899/192070756-6327838b-7193-4f19-b1a3-48260670fddf.png) ![Credits by Endcards](https://user-images.githubusercontent.com/4025899/192070465-b721ed6b-8622-4f07-9be9-5b14c4824d07.png)

#### Debug logs

<details>
<summary>Logs</summary>

```
Tab 192: Song unprocessed: {
  "parsed": {
    "track": "Music",
    "artist": "Non",
    "album": null,
    "albumArtist": null,
    "uniqueID": null,
    "duration": null,
    "currentTime": null,
    "isPlaying": false,
    "trackArt": null,
    "isPodcast": false,
    "originUrl": "https://youtu.be/EVBsypHzF3U"
  },
  "processed": {
    "track": null,
    "album": null,
    "artist": null,
    "albumArtist": null,
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": true,
    "isValid": true,
    "isMarkedAsPlaying": true,
    "isSkipped": false,
    "isReplaying": false
  },
  "metadata": {
    "startTimestamp": 1663977452,
    "label": "YouTube",
    "trackArtUrl": "http://coverartarchive.org/release/71babf1e-82cc-4c40-be2e-df69c38f2784/front-500",
    "notificationId": "6"
  },
  "connectorLabel": "YouTube"
}

Tab 192: Clearing playback timer destination time

Send "get info" request: 1

Tab 192: Song finished processing: {
  "parsed": {
    "track": "Music",
    "artist": "Non",
    "album": null,
    "albumArtist": null,
    "uniqueID": null,
    "duration": null,
    "currentTime": null,
    "isPlaying": false,
    "trackArt": null,
    "isPodcast": false,
    "originUrl": "https://youtu.be/EVBsypHzF3U"
  },
  "processed": {
    "track": null,
    "album": null,
    "artist": null,
    "albumArtist": null,
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  },
  "metadata": {
    "startTimestamp": 1663977496,
    "label": "YouTube"
  },
  "connectorLabel": "YouTube"
}
```
</details>

#### Environment

- OS: Windows 10
- Browser: Firefox 106 (developer edition)
- Extension version: v2.70.1

#### Additional context

SponsorBlock version: 5.0.4

**Comment by mchangrh** [comment]
Have you considered using [Navigator.mediaSession ](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaSession) as a way to pull metadata? Last time I was testing it, it would reliably return the video title, uploader and thumbnail.

SponsorBlock does  [re-set it](https://github.com/ajayyy/SponsorBlock/pull/1155/commits/ba7d46dd73ee6d98fcb187fd3ae5b0e851316023#diff-b769f60434f9ce6a59837e3786f8b1ef4d13930a04c73e4d525ffa17ad9f665cR1276-R1283) when there are audio notifications, so beware of that if you are going that route

**Comment by Eyeball753** [comment]
It also happens with intermission. It detected the artist but the song title was named Intermission. It doesn't even reset for the next song(s). I've had 9 Non - Music in a row and only the first one had a non-music skip. When it detects 1 intermission, all the following song titles seem to be "Intermission" regardless if there's an intermission or not. It wasn't a problem until about 2 weeks ago.

**Comment by inverse** [comment]
Should be fixed in the latest release thanks to @yayuyokitano
