### ISSUE TITLE
Unable to scrooble on PWA

### ISSUE THREAD

**Issue by furquim87** [web-scrobbler/web-scrobbler#3390]
**Describe the bug**
Since the last update (version 2.73.0) I'm unable to scrobble Youtube Music songs on PWA mode. While it works fine if I open YouTube Music on a browser tab, if I listen to a song using a PWA it will first it gives me the message: 
"Play some music to get started
Is it already playing?"

If I refresh the page, sometimes it will give me the same message, but other times it says:
"This website is not supported
Web Scrobbler does not support scrobbling from this website.
Some Google websites supported by the extension (e.g. Google Play Music, YouTube) can be blocked due to an ExtensionSettings policy.
Learn more"

I already tried using the extension on Google Chrome, Microsoft Edge and Firefox (via Progressive Web Apps for Firefox addon)

EDIT: Now it doesn't even seem to work while playing on the browser itself, only on Firefox where the extension is still on version 2.72.0.

**How to reproduce**
1. Go to YouTube Music PWA (on Chrome, Edge or even Firefox via Progressive Web Apps for Firefox addon)
2. Try to play a song
3. Receive "Play some music to get started
Is it already playing?" message.

**Debug logs**
[Debug log.](https://pastebin.com/5CBciwZP)

**Environment (please complete the following information)**
-   OS: Windows 10 LTSC 2021
-   Browser: Chrome, Edge, Firefox
-   Extension version: 2.73.0

**Comment by a-github-account** [comment]
What is PWA mode?

**Comment by forsureitsme** [comment]
@furquim87 It's supposed to be fixed now in 2.73.1, can you update the extension and verify that?

**Comment by furquim87** [comment]
> @furquim87 It's supposed to be fixed now in 2.73.1 (#3393), can you update the extension and verify that?
> 
> Youtube Music is rolling out a update that broke the scrobbling for some users. 2.73.0 fixed scrobbling for those who received the update, but broke for those who didn't (which seems to be your case) and 2.73.1 fixes scrobbling for everyone 🎉
> 
> @a-github-account YTM behaves like a app when you click `Install` on the chrome omnibox, this is the Progressive Web App mode

Oh, so that was the issue. Google tends to roll out updates slowly like that, it makes sense.
I have updated my extension to the latest version and it's working again, thank you very much!
