### ISSUE TITLE
Cannot scrobble an album called "http://"

### ISSUE THREAD

**Issue by JoshuaWalsh** [web-scrobbler/web-scrobbler#3392]
**Describe the bug**
I'm listening to the album ["http://" by Daiki Tsuneta Millenium Parade](https://rateyourmusic.com/release/album/daiki-tsuneta-millennium-parade/http/) on Plex. Web Scrobbler is correctly detecting the tracks, the beamed eighth icon is green and once the halfway point is reached it changes into a checkmark. Clicking on it shows the correct track information.

But on my Lastfm profile, the scrobbles don't appear. Sometimes the checkmark also changes back into the beamed eighth before the end of the song, but I can't consistently reproduce this.

**How to reproduce**
1. Add an album called "http://" to Plex
2. Listen to the album

**Expected behavior**
The tracks should be scrobbled. If they cannot be scrobbled, the WebScrobbler icon should indicate that an error occurred and I should be able to try to fix the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/2290576/192422234-9afa6ef5-d36f-4b5a-8211-730b24bbdf50.png)
![image](https://user-images.githubusercontent.com/2290576/192422286-ebb0ddd0-4332-4c04-8371-3907eaefdaad.png)

**Debug logs**
[Background script](https://pastebin.com/68sH9UtY)
[Content script](https://pastebin.com/sWKgt6U0)

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Firefox
-   Extension version: 2.73.0

**Comment by hornbuckle** [comment]
This appears to be an issue with Last.fm and not the extension.
On Last.fm, the album has 0 listeners and 0 scrobbles: https://www.last.fm/music/Daiki+Tsuneta+Millennium+Parade/http:%2F%2F
Looks like some people may have added spaces between the slashes to get it to register: https://www.last.fm/music/Daiki+Tsuneta+Millennium+Parade/Http:+%2F+%2F

**Comment by jaccarmac** [comment]
I can confirm using [Open Scrobbler](https://openscrobbler.com/scrobble/song) that this is a Last.fm issue. Unfortunately, there are a certain number of tracks out there which the API rejects. I remember discovering the issue with [Track 4 by Mania D](https://www.youtube.com/watch?v=txFLQmn_UFw).
