### ISSUE TITLE
LInda's song

### ISSUE THREAD

**Issue by laxier** [web-scrobbler/web-scrobbler#3395]
1. Go to (https://www.youtube.com/watch?v=6-RakMT9Oeg)
2. Dosn't not scrobble

**Comment by inverse** [comment]
This song is not categorised as music - you'll need to turn off both YouTube checkboxes in the options.

![image](https://user-images.githubusercontent.com/713525/193426735-0632725a-4f14-419e-be41-c266d763e418.png)
