### ISSUE TITLE
Add musicForProgramming

### ISSUE THREAD

**Issue by AnzenKodo** [web-scrobbler/web-scrobbler#3410]
**Provide information about website**
URL: https://musicforprogramming.net/twentyfive
Description: A series of mixes intended for listening while programming to focus the brain and inspire the mind (also compatible with other activities).

**Additional context**
![musicforprogramming net_twentyfive](https://user-images.githubusercontent.com/50282743/194504163-63a7a7cd-3896-493c-82e5-d245a4bbf2d9.png)

**Comment by inverse** [comment]
The problem with this site is that there is no duration information to determine when a track starts or stops.

See other discussions:

- https://github.com/web-scrobbler/web-scrobbler/issues/2199
- https://github.com/web-scrobbler/web-scrobbler/issues/1171
