### ISSUE TITLE
Add radio.animebits.moe

### ISSUE THREAD

**Issue by 3my** [web-scrobbler/web-scrobbler#3412]
**Provide information about website**
Web radio focused on Japanese music such as J-pop.

**Additional context**
<img width="1517" alt="Screen Shot 2022-10-08 at 2 15 50 pm" src="https://user-images.githubusercontent.com/50735462/194686658-792f5917-27f7-4294-950a-c297d6e7a591.png">

**Comment by inverse** [comment]
Will be solved in the next release - thanks @hornbuckle
