### ISSUE TITLE
EpidemicSound scrobbling not working

### ISSUE THREAD

**Issue by Arilozen** [web-scrobbler/web-scrobbler#3414]
EpidemicSound scrobbling isn't working - using Firefox if that helps. Everything else is scrobbling normally. I double checked to make sure that in the settings I had EpidemicSound set to scrobble yet the issue remains. Maybe they changed their site again? 

**How to reproduce**
1. Go to https://www.epidemicsound.com/music/featured/
2. Click on any song.
3. Check the Web Scrobbler addon to verify it isn't registering the song.

**Debug logs**
Some cookies are misusing the recommended “SameSite“ attribute 105
INS: content-ads.js loaded:  https://www.epidemicsound.com/ [content-scripts.js:1:108429](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
TSS: content-tss.js loaded:  https://www.epidemicsound.com/ [content-scripts.js:1:118223](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
INS: content-blocked-items.js loaded:  https://www.epidemicsound.com/ [content-scripts.js:1:138261](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
CONTENT_SHELL: Page allowed. Skipping shell injection blocks [content-scripts.js:1:137923](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
GET TAB ID RESPONSE:  
Object { tabId: 30 }
[content-scripts.js:1:119759](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
TSS: excluded result:  
Object { excluded: true }
[content-scripts.js:1:128944](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
TSS: Excluding content tss (trigger: send-mesage) [content-scripts.js:1:120296](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
InstallTrigger is deprecated and will be removed in the future. [mainapp.bundle.js:2:324129](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/270052/envelope/?sentry_key=b6756e6e0de64511aaf4a2f122f3b91a&sentry_version=7. (Reason: CORS request did not succeed). Status code: (null).

Loading failed for the <script> with source “https://gtm.epidemicsound.com/gtm.js?id=GTM-K3LQPX&gtm_auth=&gtm_preview=&gtm_cookies_win=x”. [www.epidemicsound.com:1:1](https://www.epidemicsound.com/)
[OPTIMIZELY] - ERROR 2022-10-10T18:50:21.733Z DatafileManager: Error fetching datafile: Request error [mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.optimizely.com/datafiles/QL6JxRu99mLC1w1s9gh52.json. (Reason: CORS request did not succeed). Status code: (null).

[OPTIMIZELY] - ERROR 2022-10-10T18:50:21.736Z DatafileManager: Error fetching datafile: Request error [mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.optimizely.com/datafiles/Wu3PYofgU8R74DqhBvZiV.json. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/270052/envelope/?sentry_key=b6756e6e0de64511aaf4a2f122f3b91a&sentry_version=7. (Reason: CORS request did not succeed). Status code: (null).
2
Web Scrobbler: Element '[class="src-mainapp-player-components-___PlayerBar__player___ZJ8j7"]' is missing [util.js:541:10](moz-extension://115f0871-f70c-4ebf-8c58-f8d0c2a58170/core/content/util.js)
Web Scrobbler: Starter is already loaded [util.js:541:10](moz-extension://115f0871-f70c-4ebf-8c58-f8d0c2a58170/core/content/util.js)
Activity event validation: Some fields will be overwritten 
Array [ "context" ]
[mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Activity event validation: Some fields will be overwritten 
Array [ "context" ]
[mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
INS: content-ads.js loaded:  about:blank [content-scripts.js:1:108429](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
TSS: content-tss.js loaded:  about:blank [content-scripts.js:1:118223](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
INS: content-blocked-items.js loaded:  about:blank [content-scripts.js:1:138261](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
Activity event validation: Some fields will be overwritten 
Array [ "context" ]
[mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Activity event validation: Some fields will be overwritten 
Array [ "context" ]
[mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
CONTENT_SHELL: Page allowed. Skipping shell injection blocks [content-scripts.js:1:137923](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
GET TAB ID RESPONSE:  
Object { tabId: 28 }
[content-scripts.js:1:119759](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
TSS: excluded result:  
Object { excluded: true }
[content-scripts.js:1:128944](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
TSS: Excluding content tss (trigger: send-mesage) [content-scripts.js:1:120296](moz-extension://11ff5be3-6505-4618-8315-a413f4195a42/content-scripts.js)
Error: Promised response from onMessage listener went out of scope 17 [background.js:841:170](moz-extension://390123ea-23e6-4f0c-b518-5ff455e2313c/dist/background.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://logx.optimizely.com/v1/events. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.recurly.com/js/v1/events. (Reason: CORS request did not succeed). Status code: (null).

Activity event validation: Some fields will be overwritten 
Array [ "context" ]
[mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Error: Promised response from onMessage listener went out of scope 2 [background.js:841:170](moz-extension://390123ea-23e6-4f0c-b518-5ff455e2313c/dist/background.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.recurly.com/js/v1/events. (Reason: CORS request did not succeed). Status code: (null).

Source map error: Error: request failed with status 404
Resource URL: https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.css
Source Map URL: mainapp.css.map

Error: Promised response from onMessage listener went out of scope [background.js:841:170](moz-extension://390123ea-23e6-4f0c-b518-5ff455e2313c/dist/background.js)
Source map error: Error: request failed with status 404
Resource URL: https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js
Source Map URL: mainapp.bundle.js.map

Error: Promised response from onMessage listener went out of scope [background.js:841:170](moz-extension://390123ea-23e6-4f0c-b518-5ff455e2313c/dist/background.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.recurly.com/js/v1/events. (Reason: CORS request did not succeed). Status code: (null).

Activity event validation: Some fields will be overwritten 
Array [ "context" ]
[mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
[OPTIMIZELY] - ERROR 2022-10-10T18:52:22.684Z DatafileManager: Error fetching datafile: Request error [mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.optimizely.com/datafiles/QL6JxRu99mLC1w1s9gh52.json. (Reason: CORS request did not succeed). Status code: (null).

[OPTIMIZELY] - ERROR 2022-10-10T18:52:22.688Z DatafileManager: Error fetching datafile: Request error [mainapp.bundle.js:2:284809](https://cdn.epidemicsound.com/player/20221010.87-0866fff409388670cc9a6db35aaa569de02a5f26/mainapp.bundle.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.optimizely.com/datafiles/Wu3PYofgU8R74DqhBvZiV.json. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/270052/envelope/?sentry_key=b6756e6e0de64511aaf4a2f122f3b91a&sentry_version=7. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.recurly.com/js/v1/events. (Reason: CORS request did not succeed). Status code: (null).

Error: Promised response from onMessage listener went out of scope [background.js:841:170](moz-extension://390123ea-23e6-4f0c-b518-5ff455e2313c/dist/background.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.recurly.com/js/v1/events. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.recurly.com/js/v1/events. (Reason: CORS request did not succeed). Status code: (null).

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: Firefox
-   Extension version: v2.75.1

**Comment by hornbuckle** [comment]
Unfortunately, the last update to the connector did not use good selectors (see comment https://github.com/web-scrobbler/web-scrobbler/pull/3317#pullrequestreview-1064343585 ).
Will submit an update to this one later this week.

**Comment by inverse** [comment]
Thanks @hornbuckle :pray:

**Comment by inverse** [comment]
Should be fixed in the next release - thanks @hornbuckle
