### ISSUE TITLE
Fallback for scrobbling songs with multiple artists

### ISSUE THREAD

**Issue by nalsai** [web-scrobbler/web-scrobbler#3432]
**Is your feature request related to a problem? Please describe.**

I'm having trouble scrobbling songs from 電音部/DENONBU (https://music.youtube.com/channel/UCA22VRlaMmb2B1-ki2MLLBw) on YouTube Music. It always says "The track is not recognized" until I manually add it.
YouTube Music has 電音部 and the singers in the artist field and often has the composer in brackets in the title.
Using the built in scrobbling feature of Spotify it only uses the first artist (which is always 電音部). Additionally Spotify does not have the composer in brackets in the title. It's artist field usually contains "電音部, composer, singers".

Example: YouTube Music has "`DENONBU, Tama Kurogane (CV: Akina), Aki Shirokane (CV: Arisa Komiya) & Ginka Haijima (CV: Azuki Shibuya) - Azabu Autobahn (Prod. Kenmochi Hidefumi)`" and web-scrobbler tries to scrobble "`DENONBU, Tama Kurogane (CV: Akina), Aki Shirokane (CV: Arisa Komiya), Ginka Haijima (CV: Azuki Shibuya) - Azabu Autobahn (Prod. Kenmochi Hidefumi)`".
Spotify has "`電音部, 黒鉄たま (CV: 秋奈), 白金 煌 (CV: 小宮有紗), 灰島銀華 (CV: 澁谷梓希) - Azabu Autobahn`" and scrobbles "`電音部 - Azabu Autobahn`".

Looking at the links to test in the YouTube Music connector source code, the first one (https://music.youtube.com/playlist?list=OLAK5uy_kDEvxPASaVnoSjOZViKEn4S3iVaueN0UI) also fails. web-scrobbler tries to scrobble "`Mt. Eden, T-Mass - As One (feat. Aviella Winder)`". Last.fm has the following entries for it, in order of popularity:
- Mt. Eden - As One
- Mt Eden - As One
- Mt. Eden & T-Mass - As One (feat. Aviella Winder) 
- Mt Eden - As One (feat. Aviella Winder)
- Mt Eden, T-Mass feat. Aviella Winder - As One
- Mt. Eden, T-Mass feat. Aviella Winder - As One
- Mt. Eden - As One (feat. Aviella Winder)

**Describe the solution you'd like**
I would want some kind of fallback, so it tries to scrobble with only the first artist (or maybe also with a & instead of a comma) rather than just failing (and maybe also without the feat. or Prod. part). 

**Describe alternatives you've considered**
#3306 proposes to always only scrobble one artist in YouTube Music.

**Additional context**
I think that trying to scrobble with all artists is good, but it often creates problems and I'd rather just have the first artist than no scrobble at all.
I don't think Force track recognition is a good option either for YouTube Music, because YouTube Music can contain videos which could then be wrongly scrobbled.

**Comment by jaccarmac** [comment]
This sounds like it might be two issues:

> It always says "The track is not recognized" until I manually add it.
> ...
> Example: YouTube Music has "DENONBU, Tama Kurogane (CV: Akina), Aki Shirokane (CV: Arisa Komiya) & Ginka Haijima (CV: Azuki Shibuya) - Azabu Autobahn (Prod. Kenmochi Hidefumi)" and web-scrobbler tries to scrobble

Does it scrobble that track correctly if you check "Force track recognition" in the options? The test track scrobbles for me, and I have that option set. [Azabu Autobahn](https://music.youtube.com/watch?v=nPLecyI8SIQ) also seems to be recognized.

If the option is not set and setting it fixes recognition, this sounds like another request for single-artist behavior, which is under discussion at the pull you linked. In short, I'm in favor of using the metadata as presented by the website in question as much as possible, and see always trimming the list of artists as incorrect.

The fallback idea is an interesting one; I hadn't consider it because I keep my force option on. Thanks!

**Comment by Nalsai** [comment]
I understand my problem now. I thought it was related to scrobbling multiple artist, but that isn't my main problem. I think I'll just keep "Force track recognition" enabled to deal with that.

Looking at https://github.com/web-scrobbler/web-scrobbler/blob/08a83475486c8a77a39319ce8531c7e4eebf5272/src/connectors/youtube-music.js#L25
the youtube-music connector gets all channel links in the player bar and concatenates them with a comma. This does not work in some cases, as some tracks just have a simple string without links to the artist

Examples:
[Itadaki Babel](https://music.youtube.com/watch?v=4Cal0plgebc) works correctly - there is one artist with a link.
[Belka](https://music.youtube.com/watch?v=oUvrqmOcTz0) works correctly? - there are two artist with links and `&` between them -> artists get recognized, `&` gets replaced with `,`
[Let Me Know](https://music.youtube.com/watch?v=ZuEkN-tEeSc) doesn't work - artists are not linked (it's just a long string).


My quick idea would be to parse the following:

```html
<span class="subtitle style-scope ytmusic-player-bar">
  <yt-formatted-string class="byline style-scope ytmusic-player-bar complex-string" ellipsis-truncate="" ellipsis-truncate-styling="" title="ARTIST(S) • NAME • YEAR">
```

The title field of the yt-formatted-string in .ytmusic-player-bar.subtitle` always contains the artist(s) first, then a " • " and then other stuff (song name and year). Inside of the yt-formatted-string there are spans with artists name and year. Artists are usually - but not always - links, which is what web scrobbler currently looks for. Sometimes it's just one span or multiple links and spans. The name is always a link to the song page.
