### ISSUE TITLE
Support https://radio.garden/

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#3436]
### Discussed in https://github.com/web-scrobbler/web-scrobbler/discussions/3435

<div type='discussions-op-text'>

<sup>Originally posted by **stardepp** October 22, 2022</sup>
I would be very happy if you could scrobble music played on this website:

https://radio.garden/</div>

**Comment by hornbuckle** [comment]
Unfortunately, there is no artist and track information provided on this site, so there is nothing available to scrobble.

**Comment by inverse** [comment]
Thanks for checking
