### ISSUE TITLE
Scrobbling not working on apple music website

### ISSUE THREAD

**Issue by blueming04** [web-scrobbler/web-scrobbler#3442]
**Describe the bug**
Scrobbling is no longer working on https://music.apple.com. This is what the extension says when playing music on the site: 
![Screenshot 2022-10-24 154624](https://user-images.githubusercontent.com/102505988/197644270-212ac9e4-4d38-467e-baa3-f259f0eee43e.png)

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.77.0

**Comment by MrBluesman** [comment]
Beta version of https://music.apple.com/ became an actual version and since beta was not supported it sadly became a real issue now 
https://github.com/web-scrobbler/web-scrobbler/issues/3277

**Comment by MrBluesman** [comment]
![image](https://user-images.githubusercontent.com/25730944/197731983-3b9e842f-ae24-47e6-8fc9-043f6610338a.png)

**Comment by NomaanMalick** [comment]
How long would it take to fix this?

**Comment by Nirzak** [comment]
Apple has updated their website. Now audio and many other metadata is not sourced on the HTML source code. They are rather dumped into a JS file. That's why the extension is not working. Not just this many extension and users script is not working because of this.

**Comment by UnbreakCode** [comment]
you can get the current song information from MusicKit:

`MusicKit.getInstance().nowPlayingItem.title` for the title and `MusicKit.getInstance().nowPlayingItem.artistName` for the artist.

**Comment by franclecor** [comment]
Does anyone know when it will be fixed?

**Comment by thomasknutson21** [comment]
Is it even possible to fix this if scrobbling for the old "beta" apple site never worked anyways? What would make it fixable now? Is it even possible for another scrobbling app to be able to do it? Like is it worth trying to find a different app even? It seems like it would be impossible if they haven't figured it out already? Or is there another app that is/was able to scrobble the old, now live, beta apple site?

**Comment by UnbreakCode** [comment]
> Is it even possible to fix this if scrobbling for the old "beta" apple site never worked anyways? What would make it fixable now? Is it even possible for another scrobbling app to be able to do it? Like is it worth trying to find a different app even? It seems like it would be impossible if they haven't figured it out already? Or is there another app that is/was able to scrobble the old, now live, beta apple site?

it is possible with my fix as mentioned before... should also work on both sites since they are using almost the same MusicKitJS version

**Comment by jaccarmac** [comment]
I can't speak to other scrobblers which may work, but as far as this goes:

> It seems like it would be impossible if they haven't figured it out already?

I don't think anyone has attempted a PR yet. The existing Apple Music connector is also rather old, last updated two years ago.

**Comment by gitmilotic** [comment]
it's been over a week, can this be fixed please? i have no other way to scrobble

**Comment by hornbuckle** [comment]
I don't use Apple Music, but I took a look at the new site to see if it was possible to get this connector working again, as it does allow a preview without an account.
Unfortunately, the new player is inside a shadow DOM (and each module inside the player is nested inside individual shadow DOMs), which makes the existing selector-based connector methods unusable.
@UnbreakCode seems to have a possible solution in mind but has yet to submit a PR.

**Comment by lua-mp3** [comment]
i need to scrobble :((( i don't have any other way to scrobble through pc
![image](https://user-images.githubusercontent.com/117616388/200220633-39529b52-3df3-4859-9e4b-77f8333ab80d.png)

**Comment by Nirzak** [comment]
Finally, it's fixed guys! Now I can again enjoy listening to apple music!

**Comment by inverse** [comment]
thanks @yayuyokitano for the fix ✌️
