### ISSUE TITLE
Firefox version not updated

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#3453]
**Describe the bug**

Last firefox version `2.76.0` - looks like something with the acceptance into the addon store is broken.

Manually generating a dist with `npx grunt dist:firefox` and uploading the zip manually yields

![image](https://user-images.githubusercontent.com/713525/198738782-69a197c4-6fc7-4b65-815e-2be27cc5ece6.png)

Which is strange as those files do exist.

```
├── _locales
│   ├── de
│   │   └── messages.json
│   ├── en
│   │   ├── messages.json
│   │   └── privacy.md
│   ├── es
│   │   └── messages.json
│   ├── pl
│   │   ├── messages.json
│   │   └── privacy.md
│   ├── pt_BR
│   │   └── messages.json
│   ├── ru
│   │   ├── messages.json
│   │   └── privacy.md
│   ├── sk_SK
│   │   └── messages.json
│   └── zh
│       └── messages.json
```

**Comment by inverse** [comment]
cc @hornbuckle

**Comment by yayuyokitano** [comment]
Can't help but notice it's the ones that have a privacy.md and only those. Related?

**Comment by inverse** [comment]
True - the ones in question all include the privacy policy

**Comment by yayuyokitano** [comment]
My suspicion was corrected – this is a bug on firefox end. They patched it 5 days ago. This should solve itself soon I think

**Comment by inverse** [comment]
Oh really? can you link to the :bug: ?

**Comment by yayuyokitano** [comment]
https://github.com/mozilla/addons-linter/issues/4535

**Comment by inverse** [comment]
Looks like they will resolve it Thurs evening Europe/Berlin time

**Comment by inverse** [comment]
https://github.com/mozilla/addons-linter/issues/4552#issuecomment-1299077630

**Comment by inverse** [comment]
Fixed! Just published a new version
