### ISSUE TITLE
Apple Music doesn't scrobble unless I click on the Apple Music tab

### ISSUE THREAD

**Issue by gitmilotic** [web-scrobbler/web-scrobbler#3462]
**Describe the bug**
When you scrobble from Apple Music, it doesn't scrobble the next song until you click on the Apple Music tab. The extension shows your last played song until you click it and it stops scrobbling.

**How to reproduce**
1. Listen to a song on Apple Music
2. Stay on the Apple Music tab
3. Get off the Apple Music tab
4. Let another song play
5. It will not scrobble

**Expected behavior**
It scrobbles every song I play without clicking on the tab.

**Environment**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 2.80.1

**Comment by thomasknutson21** [comment]
I also am experiencing this. I couldn't quite figure it out right away, it was just skipping certain tracks/listens and not scrobbling them. I just realized it has to do with actually clicking on the tab. Glad someone else was able to describe it like this, hopefully now it can be addressed.

**Comment by MrBluesman** [comment]
Good description @gitmilotic 

I can confirm this issue exists, any ideas to fix it?

**Comment by TMoonet** [comment]
Confirming this issue is still existing.

**Comment by lkreimann** [comment]
I'm not sure if it has to do with clicking on the tab but the web scrobbler is certainly skipping some songs I'm listening to.

**Comment by lkreimann** [comment]
Thanks for figuring this out! I noticed some weird behavior in the last few days and couldn't pin down what was wrong - I noticed that there are less scrobbles than usual, but this can be due to my work and other things too ... now I know why.

**Comment by lkreimann** [comment]
I think the problem is solved, can anyone confirm? 

I listened to a whole album without clicking into the tab too often and have all the songs in my scrobbles on last.fm

**Comment by gitmilotic** [comment]
@lkreimann this issue still is happening for me.

**Comment by TMoonet** [comment]
I changed browser, started using Firefox and it's actually working perfectly (I discovered it is a better browser, at least for me).

**Comment by lkreimann** [comment]
I'm using Firefox too. Which browser do you use, @gitmilotic ?

**Comment by gitmilotic** [comment]
@lkreimann i'm using google chrome, as stated in the original post

**Comment by gitmilotic** [comment]
my extension is now updated to v2.82.2 and this is still happening

**Comment by AlbionLoveDen** [comment]
Confirming this is still happening. I have tested this across 2 browers (Edge and Chrome), with both having the same issue.

**Comment by ericcirone** [comment]
I seem to be experiencing this as well.

**Comment by gitmilotic** [comment]
it's been over 2 months and this has still not been fixed. my extension is currently in the current version (2.85.1), too, so it's not an outdated version issue.

**Comment by gitmilotic** [comment]
is this ever going to get fixed?

**Comment by inverse** [comment]
Pull requests are welcome :)

**Comment by tailsdtg3** [comment]
yeah i've been having the same issue ever since apple music changed their coding. i use chrome (ver. 112.0.5615.138) as my browser. hopefully this gets sorted out soon as i've been using this extension for about a year now

**Comment by yayuyokitano** [comment]
It's probably worth updating here too due to the history of the issue. A patch that is hopefully more robust and permanent has been deployed in version 3.0.6. It will hopefully reach you soon.
