### ISSUE TITLE
No scrobbles from Apple Music in Edge

### ISSUE THREAD

**Issue by Spaathen** [web-scrobbler/web-scrobbler#3464]
**Describe the bug**
The web extension is not scrobbling at all from Apple Music in Microsoft Edge.

**How to reproduce**
1. Go to 'Apple Music' and play any track
2. Click on 'the icon of the extension'
3. See that it's not scrobbling at all

**Expected behavior**
Web extension is scrobbling from Apple Music

**Screenshots**
![Screenshot 2022-11-09 210522](https://user-images.githubusercontent.com/117861819/200930445-8d4ec0c7-c7af-4eb6-b0e6-54ee671b4441.png)

**Debug logs**
<details>
  <summary>Debug log</summary>
  Here is the content of debug log: ​ storage.Options = {
  "disabledConnectors": "[hidden]",
  "forceRecognize": false,
  "scrobblePercent": 50,
  "scrobblePodcasts": true,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": false
}
​ storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "*******"
}
​ storage.LibreFM = {}
​ storage.ListenBrainz = {}
​ storage.Maloja = {}
​ storage.LocalCache = {}
​ storage.Connectors = {
  "YouTube": {
    "scrobbleEntertainmentOnly": false,
    "scrobbleMusicOnly": false
  }
}
​ storage.ConnectorsOverrideOptions = {}
​ storage.Core = {
  "appVersion": "2.50.2"
}
​ Bind Last.fm scrobbler
​ 
        
       Unable to bind Libre.fm
bindAllScrobblers @ core/background/obje…obble-service.js:55
​ 
        
       Unable to bind ListenBrainz
bindAllScrobblers @ core/background/obje…obble-service.js:55
​ 
        
       Unable to bind Maloja
bindAllScrobblers @ core/background/obje…obble-service.js:55
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/apple-music.js
inject.js:52 Injecting core/content/starter.js
​ Tab 569927438: Created controller for Apple Music connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/apple-music.js
inject.js:52 Injecting core/content/starter.js
​ Tab 569927438: Remove controller for Apple Music connector
​ Tab 569927438: Created controller for Apple Music connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/apple-music.js
inject.js:52 Injecting core/content/starter.js
​ Tab 569927438: Remove controller for Apple Music connector
​ Tab 569927438: Created controller for Apple Music connector

util.js:541 
        
       Web Scrobbler: Element '.web-chrome' is missing
debugLog @ util.js:541
</details>

**Environment (please complete the following information)**
-   OS: Windows 11 Pro 22H2 22621.819
-   Browser: Microsoft Edge 107.0.1418.35
-   Extension version: 2.50.2

**Comment by Spaathen** [comment]
I just saw that there is a way newer version of the extension available when looking [into another bug](https://github.com/web-scrobbler/web-scrobbler/issues/3462).
Installed the v2.80.1 from the Chrome Web Store, with that version it's working again. 
Please update the version in the Microsoft Edge Web Store.

**Comment by inverse** [comment]
We have #3357 open to handle that - It should be possible with the new npm package but we need to implement a GitHub Action to support this.

**Comment by Spaathen** [comment]
Thanks for the swift feedback. Will close this bug then since it's fixed.
