### ISSUE TITLE
Extensão com indisponibilidade no Youtube Music com o Microsoft Edge.

### ISSUE THREAD

**Issue by danessagames** [web-scrobbler/web-scrobbler#3486]
Quando coloco uma música, a extensão não reconhece:

> Não sei se possui portabilidade para Microsoft Edge, porém, no **Microsoft Edge só funciona se for no Youtube**. Não funciona com Youtube Music.

Evidência:

 #![image](https://user-images.githubusercontent.com/118787134/203210924-52dfcbe4-cd50-4e22-93fc-19dc9e1ee82e.png)

- Obs: no Chrome, funciona normalmente.

**Comment by danessagames** [comment]
+ Tentei no Youtube pelo Microsoft Edge e também não funcionou (lol) XD

**Comment by JGuerr3** [comment]
Samesies, on Edge explorer YouTube Music is not scrobbling.

**Comment by Elfanaarg** [comment]
The version on Ms Stor hasnt been updated since January, the Chrome store one was updated 7 days ago. Uninstall and download it from chrome store

**Comment by danessagames** [comment]
> A versão na Ms Store não foi atualizada desde janeiro, a Chrome Store foi atualizada há 7 dias. Desinstale-o e baixe-o da chrome store

Atualmente estou com o Chrome mesmo, mas quero migrar de vez p o Edge, sabe?

**Comment by danessagames** [comment]
> A versão na Ms Store não foi atualizada desde janeiro, a Chrome Store foi atualizada há 7 dias. Desinstale-o e baixe-o da chrome store

entendi agora o que vc disse. funcionou aqui, mas vale apenas eles consertarem o da ms store

**Comment by yayuyokitano** [comment]
Closing as duplicate of #3357 for now use the workaround described above.

We will be setting up updates to the Edge version soon, but I have no ETA for now.
