### ISSUE TITLE
Plug-in no longer scrobbling

### ISSUE THREAD

**Issue by rgoudie** [web-scrobbler/web-scrobbler#3490]
As of yesterday, the Chrome plug-in no longer scrobbles tracks. It does display tracks as now-playing, but after the tracks end, the song is not scrobbled. I have version 2.81.0 installed. I have tested with other utilities (example: OpenScrobble) and I am able to scrobble through them.

Could there be a regression since the previous version?

Environment
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: 2.81.0

**Comment by yayuyokitano** [comment]
Cannot reproduce this. Could you provide logs as described [here?](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension)

Is it happening on every website, or have you only tested one website?

**Comment by rgoudie** [comment]
NOTE: I have updated the plug-in to version **2.82.0**.

Here are the logs, as requested:

[Spotify tab console logs](https://pastebin.com/mzG2ZAmw)
[WebScrobbler plug-in console logs](https://pastebin.com/SB2VQWCW)

In the WebScrobbler console logs, I noticed numerous messages of the form "The song is too short to scrobble".

I am exclusively using the WebScrobbler plug-in to scrobble Spotify music in my Chrome browser. This has been my consistent set-up for a number of years. I dont have the plug-in installed in any other browser.

I tried scrobbling a music video from YouTube and it successfully scrobbled. However, playing music from the Spotify tab still does not scrobble.

**Comment by yayuyokitano** [comment]
Apologies for the delay, busy week.
From the log, it looks like your spotify is set to show remaining time instead of total duration in the player. Web scrobbler currently does not work properly with this setting.
To set it to full duration, click the "-x:xx" showing the remaining time in the player, and it should turn into full duration again.
Does this solve the issue?

**Comment by rgoudie** [comment]
No worries about the late reply.

Yep! That was exactly the issue. I clicked on the remaining time and it changed to the length of the track. I am again scrobbling. I had no idea that track length display could be clicked. I must have done so inadvertently.

Thanks!
