### ISSUE TITLE
Youtube music (YT music) web player does not scrobble (Edge browser)

### ISSUE THREAD

**Issue by argetar** [web-scrobbler/web-scrobbler#3491]
Youtube music web player does not scrobble (Edge browser), addon writes, that web is supported, but icon is still rfed and do not scrobble to last.fm.  Some weeks ago was averything ok.

Win11 + Microsoft Edge - Verze 107.0.1418.56 (Oficiální build) (64bitová verze)
Web Scrobbler - Velikost: 1,9 MBVelikost1,9 MBVerze: 2 . 5 0
Connected to last.fm account

For  example, Spotify web player scrobbles ok with the same browser and addon.  I tried add some additional patterns in addon settings, deactivated AD block addon, etc.  No effect.

![image](https://user-images.githubusercontent.com/75354884/204081573-6df7120d-e2d7-4311-9243-eb9c74811588.png)

![image](https://user-images.githubusercontent.com/75354884/204081633-781cc471-0263-4c92-bec1-1553f5124478.png)

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by yayuyokitano** [comment]
Hello, I think this might be an issue of the ms addons store version of the addon being out of date (see #3357 for details on this, reimplementing edge support is in the works, but I have no ETA).
For the time being, you should be able to get around this by using the chrome web store version of the addon (which works just fine on edge, and is more up to date).
Let me know if you have any success with this

**Comment by argetar** [comment]
Thank you for yoer reaction. I have tried higher version of scrobbler app from Chrome store and scrobling wit YT music works now ok.

Thank you for this workaround tip!
