### ISSUE TITLE
Web scrobbler doesn't register Youtube music

### ISSUE THREAD

**Issue by DrivvaadeDillan** [web-scrobbler/web-scrobbler#3497]
**Describe the bug**
Web scrobbler doesn't register Youtube Music anymore (regular youtube works)

**How to reproduce**
1. Go to https://music.youtube.com/
2. Click on any song
3. Doesn't register

**Screenshot**
![dudu](https://user-images.githubusercontent.com/119352782/204355359-c626e152-68ef-4a80-90fc-38a03552e060.png)

**Environment (please complete the following information)**
Opera

**Comment by yayuyokitano** [comment]
Could you confirm which version of web scrobbler you currently have installed?

**Comment by DrivvaadeDillan** [comment]
![IhUstxZ](https://user-images.githubusercontent.com/119352782/204357083-0b843737-814f-41c6-a01b-a943aa6061c9.png)

**Comment by yayuyokitano** [comment]
Your web scrobbler version is outdated, try to update to the most recent version (2.81.0) and it should work.

From the version given, this mightve been downloaded from the ms addons store, which currently is not receiving updates (to be solved by #3493 soon)

**Comment by DrivvaadeDillan** [comment]
Ah thank you very much for the answer
