### ISSUE TITLE
Last update on Microsoft Edge was on 2022 January

### ISSUE THREAD

**Issue by maxmillerb** [web-scrobbler/web-scrobbler#3502]
Last update on Microsoft Edge was on 2022 January (version 2.50.2)

https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc

**Comment by yayuyokitano** [comment]
Closing as duplicate of #3357
#3493 will address this once completed
