### ISSUE TITLE
Is there a way to edit the album art for custom scrobbles?

### ISSUE THREAD

**Issue by nike34** [web-scrobbler/web-scrobbler#3504]
what the title says, I have a certain song that I like but the cover art is wrong, is there a way to fix this?

**Comment by yayuyokitano** [comment]
There is no way to change this within web scrobbler, however you can add album covers on lastfm album pages (but which one displays depends on which is top rated). The image shown in the web scrobbler extension doesnt necessarily match lastfm.

**Comment by nike34** [comment]
I see, guess I'll do that then! thanks!
