### ISSUE TITLE
Add an easy method to go to the extension's settings page

### ISSUE THREAD

**Issue by Froggo8311** [web-scrobbler/web-scrobbler#3507]
I find there's no obvious way to get to the settings without just entering the URL for the extension. Please add a way to get to the settings page.

**Comment by yayuyokitano** [comment]
> I find there's no obvious way to get to the settings without just entering the URL for the extension. Please add a way to get to the settings page.

The way to access extension settings are standardized per browser. Usually it is a matter of right clicking the extension icon and hitting "Extension options" (or similar)

**Comment by yayuyokitano** [comment]
I don't know which browser specifically you're using, but for the western big browsers with web scrobbler support, this is the way to access the designated options page of an extension:

Chrome: right click the extension icon and hit "Options", and it will take you to the options index.html
Edge: right click the extension icon and hit "Extension Options", and it will take you to the options index.html
Opera: Same as Chrome
Firefox: The UX is a bit worse on this one sadly, but right click extension icon, hit manage extension, then in that menu hit the triple dots and click "preferences", and it will take you to the options index.html

**Comment by Froggo8311** [comment]
Ohhh, okay, I didn't notice it when I checked there. I'm on waterfox (a fork of firefox) and never saw the preferences button.

Still might be nice to have a link inside the extension's popup, though.
