### ISSUE TITLE
songs from youtube playlists don't scrobble separately

### ISSUE THREAD

**Issue by runarawd** [web-scrobbler/web-scrobbler#3510]
when i listen to a playlist on youtube, the scrobbler scrrobles a whole name of the playlist, and not the songs that is in this playlist. but it used to scrobble the songs separately
for example, this playlist:
https://www.youtube.com/watch?v=zzn2dpOo5iI&list=PLP8UFDNH7PxMfYS5jsEjPABXXSMeIrUfv&index=1
the first song is the neighbourhood - female robbery, but the scrobble is "pov: driving through forks (twilight playlist)"

![image](https://user-images.githubusercontent.com/120267269/206863977-f3e32de4-b087-43e5-890d-50b5d0e27927.png)

what should i do to get the scrobbles of the songs one by one?

**Comment by yayuyokitano** [comment]
The functionality to scrobble each song in a playlist requires the video to be split into chapters, which this video isn't.
There isn't really a way for us to figure out which song is where without this, unfortunately.
You could try to ask the uploader to add the tracklist with time signatures to the description of the video so chapters are added to it.
