### ISSUE TITLE
Sanitize Bandcamp origin_url field

### ISSUE THREAD

**Issue by MonkeyDo** [web-scrobbler/web-scrobbler#3515]
**Describe the bug**
I noticed that listens submitted to ListenBrainz can have very long URLs full of Bandcamp-specific query parameters.

**How to reproduce**
Search for an album name and click on the result. Start playing the album.
Here is an example of the type of originURL sent to ListenBrainz in the track_metadata:
`"origin_url": "https://yidmusic.bandcamp.com/album/space-klezmer?from=search&search_item_id=266395793&search_item_type=a&search_match_part=%3F&search_page_id=2321371749&search_page_no=0&search_rank=2&logged_in_menubar=true"`

I have only checked with the Bandcamp connector and submitting to LB, but the same could apply to other connectors.

**Expected behavior**
I would expect a URL stripped of the query parameters like so:
`"origin_url": "https://yidmusic.bandcamp.com/album/space-klezmer"`

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Brave (Chromuim)
-   Extension version: 2.82.1

**Comment by inverse** [comment]
Found the issue - by default we take the full URL - this kinda makes me wonder if we should by default on all connectors exclude everything in the query string. 

I could imagine that might cause some invalid data for you though since I'm sure there are some services which use that?

**Comment by MonkeyDo** [comment]
> Found the issue - by default we take the full URL - this kinda makes me wonder if we should by default on all connectors exclude everything in the query string.
> 
> I could imagine that might cause some invalid data for you though since I'm sure there are some services which use that?

Thank you! So quick!

I also think it would make sense to always sanitize. I'll investigate the data we have and see if any service requires some query parameters, but I would assume for their own sake that would not be the case :)

**Comment by MonkeyDo** [comment]
Actually there is a very obvious one which does rely on a query parameter: Youtube and Youtube Music.

Here's an example origin_url: "https://music.youtube.com/watch?v=LZUZbV_XVPU&list=RDTMAK5uy_kset8DisdE7LSD4TNjEVvrKRTmG7a56sY"

Indeed in this case the absence of query parameters would make the url pointless.
I think even the `list` query parameter could potentially be useful in some situations.

That makes me think that we should sanitize URL on a case-by-case basis, since we could be stripping potentially-useful-in-the-future information otherwise.

**Comment by hornbuckle** [comment]
It doesn't seem like it would be scalable to know when to strip the query param and when not to, as it would require specific logic for every site supported by the extension. Perhaps most sites don't require a param, but as noted, for those that need it, the URL would be useless without it.
Another recent example: https://streamdb5web.securenetsystems.net/cirrusencore/index.cfm?stationCallSign=KNBZFM

**Comment by inverse** [comment]
Indeed - but I am trying to think of what would be better. 

The example found with Bandcamp looked like some internal analytics for tracking where folks came from.

But I could imagine also cases where folks run similar campaigns from other platforms - would be quite a significant effort to go through each connector though.
