### ISSUE TITLE
Bandcamp scrobbling issues on Firefox

### ISSUE THREAD

**Issue by fizmatbfu** [web-scrobbler/web-scrobbler#3520]
**Describe the bug**
In last 2-3 weeks sometimes apeear troubles with Bandcamp scrobbling.

**How to reproduce**
Usually it looks like this: after page loading and clicking the "Play" button extension does nothing ("To get started, turn on any song"). After reloading the page, extension shows track, which was played before reload, but does not change it, if i click "Play" for any other track.
After some page reloads extension says, that this site isn't supported.
The problem is consistently repeated on [this page](https://artofpropaganda.bandcamp.com/album/harakiri-for-the-sky) and some others.

**Environment**:
OS: Windows 10 Home
Browser: Firefox 107.0.1 64bit
Scrobbler v. 2.82.2

I tried add `*.bandcamp.com/*` template in settings, but it doesn't help

**Comment by fizmatbfu** [comment]
It seems, that problem is inaccessibility of Bandcamp images server (it's blocked in my country). If i use VPN, all works fine (sometimes, when images for some reason loading without it, extension also works fine).

**Comment by inverse** [comment]
Closing as stale
