### ISSUE TITLE
Scrobble for Český Rozhlas does not work 

### ISSUE THREAD

**Issue by bababuibui** [web-scrobbler/web-scrobbler#3542]
Scrobbling for any czech radio station is not supported (mujrozhlas.cz) despite the fact it is mentioned in your list it is. I believe it worked in the past. Will you please look in to it?

I tried also chrome and firefox - it says same statement that it is not supported.

**Comment by jaccarmac** [comment]
It looks like the connector is set up to match URLs like "prehravac.rozhlas.cz". If you add "mujrozhlas.cz" as a custom URL, does the connector work?

**Comment by hornbuckle** [comment]
Previously reported: #3396
