### ISSUE TITLE
Adding zvuk.com

### ISSUE THREAD

**Issue by zelebb** [web-scrobbler/web-scrobbler#3551]
Is it possible to add connector for https://zvuk.com?

Now the extension says that the site is not supported although "СберЗвук" is advertised as available in the desription of Web Scrobbler.

"СберЗвук" is the previous name for zvuk.com. They also changed the domain.

**Comment by yayuyokitano** [comment]
Apologies for the lateness of this and thank you for reporting. Update to this connector has been included into #3820 
The PR in question is rather large and is a draft for now, but should be included in next update.
