### ISSUE TITLE
The scrobbler doesn't scrobble music on Youtube

### ISSUE THREAD

**Issue by Vytas-R** [web-scrobbler/web-scrobbler#3552]
**Describe the bug**
The scrobbler doesn't scrobble music on Youtube. Says "This website is not supported" or "Play some music to get started"  

**How to reproduce**
Play music on Youtube - see not active add-on

**Expected behavior**
I expect scrobbling.

**Screenshots**
![scrobbler1](https://user-images.githubusercontent.com/123246155/213867480-040c5751-ab28-49d3-8f29-feac935432e1.jpg)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.
tried to get but too complicated
**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Firefox 109.0 (64 bit)
-   Extension version: 2.85.1

**Additional context**
It just refuses to be active on Youtube, works on Spotify.

**Comment by Kodey-Kayla** [comment]
can confirm is happening

OS: Windows 10 Pro 22H2
Browser: Firefox 109.0
Extension version: 2.85.1

**Comment by luthor000** [comment]
Same problem. The scrobbler says "Service error".
- OS: Windows 10
- Browser: Chrome 109.0
- Extension version: 2.85.2

**Comment by jaccarmac** [comment]
I believe I see the same issue. YouTube Music still works.

**Comment by Vytas-R** [comment]
Looks like everything ok now, fixed

**Comment by Vytas-R** [comment]
On some music seems ok, but sometimes complains about "Play some music to get started" while music is playing. Maybe does not like some genres, like jazz :)

**Comment by jaccarmac** [comment]
What does your "YouTube" section in the extension options look like? If either checkbox is checked, some videos will not scrobble and it's hard to tell ahead of time which ones.

**Comment by Vytas-R** [comment]
> 

Both options were checked, now I unchecked both of them. Not sure what they mean, let's see how it will react. Sorry if it was only options issue, not a bug at all, ups :)

**Comment by jaccarmac** [comment]
> Not sure what they mean

It's slightly obscure. Every YouTube video has a category. This used to be more visible in the UI, but it seems like categories are mostly visible for creators nowadays. However, the extension can figure out which category a video is in. Those options control whether all videos are scrobbled or just those in the given category. Unchecking both boxes enables scrobbling on all YouTube videos and is generally the most resilient option. Videos often have nonsense categories. See #3272 and related issues.
