### ISSUE TITLE
beatbump.ml not working

### ISSUE THREAD

**Issue by awsms** [web-scrobbler/web-scrobbler#3559]
ungoogled-chromium 109.0.5414.119 / web-scrobbler 2.85.2
https://beatbump.ml/release?type=MUSIC_PAGE_TYPE_ALBUM&id=MPREb_DBaqiU32Mgt

i can see in the console the extension is fetching fine the matadata.. but isPlaying is instantly set to false & then doesn't scrobble anything?
![Screenshot from 2023-01-29 15-47-55](https://user-images.githubusercontent.com/48278661/215334323-4cf5f5f4-0fb4-4833-bb6d-b667d5cfac8c.png)

**Comment by awsms** [comment]
```
l.26	return document.querySelector('.player-btn.player-title svg use').href.baseVal === '/icons-9852f1b5.svg#play';
```
fixed it

**Comment by jaccarmac** [comment]
Please feel free to open a pull request for that change!

**Comment by awsms** [comment]
Done! https://github.com/web-scrobbler/web-scrobbler/pull/3567

**Comment by inverse** [comment]
Will be in the next release - thanks @awsms
