### ISSUE TITLE
Support for KINK radio

### ISSUE THREAD

**Issue by softguitar** [web-scrobbler/web-scrobbler#3560]
Could you please add KINK radio? https://kink.nl/player/stream.kink

A Dutch radio station that has 3 channels.

**Comment by softguitar** [comment]
Issue can be resolved by going to https://tunein.com/radio/KINK-s210430/ and scrobbling that way.

**Comment by hornbuckle** [comment]
Adding a new connector for this site may be relatively simple. I will look into it more soon.
