### ISSUE TITLE
Spotify songs are no longer detected

### ISSUE THREAD

**Issue by Mirika1** [web-scrobbler/web-scrobbler#3577]
**Describe the bug**
At some point after 1:03 PM today, the Web Scrobbler extension stopped detecting songs from Spotify. It still detects songs from YouTube, so it is a problem with Spotify specifically.

**How to reproduce**
1. Go to open.spotify.com
2. Play a song
3. Click on the Web Scrobbler extension icon
4. See that the song is not detected

**Expected behavior**
The song would be detected.

**Environment**
-   OS: Windows 11
-   Browser: Opera, Microsoft Edge
-   Extension version: 2.86.0

**Comment by inverse** [comment]
Duplicate of #3575

It's already been fixed and pending the app stores.

**Comment by Mirika1** [comment]
Sorry for the duplicate, I didn't think to look at closed issues.
