### ISSUE TITLE
Strange treatment of spaces

### ISSUE THREAD

**Issue by m-jowa1863** [web-scrobbler/web-scrobbler#3584]
**Describe the bug**
The title of [`ゴールデンボンバー「死　ん　だ　妻　に　似　て　い　る」MV`](https://www.youtube.com/watch?v=UPGxsoXAExs) becomes [`死 ん だ 妻 に 似 て い る`](https://www.last.fm/music/%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%87%E3%83%B3%E3%83%9C%E3%83%B3%E3%83%90%E3%83%BC/_/%E6%AD%BB+%E3%82%93%E3%80%80%E3%81%A0%E3%80%80%E5%A6%BB%E3%80%80%E3%81%AB%E3%80%80%E4%BC%BC%E3%80%80%E3%81%A6%E3%80%80%E3%81%84%E3%80%80%E3%82%8B) instead of [`死 ん だ 妻 に 似 て い る`](https://www.last.fm/music/%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%87%E3%83%B3%E3%83%9C%E3%83%B3%E3%83%90%E3%83%BC/_/%E6%AD%BB%E3%80%80%E3%82%93%E3%80%80%E3%81%A0%E3%80%80%E5%A6%BB%E3%80%80%E3%81%AB%E3%80%80%E4%BC%BC%E3%80%80%E3%81%A6%E3%80%80%E3%81%84%E3%80%80%E3%82%8B), where the first space `U+3000` is converted to `U+0020`, but not others.

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=UPGxsoXAExs
2. Let Web Scrobbler scrobble the track

**Expected behavior**
1. All `U+3000` spaces are preserved.
2. All `U+3000` spaces are changed to `U+0020`

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac) Linux
-   Browser: (e.g. Chrome, Safari) Firefox 
-   Extension version: (e.g. v2.10.0) 2.86.2

**Additional context**

**Comment by yayuyokitano** [comment]
This issue is not located within this repo, but within web-scrobbler/metadata-filter
The exact line causing the issue is [this one.](https://github.com/web-scrobbler/metadata-filter/blob/a33c56c9f50d7a5cd93be981fd065d8037a1d491/src/rules.ts#L111)
I would recommend opening an issue over there.

**Comment by m-jowa1863** [comment]
Ok, I have opened an issue at web-scrobbler/metadata-filter/issues/269. Thank you.
