### ISSUE TITLE
Why can't I scrobble from SoundCloud?

### ISSUE THREAD

**Issue by Tamtuza** [web-scrobbler/web-scrobbler#3597]
I tried forcing scrobble in the extension options, but the problem seems to be with the website, not the tracks
![Capture](https://user-images.githubusercontent.com/1956854/226693735-d3d075b9-f0f6-4a5f-bd3f-1c6dca9597cd.PNG)

**Comment by yayuyokitano** [comment]
Can you link the URL you are trying to scrobble from?

**Comment by Tamtuza** [comment]
It seems to have been a momentary glitch, as I had tested several links and none worked.
I came back now and they all work. I'll close the issue, but thank you very much for your attention.
