### ISSUE TITLE
Scrobble didn't count

### ISSUE THREAD

**Issue by meonguyen18** [web-scrobbler/web-scrobbler#3598]
**Describe the bug**
I used Web Scrobbler (Chrome) for a long time to count my scrobbles on Spotify, but these days it didn't work smoothly. When the song was played half, the icon of Web Scrobbler turned from green to yellow then the song wasn't scrobbled. I try to connect then reconnect, delete then redownload so many times in a hopeless way, it was work sometimes but the problem was still happen for the next time and I just don't know what was wrong.

**Expected behavior**
I clearly want to know what was the problem to fix it.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: Web Scrobbler (2.88.1)

**Comment by yayuyokitano** [comment]
Do other third party scrobblers work? You can try open scrobbler pretty easily if you need to test.
The most common cause of this issue is that you have hit the rate limit for how many scrobbles you can do in a given time period.
In last.fm, this limit is around 3000 scrobbles per day.
Could this be the case?

**Comment by meonguyen18** [comment]
The limit 3000 scrobble per day is for 1 spotify account or 1 last.fm account because in the past, my scrobble passed 4000 times/day, if I sign up another last.fm account, will it work? One more question, when is the reset time?

Thank you for replying me.

**Comment by yayuyokitano** [comment]
The limit is for 1 last.fm account. However note that official scrobblers (so official lastfm applications, lastfm website, official spotify connection, etc) ignore the limit and scrobble anyway. We cannot do this.

i’m not sure how useful it is, but yes, a different lastfm account would not be bound by the same limit.

I’m not sure how resetting works, I assume it goes by number of scrobbles done in the past 24 hours, but I never checked.
