### ISSUE TITLE
Now playing notifications not showing (Firefox)

### ISSUE THREAD

**Issue by robinmetral** [web-scrobbler/web-scrobbler#3600]
**Describe the bug**
I'm not seeing "now playing" notifications, despite the option being enabled.

**How to reproduce**
1. Install addon on Firefox 111
2. Make sure "now playing notifications" option is enabled
3. Play tracks
4. Notice that notofications are not showing

**Expected behavior**
Notifications shown

**Screenshots**
n/a

**Debug logs**
Happy to provide if this is not something obvious I'm missing

**Environment (please complete the following information)**
-   OS: macOS Ventura 13.2.1
-   Browser: Firefox 111
-   Extension version: 2.88.1 (latest at time of writing)

**Additional context**
I suspect that this might not be an actual bug, but me missing some kind of permissions/option. But I have pretty standard Firefox settings, so this might also be affecting others. Tried to look through the issues but couldn't find anything. Apologies if this is documented somewhere already!

Thanks a lot for the great extension!

**Comment by yayuyokitano** [comment]
Hello, thank you for reporting!

First of all, did you verify that firefox has permission to show notifications in the macOS settings?

If yes, could you right click the extension icon, hit manage extension, and click permissions, and see if it has the display notifications permission enabled?

**Comment by robinmetral** [comment]
<img width="487" alt="Notifications not enabled for Firefox on macOS" src="https://user-images.githubusercontent.com/35560568/227336563-03afff2c-42cf-447b-92cc-2784d6f90593.png">

🤦 I didn't think to check that at all

Sorry about this, and thank you for the quick help!
