### ISSUE TITLE
Beatbump is broken again (play-icon-name is diffrent)

### ISSUE THREAD

**Issue by Jan9103** [web-scrobbler/web-scrobbler#3601]
**Describe the bug**

The BeatBump connector broke again.  

The issue: `beatbump.js:26
```js
return document.querySelector('.player-btn.player-title svg use').href.baseVal.replace(/.*\//, '') === 'icons-9852f1b5.svg#pause';
```

the webpage:
```html
<div class="player-btn player-title svelte-18v3qqe">
  <svg xmlns="http://www.w3.org/2000/svg" focusable="false" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="width: 2em; height:2em; ; transition: stroke linear 50ms;" viewBox="0 0 24 24" class="svelte-17872hf">
    <use href="http://127.0.0.1:20061/_app/immutable/assets/icons-b750f4e7.svg#pause">
    </use>
  </svg>
</div>
```

`icons-9852f1b5.svg#pause` does not match `icons-b750f4e7.svg#pause`.

since beatbump has been flaky for some time i would suggest to just use the `pause` and not the filename (untested):
```diff
- return document.querySelector('.player-btn.player-title svg use').href.baseVal.replace(/.*\//, '') === 'icons-9852f1b5.svg#pause';
+ return document.querySelector('.player-btn.player-title svg use').href.baseVal.replace(/.*#/, '') === 'pause';
```

**How to reproduce**

1. Go to beatbump.ml or a local instance
2. Play a song
3. *it does not recoggnise it*
4. Right-click on the play-button -> inspect
5.  compare the code expectation with reality

**Expected behavior**

it should recognise the playing song (and not think it stopped)

**Screenshots**

<https://0x0.st/s/LvNI_DmD1nkzuTkF3HiAOg/HozE.png> (no real additional info; the errors can be ignored . theyre independent from the issue)

**Debug logs**

It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: NixOS 23.05.20230319.60c1d71
-   Browser: Firefox 111.0
-   Extension version: 2.88.1

**Additional context**

**Comment by snuffyDev** [comment]
Hey! Beatbump dev here, although this issue is closed I figured if anyone sees this it might help. The file names are hashed at build time, which means they will be unreliable targets.

I’m going to make it easier though very soon!
