### ISSUE TITLE
Web Scrobbler scrobbles vtuber clips but not actual music

### ISSUE THREAD

**Issue by RogueLynx96** [web-scrobbler/web-scrobbler#3609]
other YouTube videos don't pose this problem, but if i am watching a vtuber clip, Web Scrobbler will always without fail scrobble it.

1. Search for either "nijisanji clips" or "hololive clips" on YouTube
2. Click on ANY of the videos and wait for a maximum of 20 seconds
3. Web Scrobbler WILL scrobble it

on the other hand, Web Scrobbler refuses to scrobble actual music from the YouTube channel [Heroes Orchestra](https://www.youtube.com/@HeroesOrchestra). even though it did scrobble 3 videos from this channel on 4th March this year, it doesn't scrobble any others, and it now doesn't even scrobble the 3 that it did scrobble before.

<details>
  <summary>Debug log</summary>
  Here is the content of debug log: ``` storage.Options = {
  "disabledConnectors": "[hidden]",
  "forceRecognize": true,
  "scrobbleEditedTracksOnly": false,
  "scrobblePercent": 50,
  "scrobblePodcasts": true,
  "scrobbleRecognizedTracks": false,
  "useNotifications": true,
  "useUnrecognizedSongNotifications": true
}
wrapper.js:74 storage.Connectors = {
  "YouTube": {
    "enableGetTrackInfoFromYtMusic": false,
    "scrobbleEntertainmentOnly": true,
    "scrobbleMusicOnly": true,
    "scrobbleMusicRecognisedOnly": false
  }
}
wrapper.js:74 storage.ConnectorsOverrideOptions = {}
wrapper.js:74 storage.LastFM = {
  "sessionID": "********************************",
  "sessionName": "***********"
}
wrapper.js:74 storage.LibreFM = {}
wrapper.js:74 storage.ListenBrainz = {}
wrapper.js:74 storage.Maloja = {}
wrapper.js:74 storage.LocalCache = {}
wrapper.js:74 storage.Core = {
  "appVersion": "2.89.0"
}
scrobble-service.js:69 Bind Last.fm scrobbler
scrobble-service.js:55 Unable to bind Libre.fm
bindAllScrobblers @ scrobble-service.js:55
scrobble-service.js:55 Unable to bind ListenBrainz
bindAllScrobblers @ scrobble-service.js:55
scrobble-service.js:55 Unable to bind Maloja
bindAllScrobblers @ scrobble-service.js:55
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152309: Created controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152313: Created controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152316: Created controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152319: Created controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152322: Created controller for YouTube connector
util.js:40 Tab 881152313: New song detected: {
  "track": "sama",
  "artist": "This is the result of hang out with Rosemi",
  "album": null,
  "albumArtist": null,
  "uniqueID": "N53mvCPETGs",
  "duration": 126,
  "currentTime": 1,
  "isPlaying": true,
  "trackArt": null,
  "isPodcast": false,
  "originUrl": "https://youtu.be/N53mvCPETGs"
}
scrobble-service.js:97 Send "get info" request: 1
util.js:40 Last.fm: track.getinfo response:
{
  "error": 6,
  "message": "Track not found",
  "links": []
}
scrobble-service.js:101 Unable to get song info from Last.fm
(anonymous) @ scrobble-service.js:101
coverartarchive.js:35 Found album artwork via MusicBrainz
util.js:40 Tab 881152313: Song finished processing: {
  "parsed": {
    "track": "sama",
    "artist": "This is the result of hang out with Rosemi",
    "album": null,
    "albumArtist": null,
    "uniqueID": "N53mvCPETGs",
    "duration": 126,
    "currentTime": 7,
    "isPlaying": true,
    "trackArt": null,
    "isPodcast": false,
    "originUrl": "https://youtu.be/N53mvCPETGs"
  },
  "processed": {
    "track": null,
    "album": null,
    "artist": null,
    "albumArtist": null,
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  },
  "metadata": {
    "startTimestamp": 1680007522,
    "label": "YouTube",
    "trackArtUrl": "http://coverartarchive.org/release/af6c5244-d4c8-4ee9-ac4b-b2bfb4f54ba4/front-500"
  },
  "connectorLabel": "YouTube"
}
util.js:40 Tab 881152313: The song will be scrobbled in 57 seconds
util.js:40 Tab 881152313: The song will be repeated in 126 seconds
scrobble-service.js:113 Send "now playing" request: 1
util.js:40 Last.fm: track.updatenowplaying response:
{
  "nowplaying": {
    "artist": {
      "corrected": "0",
      "#text": "This is the result of hang out with Rosemi"
    },
    "track": {
      "corrected": "0",
      "#text": "sama"
    },
    "ignoredMessage": {
      "code": "0",
      "#text": ""
    },
    "albumArtist": {
      "corrected": "0",
      "#text": ""
    },
    "album": {
      "corrected": "0",
      "#text": ""
    }
  }
}
util.js:40 Tab 881152313: Song set as now playing
util.js:40 Tab 881152313: Remove controller for YouTube connector
util.js:40 Tab 881152316: Remove controller for YouTube connector
util.js:40 Tab 881152319: Remove controller for YouTube connector
util.js:40 Tab 881152322: New song detected: {
  "track": "Ollie can't resist laughing at Pekora's Gatling Cannon",
  "artist": "Karl's Clips",
  "album": null,
  "albumArtist": null,
  "uniqueID": "Dj8bwqUrOsM",
  "duration": 100,
  "currentTime": 1,
  "isPlaying": true,
  "trackArt": null,
  "isPodcast": false,
  "originUrl": "https://youtu.be/Dj8bwqUrOsM"
}
scrobble-service.js:97 Send "get info" request: 1
util.js:40 Last.fm: track.getinfo response:
{
  "error": 6,
  "message": "Track not found",
  "links": []
}
scrobble-service.js:101 Unable to get song info from Last.fm
(anonymous) @ scrobble-service.js:101
coverartarchive.js:35 Found album artwork via MusicBrainz
util.js:40 Tab 881152322: Song finished processing: {
  "parsed": {
    "track": "Ollie can't resist laughing at Pekora's Gatling Cannon",
    "artist": "Karl's Clips",
    "album": null,
    "albumArtist": null,
    "uniqueID": "Dj8bwqUrOsM",
    "duration": 100,
    "currentTime": 4,
    "isPlaying": true,
    "trackArt": null,
    "isPodcast": false,
    "originUrl": "https://youtu.be/Dj8bwqUrOsM"
  },
  "processed": {
    "track": null,
    "album": null,
    "artist": null,
    "albumArtist": null,
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": false
  },
  "metadata": {
    "startTimestamp": 1680007663,
    "label": "YouTube",
    "trackArtUrl": "http://coverartarchive.org/release/84803506-a9d4-44f9-8b57-3e098be7f70d/front-500"
  },
  "connectorLabel": "YouTube"
}
util.js:40 Tab 881152322: The song will be scrobbled in 47 seconds
util.js:40 Tab 881152322: The song will be repeated in 100 seconds
scrobble-service.js:113 Send "now playing" request: 1
util.js:40 Last.fm: track.updatenowplaying response:
{
  "nowplaying": {
    "artist": {
      "corrected": "0",
      "#text": "Karl's Clips"
    },
    "track": {
      "corrected": "0",
      "#text": "Ollie can't resist laughing at Pekora's Gatling Cannon"
    },
    "ignoredMessage": {
      "code": "0",
      "#text": ""
    },
    "albumArtist": {
      "corrected": "0",
      "#text": ""
    },
    "album": {
      "corrected": "0",
      "#text": ""
    }
  }
}
util.js:40 Tab 881152322: Song set as now playing
util.js:40 Tab 881152322: Remove controller for YouTube connector
util.js:40 Tab 881152309: Remove controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152337: Created controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152335: Created controller for YouTube connector
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152339: Created controller for YouTube connector
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152341: Created controller for YouTube connector
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152338: Created controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
2inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152340: Created controller for YouTube connector
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152343: Created controller for YouTube connector
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/filter.js
inject.js:52 Injecting vendor/jquery.min.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting vendor/browser-polyfill.min.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/util.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152336: Created controller for YouTube connector
inject.js:52 Injecting core/content/reactor.js
inject.js:52 Injecting core/content/connector.js
inject.js:52 Injecting connectors/youtube.js
inject.js:52 Injecting core/content/starter.js
util.js:40 Tab 881152342: Created controller for YouTube connector
util.js:40 Tab 881152335: Remove controller for YouTube connector
util.js:40 Tab 881152336: Remove controller for YouTube connector
util.js:40 Tab 881152337: Remove controller for YouTube connector
util.js:40 Tab 881152338: Remove controller for YouTube connector
util.js:40 Tab 881152339: Remove controller for YouTube connector
util.js:40 Tab 881152340: Remove controller for YouTube connector
util.js:40 Tab 881152341: Remove controller for YouTube connector
util.js:40 Tab 881152342: Remove controller for YouTube connector
util.js:40 Tab 881152343: Remove controller for YouTube connector
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/browser-polyfill.min.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://hhinaapppaileiechjoiifaancjggfjm/vendor/md5.min.js.map: System error: net::ERR_FILE_NOT_FOUND ```
</details>

Environment

-   Windows 10 Pro (64-bit)
-   Chrome 111.0.5563.111 (Official Build) (64-bit)
-   Extension version: v2.89.0

**Comment by jaccarmac** [comment]
These issues most often have to do with the way YouTube categories work. We don't have control over those categories and they are very fuzzy distinctions, so if you have "only Music" or "only Entertainment" enabled in the options, try unchecking both boxes so the scrobbler attempts to scrobble every video and see if the issue persists.

The vtuber clips seem to contain syntax that we treat as artist/track separators, so without more information we can't automatically exclude them. If there's a way to filter out those clips without false positives, I'd consider adding such code to the YouTube connector.

YouTube is one of the dirtiest data sources for scrobbling, and there's only so much we can do at the DOM level.

**Comment by RogueLynx96** [comment]
> These issues most often have to do with the way YouTube categories work. We don't have control over those categories and they are very fuzzy distinctions, so if you have "only Music" or "only Entertainment" enabled in the options, try unchecking both boxes so the scrobbler attempts to scrobble every video and see if the issue persists.
> 
> The vtuber clips seem to contain syntax that we treat as artist/track separators, so without more information we can't automatically exclude them. If there's a way to filter out those clips without false positives, I'd consider adding such code to the YouTube connector.
> 
> YouTube is one of the dirtiest data sources for scrobbling, and there's only so much we can do at the DOM level.

unchecked both "Scrobble videos from "Music" category" and "Scrobble videos from "Entertainment" category" and it did finally scrobble the artist i was trying to scrobble. thank you.
