### ISSUE TITLE
Document adblocker interactions 

### ISSUE THREAD

**Issue by inverse** [web-scrobbler/web-scrobbler#3659]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Some adblock lists block scrobbling support

https://secure.fanboy.co.nz/fanboy-annoyance.txt

We should document adblocker interactions in the FAQ section and potentially the popup to guide users to a solution

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yayuyokitano** [comment]
Added to discord FAQ, so that’s a start

**Comment by inverse** [comment]
Added to a new Wiki page - https://github.com/web-scrobbler/web-scrobbler/wiki/Troubleshooting

Perhaps we could consolidate the efforts in a single place and link out?

**Comment by yayuyokitano** [comment]
Outdated
