### ISSUE TITLE
There is no possibility to log into any social network

### ISSUE THREAD

**Issue by dkann** [web-scrobbler/web-scrobbler#3701]
**Describe the bug**
I got unexpectedly logged out of the app 14 hours ago.

**How to reproduce**
1. Go to 'Preference'
2. Click on 'log in' button of any social network (i personally use last.fm)

**Expected behavior**
Log in interface opens.

**Actual result**
Nothing changes.

**Screenshots**
![lastfm_loginto_](https://user-images.githubusercontent.com/10476998/236611451-aa70c373-f4ae-4813-8b65-84c0d87559c8.png)

**Debug logs**
IndexedDB UnknownErr: ActorsParent.cpp:565
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. [ExtensionStorageIDB.jsm:824](resource://gre/modules/ExtensionStorageIDB.jsm)
IndexedDB UnknownErr: ActorsParent.cpp:565
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. [ExtensionStorageIDB.jsm:824](resource://gre/modules/ExtensionStorageIDB.jsm)
Error: An unexpected error occurred undefined

**Environment (please complete the following information)**
-   OS: LinuxMX 19
-   Browser: Firefox
-   Extension version: 2.89.0

**Additional context**
critical :)

**Comment by yayuyokitano** [comment]
While I’m not gonna say anything for sure, at first glance this sounds like a firefox issue, and not a web scrobbler issue.

Are you using dev preview or even building firefox yourself, or are you just running the official stable release and nothing else?

**Comment by dkann** [comment]
there is some more additional information on the issue. 
It might happen if you're the type of person disposed to configure your system right after its installation and never more.
While the plugin was down I found a couple of solutions. 
First, I realized i hadn't upgraded my software for a really long time and immediately did it. 
Oh, skies web-scrobbler is back to work. 
let's see what might happen to it after system reboot?
Unfourtunately, the issue remains the same: there is no interface to log into social network, so I installed Chrome.

**Comment by yayuyokitano** [comment]
Gotcha, not an optimal solution, but I guess it works.
Since this issue seems like it is connected to firefox and is probably not something we can workaround with our own code, I'll be closing this issue unless something else pops up that connects it to web scrobbler specifically.
