### ISSUE TITLE
(YouTube) Missing scrobbling (at least) one song from an album

### ISSUE THREAD

**Issue by medavox** [web-scrobbler/web-scrobbler#3718]
**Describe the bug**
I've just noticed after listening to this song on youtube a lot over the last month, that not one scrobble is recorded for it :(
Most of my plays are from one machine, but in that time I've definitely played it on other machines/browsers (which also have this extension installed), and they haven't scrobbled either.

What's even stranger is that the songs immediately before and after it from the album *have* been scrobbled, which is partly why I didn't notice.

I've just played it directly from last.fm using an embedded youtube video, and that scrobbled (for the first time).

**How to reproduce**

This is the song that isn't being scrobbled: https://www.youtube.com/watch?v=lLdGlDVg9So

And this is the album https://www.youtube.com/watch?v=tqVxd57H-cA&list=PLfsbuQF4YPohXa4nvblxJQX-_ptryBAle

**Debug logs**
I refreshed the page then played the song, but the logs were pretty bare.

<details>
  <summary>Debug log</summary>
```
15:47:07.217 Injecting vendor/filter.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.252 Injecting vendor/jquery.min.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.260 Injecting vendor/browser-polyfill.min.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.267 Injecting core/content/util.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.273 Injecting core/content/reactor.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.274 Injecting core/content/connector.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.275 Injecting connectors/youtube.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.278 Injecting core/content/starter.js [inject.js:52:12](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/browser/inject.js)
15:47:07.281 Tab 1056: Created controller for YouTube connector [util.js:40:10](moz-extension://f8417cd6-02da-48b3-a93c-24e580149900/core/background/util/util.js)
```
</details>

**Environment (please complete the following information)**
-   OS: MacOS Monterey 12.6
-   Browser: Firefox 112.0.2
-   Extension version: 2.89.0

**Additional context**

**Comment by yayuyokitano** [comment]
I notice that the song that isn't scrobbling is labeled as people and blogs, while others seem to be labeled as music.

Do you happen to have "Scrobble only videos from "music" category" enabled?

**Comment by yayuyokitano** [comment]
Yeah its unfortunate, the categories are set by the uploader so i guess they made a mistake.
AFAIK web scrobbler only prints the video category the first time a song is played.

**Comment by medavox** [comment]
I prefer not to scrobble general videos, as the chapters of video essays tend to flood my play history. 

I might make a feature request for per-channel block/allow lists

**Comment by medavox** [comment]
Anyway, thanks for the extension, and the prompt response :)
