### ISSUE TITLE
Service error

### ISSUE THREAD

**Issue by ThatNighaD6** [web-scrobbler/web-scrobbler#3744]
**Describe the bug**
Doesn't scrobble music, says 

**How to reproduce**
1. Go to 'YouTube'
2. Click on 'Any song'
4. See error "Service error
Looks like something went wrong while scrobbling the music. Please open the options page and try to reauthenticate with services. If reauthentication doesn't help, and you still see this message, please create [a new issue](https://github.com/web-scrobbler/web-scrobbler/issues) at the GitHub project page."

**Expected behavior**

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Opera
-   Extension version: current

![image_2023-05-20_194141307](https://github.com/web-scrobbler/web-scrobbler/assets/134174064/84f3c54f-93b8-4d43-bfde-1df8c047ce8c)

**Comment by yayuyokitano** [comment]
This is usually not a web scrobbler error, though it is possible.

Before going into troubleshooting, the most common cause of service errors is that the user has been rate limited. For lastfm, the ratelimit is something along the lines of 3000 scrobbles every 24 hours per account (but doesnt seem to always be completely precise). This is a global limit that applies even if the scrobbles were made using a different scrobbler.

Have you scrobbled around 3000 times in roughly the past 24 hours? If so, that’s probably the cause and you just have to wait, and not import as many songs at once in the future.

If it cannot be that, please try the following troubleshooting steps:

1. Go to settings, sign out of your accounts, and sign back in. Restart your browser to ensure everything refreshes and try to scrobble.
2. If it still errors, try to scrobble using openscrobbler and see if that works. If you are able to scrobble using openscrobbler, it is a web scrobbler issue, if you cannot scrobble using openscrobbler it is not a web scrobbler issue.

Are you able to go through the troubleshooting steps?
