### ISSUE TITLE
service error

### ISSUE THREAD

**Issue by hheun2805** [web-scrobbler/web-scrobbler#3745]
**Describe the bug**

**How to reproduce**
4. Service error

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by inverse** [comment]
Sounds related to #3744 - I'm guessing Last.fm API was down
