### ISSUE TITLE
3.0.5 not scrobbling 

### ISSUE THREAD

**Issue by Enferlain** [web-scrobbler/web-scrobbler#3768]
I updated to the latest version and it doesn't work for some reason

Default result on Youtube

![image](https://github.com/web-scrobbler/web-scrobbler/assets/15861396/e53c25f2-6252-4d7e-ba0b-4246964e3616)

If I disable and reenable the extension

![image](https://github.com/web-scrobbler/web-scrobbler/assets/15861396/686adc57-779f-4323-a53f-6f8762018c89)

Reconnecting to last.fm doesn't solve it, and neither does removing and reinstalling.

**Comment by Enferlain** [comment]
Chrome 113.0.5672.127

![image](https://github.com/web-scrobbler/web-scrobbler/assets/15861396/c183e90f-c39e-4b03-8def-15fe4d0a3ade)

**Comment by 0edit** [comment]
Same here. Well, it works on Spotify for me but not on Bandcamp and other sites.  Kudos for updating the app in a timely minor though!

**Comment by yayuyokitano** [comment]
The first error was probably connected to the update, and I don't _think_ it should reoccur.
The service error is odd and I cannot repro it. Is it still occuring?
Could you copy-paste the complete logs from refreshing the site until trying to play a song and getting service error?
You can hide the storage.LocalCache = [...] one if its too long, but I need to see some more stuff relating to initialization.

**Comment by Enferlain** [comment]
https://pastebin.com/raw/52H63D1G

I opened the logs and then pressed f5 on the youtube page, these are the logs

**Comment by yayuyokitano** [comment]
Could you provide content logs from the website as well? A lot of web scrobbler logs are there.
Also, could you verify at the top of the service worker log if there is anything set to storage.LastFM or whichever other scrobbling service you use? It doesn't seem to be included in your pastebin.

**Comment by Enferlain** [comment]
I'm using last.fm

Logs from console on youtube page, hopefully no leaks or anything

https://pastebin.com/raw/Bm1uFBYb

**Comment by yayuyokitano** [comment]
Well the bad news is there is a leak, please ASAP disconnect web scrobbler here https://www.last.fm/settings/applications
You will have to then sign out in web scrobbler itself and reconnect, but please disconnect in last.fm first to be safe.

The good news is it's pretty clear what is causing this. It's caused by some outside factor blocking the request.
I think more than likely this is just an adblocker list blocking the connection to audioscrobbler, which is easily fixable by whitelisting ws.audioscrobbler.com and/or removing ws.audioscrobbler.com from any blocklists. [fanboy's annoyance list](https://secure.fanboy.co.nz/fanboy-annoyance.txt) is one example of an adblocking list that blocks ws.audioscrobbler.com

**Comment by 0edit** [comment]
Well, maybe I jumped the gun too soon. It claims it's scrobbling, but then doesn't scrobble the tracks.  

Logs: [](https://pastebin.com/nPri6QsA)

**Comment by Enferlain** [comment]
@yayuyokitano Thanks. I disabled ublock extension and it seems like it scrobbles without being blocked, but the extension still shows the error icon instead of a scrobbling icon. I also tried adding ws.audioscrobbler.com to the trusted sites but that doesn't seem to help for some reason

**Comment by yayuyokitano** [comment]
> @yayuyokitano Thanks. I disabled ublock extension and it seems like it scrobbles without being blocked, but the extension still shows the error icon instead of a scrobbling icon. I also tried adding ws.audioscrobbler.com to the trusted sites but that doesn't seem to help for some reason

I think this is a result of the way notifications work in V3 currently.
Each tab has a state associated with it, and tabs with error states are prioritized over other tabs for display in the popup.
Just close any tabs where you got errors previously, and you should no longer be getting the error popup I think.

**Comment by yayuyokitano** [comment]
> Well, maybe I jumped the gun too soon. It claims it's scrobbling, but then doesn't scrobble the tracks.
> 
> Logs: https://pastebin.com/nPri6QsA

I see it seems to be spotify, I suspect it's a connector issue as there were issues with spotify prior to V3.
I can't reproduce it though currently.
Could you open a new issue, it's unrelated to this.

**Comment by Enferlain** [comment]
Hmm, any idea what else could be blocking it?

This is how it looks like in the filter ||ws.audioscrobbler.com^$third-party,domain=~play.google.com|~spotify.com

As for the notification it's as you said 
![image](https://github.com/web-scrobbler/web-scrobbler/assets/15861396/c00bd9a8-a06d-4d6a-9c82-4668f671b7d0)

**Comment by 0edit** [comment]
> > Well, maybe I jumped the gun too soon. It claims it's scrobbling, but then doesn't scrobble the tracks.
> > Logs: https://pastebin.com/nPri6QsA
> 
> I see it seems to be spotify, I suspect it's a connector issue as there were issues with spotify prior to V3. I can't reproduce it though currently. Could you open a new issue, it's unrelated to this.

Okay just did this! Thanks!

Also just to be clear, the leak you were speaking of earlier, that doesn't affect me? Since my issue is unrelated to this current one. Apologies. I'm kinda an idiot when it comes to this stuff. Trying my best though!

**Comment by yayuyokitano** [comment]
> Hmm, any idea what else could be blocking it?
> 
> This is how it looks like in the filter ||ws.audioscrobbler.com^$third-party,domain=~play.google.com|~spotify.com
> 
> As for the notification it's as you said ![image](https://user-images.githubusercontent.com/15861396/241401834-c00bd9a8-a06d-4d6a-9c82-4668f671b7d0.png)

Regarding fanboy list blocking V3 but not V2, this is because V3 sends requests from the content script, while V2 sent from background script, which ignores adblockers.

Adding to trusted sites doesn't really help, since you're not actually on the site when it happens.
Add `@@ws.audioscrobbler.com` to a new line in "My filters" to fix. You will need to reload the page you're playing music from after saving in ublock.

**Comment by yayuyokitano** [comment]
> > > Well, maybe I jumped the gun too soon. It claims it's scrobbling, but then doesn't scrobble the tracks.
> > > Logs: https://pastebin.com/nPri6QsA
> > 
> > 
> > I see it seems to be spotify, I suspect it's a connector issue as there were issues with spotify prior to V3. I can't reproduce it though currently. Could you open a new issue, it's unrelated to this.
> 
> Okay just did this! Thanks!
> 
> Also just to be clear, the leak you were speaking of earlier, that doesn't affect me? Since my issue is unrelated to this current one. Apologies. I'm kinda an idiot when it comes to this stuff. Trying my best though!

Cool, we'll talk further there then. For now the leak concern is a valid concern, but I see no leak for you

The leak in previous case was caused by the fact that adblocker was blocking the request

**Comment by Enferlain** [comment]
Yep, works now, thanks!
