### ISSUE TITLE
Sirius XM won't scrobble in Google Chrome. Windows 10.

### ISSUE THREAD

**Issue by elpidge** [web-scrobbler/web-scrobbler#3769]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by yayuyokitano** [comment]
What does the extensions say? Does it say website not supported, does it say play some music to get started but then never change, does it say service error, or does it say it's playing as normal but not scrobble?

**Comment by elpidge** [comment]
In most cases this means the site has changed somehow. The change does not have to be visible to user, but means a lot to the extension.

The connector code for this specific website needs to be updated. You can navigate to the [list of issues](https://github.com/web-scrobbler/web-scrobbler/issues) and see if this website is already reported. If it is not, you can submit a new issue describing what's wrong, what's expected behavior and what's happening instead.

**Comment by elpidge** [comment]
Doesn't recognize music is playing anymore. Worked last week.

**Comment by yayuyokitano** [comment]
Understood. I think this is related to V3 update. I'll have a look into it asap

**Comment by terententen** [comment]
Yeah, I must have been running on an older extension. Scrobbling worked for my first song of the day today, about 2 hours ago, then I didn't realize it stopped scrobbling and is now saying "Website is not supported". Probably autoupdated to the latest extension.

**Comment by dmerryman** [comment]
I'm having the same issue on Windows 11. I found a temporary workaround though. It looks like if you select a station, and then click on the thumbnail for it, navigating to https://player.siriusxm.com/now-playing rather than just using the toolbar at the bottom, it starts submitting the tracks again.

**Comment by elpidge** [comment]
I tried your work around, it seems to work on some stations but not others. Deep Tracks won't scrobble but First Wave will. It's weird.

**Comment by yayuyokitano** [comment]
You’ll have to refresh the page for ublock changes to be applied – did you make sure to do this?
Also if youre playing on multiple devices I believe ublock settings are per device, and not synced.

**Comment by yayuyokitano** [comment]
Sorry for previous comment, this was a different issue from what I thought.
As an update we tried to get an account from sirius and failed.
Still planning to get an account and patch this soon.

**Comment by elpidge** [comment]
Thanks so much for your help.

**Comment by terententen** [comment]
I am still experiencing issues with Sirius scrobbles. Seems to be hit or miss all morning... mainly miss. Worked for a few songs then stopped.

**Comment by elpidge** [comment]
> I am still experiencing issues with Sirius scrobbles. Seems to be hit or miss all morning... mainly miss. Worked for a few songs then stopped.

I noticed this yesterday. Would work for awhile and then stop.
