### ISSUE TITLE
Spotify claims to be scrobbling, but does not scrobble my tracks. 

### ISSUE THREAD

**Issue by 0edit** [web-scrobbler/web-scrobbler#3770]
**Describe the bug**
I'll play a song on Spotify and it appears to be scrobbling. However, when the song reaches the half way point, it does not appear as scrobbled. 

**How to reproduce**
1. Go to Spotify web player 
2. Click on the play button to play track. 
3. Track appears to be scrobbling
4.  Reach half way point, does not appear to be scrobbled. 

**Expected behavior**
The track to be scrobbled.

**Debug logs**
https://pastebin.com/nPri6QsA

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 3.0.5

**Comment by yayuyokitano** [comment]
Based on logs I think this might be caused by having duration set to showing remaining time instead of full duration of track, this is an issue from before v3 as well.
Could this be correct?

**Comment by 0edit** [comment]
> Based on logs I think this might be caused by having duration set to showing remaining time instead of full duration of track, this is an issue from before v3 as well. Could this be correct?

I tried fixing the duration before my post in the previous thread. Did nothing. Tried it again just now and seems to have done the trick. Gonna assume when I tried it the first time, I just didn't let the song play long enough. Doh! Seems to be good now though. Thanks again and appreciate you putting up with me!

**Comment by yayuyokitano** [comment]
No worries, thank you for reporting regardless!
