### ISSUE TITLE
Deezer scrobbling not working

### ISSUE THREAD

**Issue by derek-gz** [web-scrobbler/web-scrobbler#3771]
**Describe the bug**
Deezer scrobbling not working

**Expected behavior**
After pressing play on any song, I expected the song data to be shown as it was scrobbling, however, what I got was "Play some music to get started".

**Screenshots**
![Screen Shot 2023-05-27 at 11 52 42](https://github.com/web-scrobbler/web-scrobbler/assets/112263890/0316b632-6449-4d61-b8d6-c76b764f2778)

**Debug logs**
<details>
  <summary>Debug log</summary>
  main.js:3 Error: Could not establish connection. Receiving end does not exist.
    at me (main.js:1:40993)
</details>

**Environment (please complete the following information)**
-   OS: MacOS Catalina 10.15.7
-   Browser: Version 113.0.5672.126 (Official Build)
-   Extension version: [v3.0.5](https://github.com/web-scrobbler/web-scrobbler/releases/tag/v3.0.5)

**Comment by yayuyokitano** [comment]
Found the issue, this is caused by the browser crashing on an export statement in the inject script. Should be an easy fix.

**Comment by yayuyokitano** [comment]
Fix pushed in 3.0.6 which has been deployed and hopefully makes its way to browser soon. Deezer connector still seems to be a little flakey so id love to do some finer work on it soon, but at least it seems to be scrobbling all the songs rn and we have more pressing issues for now

**Comment by derek-gz** [comment]
Is this a new update? I tried removing the extension and downloading it again, but the issue continues. I looks like the version available is still 3.0.5
