### ISSUE TITLE
Web Scrobbler scrobbles edited tracks twice if "Scrobble recognized or edited tracks" option is selected

### ISSUE THREAD

**Issue by Mirika1** [web-scrobbler/web-scrobbler#3772]
**Describe the bug**
When the "Scrobble recognized or edited tracks" option is selected in the Web Scrobbler options, scrobbling an edited track will cause two scrobbles to appear on last.fm. The first scrobble will have the original information, and the second one will have the edited information.

**How to reproduce**
1. Go to the Web Scrobbler options and select the "Scrobble recognized or edited tracks" option
2. Go to open.spotify.com
3. Play a track and edit its information
4. Wait for the track to scrobble
5. Notice there are two scrobbles on last.fm

**Expected behavior**
Only the scrobble with the edited information should appear.

**Environment**
-   OS: Windows 11
-   Browser: Opera
-   Extension version: v3.0.5

**Comment by yayuyokitano** [comment]
Cannot reproduce. Could you provide log of content script as described [here](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension)?
Also just to be sure, could you go through browser extension settings and make sure theres only one instance of web scrobbler?

**Comment by Mirika1** [comment]
There is only one instance of Web Scrobbler.

Here is the log: https://pastebin.com/pdjesqX6.
I'm not sure if I did that right since I've never done it before. Also, while I was getting the log, I found out that this only happens when you let the song finish playing. If you pause the song after it scrobbles, the bug will not occur.

**Comment by yayuyokitano** [comment]
Is this log is for the entire duration from start until both scrobbles have come through? If so that is very odd, because the logs only seem to indicate that a single scrobble request was made by the extension.
Could you try to restart your browser, just to make sure the browser didn't do anything wonky while updating the extension?

**Comment by Mirika1** [comment]
Ok, it turns out this wasn't an issue with Web Scrobbler. I tried playing a track with Web Scrobbler disabled and last.fm scrobbled the track even though I had the Spotify Scrobbling application disconnected on last.fm. I reconnected the application and disconnected it again and that fixed it.

Sorry for wasting your time.

**Comment by yayuyokitano** [comment]
Gotcha, I'm glad you figured it out!
No worries at all, we're here to help!!
