### ISSUE TITLE
Apple Music not scrobbling

### ISSUE THREAD

**Issue by gitmilotic** [web-scrobbler/web-scrobbler#3773]
**Describe the bug**
Apple Music has completely stopped scrobbling since the new update, with it saying it's being scrobbled but never actually scrobbling it. This comes after my previous report #3462 which has never been fixed.

**How to reproduce**
1. Go to Apple Music
2. Play any song
3. Wait for the song to end
4. Check Last.fm
5. See error

**Expected behavior**
The songs I've listened to on Apple Music would all be scrobbled and accounted for.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: v3.0.5

**Comment by yayuyokitano** [comment]
Odd bug. Fixing #3462 was already a very high priority after V3 release, so I will look into this one quickly and probably rewrite the connector.

**Comment by franclecor** [comment]
when will it be able to be fixed? It hasn't worked all afternoon.

**Comment by yayuyokitano** [comment]
I have started working on this issue now, so however long it takes for me to figure it out.

**Comment by yayuyokitano** [comment]
Fix has been published in 3.0.6, which has been pushed to chrome/amo/edge.
When they accept it idk, though chrome accepted v3 in less than a day so hopefully it's fast.
