### ISSUE TITLE
Restore this removed feature?

### ISSUE THREAD

**Issue by nikfiendluvr666** [web-scrobbler/web-scrobbler#3774]
Since the new version of the web scrobbler has been released I've noticed a feature I used to use daily has either been removed or forgotten.

Previously, while editing tracks through the web scrobbler, you could press enter on the keyboard to activate your changes instead of having to click the little check icon. 
I also used to use the tab key to scroll through the artist/track/album sections, but this no longer works as efficiently. There's one or two things that become highlighted before the artist section becomes highlighted (this one I can live with. But in regards to the first missing feature, it is truly frustrating that the enter key function has been removed).

These features made editing tracks far more efficient and I already miss them dearly! Would love if they could make a return

**Comment by yayuyokitano** [comment]
Thank you for reporting, this will definitely be readded!
