### ISSUE TITLE
Deezer connector issue

### ISSUE THREAD

**Issue by Oleg451-tr** [web-scrobbler/web-scrobbler#3786]
**Describe the bug**
Recognition of any track playing on Deezer actually not working.

**How to reproduce**
Go to Deezer
See a gray icon instead of usual 'green note' pictogram when picking, stopping, switching tracks or even refresh page.

**Expected behavior**
Correct Deezer scrobbling as it was in older versions

**Environment**
-   OS: win10, 19042.746
-   Browser: Chrome
-   Extension version:  v3.0.5

**Debug logs**
<details>
  <summary>Debug log</summary>
main.js:3 Error: Could not establish connection. Receiving end does not exist.
    at me (main.js:1:40993)
(anonymous) @ main.js:3
Promise.catch (async)
ss @ main.js:3
as @ main.js:3
await in as (async)
ae @ main.js:3
ns @ main.js:5
await in ns (async)
Pt @ main.js:5
</details>

**Logs of content scripts**
https://pastebin.com/gYbdjkU7

**Comment by yayuyokitano** [comment]
Hi, we already applied a patch in 3.0.6 that should at least help. It is already up in chrome web store. Could you try to get it updated and see if it fixes the problem?

**Comment by Oleg451-tr** [comment]
Great! Now it's fully functioning. Thanks for such a significant update.
![image](https://github.com/web-scrobbler/web-scrobbler/assets/121514702/c6ee9be6-dde4-48f4-8dc7-b0862a51c3bb)

**Comment by yayuyokitano** [comment]
Glad to hear it!
