### ISSUE TITLE
Musify Connector does not work. 

### ISSUE THREAD

**Issue by painchen88** [web-scrobbler/web-scrobbler#3787]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

If I play music via musify, the Icon show me the title but if the title finish the don't appear on last fm. I use the google chrom browser Version 109.0.5414.120 (Offizieller Build) (64-Bit) and Windows 7. Everything was working fine until noon today, but at 23:15 CET it stopped working.

**Comment by painchen88** [comment]
After I disconnected and reconnected it works fine now.

**Comment by yayuyokitano** [comment]
Glad it works! Sorry for late response
