### ISSUE TITLE
"Service error" preventing scrobbles

### ISSUE THREAD

**Issue by malemedusa** [web-scrobbler/web-scrobbler#3790]
<img width="325" alt="Screenshot 2023-05-28 at 1 08 30 AM" src="https://github.com/web-scrobbler/web-scrobbler/assets/134835196/01ab8735-abe8-4739-a817-3fe68ce8f4b6">
this

**Comment by yayuyokitano** [comment]
Possibly connected to certain adblocker filters. Do you have an adblocker installed? If so, try to add `ws.audioscrobbler.com` to your allowlist.
In uBlock origin, this can be done by adding `@@||ws.audioscrobbler.com` under "My filters" in settings.

**Comment by malemedusa** [comment]
> @@||ws.audioscrobbler.com

Oh my gosh! Thank you so much! It worked!!
