### ISSUE TITLE
Web Scrobbler перестал скробблить с Youtube

### ISSUE THREAD

**Issue by Maxim19902501** [web-scrobbler/web-scrobbler#3798]
При просмотре видео, скробблер начинает скробблить трек, но не завершает это. Галочка, что трек из видео заскробблен, не появляется.. Он теперь даже не понимает, что видео закончилось! Исправьте, пожалуйста, эту ошибку при последнем обновлении!!!!!!!!

**Comment by Maxim19902501** [comment]
Дополню своё сообщение: оказывается, Web Scrobbler перестаёт засчитывать те треки, где пришлось редактировать название и исполнителя.

**Comment by yayuyokitano** [comment]
This might be related to #3805

**Comment by yayuyokitano** [comment]
#3805 has been pushed in 3.0.9. Once you receive 3.0.9 update, please see if bug still happening

**Comment by Maxim19902501** [comment]
Thanks to fixing this bug. Now scrobbler is working good.

**Comment by yayuyokitano** [comment]
Glad to hear the issue is solved! Thank you for reporting!
