### ISSUE TITLE
Web Scrobbler doesn't scrobble track if the track is paused and unpaused

### ISSUE THREAD

**Issue by Mirika1** [web-scrobbler/web-scrobbler#3799]
**Describe the bug**
After a track has been scrobbled by Web Scrobbler, playing another track, pausing it, and then unpausing it will cause the track to not be scrobbled.

**How to reproduce**
1. Go to open.spotify.com
2. Play a track and wait for Web Scrobbler to scrobble it
3. Play a different track
4. Pause and unpause that track
5. Wait for the track to finish playing
6. Notice that the track is not scrobbled

**Expected behavior**
The track should be scrobbled.

**Debug logs**
https://pastebin.com/aRK5kGJ3
"fragile" is the track that didn't get scrobbled.

**Environment**
-   OS: Windows 11
-   Browser: Opera, Google Chrome
-   Extension version: v3.0.8

**Comment by Maxim19902501** [comment]
exactly! and after changing the name of the artist and the name of the track this track is not scrobbled. Web Scrobbler even doesn't understand that the track is finished.

**Comment by jetdzhet** [comment]
Exact same thing happens to me since the extension updated

**Comment by yayuyokitano** [comment]
Thank you for reporting! This is fixed and hotfix will be deployed soon
