### ISSUE TITLE
plis how to connect it to youtube and put it to last.fm and then to discord

### ISSUE THREAD

**Issue by Berchis18** [web-scrobbler/web-scrobbler#3800]
can annyone make a vid or just a detailed  of how to do this 
how to connect it to youtube 
then how to to connect youtube to last.fm
then how to connect it to discord

**Comment by yayuyokitano** [comment]
Go to extension settings (open the extension popup and click the cog in the bottom right).

Then you can go to account tab and click sign in on last.fm.

Go through the steps on last.fm and go back to the extension settings. If everything went right you should see your username listed in the settings.

Then you can just go to youtube and use it, you don't need to do any separate connection to youtube.

Web scrobbler cannot connect to discord. However, you can use https://github.com/PvtTyphoon/lfm-rich-presence/releases/tag/3.0.0 to make discord show whatever you're currently playing on last.fm.
