### ISSUE TITLE
Will stop scrobbling after first track if I leave Youtube Music paused for a while.

### ISSUE THREAD

**Issue by radipan** [web-scrobbler/web-scrobbler#3802]
**Describe the bug**
If I play some music on youtube Music and I pause the track and leave it paused for a while then resume, all the following tracks will not scrobble anymore and I have to refresh the page.

**How to reproduce**
1. Go to Youtube Music
2. Play a song
3. Pause it before it reaches its half time.
4. Wait 10 minutes
5. Continue
6. Track will scrobble but the next track that comes from Autoplay will not

**Expected behavior**
Normally it should scrobble all the tracks. If I check last FM while listening, the tracks appear as 'scrobbling', however, the song ends and there is no scrobble.

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows 10)
-   Browser: (Opera GX)
-   Extension version: Version 3.0.8

**Additional context**
I am not 100% that the pausing, and leaving the music paused for a while is what causes the issue, it might be from something else as well, like windows locking up.

**Comment by yayuyokitano** [comment]
Thank you for reporting! This is fixed and hotfix will be deployed soon
