### ISSUE TITLE
the web-scrobbler does not track and does not recognise the music  please wsolve this problem...

### ISSUE THREAD

**Issue by cocobear21** [web-scrobbler/web-scrobbler#3806]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by yayuyokitano** [comment]
What website(s) are you using, and what does the extension popup say?

**Comment by bannackk** [comment]
> What website(s) are you using, and what does the extension popup say?

I'm using youtube music and it's not scrobbling

**Comment by cocobear21** [comment]
Thank u so much for the response..but the web scrobbler now is okay already
and it's working fine...thank u have a wonderful day

**Comment by greedoe** [comment]
having the same issue with Amazon Music. I have open scrobbler open in another window scrobbling what I'm listening to, even though the webscrobbler icon is receiving the information (as I can see it and edit it), it just doesn't seem to be passed on to Last.fm

**Comment by yayuyokitano** [comment]
Sorry for getting back to this slow.
Original issue seems to be solved.
@greedoe and @bannackk if you are still experiencing issues on 3.0.10 please open new issues
