### ISSUE TITLE
asap  please resolve this issue as soon as possible   ...the web scrobbler does not recognize the extension of youtube....

### ISSUE THREAD

**Issue by cocobear21** [web-scrobbler/web-scrobbler#3807]
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by yayuyokitano** [comment]
Cannot reproduce.
A new update just rolled out, the extension might have initialized incorrectly.
Could you try refreshing the page? If that doesn't work, could you try restarting the browser, and seeing if the problem persists.

**Comment by cocobear21** [comment]
It's working now..thank you so much for your help

**Comment by yayuyokitano** [comment]
Glad to hear it!

**Comment by cocobear21** [comment]
Thank you for your help!
