### ISSUE TITLE
It seems the version on Edge addons site is outdated

### ISSUE THREAD

**Issue by youthlin** [web-scrobbler/web-scrobbler#3809]
https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc
<img width="1610" alt="image" src="https://github.com/web-scrobbler/web-scrobbler/assets/6056413/3f64f722-ce7b-4d9c-ae45-a40df9682c4d">

the version is 2.82.1, updated at 2022-12-11

however the deploy action run complete with no errors: https://github.com/web-scrobbler/web-scrobbler/actions/runs/5106479493/jobs/9178704106

**Comment by inverse** [comment]
It's most likely in review with Microsoft. Unfortunately we don't all have access to the backend for this to check the status.
