### ISSUE TITLE
Deezer scrobbling not recognizing the second track in queue and related issues

### ISSUE THREAD

**Issue by derek-gz** [web-scrobbler/web-scrobbler#3811]
**Describe the bug**
If there are say 3 tracks in the queue, first track usually gets scrobbled normally, but web-scrobbler doesn't recognize the second track (sometimes that causes a duplicated scrobble for the first track). When the third track starts, it thinks it's the second track. It's usually scrobbling one track behind, after double scrobbling the first. That sometimes also causes scrobbles to be missed (depending on song lengths). Pausing a song and then clicking play before the 50% mark usually helps the scrobbler recognize that song.

**How to reproduce**
1. Go to 'deezer.com'
2. Click on 'any playlist or album'
3. Wait for 3 songs to play and see which ones got scrobbled

**Expected behavior**
All songs should be scrobbled at their own 50% mark, without delayed, duplicate or missed scrobbles.

**Environment (please complete the following information)**
OS: MacOS Catalina 10.15.7
Browser: Google Chrome Version 113.0.5672.126 (Official Build)
Extension version: [v3.0.9](https://github.com/web-scrobbler/web-scrobbler/releases/tag/v3.0.9)

**Comment by Tscharbo** [comment]
Since today the Web Scrobbler has a new look with me, and since then this error also exists with me!

**Comment by yayuyokitano** [comment]
Thank you for reporting and apologies for not getting back to you sooner.
This is fixed by #3838 to be pushed in the next version. I imagine this won't be very long.

**Comment by yayuyokitano** [comment]
The update containing this patch (3.0.11) is being reviewed by mozilla and is not yet out on the firefox store.

**Comment by Tscharbo** [comment]
Thank You! Then i must wait...i hope not so long!
