### ISSUE TITLE
[AccuRadio] - Web Scrobbler doesn't stop scrobbling tracks with long titles

### ISSUE THREAD

**Issue by Rostov84** [web-scrobbler/web-scrobbler#3812]
**Describe the bug**

In general, Web Scrobbler properly scrobbles tracks from all Accu Radio channels. But after updating the extension to version 3.0.9
for tracks from channels in the "classical music" category (https://www.accuradio.com/classical/) Web Scrobbler starts to scrobble (green note icon appears), but does not complete the scrobble process (green tick icon does not appear) . I suppose this is due to the song titles being too long. For this reason, such songs are not listed on the last.fm list.

**Environment (please complete the following information)**
-   OS: Windows 7 Home Premium SP1 (x64)
-   Browser: Google Chrome 109.0.5414.120 (x64)
-   Extension version: 3.0.9

**Comment by yayuyokitano** [comment]
Hi, could you give a specific example of a track that does not work? I do know that there is a limit of 500 bytes per field from last.fm's side, idk if you're hitting that though.

**Comment by Rostov84** [comment]
For example:

Amadeus Quartet - String Quartet in D major, KV 499 "Hoffmeister": 4th movement

**Comment by inverse** [comment]
This connector currently doesnt handle the duration of tracks. Could it be something to do with this not existing causing scrobble issues?

**Comment by yayuyokitano** [comment]
Very possible. The name sure isn't long enough to be causing any issues with lastfm

**Comment by inverse** [comment]
I just patched the connector to pick up this information and it scrobbles correctly. 

We should def handle this case - wonder what changed compared to v2 for this :/

**Comment by yayuyokitano** [comment]
Think I found the issue, some excessively aggressive type checking

**Comment by Rostov84** [comment]
I just noticed that the same problem also applies to stations:

https://www.di.fm/
https://www.rockradio.com/
https://www.jazzradio.com/
https://www.classicalradio.com/
https://www.radiotunes.com/
https://www.zenradio.com/

However, while on classic Accu Radio channels the problem applies to all songs, on the above-mentioned channels scrobbling of only selected songs is not completed.

**Comment by yayuyokitano** [comment]
I suspect these might all be fixed by #3815

**Comment by inverse** [comment]
Published a release just now - it's pending review from Google
