### ISSUE TITLE
Spotify webplayer not working anymore

### ISSUE THREAD

**Issue by s7enkoec** [web-scrobbler/web-scrobbler#3819]
**Describe the bug**
The Spotify webplayer does not scrobble anymore :( Bandcamp still works, so it does not seem to be a problem of my config.

**How to reproduce**
1. Go to 'spotify.com'
2. Click on 'login'
3. Start playing
4. Message "Play some music to get started Is it already playing?" is shown

**Expected behavior**
It should recognize the page

**Screenshots**
--

**Debug logs**
![image](https://github.com/web-scrobbler/web-scrobbler/assets/15656959/7f37a502-89b9-473f-b440-2470eae7d055)

**Environment (please complete the following information)**
Debian 11 with Firefox 102 on xfce

**Comment by inverse** [comment]
A fix for Spotify has already been published but we're waiting on the Mozilla team to review the extension. Only thing we can do is wait unless you want to run the extension unpacked.

**Comment by s7enkoec** [comment]
Sorry, didn't find the #3749 yesterday somehow. Thanks for fixing!
