### ISSUE TITLE
Extension polluting console on every website

### ISSUE THREAD

**Issue by sphinx9** [web-scrobbler/web-scrobbler#3828]
**Describe the bug**
The extension is writing to console.log for every website - most users probably won't notice but I am a web developer and this hinders me.

**How to reproduce**
1. Open website
2. Open console...

**Expected behavior**
Don't pollute console

**Environment (please complete the following information)**
-   OS: W10
-   Browser: Vivaldi (latest)
-   Extension version: latest

**Comment by yayuyokitano** [comment]
We've done some work to reduce logging since release, this newly raised PR should more or less complete that work. Thank you for reporting!
