### ISSUE TITLE
Deezer currently "not supported"

### ISSUE THREAD

**Issue by mhall-tamro** [web-scrobbler/web-scrobbler#3831]
**Describe the bug**
As of today, playing a track on deezer.com causes the extension to say "This Website is not supported." It worked yesterday and for months previously.

**How to reproduce**
1. Open Microsoft Edge or Chrome with the Web Scrobbler extension enabled.
2. Make sure Deezer scrobbling is enabled in the extension settings. 
3. Go to deezer.com
4. Play a song.
5. Click on extension icon in browser bar.
6. See error. Initially it may say something like "Is anything playing?" but then it changes to "This website is not supported".

**Expected behavior**
Expect Webscrobbler icon to be green, not gray, and to not have any warnings and to write scrobble to Last.fm (assuming it is set up in settings).

**Environment**
-   OS: Windows 11
-   Browser: Microsoft Edge and Chrome
-   Extension version: 3.0.3, I think (where do I find out, it's not in "About"?)

**Comment by yayuyokitano** [comment]
Version should be shown in the extensions list in your browser.

i think this might be an issue that we previously fixed in one of the hotfixes since 3.0.3. Could you confirm the version and see?

If you grabbed the extension from edge store, it is currently outdated due to microsoft approving the wrong version, we’re working on resolving it.

**Comment by mhall-tamro** [comment]
Thanks, that worked. Recognizes tracks and scrobbles to Last.fm as expected now. Chrome store version (3.0.10) works on both Microsoft Edge and Chrome. I tossed you a little donation. :)

**Comment by mhall-tamro** [comment]
Closing issue.

**Comment by yayuyokitano** [comment]
Glad it solved the issue, and thank you for the contribution! There still seems to be some bugginess to the deezer connector (#3811), but hope to have that cleaned up soon.
