### ISSUE TITLE
Now playing notifications still display despite being disabled.

### ISSUE THREAD

**Issue by FlamingNinja42** [web-scrobbler/web-scrobbler#3887]
**Describe the bug**
Now playing notifications still display despite being disabled.

**How to reproduce**
1. Disable now playing notifications.
2. See they still appear.

**Expected behavior**
Disabling notifications should prevent them from appearing,

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Microsoft Edge Version 114.0.1823.43 (Official build) (64-bit)
-   Extension version: [v3.0.12

**Comment by yayuyokitano** [comment]
Thank you for reporting! Will have a look into this asap.
