### ISSUE TITLE
BBC Sounds connector no longer scrobbling

### ISSUE THREAD

**Issue by markwheeler** [web-scrobbler/web-scrobbler#3889]
**Describe the bug**
The connector for BBC Sounds seems to longer be recognizing songs played.

**How to reproduce**
1. Go to https://www.bbc.co.uk/sounds/play/m001mf0t
2. Click on play
3. Note web scrobbler recognizes the site but does not display any song info.

**Expected behavior**
This site was previously scrobbling like a champ.

**Environment (please complete the following information)**
-   OS: MacOS 13.4
-   Browser: Brave
-   Extension version: 3.0.12

**Comment by neanias** [comment]
I'm also seeing problems with this:

* OS: MacOS 13.4
* Browser: Firefox 114.0.2
* Extension version: 3.0.13

**Comment by inverse** [comment]
Will be in the next release

**Comment by neanias** [comment]
Thanks for the fix! When are you expecting to release a new version?
