### ISSUE TITLE
Spotify again

### ISSUE THREAD

**Issue by MXB2001** [web-scrobbler/web-scrobbler#3906]
**Describe the bug**
Spot stopped scrobbling recently.

**Environment (please complete the following information)**
-   OS: Linux
-   Browser: Firefox
-   Extension version: current

**Comment by s7enkoec** [comment]
I found a workaround: you can connect last.fm and spotify directly: https://www.makeuseof.com/tag/scrobble-spotify-last-fm/

**Comment by inverse** [comment]
Sounds like perhaps they are rolling out a new redesign? It's still working for me :/

**Comment by MXB2001** [comment]
Just checked, hehe, and it is still broken for me.

**Comment by yayuyokitano** [comment]
Apologies for delay getting to this. Unable to repro this on my end.
What do you mean when you say it doesn't scrobble. Icon gray? Red? Does it recognize song but not actually scrobble?
Also, do you have any extensions installed that affect spotify in any way?

**Comment by MXB2001** [comment]
Red icon. It doesn't seem to pick it up at all. Nope, no spotify extensions at all.

**Comment by MXB2001** [comment]
Fixed as of today's update.
