### ISSUE TITLE
Poolsuite.net connector not scrobbeling

### ISSUE THREAD

**Issue by pedrojvaz** [web-scrobbler/web-scrobbler#3921]
**Describe the bug**
WS not scrobbling from Poolsuite.net

**How to reproduce**
1. Go to ['Poolsuite'](https://poolsuite.net/)
2. Click on Play
3. Web Scrobbler does not detect the music

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: Brave [Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)](https://brave.com/latest/)
-   Extension version: 3.0.13

**Comment by inverse** [comment]
Will be in the next release - thanks @fikimaul
