### ISSUE TITLE
Apple music not working.

### ISSUE THREAD

**Issue by RAMuri** [web-scrobbler/web-scrobbler#3967]
**Describe the bug**
Getting this error when playing music in Apple music:
![image](https://github.com/web-scrobbler/web-scrobbler/assets/50538082/91ef8703-9737-4229-841f-d6486810b2f6)

**Screenshots**
Settings:
![image](https://github.com/web-scrobbler/web-scrobbler/assets/50538082/be8e4d20-7d25-4f13-b3a5-41316616f11c)
![image](https://github.com/web-scrobbler/web-scrobbler/assets/50538082/1d43875c-e662-4d36-9675-0db1b7517a3d)

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: Firefox
-   Extension version: 3.0.15

**Comment by pchmykh** [comment]
Doesn't work on Fedora linux Firefox too.
