### ISSUE TITLE
Scrobbling just one artist

### ISSUE THREAD

**Issue by kostalexei** [web-scrobbler/web-scrobbler#3979]
Hi!

Is it possible to make it so that only one artist is scrobbled?
For example:
<img width="1153" alt="screen" src="https://github.com/web-scrobbler/web-scrobbler/assets/32930504/01a46d09-575b-400f-8a0e-3d1d4a5276a1">

**Comment by yayuyokitano** [comment]
You can use the new regex edit function for this.
In the artist field, try to input `(.*?)(( &)|,) (.*)` in search, and `$1` in replace, and I believe it should work.
