### ISSUE TITLE
Web Spotify scrobbling does not work

### ISSUE THREAD

**Issue by yolomak** [web-scrobbler/web-scrobbler#3980]
Hi, I've always been using my web spotify on pc, through google chrome and scrobbling on last.fm, but it doesn't work for almost a week. It recognizes the song and it plays but it doesn't scrobble it or write it down as played. I don't know where the problem is, it's working on youtube, but it does not work on web spotify. Please help!!

I've checked all the options, I've deleted the extension and download it again, nothing works.

![Snimka zaslona (1546)](https://github.com/web-scrobbler/web-scrobbler/assets/140254283/8885eb0f-2eef-4c60-b260-bab57cfc88f5)

It stays like it, it doesn't do the 'strick' to actually scrobble it.

**Comment by yayuyokitano** [comment]
Web scrobbler spotify connector currently only works if you have the duration on the right side of the seekbar set to full duration.
If it is set to show the remaining duration, it will not scrobble much like this.
Could you check if this is the case?
You can toggle between full duration and remaining duration by clicking the duration number.

**Comment by yolomak** [comment]
Oh my god!! It works now, I was not aware of this detail. Thank you so much!!

**Comment by yayuyokitano** [comment]
Great! This is not intended so it should be fixed at some point, but for now this workaround will do. Closing because I know for a fact we definitely have this issue already reported, though I don't feel like finding the exact issue number right now.
