### ISSUE TITLE
Only versions 2.89.0 and below work in Waterfox

### ISSUE THREAD

**Issue by eclairy666** [web-scrobbler/web-scrobbler#3990]
The latest version(s) of this extension is(are) not optimized for the Waterfox fork of Firefox

I recently experienced some laggy behavior from the web scrobbler extension in Waterfox, I decided to uninstall it and install it again. 
When I went to Firefox's add-on page for this extension I got this warning, only being able to install an older version of the extension(2.89.0)
<img width="827" alt="image" src="https://github.com/web-scrobbler/web-scrobbler/assets/140423291/5236f1ca-c477-4ec3-99f5-14fcf49527d7">

**Comment by yayuyokitano** [comment]
The main purpose of V3 was to redo the entire extension architecture to allow us to update to manifest V3 to ensure continued functioning with chromium.

Sadly, firefox really dropped the ball on this one, and did not implement manifest V3 support until January this year with Firefox 109.

Waterfox bases itself on Firefox ESR, which did not receive this update until ESR 115 released 4 July 2023.

Presumably the next version of waterfox will support web scrobbler V3, as I would hope the next version includes an update to firefox ESR.
