### ISSUE TITLE
npm run lint: errors and warnings

### ISSUE THREAD

**Issue by mathwar** [web-scrobbler/web-scrobbler#4023]
When I run the command npm run lint my result is
```
✖ 58 problems (8 errors, 50 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```
The simplest ones are solved by removing a * from the start of some comment blocks. But the following messages I don't understand at the moment. Many are of the type:
```
(warning The reactive variable 'props' should be used within JSX, a tracked scope (like createEffect),
or inside an event handler function, or else changes will be ignored  solid/reactivity).
```
It seems to me that work is being done on the issue, as I saw some PR regarding ESLint.

However, npm run test completes successfully:

```
Test Files 9 passed (9)
     Tests 1652 passed (1652)
```

1. Is the problem common for you too?
2. Could I submit a new tested and working connector anyway?

I haven't been here in a while, great job with v3!

**Comment by yayuyokitano** [comment]
The warnings are generally not an issue (though I think you did introduce 4 new ones compared to master which you may want to look into). Errors must be eliminated before merge. Currently master has 0 errors, so these should have been introduced from your side unless you have some issue in environment. But without seeing the errors I don't know what that is.

It working is not enough, as linting is part of our requirements for code quality and standardization within the project, to keep the code easier to work with in the future. If you are confused, feel free to submit a PR with your current code so we can see the linter output and help you sort it out.

As an aside, typescript comments do not start with /**, ts comments are // for single and /* for multi line comments like in js. However, web scrobbler uses the jsdoc-based [tsdoc](https://tsdoc.org/) standard for some of our comments to standardize some things.

**Comment by mathwar** [comment]
Thanks for the comments and help. It's been another long time. I definitely had problems with the environment, but I lost track of which dependencies I had installed and which were updated.

Now it turns out the following:
```
npm run lint
✖ 46 problems (0 errors, 46 warnings)
```
and

```
npm run test
      Test Files  9 passed (9)
      Tests  1648 passed (1648)
 PASS
```
