### ISSUE TITLE
Update Stylelint configuration.

### ISSUE THREAD

**Issue by jaccarmac** [web-scrobbler/web-scrobbler#4065]
Continuing the conversation from #4049.

web-scrobbler/stylelint-config-web-scrobbler#30 and web-scrobbler/stylelint-config-web-scrobbler#31 are my clumsy starts to addressing the out-of-date Stylelinting.

SASS support appears to be the big blocker for Stylelint. I submit that upgrading to 14 then 15 is the best course of action.

**Comment by inverse** [comment]
Thanks for looking into this :+1:

**Comment by inverse** [comment]
I'm guessing we will have to migrate the npm package too as we don't have much access on the non-org scoped stuff.

we did a similar thing for the meta filter.

**Comment by jaccarmac** [comment]
> non-org scoped stuff

Which stuff is this? Forgive me, I'm out of the loop, but what I can tell so far is:

- Configurations sit in various repos under the WS GitHub org.
- I have commit permissions here but not on the config repos.

**Comment by inverse** [comment]
Ahh sorry for my vagueness - I meant we had to migrate
-  from https://www.npmjs.com/package/metadata-filter
-  to https://www.npmjs.com/package/@web-scrobbler/metadata-filter 

due to permissions on the non-org scoped package.

Here's the PR https://github.com/web-scrobbler/metadata-filter/pull/263

I guess we'll need to do a similar thing for the stylelint one.

**Comment by jaccarmac** [comment]
Ah, gotcha.

On the GitHub side, may I have permissions on the rest of the org repositories? Happy to do PRs-from-forks if there's a reason to prefer that, but the impedance between modding this repo and those of the configs was the source of some frustration.

**Comment by inverse** [comment]
Permissions should be updated :)

**Comment by jaccarmac** [comment]
Great! I'm getting pinged for reviews on metadata-filter now, though I still can't press merge.
