### ISSUE TITLE
Turntable.fm not scrobbling

### ISSUE THREAD

**Issue by fuzz-lightyear11** [web-scrobbler/web-scrobbler#4071]
Turntable.fm has changed its url to www.deepcut.fm and the web scrobbler no longer supports the site. Please fix!

**Comment by onchyophoran** [comment]
wanted to second this request, the deepcut.fm version of the site improves some playback, so it'd be very much appreciated if scrobbling worked from it as well as it has been for TTFM

many thanks

**Comment by jbwharris** [comment]
> Turntable.fm has changed its url to [www.deepcut.fm](http://www.deepcut.fm/) and the web scrobbler no longer supports the site. Please fix!

It does still work if you use the old URL, I think it just requires adding the new URL to the list of valid URLs

**Comment by jaccarmac** [comment]
Is this fixed with your pull request @jbwharris ?

**Comment by jbwharris** [comment]
@jaccarmac Yup, fully functioning with the renamed connector. This issue can be closed.

![image](https://github.com/web-scrobbler/web-scrobbler/assets/2962327/875f567b-cb6f-4327-9d0e-eebd647e9c1a)

**Comment by onchyophoran** [comment]
> @jaccarmac Yup, fully functioning with the renamed connector. This issue can be closed.
> 
> ![image](https://user-images.githubusercontent.com/2962327/267746327-875f567b-cb6f-4327-9d0e-eebd647e9c1a.png)

they broke it again.
both turntable.fm and deepcut.fm now redirect to **deep-cut.fm**, and the extension no longer recognizes it

**Comment by jbwharris** [comment]
@onchyophoran I just pushed a fix for this.

**Comment by jaccarmac** [comment]
Thanks @jbwharris

**Comment by onchyophoran** [comment]
big thanks
