### ISSUE TITLE
Radiojavan connector is broken

### ISSUE THREAD

**Issue by MasoudRahmani** [web-scrobbler/web-scrobbler#4144]
### RadioJavan
![image](https://github.com/web-scrobbler/web-scrobbler/assets/5321268/374aa01f-9892-42c4-93c2-fee8cfe264af)

Website **address** is **changed** as it says it is not a supported website.

![image](https://github.com/web-scrobbler/web-scrobbler/assets/5321268/bf250d71-0227-4b3a-b751-cd9d897ec06e)

After i manually add the new address `https://play.radiojavan.com/` It still does not recognize playing song.

![image](https://github.com/web-scrobbler/web-scrobbler/assets/5321268/2dbcfab5-e8bd-49ae-b070-eed4b5e3cf18)

**Expected behavior**
Add new address website, recognize playing song.

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: FireFox and chrome

**Comment by yayuyokitano** [comment]
Struggling to work on this, the website is putting hurdles in the way of being able to access any DOM information unless you have premium, and they're declining my card. Might look into getting around it at a later time

**Comment by MasoudRahmani** [comment]
Thank you, It's really disappointing when a streaming service don't understand what is needed for avid listener.

Appreciated for you efforts. ❤️🌹
