### ISSUE TITLE
On firefox. Webhook API does not work with local IP as hostname

### ISSUE THREAD

**Issue by FoxxMD** [web-scrobbler/web-scrobbler#4183]
**Describe the bug**

On Firefox, with the default add-on settings, the Webhook API fails to send a request when the API URL hostname is (private/local)? IP address like `192.168.0.100`.

This **only occurs** when using IP address. If I use `localhost` it's fine.

* OK `http://localhost:8080/webscrobbler` 
* ? `http://scrobble.myDomain.tld/webscrobbler` (did not test but assume it works)
* FAIL `http://192.168.0.100:8080/webscrobbler`

**How to reproduce**
1. Setup an HTTP server to accept POST on `0.0.0.0:8080/webscrobbler`
2. Create a Webhook with API URL `http://192.168.0.100:8080/webscrobbler` (use the same machine's IP)
3. [Debug the extension](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) to see requests fail to send 

**Expected behavior**
Webhook API works whether using FQN, localhost, or IP address

**Debug logs**

```
10:56:58.854 Webhook: Webhook - sendRequest: {
  "eventName": "paused",
  "data": {
    "song": {
      "parsed": {
        "track": "Cissy Strut",
        "artist": "The Meters",
        "albumArtist": null,
        "album": null,
        "duration": null,
        "uniqueID": null,
        "currentTime": null,
        "isPlaying": false,
        "trackArt": null,
        "isPodcast": false,
        "originUrl": "https://www.mixcloud.com/EuanBarker/soul-ska-other-good-good-stuff-october-2023/"
      },
      "processed": {
        "track": "Cissy Strut",
        "artist": "The Meters",
        "albumArtist": null,
        "album": "Good Old Funky Music: 20 Upbeat Cool Down New Orleans Classics",
        "duration": 183
      },
      "noRegex": {
        "track": "Cissy Strut",
        "artist": "The Meters",
        "albumArtist": null,
        "album": "Good Old Funky Music: 20 Upbeat Cool Down New Orleans Classics",
        "duration": null
      },
      "flags": {
        "isScrobbled": false,
        "isCorrectedByUser": false,
        "isRegexEditedByUser": {
          "track": false,
          "artist": false,
          "album": false,
          "albumArtist": false
        },
        "isAlbumFetched": true,
        "isValid": true,
        "isMarkedAsPlaying": true,
        "isSkipped": false,
        "isReplaying": false
      },
      "metadata": {
        "userloved": false,
        "startTimestamp": 1696517813,
        "label": "Mixcloud",
        "trackArtUrl": "https://lastfm.freetls.fastly.net/i/u/300x300/ce301889644ba2e03396eb5593bd6010.png",
        "artistUrl": "https://www.last.fm/music/The+Meters",
        "trackUrl": "https://www.last.fm/music/The+Meters/_/Cissy+Strut",
        "albumUrl": "https://www.last.fm/music/The+Meters/Good+Old+Funky+Music:+20+Upbeat+Cool+Down+New+Orleans+Classics",
        "userPlayCount": 0,
        "albumMbId": "b71535b2-9b2a-4700-a471-7d1c6a9a6c2c"
      },
      "connectorLabel": "Mixcloud",
      "controllerTabId": 925
    }
  }
} [main.js:1:10188](moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js)
10:56:58.856 Web Scrobbler: Send "paused" request: 2 [main.js:1:11427](moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js)
10:56:58.860
Webhook: Error while sending request [main.js:1:10188](moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js)
    _ moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:1
    debugLog moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:4
    sendRequest moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:6
    sendPaused moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:6
    sendPaused moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:6
    sendPaused moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:6
    la moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:6
    fn moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:6
    o moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:1
    x moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:1
    Jt moz-extension://8593d7e0-d121-4ba1-90b9-e2bcd090a4fc/background/main.js:1
```

**Environment (please complete the following information)**
-   OS: EndeavourOS Linux x86_64 | Kernel: 6.5.3-arch1-1 
-   Browser: Firefox 117.0.1
-   Extension version: v3.2.0

**Additional context**

After changing webhook API URLs (add/remove) I had to reload the entire extension  (by toggling "enable in private windows" from add-on management") in order to get the changes to take effect.

**Comment by yayuyokitano** [comment]
This one is on firefox. Firefox completely disrespects the http scheme and will silently and automatically redirect requests to https for all but a handful of urls (localhost and 127.0.0.1 being two of them). You can observe this if you go to the network tab in the extension background script, and wait for the request to time out so you can see the details including scheme.

You can try to turn off https redirects in firefox settings, though I have heard stories of firefox simply ignoring that too.

You may want to simply set up https on your local server if you want to use firefox.

> After changing webhook API URLs (add/remove) I had to reload the entire extension (by toggling "enable in private windows" from add-on management") in order to get the changes to take effect.

This is fixed on master, and will be pushed next update.
