### ISSUE TITLE
Fritz connector is not working anymore

### ISSUE THREAD

**Issue by Ceddicedced** [web-scrobbler/web-scrobbler#4187]
The problem is the connector seems to be outdated.

Also the livestream website doesn't display the current playback information anymore.
So we can't scrape the track and artist...

**Comment by jaccarmac** [comment]
> the livestream website doesn't display the current playback information anymore

Does this mean a connector is no longer possible at all?

**Comment by Ceddicedced** [comment]
Yeah seems like it.
