### ISSUE TITLE
cannot sign in with last.fm

### ISSUE THREAD

**Issue by makoalbo** [web-scrobbler/web-scrobbler#4197]
i had to make a github account just to report this 💀

anyways, i have a problem trying to sign in with last.fm in web scrobbler. that problem being the site not opening. if you can fix this i'd very much appreciate it. thanks!

**Comment by yayuyokitano** [comment]
Indeed I have heard of a lot of issues from last.fm's side the past 24 hours or so.
I don't think this is an issue on our end, as we have not made any updates in weeks, yet this has only started happening now.
I think we just have to wait it out while lastfm gets their website under control.
@makoalbo are you still experiencing the issue?

**Comment by yayuyokitano** [comment]
Glad to hear that! Will close then as this seems to have been on lastfm's end
