### ISSUE TITLE
Change bulk edit rules data structure

### ISSUE THREAD

**Issue by FichteFoll** [web-scrobbler/web-scrobbler#4218]
Per the default format of the JSON export, I assume that the data structure currently always has 8 fields for each entry in a flat structure, i.e.:
```
{"search":{"track":null,"artist":null,"album":"(.*) - Single","albumArtist":null},"replace":{"track":null,"artist":null,"album":"$1","albumArtist":null}}
```

This format is unintuitive because it is not clear to me whether there is a difference between a single entry with a track and an album rule and two entries with one rule each. Additionally it can lead to confusions such as #4217. 

The ambiguity seems unnecessary, so I instead want to suggest to have a list of multiple entries, one list for each field (artist, album, etc).

<details>
<summary>JSON format examples (before and after)</summary>

Before:
```json
[
  {
    "search": {
      "track": null,
      "artist": null,
      "album": "(.*) - Single",
      "albumArtist": null
    },
    "replace": {
      "track": null,
      "artist": null,
      "album": "$1",
      "albumArtist": null
    }
  },
  {
    "search": {
      "track": null,
      "artist": null,
      "album": "(.*) - EP",
      "albumArtist": null
    },
    "replace": {
      "track": null,
      "artist": null,
      "album": "$1",
      "albumArtist": null
    }
  }
]
```

After:
```json
{
    "track": [],
    "artist": [],
    "album": [
        {
            "search": "(.*) - Single",
            "replace": "$1"
        },
        {
            "search": "(.*) - EP",
            "replace": "$1"
        }
    ],
    "albumArtist": []
}
```

</details>

The advantage to this is that the way the data is used is clear and saves a lot of redundant `null` fields.

**Comment by yayuyokitano** [comment]
Regex and bulk edits are made to be able to specify multiple fields at once. That is, you can specify to only edit if there is a certain artist AND a track, and apply edits to one or both, or artist and an album, or all three, or just one, or album artist, or whatever combination you want, in a single edit.

so for instance, lets say if there is an album called “hello world” by “foo” and another album called “hello world” by “bar”, you can apply just an edit setting “hello world” to “hello 世界” and it will apply to both albums, or you can specify “foo” in the same edit, and it will not apply to “hello world” by “bar”.

the data structure you mention would not work for this.

we do not plan to make any major changes to the data structure as of now. The only potential future change could be removing cases where both search and replace are null for the same field, but it would add complexity to the code that I’m not completely sure is worth it given that by their nature people will probably not stack up all that many bulk edits.

**Comment by FichteFoll** [comment]
I see, it wasn't clear to me that all conditions for the search need to match in order for the replacements to apply. In that case, the data strutcure makes sense.

However, would you mind improving the documentation on this part a bit? Some text explaining this inside the options page would be much appreciated.
