### ISSUE TITLE
Song is being categorized/streaking incorrectly

### ISSUE THREAD

**Issue by Aetherskye** [web-scrobbler/web-scrobbler#4221]
**Describe the bug**
The song Savages by Chonny Jash on Youtube is being categorized wrongly as Chonny Jash by Savages

**How to reproduce**
1. Go to Youtube
2. Listen to [Savages by Chonny Jash] (https://www.youtube.com/watch?v=Vb2MNYMo964)
3. When listened too, it will scrobble Chonny Jash by Savages and not Savages by Chonny Jash

**Expected behavior**
I expect it to be Savages by Chonny Jash, and add to my streak and leaderboard stats for that song.

**Screenshots**
<img width="287" alt="image" src="https://github.com/web-scrobbler/web-scrobbler/assets/50000718/15214612-d76f-4332-b9b2-69d4360d8b7c">
<img width="612" alt="image" src="https://github.com/web-scrobbler/web-scrobbler/assets/50000718/68574452-57ba-4cc3-be60-f495d25872de">

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
Browser, Chrome

**Additional context**

**Comment by yayuyokitano** [comment]
Thank you for reporting!

This might actually not be trivial to fix given how things are structured in the code right now, but I agree that this should eventually be done.

In the meantime, you can use the edit function to edit the track and it should be saved, though this is of course not optimal.

**Comment by Aetherskye** [comment]
Alright, thank you!

**Comment by kornykutie** [comment]
Heyhey!! i know why its doing this; 
the video uploader formatted it wrong! they put "savages - chonny jash" 
the correct way should be the other way around , "chonny jash - savages" 
try to find a upload of the song where it's correct or make it your self! 
hope this helps!

**Comment by yayuyokitano** [comment]
Oh my bad, I assumed the title between [] was written exactly as it is on youtube in the original issue, my bad.
Thank you @kornykutie for noticing.
Yes, the way this title is formatted, it is not realistic for web scrobbler to handle it (short of implementing some sort of advanced AI, or some sort of complicated community based server, which are both far out of scope for our current size).
you will have to edit manually and it will remember it, or scrobble from another video.
closing as wontfix.
