### ISSUE TITLE
Spaces in artist/track name are sometimes rendered with '%20' in the last.fm link instead of '+'

### ISSUE THREAD

**Issue by AquaDoesStuff** [web-scrobbler/web-scrobbler#4252]
Title. For example, a track I noticed this in is https://soundcloud.com/tribaltrapmusic/the-forgotten-hyperlink-senkrad-remix, where instead of scrobbling to https://www.last.fm/music/The+Forgotten/Hyperlink+(SENKRAD+Remix) (the page where all of the last.fm data is), it scrobbles to https://www.last.fm/music/The%20Forgotten/_/Hyperlink%20(SENKRAD%20Remix), where the artist and track text is visually identical but has no last.fm data.

![image](https://github.com/web-scrobbler/web-scrobbler/assets/77502880/ed59b477-f455-4e1c-97e5-246d71490bde)
![image](https://github.com/web-scrobbler/web-scrobbler/assets/77502880/d5b14265-73d6-48d6-a21a-03b548fc9919)

I'm using Windows 10 with extension version 3.2.0 on Google Chrome

**Comment by yayuyokitano** [comment]
%20 and + are interpreted identically by last.fm. The issue here is that your first link is an album, while the second link is a track. (You can see this, because the second link has a `/_/` between the artist and track name, while the first link only has a `/`)
