### ISSUE TITLE
Titles with brackets not recognized in bulk-editing mode

### ISSUE THREAD

**Issue by Sil3sium** [web-scrobbler/web-scrobbler#4275]
**Describe the bug**
If a Spotify album has an unnecessary brackets in the title (for example, "Anniversary edition"), these cannot be mass-removed through the bulk-edit feature. Each track of the album needs to be edited separately.

If I go to the bulk edit section and copy the title that has brackets and needs to be mass-replaced, the extension does not seem to recognize it (this is indicated by the red cross at the end of the input box).

Perhaps the extension recognizes brackets as part of regexp, rather than plain text?

**How to reproduce**
1. Play a Spotify album that has bracketed information added to the title, for example, "No Limits (Anniversary Edition)" by U.D.O.
2. Click on 'Edit track metadata' and then '<>'
3. Copy the album title complete with the brackets into the Search / Album cell
4. See error — a red cross appears next to the title, indicating that this title has not been recognized. Writing the desired title in the Replace / Album cell ("No Limits") does not change the title shown in the Preview cell and subsequently is scrobbled in the unchanged form, complete with the brackets.

**Expected behavior**
Placing a title that has brackets in the Search / Album cell should produce the green tick next to it and adding the desired title in the Replace / Album cell should show that version of the title in the Preview cell.

**Screenshots**
https://imgur.com/FfcntO5

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Firefox
-   Extension version: 3.2.0

**Comment by fikimaul** [comment]
Add backslash `\` before the ( and )
![image](https://github.com/web-scrobbler/web-scrobbler/assets/18456011/d1582b5f-1f85-4e28-916a-dcab75db9b09)

**Comment by Sil3sium** [comment]
Great, thank you!

**Comment by yayuyokitano** [comment]
We have added a toggle to disable regex to be pushed in 3.6.0, which will disable regex by default.
