### ISSUE TITLE
FluxFM Berlin Connector doesn't work anymore

### ISSUE THREAD

**Issue by LetsSmash** [web-scrobbler/web-scrobbler#4278]
![Screenshot 2023-11-10 111442](https://github.com/web-scrobbler/web-scrobbler/assets/94486695/b2326c65-fe31-412d-bc0c-f52f70a631e5)
![Screenshot 2023-11-10 111336](https://github.com/web-scrobbler/web-scrobbler/assets/94486695/62dc4bce-79d1-47a9-99ed-826a7c8a51ce)

I looked into the Elements, they seem to have been changed

**Comment by inverse** [comment]
Will be in the next realase  - was fixed in #4268
