### ISSUE TITLE
FIP has stopped scrobbling

### ISSUE THREAD

**Issue by Maddieman** [web-scrobbler/web-scrobbler#4294]
**Describe the bug**
FIP playback is no longer detected at https://www.radiofrance.fr/fip

**How to reproduce**
1. Go to: https://www.radiofrance.fr/fip
2. Click on ECOUTER FIP button to start the radio
3. Alternatively, click on one of the sub-stations below (e.g. Jazz, Electro, Metal, etc)

**Expected behavior**
FIP playback is detected and scrobbles.

**Actual**
FIP is not detected, the extension shows the "Play some music to get started / Is it already playing?" prompt.

**Screenshots**
![Screenshot 2023-11-14 at 14 46 20](https://github.com/web-scrobbler/web-scrobbler/assets/1643178/5a38b36c-af28-4f1a-b1e7-bd24a4300374)
![Screenshot 2023-11-14 at 14 50 50](https://github.com/web-scrobbler/web-scrobbler/assets/1643178/265f8f82-87b3-4c68-8d4e-ff449ec26cf6)

**Debug logs**
Only thing of note is:
`Error: Could not establish connection. Receiving end does not exist. at je (main.js:1:9106)`

**Environment (please complete the following information)**
-   OS: MacOS Monterey
-   Browser: Chrome, Version 119.0.6045.123 (Official Build) (arm64)
-   Extension version: 3.2.0

**Additional context**
I think they've changed their music player UI recently.  It also looks like there was a problem last week: https://github.com/web-scrobbler/web-scrobbler/issues/4266

Thanks in advance for looking into this.

**Comment by jee-r** [comment]
Thank's for the fix @Mehavoid,  do you know when it will be released ?

I do not understand why this kind of fix is not release as a patch release
