### ISSUE TITLE
YouTube Music connector unable to find unique IDs

### ISSUE THREAD

**Issue by LostLuma** [web-scrobbler/web-scrobbler#4342]
**Describe the bug**

The YouTube Music connector can no longer find the unique ID (video ID) of each track.  
This prevents using previous saved edits, and also saves them in a less useful format.

**How to reproduce**
1. Save an edit for a track on YouTube music
2. Export the saved track storage
3. A hash of the pre-edit track data is used as the key instead of the video ID

**Expected behavior**

Saved edits should use the video ID, same as they've done previously and do on regular YouTube.

**Screenshots**

```json5
{
  // This should be 1tkdmY7sdUc instead
  "6cb3267d1f7d02d71b367996999f5350": {
    "artist": "IZ*ONE",
    "track": "Panorama",
    "album": "One-reeler / Act IV",
    "albumArtist": null
  }
}
```

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   Browser: Firefox 122.0a1
-   Extension version: 3.2.0

**Comment by SeijiSuenaga** [comment]
This problem has been intermittent in the past few days. Sometimes the YouTube Music DOM contains the `.yt-uix-sessionlink` element (which the connector depends on), but other times it doesn't. 🤔

**Comment by inverse** [comment]
Will beh handled in the next release - thanks @LostLuma!
