### ISSUE TITLE
Disable 'Scrobbling is not allowed. Click web scrobbler extension icon for more information.' text on YouTube

### ISSUE THREAD

**Issue by ryanzzz1243** [web-scrobbler/web-scrobbler#4355]
**Is your feature request related to a problem? Please describe.**
WebScrobbler is putting 'Scrobbling is not allowed. Click web scrobbler extension icon for more information.' text under the title of YouTube videos.

**Describe the solution you'd like**
Remove this text or add an option to disable this text.

**Comment by LetrixZ** [comment]
Same for 'This site is supported for scrobbling, but you disabled it'

**Comment by FlashlightET** [comment]
yeah i agree - i watch a lot of youtube videos that aren't music and this is quite in the way

**Comment by yayuyokitano** [comment]
There is already such an option. In web scrobbler settings, disable "Show infobox" to make the text disappear.
Note that you will have to refresh youtube for changes to be applied.
