### ISSUE TITLE
SiriusXM Website Update, No Longer Scrobbles

### ISSUE THREAD

**Issue by WillowGryph** [web-scrobbler/web-scrobbler#4362]
**Describe the bug**
SiriusXM's website was updated and it appears the connectors are broken.

**How to reproduce**
1. Go to https://www.siriusxm.com/player/my-library
2. Click on a station
3. Play station
4. "This website is not supported"

**Expected behavior**
Extension should be scrobbling the current song playing.

**Screenshots**
![image](https://github.com/web-scrobbler/web-scrobbler/assets/113316179/5294ce34-30b7-4eb1-a612-33bd1fdd62bb)

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: Firefox
-   Extension version: 3.3.0

**Comment by terententen** [comment]
Welp. This was a bummer to run into this morning.

**Comment by NeilN1** [comment]
Changing the URL pattern to match the new address results in: 
![image](https://github.com/web-scrobbler/web-scrobbler/assets/12532256/63224e29-22cf-4461-9fd5-5cc05c8b409d)

**Comment by alcapurrias** [comment]
I just wanted to note that they also changed the format of artist/track name also. They were separated previously and now they're coming up as a single span:

```
<span class="_text_2wvdz_6 _text--align-left_2wvdz_343 _text--baseline-paragraph-medium_2wvdz_1349 _text--decoration-paragraph-medium_2wvdz_818 _text--font-paragraph-medium_2wvdz_896 _text--line-paragraph-medium_2wvdz_983 _text--size-paragraph-medium_2wvdz_1088 _text--spacing-paragraph-medium_2wvdz_1172 _text--weight-paragraph-medium_2wvdz_1259 _text--accessible_2wvdz_1565 _text--accessible_2wvdz_1565" style="--text-color: currentColor;">Black Box  -  Strike It Up</span>
```

![image](https://github.com/web-scrobbler/web-scrobbler/assets/63966511/5c4ab4d5-46e3-4c90-83fb-bb8c888fbd41)

**Comment by elpidge** [comment]
Came here to post the same problem. Good to see its already been reported.

**Comment by egoforth** [comment]
Just another vote in support of updating the connector.

**Comment by egoforth** [comment]
> Just another vote in support of updating the connector.

If it makes any difference, I am an OpenCollective supporter, and I just sent another contribution

**Comment by egoforth** [comment]
I'd like to offer to help, but I don't know TypeScript at all. If you think it's something I can figure out with a bit of guidance, I'd still be willing to help out.

**Comment by jbwharris** [comment]
> @jbwharris would you be able to help with this one? 

I unfortunately don't currently have SiriusXM. I can see about reupping to take a look, I'm just out of town for a bit.

**Comment by inverse** [comment]
@jbwharris no worries - assumed you were subscribed :)

@egoforth we have this guide https://github.com/web-scrobbler/web-scrobbler/wiki/Connectors-development which might help.

However looking at what @alcapurrias  posted in https://github.com/web-scrobbler/web-scrobbler/issues/4362#issuecomment-1858693020

Those selectors look a bit difficult to match as they would be prune to breaking with each build of SiiriusXM :/

**Comment by m01001100** [comment]
I just learn I've missed two weeks of scrobbles 😭
