### ISSUE TITLE
 Notify if user loved/unloved song via hotkey

### ISSUE THREAD

**Issue by CennoxX** [web-scrobbler/web-scrobbler#4374]
In terms of usability, it would be good to get feedback whether using the hotkey has had any effect. The only way to find out is to open the popup, which makes the hotkey kinda useless. 

In version 2.x this was made by displaying a  temporary browser action icon on hotkey press - with version 3 this doesn't work anymore. 
Here is the implementation of version 2: https://github.com/web-scrobbler/web-scrobbler/commit/a945a4f2715d59aba16df1736399156dd26e399d

**Comment by ahnesther** [comment]
Hello @yayuyokitano: I was wondering if I could take over this issue, since I have been working on this and the major kinks have been worked out. There are some things I have to look into, like localization and testing on Safari. Please let me know!

**Comment by yayuyokitano** [comment]
Go for it! Feel free to open a draft PR if you want help with localization related things and Safari testing.
Thank you for letting me know!

**Comment by ahnesther** [comment]
Awesome, thanks!!

**Comment by ahnesther** [comment]
@yayuyokitano https://github.com/web-scrobbler/web-scrobbler/pull/4472 Draft PR ready to be looked at :)
