### ISSUE TITLE
What is the new minimum browser version for Firefox?

### ISSUE THREAD

**Issue by TheBros47874** [web-scrobbler/web-scrobbler#4381]
Hi!

Let me preface this by saying that I'm using Firefox 83.0 for compatibility reasons. I will also not upgrade my (main) version of Firefox.

Now, on to the actual question:
I listen to music mostly on Youtube and for that I'd need to use the addon. If I wanted to install that add-on however, Firefox tells me that it is corrupt and won't download it. Having seen the error on the very top the last.fm forum page however, I assume that it's due to my low Firefox version and thus my question.
I don't want to keep trying every version of Firefox either up or down to find out which one is the one that is compatible with both my own applications and the scrobbler service. So far the Forum and this add-on have also been the only ones that claim to be incompatible, so I'm not hindered in any other activities online.

Also, what is the newest version of this add-on that's still compatible with my current browser version/after which update did the compatibility break?

Thank you and thank you for respecting my choices to want to stay on an older version of my browser.

**Comment by yayuyokitano** [comment]
Hi, our major update 3.0.0 migrated the extension to extension manifest V3, which FIrefox only added general support for in version 109. That should be the only compatibility issue, so any version prior to 3.0.0 should work with even very old versions of Firefox.

You should also be able to use versions starting from firefox 101 as long as they come from beta or developer channels.
