### ISSUE TITLE
No artifacts available in Actions tab

### ISSUE THREAD

**Issue by thompcha** [web-scrobbler/web-scrobbler#4450]
**Describe the bug**
I'm trying to download the latest build for Firefox using these instructions:
[https://github.com/web-scrobbler/web-scrobbler/wiki/How-to-get-builds](https://github.com/web-scrobbler/web-scrobbler/wiki/How-to-get-builds)

Step 3 states "Download an artifact built for a browser you use (Chrome, Firefox, or Safari)."

When I load the latest build, I see no artifacts to download

**How to reproduce**
1. Visit [https://github.com/web-scrobbler/web-scrobbler/actions/runs/7600566548](https://github.com/web-scrobbler/web-scrobbler/actions/runs/7600566548)

No artifacts are listed.

**Expected behavior**
A list of artifacts should be displayed per [the Github docs](https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts)

**Screenshots**
<img width="1239" alt="Screenshot 2024-01-22 at 10 45 09 AM" src="https://github.com/web-scrobbler/web-scrobbler/assets/3323656/edd962a0-fce1-45e9-a0f5-a5315759d6cc">

**Debug logs**
N/A

**Environment (please complete the following information)**
-   OS: 13.0.1 (22A400)
-   Browser: 121.0.1 (64-bit)
-   Extension version: Latest

**Additional context**
Sorry if this is obvious, I'm new to the Actions feature of Github.

**Comment by inverse** [comment]
@yayuyokitano that might have the artifact upload bit I removed in https://github.com/web-scrobbler/web-scrobbler/pull/4353

**Comment by thompcha** [comment]
Thanks for the response. It sounds like the practice of uploading artifacts is no longer current? If so, is there an alternative way for me to get the latest build, or do I just have to build from source?

**Comment by inverse** [comment]
We removed it as it was slowing down branch builds significantly. 

Perhaps it could be something we bring back for master builds?

**Comment by yayuyokitano** [comment]
Yeah I'd agree with that, seems like a reasonable compromise, since PRs is the only place we actually care about speed.
In the meantime, here's a dist copy of most recent master commit at time of writing:
[web-scrobbler-firefox.zip](https://github.com/web-scrobbler/web-scrobbler/files/14070479/web-scrobbler-firefox.zip)

**Comment by inverse** [comment]
Addded back mastef build artifacts + updated docs to reflect
