### ISSUE TITLE
"Web scrobbler error"

### ISSUE THREAD

**Issue by cornucopia** [web-scrobbler/web-scrobbler#451]
I'm trying to scrobble song from youtube, but this is appearing:
![wse](https://cloud.githubusercontent.com/assets/8769598/4264757/523071e4-3c32-11e4-9fa4-29552038a0d8.png)

I was checking and everything is OK, I even reinstalled scrobbler but it's still not working.

**Comment by beweress** [comment]
I have this problem with version 1.50, what's wrong?

**Comment by bes-internal** [comment]
see #698
