### ISSUE TITLE
[Yandex Music] Scrobbling doesn't work when listening to a user-uploaded song

### ISSUE THREAD

**Issue by wileyfoxyx** [web-scrobbler/web-scrobbler#4529]
**Describe the bug**
Yandex Music (just like many other services) allows to upload songs to user's library in case if service's library doesn't have them. Due to that, either Yandex's built-in scrobbler and Web Scrobbler don't scrobble the user-uploaded songs, but do scrobble "legally" uploaded songs.

**How to reproduce**
1. Go to any playlist of yours or create a new one
2. Click on 'Upload track' and wait for the processing to finish
3. Play the song

**Expected behavior**
Web Scrobbler scrobbles the user-uploaded song fine

**Screenshots**
Legally uploaded song:
![image](https://github.com/web-scrobbler/web-scrobbler/assets/46865008/9abf6f0b-9d2d-4e41-b6f1-be4aa68628a2)
User-uploaded song:
![image](https://github.com/web-scrobbler/web-scrobbler/assets/46865008/9c849927-f08c-4cd6-b048-ef3fde4636f2)

**Environment (please complete the following information)**
-   OS: Windows 11 23H2 (build 22631.3155) x64
-   Browser: Google Chrome 121.0.6167.185
-   Extension version: v3.5.0

**Additional context**
Snippet of the DOM while playing legally uploaded song:
```html
<div class="track track_type_player" data-b="4115">
	<div class="entity-cover deco-entity-image-placeholder track-cover entity-cover_size_Large">
		<a href="/album/12669404" class="d-link deco-link" title="From the album &quot;N°5 On Tour&quot;" data-b="4116"> 
			<img class="entity-cover__image deco-pane" src="//avatars.yandex.net/get-music-content/2441215/033e4059.a.12669404-1/50x50" srcset="//avatars.yandex.net/get-music-content/2441215/033e4059.a.12669404-1/50x50, //avatars.yandex.net/get-music-content/2441215/033e4059.a.12669404-1/100x100 2x">
		</a>
	</div>
	<div class="track__name">
		<div class="track__name-wrap deco-typo">
			<div class="track__name-innerwrap">
				<a href="/album/12669404/track/234114" class="d-link deco-link track__title" title="Paradis inanimé" data-b="4117">Paradis inanimé</a>
				<div class="track__ver">Live La Halle Tony Garnier, Lyon / 2009</div>
			</div>
			<div class="track__artists deco-link deco-link_no-hover-color">
				<span class="d-artists d-artists__expanded" data-b="4118">
					<a href="/artist/8773" class="d-link deco-link" title="Mylène Farmer" data-b="4119">Mylène Farmer</a>
				</span>
			</div>
		</div>
	</div>
</div>
```
When playing user-uploaded song:
```html
<div class="track track_type_player track_ugc track_invisible" data-b="4148">
	<div class="entity-cover deco-entity-image-placeholder track-cover entity-cover_size_Large"> 
		<img class="entity-cover__image deco-pane" src="//avatars.yandex.net/get-music-content/5503671/u.0a2d4103-2de5-4351-9993-af1ddaeaf44f/50x50" srcset="//avatars.yandex.net/get-music-content/5503671/u.0a2d4103-2de5-4351-9993-af1ddaeaf44f/50x50, //avatars.yandex.net/get-music-content/5503671/u.0a2d4103-2de5-4351-9993-af1ddaeaf44f/100x100 2x">
	</div>
	<div class="track__name">
		<div class="track__name-wrap deco-typo">
			<div class="track__name-innerwrap">
				<span class="track__title">À quoi je sers... (N°5 On Tour Live)</span>
			</div>
			<div class="track__artists deco-link deco-link_no-hover-color">
				<span class="d-artists d-artists__expanded" data-b="4149">
					<span class="deco-typo-secondary ">Mylène Farmer</span>
				<span>
			</div>
		</div>
	</div>
</div>
```

**Comment by Airkek** [comment]
same to me

**Comment by Airkek** [comment]
![image](https://github.com/user-attachments/assets/c45ddd68-c59f-49ee-9b0c-4a244099199b)

seems like there is problem with parsing cover [here](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/yandex-music-dom-inject.ts#L68)
