### ISSUE TITLE
Reduce delay before scrobbling a track

### ISSUE THREAD

**Issue by anthonypetrov** [web-scrobbler/web-scrobbler#453]
By default, the extension requires one to play a song for 240 seconds or 1/2 of a song (whichever comes first) before allowing one to actually scrobble it.

I propose to introduce a new option that would allow users to set custom delays.

For example, personally, I prefer to submit a scrobble after 30 seconds or 1/5 of a song instead.

**Comment by anthonypetrov** [comment]
See patches in #452 where the suggested changes are implemented (along with other stuff.)

**Comment by janbaykara** [comment]
@david-sabata can close.

**Comment by anthonypetrov** [comment]
Jan or David, could you please clarify the reason for closing this issue? Has this been implemented already? Any links to the changeset or other confirmation info would be very helpful.

**Comment by janbaykara** [comment]
@anthonypetrov ... actually, I'm not 100%. I was scanning through old issues, and I think I may have mistakenly pointed this one out, or perhaps misread it.

@david-sabata  As there is still no way to customise scrobble time, this could probably be reopened.

**My bad guys, sorry.**

On the subject: is there a rationale for wanting custom scrobble delay, @anthonypetrov?

**Comment by anthonypetrov** [comment]
@janbaykara The rationale is that sometimes you listen to a track somewhere that can't scrobble individual tracks or at all (e.g. a mixtape), or Last.fm is down and your scrobble gets lost, or Last.fm changed their APIs and Last.fm Scrobbler extension for Chrome didn't catch up yet, etc. The main point is: sometimes you have listened to a track but haven't scrobbled it for some reason. Later on, when all is well and the extension is working, and you found the song as an individual track with the right length (rather than mixtape's), you just want to add this track to your library, but not necessarily listen to the whole track, or even just 240 seconds of it. That's when this option comes in handy - just 30 seconds and the track is scrobbled, and then you decide if you want to listen it to the end or just move on.

Another situation that I've encountered is when you come a cross a blog post with a few dozens of tracks, and you don't have time to listen to all of them. Yet, you want to "taste" them and add them to your Last.fm library. That's when I use my 30-seconds patch, too (you can find the patch in a linked issue above). 30 seconds is quite enough to understand how a song sounds, especially if you use the "skip forward" option a few times.

Finally, in the ol' good days when Last.fm was actually a radio, 30 seconds was the minimum track length for Last.fm to scrobble it. I believe they still enforce this limitation on scrobbles.

All in all, I believe that 30 seconds is a reasonable timeout to submit a scrobble. And if this value can be customized, this would even be better since different people may like different timeouts. But again, I'm totally fine if you just accept a one-liner patch from me and hard-code the value to 30 seconds/ 1/5 of a song. For me personally this would work perfectly.

@david-sabata Could you please re-open the issue?

**Comment by Paszt** [comment]
I think it's a bad idea to have customisable listening time until scrobble. Last.fm's guidelines say:

>A track should only be scrobbled when the following conditions have been met:

>* The track must be longer than 30 seconds.
>* And the track has been played for at least half its duration, or for 4 minutes (whichever occurs earlier.)

**Comment by fedorg** [comment]
Maybe a "force scrobble" button somewhere in the popup/notification?

**Comment by janbaykara** [comment]
Your usecase does seem to basically be 'let me scrobble the thing', which could be solved with a 'force scrobble' button. I would recommend that above and beyond a shortened scrobble time.

**Comment by anthonypetrov** [comment]
Yes, the "force scrobble" button would work equally well.

**Comment by anthonypetrov** [comment]
On a second thought, I'd still apply my patch to my own copy of the Scrobbler extension then, because this way I save an extra click when scrobbling tracks. So, while useful for some, myself I'd use this button rather rarely.

**Comment by janbaykara** [comment]
@anthonypetrov Fair enough. Thoughts on the quoted LFM guidelines, though?

In any case, the quickest way for your proposed changes to be merged, would be to turn the patch into a PR.

**Comment by anthonypetrov** [comment]
@janbaykara Guidelines are guidelines. They are neither the law nor the rules. If something makes sense (and you can find a few valid use-cases that I've provided above), you can go against the guidelines. Besides, if that was a configurable value, then by default nothing would change for anyone. Only those who need this alternative behavior would tweak that option. So I don't see anything wrong with that.

As for the pull request, yeah, well. I'm unlikely to implement the configuration option myself. I also see that some people oppose the default 30 seconds/ 1/5 of song duration timeout, so my original patch may not work for everyone.

I propose to re-open this issue and keep it open until someone finds time to implement a proper fix.

**Comment by david-sabata** [comment]
Personally, I'd rather play by the guidelines. But I understand your case @anthonypetrov and you're right, that config switch (or value) shouldn't cause any harm.

Our important counter-case is that time before scrobbling is time that our users have to correct incorrectly recognized tracks.

As for configuration, how about a single checkbox in a spirit of "I want to scrobble my tracks ASAP"?
If unchecked (=default), the current timing will apply.

**Comment by ex47** [comment]
> As for configuration, how about a single checkbox in a spirit of "I want to scrobble my tracks ASAP"?
If unchecked (=default), the current timing will apply.

Or a percentage slider with minimal value meaning ASAP.

**Comment by inverse** [comment]
Should we close this? I think following the guidelines is a valid case.

**Comment by alexesprit** [comment]
Probably, yes.

I got an idea some time ago to add a hidden (configurable via console) option to resolve this issue.

**Comment by alexesprit** [comment]
<details>
  <summary>Hidden description</summary>

![image](https://user-images.githubusercontent.com/1119267/76634351-32f99900-6557-11ea-9534-0d4a27596b0b.png)
</details>
