### ISSUE TITLE
[ListenBrainz] Sign in button not working

### ISSUE THREAD

**Issue by WrayOfSunshine** [web-scrobbler/web-scrobbler#4531]
**Describe the bug**
The sign in button for ListenBrainz (not a custom instance) fails.

**How to reproduce**
1. Go to extension options
2. Click on Sign In button for ListenBrainz

**Expected behavior**
This would result in connection.

ListenBrainz: Use https://listenbrainz.org/profile/ [context-menu-0106d5a0.js:15:52893](moz-extension://eebcee41-b5e1-476f-946f-6f13c10b3ec2/assets/context-menu-0106d5a0.js)
ListenBrainz: Failed to get session [context-menu-0106d5a0.js:15:52893](moz-extension://eebcee41-b5e1-476f-946f-6f13c10b3ec2/assets/context-menu-0106d5a0.js)
ListenBrainz: Error while fetching session [context-menu-0106d5a0.js:15:52893](moz-extension://eebcee41-b5e1-476f-946f-6f13c10b3ec2/assets/context-menu-0106d5a0.js)
error-auth

**Environment (please complete the following information)**
-   OS: Linux
-   Browser: Firefox
-   Extension version: 3.5.0

**Additional context**
It -looks- like the issue is a bad URL. I've tried with and without being logged into the scrobbler already. I tried to get debug logs via the provided URL but the above was all the useful information I was able to figure out how to get.

**Comment by szul** [comment]
@dethmourne As a temporary solution you can use the local instance option, setting the URL to "https://api.listenbrainz.org/1/submit-listens" and adding your API token.

**Comment by yayuyokitano** [comment]
I have been in sweden to procure medicines norway has run out of. I’m back tonight, so we can push tomorrow morning I think.

**Comment by yayuyokitano** [comment]
I see 3.6 is out in chrome now, so should work in chrome now

**Comment by catuhana** [comment]
I can confirm that it works on Chrome Store release.

**Comment by UnitR** [comment]
I had a similar issue but with last.fm

For me the cause was my organisation filtering traffic and warning that the website being accessed is classed as Entertainment so I had to essentially verify I am indeed trying to access the website.

I had to manually enter the token URL in my browser (ie https://ws.audioscrobbler.com/2.0/?method=auth.gettoken), bypass the warning screen so the domain was whitelisted temporarily and go back to the Web Scrobbler options page and retry the sign in for last.fm. Everything worked fine afterwards :)

For reference, I am using Firefox Developer Edition 124.0b3 (64-bit)

**Comment by mrkesu** [comment]
Tried on multiple computers, multiple browsers (Edge and Firefox) since last days because I wanted to add scrobbling to Navidrome.

Clicking "Login" and then "Sign in with MusicBrainz" just sends me to the homepage again, without being signed in...
If I click "Create account" I am sent to my musicbrainz profile page (logged in), but if I go back to ListenBrainz I am still not logged in there...

**Comment by catuhana** [comment]
> Tried on multiple computers, multiple browsers (Edge and Firefox) since last week because I wanted to add scrobbling to Navidrome.
> 
> Clicking "Login" and then "Sign in with MusicBrainz" just sends me to the homepage again, without being signed in... If I click "Create account" I am sent to my musicbrainz profile page (logged in), but if I go back to ListenBrainz I am still not logged in there...

I can't reproduce. Are we sure any ad blockers/similar aren't interfering? I can't see any ListenBrainz change that could affect the login too, so I think that's not a Web Scrobbler issue.

**Comment by WrayOfSunshine** [comment]
I'm not sure if it's still an issue. I tried it without ad blockers previously but I haven't used this extension in quite some time at this pointOn Aug 16, 2024, at 09:07, tuhana ***@***.***> wrote:﻿

Tried on multiple computers, multiple browsers (Edge and Firefox) since last week because I wanted to add scrobbling to Navidrome.
Clicking "Login" and then "Sign in with MusicBrainz" just sends me to the homepage again, without being signed in... If I click "Create account" I am sent to my musicbrainz profile page (logged in), but if I go back to ListenBrainz I am still not logged in there...

I can't reproduce. Are we sure any ad blockers/similar aren't interfering? I can't see any ListenBrainz change that could affect the login too, so I think that's not a Web Scrobbler issue.

**Comment by mrkesu** [comment]
> I can't reproduce. Are we sure any ad blockers/similar aren't interfering?

I have adblocking only on my firewall, but I've tried while at work too with the same issue. Just to make sure I tried now over a 5G connection and no extensions enabled (even though I have no adblockers installed) and I still have the same behavior.

What's odd is when I open "Authorized applications" on MusicBrainz.org I can see "Last granted token" time update for "ListenBrainz Prod" every time I try to log in on ListenBrainz.org, even though I'm still not being signed in on ListenBrainz.org

I clicked "Revoke access" to remove it and when I then logged in on ListenBrainz.org I had to authorize it again which went fine and it was added to "Authorized applications" again, but I'm still not logged in on ListenBrainz.org.

**Comment by yayuyokitano** [comment]
Just to have this completely clear, are you having trouble logging into listenbrainz.org the website?

**Comment by mrkesu** [comment]
> Just to have this completely clear, are you having trouble logging into listenbrainz.org the website?

Oh geez, you're right, and this isn't the metabrainz's repo at all!

I must have started replying in the wrong issue amongst all my tabs while I was researching my issue. I'm so sorry for creating unnecessary noise! :face_exhaling:

**Comment by yayuyokitano** [comment]
Ok cool, no worries! Also I realize the original bug here was fixed months ago, and this issue should have been closed, so I will do that

**Comment by Sixfifty** [comment]
I just had this issue, the Log In button form ListenBrainz in webscrobbler took me to the settings page in my account on Firefox and didn't do anything else.

I had to use the Local Instance, with the ListenBrainz API URL method [mentioned earlier](https://github.com/web-scrobbler/web-scrobbler/issues/4531#issuecomment-1956426893). 

Firefox 129 & WebScrobbler 3.9.1

**Comment by mbeko** [comment]
I've just run into this issue as well, exactly like Sixfifty described and seeing the error messages posted by WrayOfSunshine.

I'm on Web Scrobbler 3.22.0 and Firefox 155.0. Using the local instance workaround works.

@yayuyokitano Can you reopen this issue, or should I create a new one?
