### ISSUE TITLE
Cannot edit fields during pause state

### ISSUE THREAD

**Issue by PlaylistsTrance** [web-scrobbler/web-scrobbler#4539]
**Describe the bug**
When a (YouTube) video is paused, the scrobbler won't let you edit the artist/track/album/albumartist fields.

**How to reproduce**
1. Pause a YouTube video that hasn't been scrobbled yet.
2. Try to edit the metadata fields.

**Expected behavior**
The user should be able to modify the fields while the video is paused.

**Screenshots**
N/A

**Debug logs**
N/A

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: 3.6.0

**Additional context**
N/A

**Comment by PlaylistsTrance** [comment]
I assume this was introduced by #4484

**Comment by yayuyokitano** [comment]
Thank you for reporting! PR has been made to fix this. Might take some time to get merged to avoid breaking something else in the process.

**Comment by yayuyokitano** [comment]
3.6.1 is now out on chrome, should have this issue fixed.
