### ISSUE TITLE
Regular updating of Apple Safari Extensions

### ISSUE THREAD

**Issue by mountainash** [web-scrobbler/web-scrobbler#4549]
It appears that the [current CI/CD workflow](https://github.com/web-scrobbler/web-scrobbler/actions/runs/8025462459/workflow) doesn't include releases to the Apple App Store, and as such the Safari Extension is still on release v3.4 of the Web Scrobbler (when [v3.6.1](https://github.com/web-scrobbler/web-scrobbler/releases/tag/v3.6.1) is the latest version).

Would it be possible to update the Safari app closer to the releases for the other platforms?

**Comment by yayuyokitano** [comment]
Apologies for some delay on this.
I've gotten my mac up to date, and done some sanity testing to be satisfied to upload update.
It is currently waiting for apple to review, probably ETA ~24h from how apple usually reviews.

**Comment by yayuyokitano** [comment]
3.6.2 is now out on both macos and ios safari
