### ISSUE TITLE
can't create new bulk edits with the mozilla extension

### ISSUE THREAD

**Issue by noablimi** [web-scrobbler/web-scrobbler#4552]
**Describe the bug**
just got the new update! It seems like the Mozilla extension is not allowing me to do a bulk edit; when I click on the checkmark button, nothing happens. this doesn't happen on the google chrome version. normal edits are working fine.

**How to reproduce**
1. Go to Extension icon
2. Click on the pencil
3. Click on the Regex/Bulk edit mode button
4. Try to apply some bulk edit with the checkmark button

**Expected behavior**
i click on the checkmark button and the bulk edit is applied and it works right after

**Screenshots**
![Screenshot 2024-02-29 130929](https://github.com/web-scrobbler/web-scrobbler/assets/43256327/8039e404-de68-4d23-9b34-0161ddc42f07)

**Debug logs**
N/A

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: Mozilla Firefox
-   Extension version: 3.6.1

**Additional context**
N/A

**Comment by yayuyokitano** [comment]
Thank you for reporting! This has now been fixed and update 3.6.2 has already been pushed with the hotfix.
It is now just pending mozilla approval.

**Comment by yayuyokitano** [comment]
3.6.2 has been approved by mozilla, and is now out.
