### ISSUE TITLE
Double artsit name | YT Music

### ISSUE THREAD

**Issue by Kellen-wq** [web-scrobbler/web-scrobbler#4561]
**Describe the bug**
when scrobbling in youtube music, probably when playlist repeat is enabled, artist names are duplicated
**How to reproduce**
I don't understand how to reproduce it exactly, because I was just listening to music in the background and noticed it for the first time about two days ago
I thought I had to reproduce it that way, but it only worked once out of five tries:
1. enable track list repeat
2. reload page
3. play any playlist, mix, album
4. see double artist name

**Expected behavior**
scrobble without duplicates

**Screenshots**
![image](https://github.com/web-scrobbler/web-scrobbler/assets/76692731/26a73e4a-4c81-4a89-8670-41a0005a7dfa)
I was just listening to one album here and the double names started scrobbling.

![image](https://github.com/web-scrobbler/web-scrobbler/assets/76692731/5540bf5a-8d50-4353-a1df-0879ee9ebca9)
here I was listening to one artist, then through search I turned on an another artist and the names started duplicating

![image](https://github.com/web-scrobbler/web-scrobbler/assets/76692731/1c7d3f06-29b0-4fd4-9f42-e128643f64a9)
then I turned on another track from the main page and the duplication disappeared, then I turned on the album through the search. the first two tracks were fine, and then the duplication started again.
![image](https://github.com/web-scrobbler/web-scrobbler/assets/76692731/6bb27f47-081a-4859-b45a-95cd25dd3ab8)

**Debug logs**
debug mod is enabled now, so far the error has not recurred. i will provide logs when it does.

**Environment (please complete the following information)**
-   OS: Arch Linux, Hyprland
-   Browser: Firefox
-   Extension version: 3.6.1

**Comment by Kellen-wq** [comment]
i got this bug again just listening to music in the background. no errors in the console

`Web Scrobbler: Controller: Song finished processing: {
  "parsed": {
    "track": "りゅーーっときてきゅーーっ!!!",
    "artist": "湊あくあ, 宝鐘マリン, 沙花叉クロヱ, Ninomae Ina'nis, 湊あくあ, 宝鐘マリン, 沙花叉クロヱ, Ninomae Ina'nis",
    "albumArtist": null,
    "album": "りゅーーっときてきゅーーっ!!!",
    "duration": 291,
    "uniqueID": "qATdCqJXLSc",
    "currentTime": 259,
    "isPlaying": true,
    "trackArt": "https://lh3.googleusercontent.com/TOlZwaM4hsE7oub1-aNt_cpNkSxIWhXBzICHf14nRV090YRprUCVfAX_ZaNY64JbEgDKDsDxQEZPP0kAsg",
    "isPodcast": false,
    "originUrl": "https://music.youtube.com/watch?v=qATdCqJXLSc&list=OLAK5uy_ktTEMvObjxjtqRZfv_T0cbFq9gnoBKNFI",
    "scrobblingDisallowedReason": null
  },
  "processed": {
    "track": "りゅーーっときてきゅーーっ!!!",
    "artist": "湊あくあ, 宝鐘マリン, 沙花叉クロヱ, Ninomae Ina'nis, 湊あくあ, 宝鐘マリン, 沙花叉クロヱ, Ninomae Ina'nis",
    "albumArtist": null,
    "album": "りゅーーっときてきゅーーっ!!!",
    "duration": 260
  },
  "noRegex": {
    "track": "りゅーーっときてきゅーーっ!!!",
    "artist": "湊あくあ, 宝鐘マリン, 沙花叉クロヱ, Ninomae Ina'nis, 湊あくあ, 宝鐘マリン, 沙花叉クロヱ, Ninomae Ina'nis",
    "albumArtist": null,
    "album": "りゅーーっときてきゅーーっ!!!",
    "duration": null
  },
  "flags": {
    "isScrobbled": false,
    "isCorrectedByUser": false,
    "isRegexEditedByUser": {
      "track": false,
      "artist": false,
      "album": false,
      "albumArtist": false
    },
    "isAlbumFetched": false,
    "isValid": true,
    "isMarkedAsPlaying": false,
    "isSkipped": false,
    "isReplaying": true,
    "hasBlockedTag": false,
    "isLovedInService": null,
    "finishedProcessing": true
  },
  "metadata": {
    "startTimestamp": 1709761398,
    "label": "YouTube Music"
  },
  "connector": {
    "label": "YouTube Music",
    "matches": [
      "*://music.youtube.com/*"
    ],
    "js": "youtube-music.js",
    "id": "youtube-music"
  }
}`


and after it all the tracks go with double the artist's name.
![image](https://github.com/web-scrobbler/web-scrobbler/assets/76692731/fbe85a83-c9b9-40fb-98e7-76a5d5cab42e)

**Comment by josineudo-arruda** [comment]
I had the same trouble with my scrobbles, where the artist name is saving as two. (for example: Ariana Grande, Ariana Grande)

![imagem_2024-03-11_195346529](https://github.com/web-scrobbler/web-scrobbler/assets/96135176/c49d4798-9464-4099-8e8b-df13c49eafe2)

**Comment by yayuyokitano** [comment]
Thank you for reporting, PR #4587 has been created which will fix this once merged and pushed to production.
