### ISSUE TITLE
Track gets loved when I minimize it

### ISSUE THREAD

**Issue by m-yordanov** [web-scrobbler/web-scrobbler#4564]
**Describe the bug**
Every time I minimize a music video(like when i search another video while this one is running), I get a notification that my track is added to my "Loved tracks" list. When I return the video to take up the whole page again, it unloves the track (and I get a notification for it). 

**How to reproduce**
1. Go to youtube.com
2. Play any song.
3. Click on the youtube logo so that you open the home page while the song is running as a small window.
4. You should get a notification that you loved the track that is running.
5. You can return to the video in full view again to unlove it

**Environment**
Browser: Chrome
OS: Windows 10
Extension version: 3.6.2

**Comment by ngviner** [comment]
Same issue on MS Edge
Windows 11
Edge 122.0.2365.80

**Comment by yayuyokitano** [comment]
Thank you for reporting! Have now created PR #4586 that should stop this issue once it is merged and pushed to production.
