### ISSUE TITLE
Songs get Loved when you save them on Spotify

### ISSUE THREAD

**Issue by ile1** [web-scrobbler/web-scrobbler#4565]
**Describe the bug**
If you save a track on spotify, it makes it loved on last.fm. 

**How to reproduce**
1. Go to open.spotify.com
2. play a track
3. save it
4. see track gets hearted in the extension

**Expected behavior**
Saving a song on spotify isn't a song I love, it's just a song I want to hear again.

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by yayuyokitano** [comment]
You can disable this in the settings globally or on a per connector basis using the “Love/unlove tracks through players” option.
