### ISSUE TITLE
[YouTube Music] Scrobbling broken on new UI for small windows.

### ISSUE THREAD

**Issue by itsSanalog** [web-scrobbler/web-scrobbler#4571]
**Describe the bug**
YouTube Music has a new minimal UI when running on a browser window that's small, completely changing the title and artist layout and removing the album information, preventing anything from being scrobbled.

**How to reproduce**
1. Go to music.youtube.com
2. Play any song
3. Resize window until the UI changes to a 'mobile music player' style (in my case, it appeared when window width <616px).

**Screenshots**
![example of the new UI](https://i.imgur.com/k7wSvJM.png)

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: 3.6.2

**Comment by TheColorman** [comment]
+1, I use a small window to only show album art, and it's very annoying having to manually input every single artist. Out of curiosity, is there a way to grab the now playing information from Chrome itself? The built-in player control always shows the correct song title and artist:
![image](https://github.com/web-scrobbler/web-scrobbler/assets/18369995/c6663466-a8f0-4565-97fd-cdb93826ca30)

If it's possible to use this it could get much easier to standardise across different platforms.

**Comment by yayuyokitano** [comment]
Thank you for reporting, and thank you @TheColorman for helpful input.
PR #4587 has been created, reworking entire ytm connector using the mediasession api that chrome now playing information uses.
