### ISSUE TITLE
Service Error

### ISSUE THREAD

**Issue by PureShiroi** [web-scrobbler/web-scrobbler#4573]
It says it's trying to scrobble/find the song i'm listening to but then it pops up with a yellow ! saying "Service Error"

**How to reproduce**
1. Go To; Youtubemusic
3. Click on Any song
4. Wait
5. Scrobble extension will come up with yellow !

I was taking a break from listening to music and it was working fine before that break i started listening to music and noticed the error because i like comparing how much music i listen to compared to my friends and i was trying to check how many times i had listened to a certain song and noticed it

![scrobble](https://github.com/web-scrobbler/web-scrobbler/assets/162758899/dc9f4978-3ea6-484a-965b-1108c3740b8a)

-   OS: Windows
-   Browser: Chrome
-   Extension version: v3.6.2

**Comment by ChrisGuenther333** [comment]
I'm having the same issue, same specs

**Comment by rf7033nk** [comment]
This is also happening to me, it was working fine earlier then the error code started maybe 2 hours ago. Same version, but I'm using Firefox on Windows 10

**Comment by michaelfaith** [comment]
Same issue here. Tried signing out and back in, but still happening

**Comment by yayuyokitano** [comment]
Btw a reminder that we added scrobble cache in 3.6.0. Once the outage is over and scrobbling is reliable again, you can simply go to setting and rescrobble all the failed scrobbles under "errored scrobbles"

**Comment by rf7033nk** [comment]
> Btw a reminder that we added scrobble cache in 3.6.0. Once the outage is over and scrobbling is reliable again, you can simply go to setting and rescrobble all the failed scrobbles under "errored scrobbles"

Thank you!
