### ISSUE TITLE
Don't love track on last.fm after user liked it on YouTube (probably on other platforms as well)

### ISSUE THREAD

**Issue by havryliuk** [web-scrobbler/web-scrobbler#4599]
Not long ago, I noticed that when I like a video that is scrobbling from YouTube, it is marked as Loved on last.fm.
Though I kind of understand why it was implemented, I still don't believe this is the right thing, for me at least.
For example, I can like the song on YouTube but don't want to add it to liked on last.fm. I may just like the video but not the song.

In order to keep my loved tracks clean on last.fm, I have to manually unlike the tracks loved in this manner.

Still not sure what the feedback is from other users. Maybe it is possible to make this feature configurable.

**Comment by yayuyokitano** [comment]
You can disable this globally or per connector in the settings using the “Love/Unlove tracks through players” option

**Comment by havryliuk** [comment]
> You can disable this globally or per connector in the settings using the “Love/Unlove tracks through players” option

Thank you! Closing the issue ;)

**Comment by StarterX4** [comment]
It annoyed me as well when I noticed I've got a ton of past YT vids added as liked "songs" on last.fm.

IMHO this option should be _disabled_ by default.

**Comment by havryliuk** [comment]
> It annoyed me as well when I noticed I've got a ton of past YT vids added as liked "songs" on last.fm.
> 
> IMHO this option should be _disabled_ by default.

Can't agree more.
