### ISSUE TITLE
Soundcloud tracks being flagged as "private" by the extension if they're uploaded, reposted, or in a playlist by the user's account

### ISSUE THREAD

**Issue by AquaDoesStuff** [web-scrobbler/web-scrobbler#4604]
A couple days ago when listening to music, either when from my own Soundcloud account or from a playlist marked as private, I've noticed that Web Scrobbler doesn't scrobble them anymore unless I open the extension and click "scrobble anyway". It's a bit weird that it happens with public tracks uploaded on my Soundcloud account, or with public tracks in private playlists, and it goes away and scrobbles if I press the button (at least until the next track that fits under the conditions or when the track is replayed), but its a bit annoying. Through some further experimenting I realized that it happens with reposted tracks as well, and probably isn't even exclusively related to the playlist being private but only due to the playlist being owned by the account logged in. Google Chrome. Extension version 3.7.0.

![image](https://github.com/web-scrobbler/web-scrobbler/assets/77502880/2ddec4c7-50fa-4dac-af46-02a9fd2ca330)
Public track being played through my own playlist

**Comment by AwesomeAwesomeAwesome** [comment]
I'm getting the same for **all** of Soundcloud, but only on Firefox. Chrome scrobbles without an issue.

**Comment by harshpow** [comment]
just started happening to me

**Comment by AwesomeAwesomeAwesome** [comment]
Further insight: I'm getting this on SC feed past a few days scrolling (https://soundcloud.com/feed)
