### ISSUE TITLE
bandcamp tracks not scrobbling

### ISSUE THREAD

**Issue by McFaceman** [web-scrobbler/web-scrobbler#4624]
Tracks played on Bandcamp will not be detected. Instead of a music note, the extension icon is the WS logo. Apparently this means that the connector code needs updating.

1. Go to any album or track on Bandcamp.
2. Play track.
3. Check web scrobbler icon.

Tracks are supposed to be detected and scrobbled.

![image](https://github.com/web-scrobbler/web-scrobbler/assets/165608801/0d468daa-0e54-4d81-9436-691ec055aae8)
![image](https://github.com/web-scrobbler/web-scrobbler/assets/165608801/568c5e44-a497-482d-806f-377325ebcbcd)

**Environment (please complete the following information)**
-   OS: iOS
-   Browser: Safari
-   Extension version: (e.g. v3.7.0)

**Comment by inverse** [comment]
We will need to add support to the mobile player to get this working.

**Comment by keerah** [comment]
There's also a problem with the updated Bandcamp discovery page. Tracks are not scrobbled from there, but are scrobbled fine from the ordinary album pages and the feed page.
