### ISSUE TITLE
WeAreOne.fm - Connector Request

### ISSUE THREAD

**Issue by calvinthefreak** [web-scrobbler/web-scrobbler#4663]
**Provide information about website**
A short description of the website, sample URLs, (demo) accounts for testing purposes. If (demo) accounts are not for public use, you can mail them to the project developers.

https://weareone.fm/

**Additional context**
Add any other context or screenshots about the request here.

There are multiple radiostations, about 8. If you click on the colored buttons on the side, the Player will be tuned in to the station that you want.
![image](https://github.com/web-scrobbler/web-scrobbler/assets/5560381/93006dbc-8dbb-4394-a41f-7e825ec8da1a)

You can see the current Song over here, I've seen that you can get the data from the official API. But I am to stupid to program the connector.
Artist: ``document.getElementById("stream-tracklist").children[0].children[0].children[1].children[0].innerText.split("\n")[0]``
Track: ``document.getElementById("stream-tracklist").children[0].children[0].children[1].children[0].innerText.split("\n")[1]``
![image](https://github.com/web-scrobbler/web-scrobbler/assets/5560381/b30423cf-45a4-453f-8f63-f504b20316df)

The only way to get the Info when the player is playing is: ``document.getElementsByClassName("fa-pause-circle").length`` -> 1=playing.

it would be great if this could be added to the Scrobbler, since I like to listen to the Music, and want to know the songs that did run, while I'd tune in to that radio.

Best regards,
Calvin

**Comment by calvinthefreak** [comment]
And to Add: Mobile and Desktop Dom are the Same.

**Comment by inverse** [comment]
Will be in the next relase
