### ISSUE TITLE
Bandcamp not scrobbling on Firefox

### ISSUE THREAD

**Issue by mad-bank** [web-scrobbler/web-scrobbler#4752]
Scrobbler is not working for Bandcamp. It says "play some music to get started" even when music is playing.

**How to reproduce:**
Go to Bandcamp
Play a song
Click Web Scrobbler extension icon for error message.

**Expected behavior**
The extension scrobbles from Bandcamp while music is playing.

**Screenshots**
<img width="601" alt="Screen Shot 2024-06-11 at 11 06 23 AM" src="https://github.com/web-scrobbler/web-scrobbler/assets/116916794/e2549f63-2a63-4e30-a91c-551f4fa982d8">

**Environment**
-   OS: Mac
-   Browser: Firefox 126.0.1
-   Extension version: 3.8.0

**Additional context**
This is a new issue that only started a couple weeks ago.

**Comment by mad-bank** [comment]
Sure thing, thanks for responding quickly.

https://bandcamp.com/discover/punk

**Comment by mad-bank** [comment]
Looks like it works fine when I listen to an album on the album's actual
page. Sorry for the trouble! Would be cool if I could scrobble on the
discover page but fine if not too

**Comment by inverse** [comment]
Ohh they've revamped this page! Yeah looks like we'll need to support this.

**Comment by mad-bank** [comment]
Cool, glad I could point it out!

**Comment by inverse** [comment]
Will be supported in the next release!
