### ISSUE TITLE
New connector -myTuner Radio

### ISSUE THREAD

**Issue by thomwim** [web-scrobbler/web-scrobbler#4788]
**Provide information about website**
myTuner Radio is an online streaming website with thousands of radio stations.

**Additional context**
Here is a sample radio station: https://mytuner-radio.com/radio/kola-999-fm-409122/

The song title and artist name will often appear in the "Now Playing" section, while recently played tracks appear in the Playlist.

**Comment by inverse** [comment]
Supported in #4825 and will be in the next release!
