### ISSUE TITLE
An option to allow Chrome notifications to display for the duration of the song?

### ISSUE THREAD

**Issue by cfye14** [web-scrobbler/web-scrobbler#480]

**Comment by janbaykara** [comment]
Is this necessary, now that there is a working pageAction popup?

**Comment by i1abnrk** [comment]
A wait/dismiss function like this would also help me when copy-pasting non-English songs. Currently, I can only copy-paste artist OR song because textbox reverts to default when lost focus to copy the second datum.

**Comment by inverse** [comment]
@cfye14 is this still wanted?

**Comment by i1abnrk** [comment]
I haven't been using desktop browser for some time.
