### ISSUE TITLE
Radio Free Fedi

### ISSUE THREAD

**Issue by candideu** [web-scrobbler/web-scrobbler#4808]
**Provide information about website**
radio free fedi is consent, agency and artist celebrating community radio from the Fediverse. It features music, spoken word, and programming from Fediverse artists.

https://radiofreefedi.net/

**Comment by limebar** [comment]
duplicate of #4046 ?

**Comment by candideu** [comment]
@limebar Weird, I could have sworn I didn't find any existing posts in my search. Closing.
