### ISSUE TITLE
Web Scrobbler doesn't scrobbler music from Spotify.

### ISSUE THREAD

**Issue by Maxim19902501** [web-scrobbler/web-scrobbler#4849]
Web Scrobbler doesn't scrobbler music from Spotify. This problem started today, Restarts and reboots doesn't work. Please fix this bug.
Update: Web Scrobbler is scrobbling music from YouTube now, but it doesn't scrobbler from Spotify so far. PLEASE FIX THIS BUG

**Comment by socialuhs** [comment]
Yes, please. Thank God, thought it was just me. I have tried reconnecting and removing then reinstalling the extension, but nothing worked.

**Comment by Maxim19902501** [comment]
> Yes, please. Thank God, thought it was just me. I have tried reconnecting and removing then reinstalling the extension, but nothing worked.

That's what i'm saying, the same problem!

**Comment by Jenjicu** [comment]
I agree, the same problem, although everything worked a couple of hours ago

**Comment by 0edit** [comment]
Yep same here. Having the same problem on Chrome. Bandcamp and other sites work fine.

**Comment by BTSPHCHART** [comment]
Same here please fix this asap.

**Comment by rgoudie** [comment]
Same issue for me using the Chrome browser on Windows 10.

**Comment by futaride** [comment]
Same issue on Firefox. Worked fine last night

**Comment by BlastkinS** [comment]
Same here, on Opera. I think this issue needs a connector tag.

**Comment by Noel2107** [comment]
so it isn't just me thank god

**Comment by hans-juergen** [comment]
Probably the layout of the web player changed somehow. The mic icon for lyrics might be new or back due to their extended limit for free users and lyrics.
![image](https://github.com/user-attachments/assets/3a334fcb-164f-416b-9dd6-ea3929a4731f)

**Comment by socialuhs** [comment]
> Probably the layout of the web player changed somehow. The mic icon for lyrics might be new or back due to their extended limit for free users and lyrics. ![image](https://private-user-images.githubusercontent.com/4970867/353785859-3a334fcb-164f-416b-9dd6-ea3929a4731f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjE3MDMsIm5iZiI6MTcyMjQyMTQwMywicGF0aCI6Ii80OTcwODY3LzM1Mzc4NTg1OS0zYTMzNGZjYi0xNjRmLTQxNmItOWRkNi1lYTM5MjlhNDczMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTAyMzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTMwMmEzNTViYjQyMGEzN2RjMWJiMjNiMTA4ZTQyM2VkZDVhYTJmYmQxMzhlM2YyMGZiOWY5MTMyNGYyZmE3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K9FbdAMEfStpJEPrtk_R9N6S6D-otD2nIuoQlXN8uD8)

the lyrics icon has been there for a long while now. Even then, why would that affect the scrobbler though?

**Comment by yayuyokitano** [comment]
A wrapper div was added that actually didnt change the visible layout of the site but regardless broke the extension. Fix has been pushed to main and a hotfix will be released shortly. Chrome update will probably release while I am asleep. Unfortunately, firefox and edge reviews take time and you should expect the release to take a few days.

**Comment by Maxim19902501** [comment]
> A wrapper div was added that actually didnt change the visible layout of the site but regardless broke the extension. Fix has been pushed to main and a hotfix will be released shortly. Chrome update will probably release while I am asleep. Unfortunately, firefox and edge reviews take time and you should expect the release to take a few days.

ok thanks we will be waiting

**Comment by yayuyokitano** [comment]
Chrome web store version has been updated to newest 3.9.1, which should see this issue fixed. Firefox, edge, safari remain unupdated for now.

**Comment by rgoudie** [comment]
I have the new Chrome version of the extension and can confirm that scrobbling has returned. Thank you.

**Comment by Maxim19902501** [comment]
> I have the new Chrome version of the extension and can confirm that scrobbling has returned. Thank you.

Yes, i can confirm it too. Thanks very much!!!! I can scrobble from Spotify again!!!!!!!!

**Comment by yayuyokitano** [comment]
Firefox 3.9.1 should also be out now!

**Comment by 9jS2PL5T** [comment]
3.10.0 does not work on Firefox 139.0.04 for me.

**Comment by 9jS2PL5T** [comment]
Workaround:
https://github.com/web-scrobbler/web-scrobbler/issues/5452#issuecomment-3055983644

**Comment by phoemixoo** [comment]
WS is unable to identify the track when I scrobble from Spotify Web Player on Firefox ver. 147.0 . It finds the track title and album title but not the artist.
