### ISSUE TITLE
Web scrobbler doesn't work on edge

### ISSUE THREAD

**Issue by Lulu-894** [web-scrobbler/web-scrobbler#4856]
**Provide information about website**
A short description of the website, sample URLs, (demo) accounts for testing purposes. If (demo) accounts are not for public use, you can mail them to the project developers.

**Additional context**
Add any other context or screenshots about the request here.

**Comment by yayuyokitano** [comment]
Duplicate of #4849 please see that issue for updates. The fix has already been pushed, just pending approval from edge store.
