### ISSUE TITLE
web scrobbler not working on nightwave plaza - plaza.one

### ISSUE THREAD

**Issue by anna33210** [web-scrobbler/web-scrobbler#4899]
web scrobbler was working a while ago on plaza.one, but now the icon for web scrobbler says:

"In most cases this means the site has changed somehow. The change does not have to be visible to user, but means a lot to the extension. The connector code for this specific website needs to be updated. You can navigate to the list of issues and see if this website is already reported. If it is not, you can submit a new issue describing what's wrong, what's expected behavior and what's happening instead."

- windows 10
- google chrome
- mozilla firefox
- version 3.9.1

**Comment by jbwharris** [comment]
This one does seem like it's working again and can probably be closed.

**Comment by anus42** [comment]
Seems not working for me now again.
ubuntu 24.04 LTS
firefox 133.0
brave 1.73.97 based on Chromium 133.0.6778.108

**Comment by anus42** [comment]
Seems to not working again, ubuntu 24.04lts, firefox 133.0

**Comment by jbwharris** [comment]
@anus42 Not really a fix for this site, but I do have Nightwave Plaza in [ScrobbleRadio](https://scrobblerad.io) that will fill the gap.
