### ISSUE TITLE
Text list of Supported Websites in domain (or hosts) format

### ISSUE THREAD

**Issue by realAzazello** [web-scrobbler/web-scrobbler#4903]
With the growing list of supported websites - which will continue to evolve - it would be useful to have a straight, simple textual list of them in domain format. e.g. yaymusic**.com**

A major use-case is to allow-list them in a hosts file or content blocker.

I don't know and haven't found if one of the sourcefiles has that structure; and a search of Issues doesn't pull up this kind of request before.

**Comment by inverse** [comment]
What format would work best for this? currently on release we publish a list of connectors which is included onto the website.

See: https://raw.githubusercontent.com/web-scrobbler/website-resources/master/resources/connectors.json

What would the format you require need to look like?

**Comment by realAzazello** [comment]
I feel a hosts-file format would be best---

1.2.3.4 abc.zyx
5.6.7.8 uvw.fde

**Comment by inverse** [comment]
That could work but how should we handle cases where the matches are defined as things like

```
*://*.wdr.de/radio/*
```
Would `wdr.de` be fine?


```
*://music.amazon.*/*
*://www.amazon.*/gp/dmusic/cloudplayer/*
```

For these it could be any tld :/

**Comment by realAzazello** [comment]
Very interesting cases!

Yes, the root domains are all that's needed.

Remind that hosts-file format i.e. root domains should be sufficient. Content blockers already presume a barebones list of domains should be blocked. If someone wants to use fuller paths, they'll have to make custom blocking filters.

As for the TLD wildcards, hmm... Perhaps for those cases, actually label as ".tld" (".TLD"): useful because it quickly flags that those'll need to be manually modified.

e.g. I already use a hosts file manager that can allowlist domains even on the TLD.
I would also convert some TLDs to ".com" or whatever, based on my specific usage of the site.

>IF possible, the addition of comment lines (# МТС Музыка) would be useful data.

**Comment by inverse** [comment]
Started work in https://github.com/web-scrobbler/website-resources/pull/19

Some edge cases will need to be worked out.

**Comment by inverse** [comment]
@realAzazello how does the output look in this file

https://github.com/web-scrobbler/website-resources/blob/5c42e2315afed8083f29ba9463b1a3bbeebbcaa5/resources/hostfile.txt

**Comment by realAzazello** [comment]
Fab-U-lous! Primo! Just what's needed, Thank you!

I can only assume the service headings are correct, haha. And there are a couple of duplicated lines, but those will be ignore by content blockers.

Let us know which final version we can use, when it's ready. (I'll be using it to allow-list the domains)

**Comment by inverse** [comment]
This is the final URL which will be updated as new versions are made available.

https://raw.githubusercontent.com/web-scrobbler/website-resources/master/resources/hostfile.txt
