### ISSUE TITLE
somafm stopped working ("This website is not supported")

### ISSUE THREAD

**Issue by laroestr** [web-scrobbler/web-scrobbler#4923]
**Describe the bug**
The extension states: This website is not supported.

**How to reproduce**
1. Go to https://somafm.com/

**Expected behavior**

**Screenshots**
![Bildschirmfoto 2024-09-11 um 11 07 42](https://github.com/user-attachments/assets/45f8cfde-281e-4499-9523-8231a315a9fd)

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Safari, Brave, …)
-   Extension version: 3.9.1 

**Additional context**
Other sites (e.g. YouTube Music, KEXP…) are working.

**Comment by inverse** [comment]
It's working for me when I click "Listen Now" on one of the streams which opens a popup with the player element. e.g. https://somafm.com/player/#/now-playing/groovesalad

Does this work for you?

**Comment by laroestr** [comment]
I'm so embarrassed. You're right. As soon as you click on "Listen Now" it works. I hadn't even tried that because Webscrobbler immediately claimed that the website wasn't supported. Perhaps a note here would protect against false bug reports. The behavior is obviously different on most other sites, as there is a player on the homepage.

Thanks for the quick help.
