### ISSUE TITLE
Dash Radio is now Litt Live

### ISSUE THREAD

**Issue by duhnnie** [web-scrobbler/web-scrobbler#4925]
**Provide information about website**
web-scrobbler supports scrobbling from DashRadio, but now that service was renamed to Litt Live (https://littlive.com) so scrobbling looks to not be working now. Please fix it.

**Comment by inverse** [comment]
Should be fixed in the release just pushed https://github.com/web-scrobbler/web-scrobbler/releases/tag/v3.10.0
