### ISSUE TITLE
Website request

### ISSUE THREAD

**Issue by Crazychemist** [web-scrobbler/web-scrobbler#5014]
Hi! I'm an avid Limbik Frequencies user (https://limbikfreq.com/public/limbik_frequencies) but sadly the extension doesn't recognize the livestream.

I've seen many radios using this kind of player.

![image](https://github.com/user-attachments/assets/b8acd3de-3bee-451d-a1ab-2855f4856db7)

I barely know how to program a hangman game, so please, let us scrobble these tracks! :D

**Comment by jbwharris** [comment]
@Crazychemist I built a connector for [BassPistol](https://radio.basspistol.com/public/basspistol) awhile back that works for this site, you just need to add the URL in the connector settings and it does work. I'll see if I can figure out a way to identifying these sites more universally, as they seem to be AzuraCast powered.

**Comment by Crazychemist** [comment]
@jbwharris It works perfectly. Thanks a lot!!!
