### ISSUE TITLE
Opera support / Why is Opera not getting updates?

### ISSUE THREAD

**Issue by david-sabata** [web-scrobbler/web-scrobbler#503]
I stopped submitting updates to Opera extension store a while ago (Q4/2014). This meta-issue is here to explain why is that and to serve as reference point in other issues.

TL;DR: **Chrome is evolving much faster than Opera does. Opera does not support some crucial parts of the extension code and I don't have enough time and energy to maintain compatibility.**

**Update**: Opera extension has been deleted from the store. (28/03/15)

---

Around Q3/2014 I started working on new extension core which will replace the obsolete one. The reason is simple - use new browser capabilities to allow better user experience with the extension. That means stability and some new features. I'm quite a technology fan and I love to check out new stuff as soon as possible :-)

As you may know, beside Chrome is Opera second browser capable of running this extension. Sadly that is less and less true, since Opera doesn't seem to catch on with Chrome extension APIs. Maintaining compatibility is always tough work and I submitted the extension to Opera store with a condition that I would upload the very same version I upload to Chrome store. (There were some complaints from Opera, but it worked, so they made the extension public eventually.)

Last time I checked compatibility was there, around Q3/2014, when I found the extension to be a little broken in Opera. That was when I started the very first big changes. I haven't checked since, but I am getting reports from some users, that the extension simply doesn't work. (Fun fact: as a Fedora user I cannot check the compabitility myself, because there is no Opera package for my system.) Given the small amount of free time I have for development of this extension I decided not to support Opera anymore.

That means that I won't back off with some new stuff just because Opera wouldn't work with it. That I won't check compatibility anymore and that I won't submit any new versions to Opera store.

On the other hand I am happy to merge compatibility pull requests from brave Opera-using contributors and after a confirmation that it works fine I'll upload an update to the store. 

Hope you understand :-)

**Comment by alexesprit** [comment]
Currently, the extension is not available on addons.opera.com; it haven't been passed the review yet. Anyway, it can be installed using Download Chrome Extension addon for Opera.

The latest version is mostly compatible with Opera. Since I'm Opera user, I'll try to keep compatibility in future.
