### ISSUE TITLE
No blocked tags format documentation

### ISSUE THREAD

**Issue by Dunxter** [web-scrobbler/web-scrobbler#5073]
Hi! 

I've seen the blocked tags feature on the Edit Page of the Settings, but I can't find any documentation on how to properly format the .json file in order to block a certain artist.

Could it be this feature is still to be implemented? 

Thank you so much for this scrobbler, keep up the good work!

**Comment by yayuyokitano** [comment]
There is no need to format the JSON manually, you can simply block tags in the UI in the bulk/regex edit menu. The placement is clunky, but it was difficult to find a better place to put it.

<img width="800" alt="Screenshot 2024-12-15 at 00 55 36" src="https://github.com/user-attachments/assets/202f238f-093f-4540-961e-50a1e4e2d3e1" />

**Comment by Dunxter** [comment]
Thank you! However, it seems like my bulk/regex edit menu UI is different. I can't interact with it at all.

![image](https://github.com/user-attachments/assets/8e9f9c19-cce3-4701-9bb8-2b74db724f42)

**Comment by yayuyokitano** [comment]
The menu in question is accessed from the popup while playing a song by pressing the bottom right button. You can then block the currently playing artist/track

**Comment by Dunxter** [comment]
Okay I see, thanks again!

**Comment by CennoxX** [comment]
For anyone who wants to use JSON to block artists, albums, or tracks, here is the structure of the JSON format:

---

The JSON file is a single object where each key is an artist’s name.
All names are **case-sensitive**, and the file must be **valid JSON**.
Each artist maps to an object that can include:

* **`disabled`** *(boolean)* – if `true`, blocks all scrobbles for that artist.
* **`albums`** *(object)* – album titles as keys, set to `true` to block them.
* **`tracks`** *(object)* – track titles as keys, set to `true` to block them.

**Example:**

* All tracks of *Artist One* are blocked.
* All tracks from *Album Title* and the tracks *Track Title 1* and *Track Title 2* of *Artist Two* are blocked.
* No tracks or albums of *Artist Three* are blocked.

```json
{
  "Artist One": {
    "tracks": {},
    "albums": {},
    "disabled": true
  },
  "Artist Two": {
    "albums": {
      "Album Title": true
    },
    "tracks": {
      "Track Title 1": true,
      "Track Title 2": true
    }
  },
  "Artist Three": {
    "tracks": {},
    "albums": {}
  }
}
```
