### ISSUE TITLE
Idea - Snooze: Don't scrobble for [TIME_PERIOD]

### ISSUE THREAD

**Issue by janbaykara** [web-scrobbler/web-scrobbler#616]
**_A one-click button to temporarily disable scrobbling (not necessarily the chrome notification messages), when you're listening to things, but you don't want to contaminate your Last.fm scrobble->suggest list.**_
#### E.g. Listening to some study music

When I'm reading/revising/essay writing, I like to listen to movie soundtracks, classical music, and weird ambient music - essentially the kind of music I don't really listen to for pleasure, but as background noise.

However, I recently played my `last.fm/<username>/recommended` playlist, and it was filled with those kind of tracks, which was annoying.

**_So:**_ Have a 'snooze' button that temporarily disables scrobbling, without the ball-ache of disabling the extension and then potentially **forgetting to turn it back on later**.

**Comment by david-sabata** [comment]
:+1: 

I want this too for quite a time, but still haven't found time for it. Ideally right in notifications as a button that allows users to snooze and restore scrobbling.
The playing notifications should show up regardless of the snoozing.

**Comment by david-sabata** [comment]
With the new song info popup we could add a button for disabling scrobbling.

It should reveal few options, like
* just this track
* for next XY minutes
* until this tab is closed
* until browser is started again
* until manually re-enabled

**Comment by janbaykara** [comment]
Somehow I imagined scrobble pausing being a more global setting, using the browser UI button, rather than PageActions. Imo we should leave the page action pop-up for song/site contextual info and settings. Which isn't to say we couldn't have site/song-specfic disabling...

**Comment by PiotrDabr** [comment]
I'd love to see at least an option to disable scrobbling for the video I'm playing. Quite often I watch some news videos and they're scrobbled in a way that channel name is an artist name and video name is a track name. I'm talking about YouTube by the way but I think it doesn't make any difference.

The only working solution for that problem I know is to "fix" artist and track names to " " (a space symbol). That would be awesome for me to see something like "Don't scrobble this video" button.

**Comment by f1u77y** [comment]
@PiotrDabr you can enable "scrobble only music" option

**Comment by alexesprit** [comment]
@PiotrDabr in the current v1.65.0 version you can toggle scrobbling for a certain website (permanently or until current tab is closed) by right-clicking on the icon in the exntensions bar. The next one has a feature to skip (ignore) now playing song.

**Comment by PiotrDabr** [comment]
@alexesprit Awesome! That's exactly what I was looking for.

**Comment by inverse** [comment]
Is this still relevant?

**Comment by PiotrDabrowskey** [comment]
Hi! I'd like to bump this issue as solution proposed by @alexesprit with selecting "disable until tab is closed" does not longer work due to this option missing from the menu. I've already created a separated issue for that problem https://github.com/web-scrobbler/web-scrobbler/issues/2363.

**Comment by alexesprit** [comment]
> Is this still relevant?

We now have 3 of 5 ways to disable scrobbling. Not sure if we need to disable scrobbling for "next XY minutes" and "until browser is started again".

**Comment by inverse** [comment]
Perhaps we need to improve our documentation in general to cover these points. Or provide some onboarding experience.

**Comment by yayuyokitano** [comment]
Is this still a desired feature? It seems like it isn't, and that what discussion is here is not related to the issue anymore. Might be time to close as not planned.

**Comment by yayuyokitano** [comment]
Closing as not planned due to other features added since this issue was created.
