### ISSUE TITLE
Support for Microsoft's new Edge browser in Windows 10?

### ISSUE THREAD

**Issue by hans-juergen** [web-scrobbler/web-scrobbler#678]
I just read that Microsoft intends to support Chrome extensions in their new Edge browser in the future:

http://www.theverge.com/2015/7/30/9072271/microsoft-windows-10-updates

"Speaking to The Verge last week, Microsoft Edge program manager Drew DeBruyne revealed a little more about how extensions will work in Microsoft Edge. Extensions will be javascript-based, and Microsoft is trying to mimic exactly how Chrome extensions work so it's easy for developers to port them across. In the screenshot above you can see how a Pinterest extension is integrated in a similar way to Chrome. "The intention is that there’s not much work to do, or zero work to do," explains DeBruyne. "We’re doing a lot of work to essentially support the same APIs that Chrome does." Extensions will be hosted in the Windows Store alongside regular apps, and developers will be able to sideload them."

Would be cool to finally have a MS browser being able to scrobble, maybe even on mobile devices then.

**Comment by david-sabata** [comment]
Sounds interesting, but that's almost exactly the same I've heard from Opera people. Which turned out to be very minimal support of Chrome APIs and dealing with browser differences.

Let's wait and see what MS comes with. I'm generally open to this, but I need to see implementation details.

**Comment by bes-internal** [comment]
same story with firefox. he will support chrome api too:
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

**Comment by hans-juergen** [comment]
Only one year later Microsoft seems to have implemented the ability to use Chrome extensions in Edge which will be released tomorrow with the big Anniversary update for Windows 10. Some extensions are already available in the Windows 10 Store, most important of course Adblockers.

**Comment by hans-juergen** [comment]
Update: there is a MS developer tool now available in the Windows 10 store to port Chrome extensions to Edge:

http://news.softpedia.com/news/microsoft-launches-app-to-convert-chrome-extensions-to-windows-10-edge-browser-507034.shtml

**Comment by tbenbrahim** [comment]
@hans-juergen, is this a joke? Because when I converted one of my extensions, no less than six API calls resulted in logging an unsupported API. Until Edge supports all APIs, or at least more than 15%, the tool is a waste of time...

**Comment by hans-juergen** [comment]
I don't know if Microsoft is joking by fooling developers with an unsupported API. I am not joking by asking about support for MS Edge, as there are many Last.fm users who cannot use another browser for scrobbling, because they listen to music at work or elsewhere where they are not allowed to install e.g. the Spotify desktop app.

The new Edge version coming with the Windows 10 Fall Creators update is said to be faster than Chrome and Firefox, by the way. Bookmark handling has also been improved. Furthermore Groove Music will no longer offer streaming music in 2018, as they partner with Spotify for that now, so they will probably discontinue their web player, and supporting scrobbling for it will no longer be necessary. Groove Music will still be able to play your local music files library, so developing a scrobbler and/or plugin for that is more important. There already is an UWP app called "Data for Last.fm UWP" which works for Windows 10, but it cannot scrobble automatically, only manually:

https://www.microsoft.com/store/p/data-for-lastfm-uwp/9wzdncrfj8hg?rtc=2

**Comment by hans-juergen** [comment]
By the way, MS Edge will be using the Chromium engine for its next version as well:

https://www.windowscentral.com/hands-new-chromium-powered-version-microsoft-edge

I'm looking forward to finally use some Chrome extensions with it like the Last.fm web scrobbler.

**Comment by alexesprit** [comment]
The extension can be installed from the Chrome Web Store. I loaded the unpacked one, though.

![image](https://user-images.githubusercontent.com/1119267/56744480-49510780-6781-11e9-97b6-a7f13b49f03c.png)

**Comment by hans-juergen** [comment]
Is this a beta version of Edge? In my standard version 44.17763.1.0 from Dec 2018 I still get the popup that I need to download Chrome when I visit the web scrobbler extension page in the Chrome web store.

**Comment by alexesprit** [comment]
It's canary. I downloaded it from https://www.microsoftedgeinsider.com/en-us/download.

**Comment by hans-juergen** [comment]
I see, thanks for replying.

**Comment by alexesprit** [comment]
@hans-juergen Does support for MS Edge also means publishing the extension in their store? MS Edge supports downloading extensions from Chrome Web Store, so the extension supports this browser technically.

**Comment by hans-juergen** [comment]
I don't think it is necessary to have the Web Scrobbler available in the MS Store if you can simply go directly to the Chrome Web Store and install it from there, same as you can go there with Opera and just install it. The special add-on once needed for that is implemented in Opera now, as far as I know.

The current default MS Edge version in Windows 10 is not able yet to install Chrome extensions directly, I checked this a few days ago. But their beta version already is, I think.

By the way, would it be possible to offer a Safari version of Web Scrobbler? The scroblr.fm extension also works for Safari besides Chrome, but does not seem to be developed anymore.

**Comment by alexesprit** [comment]
> By the way, would it be possible to offer a Safari version of Web Scrobbler?

It's requested in #1908.

**Comment by alexesprit** [comment]
I'm closing this one, as MS Edge based on Chromium fully supports this extension.

**Comment by Dugnychon** [comment]
> I don't think it is necessary to have the Web Scrobbler available in the MS Store if you can simply go directly to the Chrome Web Store and install it from there, same as you can go there with Opera and just install it. 

I disagree, with Chromium Edge rolling out on most Windows 10 devices in January and becoming the default Edge, the availability on the MS Store might be more useful. Installing from Chrome Web Store works well in all Edge Chromium versions, but it displays a warning to users. Extension synchronisation should be coming soon, and having the extension available and ready on MS Store might be great!

I hope you'll try to think about it, and that having two stores is not too much hassle.

**Comment by alexesprit** [comment]
@Dugnychon I'm not against adding the extension to MS Store, though it probably will be an issue, if we won't have a way to upload it automatically, as it done for AMO and Chrome Web Store.

> Installing from Chrome Web Store works well in all Edge Chromium versions, but it displays a warning to users.

I'm a MS Edge user for a several months, and I see no warnings, but a tip instead, like "You can install extensions from Chrome Web Store". I'm on Edge Dev, probably there're no warnings in the dev version.

**Comment by hans-juergen** [comment]
Good news that Chromium Edge will be released for everyone in Jan 2020, only four and a half year since I started this request. ;-)

**Comment by alexesprit** [comment]
Tried to register a developer account to publish the extension to MS Edge store, but got a 2201 error. Haven't find a solution. :(

**Comment by alexesprit** [comment]
![image](https://user-images.githubusercontent.com/1119267/83760805-24b2a900-a67e-11ea-88cd-bd143583077d.png)

**Comment by alexesprit** [comment]
Meh, they rejected the extension, and said it doesn't work. Seems like they expect test accounts for scrobble services.

So, the only way to download the extension for MS Edge is Chrome Web Store. :)

![image](https://user-images.githubusercontent.com/1119267/83871431-b2eb6580-a738-11ea-8833-22134352b1f8.png)

**Comment by inverse** [comment]
That's so silly - so they rejected it because they didn't take the time to understand it? 

What kind of help can you provide during the review process?

**Comment by hans-juergen** [comment]
Thanks for trying though.

**Comment by Dugnychon** [comment]
Any way we could help with the review process?

**Comment by alexesprit** [comment]
I'm not sure what we should do to pass the review.

I doubt we should provide test accounts of scrobbling services, or write a documentation how to sign in to Last.fm.

Do we really need to have the extension in MS Marketplace? I have no issues with installing Web Scrobbler from Chrome Web Store.

**Comment by hans-juergen** [comment]
Maybe you should just give them the publicly available links to official explanations what Last.fm is and what it does (as they very likely have no idea). Here are the most important ones:

https://www.last.fm/about

https://cbsi.secure.force.com/lastfm/articles/LastFM/What-do-I-get-for-signing-up?retURL=/lastfm/apex/knowledgehome_lfm&popup=false&categories=LastFM:LastFM_Eng&template=template_lastfm&referer=lastfm.com&data=&cfs=LFM

https://support.last.fm/t/i-can-t-login-what-should-i-do-and-where-can-i-get-help-with-this/162

**Comment by Dugnychon** [comment]
> I'm not sure what we should do to pass the review.
> 
> I doubt we should provide test accounts of scrobbling services, or write a documentation how to sign in to Last.fm.
> 
> Do we really need to have the extension in MS Marketplace? I have no issues with installing Web Scrobbler from Chrome Web Store.

I have no issue neither with installing it through the Chrome Web Store, but having it in the Microsoft Store would allow for extension synchronisation between devices, which is a nice perk.

If you try the review process again, in the "Notes for certification" field, you can put the following instructions, alongside demo Last.Fm credentials. I'll send you privately some test credentials.

Apparently, you also have to [disclose in the description](https://www.last.fm/user/WebScrobblerDmo) that the extension depends on a scrobbling website to work, if it's not already done.

# Notes for certification

## Credentials

Demo credentials for Last.Fm are available in step 2.4.

## Features test

1. Install the extension
    1. Install the extension from the Microsoft Store
    2. When prompted, opt-in or opt-out of our privacy policy
2. Login to Last.Fm 
    1. Go to the extension's option page to login. _Users know they have to login before any scrobbler can work._
    2. Click on the "Accounts" collapsed card to expand it.
    3. Sign-in to the Last.Fm scrobbling services.
        - In this demo, we'll use "Last.Fm" with the provided credentials. The extension works in the same way with other scrobbling providers.
    4. When redirected to the Last.Fm Login page, enter the following test credentials and click "Let me in"
        - Account: WebScrobblerDmo
        - Password: [REDACTED]
    5. If redirect to a "Connect Application" page on Last.Fm, allow the extension to work by clicking "Yes, allow access"
    6. Once you see "Application Authenticated" on Last.fm, you can close the Last.Fm tab.
    - _In the option's extension page, you should now see "You are signed in as WebScrobblerDmo." under Accounts > Last.Fm_
3. Test scrobbling from the extension
    1. Go to [any song on Youtube](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
    2. See that the state of the extension's icon has changed to a green checkmark
        - It means that the scrobbling has been saved to your Last.Fm account. 
4. _(Optional)_ See scrobbled tracks on Last.Fm 
    1. Go on the [demo account Last.Fm page](https://www.last.fm/user/WebScrobblerDmo)
    2. While the song is playing, it should appear as "Scrobbling now"
    3. After the song has played, it should appear in the track history, with a time.

**Comment by alexesprit** [comment]
@Dugnychon thank you a lot for writing this!

Once v3 will be released, these steps should be slighty updated, as v3 comes with a new options UI. This is easy task, though, and I will update all documentation when I'll merge v3 changes to master branch.

**Comment by alexesprit** [comment]
I created a new issue, where I will publish progress regarding publishing the extension to the store.
