### ISSUE TITLE
Add support for streamboxr.com

### ISSUE THREAD

**Issue by andrei-pavel** [web-scrobbler/web-scrobbler#969]
streamboxr.com is a free alternative to cloud music players available at [http://streamboxr.com](http://streamboxr.com). It plays music from your Dropbox stash.

Support should be easy to add.

**Comment by alexesprit** [comment]
streamboxr doesn't provide UI element with track name. There's only file name and artist on the page.

**Comment by ex47** [comment]
> There's only file name and artist on the page.

which we could parse..?

**Comment by alexesprit** [comment]
The file name can be in any format. Or do we need to use some heuristic algorithms to find out what's inside the file name? :)

**Comment by ex47** [comment]
Actually, we already [use](https://github.com/david-sabata/web-scrobbler/blob/a4944bca28edd535a16acbcbfc4c783cbff6b5be/connectors/v2/youtube.js#L87-L110) them :D

**Comment by alexesprit** [comment]
Well, you're right. :D Maybe using of this stuff is a good idea.
But it's should be shared between connectors. Now 4 or 5 connectors have this copypasted code each. But it's another subject for discussion,

**Comment by inverse** [comment]
We should have some sanatisation built into the base connector that can be used and extended by each connector. Similar to how we have made the[ find separator function ](https://github.com/david-sabata/web-scrobbler/blob/master/core/content/connector.js#L407)

**Comment by inverse** [comment]
CLosing as site gone it seems
